import assert from 'node:assert/strict';
import { dayRange, overviewData, percentChange, type ReportEntry } from './adOverview';
const entry: ReportEntry = { id: 'a', name: 'a', currency: 'CNY', budget: 100, report: { source: 'provider_snapshot', stale: true, currency: 'CNY', spend: 6.74, clicks: 3, impressions: 94, daily: [{ date: '2026-09-13', spend: 6.74, clicks: 3, impressions: 94 }] } };
let result = overviewData([entry], 'CNY', '2026-09-12', '2026-09-14');
assert.equal(result.spend, 6.74);
assert.equal(result.daily[0].spend, null, 'missing dates never become zero');
assert.equal(result.complete, false);
assert.equal(result.stale, true);
assert.equal(percentChange(6.74, 5, result.complete), '上期可比数据不足');
assert.equal(overviewData([entry], 'USD', '2026-09-13', '2026-09-13').spend, null);
assert.equal(overviewData([entry], 'CNY', '2026-09-14', '2026-09-14').spend, null, 'snapshot total must not leak into another date');
const zero = { ...entry, report: { ...entry.report!, source: 'provider', stale: false, daily: [{ date: '2026-09-13', spend: 0, clicks: 0, impressions: 0 }] } };
result = overviewData([zero], 'CNY', '2026-09-13', '2026-09-13');
assert.equal(result.spend, 0);
assert.equal(result.complete, true);
assert.equal(percentChange(1, 0, true), '上期可比数据不足');
assert.equal(percentChange(6, 3, true), '较上期 +100.0%');
assert.equal(overviewData([zero, { ...entry, id: 'b', report: undefined, error: 'offline' }], 'CNY', '2026-09-13', '2026-09-13').complete, false);
assert.equal(overviewData([{ ...entry, report: { ...entry.report!, currency: 'USD' } }], 'CNY', '2026-09-13', '2026-09-13').spend, null);
assert.deepEqual(dayRange('', ''), []);
assert.deepEqual(dayRange('2026-09-14', '2026-09-13'), []);
console.log('Ad overview: currency isolation, missing/zero, snapshot date scope and comparison guards passed');
