import assert from 'node:assert/strict';
import { createAssistantDecisionRequestGuard } from './assistantDecisionRequestGuard';

let identity = 'tenantA:user1:token1';
const guard = createAssistantDecisionRequestGuard(() => identity);
const first = guard.begin()!;
assert.equal(guard.begin(), null, 'concurrent save/revoke must not issue a second request');
identity = 'tenantB:user2:token2';
assert.equal(first.current(), false, 'identity changes invalidate a pending response immediately');
guard.reset();
identity = 'tenantA:user1:token1';
guard.reset();
const returned = guard.begin()!;
assert.equal(first.current(), false, 'A -> B -> A cannot revive the first A response');
assert.equal(first.finish(), false, 'a stale completion must not unlock the current request');
assert.equal(guard.begin(), null, 'new request remains locked after stale completion');
assert.equal(returned.finish(), true);
const beforeUnmount = guard.begin()!;
guard.reset();
assert.equal(beforeUnmount.current(), false, 'unmount invalidates pending UI writes');
assert.equal(beforeUnmount.finish(), false);
const afterMount = guard.begin()!;
assert.equal(afterMount.current(), true);
assert.equal(afterMount.finish(), true);
const beforeTokenRotation = guard.begin()!;
identity = 'tenantA:user1:refreshedToken';
assert.equal(beforeTokenRotation.current(), false, 'old token responses must be ignored');
assert.equal(beforeTokenRotation.finish(), true, 'token rotation must not leave the UI permanently locked');
const withNewToken = guard.begin()!;
assert.equal(beforeTokenRotation.finish(), false, 'duplicate completion cannot release a newer lock');
assert.equal(guard.begin(), null);
assert.equal(withNewToken.finish(), true);
console.log('assistant decision request guard tests passed');
