import test from 'node:test';import assert from 'node:assert/strict';import {customerManualTakeoverApi,type CustomerManualTakeoverView} from './customerManualTakeoverApi';
const scope={tenantId:'tenant',channel:'messenger' as const,accountId:'account',nativeAccountId:'native',customerId:'buyer',conversationId:'messenger:native:recipient',accountHash:'actual-authority',handlingMode:'human_needed'};
const hold={holdId:'hold',scope,version:1,ownerUserId:'owner',actorUserId:'owner',startedAt:'2026-10-10T00:00:00Z',expiresAt:'2026-10-10T00:10:00Z',status:'held' as const,releasedAt:null,recordHash:'actual-hash'};
const view:CustomerManualTakeoverView={scope,item:hold,actorUserId:'owner',canRelease:true,active:true,humanHandling:true};
function setup(handler:(url:string,init?:RequestInit)=>Response|Promise<Response>){const f=globalThis.fetch,s=globalThis.localStorage;globalThis.localStorage={getItem:()=> 'test-session'} as unknown as Storage;globalThis.fetch=async(url,init)=>handler(String(url),init);return()=>{globalThis.fetch=f;globalThis.localStorage=s;};}
const response=(v:unknown)=>new Response(JSON.stringify(v),{status:200,headers:{'Content-Type':'application/json'}});
test('read persisted true hold then explicit takeover uses exact version and no client tenant/account/owner',async()=>{const calls:string[]=[];const restore=setup((url,init)=>{calls.push(init?.method||'GET');if(init?.method==='GET')return response(view);assert.deepEqual(JSON.parse(String(init?.body)),{minutes:10,expectedVersion:1});return response({item:{...hold,version:2}});});try{const v=await customerManualTakeoverApi.read('buyer');assert.equal(v.humanHandling,true);assert.equal((await customerManualTakeoverApi.hold(v)).version,2);assert.deepEqual(calls,['GET','POST']);}finally{restore();}});
test('explicit release retains real owner and frozen scope; it does not auto switch human handling',async()=>{const restore=setup((url,init)=>{assert.ok(url.endsWith('/manual-active/release'));assert.deepEqual(JSON.parse(String(init?.body)),{expectedVersion:1});return response({item:{...hold,version:2,status:'released',releasedAt:'2026-10-10T00:01:00Z'}});});try{assert.equal((await customerManualTakeoverApi.release(view)).scope.handlingMode,'human_needed');}finally{restore();}});
test('foreign customer/account and replaced login receipts rejected with no automatic retry',async()=>{let token='first',calls=0;const restore=setup(()=>{calls++;return response({...view,scope:{...scope,customerId:'foreign'}});});globalThis.localStorage={getItem:()=>token} as unknown as Storage;try{await assert.rejects(()=>customerManualTakeoverApi.read('buyer'),/身份或状态缺失/);globalThis.fetch=async()=>{calls++;token='second';return response(view);};await assert.rejects(()=>customerManualTakeoverApi.read('buyer'),/登录身份已变化/);assert.equal(calls,2);}finally{restore();}});
test('network unknown release never becomes fake success or automatic resend',async()=>{let calls=0;const restore=setup(()=>{calls++;throw Error('network unknown');});try{await assert.rejects(()=>customerManualTakeoverApi.release(view),/network unknown/);assert.equal(calls,1);}finally{restore();}});
