import {authHeader} from './auth';
import type {CustomerRelationshipAssessment,CustomerRelationshipConfirmation,WeeklyCustomerRelationshipCheck} from '../../shared/contracts/customerRelationshipEvidence';
export interface RelationshipBuyerMessage {interactionId:string;body:string;timestamp:number;recordHash:string}
const path=(id:string)=>`/api/overseas/customer-relationships/${encodeURIComponent(id)}`;
async function request(url:string,body?:unknown){const r=await fetch(url,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.message||d.error||'客户关系证据读取失败');return d;}
export interface RelationshipSegmentRevisionReceipt {segment:{id:string;version:number;runId:string;programId:string;packageId:string;packageVersion:number;memberCount:number;excludedCount:number};followupBatchRebuildRequired:true}
export const customerRelationshipEvidenceApi={
 reviseSegment:async(c:WeeklyCustomerRelationshipCheck):Promise<RelationshipSegmentRevisionReceipt>=>{if(!c.programId||!c.packageId||!Number.isSafeInteger(c.packageVersion)||!c.segmentId||!Number.isSafeInteger(c.segmentVersion))throw Error('缺少真实绑定分群版本');const d=await request(`${path(c.customerId)}/segment-revisions`,{programId:c.programId,packageId:c.packageId,packageVersion:c.packageVersion,runId:c.runId,expectedSegmentId:c.segmentId,expectedSegmentVersion:c.segmentVersion});const s=d.segment;if(!s||s.runId!==c.runId||s.programId!==c.programId||s.packageId!==c.packageId||s.packageVersion!==c.packageVersion||typeof s.id!=='string'||s.id===c.segmentId||!Number.isSafeInteger(s.version)||s.version<=c.segmentVersion!||d.followupBatchRebuildRequired!==true)throw Error('未获得范围一致的实际新版分群');return d;},
 read:async(c:WeeklyCustomerRelationshipCheck):Promise<{item:CustomerRelationshipAssessment;buyerMessages:RelationshipBuyerMessage[]}>=>{const d=await request(`${path(c.customerId)}?${new URLSearchParams({weekStart:c.weekStart,weekEnd:c.weekEnd})}`);if(!d.item||d.item.customerId!==c.customerId||d.item.weekStart!==c.weekStart||d.item.weekEnd!==c.weekEnd||!Array.isArray(d.buyerMessages)||!d.buyerMessages.every((m:RelationshipBuyerMessage)=>m&&typeof m.interactionId==='string'&&typeof m.body==='string'&&Number.isFinite(m.timestamp)&&typeof m.recordHash==='string'))throw Error('客户关系证据范围不一致');return d;},
 confirm:async(c:WeeklyCustomerRelationshipCheck,input:{classification:'new_inquiry'|'existing_customer';firstInteractionId:string;relationshipSince:string;reason:string}):Promise<CustomerRelationshipConfirmation>=>{const d=await request(`${path(c.customerId)}/confirmations`,{...input,weekStart:c.weekStart,weekEnd:c.weekEnd});if(!d.item||d.item.customerId!==c.customerId||d.item.weekStart!==c.weekStart||d.item.weekEnd!==c.weekEnd||d.item.classification!==input.classification||d.item.firstInteractionId!==input.firstInteractionId||!d.item.recordHash)throw Error('未获得真实关系确认回执');return d.item;}
};
