import type {WeeklyMaterialEvidenceConfiguration,WeeklyAgentPlanningState} from '../../shared/contracts/socialProgram';
import {getToken} from './auth';
export async function saveMaterialEvidenceConfigurationApi(input:{programId:string;packageId:string;packageVersion:number;slotId:string;expectedPlanningVersion:number;decisions:WeeklyMaterialEvidenceConfiguration['decisions'];expectedHandoffRef:WeeklyMaterialEvidenceConfiguration['handoffRef']}):Promise<WeeklyMaterialEvidenceConfiguration>{
 if(!input.decisions.length||input.decisions.some(decision=>decision.classification!=='human_irreplaceable'||!decision.requirementId.trim()||!decision.reason.trim()||!decision.shotUsage.trim()))throw Error('请逐项明确真实素材原因和镜头用途。');
 const token=getToken();const response=await fetch(`/api/overseas/social-programs/${encodeURIComponent(input.programId)}/operating-packages/${encodeURIComponent(input.packageId)}/material-evidence-configuration`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify({packageVersion:input.packageVersion,slotId:input.slotId,expectedPlanningVersion:input.expectedPlanningVersion,decisions:input.decisions})});const data=await response.json().catch(()=>null);if(!response.ok||!data?.item||data.reanalysisRequired!==true)throw Error(data?.message||'真实素材分类配置未保存，请刷新当前计划后重试。');const c=data.item as WeeklyMaterialEvidenceConfiguration;
 if(c.schemaVersion!=='weekly-material-evidence-configuration.v1'||c.scope?.packageId!==input.packageId||c.scope.packageVersion!==input.packageVersion||c.scope.slotId!==input.slotId||c.programId!==input.programId||!c.configurationId||!c.recordHash||c.version!==input.expectedPlanningVersion||JSON.stringify(c.decisions)!==JSON.stringify(input.decisions)||c.handoffRef?.inspirationId!==input.expectedHandoffRef.inspirationId||c.handoffRef.version!==input.expectedHandoffRef.version||c.handoffRef.recordHash!==input.expectedHandoffRef.recordHash)throw Error('配置保存回执与当前周计划或实际来源不一致。');return c;
}
export function materialConfigurationIdentity(pkg:{programId:string;packageId:string;version:number;agentPlanning?:WeeklyAgentPlanningState}){return JSON.stringify([pkg.programId,pkg.packageId,pkg.version,pkg.agentPlanning?.version??null,pkg.agentPlanning?.directorAnalyses.map(analysis=>[analysis.slotId,analysis.materialEvidenceRequirements])??[]]);}
export function validateMaterialConfigurationPlanningResult(input:{programId:string;packageId:string;packageVersion:number;expectedPlanningVersion:number;configurations:WeeklyMaterialEvidenceConfiguration[]},plan:WeeklyAgentPlanningState):void {
 if(plan.programId!==input.programId||plan.packageId!==input.packageId||plan.packageVersion!==input.packageVersion||!Number.isSafeInteger(plan.version)||plan.version<=input.expectedPlanningVersion||['confirmed','dispatched'].includes(plan.status))throw Error('重新分析回执属于其它来源、版本或已确认计划，请刷新。');
 for(const configuration of input.configurations){const contract=plan.directorAnalyses.find(analysis=>analysis.slotId===configuration.scope.slotId)?.materialEvidenceRequirements;if(contract?.scope.packageId!==input.packageId||contract.scope.packageVersion!==input.packageVersion||contract.configurationRef?.id!==configuration.configurationId||contract.configurationRef.version!==configuration.version||contract.configurationRef.recordHash!==configuration.recordHash||JSON.stringify(contract.handoffRef)!==JSON.stringify(configuration.handoffRef)||configuration.decisions.some(decision=>!contract.items.some(item=>item.requirementId===decision.requirementId&&item.classification==='human_irreplaceable')))throw Error('配置已保存，但重新分析尚未核验使用该配置与实际来源，请刷新后重试。');}
}
