import type {OperatingPlanningResolution} from '../../shared/contracts/socialOperatingDecision';
import type {OwnedSocialAccount} from '../../shared/contracts/socialProgram';
import type {WeeklyProfileUpgrade,WeeklyProfileUpgradeScope} from './weeklyProfileUpgradeApi';
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(!value||typeof value!=='object')return value;return Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical((value as Record<string,unknown>)[key])]));}
export async function nextWeekCreationHash(value:unknown){const bytes=new TextEncoder().encode(JSON.stringify(canonical(value)));const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');}
export interface NewWeekPublication{accountId:string;publishWindow:string;businessProposition:string;cta:string}
export function buildNextWeekProfileInput(args:{scope:WeeklyProfileUpgradeScope;proposal:WeeklyProfileUpgrade;resolution:OperatingPlanningResolution;authority:Record<string,unknown>;accounts:OwnedSocialAccount[];objective:string;successCriteria:string[];timeZone:string;publications:NewWeekPublication[];creationRequestId:string}):Record<string,unknown>{
 const {scope,proposal,resolution:r,authority,accounts}=args,ref=authority.operatingDecisionSnapshotRef as {type?:string;id?:string;version?:number}|undefined;
 if(Object.entries(scope).some(([k,v])=>(proposal as unknown as Record<string,unknown>)[k]!==v)||!proposal.confirmedAt||!proposal.confirmedBy)throw Error('必须使用当前来源周的已确认画像。');
 if(r.snapshot.programId!==scope.programId||r.snapshot.planningWeekStart!==proposal.targetWeekStart||!['ready','degraded'].includes(r.snapshot.status)||r.goal.status!=='ready'||r.capacityPlan.status==='blocked'||!ref||ref.type!=='operating_authority_snapshot'||ref.id!==r.snapshot.snapshotId||ref.version!==r.snapshot.version)throw Error('下一周经营条件尚未齐全，请补充资料或调整计划。');
 if(!args.objective.trim()||!args.successCriteria.length||args.successCriteria.some(x=>!x.trim()))throw Error('请明确下一周经营目标与成功标准。');
 new Intl.DateTimeFormat('en',{timeZone:args.timeZone}).format();
 if(!/^[a-zA-Z0-9_-]{16,160}$/.test(args.creationRequestId))throw Error('创建请求身份无效。');
 const quotas=r.capacityPlan.accountQuotas;
 if(!quotas.length||new Set(quotas.map(q=>q.accountId)).size!==quotas.length||quotas.some(q=>!Number.isSafeInteger(q.publicationQuota)||q.publicationQuota<0||!accounts.some(a=>a.programId===scope.programId&&a.accountId===q.accountId&&a.status==='active')))throw Error('真实账号或发布配额不完整。');
 if(!args.publications.length||args.publications.length>100||args.publications.length!==r.capacityPlan.publicationQuota||quotas.some(q=>args.publications.filter(p=>p.accountId===q.accountId).length!==q.publicationQuota))throw Error('每条新排期必须符合真实账号配额。');
 const end=new Date(Date.parse(proposal.targetWeekStart+'T00:00:00Z')+6*86400000).toISOString().slice(0,10);
 for(const p of args.publications){if(!quotas.some(q=>q.accountId===p.accountId)||!p.businessProposition.trim()||!p.cta.trim()||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?(?:Z|[+-]\d{2}:\d{2})$/.test(p.publishWindow)||!Number.isFinite(Date.parse(p.publishWindow)))throw Error('请为每条视频填写发布账号、主题、行动引导和完整发布时间。');const parts=new Intl.DateTimeFormat('en-CA',{timeZone:args.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(p.publishWindow)),date=['year','month','day'].map(t=>parts.find(x=>x.type===t)?.value).join('-');if(date<proposal.targetWeekStart||date>end)throw Error('发布时间必须位于所选时区的下一周。');}
 return {operatingDecisionSnapshotRef:{type:ref.type,id:ref.id,version:ref.version},weekStart:proposal.targetWeekStart,objective:args.objective.trim(),successCriteria:args.successCriteria.map(x=>x.trim()),originalContentTarget:r.capacityPlan.originalContentQuota,accountPlans:quotas.map(q=>({accountId:q.accountId,publicationCount:q.publicationQuota})),publicationTasks:args.publications.map(p=>({accountId:p.accountId,publishWindow:p.publishWindow,businessProposition:p.businessProposition.trim(),cta:p.cta.trim(),factRefs:r.goal.publicFactRefs})),profileUpgradeTimeZone:args.timeZone,profileUpgradeCreationRequestId:args.creationRequestId,profileUpgradeRef:{id:proposal.id,sourcePackageId:scope.packageId,sourcePackageVersion:scope.packageVersion}};
}
