import assert from 'node:assert/strict';
import { buildReviewInsights } from './reviewInsights';
import type { DigitalEmployeeOverview } from './digitalEmployees';
const data = { tasks: [], review: null, businessSnapshot: null } as unknown as DigitalEmployeeOverview;
assert.deepEqual(buildReviewInsights(data), [], 'missing receipts must not generate advice');
const platforms = [{ platform: 'tiktok', views: 100, status: 'available', accounts: 1 }, { platform: 'youtube', views: 50, status: 'available', accounts: 1 }];
const withPlatforms = { ...data, businessSnapshot: { social: { platformBreakdown: platforms } } } as unknown as DigitalEmployeeOverview;
assert.equal(buildReviewInsights(withPlatforms)[0].category, 'channel');
assert.equal(platforms[0].platform, 'tiktok', 'input order must not be mutated');
platforms[1].views = 100;
assert.match(buildReviewInsights(withPlatforms)[0].title, /并列/);
platforms[1].status = 'pending';
assert.deepEqual(buildReviewInsights(withPlatforms), [], 'unavailable comparison must not be ranked');
platforms[1].status = 'available'; platforms[1].views = NaN;
assert.deepEqual(buildReviewInsights(withPlatforms), [], 'invalid metrics must be excluded');
const task = { id: 'task-1', title: '发布', status: 'waiting_external', blocked_reason: '到期执行', output: { waitState: { requiresAttention: false } } };
const withTask = { ...data, tasks: [task] } as unknown as DigitalEmployeeOverview;
assert.deepEqual(buildReviewInsights(withTask), [], 'normal scheduled waiting must not be called a blocker');
task.status = 'failed';
assert.equal(buildReviewInsights(withTask)[0].action.taskId, 'task-1');
task.status = 'waiting_approval';
assert.deepEqual(buildReviewInsights(withTask), [], 'ordinary approval is not a failed task');
const candidates = { ...data, review: { id: 'r1', status: 'generated', summary: { knowledgeCandidates: ['待核实安装条件', '待核实安装条件'] } } } as unknown as DigitalEmployeeOverview;
assert.equal(buildReviewInsights(candidates).length, 1);
assert.equal(buildReviewInsights(candidates)[0].confidence, 'candidate');
assert.match(buildReviewInsights(candidates)[0].caveat, /未附客户会话/);
console.log('Review evidence tests passed');
