import {test} from 'node:test';import assert from 'node:assert/strict';import {parseSceneReworkAvailability,parseSceneReworkStatus,sceneReworkSelectionAllowed} from './socialSceneReworkApi';
const scope={tenantId:'tenant',taskId:'task',sourceRunId:'source',parentArtifactId:'artifact'};const a={...scope,parentArtifactHash:'a'.repeat(64),cacheHash:'c'.repeat(64),canRequest:true,blockingReasons:[],scenes:[{sceneId:'3',shotId:'3',referenceShotId:null,sourceTiming:null,status:'failed' as const,technicalReceiptId:'r3'},{sceneId:'2',shotId:'2',referenceShotId:null,sourceTiming:null,status:'passed' as const,technicalReceiptId:'r2'}]};
test('scope and unique real receipts required',()=>{assert.equal(parseSceneReworkAvailability(a,scope).scenes.length,2);assert.throws(()=>parseSceneReworkAvailability({...a,tenantId:'other'},scope));assert.throws(()=>parseSceneReworkAvailability({...a,scenes:[a.scenes[0],a.scenes[0]]},scope));});
test('only actual failed selection and all retained scenes passed',()=>{assert.equal(sceneReworkSelectionAllowed(a,['3']),true);assert.equal(sceneReworkSelectionAllowed(a,['2']),false);assert.equal(sceneReworkSelectionAllowed({...a,scenes:[...a.scenes,{sceneId:'4',shotId:'4',referenceShotId:null,sourceTiming:null,status:'review_required',technicalReceiptId:'r4'}]},['3']),false);assert.equal(sceneReworkSelectionAllowed(a,['3','3']),false);});
test('independent run actual operation status cannot drift',()=>{const s={...scope,operationId:'op',executionRunId:'newrun',affectedSceneIds:['3'],jobId:'job',jobStatus:'queued',runStatus:'running',lastError:null};assert.equal(parseSceneReworkStatus(s,scope,'op').jobStatus,'queued');assert.throws(()=>parseSceneReworkStatus({...s,executionRunId:'source'},scope));assert.throws(()=>parseSceneReworkStatus(s,scope,'another'));});
test('explicit submission sends frozen cache hash and exact affected IDs once',async()=>{const previousFetch=globalThis.fetch;const previousStorage=globalThis.localStorage;let calls=0;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null}});globalThis.fetch=async(url,init)=>{calls++;assert.match(String(url),/\/api\/overseas\/starter-198\/social-content\/tasks\/task\/scene-rework$/);assert.equal(init?.method,'POST');assert.deepEqual(JSON.parse(String(init?.body)),{parentArtifactId:'artifact',affectedSceneIds:['3'],expectedCacheHash:'c'.repeat(64),expectedPreviewHash:'d'.repeat(64)});return new Response(JSON.stringify({item:{...scope,operationId:'op',executionRunId:'independent',affectedSceneIds:['3'],jobId:'job',jobStatus:'queued',runStatus:'running',lastError:null}}));};try{const {socialSceneReworkApi}=await import('./socialSceneReworkApi');const preview={type:'scene_rework_admission_preview' as const,version:1 as const,...scope,tenantId:'tenant',affectedSceneIds:['3'],operationId:'op',executionRunId:'independent',cacheHash:'c'.repeat(64),planHash:'e'.repeat(64),localOnly:true,quote:null,gaps:[],previewHash:'d'.repeat(64)};const receipt=await socialSceneReworkApi.submit(scope,a,['3'],preview);assert.equal(receipt.jobStatus,'queued');assert.equal(calls,1);}finally{globalThis.fetch=previousFetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:previousStorage});}});
test('actual output must be new owned file with parent lineage and real QC references',()=>{const base={...scope,operationId:'op',executionRunId:'newrun',affectedSceneIds:['3'],jobId:'job',jobStatus:'succeeded',runStatus:'completed',lastError:null,completedAt:'2026-10-09T00:00:00Z',runCompletedAt:null};const output={artifactId:'newartifact',fileRef:'socialfile:file-id',sha256:'a'.repeat(64),parentArtifactId:'artifact',reviewStatus:'review_required',qualityReceiptIds:['qc'],savedAt:'2026-10-09T00:00:00Z'};assert.equal(parseSceneReworkStatus({...base,output},scope).output?.reviewStatus,'review_required');for(const bad of [{fileRef:'/private/media.mp4'},{parentArtifactId:'other'},{reviewStatus:'approved'},{qualityReceiptIds:[]},{sha256:'unknown'},{artifactId:'artifact'},{savedAt:'invalid'}])assert.throws(()=>parseSceneReworkStatus({...base,output:{...output,...bad}},scope));assert.throws(()=>parseSceneReworkStatus({...base,completedAt:'invalid'},scope));assert.equal(parseSceneReworkStatus({...base,output:null},scope).output,null);});
test('resume is an explicit same job operation with policy hash, no second admission',async()=>{const oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null}});const previous={...scope,operationId:'op',executionRunId:'independent',affectedSceneIds:['3'],jobId:'existingjob',jobStatus:'blocked',runStatus:'running',lastError:'budget'};let calls=0;globalThis.fetch=async(url,init)=>{calls++;assert.match(String(url),/\/scene-rework\/op\/resume$/);assert.deepEqual(JSON.parse(String(init?.body)),{expectedJobId:'existingjob',expectedPolicyHash:'a'.repeat(64)});return new Response(JSON.stringify({item:{...previous,jobStatus:'reconciling',lastError:null}}));};try{const {socialSceneReworkApi}=await import('./socialSceneReworkApi');assert.equal((await socialSceneReworkApi.resume(scope,previous,'a'.repeat(64))).jobId,'existingjob');assert.equal(calls,1);await assert.rejects(()=>socialSceneReworkApi.resume(scope,{...previous,jobStatus:'running'}));assert.equal(calls,1);globalThis.fetch=async()=>new Response(JSON.stringify({item:{...previous,jobId:'otherjob',jobStatus:'queued'}}));await assert.rejects(()=>socialSceneReworkApi.resume(scope,previous));}finally{globalThis.fetch=oldFetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:oldStorage});}});

test('scene checks preserve real typed evidence and reject malformed DTOs',()=>{
 const checks=[{code:'material_mismatch',passed:false,message:'真实素材与画面要求不符'},{code:'timing',passed:true,message:'时长通过'}];
 const withChecks=(value:unknown)=>({...a,scenes:[{...a.scenes[0],checks:value},a.scenes[1]]});
 assert.deepEqual(parseSceneReworkAvailability(withChecks(checks),scope).scenes[0].checks,checks);
 assert.deepEqual(parseSceneReworkAvailability(withChecks([]),scope).scenes[0].checks,[]);
 for(const invalid of [null,{},'failure',[null],[{code:'x',passed:'false',message:'reason'}],[{code:'',passed:false,message:'reason'}],[{code:' ',passed:false,message:'reason'}],[{code:'x',passed:false,message:''}],[{code:'x',passed:false,message:' '}],[{code:'x',passed:false,message:42}]])assert.throws(()=>parseSceneReworkAvailability(withChecks(invalid),scope),/scene_rework_response_invalid/);
});

test('actual production workspace binding requires matching scope and complete unique owned-media scene mappings',()=>{
 const binding={type:'social_production_workspace',version:1,tenantId:scope.tenantId,taskId:scope.taskId,runId:scope.sourceRunId,artifactId:scope.parentArtifactId,artifactContentHash:'d'.repeat(64),projectId:'123456789abcdef',projectVersion:1,specHash:'e'.repeat(64),baselineHash:'f'.repeat(64),recordHash:'b'.repeat(64),sceneMappings:a.scenes.map(scene=>({sceneId:scene.sceneId,slotId:scene.sceneId,mediaFileRef:`socialfile:real-${scene.sceneId}`,mediaSha256:'a'.repeat(64)}))};
 const parse=(value:unknown)=>parseSceneReworkAvailability({...a,productionWorkspaceBinding:value},scope);
 assert.deepEqual(parse(binding).productionWorkspaceBinding,binding);
 assert.equal(parse(null).productionWorkspaceBinding,null);
 for(const bad of [{type:'client_project'},{version:2},{tenantId:'other'},{taskId:'other'},{runId:'other'},{artifactId:'other'},{projectId:'arbitrary-project'},{projectVersion:2},...['artifactContentHash','specHash','baselineHash','recordHash'].map(key=>({[key]:'unverified'})),{sceneMappings:[]},{sceneMappings:[binding.sceneMappings[0]]},{sceneMappings:[binding.sceneMappings[0],binding.sceneMappings[0]]},{sceneMappings:[{...binding.sceneMappings[0],sceneId:'other',slotId:'other'},binding.sceneMappings[1]]},...[{slotId:'slot-3'},{mediaFileRef:'/private/video.mp4'},{mediaSha256:'missing'}].map(change=>({sceneMappings:[{...binding.sceneMappings[0],...change},binding.sceneMappings[1]]}))])assert.throws(()=>parse({...binding,...bad}),/scene_rework_workspace_invalid/);
 for(const gap of [42,{},''])assert.throws(()=>parseSceneReworkAvailability({...a,productionWorkspaceGap:gap},scope),/scene_rework_workspace_invalid/);
 assert.equal(parseSceneReworkAvailability({...a,productionWorkspaceBinding:null,productionWorkspaceGap:'真实生产工作区尚未保存'},scope).productionWorkspaceGap,'真实生产工作区尚未保存');
});
