import test from 'node:test';import assert from 'node:assert/strict';import {parseWeeklyG6Context,parseWeeklyG6Read} from './socialWeeklyG6ReviewApi';
const scope={tenantId:'t',taskId:'task',runId:'run',artifactId:'artifact',programId:'program',packageId:'week',packageVersion:1,publicationTaskId:'pub'};
test('missing, foreign target and invented partial five-check contexts cannot become verified',()=>{assert.throws(()=>parseWeeklyG6Context(null,scope));assert.throws(()=>parseWeeklyG6Context({...scope,packageId:'other'},scope));assert.throws(()=>parseWeeklyG6Context({...scope,checks:[{code:'account',status:'passed',reasons:[],evidenceRefs:[]}]},scope));});
test('readonly absent receipt means absent, never passed or applied',()=>{const actual=parseWeeklyG6Read({item:null,projectionStatus:'not_found',currentSourceVerified:true},scope,'request-id-original-0001');assert.equal(actual.item,null);assert.throws(()=>parseWeeklyG6Read({...actual,projectionStatus:'applied'},scope,'request-id-original-0001'));assert.throws(()=>parseWeeklyG6Read({projectionStatus:'not_found',currentSourceVerified:true},scope,'request-id-original-0001'));});
test('actual HTTP owned MP4 preflight preserves real blocked and unknown evidence through frozen original GET recovery',async()=>{
 const [{default:express},{prepareWeeklyQualityAuditFixture},{createSocialWeeklyG6ReviewService},{createSocialWeeklyG6ReviewRouter},{socialWeeklyG6ReviewApi},{nextWeekCreationHash}]=await Promise.all([import('express'),import('../../server/runtime/weeklyContentQualityAudit.fixture'),import('../../server/starter198/socialWeeklyG6ReviewService'),import('../../server/starter198/socialWeeklyG6ReviewRouter'),import('./socialWeeklyG6ReviewApi'),import('./nextWeekProfilePackage')]);const f=await prepareWeeklyQualityAuditFixture();const scope={tenantId:'t',taskId:String(f.tables.starter_social_content_tasks![0]!.task_id),runId:String(f.context.cache.runId),artifactId:String(f.artifact.artifact_id),programId:f.pkg.programId,packageId:f.pkg.packageId,packageVersion:f.pkg.version,publicationTaskId:f.pkg.socialContentPackage.publicationTasks[0]!.publicationTaskId};const app=express();app.use(express.json());app.use((_req,res,next)=>{res.locals.tenantId='t';res.locals.userId='owner';next();});app.use('/api/overseas/starter-198/social-content/tasks/:taskId/runs/:runId/artifacts/:artifactId/g6-reviews',createSocialWeeklyG6ReviewRouter(createSocialWeeklyG6ReviewService(f.repository)));const server=app.listen(0);await new Promise<void>(r=>server.once('listening',r));const address=server.address();assert(address&&typeof address==='object');const old=globalThis.fetch,calls:string[]=[];Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=> 'g6-actual-http-token'}});globalThis.fetch=(url,init)=>{calls.push(`${init?.method} ${url}`);return old(`http://127.0.0.1:${address.port}${String(url)}`,init);};
 try{const c=await socialWeeklyG6ReviewApi.context(scope);assert.equal(c.metadata?.width,160);assert.equal(c.metadata?.height,180);assert.equal(c.checks.find(x=>x.code==='platform_format')?.status,'blocked');assert.equal(c.checks.find(x=>x.code==='conversion_route')?.status,'unknown');assert.ok(c.gaps.includes('actual_independent_g5_pass_required'));const id='actual-g6-http-original-0001',body={programId:scope.programId,packageId:scope.packageId,packageVersion:scope.packageVersion,publicationTaskId:scope.publicationTaskId,requestId:id,expectedContextHash:c.contextHash},inputHash=await nextWeekCreationHash(body);const actual=await socialWeeklyG6ReviewApi.check(scope,c,id);assert.equal(actual.item?.status,'blocked');assert.equal(actual.item?.receiptId,null);assert.equal(actual.projectionStatus,'applied');assert.equal(actual.currentSourceVerified,true);assert.equal(await nextWeekCreationHash({...body,expectedContextHash:actual.item!.contextHash}),inputHash);calls.length=0;for(let i=0;i<2;i++){const r=await socialWeeklyG6ReviewApi.read(scope,id);assert.equal(r.item?.recordHash,actual.item?.recordHash);assert.equal(r.item?.status,'blocked');assert.equal(r.item?.receiptId,null);}assert.equal(calls.length,2);assert.ok(calls.every(x=>x.startsWith('GET ')));await assert.rejects(socialWeeklyG6ReviewApi.context({...scope,publicationTaskId:'foreign'}));assert.equal(f.tables.starter_social_production_receipts?.filter(r=>r.gate==='G6').length??0,0);
 }finally{globalThis.fetch=old;await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await f.cleanup();}
});
test('actual five-pass HTTP receipt recovers original panel intent by GET without repeat check or publication',async()=>{
 const [{default:express},{prepareWeeklyG6Fixture},{createSocialWeeklyG6ReviewRouter},{socialWeeklyG6ReviewApi},{freezeWeeklyG6Intent,readWeeklyG6Intent,verifyWeeklyG6Intent}]=await Promise.all([import('express'),import('../../server/starter198/socialWeeklyG6ReviewService.fixture'),import('../../server/starter198/socialWeeklyG6ReviewRouter'),import('./socialWeeklyG6ReviewApi'),import('./socialWeeklyG6ReviewIntent')]);const f=await prepareWeeklyG6Fixture(),app=express();app.use(express.json());app.use((_req,res,next)=>{res.locals.tenantId='t';res.locals.userId='owner';next();});app.use('/api/overseas/starter-198/social-content/tasks/:taskId/runs/:runId/artifacts/:artifactId/g6-reviews',createSocialWeeklyG6ReviewRouter(f.service));const server=app.listen(0);await new Promise<void>(r=>server.once('listening',r));const address=server.address();assert(address&&typeof address==='object');const old=globalThis.fetch,calls:string[]=[];Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=> 'actual-g6-positive-token'}});globalThis.fetch=(url,init)=>{calls.push(`${init?.method} ${url}`);return old(`http://127.0.0.1:${address.port}${String(url)}`,init);};
 try{const c=await socialWeeklyG6ReviewApi.context(f.scope);assert.equal(c.metadata?.width,360);assert.equal(c.metadata?.height,640);assert.equal(c.metadata?.framesPerSecond,30);assert.equal(c.checks.length,5);assert.ok(c.checks.every(x=>x.status==='passed'));assert.deepEqual(c.gaps,[]);const rows=new Map<string,string>(),store={getItem:(k:string)=>rows.get(k)??null,setItem:(k:string,v:string)=>{rows.set(k,v);}},key='actual-original-panel-intent',p=await freezeWeeklyG6Intent(store,key,f.scope,c,'actual-positive-http-request-0001'),r=await socialWeeklyG6ReviewApi.check(f.scope,c,p.requestId);await verifyWeeklyG6Intent(f.scope,p,r);assert.equal(r.item?.status,'passed');assert.equal(r.projectionStatus,'applied');assert.ok(r.item?.receiptId);assert.ok(r.item?.receiptHash);const original=readWeeklyG6Intent(store,key);assert(original);await assert.rejects(freezeWeeklyG6Intent(store,key,f.scope,c,'new-second-request-forbidden-0001'));calls.length=0;for(let i=0;i<2;i++){const restored=await socialWeeklyG6ReviewApi.read(f.scope,original.requestId);await verifyWeeklyG6Intent(f.scope,original,restored);assert.equal(restored.item?.recordHash,r.item?.recordHash);assert.equal(restored.item?.receiptId,r.item?.receiptId);}assert.equal(calls.length,2);assert.ok(calls.every(x=>x.startsWith('GET ')));assert.equal(f.tables.starter_social_production_receipts?.filter(x=>x.gate==='G6').length,1);assert.equal(f.tables.social_publication_attempts?.length??0,0);assert.equal(f.artifact.status,'review_required');
 }finally{globalThis.fetch=old;await new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve()));await f.cleanup();}
});
