import {authHeader,getToken} from './auth';
import type {SocialWeeklyG6Scope} from '../../shared/contracts/socialWeeklyG6Review';
import {INSTAGRAM_DELIVERY_TECHNICAL_CHECKS,INSTAGRAM_DELIVERY_CREATIVE_CHECKS,type SocialInstagramDeliveryRead,type InstagramDeliveryObservation,type InstagramDeliveryReviewKind} from '../../shared/contracts/socialInstagramDelivery';
const hash=(x:unknown)=>typeof x==='string'&&/^[a-f0-9]{64}$/.test(x);
export function instagramDeliveryPath(s:SocialWeeklyG6Scope){return `/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/runs/${encodeURIComponent(s.runId)}/artifacts/${encodeURIComponent(s.artifactId)}/instagram-delivery`;}
const target=(s:SocialWeeklyG6Scope)=>({programId:s.programId,packageId:s.packageId,packageVersion:s.packageVersion,publicationTaskId:s.publicationTaskId});
export function instagramDeliveryMediaPath(s:SocialWeeklyG6Scope){return instagramDeliveryPath(s)+'/media?'+new URLSearchParams(Object.entries(target(s)).map(([k,v])=>[k,String(v)]));}
export function parseInstagramDeliveryRead(value:unknown,s:SocialWeeklyG6Scope):SocialInstagramDeliveryRead{
 if(!value||typeof value!=='object')throw Error('包装回执不可读取。');const v=value as SocialInstagramDeliveryRead;
 if(typeof v.currentSourceVerified!=='boolean'||!Array.isArray(v.gaps)||v.gaps.some(x=>typeof x!=='string')||!Array.isArray(v.reviews))throw Error('包装证据不完整。');
 if(v.item===null){if(v.currentSourceVerified||v.previewUrl!==null||v.reviews.length)throw Error('包装来源不一致。');return v;}
 const i=v.item;if(!i||Object.entries(s).some(([k,x])=>i[k as keyof typeof i]!==x)||i.version!==1||!i.deliveryId||!i.requestId||!i.fileRef||!i.fileId||!i.preparedBy||!Number.isFinite(Date.parse(i.preparedAt))||![i.recordHash,i.sourceAuditHash,i.sourceContextHash,i.sourceArtifactHash,i.sourceFileSha256,i.sourceProductionResultHash,i.conversionHash,i.fileSha256].every(hash)||i.metadata?.fileSha256!==i.fileSha256||v.previewUrl!==instagramDeliveryMediaPath(s))throw Error('包装与当前成片或目标周不一致。');
 for(const r of v.reviews){const codes=r.kind==='technical'?INSTAGRAM_DELIVERY_TECHNICAL_CHECKS:r.kind==='creative'?INSTAGRAM_DELIVERY_CREATIVE_CHECKS:null;if(!codes||r.deliveryId!==i.deliveryId||r.deliveryHash!==i.recordHash||r.fileSha256!==i.fileSha256||!hash(r.recordHash)||!r.requestId||!r.actorUserId||r.actorRole!==(r.kind==='technical'?'human_technical_reviewer':'human_director_reviewer')||!Array.isArray(r.checks)||r.checks.length!==codes.length||new Set(r.checks.map(c=>c.code)).size!==codes.length||r.checks.some(c=>!codes.includes(c.code as never)||!['passed','failed','unknown'].includes(c.outcome)||typeof c.observation!=='string')||r.status!==(r.checks.some(c=>c.outcome==='failed')?'failed':r.checks.some(c=>c.outcome==='unknown')?'review_required':'passed'))throw Error('包装审核凭据不一致。');}return v;
}
async function request(s:SocialWeeklyG6Scope,suffix:string,body?:object){const token=getToken();if(!token)throw Error('请登录后读取包装。');const query=new URLSearchParams(Object.entries(target(s)).map(([k,v])=>[k,String(v)]));const r=await fetch(instagramDeliveryPath(s)+suffix+(body?'':'?'+query),{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({...target(s),...body})}:{}),cache:'no-store',redirect:'error'});const v=await r.json();if(getToken()!==token)throw Error('登录身份变化，请重新读取。');if(!r.ok)throw Error(v?.message??'包装结果未知，请查询原请求。');return parseInstagramDeliveryRead(v,s);}
export const socialInstagramDeliveryApi={read:(s:SocialWeeklyG6Scope)=>request(s,''),prepare:(s:SocialWeeklyG6Scope,requestId:string,expectedContextHash:string)=>request(s,'/prepare',{requestId,expectedContextHash}),review:(s:SocialWeeklyG6Scope,requestId:string,expectedDeliveryHash:string,kind:InstagramDeliveryReviewKind,checks:InstagramDeliveryObservation[])=>request(s,'/review',{requestId,expectedDeliveryHash,kind,checks})};
