import {authHeader,getToken} from './auth';
import {WEEKLY_G6_CHECK_CODES,type SocialWeeklyG6Scope,type SocialWeeklyG6Context,type SocialWeeklyG6Check,type SocialWeeklyG6ReviewRead} from '../../shared/contracts/socialWeeklyG6Review';
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v),text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim(),hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(text),instant=(v:unknown)=>text(v)&&/(Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v));
function scope(v:unknown,s:SocialWeeklyG6Scope){if(!object(v)||!Number.isSafeInteger(s.packageVersion)||s.packageVersion<1||Object.entries(s).some(([k,x])=>v[k]!==x))throw Error('发布预检与当前成片或目标周不一致。');return v;}
function checks(v:unknown):asserts v is SocialWeeklyG6Check[]{if(!Array.isArray(v)||v.length!==5||new Set(v.map(r=>r?.code)).size!==5||v.some(r=>!object(r)||!WEEKLY_G6_CHECK_CODES.includes(r.code)||!['passed','blocked','unknown'].includes(r.status)||!strings(r.reasons)||!strings(r.evidenceRefs)||(r.status==='passed'&&!r.evidenceRefs.length)||(r.status!=='passed'&&!r.reasons.length)))throw Error('五项发布预检证据不完整。');}
export function parseWeeklyG6Context(v:unknown,s:SocialWeeklyG6Scope):SocialWeeklyG6Context{const c=scope(v,s);if(!['sourceHash','contextHash','artifactHash','fileSha256','productionResultHash'].every(k=>hash(c[k]))||!['fileRef','handoffId','handoffVersion','productionResultId','accountId'].every(k=>text(c[k]))||c.previewUrl!==`/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/artifacts/${encodeURIComponent(s.artifactId)}/media`||!['tiktok','instagram','facebook','youtube'].includes(c.platform)||!(c.accountIdentityHash===null||hash(c.accountIdentityHash))||!(c.nativeAccountId===null||text(c.nativeAccountId))||!(c.plannedPublishWindow===null||instant(c.plannedPublishWindow))||!strings(c.gaps))throw Error('实际发布目标或成片来源尚未核验。');checks(c.checks);if(c.assignmentRef!==null&&(!object(c.assignmentRef)||!text(c.assignmentRef.assignmentId)||!hash(c.assignmentRef.assignmentHash)))throw Error('发布安排来源不可核验。');if(c.metadata!==null){const m=c.metadata;if(!object(m)||m.fileSha256!==c.fileSha256||!hash(m.recordHash)||!Number.isSafeInteger(m.bytes)||m.bytes<=0||![null,'mp4','mov','webm'].includes(m.container)||![m.width,m.height].every(x=>Number.isSafeInteger(x)&&x>0)||![m.framesPerSecond,m.durationSeconds].every(x=>typeof x==='number'&&Number.isFinite(x)&&x>0)||![m.videoCodec,m.probeTool,m.probeVersion].every(text)||!(m.audioCodec===null||text(m.audioCodec)))throw Error('成片实际媒体检测结果不可核验。');}return c as SocialWeeklyG6Context;}
export function parseWeeklyG6Read(v:unknown,s:SocialWeeklyG6Scope,id:string):SocialWeeklyG6ReviewRead{if(!object(v)||!['not_found','pending','applied'].includes(v.projectionStatus)||typeof v.currentSourceVerified!=='boolean'||!('item'in v))throw Error('发布预检回执不可用。');if(v.item===null){if(v.projectionStatus!=='not_found')throw Error('发布预检状态不一致。');return v as SocialWeeklyG6ReviewRead;}const r=scope(v.item,s);checks(r.checks);const actual=r.checks.some((c:SocialWeeklyG6Check)=>c.status==='blocked')?'blocked':r.checks.some((c:SocialWeeklyG6Check)=>c.status==='unknown')?'unknown':'passed';if(r.requestId!==id||r.version!==1||!text(r.reviewId)||!text(r.requestedBy)||!instant(r.requestedAt)||!['sourceHash','contextHash','recordHash'].every(k=>hash(r[k]))||!['passed','blocked','unknown'].includes(r.status)||(actual==='blocked'&&r.status!=='blocked')||(actual==='unknown'&&r.status!=='unknown')||(r.status==='passed'&&actual!=='passed')||!(r.receiptId===null||text(r.receiptId))||!(r.receiptHash===null||hash(r.receiptHash))||v.projectionStatus==='not_found'||(r.status==='passed'&&(!r.receiptId||!r.receiptHash))||(r.status!=='passed'&&(r.receiptId!==null||r.receiptHash!==null||v.projectionStatus!=='applied')))throw Error('发布预检结论与实际五项证据不一致。');return v as SocialWeeklyG6ReviewRead;}
function path(s:SocialWeeklyG6Scope){return `/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/runs/${encodeURIComponent(s.runId)}/artifacts/${encodeURIComponent(s.artifactId)}/g6-reviews`;}
const target=(s:SocialWeeklyG6Scope)=>({programId:s.programId,packageId:s.packageId,packageVersion:s.packageVersion,publicationTaskId:s.publicationTaskId});
async function request(s:SocialWeeklyG6Scope,suffix:string,body?:object){const token=getToken();if(!token)throw Error('请登录后核验发布条件。');const query=new URLSearchParams(Object.entries(target(s)).map(([k,v])=>[k,String(v)]));const r=await fetch(path(s)+suffix+(body?'':`?${query}`),{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({...target(s),...body})}:{}),cache:'no-store',redirect:'error'});const v=await r.json();if(token!==getToken())throw Error('登录身份已变化，请重新读取本周发布条件。');if(!r.ok)throw Error(typeof v?.message==='string'?v.message:'发布预检结果待查询，请保留原请求。');return v;}
export const socialWeeklyG6ReviewApi={async context(s:SocialWeeklyG6Scope){const v=await request(s,'');return parseWeeklyG6Context(v?.item,s);},async check(s:SocialWeeklyG6Scope,c:SocialWeeklyG6Context,requestId:string){scope(c,s);return parseWeeklyG6Read(await request(s,'/check',{requestId,expectedContextHash:c.contextHash}),s,requestId);},async read(s:SocialWeeklyG6Scope,id:string){return parseWeeklyG6Read(await request(s,`/requests/${encodeURIComponent(id)}`),s,id);},async resume(s:SocialWeeklyG6Scope,id:string){return parseWeeklyG6Read(await request(s,`/requests/${encodeURIComponent(id)}/resume`,{}),s,id);}};
