import type { SceneReworkCostPolicy, SceneReworkRouteQuote } from '../../server/starter198/socialContentSceneReworkCostPolicy';
import type { SocialSceneReworkStatus } from '../../shared/contracts/socialSceneRework';
import {authHeader} from './auth';
export interface SceneReworkCostEvidence {quote:SceneReworkRouteQuote|null;policy:SceneReworkCostPolicy|null;gaps:string[];jobStatus:string;runStatus:string}
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown):v is string=>typeof v==='string'&&v.length>0;
const hash=(v:unknown):v is string=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const number=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=0;
const date=(v:unknown):v is string=>text(v)&&Number.isFinite(Date.parse(v));
function sameIds(ids:unknown,s:SocialSceneReworkStatus):boolean{return Array.isArray(ids)&&ids.every(text)&&new Set(ids).size===ids.length&&ids.length===s.affectedSceneIds.length&&s.affectedSceneIds.every(id=>ids.includes(id));}
export function parseSceneReworkQuote(v:unknown,s:SocialSceneReworkStatus):SceneReworkRouteQuote{if(!obj(v)||v.type!=='scene_rework_route_quote'||v.version!==1||v.tenantId!==s.tenantId||v.taskId!==s.taskId||v.executionRunId!==s.executionRunId||v.operationId!==s.operationId||!hash(v.cacheHash)||!hash(v.planHash)||v.provider!=='qwen_image'||!text(v.model)||!sameIds(v.sceneIds,s)||v.operationsPerScene!==1||v.imagesPerOperation!==1||!number(v.maximumCostCnyPerImage)||!number(v.totalUpperBoundCny)||!number(v.maximumOriginalBudgetCny)||v.totalUpperBoundCny>v.maximumOriginalBudgetCny||v.totalUpperBoundCny<Math.ceil(v.maximumCostCnyPerImage*s.affectedSceneIds.length*100)/100||!text(v.tariffSourceRef)||!text(v.tariffVersion)||!date(v.validUntil)||!hash(v.recordHash))throw Error('scene_rework_cost_response_invalid');return v as unknown as SceneReworkRouteQuote;}
export function parseSceneReworkCostPolicy(v:unknown,s:SocialSceneReworkStatus):SceneReworkCostPolicy{if(!obj(v)||v.type!=='scene_rework_cost_policy'||v.version!==1||!obj(v.scope)||v.scope.tenantId!==s.tenantId||v.scope.taskId!==s.taskId||v.scope.runId!==s.executionRunId||v.scope.operationId!==s.operationId||!text(v.scope.actorUserId)||!number(v.authorizedMaximumCostCny)||!date(v.confirmedAt)||!hash(v.recordHash))throw Error('scene_rework_cost_response_scope');const quote=parseSceneReworkQuote(v.quote,s);if(v.authorizedMaximumCostCny<quote.totalUpperBoundCny||v.authorizedMaximumCostCny>quote.maximumOriginalBudgetCny)throw Error('scene_rework_cost_response_invalid');return v as unknown as SceneReworkCostPolicy;}
export function parseSceneReworkCostEvidence(v:unknown,s:SocialSceneReworkStatus):SceneReworkCostEvidence{if(!obj(v)||v.automaticallyResumed!==false||!obj(v.item)||!text(v.jobStatus)||!text(v.runStatus)||!Array.isArray(v.item.gaps)||!v.item.gaps.every(text)||!(v.item.quote===null||obj(v.item.quote))||!(v.item.policy===null||obj(v.item.policy)))throw Error('scene_rework_cost_response_invalid');return{quote:v.item.quote===null?null:parseSceneReworkQuote(v.item.quote,s),policy:v.item.policy===null?null:parseSceneReworkCostPolicy(v.item.policy,s),gaps:v.item.gaps as string[],jobStatus:v.jobStatus,runStatus:v.runStatus};}
export function sceneReworkCostConfirmable(e:SceneReworkCostEvidence,cap:number,now=Date.now()):boolean{return !!e.quote&&!e.policy&&e.gaps.length===0&&Date.parse(e.quote.validUntil)>now&&number(cap)&&cap>=e.quote.totalUpperBoundCny&&cap<=e.quote.maximumOriginalBudgetCny&&e.runStatus==='running'&&['queued','retry_wait','reconciling','blocked','running'].includes(e.jobStatus);}
async function request(s:SocialSceneReworkStatus,confirm?:{expectedQuoteHash:string;authorizedMaximumCostCny:number}){const response=await fetch(`/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/scene-rework/${encodeURIComponent(s.operationId)}/cost-policy${confirm?'/confirm':''}`,{method:confirm?'POST':'GET',headers:{...authHeader(),...(confirm?{'Content-Type':'application/json'}:{})},...(confirm?{body:JSON.stringify(confirm)}:{})});const value:unknown=await response.json();if(!response.ok)throw Error(obj(value)&&text(value.error)?value.error:'scene_rework_cost_request_failed');return value;}
export const socialSceneReworkCostApi={async read(s:SocialSceneReworkStatus){return parseSceneReworkCostEvidence(await request(s),s);},async confirm(s:SocialSceneReworkStatus,e:SceneReworkCostEvidence,cap:number){if(!sceneReworkCostConfirmable(e,cap))throw Error('scene_rework_cost_confirmation_not_ready');const value=await request(s,{expectedQuoteHash:e.quote!.recordHash,authorizedMaximumCostCny:cap});if(!obj(value)||value.automaticallyResumed!==false)throw Error('scene_rework_cost_response_invalid');const policy=parseSceneReworkCostPolicy(value.item,s);if(policy.quote.recordHash!==e.quote!.recordHash||policy.authorizedMaximumCostCny!==cap)throw Error('scene_rework_cost_confirmation_mismatch');return policy;}};
