import type { SocialSceneReworkAvailability, SocialSceneReworkStatus } from '../../shared/contracts/socialSceneRework';
import { authHeader } from './auth';
export interface SceneReworkScope { taskId:string; sourceRunId:string; parentArtifactId:string; tenantId?:string }
const text=(v:unknown):v is string=>typeof v==='string'&&v.length>0;
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
function identity(v:unknown,s:SceneReworkScope):Record<string,unknown>{if(!obj(v)||!text(v.tenantId)||v.taskId!==s.taskId||v.sourceRunId!==s.sourceRunId||v.parentArtifactId!==s.parentArtifactId||(s.tenantId&&v.tenantId!==s.tenantId))throw Error('scene_rework_response_scope');return v;}
function validateProductionWorkspace(r:Record<string,unknown>){
 const binding=r.productionWorkspaceBinding;
 if(r.productionWorkspaceGap!==undefined&&r.productionWorkspaceGap!==null&&!(text(r.productionWorkspaceGap)&&r.productionWorkspaceGap.trim()))throw Error('scene_rework_workspace_invalid');
 if(binding===undefined||binding===null)return;
 const hash=(value:unknown)=>typeof value==='string'&&/^[a-f0-9]{64}$/.test(value);
 if(!obj(binding)||binding.type!=='social_production_workspace'||binding.version!==1||binding.projectVersion!==1||binding.tenantId!==r.tenantId||binding.taskId!==r.taskId||binding.runId!==r.sourceRunId||binding.artifactId!==r.parentArtifactId||typeof binding.projectId!=='string'||!/^[a-f0-9]{15}$/.test(binding.projectId)||!['artifactContentHash','specHash','baselineHash','recordHash'].every(key=>hash(binding[key]))||!Array.isArray(binding.sceneMappings)||!binding.sceneMappings.length)throw Error('scene_rework_workspace_invalid');
 const scenes=r.scenes as Array<{sceneId:string}>;
 const mappings=binding.sceneMappings;
 if(mappings.length!==scenes.length||!mappings.every(item=>obj(item)&&text(item.sceneId)&&item.slotId===item.sceneId&&scenes.some(scene=>scene.sceneId===item.sceneId)&&typeof item.mediaFileRef==='string'&&/^socialfile:[a-zA-Z0-9._:@-]+$/.test(item.mediaFileRef)&&hash(item.mediaSha256))||new Set(mappings.map(item=>item.sceneId)).size!==mappings.length||new Set(mappings.map(item=>item.slotId)).size!==mappings.length)throw Error('scene_rework_workspace_invalid');
}
export function parseSceneReworkAvailability(v:unknown,s:SceneReworkScope):SocialSceneReworkAvailability{const r=identity(v,s);if(typeof r.parentArtifactHash!=='string'||!/^[a-f0-9]{64}$/.test(r.parentArtifactHash)||typeof r.cacheHash!=='string'||!/^[a-f0-9]{64}$/.test(r.cacheHash)||typeof r.canRequest!=='boolean'||!Array.isArray(r.blockingReasons)||!r.blockingReasons.every(text)||!Array.isArray(r.scenes)||!r.scenes.length||!r.scenes.every(x=>obj(x)&&text(x.sceneId)&&text(x.shotId)&&(x.referenceShotId===null||text(x.referenceShotId))&&(x.sourceTiming===null||(obj(x.sourceTiming)&&typeof x.sourceTiming.startSeconds==='number'&&Number.isFinite(x.sourceTiming.startSeconds)&&x.sourceTiming.startSeconds>=0&&typeof x.sourceTiming.endSeconds==='number'&&Number.isFinite(x.sourceTiming.endSeconds)&&x.sourceTiming.endSeconds>x.sourceTiming.startSeconds&&typeof x.sourceTiming.durationSeconds==='number'&&Number.isFinite(x.sourceTiming.durationSeconds)&&x.sourceTiming.durationSeconds>0))&&text(x.technicalReceiptId)&&(x.checks===undefined||(Array.isArray(x.checks)&&x.checks.every(check=>obj(check)&&text(check.code)&&check.code.trim().length>0&&typeof check.passed==='boolean'&&text(check.message)&&check.message.trim().length>0)))&&['passed','failed','review_required'].includes(String(x.status)))||new Set(r.scenes.map(x=>x.sceneId)).size!==r.scenes.length)throw Error('scene_rework_response_invalid');if(r.existingOperations!==undefined){if(!Array.isArray(r.existingOperations))throw Error('scene_rework_response_invalid');r.existingOperations.forEach(x=>parseSceneReworkStatus(x,s));}validateProductionWorkspace(r);return r as unknown as SocialSceneReworkAvailability;}
export function parseSceneReworkStatus(v:unknown,s:SceneReworkScope,operationId?:string):SocialSceneReworkStatus{const r=identity(v,s);if(!text(r.operationId)||(operationId&&r.operationId!==operationId)||!text(r.executionRunId)||r.executionRunId===s.sourceRunId||!text(r.jobId)||!text(r.jobStatus)||!text(r.runStatus)||!(r.lastError===null||typeof r.lastError==='string')||!Array.isArray(r.affectedSceneIds)||!r.affectedSceneIds.length||!r.affectedSceneIds.every(text)||new Set(r.affectedSceneIds).size!==r.affectedSceneIds.length)throw Error('scene_rework_response_invalid');for(const key of ['completedAt','runCompletedAt'])if(r[key]!==undefined&&r[key]!==null&&!(text(r[key])&&Number.isFinite(Date.parse(r[key] as string))))throw Error('scene_rework_response_invalid');if(r.output!==undefined&&r.output!==null){const out=r.output;if(!obj(out)||!text(out.artifactId)||out.artifactId===s.parentArtifactId||!text(out.fileRef)||!/^socialfile:[a-zA-Z0-9._:@-]+$/.test(out.fileRef)||typeof out.sha256!=='string'||!/^[a-f0-9]{64}$/.test(out.sha256)||out.parentArtifactId!==s.parentArtifactId||!['review_required','changes_requested'].includes(String(out.reviewStatus))||!Array.isArray(out.qualityReceiptIds)||!out.qualityReceiptIds.length||!out.qualityReceiptIds.every(text)||new Set(out.qualityReceiptIds).size!==out.qualityReceiptIds.length||!text(out.savedAt)||!Number.isFinite(Date.parse(out.savedAt)))throw Error('scene_rework_output_invalid');}return r as unknown as SocialSceneReworkStatus;}
export function sceneReworkSelectionAllowed(a:SocialSceneReworkAvailability,ids:string[]):boolean{return a.canRequest&&ids.length>0&&new Set(ids).size===ids.length&&ids.every(id=>a.scenes.some(s=>s.sceneId===id&&s.status==='failed'))&&a.scenes.every(s=>ids.includes(s.sceneId)||s.status==='passed');}
async function request(s:SceneReworkScope,suffix:string,body?:unknown){const res=await fetch(`/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/scene-rework${suffix}`,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data:unknown=await res.json();if(!res.ok)throw Error(obj(data)&&text(data.error)?data.error:'scene_rework_request_failed');if(!obj(data)||!('item'in data))throw Error('scene_rework_response_invalid');return data.item;}
export const socialSceneReworkApi={async resume(s:SceneReworkScope,previous:SocialSceneReworkStatus,expectedPolicyHash?:string){identity(previous,s);if(!['blocked','dead_letter','paused'].includes(previous.jobStatus)||previous.runStatus!=='running'||(expectedPolicyHash!==undefined&&!/^[a-f0-9]{64}$/.test(expectedPolicyHash)))throw Error('scene_rework_resume_not_ready');const result=parseSceneReworkStatus(await request(s,`/${encodeURIComponent(previous.operationId)}/resume`,{expectedJobId:previous.jobId,...(expectedPolicyHash?{expectedPolicyHash}:{})}),s,previous.operationId);if(result.jobId!==previous.jobId||result.executionRunId!==previous.executionRunId||result.affectedSceneIds.length!==previous.affectedSceneIds.length||!previous.affectedSceneIds.every(id=>result.affectedSceneIds.includes(id)))throw Error('scene_rework_resume_scope');return result;},async availability(s:SceneReworkScope){return parseSceneReworkAvailability(await request(s,`?parentArtifactId=${encodeURIComponent(s.parentArtifactId)}`),s);},async submit(s:SceneReworkScope,a:SocialSceneReworkAvailability,ids:string[]){identity(a,s);if(!sceneReworkSelectionAllowed(a,ids))throw Error('scene_rework_selection_not_ready');const result=parseSceneReworkStatus(await request(s,'',{parentArtifactId:s.parentArtifactId,affectedSceneIds:ids,expectedCacheHash:a.cacheHash}),s);if(result.affectedSceneIds.length!==ids.length||!ids.every(id=>result.affectedSceneIds.includes(id)))throw Error('scene_rework_selection_mismatch');return result;},async status(s:SceneReworkScope,id:string){return parseSceneReworkStatus(await request(s,`/${encodeURIComponent(id)}`),s,id);}};
