import { authHeader } from './auth';
export interface WeeklyNativeScope { tenantId: string; programId: string; packageId: string; packageVersion: number; runId: string }
export interface WeeklyNativeCandidate { batchId: string; itemId: string; customerId: string; channel: 'messenger' | 'instagram'; expectedBatchVersion: number; expectedItemHash: string; scheduledAt: string | null; taskId?: string | null; draftBody?: string | null; accountId?: string | null; recipientMasked?: string | null; status: string; gap: string | null }
const base=(s:WeeklyNativeScope)=>`/api/overseas/social-programs/${encodeURIComponent(s.programId)}/operating-packages/${encodeURIComponent(s.packageId)}/native-dispatch`;
/** Reads never dispatch. An uncertain POST is never retried by this client. */
async function request(url:string,body?:unknown){const headers=authHeader();const response=await fetch(url,{method:body?'POST':'GET',headers:{...headers,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await response.json();if(headers.Authorization!==authHeader().Authorization)throw Error('登录身份已改变，请重新读取原周任务。');if(!response.ok)throw Error(data.error||'周任务请求失败。');return data;}
export const weeklyNativeDispatchApi={
 async sources(scope:WeeklyNativeScope):Promise<WeeklyNativeCandidate[]>{const data=await request(`${base(scope)}/sources?version=${scope.packageVersion}&runId=${encodeURIComponent(scope.runId)}`);if(!data.scope||Object.entries(scope).some(([k,v])=>data.scope[k]!==v)||!Array.isArray(data.items))throw Error('发送候选与原租户、周包或运行不一致。');const ids=new Set<string>();for(const item of data.items){const id=`${item.batchId}:${item.itemId}`;if(!item.batchId||!item.itemId||!item.customerId||ids.has(id)||!['messenger','instagram'].includes(item.channel)||!Number.isSafeInteger(item.expectedBatchVersion)||item.expectedBatchVersion<1||typeof item.expectedItemHash!=='string'||!item.expectedItemHash||typeof item.status!=='string'||!(item.gap===null||typeof item.gap==='string'))throw Error('真实发送候选身份缺失或重复。');if(item.gap===null&&(!item.taskId||typeof item.taskId!=='string'||typeof item.draftBody!=='string'||!item.draftBody.trim()||typeof item.accountId!=='string'||!item.accountId))throw Error('原审批正文或真实生产任务入口缺失。');ids.add(id);}return data.items;},
 async dispatch(scope:WeeklyNativeScope,item:WeeklyNativeCandidate):Promise<{itemId:string;requestId:string;status:'sent';messagesSent:number}>{if(item.gap)throw Error('原任务证据尚未满足，请先处理缺口。');const data=await request(base(scope),{packageVersion:scope.packageVersion,runId:scope.runId,batchId:item.batchId,itemId:item.itemId,expectedBatchVersion:item.expectedBatchVersion,expectedItemHash:item.expectedItemHash});if(data.itemId!==item.itemId||typeof data.requestId!=='string'||!data.requestId||data.status!=='sent'||![0,1].includes(data.messagesSent))throw Error('发送结果尚未核验，请只读核对原发送记录。');return data;}
};
