import test from 'node:test';
import assert from 'node:assert/strict';
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null}});
import {weeklyContentTemplateApi} from './weeklyContentTemplateApi';
test('template pagination preserves exact page and rejects scope drift and absent totals',async()=>{const fetch=globalThis.fetch;try{let url='';globalThis.fetch=async u=>{url=String(u);return Response.json({items:[],page:2,perPage:50,totalItems:0,totalPages:0});};await weeklyContentTemplateApi.list('p/a',2);assert.equal(url,'/api/overseas/social-programs/p%2Fa/content-templates?page=2');for(const payload of [{items:[],page:2},{items:[{programId:'other',templateId:'t',version:1,recordHash:'h'}],page:2,perPage:50,totalItems:1,totalPages:2}]){globalThis.fetch=async()=>Response.json(payload);await assert.rejects(weeklyContentTemplateApi.list('p/a',2));}}finally{globalThis.fetch=fetch;}});
test('confirmation requires exact candidate version/hash/usage receipt',async()=>{const fetch=globalThis.fetch;try{const input={templateRef:{type:'weekly_content_template',id:'t',version:3},candidateHash:'h',usage:'trial' as const,reason:'明确试用'};let body:unknown;globalThis.fetch=async(_u,init)=>{body=JSON.parse(String(init?.body));return Response.json({item:{programId:'p',...input}});};await weeklyContentTemplateApi.confirm('p',input);assert.deepEqual(body,input);globalThis.fetch=async()=>Response.json({item:{programId:'p',...input,templateRef:{...input.templateRef,version:4}}});await assert.rejects(weeklyContentTemplateApi.confirm('p',input));}finally{globalThis.fetch=fetch;}});
test('future bind is pending receipt only and rejects mismatched target or binding ref',async()=>{const original=globalThis.fetch;try{const input={packageId:'future',expectedPackageVersion:2,expectedTargetVersion:3,publicationTaskId:'pub',templateRef:{type:'weekly_content_template',id:'template',version:1},candidateHash:'hash'};const receipt={item:{programId:'p',packageId:'future',packageVersion:3,publicationTaskId:'pub',templateRef:input.templateRef,candidateHash:'hash',bindingId:'binding'},publicationPatch:{publicationTaskId:'pub',contentTemplateBindingRef:{type:'weekly_content_template_binding',id:'binding',version:1}},planningRevisionRequired:true};const calls:string[]=[];globalThis.fetch=async(u,init)=>{calls.push(String(u));assert.deepEqual(JSON.parse(String(init?.body)),input);return Response.json(receipt);};await weeklyContentTemplateApi.bind('p',input);assert.deepEqual(calls,['/api/overseas/social-programs/p/content-templates/bind']);globalThis.fetch=async()=>Response.json({...receipt,item:{...receipt.item,packageVersion:2}});await assert.rejects(weeklyContentTemplateApi.bind('p',input));}finally{globalThis.fetch=original;}});
test('readonly confirmation and pending recovery distinguish missing receipts and preserve explicit scope',async()=>{const original=globalThis.fetch;try{const ref={type:'weekly_content_template',id:'t/a',version:3};const calls:string[]=[];globalThis.fetch=async u=>{calls.push(String(u));return Response.json({item:null});};assert.equal(await weeklyContentTemplateApi.readConfirmation('p',ref),null);const input={packageId:'w',expectedPackageVersion:4,expectedTargetVersion:5,publicationTaskId:'pub',templateRef:ref,candidateHash:'h'};assert.equal(await weeklyContentTemplateApi.readPendingBinding('p',input),null);assert.match(calls[0],/templateId=t%2Fa&templateVersion=3/);assert.match(calls[1],/expectedPackageVersion=4&expectedTargetVersion=5/);globalThis.fetch=async()=>Response.json({item:{programId:'p',templateRef:ref,candidateHash:'h',usage:'trial',confirmationId:'conf'}});assert.equal((await weeklyContentTemplateApi.readConfirmation('p',ref))?.confirmationId,'conf');globalThis.fetch=async()=>Response.json({item:{programId:'wrong',templateRef:ref,candidateHash:'h'}});await assert.rejects(weeklyContentTemplateApi.readConfirmation('p',ref));}finally{globalThis.fetch=original;}});
test('apply sends only immutable binding intent and validates exact target revision',async()=>{const original=globalThis.fetch;try{const input={bindingId:'binding',sourceVersion:2,targetVersion:3};let sent:unknown;globalThis.fetch=async(u,init)=>{assert.match(String(u),/content-templates\/apply$/);sent=JSON.parse(String(init?.body));return Response.json({item:{programId:'p',version:3},activated:false,recovered:true});};await weeklyContentTemplateApi.apply('p',input);assert.deepEqual(sent,input);globalThis.fetch=async()=>Response.json({item:{programId:'p',version:4},activated:false,recovered:true});await assert.rejects(weeklyContentTemplateApi.apply('p',input));}finally{globalThis.fetch=original;}});
