import type{WeeklyExecutionTask,WeeklyOperatingPackage,VersionedSocialRef}from'../../shared/contracts/socialProgram';
import{authHeader,getToken}from'./auth';import{productionNavigationIdentity}from'./productionNavigation';
export interface WeeklyEnterpriseFactException{type:'scheduler_supplement_exception';exceptionId:string;tenantId:string;programId:string;packageId:string;packageVersion:number;consumerTaskId:string;consumerInputHash:string;gapCode:string;kind:'enterprise_facts';status:'assignment_pending'|'resolved';dueAt:string;responsibleActor:string;createdAt:string;recordHash:string}
export interface WeeklyEnterpriseFactTarget{tenantId:string;programId:string;packageId:string;packageVersion:number;exceptionId:string;consumerTaskId:string;consumerInputHash:string;publicationTaskId:string;enterpriseProfileRef:VersionedSocialRef|null;factRefs:VersionedSocialRef[];fieldPaths:string[];authIdentity:string;createdAt:number}
const key='lingshu:weekly-enterprise-fact-navigation',fields=['company.name','products.categories','products.items[].name'];const hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),ref=(v:VersionedSocialRef)=>!!v&&v.type==='enterprise_fact'&&!!v.id&&Number.isSafeInteger(v.version)&&v.version>0;
export async function readWeeklyEnterpriseFactExceptions(scope:{programId:string;packageId:string;packageVersion:number}){const token=getToken();if(!token)throw Error('请登录后读取企业事实补齐任务。');const r=await fetch(`/api/overseas/social-programs/${encodeURIComponent(scope.programId)}/operating-packages/${encodeURIComponent(scope.packageId)}/supplement-requests/scheduler-exceptions?version=${scope.packageVersion}`,{headers:authHeader(),cache:'no-store'}),body=await r.json();if(token!==getToken())throw Error('登录身份变化，请重新读取企业事实补齐任务。');if(!r.ok)throw Error(body.message||body.error||'企业事实补齐任务读取失败。');if(!Array.isArray(body.items))throw Error('企业事实补齐任务列表不完整。');return body.items.filter((x:WeeklyEnterpriseFactException)=>x?.kind==='enterprise_facts').map((x:WeeklyEnterpriseFactException)=>{if(x.type!=='scheduler_supplement_exception'||x.programId!==scope.programId||x.packageId!==scope.packageId||x.packageVersion!==scope.packageVersion||!x.exceptionId||!x.tenantId||!x.consumerTaskId||!hash(x.consumerInputHash)||!hash(x.recordHash)||!Number.isFinite(Date.parse(x.dueAt)))throw Error('企业事实补齐任务身份不完整。');return x;});}
export function enterpriseFactTarget(item:WeeklyEnterpriseFactException,pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[],now=Date.now()):WeeklyEnterpriseFactTarget{const matches=tasks.filter(t=>t.tenantId===item.tenantId&&t.programId===item.programId&&t.packageId===item.packageId&&t.packageVersion===item.packageVersion&&t.taskId===item.consumerTaskId&&t.status==='blocked'&&t.lastError?.code===item.gapCode);if(matches.length!==1)throw Error('企业事实补齐任务与原执行不一致。');const task=matches[0]!,pubs=pkg.socialContentPackage.publicationTasks.filter(p=>p.publicationTaskId===task.publicationTaskId&&p.accountId===task.accountId);if(pkg.programId!==item.programId||pkg.packageId!==item.packageId||pkg.version!==item.packageVersion||pubs.length!==1||!pubs[0]!.factRefs.every(ref))throw Error('企业事实补齐任务与冻结周包不一致。');return{tenantId:item.tenantId,programId:item.programId,packageId:item.packageId,packageVersion:item.packageVersion,exceptionId:item.exceptionId,consumerTaskId:item.consumerTaskId,consumerInputHash:item.consumerInputHash,publicationTaskId:pubs[0]!.publicationTaskId,enterpriseProfileRef:pkg.enterpriseProfileRef,factRefs:structuredClone(pubs[0]!.factRefs),fieldPaths:fields,authIdentity:productionNavigationIdentity(),createdAt:now};}
export function saveWeeklyEnterpriseFactTarget(target:WeeklyEnterpriseFactTarget){sessionStorage.setItem(key,JSON.stringify(target));}
export function readWeeklyEnterpriseFactTarget(now=Date.now()):WeeklyEnterpriseFactTarget|null{try{const x=JSON.parse(sessionStorage.getItem(key)||'null')as WeeklyEnterpriseFactTarget;if(!x||x.authIdentity!==productionNavigationIdentity()||now-x.createdAt<0||now-x.createdAt>300_000||!x.exceptionId||!x.consumerTaskId||!hash(x.consumerInputHash)||!x.factRefs?.every(ref)||x.fieldPaths?.join('|')!==fields.join('|'))return null;return x;}catch{return null;}}
export function openWeeklyEnterpriseFactTarget(target:WeeklyEnterpriseFactTarget){saveWeeklyEnterpriseFactTarget(target);window.dispatchEvent(new CustomEvent('lingshu:navigate',{detail:{page:'enterprise',businessRef:{taskKey:'weekly_enterprise_facts',entityId:target.exceptionId,contentId:target.consumerTaskId,referenceId:target.publicationTaskId}}}));}
