import {isWeeklySalesHandoff} from '../../shared/contracts/socialWeeklySalesHandoff';
import type {WeeklyCustomerRelationshipCheck} from '../../shared/contracts/customerRelationshipEvidence';
import { authHeader } from './auth';
import type { WeeklySalesHandoff, WeeklySalesSource } from '../../shared/contracts/socialWeeklySalesHandoff';
const path=(programId:string,packageId:string)=>`/api/overseas/social-programs/${encodeURIComponent(programId)}/operating-packages/${encodeURIComponent(packageId)}/sales-handoffs`;
async function request<T>(url:string,body?:unknown):Promise<T>{const r=await fetch(url,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json().catch(()=>{throw Error('销售交接接口未返回真实数据。');});if(!r.ok)throw Error(data.error||'销售交接操作失败');return data as T;}
export const weeklySalesHandoffApi={
 list:async(p:string,k:string,v:number)=>{const r=await request<{items:WeeklySalesHandoff[]}>(`${path(p,k)}?version=${v}`);if(!Array.isArray(r.items)||!r.items.every(i=>isWeeklySalesHandoff(i)&&i.programId===p)||new Set(r.items.map(i=>i.id)).size!==r.items.length)throw Error('缺少真实销售交接列表');return r.items;},
 sources:async(p:string,k:string,v:number)=>{const result=await request<{items:WeeklySalesSource[];gaps:string[];relationshipChecks?:WeeklyCustomerRelationshipCheck[]}>(`${path(p,k)}/sources?version=${v}`);if(!Array.isArray(result.items)||!Array.isArray(result.gaps)||!result.items.every(i=>i&&typeof i.runId==='string'&&typeof i.memberId==='string'&&typeof i.sourceInteractionId==='string'&&typeof i.body==='string'))throw Error('缺少真实询盘来源记录');if(result.relationshipChecks!==undefined&&(!Array.isArray(result.relationshipChecks)||!result.relationshipChecks.every(c=>c&&typeof c.customerId==='string'&&typeof c.memberId==='string'&&typeof c.runId==='string'&&typeof c.weekStart==='string'&&typeof c.weekEnd==='string'&&c.assessment?.customerId===c.customerId&&c.assessment.weekStart===c.weekStart&&c.assessment.weekEnd===c.weekEnd)))throw Error('客户关系绑定窗口缺失');return result;},
 create:async(p:string,k:string,body:Record<string,unknown>)=>{const r=await request<{item:WeeklySalesHandoff}>(path(p,k),body);if(!isWeeklySalesHandoff(r.item)||r.item.programId!==p||r.item.packageId!==k||r.item.packageVersion!==body.packageVersion||r.item.runId!==body.runId||r.item.memberId!==body.memberId||r.item.sourceInteractionId!==body.sourceInteractionId||r.item.ownerUserId!==body.ownerUserId)throw Error('销售交接创建回执与原客户来源不一致。');return r;},
 transition:async(item:WeeklySalesHandoff,body:Record<string,unknown>)=>{if(!isWeeklySalesHandoff(item)||body.expectedVersion!==item.version||!['claim','request_feedback','feedback'].includes(String(body.action)))throw Error('销售交接动作或原版本不可核验。');const r=await request<{item:WeeklySalesHandoff}>(`${path(item.programId,item.packageId)}/${encodeURIComponent(item.id)}/events`,{...body,packageVersion:item.packageVersion});if(!isWeeklySalesHandoff(r.item)||['id','tenantId','programId','packageId','packageVersion','runId','memberId','customerId','sourceInteractionId','ownerUserId'].some(k=>r.item[k as keyof WeeklySalesHandoff]!==item[k as keyof WeeklySalesHandoff])||r.item.version!==item.version+1||r.item.status!==(body.action==='claim'?'in_progress':body.action==='request_feedback'?'awaiting_feedback':(body.feedback as {needsInformation?:boolean})?.needsInformation?'needs_information':'handled'))throw Error('销售交接动作回执与原客户或版本不一致。');return r;},
};
