import {authHeader,getToken} from './auth';
import {parseSceneReworkAvailability} from './socialSceneReworkApi';
import type {SocialSceneReworkAvailability} from '../../shared/contracts/socialSceneRework';
import type {SocialWeeklyG6Scope} from '../../shared/contracts/socialWeeklyG6Review';
import type {WeeklyInventoryScope,WeeklyInventoryView} from './weeklyInventoryReuseApi';
import type {WeeklyOperatingPackage} from '../../shared/contracts/socialProgram';
export function inventoryG6Scope(scope:WeeklyInventoryScope,pkg:WeeklyOperatingPackage,record:WeeklyInventoryView,availability:SocialSceneReworkAvailability):SocialWeeklyG6Scope{const b=record.item,pub=pkg.socialContentPackage.publicationTasks.filter(p=>p.publicationTaskId===b.target.publicationTaskId);if(record.state!=='bound'||b.tenantId!==scope.tenantId||b.programId!==scope.programId||b.target.packageId!==scope.packageId||b.target.packageVersion!==scope.packageVersion||pkg.programId!==scope.programId||pkg.packageId!==scope.packageId||pkg.version!==scope.packageVersion||pub.length!==1||b.ref.type!=='weekly_inventory_binding'||pub[0]?.inventoryReuseRef?.type!==b.ref.type||pub[0]?.inventoryReuseRef?.id!==b.bindingId||pub[0].inventoryReuseRef?.version!==b.ref.version||pub[0].accountId!==b.target.accountId||pub[0].platform!==b.target.platform||availability.tenantId!==scope.tenantId||availability.taskId!==b.source.sourceContentTaskId||availability.parentArtifactId!==b.source.artifactRef.id||availability.parentArtifactHash!==b.source.artifactHash||!availability.sourceRunId)throw Error('库存成片来源与本周绑定不一致，不能打开发布预检。');return {tenantId:scope.tenantId,taskId:b.source.sourceContentTaskId,runId:availability.sourceRunId,artifactId:b.source.artifactRef.id,programId:scope.programId,packageId:scope.packageId,packageVersion:scope.packageVersion,publicationTaskId:b.target.publicationTaskId};}
/** Run identity is read only from the actual server-owned artifact availability, never task.runId or latest run. */
export async function readInventorySourceAvailability(scope:WeeklyInventoryScope,record:WeeklyInventoryView){if(record.state!=='bound')throw Error('请先完成本周真实库存绑定。');const token=getToken();if(!token)throw Error('请登录后读取库存来源。');const source=record.item.source,r=await fetch(`/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(source.sourceContentTaskId)}/scene-rework?parentArtifactId=${encodeURIComponent(source.artifactRef.id)}`,{headers:authHeader(),cache:'no-store',redirect:'error'}),v=await r.json();if(getToken()!==token)throw Error('登录身份已变化，请重新读取库存来源。');if(!r.ok||!v?.item||typeof v.item.sourceRunId!=='string'||!v.item.sourceRunId)throw Error('原成片实际运行来源尚未核验。');return parseSceneReworkAvailability(v.item,{tenantId:scope.tenantId,taskId:source.sourceContentTaskId,parentArtifactId:source.artifactRef.id,sourceRunId:v.item.sourceRunId});}
