import { authHeader } from './auth';
import type { WeeklyOperatingPackage, VersionedSocialRef } from '../../shared/contracts/socialProgram';
import type { WeeklyContentTemplateCandidate, WeeklyContentTemplateConfirmation, WeeklyContentTemplateBinding } from '../../shared/contracts/socialWeeklyContentTemplates';
export interface CreateWeeklyContentTemplate {sourceTaskId:string;reviewRef:VersionedSocialRef;action:'new'|'retain'|'revise';previousRef?:VersionedSocialRef;title:string;reason:string;applicability:WeeklyContentTemplateCandidate['applicability']}
export interface WeeklyTemplatePage {items:WeeklyContentTemplateCandidate[];page:number;perPage:number;totalItems:number;totalPages:number}
async function request<T>(programId:string,suffix:string,body?:unknown):Promise<T>{
 const response=await fetch(`/api/overseas/social-programs/${encodeURIComponent(programId)}/content-templates${suffix}`,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const result=await response.json().catch(()=>{throw new Error('模板服务未返回有效数据。');});
 if(!response.ok)throw new Error(result.message||'模板操作失败，请核对真实来源和版本。');return result as T;
}
export const weeklyContentTemplateApi={
 async list(programId:string,page=1):Promise<WeeklyTemplatePage>{const result=await request<WeeklyTemplatePage>(programId,`?page=${page}`);if(!Array.isArray(result.items)||result.page!==page||![result.totalItems,result.totalPages,result.perPage].every(n=>Number.isSafeInteger(n)&&n>=0)||!result.items.every(i=>i.programId===programId&&i.templateId&&i.version>0&&i.recordHash))throw new Error('模板分页或项目归属缺失，请刷新服务。');return result;},
 async create(programId:string,input:CreateWeeklyContentTemplate){const {item}=await request<{item:WeeklyContentTemplateCandidate}>(programId,'',input);if(item?.programId!==programId||item.source?.sourceTaskId!==input.sourceTaskId||!item.recordHash)throw new Error('模板候选回执与所选来源不一致。');return item;},
 async apply(programId:string,input:{bindingId:string;sourceVersion:number;targetVersion:number}){const result=await request<{item:WeeklyOperatingPackage;activated:false;recovered:boolean}>(programId,'/apply',input);if(result.item?.programId!==programId||result.item.version!==input.targetVersion||result.activated!==false)throw Error('模板应用回执版本不一致。');return result;},
 async readConfirmation(programId:string,templateRef:VersionedSocialRef){const {item}=await request<{item:WeeklyContentTemplateConfirmation|null}>(programId,`/confirmation?${new URLSearchParams({templateId:templateRef.id,templateVersion:String(templateRef.version)})}`);if(item!==null&&(item?.programId!==programId||item.templateRef?.id!==templateRef.id||item.templateRef.version!==templateRef.version||!item.candidateHash))throw new Error('模板确认读取回执不一致。');return item;},
 async readPendingBinding(programId:string,input:{packageId:string;expectedPackageVersion:number;expectedTargetVersion:number;publicationTaskId:string;templateRef:VersionedSocialRef;candidateHash:string;bindingId?:string}){const {templateRef,...other}=input;const query=new URLSearchParams(Object.entries({...other,templateId:templateRef.id,templateVersion:templateRef.version}).map(([k,v])=>[k,String(v)]));const {item}=await request<{item:WeeklyContentTemplateBinding|null}>(programId,`/pending-binding?${query}`);if(item!==null&&(item?.programId!==programId||item.packageId!==input.packageId||item.packageVersion!==input.expectedTargetVersion||item.publicationTaskId!==input.publicationTaskId||item.templateRef?.id!==templateRef.id||item.templateRef.version!==templateRef.version||item.candidateHash!==input.candidateHash||(input.bindingId&&item.bindingId!==input.bindingId)))throw new Error('待绑定读取回执不一致。');return item;},
 async bind(programId:string,input:{packageId:string;expectedPackageVersion:number;expectedTargetVersion:number;publicationTaskId:string;templateRef:VersionedSocialRef;candidateHash:string}){const result=await request<{item:WeeklyContentTemplateBinding;publicationPatch:{publicationTaskId:string;contentTemplateBindingRef:VersionedSocialRef};planningRevisionRequired:true}>(programId,'/bind',input);if(result.item?.programId!==programId||result.item.packageId!==input.packageId||result.item.packageVersion!==input.expectedTargetVersion||result.item.publicationTaskId!==input.publicationTaskId||result.item.candidateHash!==input.candidateHash||result.item.templateRef?.id!==input.templateRef.id||result.item.templateRef.version!==input.templateRef.version||result.publicationPatch?.publicationTaskId!==input.publicationTaskId||result.publicationPatch.contentTemplateBindingRef.type!=='weekly_content_template_binding'||result.publicationPatch.contentTemplateBindingRef.version!==1||result.publicationPatch.contentTemplateBindingRef.id!==result.item.bindingId||result.planningRevisionRequired!==true)throw new Error('未来周模板绑定回执不一致。');return result;},
 async confirm(programId:string,input:{templateRef:VersionedSocialRef;candidateHash:string;usage:'trial'|'retain';reason:string}){const {item}=await request<{item:WeeklyContentTemplateConfirmation}>(programId,'/confirm',input);if(item?.programId!==programId||item.templateRef?.id!==input.templateRef.id||item.templateRef.version!==input.templateRef.version||item.candidateHash!==input.candidateHash||item.usage!==input.usage)throw new Error('模板确认回执不一致。');return item;}
};
