import {createElement} from 'react';import {renderToStaticMarkup} from 'react-dom/server';import WeeklyRecoveryPanel from '../components/socialProgram/WeeklyRecoveryPanel';
import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';
import type {DataStore,ListQuery,Record_} from '../../server/storage/datastore';
import {createSocialProgramService} from '../../server/socialPrograms/service';
import {createWeeklyOperatingPackageService} from '../../server/socialPrograms/weeklyOperatingPackages';
import {createWeeklyInitialScheduleRouter} from '../../server/routes/weeklyInitialSchedule';
import {weeklyInitialScheduleApi,parseInitialSchedulePreview} from './weeklyInitialScheduleApi';
import {offersInitialSchedule} from '../components/socialProgram/AgentOperatingControls';
import {listWeeklyExecutionTasks} from '../../server/socialPrograms/executionTasks';
test('actual first draft HTTP preview parses full graph and refuses missing capacity, wrong scope and late login',async t=>{
 const tables=new Map<string,Record_[]>();let serial=0;
 const store:DataStore={async getById<T>(c:string,id:string){return structuredClone(tables.get(c)?.find(r=>r.id===id)??null)as T|null;},async create<T>(c:string,d:Record<string,unknown>){const r={id:`client-${++serial}`,...structuredClone(d)} as Record_;tables.set(c,[...(tables.get(c)??[]),r]);return structuredClone(r)as T;},async update(c,id,d){const r=tables.get(c)?.find(r=>r.id===id);if(!r)return false;Object.assign(r,structuredClone(d));return true;},async delete(c,id){const old=tables.get(c)??[];tables.set(c,old.filter(r=>r.id!==id));return old.some(r=>r.id===id);},async list<T>(c:string,q:ListQuery={}){const all=(tables.get(c)??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v)),page=q.page??1,perPage=q.perPage??30;return {items:structuredClone(all.slice((page-1)*perPage,page*perPage))as T[],totalItems:all.length,totalPages:Math.max(1,Math.ceil(all.length/perPage)),page,perPage};}};
 await store.create('users',{id:'owner',tenantId:'tenant',role:'admin'});const programs=createSocialProgramService(store),packages=createWeeklyOperatingPackageService(store);const program=await programs.createProgram('tenant','owner',{brandName:'Actual first week',market:'EU',targetAudience:'Buyer',candidatePlatforms:['tiktok'],route:'cold_start'});const account=await programs.createAccount('tenant','owner',program.programId,{platform:'tiktok',displayName:'Actual account',businessRole:'core',audiencePromise:'buyer',contentPromise:'facts'});const pkg=await packages.create('tenant','owner',program.programId,{weekStart:'2026-11-09',objective:'One verified video',successCriteria:['One reviewed video'],accountPlans:[{accountId:account.accountId,publicationCount:1}],originalContentTarget:1});const scope={tenantId:'tenant',programId:program.programId,packageId:pkg.packageId,packageVersion:1};const tasks=await listWeeklyExecutionTasks(store,'tenant',program.programId,pkg.packageId,1);assert.equal(offersInitialSchedule(pkg,tasks),true);const html=renderToStaticMarkup(createElement(WeeklyRecoveryPanel,{mode:'initial',tasks,packageVersion:1,onAssess:async()=>{throw Error('must not assess during first schedule');}}));assert.match(html,/首次容量排期/);assert.match(html,/任务估时仅作辅助/);assert.doesNotMatch(html,/评估影响与可达数量/);assert.doesNotMatch(html,/先前发布授权将撤销/);assert.equal(offersInitialSchedule(pkg,tasks.map((task,i)=>i===0?{...task,attempt:1}:task)),false);
 const app=express();app.use(express.json());app.use((_req,res,next)=>{res.locals.tenantId='tenant';res.locals.userId='owner';next();});app.use('/api/overseas/social-programs/:programId/operating-packages/:packageId/initial-schedule',createWeeklyInitialScheduleRouter(store));const server=app.listen(0);await new Promise<void>(resolve=>server.once('listening',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();assert.ok(address&&typeof address==='object');
 let token:string|null='controlled-session';const oldStorage=globalThis.localStorage,oldFetch=globalThis.fetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>token}});t.after(()=>{globalThis.fetch=oldFetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:oldStorage});});let late=false;const bodies:unknown[]=[];globalThis.fetch=async(input,init)=>{if(init?.body)bodies.push(JSON.parse(String(init.body)));const r=await oldFetch(`http://127.0.0.1:${address.port}${input}`,init);if(late)token='another-session';return r;};
 const read=await weeklyInitialScheduleApi.preview(scope);assert.equal(read.authority,'estimated_task_durations_only');assert.equal(read.requiredInputs.length,read.graph.tasks.length);assert(read.graph.tasks.some(t=>t.schedule.stepKind==='material_preparation'));assert.throws(()=>parseInitialSchedulePreview(read,{...scope,tenantId:'foreign'}));assert.throws(()=>parseInitialSchedulePreview({...read,requiredInputs:[null]},scope));for(const field of ['estimatedMinutes','suggestedStartAt','suggestedFinishAt'] as const){const changed=structuredClone(read);const row=changed.requiredInputs[0];assert.ok(row);if(field==='estimatedMinutes')row.estimatedMinutes++;else row[field]=row[field]==='2026-11-01T00:00:00Z'?'2026-11-02T00:00:00Z':'2026-11-01T00:00:00Z';assert.throws(()=>parseInitialSchedulePreview(changed,scope));}
 const capacity={constraints:{},resources:{},remainingBudgetCny:1};const proposal=await weeklyInitialScheduleApi.propose(scope,capacity);assert.equal(proposal.plan.fullGraphConditionallyReachable,false);const reread=await weeklyInitialScheduleApi.readProposal(scope,proposal.proposalId);assert.equal(reread.inputEvidenceHash,proposal.inputEvidenceHash);const receipt=await weeklyInitialScheduleApi.readConfirmation(scope,proposal.proposalId);assert.deepEqual(receipt,{status:'not_committed',proposalId:proposal.proposalId,sourceVersion:1,targetVersion:2});await assert.rejects(weeklyInitialScheduleApi.confirm(scope,{proposalId:proposal.proposalId,expectedVersion:1,inputEvidenceHash:proposal.inputEvidenceHash}));assert.deepEqual(bodies[0],{packageVersion:1,capacity});assert.equal(tables.get('content_execution_jobs')?.length??0,0);assert.equal(tables.get('social_publication_attempts')?.length??0,0);
 late=true;await assert.rejects(weeklyInitialScheduleApi.preview(scope),/登录身份已变化/);late=false;token=null;await assert.rejects(weeklyInitialScheduleApi.preview(scope),/请登录/);
});
