import {authHeader} from './auth';
import type {WeeklyProfileUpgradeScope,WeeklyProfileUpgrade,WeeklyProfileHistoryEvidence,WeeklyProfileUpgradeBasis} from '../../shared/contracts/weeklyProfileUpgrade';
export type {WeeklyProfileUpgradeScope,WeeklyProfileUpgrade,WeeklyProfileHistoryEvidence,WeeklyProfileUpgradeBasis};
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim();
const hash=(v:unknown)=>text(v)&&/^[a-f0-9]{64}$/.test(v);
const instant=(v:unknown)=>text(v)&&/(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v));
function evidence(v:unknown):WeeklyProfileHistoryEvidence{if(!object(v)||!['evidenceRef','accountId','platform','externalContentId','publicUrl'].every(k=>text(v[k]))||!instant(v.publishedAt)||!(v.capturedAt===null||instant(v.capturedAt))||!(v.observationSeconds===null||typeof v.observationSeconds==='number'&&v.observationSeconds>=0&&Number.isFinite(v.observationSeconds))||typeof v.toneVerified!=='boolean'||!hash(v.evidenceHash)||!Array.isArray(v.gaps)||v.gaps.some((g:unknown)=>!text(g))||!object(v.metrics)||['views','likes','shares','comments'].some(k=>v.metrics[k]!==null&&!(typeof v.metrics[k]==='number'&&Number.isFinite(v.metrics[k])&&v.metrics[k]>=0)))throw Error('真实历史视频及播放赞转评证据缺失。');return v as WeeklyProfileHistoryEvidence;}
export function parseWeeklyProfileUpgrade(v:unknown,s:WeeklyProfileUpgradeScope):WeeklyProfileUpgrade{if(!object(v)||Object.entries(s).some(([k,x])=>v[k]!==x)||!text(v.id)||v.version!==1||!/^\d{4}-\d{2}-\d{2}$/.test(v.targetWeekStart)||!['tone_clear_growth_stalled','history_material_or_engagement_insufficient'].includes(v.basis)||!text(v.reason)||!text(v.createdBy)||!instant(v.createdAt)||!hash(v.evidenceHash)||!Array.isArray(v.evidence)||!v.evidence.length||!object(v.policy)||v.policy.profile!=='b2b_established'||v.policy.allocationUnit!=='mother_content'||v.policy.ownedPercent!==(v.basis==='tone_clear_growth_stalled'?40:20)||v.policy.externalPercent!==(v.basis==='tone_clear_growth_stalled'?60:80)||!((v.confirmedBy===null&&v.confirmedAt===null)||(text(v.confirmedBy)&&instant(v.confirmedAt))))throw Error('画像建议与当前来源周或明确比例不一致。');const records=v.evidence.map(evidence);if(records.some(r=>r.gaps.some(g=>g!=='tone_handoff_unverified'||v.basis==='tone_clear_growth_stalled')||r.observationSeconds===null||Object.values(r.metrics).some(n=>n===null)||v.basis==='tone_clear_growth_stalled'&&!r.toneVerified))throw Error('画像建议的真实历史证据尚未齐全。');return v as WeeklyProfileUpgrade;}
const base=(s:WeeklyProfileUpgradeScope)=>`/api/overseas/social-programs/${encodeURIComponent(s.programId)}/operating-packages/${encodeURIComponent(s.packageId)}/profile-upgrades`;
async function call(url:string,input?:unknown){const headers=authHeader();const response=await fetch(url,{method:input?'POST':'GET',headers:{...headers,...(input?{'Content-Type':'application/json'}:{})},...(input?{body:JSON.stringify(input)}:{})});const data=await response.json();if(headers.Authorization!==authHeader().Authorization)throw Error('登录身份已变化，请只读刷新。');if(!response.ok)throw Error(data.error||data.message||'画像升级结果尚未核验。');return data;}
export const weeklyProfileUpgradeApi={
 async evidence(s:WeeklyProfileUpgradeScope){const data=await call(`${base(s)}/evidence?version=${s.packageVersion}`),v=data.item;if(!object(v)||v.thresholdPolicy!=='not_defined'||!/^\d{4}-\d{2}-\d{2}$/.test(v.targetWeekStart)||!Array.isArray(v.items))throw Error('下一周历史证据缺失。');return {targetWeekStart:v.targetWeekStart,items:v.items.map(evidence),thresholdPolicy:'not_defined' as const};},
 async list(s:WeeklyProfileUpgradeScope):Promise<WeeklyProfileUpgrade[]>{const data=await call(`${base(s)}?version=${s.packageVersion}`);if(!Array.isArray(data.items))throw Error('画像建议列表缺失。');return data.items.map((v:unknown)=>parseWeeklyProfileUpgrade(v,s));},
 async propose(s:WeeklyProfileUpgradeScope,input:{targetWeekStart:string;basis:WeeklyProfileUpgradeBasis;reason:string;selectedEvidenceRefs:string[]}){if(!input.reason.trim()||!input.selectedEvidenceRefs.length)throw Error('请明确历史判断及证据。');const data=await call(base(s),{packageVersion:s.packageVersion,...input});const item=parseWeeklyProfileUpgrade(data.item,s);if(item.targetWeekStart!==input.targetWeekStart||item.basis!==input.basis||item.reason!==input.reason.trim()||JSON.stringify([...item.evidence.map(e=>e.evidenceRef)].sort())!==JSON.stringify([...input.selectedEvidenceRefs].sort()))throw Error('建议回执与明确选择不一致。');return item;},
 async confirm(s:WeeklyProfileUpgradeScope,p:WeeklyProfileUpgrade){parseWeeklyProfileUpgrade(p,s);const data=await call(`${base(s)}/${encodeURIComponent(p.id)}/confirm`,{packageVersion:s.packageVersion,expectedVersion:p.version,evidenceHash:p.evidenceHash});const item=parseWeeklyProfileUpgrade(data.item,s);if(item.id!==p.id||item.evidenceHash!==p.evidenceHash||!item.confirmedBy||!item.confirmedAt)throw Error('明确确认回执尚未核验。');return item;}
};
