import {authHeader} from './auth';
import type {WeeklyPublicationExecutionDetail,WeeklyPublicationRecovery,WeeklyPublicationRecoveryScope,WeeklyPublicationRecoverySource} from '../../shared/contracts/weeklyPublicationRecovery';
export type {WeeklyPublicationExecutionDetail,WeeklyPublicationRecovery,WeeklyPublicationRecoveryScope,WeeklyPublicationRecoverySource};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim();
const date=(v:unknown)=>text(v)&&/(?:Z|[+-]\d{2}:\d{2})$/.test(v)&&Number.isFinite(Date.parse(v));
export function parsePublicationRecovery(value:unknown,scope:WeeklyPublicationRecoveryScope):WeeklyPublicationRecovery{
 if(!object(value)||Object.entries(scope).some(([k,v])=>value[k]!==v)||!Number.isSafeInteger(value.version)||Number(value.version)<1||!['awaiting_receipt','resume_requested'].includes(String(value.status))||!['id','taskId','publicationTaskId','motherContentId','assignmentId','publicationPackageId','productionResultId','accountId','platform','attemptId','attemptProvider','ownerUserId','createdBy','reason','originalTaskStatus'].every(k=>text(value[k]))||!date(value.deadlineAt)||!date(value.createdAt)||!date(value.attemptStartedAt)||typeof value.overdue!=='boolean'||typeof value.gap!=='string')throw Error('原发布异常身份或期限不一致。');
 for(const key of ['assignmentHash','publicationInputHash','taskInputHash','publicationPackageHash','accountIdentityHash'])if(typeof value[key]!=='string'||!/^[a-f0-9]{64}$/.test(String(value[key])))throw Error('原发布冻结证据缺失。');
 if(value.status==='resume_requested'&&!date(value.resumedAt))throw Error('原发布恢复请求时间缺失。');
 if(value.completionProof!==undefined){const p=value.completionProof;if(!object(p)||p.taskId!==value.taskId||p.attemptId!==value.attemptId||!text(p.platformPostId)||/^(mock|simulat)/i.test(p.platformPostId)||!text(p.providerReceiptId)||!date(p.verifiedAt)||!date(p.actualFinishedAt)||!/^[a-f0-9]{64}$/.test(String(p.evidenceHash))||value.originalTaskStatus!=='succeeded')throw Error('原发布完成凭据尚未核验。');}
 return value as unknown as WeeklyPublicationRecovery;
}
const base=(s:WeeklyPublicationRecoveryScope)=>`/api/overseas/social-programs/${encodeURIComponent(s.programId)}/operating-packages/${encodeURIComponent(s.packageId)}/publication-recoveries`;
async function request(url:string,body?:unknown){const headers=authHeader();const res=await fetch(url,{method:body?'POST':'GET',headers:{...headers,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await res.json();if(headers.Authorization!==authHeader().Authorization)throw Error('登录身份已变化，请只读刷新原发布任务。');if(!res.ok)throw Error(data.error||'发布异常任务请求失败。');return data;}
export const weeklyPublicationRecoveryApi={
 async detail(s:WeeklyPublicationRecoveryScope,taskId:string):Promise<WeeklyPublicationExecutionDetail>{const data=await request(`${base(s)}/execution/${encodeURIComponent(taskId)}?version=${s.packageVersion}`),item=data.item;if(!object(item)||Object.entries(s).some(([k,v])=>item[k]!==v)||item.taskId!==taskId||!['taskId','publicationTaskId','accountId','platform','assignmentId','assignmentHash','assignmentStatus','publicationPackageId','productionResultId','attemptId','attemptStatus','attemptProvider','attemptStartedAt','taskStatus','gap'].every(k=>text(item[k]))||!['in_flight','published','failed','unknown'].includes(String(item.attemptStatus))||!date(item.attemptStartedAt)||typeof item.canRecoverOriginalAttempt!=='boolean'||!['providerReceiptId','platformPostId','resolvedAt'].every(k=>item[k]===null||text(item[k]))||!(item.platformUrl===null||(text(item.platformUrl)&&/^https:\/\//.test(item.platformUrl)))||!/^[a-f0-9]{64}$/.test(String(item.assignmentHash)))throw Error('发布执行详情与当前任务身份不一致。');if(item.canRecoverOriginalAttempt&&(!['unknown','in_flight'].includes(String(item.attemptStatus))||!text(item.providerReceiptId)))throw Error('发布恢复入口不可核验。');return item as unknown as WeeklyPublicationExecutionDetail;},
 async list(s:WeeklyPublicationRecoveryScope):Promise<WeeklyPublicationRecovery[]>{const data=await request(`${base(s)}?version=${s.packageVersion}`);if(!Array.isArray(data.items))throw Error('发布异常列表缺失。');const items=data.items.map((v:unknown)=>parsePublicationRecovery(v,s));if(new Set(items.map((v:WeeklyPublicationRecovery)=>v.id)).size!==items.length)throw Error('发布异常身份重复。');return items;},
 async sources(s:WeeklyPublicationRecoveryScope):Promise<WeeklyPublicationRecoverySource[]>{const data=await request(`${base(s)}/sources?version=${s.packageVersion}`);if(!Array.isArray(data)||data.some((v:unknown)=>!object(v)||!['taskId','publicationTaskId','motherContentId','accountId','platform','attemptId','attemptStatus'].every(k=>text(v[k]))||typeof v.gap!=='string'))throw Error('原发布尝试来源缺失。');return data;},
 async create(s:WeeklyPublicationRecoveryScope,input:{taskId:string;ownerUserId:string;deadlineAt:string;reason:string}){if(!date(input.deadlineAt))throw Error('截止时间必须包含明确时区。');const data=await request(base(s),{packageVersion:s.packageVersion,...input});const item=parsePublicationRecovery(data.item,s);if(item.taskId!==input.taskId||item.ownerUserId!==input.ownerUserId||item.deadlineAt!==input.deadlineAt)throw Error('处理回执与原发布选择不一致。');return item;},
 async resolve(s:WeeklyPublicationRecoveryScope,item:WeeklyPublicationRecovery){const data=await request(`${base(s)}/${encodeURIComponent(item.id)}/resolve`,{packageVersion:s.packageVersion,expectedVersion:item.version});const next=parsePublicationRecovery(data.item,s);if(next.id!==item.id||next.attemptId!==item.attemptId||data.originalAttemptId!==item.attemptId||data.publishesSubmitted!==0)throw Error('原发布对账尚未核验，禁止重复提交发布。');return next;}
};
