import {WEEKLY_EXECUTION_TASK_STATUSES} from '../../shared/contracts/socialProgram';
import {authHeader,getToken} from './auth';
import type {SocialDirectorG5Scope} from '../../shared/contracts/socialDirectorG5Review';
import type {WeeklyContentQualityRecoveryContext,WeeklyContentQualityRecoveryRead,WeeklyContentQualityRecoveryReceipt} from '../../shared/contracts/weeklyContentQualityRecovery';
const object=(v:unknown):v is Record<string,any>=>!!v&&typeof v==='object'&&!Array.isArray(v),text=(v:unknown):v is string=>typeof v==='string'&&!!v.trim(),hash=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v),strings=(v:unknown)=>Array.isArray(v)&&v.every(text),positive=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0;
function scope(v:unknown,s:SocialDirectorG5Scope){if(!object(v)||Object.entries(s).some(([k,x])=>v[k]!==x))throw Error('周质量恢复与当前任务、运行或成片不一致。');return v;}
function receipt(v:unknown,s:SocialDirectorG5Scope){const r=scope(v,s);if(!['requestId','executionTaskId','programId','packageId','publicationTaskId','g5ReceiptId','g5ReviewId','recoveredBy'].every(k=>text(r[k]))||!positive(r.packageVersion)||!['expectedContextHash','sourceHash','recordHash','auditSourceHash','g5ReceiptHash','g5ReviewHash'].every(k=>hash(r[k]))||!text(r.recoveredAt)||!/(Z|[+-]\d{2}:\d{2})$/.test(r.recoveredAt)||!Number.isFinite(Date.parse(r.recoveredAt))||!object(r.artifactRef)||r.artifactRef.type!=='starter_social_content_artifact'||r.artifactRef.id!==s.artifactId||!positive(r.artifactRef.version))throw Error('实际周质量恢复凭据不完整。');return r as WeeklyContentQualityRecoveryReceipt;}
export function parseQualityRecoveryContext(v:unknown,s:SocialDirectorG5Scope):WeeklyContentQualityRecoveryContext{const c=scope(v,s);if(!hash(c.artifactHash)||!hash(c.sourceHash)||!object(c.artifactRef)||c.artifactRef.type!=='starter_social_content_artifact'||c.artifactRef.id!==s.artifactId||!positive(c.artifactRef.version)||!Array.isArray(c.consumers)||new Set(c.consumers.map((x:any)=>x?.executionTaskId)).size!==c.consumers.length)throw Error('实际周质量任务来源不可核验。');for(const t of c.consumers){if(!object(t)||!['executionTaskId','programId','packageId','publicationTaskId'].every(k=>text(t[k]))||!positive(t.packageVersion)||!['quality_check','rework'].includes(t.stepKind)||!WEEKLY_EXECUTION_TASK_STATUSES.includes(t.status)||!strings(t.ownBlockingReasons)||!strings(t.inheritedBlockingTaskIds)||!hash(t.contextHash)||typeof t.resumeAvailable!=='boolean'||!(t.gap===null||(object(t.gap)&&text(t.gap.code)&&text(t.gap.message)))||!Array.isArray(t.recoveries)||(t.resumeAvailable&&(t.status!=='blocked'||!t.ownBlockingReasons.includes('weekly_production_quality_review_required')||t.gap!==null)))throw Error('真实质量任务恢复条件不一致。');for(const r of t.recoveries){const actual=receipt(r,s);if(actual.executionTaskId!==t.executionTaskId||actual.programId!==t.programId||actual.packageId!==t.packageId||actual.packageVersion!==t.packageVersion||actual.publicationTaskId!==t.publicationTaskId)throw Error('原恢复记录与当前周质量任务不一致。');}}return c as WeeklyContentQualityRecoveryContext;}
export function parseQualityRecoveryRead(v:unknown,s:SocialDirectorG5Scope,executionTaskId:string,requestId:string):WeeklyContentQualityRecoveryRead{if(!object(v)||typeof v.currentSourceVerified!=='boolean'||!('item'in v)||!object(v.task)||(v.item===null&&v.currentSourceVerified))throw Error('原周质量恢复结果尚未查到。');const t=v.task;if(t.tenantId!==s.tenantId||t.taskId!==executionTaskId||t.workflowKind!=='content'||!['programId','packageId','publicationTaskId'].every(k=>text(t[k]))||!strings(t.ownBlockingReasons)||!strings(t.inheritedBlockingTaskIds)||!strings(t.dependsOnTaskIds)||!object(t.inputSnapshot)||!['quality_check','rework'].includes(t.schedule?.stepKind)||!positive(t.packageVersion)||!WEEKLY_EXECUTION_TASK_STATUSES.includes(t.status))throw Error('实际执行任务与指定质量恢复不一致。');if(v.item!==null){const r=receipt(v.item,s);if(r.requestId!==requestId||r.executionTaskId!==executionTaskId||r.programId!==t.programId||r.packageId!==t.packageId||r.packageVersion!==t.packageVersion||r.publicationTaskId!==t.publicationTaskId)throw Error('原恢复回执与真实周任务不一致。');}return v as WeeklyContentQualityRecoveryRead;}
function path(s:SocialDirectorG5Scope){return `/api/overseas/starter-198/social-content/tasks/${encodeURIComponent(s.taskId)}/runs/${encodeURIComponent(s.runId)}/artifacts/${encodeURIComponent(s.artifactId)}/weekly-quality-recovery`;}
async function request(s:SocialDirectorG5Scope,suffix:string,body?:object){const token=getToken();if(!token)throw Error('请登录后读取真实周质量任务。');const r=await fetch(path(s)+suffix,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',redirect:'error'});const v=await r.json();if(getToken()!==token)throw Error('登录身份已变化，请重新读取真实质量任务。');if(!r.ok)throw Error(typeof v?.message==='string'?v.message:'质量恢复结果待核验，请保留原请求。');return v;}
export const weeklyContentQualityRecoveryApi={async context(s:SocialDirectorG5Scope){const v=await request(s,'');return parseQualityRecoveryContext(v?.item,s);},async resume(s:SocialDirectorG5Scope,input:{executionTaskId:string;requestId:string;expectedContextHash:string}){return parseQualityRecoveryRead(await request(s,'/resume',{executionTaskId:input.executionTaskId,requestId:input.requestId,expectedContextHash:input.expectedContextHash}),s,input.executionTaskId,input.requestId);},async read(s:SocialDirectorG5Scope,executionTaskId:string,requestId:string){return parseQualityRecoveryRead(await request(s,`/requests/${encodeURIComponent(requestId)}?executionTaskId=${encodeURIComponent(executionTaskId)}`),s,executionTaskId,requestId);}};
