import {weeklyCustomerExceptionApprovalIdentity,type WeeklyCustomerExceptionApprovalReceipt} from '../../shared/contracts/weeklyCustomerKnowledgeQuote';
import {authHeader} from './auth';
import type {WeeklyCustomerExceptionScope as Scope,WeeklyCustomerExceptionRequest as Request,WeeklyCustomerExceptionView as View,WeeklyCustomerExceptionEvidenceRef as Ref,WeeklyCustomerExceptionKind as Kind} from '../../shared/contracts/weeklyCustomerKnowledgeQuote';
export type CustomerExceptionIdentity=Omit<Scope,'tenantId'>&{tenantId?:string};
function base(s:CustomerExceptionIdentity){return `/api/overseas/social-programs/${encodeURIComponent(s.programId)}/operating-packages/${encodeURIComponent(s.packageId)}/customer-knowledge-quote-requests`;}
export function assertCustomerExceptionScope(s:CustomerExceptionIdentity,actual:Scope){if(!actual?.tenantId||(s.tenantId!==undefined&&actual.tenantId!==s.tenantId)||actual.programId!==s.programId||actual.packageId!==s.packageId||actual.packageVersion!==s.packageVersion||actual.runId!==s.runId)throw Error('补齐回执不属于当前周运行。');}
async function call(s:CustomerExceptionIdentity,path:string,body?:object){if([s.programId,s.packageId,s.runId].some(v=>typeof v!=='string'||!v.trim())||!Number.isSafeInteger(s.packageVersion)||s.packageVersion<1)throw Error('当前周运行身份缺失。');const headers=authHeader();const res=await fetch(`${base(s)}${path}`,{method:body?'POST':'GET',headers:{...headers,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify({packageVersion:s.packageVersion,runId:s.runId,...body})}:{})});const data=await res.json();if(headers.Authorization!==authHeader().Authorization)throw Error('登录身份已变化，请重新读取。');if(!res.ok)throw Error(data.message||data.error||'补齐操作未确认，请只读恢复。');return data;}
function receipt(s:CustomerExceptionIdentity,item:Request,id?:string){assertCustomerExceptionScope(s,item?.scope);if(['requestId','recordHash','batchId','itemId','memberId','customerId','consumerInputHash','ownerUserId','reviewerUserId'].some(field=>typeof item[field as keyof Request]!=='string'||!String(item[field as keyof Request]).trim())||!['knowledge','quote'].includes(item.kind)||!['requested','pending_verification','verified','applying','applied'].includes(item.status)||!Number.isSafeInteger(item.version)||item.version<1||id&&item.requestId!==id)throw Error('真实补齐回执身份缺失。');if(item.submittedAt!==undefined&&item.submittedAt!==null&&!Number.isFinite(Date.parse(item.submittedAt)))throw Error('真实提交时间无效。');return item;}
function sameConsumer(s:CustomerExceptionIdentity,original:Request,next:Request){receipt(s,original);receipt(s,next,original.requestId);const fields=['kind','batchId','itemId','memberId','customerId','consumerInputHash','ownerUserId','reviewerUserId'] as const;if(next.scope.tenantId!==original.scope.tenantId||fields.some(field=>next[field]!==original[field])||next.version<original.version)throw Error('原消费者、成员、客户或补齐版本不一致。');return next;}
export const weeklyCustomerKnowledgeQuoteApi={
 async read(s:CustomerExceptionIdentity):Promise<View>{const {item}=await call(s,`?version=${s.packageVersion}&runId=${encodeURIComponent(s.runId)}`);assertCustomerExceptionScope(s,item?.scope);if(!item.actorUserId||!Array.isArray(item.requests)||!Array.isArray(item.candidates)||!Array.isArray(item.owners)||!Array.isArray(item.evidence)||!Array.isArray(item.gaps))throw Error('真实补齐来源列表缺失。');for(const r of item.requests)receipt(s,r);if(new Set(item.requests.map((r:Request)=>r.requestId)).size!==item.requests.length)throw Error('补齐请求身份重复，请重新读取。');return item;},
 async create(s:CustomerExceptionIdentity,input:{batchId:string;itemId:string;kind:Kind;ownerUserId:string;reviewerUserId:string;submissionDueAt:string;verificationDueAt:string}):Promise<Request>{const item=receipt(s,(await call(s,'',input)).item);if((['batchId','itemId','kind','ownerUserId','reviewerUserId'] as const).some(field=>item[field]!==input[field]))throw Error('新补齐请求与所选原条目或成员不一致。');return item;},
 async reviewKnowledgeItem(s:CustomerExceptionIdentity,r:Request,draft:{batchVersion:number;contentHash:string}):Promise<Request>{receipt(s,r);if(!Number.isSafeInteger(draft.batchVersion)||draft.batchVersion<1||!draft.contentHash)throw Error('知识草稿版本或内容身份缺失。');const data=await call(s,`/${encodeURIComponent(r.requestId)}/review-knowledge-item`,{expectedVersion:r.version,expectedBatchVersion:draft.batchVersion,expectedItemContentHash:draft.contentHash});const item=receipt(s,data.item,r.requestId);sameConsumer(s,r,item);if(data.messagesSent!==0||item.humanKnowledgeReview?.status!=='applied'||item.application?.batchId!==item.humanKnowledgeReview.toBatchId)throw Error('真人知识处理的新草稿回执不一致。');return item;},
 async requestApproval(s:CustomerExceptionIdentity,r:Request,reopenStateHash?:string):Promise<WeeklyCustomerExceptionApprovalReceipt>{receipt(s,r);if(r.status!=='applied'||!r.application?.batchId||!Number.isSafeInteger(r.application.batchVersion)||r.application.batchVersion<1||!r.verified||!r.itemId||!r.memberId||!r.customerId||!r.consumerInputHash||!['knowledge','quote'].includes(r.kind)||reopenStateHash!==undefined&&!reopenStateHash.trim())throw Error('审批必须绑定真实已应用草稿、原消费者及版本。');const expectedIdentity=weeklyCustomerExceptionApprovalIdentity(r,reopenStateHash?'reopen_for_approval':'request_approval');const data=await call(s,`/${encodeURIComponent(r.requestId)}/${reopenStateHash?'reopen-for-approval':'request-approval'}`,{expectedVersion:r.version,expectedIdentity,...(reopenStateHash?{expectedRunStateHash:reopenStateHash}:{})});const item=sameConsumer(s,r,receipt(s,data.item,r.requestId));const actionIdentity=data.actionIdentity;if(!actionIdentity||Object.keys(expectedIdentity).some(field=>field==='scope'?Object.keys(expectedIdentity.scope).some(key=>actionIdentity.scope?.[key]!==expectedIdentity.scope[key as keyof Scope]):actionIdentity[field]!==expectedIdentity[field as keyof typeof expectedIdentity])||typeof data.requestHash!=='string'||!data.requestHash.trim())throw Error('审批动作与原请求、消费者或版本回执不一致。');if(item.version!==r.version||item.recordHash!==r.recordHash||!item.application||Object.keys(r.application!).some(field=>item.application?.[field as keyof NonNullable<Request['application']>]!==r.application![field as keyof NonNullable<Request['application']>])||!data.approvalId||!data.approvalTaskId||data.runId!==s.runId||data.batchId!==r.application?.batchId||data.batchVersion!==r.application?.batchVersion||!data.contentHash||data.messagesSent!==0)throw Error('实际审批请求回执不一致。');return data;},
 async mutate(s:CustomerExceptionIdentity,r:Request,action:'submit'|'verify'|'apply',ref?:Ref):Promise<Request>{receipt(s,r);const data=await call(s,`/${encodeURIComponent(r.requestId)}/${action}`,{expectedVersion:r.version,...(action==='submit'?{ref}:{})});const next=sameConsumer(s,r,receipt(s,data.item,r.requestId));if(action==='apply'&&(data.messagesSent!==0||data.batch?.id!==next.application?.batchId))throw Error('真实草稿应用回执缺失。');return next;}
};
