import type {WeeklyCustomerRelationshipCheck} from '../../shared/contracts/customerRelationshipEvidence';
import { authHeader } from './auth';
import type { WeeklySalesHandoff, WeeklySalesSource } from '../../shared/contracts/socialWeeklySalesHandoff';
const path=(programId:string,packageId:string)=>`/api/overseas/social-programs/${encodeURIComponent(programId)}/operating-packages/${encodeURIComponent(packageId)}/sales-handoffs`;
async function request<T>(url:string,body?:unknown):Promise<T>{const r=await fetch(url,{method:body?'POST':'GET',headers:{...authHeader(),...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json().catch(()=>{throw Error('销售交接接口未返回真实数据。');});if(!r.ok)throw Error(data.error||'销售交接操作失败');return data as T;}
export const weeklySalesHandoffApi={
 list:async(p:string,k:string,v:number)=>{const r=await request<{items:WeeklySalesHandoff[]}>(`${path(p,k)}?version=${v}`);if(!Array.isArray(r.items)||!r.items.every(i=>i&&i.programId===p&&typeof i.id==='string'&&typeof i.tenantId==='string'&&typeof i.packageId==='string'&&Number.isSafeInteger(i.packageVersion)&&i.packageVersion>0&&typeof i.sourceEvidence==='object'))throw Error('缺少真实销售交接列表');return r.items;},
 sources:async(p:string,k:string,v:number)=>{const result=await request<{items:WeeklySalesSource[];gaps:string[];relationshipChecks?:WeeklyCustomerRelationshipCheck[]}>(`${path(p,k)}/sources?version=${v}`);if(!Array.isArray(result.items)||!Array.isArray(result.gaps)||!result.items.every(i=>i&&typeof i.runId==='string'&&typeof i.memberId==='string'&&typeof i.sourceInteractionId==='string'&&typeof i.body==='string'))throw Error('缺少真实询盘来源记录');if(result.relationshipChecks!==undefined&&(!Array.isArray(result.relationshipChecks)||!result.relationshipChecks.every(c=>c&&typeof c.customerId==='string'&&typeof c.memberId==='string'&&typeof c.runId==='string'&&typeof c.weekStart==='string'&&typeof c.weekEnd==='string'&&c.assessment?.customerId===c.customerId&&c.assessment.weekStart===c.weekStart&&c.assessment.weekEnd===c.weekEnd)))throw Error('客户关系绑定窗口缺失');return result;},
 create:(p:string,k:string,body:Record<string,unknown>)=>request<{item:WeeklySalesHandoff}>(path(p,k),body),
 transition:(item:WeeklySalesHandoff,body:Record<string,unknown>)=>request<{item:WeeklySalesHandoff}>(`${path(item.programId,item.packageId)}/${encodeURIComponent(item.id)}/events`,{packageVersion:item.packageVersion,...body}),
};
