import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseWeeklyCustomerSendRecovery,parseWeeklyCustomerSendRecoverySources,weeklyCustomerSendRecoveryApi as api} from './weeklyCustomerSendRecoveryApi';
const scope={tenantId:'tenant',programId:'program/a',packageId:'package/a',packageVersion:3};
const item={...scope,channel:'whatsapp',id:'recovery',runId:'run',taskId:'task',batchId:'batch',itemId:'item',customerId:'customer',ownerUserId:'owner',createdBy:'actor',deadlineAt:'2026-10-10T12:00:00Z',reason:'原发送结果未知',batchVersion:1,batchContentHash:'a'.repeat(64),itemContentHash:'b'.repeat(64),claimTokenHash:'c'.repeat(64),memberId:'member',recipientMasked:'…4567',recipientHash:'d'.repeat(64),sourceRef:{type:'weekly_customer_followup_batch',id:'batch',version:1},status:'awaiting_receipt',version:1,createdAt:'2026-10-10T00:00:00Z',resolvedAt:null};
const proof={taskId:'task',runId:'run',receiptIds:['receipt'],evidenceHash:'e'.repeat(64),verifiedAt:'2026-10-10T01:00:00Z'};
const source={channel:'whatsapp',runId:'run',taskId:'task',batchId:'batch',itemId:'item',customerId:'customer',memberId:'member',recipientMasked:'…4567',status:'blocked',claimTokenHash:'c'.repeat(64),batchVersion:1,reason:'send_outcome_unknown',canCreate:true};
test('recovery DTO enforces scope/source lineage and strips raw secrets',()=>{const parsed=parseWeeklyCustomerSendRecovery({...item,claimToken:'secret',recipient:'15551234567',sourceRef:{...item.sourceRef,secret:'secret'}},scope);assert.deepEqual(parsed,item);for(const bad of [{tenantId:'other'},{programId:'other'},{packageId:'other'},{packageVersion:4},{recipientMasked:'15551234567'},{claimTokenHash:'raw'},{sourceRef:{...item.sourceRef,id:'other'}},{resolvedAt:'invalid'},{version:0}])assert.throws(()=>parseWeeklyCustomerSendRecovery({...item,...bad},scope));assert.throws(()=>parseWeeklyCustomerSendRecovery(item,scope,'other'));});
test('sources is actual array, unique scoped safe records only',()=>{assert.deepEqual(parseWeeklyCustomerSendRecoverySources([{...source,claimToken:'secret',recipient:'15551234567'}],scope),[source]);for(const v of [{items:[source]},[source,source],[{...source,tenantId:'other'}],[{...source,canCreate:'yes'}],[{...source,recipientMasked:'15551234567'}]])assert.throws(()=>parseWeeklyCustomerSendRecoverySources(v,scope));});
test('HTTP explicit payloads, true sources/resolve shapes, no proof or send and session switch rejection',async()=>{const oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;let token='token';Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>token}});const calls:Array<{url:string;body:unknown}>=[];globalThis.fetch=async(url,init)=>{calls.push({url:String(url),body:init?.body?JSON.parse(String(init.body)):null});assert.equal((init?.headers as Record<string,string>).Authorization,'Bearer token');const value=String(url).includes('/sources')?[source]:String(url).includes('/resolve')?{item:{...item,status:'resolved',resolvedProof:proof,version:2,resolvedAt:'2026-10-10T01:00:00Z'},recoveredTaskId:'task',runAdvanced:false,messagesSent:0}:init?.method==='POST'?{item}:String(url).includes('/recovery?')?{item}:{items:[item]};return new Response(JSON.stringify(value));};try{assert.equal((await api.list(scope)).length,1);assert.equal((await api.sources(scope)).length,1);await api.get(scope,'recovery');await api.create(scope,{runId:'run',itemId:'item',ownerUserId:'owner',deadlineAt:item.deadlineAt,reason:item.reason,proof:'forged'} as never);assert.equal((await api.resolve(scope,'recovery',1)).messagesSent,0);assert.match(calls[0].url,/program%2Fa\/operating-packages\/package%2Fa\/send-recoveries\?version=3$/);assert.deepEqual(calls[3].body,{packageVersion:3,runId:'run',itemId:'item',ownerUserId:'owner',deadlineAt:item.deadlineAt,reason:item.reason});assert.deepEqual(calls[4].body,{packageVersion:3,expectedVersion:1});globalThis.fetch=async()=>{token='other';return new Response(JSON.stringify({items:[item]}));};await assert.rejects(()=>api.list(scope),/session_changed/);token='';await assert.rejects(()=>api.list(scope),/auth_required/);}finally{globalThis.fetch=oldFetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:oldStorage});}});
test('resolve rejects advancing/sending and wrong recovered task',async()=>{const oldFetch=globalThis.fetch,oldStorage=globalThis.localStorage;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=> 'token'}});try{for(const change of [{messagesSent:1},{runAdvanced:true},{recoveredTaskId:'other'},{item:{...item,status:'resolved',resolvedProof:proof,version:9,resolvedAt:'2026-10-10T01:00:00Z'}}]){globalThis.fetch=async()=>new Response(JSON.stringify({item:{...item,status:'resolved',resolvedProof:proof,version:2,resolvedAt:'2026-10-10T01:00:00Z'},recoveredTaskId:'task',runAdvanced:false,messagesSent:0,...change}));await assert.rejects(()=>api.resolve(scope,'recovery',1));}}finally{globalThis.fetch=oldFetch;Object.defineProperty(globalThis,'localStorage',{configurable:true,value:oldStorage});}});

test('resolved DTO requires actual proof matching the run/task with unique signed receipt references',()=>{
 const resolved={...item,status:'resolved',version:2,resolvedAt:'2026-10-10T01:00:00Z',resolvedProof:proof};
 assert.deepEqual(parseWeeklyCustomerSendRecovery({...resolved,resolvedProof:{...proof,claimToken:'secret'}},scope),resolved);
 for(const bad of [undefined,null,{...proof,taskId:'other'},{...proof,runId:'other'},{...proof,receiptIds:[]},{...proof,receiptIds:['r','r']},{...proof,evidenceHash:'raw'},{...proof,verifiedAt:'invalid'}])assert.throws(()=>parseWeeklyCustomerSendRecovery({...resolved,resolvedProof:bad},scope));
 assert.throws(()=>parseWeeklyCustomerSendRecovery({...item,resolvedProof:proof},scope));
});
