import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'ads-approvals-'));
process.env.LOCAL_STORE_DIR = directory;
process.env.PB_URL = 'http://127.0.0.1:1';
process.env.NODE_ENV = 'test';
process.env.META_ADS_API_VERSION = 'v99.0';
const originalFetch = globalThis.fetch;
try {
  const { store } = await import('../storage/index.js');
  const { encryptSecret } = await import('../lib/tenantPlatformApps.js');
  const { createPlatformAdTask, changePlatformAdManagement, getPlatformAdTask } = await import('./tasks.js');
  const { createAdApproval, decideAdApproval, listAdApprovals, reconcileAdApproval, AD_APPROVALS } = await import('./approvals.js');
  const connection = await store.create('platform_ad_connections', { tenant_id: 'tenant', provider: 'meta', accountId: '100', currency: 'USD', status: 'connected', tokenCipher: encryptSecret('fake-test-token') });
  const task = await createPlatformAdTask('tenant', 'user', { name: '测试', video: '测试视频', goal: '提升网站访问', market: '美国', budget: 500, channels: ['Facebook'] });
  const approvedTask = (await changePlatformAdManagement('tenant', 'user', task.id, { expectedVersion: task.version, managementMode: 'approval', authorization: { accountIds: [connection!.id], allowedActions: ['pause'], maxDailyBudget: 100, maxTotalBudget: 500, maxAdjustmentPercent: 20, expiresAt: new Date(Date.now() + 86400000).toISOString() } }))!;
  await store.create('platform_ad_executions', { tenant_id: 'tenant', taskId: task.id, connectionId: connection!.id, action: 'create', requestId: 'test_created', resourceId: '200', status: 'VERIFIED', createdAt: new Date().toISOString(), result: { campaignId: '200', adsetId: '300', adId: '400' } });
  const input = { expectedVersion: approvedTask.version, action: 'pause', connectionId: connection!.id, resourceId: '200' };
  const reject = await createAdApproval('tenant', 'user', task.id, input);
  assert.equal((await decideAdApproval('tenant', 'approver', task.id, reject.id, 'reject')).status, 'REJECTED');
  await assert.rejects(decideAdApproval('other-tenant', 'approver', task.id, reject.id, 'approve'), /未找到/);
  const expires = await createAdApproval('tenant', 'user', task.id, input);
  await store.update(AD_APPROVALS, expires.id, { expiresAt: new Date(Date.now() - 1000).toISOString() });
  assert.equal((await decideAdApproval('tenant', 'approver', task.id, expires.id, 'approve')).status, 'EXPIRED');
  const approval = await createAdApproval('tenant', 'user', task.id, input);
  let writes = 0;
  globalThis.fetch = (async (url: string | URL | Request, init?: RequestInit) => {
    const parsed = new URL(String(url));
    if (parsed.hostname !== 'graph.facebook.com') return originalFetch(url, init);
    if (init?.method === 'POST') writes++;
    return new Response(JSON.stringify(parsed.searchParams.get('fields') === 'account_id' ? { account_id: '100' } : { id: '200', status: 'PAUSED', success: true }), { status: 200 });
  }) as typeof fetch;
  const result = await decideAdApproval('tenant', 'approver', task.id, approval.id, 'approve');
  assert.equal(result.status, 'EXECUTED', JSON.stringify(result));
  assert.equal(writes, 1);
  const viewTask = await createPlatformAdTask('tenant', 'user', { name: '观看目标', video: '测试视频', goal: '提升有效视频观看', market: '美国', budget: 500, channels: ['Facebook'] });
  const viewApprovalTask = (await changePlatformAdManagement('tenant', 'user', viewTask.id, { expectedVersion: viewTask.version, managementMode: 'approval', authorization: { ...approvedTask.authorization, allowedActions: ['create'] } }))!;
  const viewApproval = await createAdApproval('tenant', 'user', viewTask.id, { expectedVersion: viewApprovalTask.version, action: 'create', connectionId: connection!.id, meta: { pageId: '101', videoId: '102', imageUrl: 'https://example.com/image.jpg', linkUrl: '', message: 'test', countries: ['US'], dailyBudget: 50 } });
  assert.equal((viewApproval.payload.meta as { linkUrl: string }).linkUrl, '', 'video-view approval does not require a website URL');
  await decideAdApproval('tenant', 'approver', task.id, approval.id, 'approve');
  assert.equal(writes, 1, 'repeat approval cannot repeat provider writes');
  await store.update(AD_APPROVALS, approval.id, { status: 'APPROVING' });
  assert.equal((await reconcileAdApproval('tenant', task.id, approval.id)).status, 'EXECUTED');
  assert.equal(writes, 1, 'approval recovery only reads receipts');
  const current = (await getPlatformAdTask('tenant', task.id))!;
  const pending = await createAdApproval('tenant', 'user', task.id, { ...input, expectedVersion: current.version });
  await changePlatformAdManagement('tenant', 'user', task.id, { expectedVersion: current.version, managementMode: 'manual' });
  assert.equal((await listAdApprovals('tenant', task.id)).find(r => r.id === pending.id)?.status, 'INVALIDATED');
  assert.equal((await decideAdApproval('tenant', 'approver', task.id, pending.id, 'approve')).status, 'INVALIDATED');
  assert.equal(writes, 1);
  await store.update('platform_ad_connections', connection!.id, { provider: 'tiktok' });
  await assert.rejects(createAdApproval('tenant', 'user', viewTask.id, { expectedVersion: viewApprovalTask.version, action: 'create', connectionId: connection!.id }), /仅支持 Meta/);
  console.log('platform ads approvals tests passed');
} finally { globalThis.fetch = originalFetch; fs.rmSync(directory, { recursive: true, force: true }); }
