import assert from 'node:assert/strict';
import { MetaAdsAdapter, AdProviderError, validateMetaVideoInput } from './metaAdapter.js';
process.env.META_ADS_API_VERSION = 'v25.0';
const calls: Array<{ url: string; init?: RequestInit }> = [];
const mock = (async (url: string | URL | Request, init?: RequestInit) => {
  calls.push({ url: String(url), init });
  if (init?.method === 'GET') return Response.json({ account_id: '1' });
  return Response.json({ id: String(100 + calls.length) });
}) as typeof fetch;
const adapter = new MetaAdsAdapter('secret-not-in-url', mock);
await assert.rejects(() => adapter.request('https://attacker.test'), AdProviderError);
await assert.rejects(() => adapter.setCampaignStatus('2', '33', 'ACTIVE'), /不属于/);
assert.equal(calls.length, 1);
assert.ok(!calls[0].url.includes('secret'));
const input = validateMetaVideoInput({ pageId: '1', videoId: '2', imageUrl: 'https://example.com/a.png', linkUrl: 'https://example.com', countries: ['US'], dailyBudget: 5 }, 100);
assert.throws(() => validateMetaVideoInput({ ...input, dailyBudget: 101 }, 100));
const ids: string[] = [];
await adapter.createPausedVideoTraffic('1', 'Test', input, 100, async (_kind, id) => { ids.push(id); });
assert.equal(ids.length, 4);
const campaign = new URLSearchParams(calls[1].init?.body as URLSearchParams);
assert.equal(campaign.get('status'), 'PAUSED');
assert.equal(campaign.get('spend_cap'), '10000');
for (const index of [1, 2, 4]) assert.equal(new URLSearchParams(calls[index].init?.body as URLSearchParams).get('status'), 'PAUSED');
const uncertain = new MetaAdsAdapter('token', (async () => { throw new Error('token'); }) as typeof fetch);
await assert.rejects(() => uncertain.request('123', { status: 'ACTIVE' }, 'POST'), (e: unknown) => e instanceof AdProviderError && e.uncertain && !e.message.includes('token'));
const denied = new MetaAdsAdapter('secret-token', (async () => Response.json({ error: { code: 10, error_subcode: 1341012, message: 'secret-token' } }, { status: 403 })) as typeof fetch);
await assert.rejects(() => denied.request('123', {}, 'POST'), (e: unknown) => e instanceof AdProviderError && e.code === '10' && e.message.includes('1341012') && !e.message.includes('secret-token') && !e.uncertain);
console.log('meta adapter tests passed');
