import {Router,type RequestHandler,type ErrorRequestHandler} from 'express';
import type {AuthLocals} from '../middleware/auth.js';import type {DataStore} from '../storage/datastore.js';
import {saveMaterialEvidenceConfiguration} from '../socialPrograms/materialEvidenceConfiguration.js';import {SocialProgramError} from '../socialPrograms/service.js';
const asyncRoute=(action:RequestHandler):RequestHandler=>(req,res,next)=>Promise.resolve(action(req,res,next)).catch(next);
/** Mount under authenticated /:programId/operating-packages/:packageId/material-evidence-configuration. Saves intent only; existing analysis is immutable. */
export function createSocialWeeklyMaterialEvidenceConfigurationRouter(store:DataStore){const router=Router({mergeParams:true});router.post('/',asyncRoute(async(req,res)=>{
 const auth=res.locals as AuthLocals;if(!auth.tenantId||!auth.userId)throw new SocialProgramError('material_evidence_configuration_auth_required',401,'请登录后配置真实素材需求。');const body=req.body;
 if(!body||typeof body!=='object'||Array.isArray(body)||Object.keys(body).some(k=>!['packageVersion','slotId','expectedPlanningVersion','decisions'].includes(k))||!Number.isSafeInteger(body.expectedPlanningVersion)||body.expectedPlanningVersion<1||typeof body.slotId!=='string'||!body.slotId.trim()||!Number.isSafeInteger(body.packageVersion)||body.packageVersion<1||!Array.isArray(body.decisions)||!body.decisions.length||body.decisions.length>100||body.decisions.some((d:any)=>!d||typeof d!=='object'||Array.isArray(d)||Object.keys(d).some(k=>!['requirementId','classification','reason','shotUsage'].includes(k))||typeof d.requirementId!=='string'||!d.requirementId.trim()||d.classification!=='human_irreplaceable'||typeof d.reason!=='string'||!d.reason.trim()||typeof d.shotUsage!=='string'||!d.shotUsage.trim()))throw new SocialProgramError('material_evidence_configuration_body_invalid',400,'请逐项提交真实素材用途与对应镜头说明；此入口不能把真实证据改成生成视觉。');
 const item=await saveMaterialEvidenceConfiguration(store,{tenantId:auth.tenantId,programId:String(req.params.programId||''),scope:{packageId:String(req.params.packageId||''),packageVersion:body.packageVersion,slotId:body.slotId},actorUserId:auth.userId,expectedPlanningVersion:body.expectedPlanningVersion,decisions:body.decisions});res.status(201).json({item,reanalysisRequired:true});
 }));const error:ErrorRequestHandler=(cause,_req,res,next)=>{if(cause instanceof SocialProgramError){res.status(cause.status).json({error:cause.code,message:cause.message});return;}next(cause);};router.use(error);return router;}
