import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import type { AddressInfo } from 'node:net';
import test from 'node:test';
import express from 'express';
import type { DataStore, ListQuery, Record_ } from '../storage/datastore.js';
import { createSocialWeeklyMaterialRequestsRouter } from './socialWeeklyMaterialRequests.js';
test('HTTP material requests enforce authenticated identity, explicit versions and real byte verification without completing production',async t=>{
 const rows=new Map<string,Record_[]>();let index=0;
 const store:DataStore={async getById<T>(c:string,id:string){return structuredClone(rows.get(c)?.find(r=>r.id===id)??null) as T|null;},async create<T>(c:string,data:Record<string,unknown>){const row={id:`row${++index}`,...structuredClone(data)} as Record_;rows.set(c,[...(rows.get(c)??[]),row]);return structuredClone(row) as T;},async update(c,id,data){const row=rows.get(c)?.find(r=>r.id===id);if(!row)return false;Object.assign(row,structuredClone(data));return true;},async delete(c,id){rows.set(c,(rows.get(c)??[]).filter(r=>r.id!==id));return true;},async list<T>(c:string,q:ListQuery={}){const items=(rows.get(c)??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));return {items:structuredClone(items.slice(0,q.perPage??30)) as T[],totalItems:items.length,totalPages:1,page:1,perPage:q.perPage??30};}};
 for(const id of ['reviewer','uploader'])await store.create('users',{id,tenantId:'tenant',role:'social_operator'});
 await store.create('users',{id:'other-user',tenantId:'other',role:'social_operator'});
 const execution={tenantId:'tenant',programId:'program',packageId:'week1',packageVersion:1,taskId:'material-step',publicationTaskId:'video-one',scope:'content',status:'blocked',schedule:{stepKind:'material_readiness'}};
 await store.create('social_weekly_execution_tasks',{tenant_id:'tenant',program_id:'program',package_id:'week1',package_version:1,task_id:'material-step',payload:execution});
 const bytes=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]);const hash=createHash('sha256').update(bytes).digest('hex');let reads=0;
 const app=express();app.use(express.json({strict:false}));app.use((req,res,next)=>{res.locals.tenantId=req.header('x-tenant')??'tenant';res.locals.userId=req.header('x-user')??'reviewer';next();});
 app.use('/:programId/material-requests',createSocialWeeklyMaterialRequestsRouter(store,{getMaterial:async(tenant,id)=>tenant==='tenant'&&id==='material0000001'?{id,tenantId:tenant,type:'image',scope:'own',sha256:hash,sizeBytes:bytes.length,videoFile:'product.png',sourceType:'licensed_upload'}:null,materialBytes:{fetch:async()=>{reads++;return new Response(bytes,{headers:{'content-type':'image/png','content-length':String(bytes.length)}});}}}));
 const server=app.listen(0,'127.0.0.1');await new Promise<void>(resolve=>server.once('listening',resolve));t.after(()=>server.close());
 const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}/program/material-requests`;
 const post=(path:string,body:unknown,user='reviewer',tenant='tenant')=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json','x-user':user,'x-tenant':tenant},body:JSON.stringify(body)});
 const create={requirementKey:'product-front',requirements:'正面产品清晰',assigneeUserId:'uploader',reviewerUserId:'reviewer',dueAt:'2026-10-10T08:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:'material-step',packageId:'week1',packageVersion:1,requirement:'产品正面镜头'}]};
 for(const invalid of [[],null,'invalid',{...create,tenantId:'other'},{...create,actorUserId:'uploader'}])assert.equal((await post('',invalid)).status,400);
 const created=await post('',create);assert.equal(created.status,201);const request=(await created.json()).item;
 assert.equal((await post('',create)).status,201);assert.equal((await store.list('social_weekly_material_requests')).totalItems,1);
 const foreign=await fetch(`${base}/${request.requestId}`,{headers:{'x-tenant':'other','x-user':'other-user'}});assert.equal(foreign.status,404);
 const submit={materialRecordIds:['material0000001'],expectedSubmissionVersion:0};
 assert.equal((await post(`/${request.requestId}/submissions`,submit)).status,403);
 assert.equal((await post(`/${request.requestId}/submissions`,{...submit,actorUserId:'uploader'},'uploader')).status,400);
 const submitted=await post(`/${request.requestId}/submissions`,submit,'uploader');assert.equal(submitted.status,200);assert.equal((await submitted.json()).item.status,'pending_verification');assert.equal(reads,1);
 assert.equal((await post(`/${request.requestId}/submissions`,submit,'uploader')).status,409);
 const review={submissionVersion:1,consumerDecisions:[{taskId:'material-step',accepted:true,factCheck:'与产品事实一致',rightsCheck:'企业上传并授权',visualCheck:'清晰符合镜头要求'}]};
 assert.equal((await post(`/${request.requestId}/reviews`,review,'uploader')).status,403);
 assert.equal((await post(`/${request.requestId}/reviews`,{...review,submissionVersion:2})).status,409);
 const reviewed=await post(`/${request.requestId}/reviews`,review);assert.equal(reviewed.status,200);assert.equal((await reviewed.json()).item.status,'accepted');assert.equal(reads,2);
 assert.deepEqual((await store.list<Record_>('social_weekly_execution_tasks')).items[0]!.payload,execution,'material acceptance must not fake production completion');
 await store.update('users','reviewer',{disabled:true});assert.equal((await fetch(`${base}/${request.requestId}`)).status,403);
});
