import {Router,type RequestHandler,type ErrorRequestHandler} from 'express';import type {AuthLocals} from '../middleware/auth.js';import type {DataStore} from '../storage/datastore.js';import {createCustomerFeedbackTopicService} from '../socialPrograms/customerFeedbackTopics.js';import {SocialProgramError} from '../socialPrograms/service.js';
const invalid=():never=>{throw new SocialProgramError('customer_feedback_topic_body_invalid',400,'请选择真实买家问题与明确的下周排期。');};const text=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():invalid();const integer=(v:unknown,min=1)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=min?v:invalid();const body=(v:unknown,keys:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!keys.includes(k)))return invalid();return v as Record<string,unknown>;};const route=(f:RequestHandler):RequestHandler=>(req,res,next)=>Promise.resolve(f(req,res,next)).catch(next);
/** Authenticated /:programId/customer-feedback-topics. Confirmation is a proposal for the next immutable revision, not effective production authorization. */
export function createSocialCustomerFeedbackTopicsRouter(store:DataStore){const router=Router({mergeParams:true});const service=createCustomerFeedbackTopicService(store);const scope=(req:Parameters<RequestHandler>[0],res:Parameters<RequestHandler>[1])=>{const a=res.locals as AuthLocals;if(!a.tenantId||!a.userId)throw new SocialProgramError('customer_feedback_topic_auth_required',401,'请登录后选择客户反馈。');return {tenantId:a.tenantId,programId:text(req.params.programId),actorUserId:a.userId};};
 router.get('/',route(async(req,res)=>{res.json(await service.list(scope(req,res)));}));
 router.get('/sources',route(async(req,res)=>res.json(await service.sources({...scope(req,res),sourcePackageId:text(req.query.sourcePackageId),sourcePackageVersion:integer(typeof req.query.sourcePackageVersion==='string'&&/^\d+$/.test(req.query.sourcePackageVersion)?Number(req.query.sourcePackageVersion):req.query.sourcePackageVersion)}))));
 router.get('/confirmations',route(async(req,res)=>res.json(await service.confirmations(scope(req,res)))));
 router.get('/:candidateId',route(async(req,res)=>{const a=scope(req,res);res.json({item:await service.get(a.tenantId,a.programId,text(req.params.candidateId),a.actorUserId)});}));
 router.post('/',route(async(req,res)=>{const b=body(req.body,['sourcePackageId','sourcePackageVersion','handoffId','interactionId','excerptStart','excerptEnd','topicAngle']);res.status(201).json({item:await service.create({...scope(req,res),sourcePackageId:text(b.sourcePackageId),sourcePackageVersion:integer(b.sourcePackageVersion),handoffId:text(b.handoffId),interactionId:text(b.interactionId),excerptStart:integer(b.excerptStart,0),excerptEnd:integer(b.excerptEnd,1),topicAngle:text(b.topicAngle)})});}));
 router.post('/:candidateId/confirm',route(async(req,res)=>{const b=body(req.body,['targetPackageId','expectedTargetPackageVersion','publicationTaskId']);const item=await service.proposeNextRevision({...scope(req,res),candidateId:text(req.params.candidateId),targetPackageId:text(b.targetPackageId),expectedTargetPackageVersion:integer(b.expectedTargetPackageVersion),publicationTaskId:text(b.publicationTaskId)});res.json({item,publicationPatch:{publicationTaskId:item.target.publicationTaskId,customerFeedbackTopicRef:{type:'customer_feedback_topic_confirmation',id:item.id,version:1}},planningRevisionRequired:true});}));
 const errors:ErrorRequestHandler=(error,_req,res,next)=>{if(error instanceof SocialProgramError){res.status(error.status).json({error:error.code,message:error.message});return;}next(error);};router.use(errors);return router;}
