import type {SocialInstagramDelivery,SocialInstagramDeliveryReview} from './socialInstagramDelivery.js';
export const WEEKLY_G6_CHECK_CODES=['account','platform_format','conversion_route','sales_owner','weekly_authorization'] as const;
export type WeeklyG6CheckCode=typeof WEEKLY_G6_CHECK_CODES[number];
export interface SocialWeeklyG6Scope {tenantId:string;taskId:string;runId:string;artifactId:string;programId:string;packageId:string;packageVersion:number;publicationTaskId:string}
export interface SocialOwnedVideoMetadata {videoBitrateBitsPerSecond?:number|null;audioBitrateBitsPerSecond?:number|null;audioSampleRateHz?:number|null;audioChannels?:number|null;videoPixelFormat?:string|null;videoScanMode?:'progressive'|'interlaced'|null;audioEvidenceKind?:'input_stream_descriptor'|null;fileSha256:string;bytes:number;container:'mp4'|'mov'|'webm'|null;videoCodec:string;width:number;height:number;framesPerSecond:number;durationSeconds:number;audioCodec:string|null;probeTool:string;probeVersion:string;recordHash:string}
export interface SocialWeeklyG6Check {code:WeeklyG6CheckCode;status:'passed'|'blocked'|'unknown';reasons:string[];evidenceRefs:string[]}
export interface SocialWeeklyG6Context extends SocialWeeklyG6Scope {instagramDelivery?:{item:SocialInstagramDelivery;reviews:SocialInstagramDeliveryReview[]}|null;sourceHash:string;contextHash:string;artifactHash:string;fileRef:string;fileSha256:string;previewUrl:string;handoffId:string;handoffVersion:string;productionResultId:string;productionResultHash:string;platform:'tiktok'|'instagram'|'facebook'|'youtube';accountId:string;accountIdentityHash:string|null;nativeAccountId:string|null;plannedPublishWindow:string|null;metadata:SocialOwnedVideoMetadata|null;checks:SocialWeeklyG6Check[];gaps:string[];assignmentRef:{assignmentId:string;assignmentHash:string}|null}
export interface SocialWeeklyG6Review extends SocialWeeklyG6Scope {reviewId:string;requestId:string;version:1;sourceHash:string;contextHash:string;requestedBy:string;requestedAt:string;checks:SocialWeeklyG6Check[];status:'passed'|'blocked'|'unknown';receiptId:string|null;receiptHash:string|null;recordHash:string}
export interface SocialWeeklyG6ReviewRead {item:SocialWeeklyG6Review|null;projectionStatus:'not_found'|'pending'|'applied';currentSourceVerified:boolean}
