import {useEffect,useRef,useState} from 'react';
import {getToken} from '../../lib/auth';
import {nextWeekCreationHash} from '../../lib/nextWeekProfilePackage';
import {socialWeeklyG6ReviewApi as api} from '../../lib/socialWeeklyG6ReviewApi';
import type {SocialWeeklyG6Scope,SocialWeeklyG6Context,SocialWeeklyG6ReviewRead} from '../../../shared/contracts/socialWeeklyG6Review';
const labels={account:'发布账号与连接',platform_format:'平台格式与成片',conversion_route:'咨询承接入口',sales_owner:'接待负责人',weekly_authorization:'本周发布许可'};
interface Intent{requestId:string;inputHash:string;sourceHash:string}
function intent(key:string):Intent|null{const raw=sessionStorage.getItem(key);if(raw===null)return null;const v=JSON.parse(raw);if(!v||typeof v.requestId!=='string'||!/^[a-zA-Z0-9_-]{16,160}$/.test(v.requestId)||!['inputHash','sourceHash'].every(k=>typeof v[k]==='string'&&/^[a-f0-9]{64}$/.test(v[k])))throw Error('原预检提交索引损坏，请保留原记录，不重复提交。');return v;}
export function SocialWeeklyG6ReviewPanel({scope,onChanged}:{scope:SocialWeeklyG6Scope;onChanged?:()=>void}){
 const identity=JSON.stringify(scope),token=getToken(),current=useRef('');current.current=identity+token;const [context,setContext]=useState<SocialWeeklyG6Context|null>(null),[record,setRecord]=useState<SocialWeeklyG6ReviewRead|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Intent|null>(null),[damaged,setDamaged]=useState(false),[resumeUnknown,setResumeUnknown]=useState(false);const write=useRef(false),latest=useRef(context);latest.current=context;const key=`weekly-g6:${identity}:${token}:${context?.sourceHash??'unread'}`,active=()=>current.current===identity+token&&getToken()===token;
 useEffect(()=>{setContext(null);setRecord(null);setError('');setBusy(false);void api.context(scope).then(c=>{if(active())setContext(c);}).catch(e=>{if(active())setError(e instanceof Error?e.message:'发布预检条件尚未查到。');});},[identity,token]);
 useEffect(()=>{setRecord(null);setPending(null);setDamaged(false);if(!context)return;try{setPending(intent(key));setResumeUnknown(sessionStorage.getItem(key+':resume')==='unknown');}catch(e){setDamaged(true);setError(e instanceof Error?e.message:'原预检索引待核验。');}},[key]);
 async function refresh(){if(write.current)return;write.current=true;setBusy(true);try{const c=await api.context(scope);if(active())setContext(c);}catch(e){if(active())setError(e instanceof Error?e.message:'发布条件刷新失败。');}finally{write.current=false;if(active())setBusy(false);}}

 async function verify(r:SocialWeeklyG6ReviewRead,p:Intent){if(!r.item)return;if(r.item.sourceHash!==p.sourceHash||await nextWeekCreationHash({programId:scope.programId,packageId:scope.packageId,packageVersion:scope.packageVersion,publicationTaskId:scope.publicationTaskId,requestId:p.requestId,expectedContextHash:r.item.contextHash})!==p.inputHash)throw Error('预检回执与原目标或冻结提交不一致。');}
 async function command(mode:'check'|'read'|'resume'){if(write.current||!context||damaged)return;write.current=true;setBusy(true);setError('');const original=context;try{let p=intent(key);if(mode==='check'){if(p)throw Error('原预检已提交，请查询原请求。');const requestId=crypto.randomUUID(),body={programId:scope.programId,packageId:scope.packageId,packageVersion:scope.packageVersion,publicationTaskId:scope.publicationTaskId,requestId,expectedContextHash:original.contextHash};p={requestId,inputHash:await nextWeekCreationHash(body),sourceHash:original.sourceHash};if(!active()||latest.current?.contextHash!==original.contextHash||intent(key))throw Error('发布目标已变化，请重新读取。');sessionStorage.setItem(key,JSON.stringify(p));setPending(p);}if(!p)throw Error('原预检请求尚未查到。');if(mode==='resume'){if(resumeUnknown||record?.projectionStatus!=='pending'||!record.item||!record.currentSourceVerified)throw Error('原预检暂不能同步，请只读查询。');sessionStorage.setItem(key+':resume','unknown');setResumeUnknown(true);}const r=mode==='check'?await api.check(scope,original,p.requestId):mode==='read'?await api.read(scope,p.requestId):await api.resume(scope,p.requestId);await verify(r,p);if(active()){setRecord(r);if(r.projectionStatus==='applied'){setResumeUnknown(false);sessionStorage.removeItem(key+':resume');}if(mode!=='read')onChanged?.();}}catch(e){if(active())setError(e instanceof Error?e.message:'结果未知，请查询原预检。');}finally{write.current=false;if(active())setBusy(false);}}
 return <section className="rounded-xl border p-4 space-y-3" aria-label="本周发布五项预检"><h3>本周发布预检</h3><p>核验当前成片与已选择的本周发布目标。预检通过后，仍须按原流程明确批准发布。</p>{error&&<p role="alert">{error}</p>}{!context?<p>正在读取实际发布条件。</p>:<><p>{context.platform} · {context.nativeAccountId?'已核验平台账号':'账号身份待核验'} · {context.plannedPublishWindow?`计划发布：${context.plannedPublishWindow}`:'发布时间待明确'}</p><p>{context.metadata?`${context.metadata.width} × ${context.metadata.height} · ${context.metadata.durationSeconds} 秒 · 实际成片已检测`:'缺少实际成片检测结果，不能当作已通过。'}</p>{(record?.item?.checks??context.checks).map(c=><article key={c.code}><strong>{labels[c.code]} · {c.status==='passed'?'通过':c.status==='blocked'?'受阻':'待核验'}</strong>{c.reasons.map((reason,i)=><p key={i}>{reason}</p>)}<p>{c.evidenceRefs.length?'已有实际来源凭据':'缺少可核验来源'}</p></article>)}{context.gaps.length>0&&<p>仍有发布条件缺口，请在对应配置入口处理后重新读取。</p>}{record?.item&&<p>{!record.currentSourceVerified?'原预检来源已变化，不能用于当前发布。':record.item.status==='passed'?'五项预检通过；尚未发布。':record.item.status==='blocked'?'五项预检仍受阻；尚未发布。':'部分条件尚不明确；尚未发布。'}</p>}<button disabled={busy} onClick={()=>void refresh()}>重新读取实际发布条件</button><button disabled={busy||damaged||!!pending} onClick={()=>void command('check')}>明确核验五项发布条件</button>{pending&&<button disabled={busy||damaged} onClick={()=>void command('read')}>查询原发布预检</button>}{record?.item&&record.projectionStatus==='pending'&&<button disabled={busy||resumeUnknown||!record.currentSourceVerified} onClick={()=>void command('resume')}>明确同步原预检结果</button>}{resumeUnknown&&<p>同步结果待查询，不重复操作。</p>}</>}</section>;
}
