import {SocialInstagramDeliveryPanel} from './SocialInstagramDeliveryPanel';
import {useEffect,useRef,useState} from 'react';
import {getToken} from '../../lib/auth';
import {readWeeklyG6Intent,freezeWeeklyG6Intent,verifyWeeklyG6Intent,type WeeklyG6Intent as Intent} from '../../lib/socialWeeklyG6ReviewIntent';
import {socialWeeklyG6ReviewApi as api} from '../../lib/socialWeeklyG6ReviewApi';
import type {SocialWeeklyG6Scope,SocialWeeklyG6Context,SocialWeeklyG6ReviewRead} from '../../../shared/contracts/socialWeeklyG6Review';
const labels={account:'发布账号与连接',platform_format:'平台格式与成片',conversion_route:'咨询承接入口',sales_owner:'接待负责人',weekly_authorization:'本周发布许可'};
function reasonLabel(code:string){const labels:Record<string,string>={actual_account_not_connected_or_native_identity_missing:'发布账号尚未连接，或缺少可核验的平台身份。',actual_reception_binding_scope_or_hash_changed:'承接配置与当前发布版本不一致，请重新明确绑定。',actual_reception_check_unavailable:'承接入口暂未取得实际可用性结果。',explicit_required_reception_sales_owner_missing:'尚未明确必要承接入口与接待负责人。',assigned_reception_owner_not_enabled_for_sales:'指定接待人不可用或没有相应接待权限。',explicit_weekly_publish_authorization_missing_or_revoked:'本周真实发布尚未获得许可，或许可已撤回。',planned_publish_window_outside_explicit_week_authorization:'发布时间不在已明确允许的本周范围内。',account_or_quota_outside_explicit_week_authorization:'发布账号或条数超出本周明确许可。',actual_weekly_authorizer_or_time_unverified:'发布许可的确认人或确认时间尚未核验。',actual_weekly_authorizer_disabled:'原发布确认人当前不可用。',published_delivery_scan_incomplete:'已发布记录未能完整读取，不能确定剩余条数。',assignment_scan_incomplete:'本周发布安排未能完整读取。',actual_published_count_exhausts_authorization:'本周已发布条数已达到许可上限。'};return labels[code]??'本项实际核验条件尚未齐全，请处理对应配置后重新读取。';}
const intent=(key:string)=>readWeeklyG6Intent(sessionStorage,key);
export function SocialWeeklyG6ReviewPanel({scope,onChanged}:{scope:SocialWeeklyG6Scope;onChanged?:()=>void}){
 const identity=JSON.stringify(scope),token=getToken(),current=useRef('');current.current=identity+token;const [context,setContext]=useState<SocialWeeklyG6Context|null>(null),[record,setRecord]=useState<SocialWeeklyG6ReviewRead|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Intent|null>(null),[damaged,setDamaged]=useState(false),[resumeUnknown,setResumeUnknown]=useState(false);const write=useRef(false),latest=useRef(context);latest.current=context;const key=`weekly-g6:${identity}:${token}:${context?.sourceHash??'unread'}`,active=()=>current.current===identity+token&&getToken()===token;
 useEffect(()=>{setContext(null);setRecord(null);setError('');setBusy(false);void api.context(scope).then(c=>{if(active())setContext(c);}).catch(e=>{if(active())setError(e instanceof Error?e.message:'发布预检条件尚未查到。');});},[identity,token]);
 useEffect(()=>{setRecord(null);setPending(null);setDamaged(false);if(!context)return;try{setPending(intent(key));setResumeUnknown(sessionStorage.getItem(key+':resume')==='unknown');}catch(e){setDamaged(true);setError(e instanceof Error?e.message:'原预检索引待核验。');}},[key]);
 async function refresh(){if(write.current)return;write.current=true;setBusy(true);try{const c=await api.context(scope);if(active())setContext(c);}catch(e){if(active())setError(e instanceof Error?e.message:'发布条件刷新失败。');}finally{write.current=false;if(active())setBusy(false);}}

 async function command(mode:'check'|'read'|'resume'){if(write.current||!context||damaged)return;write.current=true;setBusy(true);setError('');const original=context;try{let p=intent(key);if(mode==='check'){if(p)throw Error('原预检已提交，请查询原请求。');const requestId=crypto.randomUUID();if(!active()||latest.current?.contextHash!==original.contextHash||intent(key))throw Error('发布目标已变化，请重新读取。');p=await freezeWeeklyG6Intent(sessionStorage,key,scope,original,requestId);if(!active()||latest.current?.contextHash!==original.contextHash)throw Error('发布目标已变化，请查询原预检，不重复提交。');setPending(p);}if(!p)throw Error('原预检请求尚未查到。');if(mode==='resume'){if(resumeUnknown||record?.projectionStatus!=='pending'||!record.item||!record.currentSourceVerified)throw Error('原预检暂不能同步，请只读查询。');sessionStorage.setItem(key+':resume','unknown');setResumeUnknown(true);}const r=mode==='check'?await api.check(scope,original,p.requestId):mode==='read'?await api.read(scope,p.requestId):await api.resume(scope,p.requestId);await verifyWeeklyG6Intent(scope,p,r);if(active()){setRecord(r);if(r.projectionStatus==='applied'){setResumeUnknown(false);sessionStorage.removeItem(key+':resume');}if(mode!=='read')onChanged?.();}}catch(e){if(active())setError(e instanceof Error?e.message:'结果未知，请查询原预检。');}finally{write.current=false;if(active())setBusy(false);}}
 return <section className="rounded-xl border p-4 space-y-3" aria-label="本周发布五项预检"><h3>本周发布预检</h3><p>核验当前成片与已选择的本周发布目标。预检通过后，仍须按原流程明确批准发布。</p>{error&&<p role="alert">{error}</p>}{!context?<p>正在读取实际发布条件。</p>:<><p>{context.platform} · {context.nativeAccountId?'已核验平台账号':'账号身份待核验'} · {context.plannedPublishWindow?`计划发布：${context.plannedPublishWindow}`:'发布时间待明确'}</p><p>{context.metadata?`${context.metadata.width} × ${context.metadata.height} · ${context.metadata.durationSeconds} 秒 · 实际成片已检测`:'缺少实际成片检测结果，不能当作已通过。'}</p>{(record?.item?.checks??context.checks).map(c=><article key={c.code}><strong>{labels[c.code]} · {c.status==='passed'?'通过':c.status==='blocked'?'受阻':'待核验'}</strong>{c.reasons.map((reason,i)=><p key={i}>{reasonLabel(reason)}</p>)}<p>{c.evidenceRefs.length?'已有实际来源凭据':'缺少可核验来源'}</p></article>)}{context.platform==='instagram'&&<SocialInstagramDeliveryPanel scope={scope} context={context} onChanged={()=>{void refresh();onChanged?.();}}/>}{context.gaps.length>0&&<p>仍有发布条件缺口，请在对应配置入口处理后重新读取。</p>}{record?.item&&<p>{!record.currentSourceVerified?'原预检来源已变化，不能用于当前发布。':record.item.status==='passed'?'五项预检通过；尚未发布。':record.item.status==='blocked'?'五项预检仍受阻；尚未发布。':'部分条件尚不明确；尚未发布。'}</p>}<button disabled={busy} onClick={()=>void refresh()}>重新读取实际发布条件</button><button disabled={busy||damaged||!!pending} onClick={()=>void command('check')}>明确核验五项发布条件</button>{pending&&<button disabled={busy||damaged} onClick={()=>void command('read')}>查询原发布预检</button>}{record?.item&&record.projectionStatus==='pending'&&<button disabled={busy||resumeUnknown||!record.currentSourceVerified} onClick={()=>void command('resume')}>明确同步原预检结果</button>}{resumeUnknown&&<p>同步结果待查询，不重复操作。</p>}</>}</section>;
}
