import {useEffect,useRef,useState} from 'react';
import {getToken} from '../../lib/auth';
import {socialInstagramDeliveryApi as api} from '../../lib/socialInstagramDeliveryApi';
import type {SocialWeeklyG6Context,SocialWeeklyG6Scope} from '../../../shared/contracts/socialWeeklyG6Review';
import {INSTAGRAM_DELIVERY_TECHNICAL_CHECKS,INSTAGRAM_DELIVERY_CREATIVE_CHECKS,type SocialInstagramDeliveryRead,type InstagramDeliveryReviewKind,type InstagramDeliveryObservation} from '../../../shared/contracts/socialInstagramDelivery';
type Intent={requestId:string;contextHash:string;kind:'prepare'|InstagramDeliveryReviewKind;deliveryHash?:string;checks?:InstagramDeliveryObservation[]};
export function SocialInstagramDeliveryPanel({scope,context,onChanged}:{scope:SocialWeeklyG6Scope;context:SocialWeeklyG6Context;onChanged?:()=>void}){
 const token=getToken(),identity=JSON.stringify(scope)+token,current=useRef(identity);current.current=identity;const active=()=>current.current===identity&&getToken()===token;const [read,setRead]=useState<SocialInstagramDeliveryRead|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<Intent|null>(null),[kind,setKind]=useState<InstagramDeliveryReviewKind>('technical'),[checks,setChecks]=useState<InstagramDeliveryObservation[]>([]),[preview,setPreview]=useState('');const lock=useRef(false),latestContext=useRef(context.contextHash);latestContext.current=context.contextHash;const key='instagram-delivery:'+JSON.stringify(scope);const authHash=async()=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token??'')))).map(x=>x.toString(16).padStart(2,'0')).join('');const codes=kind==='technical'?INSTAGRAM_DELIVERY_TECHNICAL_CHECKS:INSTAGRAM_DELIVERY_CREATIVE_CHECKS;
 useEffect(()=>{setChecks(codes.map(code=>({code,outcome:'unknown',observation:''})));},[kind]);
 useEffect(()=>{setRead(null);setPending(null);setPreview('');setError('');void authHash().then(h=>{if(!active())return;try{const stored=sessionStorage.getItem(key);if(stored){const p=JSON.parse(stored);if(p.authHash===h)setPending(p.intent);else {setPending({requestId:'identity_changed',contextHash:'',kind:'prepare'});setError('原操作属于其他登录身份，请只读核验。');}}}catch{setPending({requestId:'unreadable',contextHash:'',kind:'prepare'});setError('原操作索引不可读取，请只读核验。');}});void api.read(scope).then(v=>{if(active())setRead(v);}).catch(e=>{if(active())setError(String(e.message));});},[identity]);
 async function act(mode:'read'|'prepare'|'review'){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{let p=pending;if(mode!=='read'){if(p||sessionStorage.getItem(key))throw Error('原操作结果待查询，不重复提交。');p={requestId:crypto.randomUUID(),contextHash:context.contextHash,kind:mode==='prepare'?'prepare':kind,...(mode==='review'?{deliveryHash:read?.item?.recordHash,checks}: {})};if(mode==='review'&&(!read?.currentSourceVerified||!p.deliveryHash||checks.some(c=>!c.observation.trim())))throw Error('请逐项观察实际包装并填写结论。');const h=await authHash();if(!active()||latestContext.current!==p.contextHash)throw Error('登录或目标已变化，请重新读取。');sessionStorage.setItem(key,JSON.stringify({authHash:h,intent:p}));setPending(p);}
 const v=mode==='read'?await api.read(scope):mode==='prepare'?await api.prepare(scope,p!.requestId,p!.contextHash):await api.review(scope,p!.requestId,p!.deliveryHash!,p!.kind as InstagramDeliveryReviewKind,p!.checks!);if(!active())return;setRead(v);if(p){const recovered=p.kind==='prepare'?v.item?.requestId===p.requestId&&v.item.sourceContextHash===p.contextHash:v.reviews.some(r=>r.requestId===p.requestId&&r.kind===p.kind&&r.deliveryHash===p.deliveryHash&&JSON.stringify(r.checks)===JSON.stringify(p.checks));if(recovered){sessionStorage.removeItem(key);setPending(null);}else setError('原请求尚未读到，继续只读查询，不重复提交。');}if(mode!=='read')onChanged?.();}catch(e){if(active())setError(e instanceof Error?e.message:'结果未知，请查询原请求。');}finally{lock.current=false;if(active())setBusy(false);}}
 async function loadPreview(){if(!read?.previewUrl||!read.item)return;try{const r=await fetch(read.previewUrl,{headers:(await import('../../lib/auth')).authHeader(),cache:'no-store',redirect:'error'});const previewHash=read.item.fileSha256;const bytes=await r.arrayBuffer();const actual=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');if(!r.ok||r.headers.get('X-Content-SHA256')!==previewHash||actual!==previewHash)throw Error('包装预览字节与归档不一致。');if(active()&&getToken()===token)setPreview(URL.createObjectURL(new Blob([bytes],{type:'video/mp4'})));}catch(e){if(active())setError(String((e as Error).message));}}
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 return <section aria-label="Instagram 实际包装" className="border rounded-xl p-3 space-y-2"><h4>Instagram 发布包装</h4><p>保留原成片来源，单独归档转换后的发布文件。包装后须重新核验画面和创意，仍需最终批准。</p>{error&&<p role="alert">{error}</p>}<button disabled={busy} onClick={()=>void act('read')}>读取包装与原请求</button><button disabled={busy||!!pending||!!read?.item} onClick={()=>void act('prepare')}>明确准备并归档包装</button>{pending&&<p>原操作结果待查询，暂不重复提交。</p>}{read?.item&&<><p>原成片 SHA：{read.item.sourceFileSha256}；包装 SHA：{read.item.fileSha256}</p><button onClick={()=>void loadPreview()}>读取实际包装预览</button>{preview&&<video controls src={preview}/>}<select value={kind} onChange={e=>setKind(e.target.value as InstagramDeliveryReviewKind)}><option value="technical">真人技术核验（七项）</option><option value="creative">真人编导核验（六项）</option></select>{checks.map((c,i)=><label key={c.code} className="block">{c.code}<select value={c.outcome} onChange={e=>setChecks(old=>old.map((x,j)=>j===i?{...x,outcome:e.target.value as typeof x.outcome}:x))}><option value="unknown">待核验</option><option value="passed">通过</option><option value="failed">失败</option></select><input aria-label={`${c.code} 观察`} value={c.observation} onChange={e=>setChecks(old=>old.map((x,j)=>j===i?{...x,observation:e.target.value}:x))}/></label>)}<button disabled={busy||!!pending||!read.currentSourceVerified} onClick={()=>void act('review')}>明确提交包装核验</button>{read.reviews.map(r=><p key={r.reviewId}>{r.kind}：{r.status} · {r.reviewedAt}</p>)}</>}</section>;
}
