import {useEffect,useRef,useState} from 'react';
import {getToken} from '../../lib/auth';
import type {SocialDirectorG5Scope} from '../../../shared/contracts/socialDirectorG5Review';
import type {WeeklyContentQualityRecoveryContext,WeeklyContentQualityRecoveryConsumer,WeeklyContentQualityRecoveryRead} from '../../../shared/contracts/weeklyContentQualityRecovery';
import {weeklyContentQualityRecoveryApi as api} from '../../lib/weeklyContentQualityRecoveryApi';
import {SocialWeeklyG6ReviewPanel} from './SocialWeeklyG6ReviewPanel';
interface Intent{requestId:string;executionTaskId:string;expectedContextHash:string;sourceHash:string}
function readIntent(key:string):Intent|null{const raw=sessionStorage.getItem(key);if(raw===null)return null;const p=JSON.parse(raw);if(!p||typeof p.requestId!=='string'||!/^[a-zA-Z0-9_-]{16,160}$/.test(p.requestId)||typeof p.executionTaskId!=='string'||!p.executionTaskId||!['expectedContextHash','sourceHash'].every(k=>typeof p[k]==='string'&&/^[a-f0-9]{64}$/.test(p[k])))throw Error('原质量恢复索引损坏，不能重复继续任务。');return p;}
export function WeeklyContentQualityRecoveryPanel({scope,onChanged}:{scope:SocialDirectorG5Scope;onChanged?:()=>void}){
 const token=getToken(),identity=JSON.stringify(scope)+token,current=useRef(identity);current.current=identity;const [context,setContext]=useState<WeeklyContentQualityRecoveryContext|null>(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[record,setRecord]=useState<WeeklyContentQualityRecoveryRead|null>(null),[pending,setPending]=useState<Intent|null>(null),[damaged,setDamaged]=useState(false);const write=useRef(false);const active=()=>current.current===identity&&getToken()===token,key=`weekly-quality:${identity}:${selected}:${context?.sourceHash??'unread'}`;
 useEffect(()=>{setContext(null);setSelected('');setRecord(null);setError('');void api.context(scope).then(c=>{if(active())setContext(c);}).catch(e=>{if(active())setError(e instanceof Error?e.message:'本周质量任务尚未查到。');});},[identity]);
 useEffect(()=>{setRecord(null);setPending(null);setDamaged(false);if(!context||!selected)return;try{setPending(readIntent(key));}catch(e){setDamaged(true);setError(e instanceof Error?e.message:'原恢复索引待核验。');}},[key]);
 async function refresh(){if(write.current)return;write.current=true;setBusy(true);try{const c=await api.context(scope);if(active())setContext(c);}catch(e){if(active())setError(e instanceof Error?e.message:'质量任务刷新失败。');}finally{write.current=false;if(active())setBusy(false);}}
 async function command(consumer:WeeklyContentQualityRecoveryConsumer,mode:'resume'|'read'){if(write.current||!context||damaged)return;write.current=true;setBusy(true);setError('');try{let p=readIntent(key);if(mode==='resume'){if(p)throw Error('原恢复命令已提交，请查询原请求。');if(!consumer.resumeAvailable)throw Error('实际质量证据尚未齐全，不能继续。');p={requestId:crypto.randomUUID(),executionTaskId:consumer.executionTaskId,expectedContextHash:consumer.contextHash,sourceHash:context.sourceHash};sessionStorage.setItem(key,JSON.stringify(p));setPending(p);}if(!p)throw Error('原恢复请求尚未查到。');const r=mode==='resume'?await api.resume(scope,p):await api.read(scope,p.executionTaskId,p.requestId);if(r.item&&(r.item.sourceHash!==p.sourceHash||r.item.expectedContextHash!==p.expectedContextHash))throw Error('原质量恢复与冻结提交不一致。');if(active()){setRecord(r);if(r.item&&r.currentSourceVerified)onChanged?.();}}catch(e){if(active())setError(e instanceof Error?e.message:'恢复结果未知，请查询原请求。');}finally{write.current=false;if(active())setBusy(false);}}
 const consumer=context?.consumers.find(c=>c.executionTaskId===selected);
 return <section className="rounded-xl border p-4 space-y-3" aria-label="本周质量任务与发布目标"><h3>继续本周质量核验</h3><p>逐镜与编导整片审核通过后，明确恢复对应的原周任务；其他阻塞继续保留。</p>{error&&<p role="alert">{error}</p>}{!context?<p>正在读取同一成片的真实周任务。</p>:<><button disabled={busy} onClick={()=>void refresh()}>重新读取质量任务</button>{!context.consumers.length?<p>当前成片尚未关联可核验的周质量任务，不创建虚拟任务。</p>:<label>选择真实质量任务<select value={selected} disabled={busy} onChange={e=>setSelected(e.target.value)}><option value="">请选择</option>{context.consumers.map(c=><option key={c.executionTaskId} value={c.executionTaskId}>{c.stepKind==='quality_check'?'质量核验':'返工复核'} · 第 {c.packageVersion} 版 · {c.status==='succeeded'?'已完成':c.status==='blocked'?'受阻':'待执行'}</option>)}</select></label>}{consumer&&<><p>{consumer.gap?.message??(consumer.resumeAvailable?'同源审核凭据已核验，可明确继续此任务。':'当前任务没有可解除的质量阻塞。')}</p><button disabled={busy||damaged||!!pending||!consumer.resumeAvailable} onClick={()=>void command(consumer,'resume')}>明确继续原周质量任务</button>{pending&&<button disabled={busy||damaged} onClick={()=>void command(consumer,'read')}>查询原质量恢复</button>}{record&&<p>{record.item&&record.currentSourceVerified?`实际任务状态：${record.task.status==='succeeded'?'已完成':record.task.status==='queued'?'已排队':record.task.status==='blocked'?'仍有其他阻塞':'待执行'}`:'原恢复凭据尚未查到或来源已变化，不重复提交。'}</p>}<SocialWeeklyG6ReviewPanel scope={{...scope,programId:consumer.programId,packageId:consumer.packageId,packageVersion:consumer.packageVersion,publicationTaskId:consumer.publicationTaskId}} onChanged={onChanged}/></>}</>}</section>;
}
