import {useEffect,useRef,useState} from 'react';
import type {WeeklyOwnedProductIdentityScope} from '../../../shared/contracts/weeklyOwnedProductIdentity';
import type {WeeklyOwnedProductIdentityRead} from '../../../shared/contracts/weeklyOwnedProductIdentityUI';
import type {WeeklyMaterialRequest} from '../../../server/socialPrograms/weeklyMaterialRequests';
import {weeklyOwnedProductIdentityApi} from '../../lib/weeklyOwnedProductIdentityApi';
import {weeklyMaterialRequestsApi} from '../../lib/weeklyMaterialRequestsApi';
import {publicationReceptionApi,type ReceptionEmployee} from '../../lib/publicationReceptionApi';
import {AUTH_TOKEN_CHANGED_EVENT,authHeader,getToken,refreshAuthSession} from '../../lib/auth';
import {ownedProductPreviewHeaders} from '../../lib/weeklyOwnedProductPreview';
import {resolvePublicationTime,publicationTimeZones} from '../../lib/nextWeekPublicationTime';
import {calendarTimestampLabel,frozenCalendarClock} from '../socialProgram/calendarTime';
type Review={decision:''|'accepted'|'rejected';factCheck:string;rightsCheck:string;visualCheck:string};
export interface WeeklyOwnedProductIdentityPanelProps{scope:WeeklyOwnedProductIdentityScope;expectedRunId:string|null;onChanged?:()=>void|Promise<void>}
/** Actual requirement and candidate IDs come exclusively from the scoped server read. */
export default function WeeklyOwnedProductIdentityPanel({scope,expectedRunId,onChanged}:WeeklyOwnedProductIdentityPanelProps){
 const identity=JSON.stringify([scope,expectedRunId]),active=useRef(identity),mounted=useRef(false),epoch=useRef(0);active.current=identity;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const [read,setRead]=useState<WeeklyOwnedProductIdentityRead|null>(null),[requests,setRequests]=useState<WeeklyMaterialRequest[]>([]),[employees,setEmployees]=useState<ReceptionEmployee[]>([]),[userId,setUserId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[reload,setReload]=useState(0);
 const [requestId,setRequestId]=useState(''),[assignee,setAssignee]=useState(''),[reviewer,setReviewer]=useState(''),[title,setTitle]=useState('产品身份图片核验'),[due,setDue]=useState(''),[verifyDue,setVerifyDue]=useState(''),[timeZone,setTimeZone]=useState('Asia/Shanghai'),[selected,setSelected]=useState<string[]>([]),[review,setReview]=useState<Review>({decision:'',factCheck:'',rightsCheck:'',visualCheck:''});
 const [preparationStatus,setPreparationStatus]=useState('');
 const [previews,setPreviews]=useState<Record<string,string>>({});const urls=useRef<string[]>([]);
 const intent=useRef<{kind:'create'|'submit'|'review'|'bind'|'preparation';data:unknown}|null>(null);
 useEffect(()=>{let disposed=false;const generation=++epoch.current,token=getToken(),key=identity;setRead(null);setPreparationStatus('');setRequests([]);setRequestId('');setSelected([]);setError('');setUnknown(false);setBusy(false);intent.current=null;setPreviews({});urls.current.forEach(URL.revokeObjectURL);urls.current=[];
  Promise.all([weeklyOwnedProductIdentityApi.read(scope,expectedRunId),weeklyMaterialRequestsApi.list(scope.programId),publicationReceptionApi.employees(),refreshAuthSession()]).then(([value,items,people,session])=>{if(disposed||epoch.current!==generation||!mounted.current||active.current!==key||getToken()!==token)return;if(!session?.user.id)throw Error('当前登录身份无法核验。');setRead(value);setRequests(items);setEmployees(people);setUserId(session.user.id);const ids=[...new Set(value.assessment.bindings.map(b=>b.requestId))];if(ids.length===1)setRequestId(ids[0]);}).catch(e=>{if(!disposed&&epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token)setError(e instanceof Error?e.message:'读取产品身份要求失败。');});
  const changed=()=>{if(!disposed){setRead(null);setRequests([]);setSelected([]);setReload(v=>v+1);}};window.addEventListener(AUTH_TOKEN_CHANGED_EVENT,changed);
  return()=>{disposed=true;epoch.current++;window.removeEventListener(AUTH_TOKEN_CHANGED_EVENT,changed);urls.current.forEach(URL.revokeObjectURL);urls.current=[];};
 },[identity,reload]);
 const requirements=read?.assessment.requirements??[],lines=requirements.map(r=>`${r.requirementId}：${r.description}`),consumerId=read?.assessment.consumerTaskId;
 const matching=requests.filter(r=>r.status!=='cancelled'&&r.programId===scope.programId&&r.consumers.length===1&&r.consumers[0].taskId===consumerId&&r.consumers[0].packageId===scope.packageId&&r.consumers[0].packageVersion===scope.packageVersion&&lines.every(line=>r.consumers[0].requirement.split('\n').includes(line)));
 const current=matching.find(r=>r.requestId===requestId),submission=current?.submissions.at(-1),readonly=!read||read.readOnly||expectedRunId!==null;
 async function refreshOnly(){const key=identity,token=getToken(),generation=epoch.current;setBusy(true);setError('');try{const [value,items]=await Promise.all([weeklyOwnedProductIdentityApi.read(scope,expectedRunId),weeklyMaterialRequestsApi.list(scope.programId)]);if(epoch.current!==generation||!mounted.current||active.current!==key||getToken()!==token)return;setRead(value);setRequests(items);const pending=intent.current;
   if(pending?.kind==='preparation'){const id=(pending.data as {taskId:string}).taskId;const task=await weeklyOwnedProductIdentityApi.readPreparation(scope,id);if(!mounted.current||epoch.current!==generation||active.current!==key||getToken()!==token)return;setPreparationStatus(`原素材前置任务当前状态：${task.status==='queued'?'待执行':task.status==='blocked'?'仍受阻':task.status==='succeeded'?'已取得实际执行交付':'处理中或已结束'}。原复核响应未知，保持只读，不重复提交。`);}
   if(pending?.kind==='bind'){const ids=(pending.data as {requestId:string}).requestId;if(value.assessment.bindings.length===value.assessment.requirements.length&&value.assessment.bindings.every(b=>b.requestId===ids)){setUnknown(false);intent.current=null;await onChanged?.();}}
   if(pending?.kind==='submit'||pending?.kind==='review'){const p=pending.data as {requestId:string;version:number;ids?:string[];review?:Review};const r=items.find(r=>r.requestId===p.requestId),last=r?.submissions.at(-1);const submitted=pending.kind==='submit'&&last?.version===p.version+1&&last.submittedBy===userId&&p.ids?.length===last.materials.length&&p.ids.every(id=>last.materials.some(m=>m.recordId===id));const decision=last?.verification?.consumerDecisions.find(d=>d.taskId===value.assessment.consumerTaskId);const reviewed=pending.kind==='review'&&last?.version===p.version&&last.verification?.reviewedBy===userId&&decision&&p.review&&decision.accepted===(p.review.decision==='accepted')&&(['factCheck','rightsCheck','visualCheck'] as const).every(k=>decision[k]===p.review![k].trim());if(submitted||reviewed){setUnknown(false);intent.current=null;}}
   if(pending?.kind==='create'){const input=pending.data as {requirementKey:string;dueAt:string;verificationDueAt:string;assigneeUserId:string;reviewerUserId:string;requirement:string};const found=items.filter(r=>r.requirementKey===input.requirementKey&&r.assigneeUserId===input.assigneeUserId&&r.reviewerUserId===input.reviewerUserId&&r.dueAt===input.dueAt&&r.verificationDueAt===input.verificationDueAt&&r.history.find(h=>h.action==='created')?.actor===userId&&r.consumers.length===1&&r.consumers[0].taskId===value.assessment.consumerTaskId&&r.consumers[0].packageId===scope.packageId&&r.consumers[0].packageVersion===scope.packageVersion&&r.consumers[0].requirement===input.requirement);if(found.length===1){setRequestId(found[0].requestId);setUnknown(false);intent.current=null;}}
  }catch(e){if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token)setError(e instanceof Error?e.message:'查询原操作失败。');}finally{if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token)setBusy(false);}}
 async function mutate(kind:'create'|'submit'|'review'|'bind'|'preparation',data:unknown,action:()=>Promise<void>){if(readonly||unknown||busy)return;const key=identity,token=getToken(),generation=epoch.current;intent.current={kind,data};setBusy(true);setError('');try{await action();if(epoch.current!==generation||!mounted.current||active.current!==key||getToken()!==token)return;setUnknown(false);const [value,items]=await Promise.all([weeklyOwnedProductIdentityApi.read(scope,expectedRunId),weeklyMaterialRequestsApi.list(scope.programId)]);if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token){setRead(value);setRequests(items);intent.current=null;await onChanged?.();}}catch(e){if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token){setUnknown(true);setError(`${e instanceof Error?e.message:'操作结果未取得'} 请查询原记录；不会再次提交。`);}}finally{if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token)setBusy(false);}}
 const instant=(v:string)=>{const [date,time]=v.split('T');return resolvePublicationTime(date,time,timeZone);};
 async function create(){if(!read||!consumerId||!lines.length||!assignee||!reviewer||!title.trim()){setError('请指定提交人、审核人和素材任务名称。');return;}try{const dueAt=instant(due),verificationDueAt=instant(verifyDue);if(Date.parse(dueAt)>Date.parse(verificationDueAt))throw Error('提交截止须早于核验截止。');const input={requirementKey:title.trim(),requirements:lines.join('\n'),assigneeUserId:assignee,reviewerUserId:reviewer,dueAt,verificationDueAt,timeZone,consumers:[{taskId:consumerId,packageId:scope.packageId,packageVersion:scope.packageVersion,requirement:lines.join('\n')}]};await mutate('create',{...input,requirement:lines.join('\n')},async()=>{await weeklyMaterialRequestsApi.create(scope.programId,input);});}catch(e){setError(e instanceof Error?e.message:'截止时间无效。');}}
 async function preview(recordId:string){const candidate=read?.candidates.find(c=>c.recordId===recordId);if(!candidate?.previewUrl)return;const key=identity,token=getToken(),generation=epoch.current;try{const response=await fetch(candidate.previewUrl,{headers:ownedProductPreviewHeaders(candidate.previewUrl,window.location.origin,authHeader())});if(!response.ok)throw Error('图片暂不可读取。');if(!response.headers.get('Content-Type')?.startsWith('image/'))throw Error('返回文件不是原图。');const bytes=await response.arrayBuffer();if(bytes.byteLength>50*1024*1024)throw Error('原图超过可核验大小。');const sha=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');if(sha!==candidate.sha256)throw Error('图片文件版本已变化，请重新查询产品要求。');if(epoch.current!==generation||!mounted.current||active.current!==key||getToken()!==token)return;const url=URL.createObjectURL(new Blob([bytes],{type:response.headers.get('Content-Type')||'image/png'}));urls.current.push(url);setPreviews(v=>({...v,[recordId]:url}));}catch(e){if(epoch.current===generation&&mounted.current&&active.current===key&&getToken()===token)setError(e instanceof Error?e.message:'无法查看图片。');}}
 const bound=current&&read?.assessment.bindings.length===requirements.length&&read.assessment.bindings.every(b=>b.requestId===current.requestId);
 return <section aria-label="产品身份图片核验" className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">产品身份图片核验</h3><p className="text-sm">确认这条视频使用的产品外观、事实与商业使用权。提交图片与人工核验分别完成。</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{!read?<p>正在读取本条视频的产品要求…</p>:<>
  {readonly&&<p className="text-sm text-amber-700">生产已经开始或当前任务不可编辑；此处仅查看原要求，不能更换素材。</p>}
  {!read.assessment.required?<p>本条视频当前不需要产品身份图片核验。</p>:<><p className="text-sm">{read.assessment.status==='ready'?'产品身份图片已核验并关联生产。':'产品身份图片尚未全部核验并关联。'}</p>
  {requirements.map(r=><article key={r.requirementId} className="rounded border p-3"><h4>{r.productRef}</h4><p className="text-xs">用于镜头：{r.sceneIds.join('、')}</p><p className="text-sm">{r.description.replace(/[a-f0-9]{64}/g,'对应图片版本')}</p>{read.candidates.filter(c=>c.requirementId===r.requirementId).map(c=><div key={c.recordId} className="mt-2 text-sm"><label><input type="checkbox" disabled={readonly||busy||unknown} checked={selected.includes(c.recordId)} onChange={e=>setSelected(v=>e.target.checked?[...new Set([...v,c.recordId])]:v.filter(id=>id!==c.recordId))}/> {c.name}</label>{c.previewUrl&&<button className="ml-2 underline" onClick={()=>void preview(c.recordId)}>读取原图核验</button>}{previews[c.recordId]&&<img src={previews[c.recordId]} alt={c.name} className="mt-2 max-h-40"/>}</div>)}</article>)}
  {!!read.candidateGaps.length&&<p className="text-sm text-amber-700">部分产品图片尚无可提交的真实入库记录。请在素材库完成上传及产品关联，再查询本条视频；不会猜测或替换图片。</p>}
  <select aria-label="选择产品素材任务" value={requestId} disabled={busy||unknown||readonly} onChange={e=>{setRequestId(e.target.value);setReview({decision:'',factCheck:'',rightsCheck:'',visualCheck:''});}}><option value="">选择已有本条视频的产品素材任务</option>{matching.map(r=><option key={r.requestId} value={r.requestId}>{r.requirementKey} · {r.status}</option>)}</select>
  {!readonly&&!current&&<fieldset disabled={busy||unknown} className="space-y-2"><input aria-label="产品素材任务名称" value={title} onChange={e=>setTitle(e.target.value)}/><select aria-label="素材提交人" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">指定提交人</option>{employees.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="素材审核人" value={reviewer} onChange={e=>setReviewer(e.target.value)}><option value="">指定审核人</option>{employees.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="素材截止时区" value={timeZone} onChange={e=>setTimeZone(e.target.value)}>{publicationTimeZones.map(z=><option key={z}>{z}</option>)}</select><label>提交截止<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><label>核验截止<input type="datetime-local" value={verifyDue} onChange={e=>setVerifyDue(e.target.value)}/></label><button type="button" onClick={()=>void create()}>创建本条视频的产品素材任务</button></fieldset>}
  {current&&<div className="space-y-2"><p className="text-sm">素材任务：{current.requirementKey} · {current.status}</p>{current.preparation&&<div className="rounded bg-amber-50 p-3 text-xs text-amber-900"><p>最早生产需要素材：{current.preparation.earliestRequiredAt?calendarTimestampLabel(current.preparation.earliestRequiredAt,frozenCalendarClock([current.timeZone],current.preparation.earliestRequiredAt)):'真实生产开始时间尚未补齐'}。上传与核验都应在此前完成。</p>{current.preparation.missingScheduleConsumerIds.length>0&&<p>部分视频缺少前置生产排期，暂不能确认这一周能够完成的发布数量。</p>}{current.preparation.verificationDeadlineMissing&&<p>尚未设置核验截止，请先明确核验时间再确认按时制作。</p>}{(current.preparation.uploadDeadlineAfterRequiredStart||current.preparation.verificationDeadlineAfterRequiredStart)&&<p className="font-semibold text-red-700">素材截止晚于最早生产开始时间，请调整素材截止或明确修订生产排期。</p>}</div>}{!readonly&&current.assigneeUserId===userId&&!['accepted','cancelled'].includes(current.status)&&<button disabled={busy||unknown||!selected.length} onClick={()=>{if(!requirements.every(r=>r.imageHashes.every(sha=>read.candidates.some(c=>c.requirementId===r.requirementId&&c.sha256===sha&&selected.includes(c.recordId))))){setError('请逐产品选择全部对应版本的身份图片。');return;}void mutate('submit',{requestId:current.requestId,ids:selected,version:submission?.version??0},async()=>{await weeklyMaterialRequestsApi.submit(scope.programId,current.requestId,selected,submission?.version??0);});}}>提交所选原图，等待人工核验</button>}
  {!readonly&&current.reviewerUserId===userId&&current.status==='pending_verification'&&submission&&<fieldset disabled={busy||unknown} className="space-y-2"><select aria-label="产品身份核验结论" value={review.decision} onChange={e=>setReview(v=>({...v,decision:e.target.value as Review['decision']}))}><option value="">明确选择核验结论</option><option value="accepted">符合要求</option><option value="rejected">需补交</option></select>{(['factCheck','rightsCheck','visualCheck'] as const).map(field=><textarea key={field} aria-label={field} placeholder={{factCheck:'产品事实核验说明',rightsCheck:'商业使用权及授权说明',visualCheck:'逐镜外观和适用性说明'}[field]} value={review[field]} onChange={e=>setReview(v=>({...v,[field]:e.target.value}))}/>)}<button onClick={()=>{if(!review.decision||!review.factCheck.trim()||!review.rightsCheck.trim()||!review.visualCheck.trim()){setError('请明确结论和事实、权利、镜头三项核验说明。');return;}if(review.decision==='accepted'&&submission.materials.some(m=>!previews[m.recordId])){setError('请先读取并查看本次提交的全部原图，再明确人工核验结论。');return;}void mutate('review',{requestId:current.requestId,version:submission.version,review},async()=>{await weeklyMaterialRequestsApi.review(scope.programId,current.requestId,submission.version,[{taskId:consumerId!,accepted:review.decision==='accepted',factCheck:review.factCheck.trim(),rightsCheck:review.rightsCheck.trim(),visualCheck:review.visualCheck.trim()}]);});}}>保存人工核验</button></fieldset>}
  {!readonly&&<button disabled={busy||unknown||(bound===true&&read.assessment.status==='ready')} onClick={()=>void mutate('bind',{requestId:current.requestId},async()=>{await weeklyOwnedProductIdentityApi.bind(scope,{expectedTaskVersion:read.assessment.contentTaskVersion,expectedRequirementHash:read.assessment.requirementHash,bindings:requirements.map(r=>({requirementId:r.requirementId,requestId:current.requestId}))});})}>明确关联本条生产任务{current.status==='accepted'?'并应用已核验素材':'（核验完成前不会放行）'}</button>}
  {bound&&<p className="text-xs">本任务已保存对应素材要求；以当前核验和实际来源检查结果为准，不自动启动。</p>}
  </div>}</>}
 </>}{read?.assessment.preparationTaskId&&!readonly&&<div><button type="button" disabled={busy||unknown||read.assessment.status!=='ready'} onClick={()=>void mutate('preparation',{taskId:read.assessment.preparationTaskId},async()=>{const key=identity,token=getToken(),generation=epoch.current;const task=await weeklyOwnedProductIdentityApi.recheckPreparation(scope,read.assessment.preparationTaskId!);if(mounted.current&&epoch.current===generation&&active.current===key&&getToken()===token)setPreparationStatus(task.status==='queued'?'原素材前置任务已进入待执行；尚未开始制作。':task.status==='blocked'?'原素材前置任务仍受阻，请核对上游与其他缺口。':'已读取原素材前置任务真实状态；以实际交付凭据为准。');})}>核验素材并继续原前置任务</button>{preparationStatus&&<p role="status">{preparationStatus}</p>}<p className="text-xs">仅复核本条视频原素材准备任务，不启动制作或自动核销。</p></div>}<button type="button" disabled={busy} onClick={()=>void refreshOnly()}>{unknown?'只读查询原操作记录':'重新读取产品要求与核验状态'}</button>{unknown&&<p className="text-xs">原操作结果尚未明确；保持只读查询，不重复提交、审核或绑定。</p>}</section>;
}
