import { AlertTriangle, Check, Database, RefreshCcw, ShieldCheck } from 'lucide-react';
import type { ExecutionContract } from '../../lib/digitalEmployees';

export function ExecutionContractPanel({ contract, busy, onConfirm, onRecompile }: { contract: ExecutionContract; busy: boolean; onConfirm: () => void; onRecompile: () => void }) {
  const blocked = contract.readiness === 'blocked';
  const confirmed = contract.status === 'confirmed';
  return <section id="execution-contract" className={`scroll-mt-5 rounded-3xl border bg-white p-6 shadow-sm ${blocked ? 'border-red-200' : confirmed ? 'border-emerald-200' : 'border-blue-200'}`}>
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
      <div><div className="flex items-center gap-2"><ShieldCheck size={20} className={blocked ? 'text-red-600' : 'text-blue-700'} /><h2 className="font-black text-slate-950">执行契约</h2><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[10px] font-bold">v{contract.version}</span></div><p className="mt-2 text-sm text-slate-600">系统已从企业中心、产品、账号、历史发布与指标编译自主运行边界。确认后会固化到运行快照。</p></div>
      <div className="flex gap-2"><button disabled={busy} onClick={onRecompile} className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700"><RefreshCcw size={14} />重新读取数据</button>{!confirmed && <button disabled={busy || blocked} onClick={onConfirm} className="inline-flex items-center gap-1.5 rounded-xl bg-blue-700 px-4 py-2 text-xs font-bold text-white disabled:opacity-40"><Check size={14} />确认执行契约</button>}</div>
    </div>
    <div className="mt-5 grid gap-3 md:grid-cols-4"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] text-slate-500">主推产品</p><p className="mt-1 text-sm font-bold">{contract.intent.focusProducts.join('、') || '待补充'}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] text-slate-500">目标客户 / 市场</p><p className="mt-1 text-sm font-bold">{contract.intent.audience || '待补充'} · {contract.intent.market}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] text-slate-500">正式数据源</p><p className="mt-1 text-sm font-bold">{contract.resources.productCount} 产品 · {contract.resources.connectedAccounts.length} 账号 · {contract.resources.metricSnapshots} 指标快照</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-[11px] text-slate-500">指标口径</p><p className="mt-1 text-sm font-bold">{contract.measurement.baseline} → {contract.measurement.target} {contract.measurement.unit}</p><p className="mt-1 text-[10px] text-slate-400">{contract.measurement.source}</p></div></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2 text-xs font-bold"><Database size={14} />事实引用</div><div className="mt-3 space-y-2">{contract.facts.map(fact => <div key={fact.key} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-800">{fact.summary}</p><p className="mt-1 text-[10px] text-slate-400">{fact.source} · {fact.sourceVersion}</p></div>)}</div></div><div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-bold">预算与停止条件</p><div className="mt-3 flex flex-wrap gap-2">{contract.budgetAllocation.map(item => <span key={item.category} className="rounded-full bg-blue-50 px-3 py-1 text-[11px] text-blue-700">{item.category} ¥{item.limit}</span>)}</div><ul className="mt-3 space-y-1 text-xs text-slate-600">{contract.policy.stopConditions.map(item => <li key={item}>• {item}</li>)}</ul></div></div>
    {contract.gaps.length > 0 && <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex items-center gap-2 text-xs font-bold text-amber-900"><AlertTriangle size={15} />运行前信息检查</div><div className="mt-3 space-y-2">{contract.gaps.map(gap => <div key={gap.code} className="flex items-start justify-between gap-3 text-xs"><div><span className={`mr-2 rounded-full px-2 py-0.5 font-bold ${gap.severity === 'blocking' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'}`}>{gap.severity === 'blocking' ? '阻塞' : '假设'}</span><span className="font-semibold text-slate-800">{gap.title}</span></div><span className="text-right text-slate-500">{gap.resolution}</span></div>)}</div></div>}
    {confirmed && <p className="mt-4 text-xs font-bold text-emerald-700">已确认 · 内容或正式数据源变化后需重新编译并确认</p>}
  </section>;
}
