import {useEffect,useRef,useState} from 'react';
import {getToken,AUTH_TOKEN_CHANGED_EVENT} from '../../lib/auth';
import {socialProgramApi,SocialProgramRequestError} from '../../lib/socialProgramApi';
import {saveExplicitAccountPlaybook,type AccountPlaybookDraft} from '../../lib/accountPlaybookEditor';
export default function AccountPlaybookEditor({programId,accountId,onSaved}:{programId:string;accountId:string;onSaved:()=>Promise<void>}){
 const [draft,setDraft]=useState<AccountPlaybookDraft>({audience:'',pillars:'',evidenceRules:'',entryType:'',entryRef:'',callToAction:''});const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[confirmed,setConfirmed]=useState(false);const identity=useRef({programId,accountId,token:getToken(),active:true});
 useEffect(()=>{const selected={programId,accountId,token:getToken(),active:true};identity.current=selected;const changed=()=>{selected.active=false;setConfirmed(false);setMessage('登录身份已变化，请重新打开账号打法编辑。');};window.addEventListener(AUTH_TOKEN_CHANGED_EVENT,changed);window.addEventListener('storage',changed);return()=>{selected.active=false;window.removeEventListener(AUTH_TOKEN_CHANGED_EVENT,changed);window.removeEventListener('storage',changed);};},[programId,accountId]);
 const save=async(activate:boolean)=>{if(busy||activate&&!confirmed)return;const selected=identity.current;const current=()=>identity.current===selected&&selected.active&&!!selected.token&&getToken()===selected.token;setBusy(true);setMessage('');try{const result=await saveExplicitAccountPlaybook({programId,accountId,draft,activate,current,list:()=>socialProgramApi.listAccounts(programId),save:body=>socialProgramApi.savePlaybook(programId,accountId,body)});if(current()){await onSaved();if(current())setMessage(`账号打法 v${result.version} 已${activate?'启用':'保存为草稿'}；未启动制作。`);}}catch(error){if(current()){setMessage(error instanceof Error?error.message:'保存失败');if(error instanceof SocialProgramRequestError&&error.status===409)await onSaved();}}finally{if(current())setBusy(false);}};
 return <details className="mt-4 rounded border border-border p-3"><summary>编辑账号打法（需明确保存/启用）</summary><div className="mt-3 space-y-3">{(['audience','pillars','evidenceRules','entryRef','callToAction'] as const).map(key=><label key={key} className="block text-sm">{{audience:'目标受众（每行一项）',pillars:'内容支柱（每行一项）',evidenceRules:'事实/证据规则（每行一项）',entryRef:'获客入口地址或引用',callToAction:'行动引导 CTA'}[key]}<textarea value={draft[key]} onChange={e=>{setDraft({...draft,[key]:e.target.value});setConfirmed(false);}} className="ui-field"/></label>)}<label className="block">获客入口<select className="ui-field" value={draft.entryType} onChange={e=>{setDraft({...draft,entryType:e.target.value});setConfirmed(false);}}><option value="">请选择真实入口</option>{['profile_link','comment','direct_message','store','form','whatsapp','other'].map(v=><option key={v} value={v}>{{profile_link:'主页链接',comment:'评论承接',direct_message:'私信',store:'店铺',form:'表单',whatsapp:'WhatsApp',other:'其他'}[v as 'profile_link'|'comment'|'direct_message'|'store'|'form'|'whatsapp'|'other']}</option>)}</select></label><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我确认这些规则适用于该账号，并明确启用此版本</label><div className="flex gap-2"><button type="button" disabled={busy} onClick={()=>void save(false)} className="btn-ghost">保存草稿</button><button type="button" disabled={busy||!confirmed} onClick={()=>void save(true)} className="btn-primary">保存并启用</button></div>{message&&<p role="status">{message}</p>}</div></details>;
}
