import {crossWeekMaterialCandidateKey,recoversCrossWeekMaterialIntent,type PendingCrossWeekMaterialIntent} from './crossWeekMaterialIntent';
import {crossWeekMaterialPanelId} from './crossWeekMaterialCalendar';
import {useEffect,useRef,useState} from 'react';
import {getToken} from '../../lib/auth';
import {crossWeekMaterialContinuationApi as api,assertCrossWeekMaterialConfirmation,type CrossWeekMaterialScope,type CrossWeekMaterialContinuationCandidate,type CrossWeekMaterialContinuationView} from '../../lib/crossWeekMaterialContinuationApi';
export default function CrossWeekMaterialContinuationPanel({onChanged,onOpenMaterial,...scope}:CrossWeekMaterialScope&{onChanged?:(items:CrossWeekMaterialContinuationView[])=>void;onOpenMaterial?:(requestId:string)=>void}){
 const identity=JSON.stringify([scope,getToken()]),live=useRef(identity);live.current=identity;
 const [data,setData]=useState<{identity:string;candidates:CrossWeekMaterialContinuationCandidate[];records:CrossWeekMaterialContinuationView[];gaps:string[]}|null>(null),[reload,setReload]=useState(0),[selected,setSelected]=useState(''),[deadline,setDeadline]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const pending=useRef<PendingCrossWeekMaterialIntent|null>(null);
 useEffect(()=>{let active=true;setData(null);void Promise.all([api.candidates(scope),api.list(scope)]).then(([c,r])=>{if(!active||live.current!==identity)return;setData({identity,candidates:c.items,records:r,gaps:c.gaps});onChanged?.(r);const p=pending.current;if(p?.identity===identity&&r.some(v=>recoversCrossWeekMaterialIntent(p,v)))pending.current=null;}).catch(e=>{if(active&&live.current===identity)setError(e instanceof Error?e.message:'跨周素材读取失败。');});return()=>{active=false;};},[identity,reload]);
 useEffect(()=>{const refresh=()=>setReload(n=>n+1);window.addEventListener('lingshu:agent-business-refresh',refresh);return()=>window.removeEventListener('lingshu:agent-business-refresh',refresh);},[]);
 const snapshot=data?.identity===identity?data:null,candidate=snapshot?.candidates.find(c=>crossWeekMaterialCandidateKey(c)===selected),unknown=pending.current?.identity===identity;
 const confirm=async()=>{if(!candidate||candidate.gap||busy||unknown||!selected||!reason.trim())return;try{assertCrossWeekMaterialConfirmation(candidate,deadline,reason);}catch(e){setError(e instanceof Error?e.message:'核验截止无效。');return;}const captured=identity;pending.current={identity,candidate:structuredClone(candidate),verificationDueAt:deadline,reason:reason.trim()};setBusy(true);setError('');try{await api.confirm(scope,candidate,deadline,reason);if(live.current===captured){setReload(n=>n+1);window.dispatchEvent(new Event('lingshu:agent-business-refresh'));}}catch(e){if(live.current===captured)setError(e instanceof Error?e.message:'确认回执尚未恢复。');}finally{if(live.current===captured)setBusy(false);}};
 return <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h4 className="text-sm font-bold">S9 · 跨周沿用人工素材</h4><button disabled={busy} onClick={()=>setReload(n=>n+1)}>只读刷新</button></div><p className="text-xs">沿用原上传请求、负责人和截止；新一周单独核验素材，不增加母版产量。</p>{error&&<p role="alert">{error}</p>}{unknown&&<p role="status">确认结果待恢复。只读找回真实记录前，保持提交锁定。</p>}{snapshot&&<>{snapshot.gaps.map((g,i)=><p key={i} className="text-amber-800 text-xs">{g}</p>)}<select aria-label="真实跨周素材候选" value={selected} disabled={busy||unknown} onChange={e=>{setSelected(e.target.value);setDeadline(snapshot.candidates.find(c=>crossWeekMaterialCandidateKey(c)===e.target.value)?.latestVerificationAt||'');}}><option value="">选择原素材与新消费者</option>{snapshot.candidates.map(c=><option key={crossWeekMaterialCandidateKey(c)} value={crossWeekMaterialCandidateKey(c)}>{c.requirement} · 原请求 {c.source.requestId}{c.gap?' · 条件未满足':''}</option>)}</select>{selected!==''&&candidate&&<p className="text-xs">原负责人 {candidate.originalOwnerUserId} · 原上传截止 {candidate.originalUploadDueAt} · 新核验最晚 {candidate.latestVerificationAt||'尚未冻结'}{candidate.gap&&` · ${candidate.gap}`}</p>}<input aria-label="新消费者核验截止" placeholder="2026-10-12T10:00:00+08:00" value={deadline} disabled={busy||unknown} onChange={e=>setDeadline(e.target.value)}/><textarea aria-label="明确跨周沿用原因" value={reason} disabled={busy||unknown} onChange={e=>setReason(e.target.value)}/><button disabled={busy||unknown||selected===''||!candidate||!!candidate.gap||!deadline||!reason.trim()} onClick={()=>void confirm()}>确认沿用原素材请求</button>{snapshot.records.map(v=><article key={v.item.continuationId} id={crossWeekMaterialPanelId(scope,v.item.continuationId)} tabIndex={-1} data-request={v.item.source.requestId} data-consumer={v.item.target.consumerTaskId} className="border rounded-lg p-3"><p>{v.item.target.requirement} · {v.materialStatus==='ready'?'新消费者核验通过':v.attachment==='pending'?'原请求追加待恢复':'等待新消费者核验'}</p><p className="text-xs">原请求 {v.item.source.requestId} · 原负责人 {v.item.originalOwnerUserId} · 上传截止 {v.item.originalUploadDueAt}</p>{onOpenMaterial&&v.attachment==='attached'&&<button type="button" onClick={()=>onOpenMaterial(v.item.source.requestId)}>打开原素材上传与逐视频核验</button>}<p className="text-xs">核验负责人 {v.reviewerUserId} · 新核验截止 {v.item.target.verificationDueAt}{v.consumerVerification&&` · 实际审核 ${v.consumerVerification.completedAt}`}</p></article>)}</>}</section>;
}
