import type {WeeklyOperatingPackage,WeeklyExecutionTask,WeeklyProductionStepKind} from '../../../shared/contracts/socialProgram';
import type {AgentCalendarTask} from '../smartBusiness/AgentWeeklyCalendar';
import {getScrollBehavior} from '../../lib/usePrefersReducedMotion';
export const PLANNING_CALENDAR_STEPS=['business_outline','benchmark_collection','benchmark_scoring','director_analysis','business_schedule'] as const;
export const PLANNING_CALENDAR_LABELS={business_outline:'经营初排',benchmark_collection:'采集真实参考',benchmark_scoring:'对标与播放赞转评诊断',director_analysis:'编导分析',business_schedule:'经营合并详细排期'};
export type PlanningCalendarStep=typeof PLANNING_CALENDAR_STEPS[number];
export interface PlanningCalendarTarget{tenantId:string;programId:string;packageId:string;packageVersion:number;taskId:string;stepKind:PlanningCalendarStep}
export const isPlanningCalendarStep=(step:WeeklyProductionStepKind|string):step is PlanningCalendarStep=>(PLANNING_CALENDAR_STEPS as readonly string[]).includes(step);
export function hasPlanningCalendarTarget(task:AgentCalendarTask){const t=task.planningTarget;return Boolean(t&&t.taskId===task.id&&typeof t.tenantId==='string'&&t.tenantId&&typeof t.programId==='string'&&t.programId&&typeof t.packageId==='string'&&t.packageId&&Number.isSafeInteger(t.packageVersion)&&t.packageVersion>0&&isPlanningCalendarStep(t.stepKind));}
export const weeklyPlanningPanelId=(pkg:Pick<WeeklyOperatingPackage,'programId'|'packageId'|'version'>)=>`weekly-planning:${pkg.programId}:${pkg.packageId}:${pkg.version}`;
export const weeklyPlanningTaskId=(pkg:Pick<WeeklyOperatingPackage,'programId'|'packageId'|'version'>,taskId:string)=>`${weeklyPlanningPanelId(pkg)}:task:${taskId}`;
export function validatedPlanningCalendarTask(scope:{programId:string;packageId:string;packageVersion:number},tasks:WeeklyExecutionTask[],card:AgentCalendarTask):WeeklyExecutionTask|null{if(!hasPlanningCalendarTarget(card))return null;const target=card.planningTarget!;if(target.programId!==scope.programId||target.packageId!==scope.packageId||target.packageVersion!==scope.packageVersion)return null;const scoped=tasks.filter(t=>t.programId===scope.programId&&t.packageId===scope.packageId&&t.packageVersion===scope.packageVersion);if(new Set(scoped.map(t=>t.tenantId)).size!==1)return null;const matching=scoped.filter(t=>t.taskId===target.taskId&&t.tenantId===target.tenantId&&t.programId===target.programId&&t.packageId===target.packageId&&t.packageVersion===target.packageVersion&&t.schedule.stepKind===target.stepKind);return matching.length===1?matching[0]!:null;}
/** Opens only the currently rendered real package panel. This performs no planning mutation. */
export function revealWeeklyPlanningTask({pkg,tasks,task,document:doc=globalThis.document}:{pkg:WeeklyOperatingPackage;tasks:WeeklyExecutionTask[];task:AgentCalendarTask;document?:Pick<Document,'getElementById'>}){const actual=validatedPlanningCalendarTask({programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version},tasks,task);if(!actual)throw Error('规划任务与当前周包或真实执行身份不一致，请刷新。');const panel=doc?.getElementById(weeklyPlanningPanelId(pkg));if(!panel||panel.dataset.planningProgram!==pkg.programId||panel.dataset.planningPackage!==pkg.packageId||panel.dataset.planningVersion!==String(pkg.version))throw Error('当前周版本的真实规划工作区尚未加载。');const taskRow=doc.getElementById(weeklyPlanningTaskId(pkg,actual.taskId));const target=taskRow&&panel.contains(taskRow)?taskRow:panel;let parent=target.parentElement;while(parent){if(parent.tagName==='DETAILS')(parent as HTMLDetailsElement).open=true;parent=parent.parentElement;}panel.dataset.selectedPlanningTask=actual.taskId;panel.dataset.selectedPlanningStep=actual.schedule.stepKind;target.scrollIntoView({behavior:getScrollBehavior(),block:'start'});target.focus({preventScroll:true});return actual;}
