import test from 'node:test';import assert from 'node:assert/strict';import type{WeeklyExecutionTask,WeeklyOperatingPackage}from'../../../shared/contracts/socialProgram';import type{AgentCalendarTask}from'../smartBusiness/AgentWeeklyCalendar';import{validatedPlanningCalendarTask,revealWeeklyPlanningTask,weeklyPlanningPanelId,PLANNING_CALENDAR_STEPS}from'./planningCalendarNavigation';
const pkg={programId:'program',packageId:'week',version:2}as WeeklyOperatingPackage;
const execution={tenantId:'tenant',taskId:'outline-real',programId:'program',packageId:'week',packageVersion:2,schedule:{stepKind:'business_outline'}}as WeeklyExecutionTask;
const card={id:execution.taskId,planningTarget:{tenantId:'tenant',taskId:execution.taskId,programId:'program',packageId:'week',packageVersion:2,stepKind:'business_outline'}}as AgentCalendarTask;
const scope={programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version};
test('planning entry requires actual exact task identity and current package scope',()=>{assert.equal(validatedPlanningCalendarTask(scope,[execution],card),execution);for(const change of [{packageVersion:1},{programId:'foreign'},{tenantId:'foreign'},{taskId:'fabricated'},{stepKind:'weekly_review'}])assert.equal(validatedPlanningCalendarTask(scope,[execution],{...card,planningTarget:{...card.planningTarget!,...change}as any}),null);assert.equal(validatedPlanningCalendarTask(scope,[execution,execution],card),null);assert.equal(validatedPlanningCalendarTask({...scope,packageVersion:3},[execution],card),null);});
test('only the five persisted planning stages can target the planning panel',()=>{for(const stepKind of PLANNING_CALENDAR_STEPS){const e={...execution,schedule:{stepKind}}as WeeklyExecutionTask;const c={...card,planningTarget:{...card.planningTarget!,stepKind}};assert.equal(validatedPlanningCalendarTask(scope,[e],c),e);}for(const stepKind of ['weekly_review','performance_monitoring','publishing','video_generation'])assert.equal(validatedPlanningCalendarTask(scope,[{...execution,schedule:{stepKind}}as WeeklyExecutionTask],{...card,planningTarget:{...card.planningTarget!,stepKind}as any}),null);});
test('navigation expands rendered current planning panel and performs no mutation or network work',()=>{const detail={tagName:'DETAILS',open:false,parentElement:null};let scrolls=0,focuses=0;const panel={dataset:{planningProgram:'program',planningPackage:'week',planningVersion:'2'},parentElement:detail,scrollIntoView(){scrolls++;},focus(){focuses++;}};let lookups=0;const doc={getElementById(id:string){lookups++;return id===weeklyPlanningPanelId(pkg)?panel:null;}}as unknown as Pick<Document,'getElementById'>;assert.equal(revealWeeklyPlanningTask({pkg,tasks:[execution],task:card,document:doc}),execution);assert.equal(detail.open,true);assert.equal(scrolls,1);assert.equal(focuses,1);assert.equal((panel.dataset as any).selectedPlanningTask,execution.taskId);assert.equal(lookups,2);assert.throws(()=>revealWeeklyPlanningTask({pkg:{...pkg,version:3},tasks:[execution],task:card,document:doc}),/身份/);assert.equal(lookups,2);panel.dataset.planningVersion='1';assert.throws(()=>revealWeeklyPlanningTask({pkg,tasks:[execution],task:card,document:doc}),/未加载/);assert.equal(scrolls,1);});
test('a real task row opens nested planning details and focuses only that current task',()=>{const outer={tagName:'DETAILS',open:false,parentElement:null};const panel:any={tagName:'SECTION',dataset:{planningProgram:'program',planningPackage:'week',planningVersion:'2'},parentElement:outer};const inner={tagName:'DETAILS',open:false,parentElement:panel};let focused=0,scrolled=0;const row={parentElement:inner,scrollIntoView(){scrolled++;},focus(){focused++;}};panel.contains=(element:unknown)=>element===row;const doc={getElementById(id:string){return id===weeklyPlanningPanelId(pkg)?panel:row;}}as unknown as Pick<Document,'getElementById'>;revealWeeklyPlanningTask({pkg,tasks:[execution],task:card,document:doc});assert.equal(outer.open,true);assert.equal(inner.open,true);assert.equal(focused,1);assert.equal(scrolled,1);});
