import {workspaceNavigationFixture} from '../../lib/productionWorkspaceNavigation.fixture';
import {test} from 'node:test';import assert from 'node:assert/strict';
import {sceneCalendarExecution,sceneCalendarChoices,isSceneContentExecution} from './sceneCalendarNavigation';
const pkg={programId:'p',packageId:'w',version:2};
const execution:any={tenantId:'tenant',programId:'p',packageId:'w',packageVersion:2,taskId:'e',workflowKind:'content',schedule:{stepKind:'rework'},dependsOnTaskIds:['upstream'],productionProgress:{contentTaskId:'c',runId:'r'}};
const task:any={taskId:'c',version:'v1',runId:'r',brief:{programRef:{id:'p'}},agentWorkflow:{weeklyPackage:{packageId:'w',version:'2'}},artifacts:[{artifactId:'a',taskId:'c',kind:'short_video',origin:'agent',version:'v1',content:{productionWorkspaceSource:{type:'actual_social_render'}}}]};
const fixture=workspaceNavigationFixture({tenantId:'tenant',taskId:'c',runId:'r',artifactId:'a',projectId:'project',sceneIds:['s3','s4']});
const projects=[{...fixture.project,title:'真实视频'}];
const receipt:any={productionWorkspaceBinding:fixture.binding,tenantId:'tenant',taskId:'c',sourceRunId:'r',parentArtifactId:'a',scenes:[{sceneId:'s3',shotId:'shot3',status:'failed',checks:[{code:'visual',passed:false,message:'真实失败原因'}]},{sceneId:'s4',shotId:'shot4',status:'failed'}]};
test('exact execution identity overrides publication aggregate and exposes missing upstream',()=>{assert.equal(sceneCalendarExecution(pkg,[execution],{id:'e'}),execution);assert.throws(()=>sceneCalendarExecution(pkg,[execution],{id:'e',productionTaskId:'other'}));assert.throws(()=>sceneCalendarExecution(pkg,[execution,execution],{id:'e'}));assert.throws(()=>sceneCalendarExecution(pkg,[{...execution,productionProgress:null}],{id:'e'}),/upstream/);assert.equal(isSceneContentExecution({...execution,schedule:{stepKind:'user_approval'}}),false);});
test('all real failed scenes are offered without choosing ordinal or most recent video',()=>{const choices=sceneCalendarChoices(execution,task,projects,[receipt]);assert.deepEqual(choices.map(c=>c.target.sceneId),['s3','s4']);assert.deepEqual(choices[0].reasons,['真实失败原因']);const multiple=sceneCalendarChoices(execution,task,[...projects,{...projects[0],id:'another'}],[receipt]);assert.equal(multiple.length,2);});
test('missing projects, mismatched scopes, duplicate identities and no failed evidence block navigation',()=>{assert.throws(()=>sceneCalendarChoices(execution,task,[],[receipt]),/尚无真实/);assert.throws(()=>sceneCalendarChoices(execution,task,projects,[{...receipt,tenantId:'other'}]));assert.throws(()=>sceneCalendarChoices(execution,task,[...projects,...projects],[receipt]),/不唯一/);assert.throws(()=>sceneCalendarChoices(execution,task,projects,[{...receipt,scenes:[{sceneId:'s3',status:'passed'}]}]),/未读取到/);});

test('common task membership never fabricates parent-to-project lineage',()=>{assert.throws(()=>sceneCalendarChoices(execution,task,projects,[{...receipt,productionWorkspaceBinding:null}]),/血缘/);assert.throws(()=>sceneCalendarChoices(execution,task,projects,[{...receipt,productionWorkspaceBinding:undefined}]),/血缘/);});

test('completed content, independent approval and publishing remain eligible for server binding lookup without progress',async()=>{const {isWeeklyContentNavigationExecution}=await import('./sceneCalendarNavigation');for(const [workflowKind,stepKind] of [['content','material_preparation'],['directing','script'],['directing','storyboard'],['content','quality_check'],['content','user_approval'],['publishing','publishing']])assert.equal(isWeeklyContentNavigationExecution({...execution,workflowKind,schedule:{stepKind},status:'succeeded',productionProgress:null}),true);for(const [workflowKind,stepKind] of [['engagement','performance_monitoring'],['review','weekly_review'],['content','performance_monitoring']])assert.equal(isWeeklyContentNavigationExecution({...execution,workflowKind,schedule:{stepKind}}),false);});
