import type {WeeklyOperatingPackage,WeeklyExecutionTask} from '../../../shared/contracts/socialProgram';
import type {AgentCalendarTask} from '../smartBusiness/AgentWeeklyCalendar';
import {getScrollBehavior} from '../../lib/usePrefersReducedMotion';
export type TemplateCalendarStep='template_extraction'|'template_performance_validation';
export interface TemplateCalendarTarget{tenantId:string;programId:string;packageId:string;packageVersion:number;taskId:string;stepKind:TemplateCalendarStep}
export const isTemplateCalendarStep=(step:string):step is TemplateCalendarStep=>['template_extraction','template_performance_validation'].includes(step);
export const weeklyTemplatePanelId=(pkg:Pick<WeeklyOperatingPackage,'programId'|'packageId'|'version'>)=>`weekly-content-templates:${pkg.programId}:${pkg.packageId}:${pkg.version}`;
export function hasTemplateCalendarTarget(card:AgentCalendarTask){const t=card.templateTarget;return Boolean(t&&t.taskId===card.id&&t.tenantId&&t.programId&&t.packageId&&Number.isSafeInteger(t.packageVersion)&&t.packageVersion>0&&isTemplateCalendarStep(t.stepKind));}
export function templateTaskEvidence(pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[],taskId:string){const scoped=tasks.filter(t=>t.programId===pkg.programId&&t.packageId===pkg.packageId&&t.packageVersion===pkg.version);if(new Set(scoped.map(t=>t.tenantId)).size!==1)return null;const unique=(id:unknown)=>{const matches=scoped.filter(t=>t.taskId===id);return matches.length===1?matches[0]:undefined;};const task=unique(taskId);if(!task||!isTemplateCalendarStep(task.schedule.stepKind)||task.workflowKind!==(task.schedule.stepKind==='template_extraction'?'directing':'review')||!task.publicationTaskId)return null;const source=unique(task.inputSnapshot.sourceTaskId),review=unique(task.inputSnapshot.reviewTaskId);if(!source||source.workflowKind!=='content'||source.schedule.stepKind!=='video_generation'||source.publicationTaskId!==task.publicationTaskId||source.accountId!==task.accountId||!review||review.workflowKind!=='review'||review.schedule.stepKind!=='weekly_review'||(review.publicationTaskId&&review.publicationTaskId!==task.publicationTaskId))return null;const extraction=task.schedule.stepKind==='template_extraction'?task:unique(task.inputSnapshot.extractionTaskId);if(!extraction||extraction.workflowKind!=='directing'||extraction.schedule.stepKind!=='template_extraction'||extraction.publicationTaskId!==task.publicationTaskId||extraction.accountId!==task.accountId||extraction.inputSnapshot.sourceTaskId!==source.taskId||extraction.inputSnapshot.reviewTaskId!==review.taskId||!extraction.dependsOnTaskIds.includes(source.taskId)||!extraction.dependsOnTaskIds.includes(review.taskId)||(task!==extraction&&!task.dependsOnTaskIds.includes(extraction.taskId)))return null;return {task,source,review};}
export function validatedTemplateCalendarTask(scope:{programId:string;packageId:string;packageVersion:number},tasks:WeeklyExecutionTask[],card:AgentCalendarTask){if(!hasTemplateCalendarTarget(card))return null;const t=card.templateTarget!;if(t.programId!==scope.programId||t.packageId!==scope.packageId||t.packageVersion!==scope.packageVersion)return null;const evidence=templateTaskEvidence({programId:scope.programId,packageId:scope.packageId,version:scope.packageVersion} as WeeklyOperatingPackage,tasks,t.taskId);return evidence&&evidence.task.tenantId===t.tenantId&&evidence.task.schedule.stepKind===t.stepKind?evidence.task:null;}
export function revealWeeklyTemplateTask({pkg,tasks,task,document:doc=globalThis.document}:{pkg:WeeklyOperatingPackage;tasks:WeeklyExecutionTask[];task:AgentCalendarTask;document?:Pick<Document,'getElementById'>}){const actual=validatedTemplateCalendarTask({programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version},tasks,task);if(!actual)throw Error('模板任务来源、复盘或周版本身份不一致。');const panel=doc?.getElementById(weeklyTemplatePanelId(pkg));if(panel){if(panel.dataset.templateProgram!==pkg.programId||panel.dataset.templatePackage!==pkg.packageId||panel.dataset.templateVersion!==String(pkg.version))throw Error('模板面板周版本不一致。');let parent=panel.parentElement;while(parent){if(parent.tagName==='DETAILS')(parent as HTMLDetailsElement).open=true;parent=parent.parentElement;}panel.scrollIntoView({behavior:getScrollBehavior(),block:'start'});panel.focus({preventScroll:true});}return actual;}
