import {isWeeklySalesHandoff} from '../../../shared/contracts/socialWeeklySalesHandoff';
import type {WeeklySalesHandoff} from '../../../shared/contracts/socialWeeklySalesHandoff';
import type {AgentCalendarTask} from '../smartBusiness/AgentWeeklyCalendar';
export type WeeklySalesAction='claim'|'feedback'|'information';
export interface WeeklySalesNavigationTarget {tenantId:string;programId:string;packageId:string;packageVersion:number;handoffId:string;handoffVersion:number;runId:string;memberId:string;customerId:string;action:WeeklySalesAction}
const text=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0;
export function isWeeklySalesTarget(v:unknown):v is WeeklySalesNavigationTarget {if(!v||typeof v!=='object'||Array.isArray(v))return false;const t=v as WeeklySalesNavigationTarget;return ['tenantId','programId','packageId','handoffId','runId','memberId','customerId'].every(k=>text(t[k as keyof typeof t]))&&Number.isSafeInteger(t.packageVersion)&&t.packageVersion>0&&Number.isSafeInteger(t.handoffVersion)&&t.handoffVersion>0&&['claim','feedback','information'].includes(t.action);}
export function salesNavigationTarget(item:WeeklySalesHandoff,action:WeeklySalesAction):WeeklySalesNavigationTarget{return {tenantId:item.tenantId,programId:item.programId,packageId:item.packageId,packageVersion:item.packageVersion,handoffId:item.id,handoffVersion:item.version,runId:item.runId,memberId:item.memberId,customerId:item.customerId,action};}
export function validWeeklySalesTaskBinding(card:AgentCalendarTask):boolean {const t=card.salesTarget;return isWeeklySalesTarget(t)&&card.agent==='human'&&card.id===`sales:${t.handoffId}:${t.action}`&&card.salesHandoffId===t.handoffId&&card.salesPackageId===t.packageId&&card.salesPackageVersion===t.packageVersion&&card.salesAction===(t.action==='information'?'feedback':t.action);}
export function validateWeeklySalesTask(card:AgentCalendarTask,scope:{tenantId:string;programId:string;packageId:string;packageVersion:number},items:WeeklySalesHandoff[]):WeeklySalesNavigationTarget|null {if(!validWeeklySalesTaskBinding(card))return null;const t=card.salesTarget!;if((['tenantId','programId','packageId','packageVersion'] as const).some(k=>t[k]!==scope[k]))return null;const matches=items.filter(i=>i.id===t.handoffId);if(matches.length!==1||!isWeeklySalesHandoff(matches[0]))return null;const expected=salesNavigationTarget(matches[0]!,t.action);if(Object.entries(expected).some(([k,v])=>t[k as keyof typeof t]!==v))return null;if(t.action==='information'&&matches[0]!.status!=='needs_information')return null;return t;}
export function salesActionPanelId(t:WeeklySalesNavigationTarget):string{return `weekly-sales-action:${JSON.stringify([t.tenantId,t.programId,t.packageId,t.packageVersion,t.handoffId,t.handoffVersion,t.runId,t.memberId,t.customerId,t.action])}`;}
export function revealWeeklySalesAction(card:AgentCalendarTask,scope:{tenantId:string;programId:string;packageId:string;packageVersion:number},root:HTMLElement|null):void {const t=card.salesTarget;if(!validWeeklySalesTaskBinding(card)||!t||(['tenantId','programId','packageId','packageVersion'] as const).some(k=>t[k]!==scope[k]))throw Error('销售交接身份与当前周版本不一致，请刷新。');const matches=Array.from(root?.querySelectorAll<HTMLElement>('[data-sales-target]')??[]).filter(n=>n.id===salesActionPanelId(t)&&n.dataset.salesTarget===JSON.stringify(t));if(matches.length!==1)throw Error('原销售交接动作或版本尚未读取，请刷新真实交接。');const node=matches[0]!;const details=node.closest('details');if(details)details.open=true;node.scrollIntoView({behavior:'smooth',block:'center'});node.focus({preventScroll:true});}
