import type {WeeklyNativeSendRecovery,WeeklyNativeSendRecoveryScope} from '../../../shared/contracts/weeklyNativeSendRecovery';
import type {AgentCalendarTask} from '../smartBusiness/AgentWeeklyCalendar';
import {calendarClock,calendarDateTime} from './calendarTime';
export interface NativeRecoveryTarget extends WeeklyNativeSendRecoveryScope{id:string;runId:string;taskId:string;itemId:string;requestId:string;channel:'messenger'|'instagram'}
export const nativeRecoveryPanelId=(s:WeeklyNativeSendRecoveryScope,id:string)=>`native-send-recovery:${encodeURIComponent(s.tenantId)}:${encodeURIComponent(s.programId)}:${encodeURIComponent(s.packageId)}:${s.packageVersion}:${encodeURIComponent(id)}`;
export function validNativeRecoveryTarget(card:AgentCalendarTask,scope:WeeklyNativeSendRecoveryScope):NativeRecoveryTarget|null{const t=card.nativeRecoveryTarget;return t&&card.id===`native-send-recovery:${t.id}`&&Object.entries(scope).every(([k,v])=>t[k as keyof NativeRecoveryTarget]===v)&&['messenger','instagram'].includes(t.channel)&&[t.id,t.runId,t.taskId,t.itemId,t.requestId].every(v=>typeof v==='string'&&!!v)?t:null;}
export function projectNativeRecoveries(items:WeeklyNativeSendRecovery[],scope:WeeklyNativeSendRecoveryScope):AgentCalendarTask[]{const seen=new Set<string>();return items.flatMap(item=>{if(Object.entries(scope).some(([k,v])=>item[k as keyof WeeklyNativeSendRecovery]!==v)||seen.has(item.id)||!['messenger','instagram'].includes(item.channel)||!/(?:Z|[+-]\d{2}:\d{2})$/.test(item.deadlineAt)||!Number.isFinite(Date.parse(item.deadlineAt)))return [];seen.add(item.id);const clock=calendarClock(item.deadlineAt),planned=calendarDateTime(item.deadlineAt,clock),p=item.resolvedProof;const completed=item.status==='resolved'&&item.version>1&&!!item.resolvedAt&&Number.isFinite(Date.parse(item.resolvedAt))&&!!p&&p.taskId===item.taskId&&p.runId===item.runId&&p.requestId===item.requestId&&!!p.providerMessageId&&/^[a-f0-9]{64}$/.test(p.evidenceHash)&&Number.isFinite(Date.parse(p.verifiedAt));return [{id:`native-send-recovery:${item.id}`,agent:'human',date:planned.date,time:planned.time,calendarClock:clock,timeSemantics:'finish',title:`S7 · ${item.channel==='messenger'?'Messenger':'Instagram'} 发送异常处理`,context:`实际客户 ${item.customerId} · 原任务 ${item.taskId}`,output:completed?'原可信回执与任务已核验；未重发消息':'核对原发送请求的可信凭据',minutes:null,status:completed?'completed':'blocked',assignee:item.ownerUserId,dueAt:item.deadlineAt,deadlineTracked:true,availableForHuman:true,submission:completed?'accepted':'missing',actualFinishedAt:completed?item.resolvedAt!:undefined,deliveryTiming:completed?(Date.parse(item.resolvedAt!)<=Date.parse(item.deadlineAt)?'on_time':'late'):undefined,reason:completed?undefined:item.gap||item.reason,nativeRecoveryTarget:{...scope,id:item.id,runId:item.runId,taskId:item.taskId,itemId:item.itemId,requestId:item.requestId,channel:item.channel}} as AgentCalendarTask];});}
export function nativeRecoveryProductionLink(item:WeeklyNativeSendRecovery,scope:WeeklyNativeSendRecoveryScope):import('../../lib/digitalEmployees').DigitalEmployeeDeepLink{
 if(Object.entries(scope).some(([k,v])=>item[k as keyof WeeklyNativeSendRecovery]!==v)||!['messenger','instagram'].includes(item.channel)||![item.id,item.runId,item.taskId,item.requestId,item.itemId].every(v=>typeof v==='string'&&!!v.trim()))throw Error('原客服任务与当前租户或周包不一致。');
 return {page:'conversion',runId:item.runId,taskId:item.taskId,businessRef:{taskKey:'followup_dispatch',businessDomain:'customer',statusSource:'原发送请求、审批与客服生产任务'}};
}
