import React from 'react';import test from 'node:test';import assert from 'node:assert/strict';import express from 'express';import {once} from 'node:events';import {renderToStaticMarkup} from 'react-dom/server';
import {runningEvidenceFixture} from '../../../server/socialPrograms/weeklyRunningResourceEvidence.fixture.js';
import {createSocialWeeklyRunningResourceEvidenceRouter} from '../../../server/routes/socialWeeklyRunningResourceEvidence.js';
import {weeklyRunningResourceEvidenceApi} from '../../lib/weeklyRunningResourceEvidenceApi.js';
import {ObservedQueueResources} from './WeeklyRunningResourceEvidencePanel.js';
Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null}});
test('actual authenticated GET is parsed and shown as three independent observed pools, never a future reservation',async()=>{
 const f=await runningEvidenceFixture(),originalFetch=globalThis.fetch;const now=new Date(),expiry=new Date(now.getTime()+600000).toISOString();f.tables.content_execution_jobs![0]!.lease_expires_at=expiry;f.tables.durable_operation_leases![0]!.expires_at=expiry;
 const stamp=now.toISOString();f.tables.content_execution_limits!.push({id:'account-limit',tenant_id:'t',limit_scope:'account',scope_key:'account',max_running:1,updated_by:'owner',created_at:stamp,updated_at:stamp},{id:'type-limit',tenant_id:'t',limit_scope:'task_type',scope_key:'social_video',max_running:3,updated_by:'owner',created_at:stamp,updated_at:stamp});
 const app=express();app.use((_req,res,next)=>{res.locals.tenantId='t';res.locals.userId='owner';next();});app.use('/api/overseas/social-programs/:programId/operating-packages/:packageId/running-resource-evidence',createSocialWeeklyRunningResourceEvidenceRouter(f.store));const server=app.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();assert.ok(address&&typeof address!=='string');const base=`http://127.0.0.1:${address.port}`;
 try{globalThis.fetch=(input,init)=>originalFetch(new URL(String(input),base),init);const item=await weeklyRunningResourceEvidenceApi.read('p','week1',1,'video');assert.equal(item.observedResources.length,3);assert.equal(item.observedResources.find(r=>r.scope==='account')?.observation.availableSlots,0);assert.equal(item.resourceKey,null);assert.equal(item.reservationEligible,false);assert.equal(item.remainingCostCny,null);assert.equal(item.expectedFinishAt,null);
 const html=renderToStaticMarkup(<ObservedQueueResources resources={item.observedResources}/>);assert.match(html,/租户/);assert.match(html,/当前账号/);assert.match(html,/当前任务类型/);assert.match(html,/仅是当次观测/);assert.ok(!html.includes('private-token'));assert.ok(!html.includes('expectedFinishAt'));
 f.tables.durable_operation_leases=[];const unknown=await weeklyRunningResourceEvidenceApi.read('p','week1',1,'video');assert.ok(unknown.observedResources.every(r=>r.observation.availableSlots===null));assert.match(renderToStaticMarkup(<ObservedQueueResources resources={unknown.observedResources}/>),/未知/);
 globalThis.fetch=async()=>Response.json({item:{...unknown,observedResources:unknown.observedResources.map(r=>({...r,observation:{...r.observation,availableSlots:0}}))}});await assert.rejects(weeklyRunningResourceEvidenceApi.read('p','week1',1,'video'));
 }finally{globalThis.fetch=originalFetch;server.close();await once(server,'close');await f.cleanup();}
});
