import {resumeWeeklyTemplateExecution} from '../../lib/weeklyTemplateExecutionResumeApi';
import {weeklyTemplateExecutionSelectionApi,type WeeklyTemplateExecutionSelection} from '../../lib/weeklyTemplateExecutionSelectionApi';
import {templateTaskEvidence,weeklyTemplatePanelId} from './templateCalendarNavigation';
import { useEffect, useRef, useState } from 'react';
import type { WeeklyExecutionTask, WeeklyOperatingPackage } from '../../../shared/contracts/socialProgram';
import type { WeeklyContentTemplateCandidate, WeeklyContentTemplateConfirmation } from '../../../shared/contracts/socialWeeklyContentTemplates';
import { getToken } from '../../lib/auth';
import { socialProgramApi } from '../../lib/socialProgramApi';
import { weeklyContentTemplateApi, type WeeklyTemplatePage } from '../../lib/weeklyContentTemplateApi';
import { getScrollBehavior } from '../../lib/usePrefersReducedMotion';
export function templateSourceOptions(pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[]){
 const scoped=tasks.filter(t=>t.programId===pkg.programId&&t.packageId===pkg.packageId&&t.packageVersion===pkg.version);
 const reviews=scoped.filter(t=>t.workflowKind==='review'&&t.status==='succeeded').flatMap(t=>t.resultRefs.filter(r=>r.type==='weekly_review_snapshot'));
 return {pkg,sources:scoped.filter(t=>t.workflowKind==='content'&&t.schedule?.stepKind==='video_generation'&&t.status==='succeeded'&&t.resultRefs.filter(r=>r.type==='starter_social_content_artifact').length===1),reviews};
}
export function templateCandidateMatchesTask(pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[],taskId:string,candidate:WeeklyContentTemplateCandidate){const evidence=templateTaskEvidence(pkg,tasks,taskId);return Boolean(evidence&&candidate.tenantId===evidence.task.tenantId&&candidate.programId===pkg.programId&&candidate.source.packageId===pkg.packageId&&candidate.source.packageVersion===pkg.version&&candidate.source.publicationTaskId===evidence.task.publicationTaskId&&candidate.source.accountId===evidence.task.accountId&&candidate.source.sourceTaskId===evidence.source.taskId&&evidence.review.resultRefs.some(r=>r.type===candidate.source.reviewRef.type&&r.id===candidate.source.reviewRef.id&&r.version===candidate.source.reviewRef.version));}
export default function WeeklyContentTemplatesPanel({pkg,onTemplateRevision,tasks=[],taskId,onExecutionResume}:{pkg:WeeklyOperatingPackage;onExecutionResume?:(task:WeeklyExecutionTask)=>void|Promise<void>;tasks?:WeeklyExecutionTask[];taskId?:string;onTemplateRevision?:(next:WeeklyOperatingPackage)=>void|Promise<void>}){
 const selectedTask=taskId?templateTaskEvidence(pkg,tasks,taskId):null;
 const identity=JSON.stringify([getToken(),pkg.programId,pkg.packageId,pkg.version,taskId??null]);const active=useRef(identity);active.current=identity;
 const [executionSelection,setExecutionSelection]=useState<{identity:string;item:WeeklyTemplateExecutionSelection|null}|null>(null);
 const [page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[data,setData]=useState<{identity:string;page:WeeklyTemplatePage}|null>(null);
 const [sources,setSources]=useState<{identity:string;items:ReturnType<typeof templateSourceOptions>[]} |null>(null);
 const [targets,setTargets]=useState<{identity:string;items:WeeklyOperatingPackage[]}|null>(null),[targetId,setTargetId]=useState(''),[publicationId,setPublicationId]=useState('');
 const [recoverySourceVersion,setRecoverySourceVersion]=useState('');
 const [pending,setPending]=useState<{identity:string;target:WeeklyOperatingPackage;result:Awaited<ReturnType<typeof weeklyContentTemplateApi.bind>>}|null>(null);
 const [action,setAction]=useState<'new'|'retain'|'revise'>('new');
 const [sourceId,setSourceId]=useState(''),[reviewKey,setReviewKey]=useState(''),[title,setTitle]=useState(''),[reason,setReason]=useState(''),[audience,setAudience]=useState(''),[product,setProduct]=useState(''),[facts,setFacts]=useState(''),[prohibited,setProhibited]=useState(''),[platform,setPlatform]=useState('tiktok');
 const [candidate,setCandidate]=useState<{identity:string;item:WeeklyContentTemplateCandidate}|null>(null),[confirmReason,setConfirmReason]=useState(''),[usage,setUsage]=useState<'trial'|'retain'>('trial');
 const [confirmation,setConfirmation]=useState<{key:string;item:WeeklyContentTemplateConfirmation|null}|null>(null);
 const [message,setMessage]=useState<{identity:string;text:string}|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;setBusy(false);setSourceId('');setReviewKey('');setCandidate(null);setMessage(null);setPending(null);setTargetId('');setPublicationId('');
 void socialProgramApi.listOperatingPackages(pkg.programId).then(async packages=>{if(live)setTargets({identity,items:packages.filter(p=>p.programId===pkg.programId&&p.status==='draft')});const eligible=taskId?[]:packages.filter(p=>p.programId===pkg.programId&&p.weekEnd<pkg.weekStart);const items=await Promise.all(eligible.map(async p=>templateSourceOptions(p,await socialProgramApi.listExecutionTasks(p.programId,p.packageId,p.version))));if(live)setSources({identity,items});}).catch(e=>{if(live)setMessage({identity,text:String(e.message||e)});});return()=>{live=false;};},[identity,taskId]);
 useEffect(()=>{let live=true;void weeklyContentTemplateApi.list(pkg.programId,page).then(result=>{if(live)setData({identity,page:result});}).catch(e=>{if(live)setMessage({identity,text:String(e.message||e)});});return()=>{live=false;};},[identity,page,refresh]);
 const selectionScope=selectedTask?{tenantId:selectedTask.task.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,taskId:selectedTask.task.taskId,extractionTaskId:selectedTask.task.schedule.stepKind==='template_extraction'?selectedTask.task.taskId:String(selectedTask.task.inputSnapshot.extractionTaskId)}:null;
 useEffect(()=>{let live=true;setExecutionSelection(null);if(selectionScope)void weeklyTemplateExecutionSelectionApi.read(selectionScope).then(item=>{if(live)setExecutionSelection({identity,item});}).catch(e=>{if(live)setMessage({identity,text:String(e.message||e)});});return()=>{live=false;};},[identity]);
 const options=taskId?(selectedTask?[{pkg,sources:selectedTask.source.status==='succeeded'?[selectedTask.source]:[],reviews:selectedTask.review.status==='succeeded'?selectedTask.review.resultRefs.filter(r=>r.type==='weekly_review_snapshot'):[]}]:[]):sources?.identity===identity?sources.items:[];const sourceGroup=options.find(x=>x.sources.some(t=>t.taskId===sourceId));const reviews=sourceGroup?.reviews??[];const selectedReview=reviews.find(r=>JSON.stringify(r)===reviewKey);const current=candidate?.identity===identity?candidate.item:null;
 useEffect(()=>{setSourceId(selectedTask?.source.taskId??'');setReviewKey('');setCandidate(null);setPending(null);const el=document.getElementById(weeklyTemplatePanelId(pkg));if(taskId&&el){let p=el.parentElement;while(p){if(p.tagName==='DETAILS')(p as HTMLDetailsElement).open=true;p=p.parentElement;}el.scrollIntoView({behavior:getScrollBehavior(),block:'start'});el.focus({preventScroll:true});}},[identity,taskId]);
 const perform=async(operation:()=>Promise<void>)=>{setBusy(true);setMessage(null);try{await operation();}catch(e){if(active.current===identity)setMessage({identity,text:e instanceof Error?e.message:String(e)});}finally{if(active.current===identity)setBusy(false);}};
 const lines=(text:string)=>text.split('\n').map(x=>x.trim()).filter(Boolean);
 const create=()=>perform(async()=>{if(!selectedReview)return;const item=await weeklyContentTemplateApi.create(pkg.programId,{sourceTaskId:sourceId,reviewRef:selectedReview,action,...(action!=='new'&&current?{previousRef:{type:'weekly_content_template',id:current.templateId,version:current.version}}:{}),title,reason,applicability:{platform,audience,productScope:product,replaceFacts:lines(facts),prohibited:lines(prohibited)}});if(active.current!==identity)return;setCandidate({identity,item});setRefresh(x=>x+1);});
 const candidateKey=JSON.stringify([identity,current?.templateId,current?.version,current?.recordHash]);const selectionRef=useRef(candidateKey);selectionRef.current=candidateKey;
 useEffect(()=>{let live=true;setConfirmation(null);if(current)void weeklyContentTemplateApi.readConfirmation(pkg.programId,{type:'weekly_content_template',id:current.templateId,version:current.version}).then(item=>{if(live&&item&&item.candidateHash!==current.recordHash)throw Error('已确认凭据与当前候选不一致。');if(live)setConfirmation({key:candidateKey,item});}).catch(e=>{if(live)setMessage({identity,text:String(e.message||e)});});return()=>{live=false;};},[candidateKey]);
 const confirmed=confirmation?.key===candidateKey?confirmation.item:null;
 const resumeExecution=()=>perform(async()=>{if(!selectedTask)return;const actual=await resumeWeeklyTemplateExecution(selectedTask.task);if(active.current!==identity)return;setMessage({identity,text:`已核验当前任务凭据，实际状态 ${actual.status}；剩余阻塞 ${[...actual.ownBlockingReasons,...actual.inheritedBlockingTaskIds].join('、')||'无'}。没有确认模板或继续其他任务。`});await onExecutionResume?.(actual);});
 const readExecutionSelection=()=>perform(async()=>{if(!selectionScope)return;const item=await weeklyTemplateExecutionSelectionApi.read(selectionScope);if(active.current===identity)setExecutionSelection({identity,item});});
 const selectForExecution=()=>perform(async()=>{if(!selectionScope||!current||!taskId||!templateCandidateMatchesTask(pkg,tasks,taskId,current))return;const item=await weeklyTemplateExecutionSelectionApi.select(selectionScope,{templateRef:{type:'weekly_content_template',id:current.templateId,version:current.version},candidateHash:current.recordHash});if(active.current===identity){setExecutionSelection({identity,item});setMessage({identity,text:'已保存当前模板任务的明确候选选择；未创建、确认模板或执行任务。'});}});
 const confirm=()=>perform(async()=>{if(!current||confirmation?.key!==candidateKey)return;const existing=await weeklyContentTemplateApi.readConfirmation(pkg.programId,{type:'weekly_content_template',id:current.templateId,version:current.version});if(selectionRef.current!==candidateKey)return;if(existing){if(existing.candidateHash!==current.recordHash)throw Error('确认凭据不一致。');setConfirmation({key:candidateKey,item:existing});setMessage({identity,text:'已读取真实确认，无需再次确认。'});return;}const item=await weeklyContentTemplateApi.confirm(pkg.programId,{templateRef:{type:'weekly_content_template',id:current.templateId,version:current.version},candidateHash:current.recordHash,usage,reason:confirmReason});if(selectionRef.current===candidateKey){setConfirmation({key:candidateKey,item});setMessage({identity,text:`已明确确认${usage==='trial'?'试用':'保留'}；尚未绑定未来周任务。`});}});
 const target=targets?.identity===identity?targets.items.find(p=>p.packageId===targetId):undefined;
 const pendingBinding=pending?.identity===identity&&pending.result.item.templateRef.id===current?.templateId&&pending.result.item.templateRef.version===current?.version&&pending.result.item.candidateHash===current?.recordHash?pending:null;
 const bindingKey=JSON.stringify([candidateKey,target?.packageId,target?.version,publicationId,recoverySourceVersion]);const bindingSelection=useRef(bindingKey);bindingSelection.current=bindingKey;
 const readPending=()=>perform(async()=>{if(!target||!current||!publicationId)return;const sourceVersion=recoverySourceVersion?Number(recoverySourceVersion):target.version;if(!Number.isSafeInteger(sourceVersion)||sourceVersion<1)throw Error('请明确填写原绑定时的周包版本。');const item=await weeklyContentTemplateApi.readPendingBinding(pkg.programId,{packageId:target.packageId,expectedPackageVersion:sourceVersion,expectedTargetVersion:sourceVersion+1,publicationTaskId:publicationId,templateRef:{type:'weekly_content_template',id:current.templateId,version:current.version},candidateHash:current.recordHash});if(bindingSelection.current!==bindingKey)return;if(!item){setMessage({identity,text:'未找到该明确目标版本的待绑定凭据。'});return;}setPending({identity,target,result:{item,publicationPatch:{publicationTaskId:item.publicationTaskId,contentTemplateBindingRef:{type:'weekly_content_template_binding',id:item.bindingId,version:1}},planningRevisionRequired:true}});});
 const bind=()=>perform(async()=>{if(!target||!current||!publicationId||!confirmed)return;const existing=await weeklyContentTemplateApi.readPendingBinding(pkg.programId,{packageId:target.packageId,expectedPackageVersion:target.version,expectedTargetVersion:target.version+1,publicationTaskId:publicationId,templateRef:{type:'weekly_content_template',id:current.templateId,version:current.version},candidateHash:current.recordHash});if(bindingSelection.current!==bindingKey)return;if(existing){setPending({identity,target,result:{item:existing,publicationPatch:{publicationTaskId:existing.publicationTaskId,contentTemplateBindingRef:{type:'weekly_content_template_binding',id:existing.bindingId,version:1}},planningRevisionRequired:true}});return;}const result=await weeklyContentTemplateApi.bind(pkg.programId,{packageId:target.packageId,expectedPackageVersion:target.version,expectedTargetVersion:target.version+1,publicationTaskId:publicationId,templateRef:{type:'weekly_content_template',id:current.templateId,version:current.version},candidateHash:current.recordHash});if(bindingSelection.current===bindingKey)setPending({identity,target,result});});
 const revise=()=>perform(async()=>{if(!pendingBinding)return;const {target,result}=pendingBinding;const applied=await weeklyContentTemplateApi.apply(pkg.programId,{bindingId:result.item.bindingId,sourceVersion:result.item.packageVersion-1,targetVersion:result.item.packageVersion});const actual=await socialProgramApi.getOperatingPackage(pkg.programId,target.packageId);if(actual.version!==result.item.packageVersion||actual.status!=='draft'||actual.socialContentPackage.publicationTasks.find(p=>p.publicationTaskId===result.item.publicationTaskId)?.contentTemplateBindingRef?.id!==result.item.bindingId)throw Error('应用回执尚未核验，请用同一待绑定凭据恢复。');if(active.current===identity){await onTemplateRevision?.(actual);setMessage({identity,text:applied.recovered?'同一新草稿已恢复，未启用。':'未来周新草稿已保存，未启用；素材消费者及新版分析需继续核验。'});}});
 const field=(label:string,value:string,set:(v:string)=>void,multi=false)=> <label className="block text-xs">{label}{multi?<textarea className="block w-full rounded border p-2" disabled={busy} value={value} onChange={e=>set(e.target.value)}/>:<input className="block w-full rounded border p-2" disabled={busy} value={value} onChange={e=>set(e.target.value)}/>}</label>;
 return <section id={weeklyTemplatePanelId(pkg)} tabIndex={-1} data-template-program={pkg.programId} data-template-package={pkg.packageId} data-template-version={pkg.version} data-template-task={selectedTask?.task.taskId} className="space-y-3 rounded-lg border border-border bg-white p-4"><h4 className="font-bold">复盘成片 → 内容模板</h4>{selectedTask&&<button type="button" disabled={busy||executionSelection?.identity!==identity||!executionSelection.item||["succeeded","leased","cancelled"].includes(selectedTask.task.status)} onClick={()=>void resumeExecution()}>核验凭据并继续当前模板任务</button>}{taskId&&<p className="text-xs">{selectedTask?`真实模板任务：${selectedTask.task.taskId} · 状态 ${selectedTask.task.status} · 成片 ${selectedTask.source.taskId} · 复盘 ${selectedTask.review.taskId}`:"当前模板任务来源或复盘依赖不一致，禁止借用其他发布任务。"}</p>}<p className="text-xs">只选明确来源的真实完成成片和同周复盘凭据。模板候选不等于已验证爆款；试用、保留和未来排期绑定分别确认。</p>
 {message?.identity===identity&&<p role="status" className="text-sm">{message.text}</p>}
 <select aria-label="历史完成成片" value={sourceId} onChange={e=>{setSourceId(e.target.value);setReviewKey('');}}><option value="">选择真实成片任务</option>{options.flatMap(x=>x.sources.map(t=><option key={t.taskId} value={t.taskId}>{x.pkg.weekStart} · v{x.pkg.version} · {t.taskId}</option>))}</select>
 <select aria-label="同周复盘报告" value={reviewKey} onChange={e=>setReviewKey(e.target.value)}><option value="">选择同周真实复盘凭据</option>{reviews.map(r=><option key={JSON.stringify(r)} value={JSON.stringify(r)}>{r.id} · v{r.version}</option>)}</select>
 {sources?.identity===identity&&!options.some(x=>x.sources.length&&x.reviews.length)&&<p className="text-xs">没有同时具备完成成片与真实复盘凭据的历史周，暂不能创建。</p>}
 <select aria-label="适用平台" value={platform} onChange={e=>setPlatform(e.target.value)}>{['tiktok','facebook','instagram','youtube'].map(x=><option key={x}>{x}</option>)}</select>
 <select aria-label="候选类型" value={action} onChange={e=>setAction(e.target.value as typeof action)}><option value="new">新模板候选</option><option value="retain">基于所选已确认模板保留结构</option><option value="revise">基于所选已确认模板修订</option></select>
 {field('模板名称',title,setTitle)}{field('创建依据',reason,setReason)}{field('适用受众',audience,setAudience)}{field('产品范围',product,setProduct)}{field('必须替换的事实（每行一项）',facts,setFacts,true)}{field('禁用项（每行一项）',prohibited,setProhibited,true)}
 <button disabled={busy||!selectedReview||(action!=='new'&&!current)||![title,reason,audience,product,facts].every(x=>x.trim())} onClick={()=>void create()}>创建候选</button>
 <div className="space-y-2">{data?.identity===identity&&data.page.items.map(c=><button className="block text-left text-xs" key={`${c.templateId}:${c.version}`} disabled={busy} onClick={()=>setCandidate({identity,item:c})}>{c.title} · v{c.version} · 样本 {c.performance.sampleSufficiency} · 播放 {c.performance.metrics.views??'缺数据'} · 赞/评/转 {c.performance.metrics.likes??'缺'}/{c.performance.metrics.comments??'缺'}/{c.performance.metrics.shares??'缺'}</button>)}<button disabled={page<=1||busy} onClick={()=>setPage(x=>x-1)}>上一页</button><span>第 {page} 页</span><button disabled={busy||data?.identity!==identity||page>=(data?.page.totalPages??0)} onClick={()=>setPage(x=>x+1)}>下一页</button></div>
 {current&&<div className="space-y-2">{taskId&&<><button disabled={busy||executionSelection?.identity!==identity||!!executionSelection.item||!templateCandidateMatchesTask(pkg,tasks,taskId,current)} onClick={()=>void selectForExecution()}>用于当前模板任务</button><button disabled={busy} onClick={()=>void readExecutionSelection()}>只读恢复当前任务选择</button><p className="text-xs">{executionSelection?.identity===identity&&executionSelection.item?`实际所选模板：${executionSelection.item.templateRef.id} v${executionSelection.item.templateRef.version}（已冻结；改选需明确新轮任务或版本）`:"当前任务尚未明确选择模板，不自动使用最新候选。"}</p></>}<p className="text-xs">所选：{current.title} v{current.version} · 适用 {current.applicability.platform} / {current.applicability.audience} / {current.applicability.productScope} · 缺数据：{current.performance.missingKeys.join('、')||'无'}</p><select aria-label="确认用途" value={usage} onChange={e=>setUsage(e.target.value as 'trial'|'retain')}><option value="trial">试用</option><option value="retain">保留</option></select>{field('确认理由',confirmReason,setConfirmReason)}<button disabled={busy||!confirmReason.trim()||confirmation?.key!==candidateKey||!!confirmed} onClick={()=>void confirm()}>明确确认所选模板</button>{confirmed&&<p className="text-xs">真实已确认：{confirmed.usage} · {confirmed.confirmedAt}</p>}</div>}
 {current&&<div className="space-y-2"><select aria-label="未来目标草稿" value={targetId} disabled={busy||!!pendingBinding} onChange={e=>{setTargetId(e.target.value);setPublicationId('');setRecoverySourceVersion('');}}><option value="">明确选择未来周草稿</option>{targets?.identity===identity&&targets.items.filter(p=>p.weekStart>current.source.weekEnd).map(p=><option key={p.packageId} value={p.packageId}>{p.weekStart} · {p.packageId} · v{p.version}</option>)}</select><select aria-label="模板目标发布任务" value={publicationId} disabled={busy||!!pendingBinding} onChange={e=>setPublicationId(e.target.value)}><option value="">选择适用平台的发布任务</option>{target?.socialContentPackage.publicationTasks.filter(p=>p.platform===current.applicability.platform).map(p=><option key={p.publicationTaskId} value={p.publicationTaskId}>{p.publicationTaskId}</option>)}</select><button disabled={busy||!target||!publicationId||!!pendingBinding||!confirmed} onClick={()=>void bind()}>创建未来版本待绑定凭据</button>{field('只读恢复：原绑定时周包版本（留空使用所选版本）',recoverySourceVersion,setRecoverySourceVersion)}<button disabled={busy||!target||!publicationId} onClick={()=>void readPending()}>只读恢复待绑定凭据</button>{pendingBinding&&<><p className="text-xs">模板 {pendingBinding.result.item.templateRef.id} v{pendingBinding.result.item.templateRef.version} 待保存到 {pendingBinding.target.packageId} v{pendingBinding.result.item.packageVersion}，尚未修改排期。</p><button disabled={busy} onClick={()=>void revise()}>明确应用或幂等恢复新草稿</button></>}</div>}
 </section>;
}
