import { useEffect, useRef, useState } from 'react';
import type { WeeklyExecutionTask, WeeklyOperatingPackage } from '../../../shared/contracts/socialProgram';
import type { WeeklyMaterialRequest } from '../../../server/socialPrograms/weeklyMaterialRequests';
import { weeklyMaterialRequestsApi, materialCanonicalId, type MaterialReviewDecision } from '../../lib/weeklyMaterialRequestsApi';
import { publicationReceptionApi, type ReceptionEmployee } from '../../lib/publicationReceptionApi';
import { refreshAuthSession } from '../../lib/auth';
import { studioApi, type Material } from '../../lib/studioApi';
import { weeklyMaterialRequirementChoices, selectedWeeklyMaterialConsumers, type WeeklyHumanMaterialBinding } from '../../lib/weeklyMaterialBinding';

import { materialActionPanelId } from './weeklyMaterialNavigation';

type Review = { decision: '' | 'accepted' | 'rejected'; factCheck: string; rightsCheck: string; visualCheck: string };
export interface WeeklyMaterialRequestsPanelProps { programId: string; packageId: string; packageVersion: number; pkg?:WeeklyOperatingPackage; tasks: WeeklyExecutionTask[]; requiredRequestIds?: string[]; onBindRequiredRequests?: (request: WeeklyMaterialRequest,bindings:WeeklyHumanMaterialBinding[]) => Promise<void> }
const statusLabels = { missing: '待提交', pending_verification: '已提交待核验', accepted: '核验通过', rejected: '需补交', cancelled: '已取消' };
const iso = (value: string) => { const date = new Date(value); if (!value || !Number.isFinite(date.getTime())) throw Error('请设置有效的具体截止时间。'); return date.toISOString(); };
/** Existing tenant material library/upload only; submitting never grants production acceptance. */
export default function WeeklyMaterialRequestsPanel({ programId, packageId, packageVersion, pkg, tasks, requiredRequestIds = [], onBindRequiredRequests }: WeeklyMaterialRequestsPanelProps) {
  const identity = `${programId}:${packageId}:${packageVersion}`; const current = useRef(identity); current.current = identity;
  const [loaded, setLoaded] = useState(''); const [requests, setRequests] = useState<WeeklyMaterialRequest[]>([]); const [employees, setEmployees] = useState<ReceptionEmployee[]>([]); const [userId, setUserId] = useState('');
  const [materials, setMaterials] = useState<Material[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [reload, setReload] = useState(0);
  const [key, setKey] = useState(''); const [requirements, setRequirements] = useState(''); const [assignee, setAssignee] = useState(''); const [reviewer, setReviewer] = useState(''); const [dueAt, setDueAt] = useState(''); const [verificationDueAt, setVerificationDueAt] = useState('');
  const [consumers, setConsumers] = useState<Record<string, string>>({}); const [selectedMaterials, setSelectedMaterials] = useState<Record<string, string[]>>({}); const [reviews, setReviews] = useState<Record<string, Review>>({});
  const [revision, setRevision] = useState<Record<string, { dueAt: string; verificationDueAt: string; reason: string }>>({});
  const timeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const productionTasks = tasks.filter(task => task.programId === programId && task.packageId === packageId && task.packageVersion === packageVersion && task.publicationTaskId && ['content', 'adaptation'].includes(task.scope) && ['material_readiness', 'asset_generation', 'storyboard', 'video_generation'].includes(task.schedule.stepKind));
  const choices=pkg&&pkg.programId===programId&&pkg.packageId===packageId&&pkg.version===packageVersion?weeklyMaterialRequirementChoices(pkg,tasks):[];
  useEffect(() => {
    let disposed = false; setLoaded(''); setBusy(false); setError(''); setRequests([]); setUserId(''); setSelectedMaterials({}); setReviews({}); setConsumers({}); setRevision({}); setKey(''); setRequirements(''); setAssignee(''); setReviewer(''); setDueAt(''); setVerificationDueAt('');
    Promise.all([weeklyMaterialRequestsApi.list(programId), publicationReceptionApi.employees(), refreshAuthSession(), studioApi.listMaterialLibrary('library')]).then(([items, people, session, library]) => {
      if (disposed) return; if (!session?.user.id) throw Error('登录身份无法核验，请重新登录。');
      setRequests(items); setEmployees(people); setUserId(session.user.id); setMaterials(library.items ?? []); setLoaded(identity);
    }).catch(cause => { if (!disposed) setError(cause instanceof Error ? cause.message : '素材任务加载失败。'); });
    const refresh=()=>{void weeklyMaterialRequestsApi.list(programId).then(items=>{if(!disposed)setRequests(items);}).catch(cause=>{if(!disposed)setError(cause instanceof Error?cause.message:'素材刷新失败。');});};
    window.addEventListener('lingshu:agent-business-refresh',refresh);
    const timer = window.setInterval(() => { if (!document.hidden) void weeklyMaterialRequestsApi.list(programId).then(items => { if (!disposed) setRequests(items); }).catch(() => {}); }, 10_000);
    return () => { disposed = true; window.clearInterval(timer);window.removeEventListener('lingshu:agent-business-refresh',refresh); };
  }, [identity, reload]);
  const visible = requests.filter(request => requiredRequestIds.includes(request.requestId) || request.consumers.some(consumer => consumer.packageId === packageId && consumer.packageVersion === packageVersion));
  const usableMaterials = materials.filter(material => ['image', 'video'].includes(material.type) && material.scope !== 'shared' && material.usage !== 'reference_only' && materialCanonicalId(material));
  async function act(action: () => Promise<void>) { const started = identity; setBusy(true); setError(''); try { await action(); if (current.current === started) { const items = await weeklyMaterialRequestsApi.list(programId); if (current.current === started) {setRequests(items);window.dispatchEvent(new Event('lingshu:agent-business-refresh'));} } } catch (cause) { if (current.current === started) setError(cause instanceof Error ? cause.message : '素材操作失败。'); } finally { if (current.current === started) setBusy(false); } }
  async function create() { await act(async () => {
    if (!pkg || !key.trim() || !assignee || !reviewer || !Object.keys(consumers).length) throw Error('请从本版本真实需求分析选择真人素材要求，并填写稳定素材名称及指定人员。');
    const exactConsumers=selectedWeeklyMaterialConsumers(pkg,tasks,Object.keys(consumers));
    const created = await weeklyMaterialRequestsApi.create(programId, { requirementKey: key, requirements:[...new Set(exactConsumers.flatMap(consumer=>consumer.requirement.split('\n'))),...(requirements.trim()?[`补充说明：${requirements.trim()}`]:[])].join('\n'), assigneeUserId: assignee, reviewerUserId: reviewer, dueAt: iso(dueAt), ...(verificationDueAt ? { verificationDueAt: iso(verificationDueAt) } : {}), timeZone, consumers: exactConsumers });
    if (onBindRequiredRequests && current.current === identity) await onBindRequiredRequests(created,Object.keys(consumers).map(requirementId=>({requirementId,requestId:created.requestId})));
  }); }
  async function upload(requestId: string, files: FileList | null) { if (!files?.length) return; await act(async () => {
    const uploaded: Material[] = [];
    for (const file of Array.from(files)) { if (!/^(image|video)\//.test(file.type)) throw Error('人工素材只接受图片或视频。'); const result = await studioApi.uploadMaterialFile(file, { folder: 'upload', type: file.type.startsWith('video/') ? 'video' : 'image', sourceType: 'weekly-material-request' }); if (!result.ok || !result.material || !materialCanonicalId(result.material)) throw Error(result.error || '素材尚未形成真实云端记录，请在素材库确认上传结果。'); uploaded.push(result.material); }
    if (current.current !== identity) return;
    setMaterials(previous => [...uploaded, ...previous]); setSelectedMaterials(previous => ({ ...previous, [requestId]: [...new Set([...(previous[requestId] ?? []), ...uploaded.map(material => materialCanonicalId(material)!)])] }));
  }); }
  async function review(request: WeeklyMaterialRequest) { await act(async () => {
    const decisions: MaterialReviewDecision[] = request.consumers.map(consumer => { const value = reviews[`${request.requestId}:${request.submissions.at(-1)?.version ?? 0}:${consumer.taskId}`]; if (!value?.decision || !value.factCheck.trim() || !value.rightsCheck.trim() || !value.visualCheck.trim()) throw Error('请逐消费者明确通过或拒绝，并填写事实、权利和镜头核验结论。'); return { taskId: consumer.taskId, accepted: value.decision === 'accepted', factCheck: value.factCheck, rightsCheck: value.rightsCheck, visualCheck: value.visualCheck }; });
    if (decisions.some(decision => decision.accepted) && request.submissions.at(-1)?.materials.some(evidence => !materials.some(material => materialCanonicalId(material) === evidence.recordId && material.url))) throw Error('提交素材尚不能在当前素材库查看，不能确认通过；请重新加载或记录拒绝原因。');
    await weeklyMaterialRequestsApi.review(programId, request.requestId, request.submissions.at(-1)!.version, decisions);
  }); }
  const employeeName = (id: string) => employees.find(person => person.id === id)?.name || employees.find(person => person.id === id)?.email || '指定成员暂不可读取';
  return <section id={`weekly-material-panel:${identity}`} className="rounded-2xl border border-stone-200 bg-white p-5 space-y-4"><h3 className="font-semibold">人工素材提交与核验</h3>{!onBindRequiredRequests && <p className="text-sm text-amber-700">此处创建素材任务，尚未绑定冻结发布排期；不会直接解除生产阻塞。</p>}<p className="text-sm text-stone-500">共享素材一次提交，逐视频核验。上传截止与核验截止分别记录；当前时区 {timeZone}。</p>
    {error && <div role="alert" className="rounded bg-red-50 p-3 text-sm text-red-700">{error} <button onClick={() => setReload(value => value + 1)} className="underline">重新加载</button></div>}
    {loaded !== identity ? <p className="text-sm">{error ? '资料尚未读取完成，请解决上方缺口后重新加载。' : '正在读取真实身份、素材库和任务…'}</p> : <>
      <details className="rounded-xl border p-3"><summary className="cursor-pointer text-sm font-medium">创建共享素材任务</summary><div className="mt-3 space-y-2">
        <input aria-label="共享素材身份" value={key} onChange={event => setKey(event.target.value)} placeholder="同一素材的稳定名称，如产品A工厂全景" className="w-full rounded border p-2 text-sm" />
        <textarea aria-label="素材要求" value={requirements} onChange={event => setRequirements(event.target.value)} placeholder="必须拍摄什么、画面标准、数量和事实边界" className="w-full rounded border p-2 text-sm" />
        <div className="flex flex-wrap gap-2"><label className="text-sm">提交人 <select value={assignee} onChange={event => setAssignee(event.target.value)} className="rounded border p-2"><option value="">请选择</option>{employees.map(person => <option key={person.id} value={person.id}>{person.name || person.email}</option>)}</select></label><label className="text-sm">核验人 <select value={reviewer} onChange={event => setReviewer(event.target.value)} className="rounded border p-2"><option value="">请选择</option>{employees.map(person => <option key={person.id} value={person.id}>{person.name || person.email}</option>)}</select></label></div>
        <label className="block text-sm">上传截止 <input type="datetime-local" value={dueAt} onChange={event => setDueAt(event.target.value)} className="rounded border p-2" /></label><label className="block text-sm">核验截止 <input type="datetime-local" value={verificationDueAt} onChange={event => setVerificationDueAt(event.target.value)} className="rounded border p-2" /></label>{!verificationDueAt && <p className="text-xs text-amber-700">尚未设置核验截止，提交后会显示核验排期缺口。</p>}
        {!choices.length&&<p className="text-sm text-amber-700">未读取本版本逐项素材分析，请先完成编导分析并派单；不能手填需求身份解锁生产。</p>}
        {choices.map((choice,index)=><div key={`${choice.publicationTaskId}:${choice.requirementId??index}`} className="rounded border p-2 text-sm"><label><input type="checkbox" disabled={choice.classification!=='human_irreplaceable'||!choice.taskId||!choice.requirementId} checked={!!choice.requirementId&&choice.requirementId in consumers} onChange={event=>setConsumers(previous=>{const next={...previous};if(choice.requirementId){if(event.target.checked)next[choice.requirementId]=choice.description;else delete next[choice.requirementId];}return next;})}/> {choice.publicationTaskId} · {choice.description}</label><p className="mt-1 text-xs text-stone-500">{choice.classification==='human_irreplaceable'?'真人或不可替代证据':choice.classification==='generatable_non_evidentiary'?'可生成的非证据视觉':'性质未知，请重新分析并确认替代边界'} · {choice.reason}</p>{choice.requirementId&&<p className="text-xs text-stone-400">{choice.sourceLabel}</p>}</div>)}
        <button disabled={busy || !productionTasks.length || !Object.keys(consumers).length} onClick={create} className="rounded bg-emerald-900 px-3 py-2 text-sm text-white disabled:opacity-40">创建素材任务</button>
      </div></details>
      {!visible.length && <p className="text-sm text-stone-500">本版本还没有关联的人工素材任务。</p>}
      {visible.map(request => {
        const uploadLate = ['missing', 'rejected'].includes(request.status) && Date.now() > Date.parse(request.dueAt);
        const verificationLate = request.status === 'pending_verification' && request.verificationDueAt && Date.now() > Date.parse(request.verificationDueAt);
        return <article key={request.requestId} id={`weekly-material-request:${identity}:${request.requestId}`} className={`rounded-xl border p-4 space-y-3 ${uploadLate ? 'border-red-300 bg-red-50' : 'border-stone-200'}`}><div className="flex flex-wrap justify-between gap-2"><h4 className="font-medium">{request.requirementKey}</h4><span className="text-sm">{statusLabels[request.status]}</span></div><p className="text-sm">{request.requirements}</p><p className="text-xs text-stone-500">提交：{employeeName(request.assigneeUserId)} · 核验：{employeeName(request.reviewerUserId)}</p><p className="text-xs">上传截止 {new Date(request.dueAt).toLocaleString()} · 核验截止 {request.verificationDueAt ? new Date(request.verificationDueAt).toLocaleString() : '未设置，存在排期缺口'}</p>{uploadLate && <p className="text-sm text-red-700">人工上传已逾期，请及时提交。</p>}{verificationLate && <p className="text-sm text-amber-700">素材已提交，核验已延迟。</p>}
          {request.preparation && <div className="rounded bg-amber-50 p-3 text-xs text-amber-900"><p>最早生产需要素材：{request.preparation.earliestRequiredAt ? new Date(request.preparation.earliestRequiredAt).toLocaleString() : '待补齐真实生产开始时间'}。上传和核验都应在此前完成。</p>{request.preparation.missingScheduleConsumerIds.length > 0 && <p>有 {request.preparation.missingScheduleConsumerIds.length} 条视频缺少前置排期，请先补齐再确认可发布数量。</p>}{(request.preparation.uploadDeadlineAfterRequiredStart || request.preparation.verificationDeadlineAfterRequiredStart) && <p className="mt-1 font-semibold text-red-700">当前素材截止晚于生产所需时间，请调整素材截止或明确修订生产排期。</p>}{request.preparation.verificationDeadlineMissing && <p>核验截止尚未设置，无法确认素材能按时投入制作。</p>}</div>}
          <ul className="text-sm">{request.consumers.map(consumer => <li key={consumer.taskId}>v{consumer.packageVersion} · {consumer.requirement}</li>)}</ul>
          {onBindRequiredRequests&&pkg&&request.status!=='cancelled'&&[request.assigneeUserId,request.reviewerUserId,request.history.find(event=>event.action==='created')?.actor].includes(userId)&&<div><button disabled={busy||!Object.keys(consumers).length} onClick={()=>void act(async()=>{const selected=selectedWeeklyMaterialConsumers(pkg,tasks,Object.keys(consumers));const additions=selected.filter(consumer=>!request.consumers.some(actual=>actual.taskId===consumer.taskId&&actual.packageId===consumer.packageId&&actual.packageVersion===consumer.packageVersion&&actual.requirement===consumer.requirement));const revised=additions.length?await weeklyMaterialRequestsApi.revise(programId,request.requestId,{reason:'明确选择当前真实分析需求复用既有共享素材，新增消费者需重新核验',addConsumers:additions}):request;if(current.current!==identity)return;await onBindRequiredRequests(revised,Object.keys(consumers).map(requirementId=>({requirementId,requestId:request.requestId})));})} className="rounded border px-3 py-2 text-sm disabled:opacity-40">将上方所选真实需求关联此共享素材</button><p className="mt-1 text-xs text-stone-500">跨周保留素材原任务身份；同来源需求可复用，新增版本消费者仍需逐项核验。</p></div>}
          {requiredRequestIds.includes(request.requestId) && !request.consumers.some(consumer => consumer.packageId === packageId && consumer.packageVersion === packageVersion) && <p className="text-sm text-amber-700">当前排期已冻结引用此素材，但当前版本消费者尚未关联，生产仍被阻塞。请使用下方修复入口。</p>}
          {request.status === 'pending_verification' && request.consumers.some(consumer => !request.submissions.at(-1)?.verification?.consumerDecisions.some(decision => decision.taskId === consumer.taskId)) && <p className="text-sm text-amber-700">新增或本次提交的消费者尚未逐项核验；保留的旧通过结论不代表新版本视频已获准使用。</p>}
          {onBindRequiredRequests && request.status !== 'cancelled' && [request.assigneeUserId, request.reviewerUserId, request.history.find(event => event.action === 'created')?.actor].includes(userId) && <div><button disabled={busy} onClick={() => void act(async () => {const bindings=pkg?.socialContentPackage.publicationTasks.flatMap(item=>item.materialRequirement?.bindings?.filter(binding=>binding.requestId===request.requestId)??[])??[];const unique=[...new Map(bindings.map(binding=>[binding.requirementId,binding])).values()];if(!unique.length)throw Error('此任务没有当前冻结需求映射，请先从真实分析选择需求并明确关联。');await onBindRequiredRequests(request,unique); })} className="rounded border px-3 py-2 text-sm disabled:opacity-40">修复已有冻结映射</button><p className="mt-1 text-xs text-stone-500">只修复已明确冻结的需求映射；来源分析改变后需重新选择本版本真实需求，不沿用旧身份。</p></div>}
          {request.assigneeUserId === userId && ['missing', 'rejected'].includes(request.status) && <div id={materialActionPanelId(programId,packageId,packageVersion,request.requestId,'upload')} data-material-program={programId} data-material-package={packageId} data-material-version={packageVersion} data-material-request={request.requestId} data-material-action="upload" tabIndex={-1} className="space-y-2"><label className="block text-sm">上传真实图片或视频 <input disabled={busy} type="file" accept="image/*,video/*" multiple onChange={event => { void upload(request.requestId, event.target.files); event.target.value = ''; }} /></label><p className="text-xs">或选择企业自己的素材库记录</p>{usableMaterials.map(material => { const recordId = materialCanonicalId(material)!; return <label key={material.id} className="block text-sm"><input disabled={busy} type="checkbox" checked={(selectedMaterials[request.requestId] ?? []).includes(recordId)} onChange={event => setSelectedMaterials(previous => ({ ...previous, [request.requestId]: event.target.checked ? [...new Set([...(previous[request.requestId] ?? []), recordId])] : (previous[request.requestId] ?? []).filter(id => id !== recordId) }))} /> {material.name}</label>; })}<button disabled={busy || !(selectedMaterials[request.requestId]?.length)} onClick={() => void act(async () => { await weeklyMaterialRequestsApi.submit(programId, request.requestId, selectedMaterials[request.requestId], request.submissions.at(-1)?.version ?? 0); })} className="rounded bg-emerald-900 px-3 py-2 text-sm text-white disabled:opacity-40">提交所选素材，等待核验</button></div>}
          {request.submissions.at(-1) && <div className="text-xs text-stone-500">最新提交 v{request.submissions.at(-1)!.version} · {request.submissions.at(-1)!.materials.length} 个真实素材 · {new Date(request.submissions.at(-1)!.submittedAt).toLocaleString()}</div>}
          {request.submissions.at(-1)?.materials.map(evidence => { const material = materials.find(item => materialCanonicalId(item) === evidence.recordId); return <div key={evidence.recordId} className="rounded border p-2 text-xs">{material?.url ? <a href={material.url} target="_blank" rel="noreferrer" className="underline text-emerald-800">查看提交素材：{material.name}</a> : <span className="text-amber-700">此提交素材暂未在素材库中读取，请刷新素材库后查看。</span>}<p>实际文件版本 {evidence.sha256.slice(0, 12)} · {evidence.byteSize} 字节</p></div>; })}
          {request.submissions.at(-1)?.verification?.consumerDecisions.map(decision => <div key={decision.taskId} className="rounded bg-stone-50 p-2 text-xs"><p>{request.consumers.find(consumer => consumer.taskId === decision.taskId)?.requirement}：{decision.accepted ? '满足要求' : '需补交'}</p><p>事实：{decision.factCheck}</p><p>权利：{decision.rightsCheck}</p><p>镜头：{decision.visualCheck}</p></div>)}
          {request.reviewerUserId === userId && request.status === 'pending_verification' && <div id={materialActionPanelId(programId,packageId,packageVersion,request.requestId,'verification')} data-material-program={programId} data-material-package={packageId} data-material-version={packageVersion} data-material-request={request.requestId} data-material-action="verification" tabIndex={-1} className="space-y-3">{request.consumers.map(consumer => { const key = `${request.requestId}:${request.submissions.at(-1)?.version ?? 0}:${consumer.taskId}`; const value = reviews[key] ?? { decision: '', factCheck: '', rightsCheck: '', visualCheck: '' }; const patch = (next: Partial<Review>) => setReviews(previous => ({ ...previous, [key]: { ...value, ...next } })); return <fieldset key={key} disabled={busy} className="rounded border p-3 space-y-2"><legend className="text-sm">v{consumer.packageVersion} · {consumer.requirement}</legend><select value={value.decision} onChange={event => patch({ decision: event.target.value as Review['decision'] })} className="rounded border p-2 text-sm"><option value="">请选择核验结论</option><option value="accepted">满足要求</option><option value="rejected">不满足，需补交</option></select>{(['factCheck', 'rightsCheck', 'visualCheck'] as const).map(field => <textarea key={field} value={value[field]} onChange={event => patch({ [field]: event.target.value })} placeholder={{ factCheck: '产品事实核验结论', rightsCheck: '素材权利及授权核验结论', visualCheck: '镜头质量及适用性核验结论' }[field]} className="w-full rounded border p-2 text-sm" />)}</fieldset>; })}<button disabled={busy} onClick={() => void review(request)} className="rounded bg-emerald-900 px-3 py-2 text-sm text-white disabled:opacity-40">保存逐视频核验结果</button></div>}
          {[request.assigneeUserId, request.reviewerUserId, request.history.find(event => event.action === 'created')?.actor].includes(userId) && request.status !== 'cancelled' && <details className="text-sm"><summary>调整截止并保留记录</summary>{(['dueAt', 'verificationDueAt', 'reason'] as const).map(field => <input key={field} type={field === 'reason' ? 'text' : 'datetime-local'} value={revision[request.requestId]?.[field] ?? ''} onChange={event => setRevision(previous => ({ ...previous, [request.requestId]: { ...(previous[request.requestId] ?? { dueAt: '', verificationDueAt: '', reason: '' }), [field]: event.target.value } }))} placeholder={field === 'reason' ? '明确调整原因' : undefined} aria-label={field} className="m-1 rounded border p-2" />)}<button disabled={busy} onClick={() => void act(async () => { const value = revision[request.requestId]; if (!value?.reason.trim() || (!value.dueAt && !value.verificationDueAt)) throw Error('请填写调整原因及至少一项新截止。'); await weeklyMaterialRequestsApi.revise(programId, request.requestId, { reason: value.reason, ...(value.dueAt ? { dueAt: iso(value.dueAt) } : {}), ...(value.verificationDueAt ? { verificationDueAt: iso(value.verificationDueAt) } : {}), timeZone }); })} className="rounded border px-3 py-2">记录截止调整</button></details>}
        </article>;
      })}
    </>}
  </section>;
}
