import type { WeeklySalesHandoff } from '../../../shared/contracts/socialWeeklySalesHandoff';
import type { AgentCalendarTask } from '../smartBusiness/AgentWeeklyCalendar';
export function projectWeeklySalesCalendar(items:WeeklySalesHandoff[],scope:{tenantId:string;programId:string;packageId:string;packageVersion:number;weekStart:string;weekEnd:string}){
 const tasks:AgentCalendarTask[]=[],references:WeeklySalesHandoff[]=[];const seen=new Set<string>();
 for(const item of items){if(item.tenantId!==scope.tenantId||item.programId!==scope.programId||seen.has(item.id))continue;seen.add(item.id);if(item.packageId!==scope.packageId||item.packageVersion!==scope.packageVersion){references.push(item);continue;}
 for(const action of ['claim','feedback'] as const){const instant=action==='claim'?item.claimDueAt:item.feedbackDueAt;const d=new Date(instant);if(!Number.isFinite(d.getTime()))continue;const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(date<scope.weekStart||date>scope.weekEnd){if(!references.some(r=>r.id===item.id))references.push(item);continue;}
 const completed=action==='claim'?item.claimedAt!==null:item.feedback!==null;tasks.push({id:`sales:${item.id}:${action}`,date,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,timeSemantics:'finish',agent:'human',title:action==='claim'?'销售领取客户交接':'销售处理结果反馈',context:`客服 Agent ${item.channel||'whatsapp'} 交接 · ${item.sourceKind==='new_inquiry'?'真实新询盘':item.sourceKind==='existing_contact'?'既有联系（非采购证明）':'既有客户'} · ${item.customerId}`,output:completed?(action==='claim'?'指定销售已实际领取':item.feedback!.result):action==='claim'?'指定销售领取已批准客户交接':'记录真实处理证据、下一步及截止',minutes:null,status:completed?'completed':item.status==='awaiting_claim'&&action==='feedback'?'blocked':'planned',reason:item.status==='needs_information'?'需要补充客户资料':undefined,assignee:item.ownerUserId,dueAt:instant,salesHandoffId:item.id,salesPackageId:item.packageId,salesPackageVersion:item.packageVersion,salesAction:action,availableForHuman:action==='claim'||item.claimedAt!==null});}
 if(item.status==='needs_information'&&item.feedback){const d=new Date(item.feedback.nextDueAt);if(Number.isFinite(d.getTime())){const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(date>=scope.weekStart&&date<=scope.weekEnd)tasks.push({id:`sales:${item.id}:information`,date,time:`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`,timeSemantics:'finish',agent:'human',title:'补充销售交接资料',context:`客服交接 · ${item.customerId}`,output:item.feedback.nextStep,minutes:null,status:'planned',assignee:item.ownerUserId,dueAt:item.feedback.nextDueAt,salesHandoffId:item.id,salesPackageId:item.packageId,salesPackageVersion:item.packageVersion,salesAction:'feedback',availableForHuman:true});else if(!references.some(r=>r.id===item.id))references.push(item);}}
 }return {tasks,references};
}
