import {dispatchDigitalEmployeeDeepLink} from '../../lib/digitalEmployees';
import {nativeRecoveryPanelId,nativeRecoveryProductionLink} from './weeklyNativeRecoveryCalendar';
import {useEffect,useRef,useState} from 'react';
import {authApi,getToken,type EmployeeAccount} from '../../lib/auth';
import {weeklyNativeSendRecoveryApi,type WeeklyNativeSendRecoveryScope,type WeeklyNativeSendRecovery,type WeeklyNativeSendRecoverySource} from '../../lib/weeklyNativeSendRecoveryApi';
export default function WeeklyNativeSendRecoveryPanel({onChanged,...scope}:WeeklyNativeSendRecoveryScope&{onChanged?:(items:WeeklyNativeSendRecovery[])=>void}){
 const identity=JSON.stringify([scope.tenantId,scope.programId,scope.packageId,scope.packageVersion,getToken()]);const live=useRef(identity);live.current=identity;
 const [snapshot,setSnapshot]=useState<{identity:string;items:WeeklyNativeSendRecovery[];sources:WeeklyNativeSendRecoverySource[];employees:EmployeeAccount[]}|null>(null),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState(''),[owner,setOwner]=useState(''),[deadline,setDeadline]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{let active=true;setSnapshot(null);setError(null);setBusy(false);setSelected('');setOwner('');void Promise.all([weeklyNativeSendRecoveryApi.list(scope),weeklyNativeSendRecoveryApi.sources(scope),authApi.employees()]).then(([items,sources,employees])=>{if(active&&live.current===identity){setSnapshot({identity,items,sources,employees});setUnknown(false);onChanged?.(items);}}).catch(cause=>{if(active&&live.current===identity)setError(cause instanceof Error?cause.message:'人工任务读取失败。');});return()=>{active=false;};},[identity,reload]);
 const data=snapshot?.identity===identity?snapshot:null;const source=data?.sources.find(s=>`${s.channel}:${s.requestId}`===selected);
 const write=async(item?:WeeklyNativeSendRecovery)=>{if(busy||unknown||!data||(!item&&(!source||!data.employees.some(e=>e.id===owner)||!reason.trim())))return;const captured=identity;setBusy(true);setUnknown(true);setError(null);try{if(item)await weeklyNativeSendRecoveryApi.resolve(scope,item);else await weeklyNativeSendRecoveryApi.create(scope,{channel:source!.channel,requestId:source!.requestId,ownerUserId:owner,deadlineAt:deadline,reason:reason.trim()});if(live.current===captured){setReload(n=>n+1);window.dispatchEvent(new Event('lingshu:agent-business-refresh'));}}catch(cause){if(live.current===captured)setError(cause instanceof Error?cause.message:'处理结果尚未恢复，请只读刷新。');}finally{if(live.current===captured)setBusy(false);}};
 return <section className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h4 className="text-sm font-bold">Messenger / Instagram 发送异常人工处理</h4><button type="button" disabled={busy} className="text-xs underline" onClick={()=>setReload(n=>n+1)}>只读刷新</button></div><p className="text-xs text-slate-600">指定真实负责人和截止时间。缺少平台消息身份时保持受阻，人工核验不会发送消息。</p>{error&&<p role="alert" className="text-xs text-amber-800">{error}</p>}{unknown&&<p className="text-xs text-amber-800">处理结果尚待恢复，请先只读刷新。</p>}{data&&<><select aria-label="实际原发送请求" value={selected} disabled={busy||unknown} onChange={e=>setSelected(e.target.value)}><option value="">选择实际受阻发送</option>{data.sources.filter(s=>s.canCreate).map(s=><option key={`${s.channel}:${s.requestId}`} value={`${s.channel}:${s.requestId}`}>{s.channel} · {s.customerId} · {s.requestId}</option>)}</select><select aria-label="真实异常处理负责人" value={owner} disabled={busy||unknown} onChange={e=>setOwner(e.target.value)}><option value="">明确负责人</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name||e.email}</option>)}</select><input aria-label="明确带时区截止时间" placeholder="2026-10-11T18:00:00+08:00" value={deadline} disabled={busy||unknown} onChange={e=>setDeadline(e.target.value)}/><textarea aria-label="人工处理原因" value={reason} disabled={busy||unknown} onChange={e=>setReason(e.target.value)}/><button type="button" disabled={busy||unknown||!source||!owner||!deadline||!reason.trim()} onClick={()=>void write()}>创建原发送处理任务</button>{data.items.map(item=><article key={item.id} id={nativeRecoveryPanelId(scope,item.id)} tabIndex={-1} data-tenant={item.tenantId} data-run={item.runId} data-task={item.taskId} data-request={item.requestId} data-channel={item.channel} className={`rounded-lg border p-3 ${item.overdue&&item.status!=='resolved'?'border-red-500 bg-red-50 text-red-800':''}`}><p className="text-xs font-semibold">客服Agent · {item.channel} · {item.customerId} · {item.status==='resolved'?'原任务恢复凭据已核验':'待人工处理'}</p><p className="text-xs">负责人 {data.employees.find(e=>e.id===item.ownerUserId)?.name||item.ownerUserId} · 截止 {item.deadlineAt}{item.overdue?' · 已逾期':''}</p><p className="text-xs">{item.reason} · {item.gap}</p><button type="button" className="text-xs underline" onClick={()=>{try{if(live.current!==identity)throw Error('当前周包已变化。');dispatchDigitalEmployeeDeepLink(nativeRecoveryProductionLink(item,scope));}catch(cause){setError(cause instanceof Error?cause.message:'原客服入口尚未核验。');}}}>进入原客服生产任务</button>{item.status!=='resolved'&&<button type="button" disabled={busy||unknown} onClick={()=>void write(item)}>仅核验原可信回执并恢复任务</button>}</article>)}</>}</section>;
}
