import {useEffect,useRef,useState} from 'react';
import type {WeeklyOperatingPackage,WeeklyExecutionTask} from '../../../shared/contracts/socialProgram';
import type {WeeklyRunningResourceEvidence} from '../../../server/socialPrograms/weeklyRunningResourceEvidence';
import {weeklyRunningResourceEvidenceApi} from '../../lib/weeklyRunningResourceEvidenceApi';
import {getToken} from '../../lib/auth';
const gapLabels:Record<string,string>={planner_resource_mapping_missing:'并发池尚未映射为排期资源',provider_finish_receipt_missing:'供应商尚无可信完成时间',remaining_operation_manifest_missing:'剩余付费操作清单未冻结',remaining_cost_unknown:'完整剩余费用未知',production_lease_expired:'生产租约已到期',production_lease_missing:'没有生产租约',production_lease_inconsistent:'生产租约与运行不一致',actual_start_missing:'缺实际开工时间',persisted_queue_limits_missing:'缺持久并发配置',operation_cost_receipts_missing:'缺已发起操作费用回执',initiated_operation_cost_unknown:'已有操作费用仍未知'};
export default function WeeklyRunningResourceEvidencePanel({pkg,tasks}:{pkg:WeeklyOperatingPackage;tasks:WeeklyExecutionTask[]}){
 const identity=JSON.stringify([getToken(),pkg.programId,pkg.packageId,pkg.version]),active=useRef(identity);active.current=identity;
 const [selection,setSelection]=useState<{identity:string;taskId:string}|null>(null),[data,setData]=useState<{identity:string;taskId:string;item:WeeklyRunningResourceEvidence}|null>(null),[error,setError]=useState<{identity:string;taskId:string;message:string}|null>(null),[busy,setBusy]=useState(false);const taskId=selection?.identity===identity?selection.taskId:'';const selected=useRef(taskId);selected.current=taskId;
 useEffect(()=>setBusy(false),[identity]);
 const options=tasks.filter(t=>t.programId===pkg.programId&&t.packageId===pkg.packageId&&t.packageVersion===pkg.version&&t.workflowKind==='content');const item=data?.identity===identity&&data.taskId===taskId?data.item:null;
 const read=async()=>{if(!taskId)return;setBusy(true);try{const item=await weeklyRunningResourceEvidenceApi.read(pkg.programId,pkg.packageId,pkg.version,taskId);if(active.current===identity&&selected.current===taskId){setData({identity,taskId,item});setError(null);}}catch(e){if(active.current===identity&&selected.current===taskId)setError({identity,taskId,message:e instanceof Error?e.message:String(e)});}finally{if(active.current===identity)setBusy(false);}};
 return <section className="space-y-3 rounded-lg border border-border bg-white p-4"><h4 className="font-bold">运行资源与费用证据</h4><p className="text-xs">读取具体真实任务的供应商回执、生产租约、并发配置和已发起操作费用。完整剩余费用、可用资源时段及可信完成时间仍缺少持久合同，暂不能据此承诺发布可达。</p><select aria-label="资源证据任务" value={taskId} disabled={busy} onChange={e=>setSelection({identity,taskId:e.target.value})}><option value="">选择本周真实内容任务</option>{options.map(t=><option key={t.taskId} value={t.taskId}>{t.taskId} · {t.schedule.stepKind} · {t.status}</option>)}</select><button type="button" disabled={!taskId||busy} onClick={()=>void read()} className="text-accent">只读核查资源证据</button>{error?.identity===identity&&error.taskId===taskId&&<p role="alert" className="text-xs">{error.message}</p>}{item&&<div className="space-y-2 text-xs"><p>实际运行 {item.runId} · {item.job.status} · 核查 {item.verifiedAt}</p><p>生产租约 {item.lease.status} · 到期 {item.lease.expiresAt??'缺数据'} · 真实开始 {item.job.lastStartedAt??'缺数据'}</p><p>剩余费用：未知 · 可信完成时间：缺失 · 倒排资源映射：缺失</p>{item.configuredQueueLimits.map(l=><p key={l.id}>持久并发配置 {l.scope}/{l.scopeKey}：{l.maxRunning}</p>)}{item.providerReceipts.map(r=><p key={`${r.provider}:${r.requestId}`}>供应商 {r.provider} · 回执 {r.providerTaskId??r.requestId} · {r.state}</p>)}{item.operationCosts.map(c=><p key={c.recordId}>操作 {c.reservationId} · {c.eventType}/{c.state} · 费用状态 {c.costStatus} · {c.eventType==='terminal'?'已结算':'预占'} {c.eventType==='terminal'?(c.settledCostCny===null?'未知':`${c.settledCostCny} 元`):(c.reservedCostDeltaCny===null?'未知':`${c.reservedCostDeltaCny} 元`)}</p>)}<p>待补证据：{item.gaps.map(g=>gapLabels[g]??'有待核查的证据缺口').join('、')}</p></div>}</section>;
}
