import {publicationRecoveryPanelId} from './weeklyPublicationRecoveryCalendar';
import {useEffect,useRef,useState} from 'react';
import {authApi,getToken,type EmployeeAccount} from '../../lib/auth';
import {weeklyPublicationRecoveryApi,type WeeklyPublicationRecoveryScope,type WeeklyPublicationRecovery,type WeeklyPublicationRecoverySource} from '../../lib/weeklyPublicationRecoveryApi';
export default function WeeklyPublicationRecoveryPanel({onChanged,...scope}:WeeklyPublicationRecoveryScope&{onChanged?:(items:WeeklyPublicationRecovery[])=>void}){
 const identity=JSON.stringify([scope.tenantId,scope.programId,scope.packageId,scope.packageVersion,getToken()]);const live=useRef(identity);live.current=identity;
 const [snapshot,setSnapshot]=useState<{identity:string;items:WeeklyPublicationRecovery[];sources:WeeklyPublicationRecoverySource[];employees:EmployeeAccount[]}|null>(null),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[unknown,setUnknown]=useState(false),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState(''),[owner,setOwner]=useState(''),[deadline,setDeadline]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{let active=true;setSnapshot(null);setError(null);setBusy(false);setSelected('');setOwner('');void Promise.all([weeklyPublicationRecoveryApi.list(scope),weeklyPublicationRecoveryApi.sources(scope),authApi.employees()]).then(([items,sources,employees])=>{if(active&&live.current===identity){setSnapshot({identity,items,sources,employees});setUnknown(false);onChanged?.(items);}}).catch(cause=>{if(active&&live.current===identity)setError(cause instanceof Error?cause.message:'发布异常读取失败。');});return()=>{active=false;};},[identity,reload]);
 useEffect(()=>{const select=(event:Event)=>{const d=(event as CustomEvent).detail as Record<string,unknown>|undefined;if(!d||d.tenantId!==scope.tenantId||d.programId!==scope.programId||d.packageId!==scope.packageId||d.packageVersion!==scope.packageVersion||typeof d.taskId!=='string'||typeof d.attemptId!=='string')return;const current=snapshot?.identity===identity?snapshot:null,match=current?.sources.filter(source=>source.taskId===d.taskId&&source.attemptId===d.attemptId)??[];if(match.length!==1){setError('原发布尝试恢复来源尚未读取，请先只读刷新。');return;}setSelected(match[0]!.taskId);document.getElementById(`publication-recovery-workspace:${encodeURIComponent(scope.tenantId)}:${encodeURIComponent(scope.programId)}:${encodeURIComponent(scope.packageId)}:${scope.packageVersion}`)?.scrollIntoView({behavior:'smooth',block:'start'});};window.addEventListener('lingshu:publication-recovery-select',select);return()=>window.removeEventListener('lingshu:publication-recovery-select',select);},[identity,snapshot]);
 const data=snapshot?.identity===identity?snapshot:null;const source=data?.sources.find(s=>s.taskId===selected);
 const write=async(item?:WeeklyPublicationRecovery)=>{if(busy||unknown||!data||(!item&&(!source||!data.employees.some(e=>e.id===owner)||!reason.trim())))return;const captured=identity;setBusy(true);setUnknown(true);setError(null);try{if(item)await weeklyPublicationRecoveryApi.resolve(scope,item);else await weeklyPublicationRecoveryApi.create(scope,{taskId:source!.taskId,ownerUserId:owner,deadlineAt:deadline,reason:reason.trim()});if(live.current===captured){setReload(n=>n+1);window.dispatchEvent(new Event('lingshu:agent-business-refresh'));}}catch(cause){if(live.current===captured)setError(cause instanceof Error?cause.message:'处理结果尚未恢复，请只读刷新。');}finally{if(live.current===captured)setBusy(false);}};
 return <section id={`publication-recovery-workspace:${encodeURIComponent(scope.tenantId)}:${encodeURIComponent(scope.programId)}:${encodeURIComponent(scope.packageId)}:${scope.packageVersion}`} className="space-y-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h4 className="text-sm font-bold">S4 · 发布异常人工处理</h4><button type="button" disabled={busy} className="text-xs underline" onClick={()=>setReload(n=>n+1)}>只读刷新</button></div><p className="text-xs text-slate-600">核对原发布尝试的真实平台回执。对账不会提交新发布，恢复请求不等于发布完成。</p>{error&&<p role="alert" className="text-xs text-amber-800">{error}</p>}{unknown&&<p className="text-xs text-amber-800">处理结果尚待恢复，请先只读刷新。</p>}{data&&<><select aria-label="实际受阻发布任务" value={selected} disabled={busy||unknown} onChange={e=>setSelected(e.target.value)}><option value="">选择原发布任务</option>{data.sources.map(s=><option key={s.taskId} value={s.taskId}>{s.platform} · {s.publicationTaskId} · {s.attemptStatus}</option>)}</select><select aria-label="真实发布异常负责人" value={owner} disabled={busy||unknown} onChange={e=>setOwner(e.target.value)}><option value="">明确负责人</option>{data.employees.map(e=><option key={e.id} value={e.id}>{e.name||e.email}</option>)}</select><input aria-label="明确带时区处理截止" placeholder="2026-10-11T18:00:00+08:00" value={deadline} disabled={busy||unknown} onChange={e=>setDeadline(e.target.value)}/><textarea aria-label="发布异常处理原因" value={reason} disabled={busy||unknown} onChange={e=>setReason(e.target.value)}/><button type="button" disabled={busy||unknown||!source||!owner||!deadline||!reason.trim()} onClick={()=>void write()}>创建原发布处理任务</button>{data.items.map(item=><article key={item.id} id={publicationRecoveryPanelId(scope,item.id)} tabIndex={-1} data-tenant={item.tenantId} data-task={item.taskId} data-publication={item.publicationTaskId} data-attempt={item.attemptId} className={`rounded-lg border p-3 ${item.overdue&&!item.completionProof?'border-red-500 bg-red-50 text-red-800':''}`}><p className="text-xs font-semibold">经营Agent · {item.platform} · {item.completionProof?'原发布完成已核验':item.status==='resume_requested'?'已请求恢复，等待原任务完成':'待人工核验'}</p><p className="text-xs">账号 {item.accountId} · 母版 {item.motherContentId}{item.adaptationOfPublicationTaskId?' · 平台改编版本':' · 原发布版本'}</p><p className="text-xs">原发布 {item.publicationTaskId} · 原尝试 {item.attemptId}</p><p className="text-xs">负责人 {data.employees.find(e=>e.id===item.ownerUserId)?.name||item.ownerUserId} · 截止 {item.deadlineAt}{item.overdue?' · 已逾期':''}</p><p className="text-xs">{item.reason} · {item.gap}</p>{!item.completionProof&&<button type="button" disabled={busy||unknown} onClick={()=>void write(item)}>核对原回执并请求恢复（不重新发布）</button>}</article>)}</>}</section>;
}
