import type{SocialWeeklyPublicationTask,WeeklyExecutionTask,WeeklyOperatingPackage,WeeklyProductionStepKind}from'../../../shared/contracts/socialProgram';
import type{WeeklyScheduledPackage}from'../../../shared/contracts/socialWeeklyScheduleRevision';
export interface ExecutionCalendarPresentationOptions{pkg?:WeeklyOperatingPackage;profile?:'cold_start'|'account_repair'|null}
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const text=(v:unknown)=>typeof v==='string'&&v.trim()?v.trim():null;
const platforms:Record<string,string>={tiktok:'TikTok',facebook:'Facebook',instagram:'Instagram',youtube:'YouTube'};
const mainSteps:Partial<Record<WeeklyProductionStepKind,number>>={business_outline:1,benchmark_collection:2,benchmark_scoring:2,director_analysis:2,business_schedule:3,material_preparation:4,material_readiness:4,script:4,storyboard:4,asset_generation:5,video_generation:5,quality_check:5,rework:5,user_approval:5,publishing:6,performance_monitoring:8,weekly_review:8};
const mainNames={cold_start:['建立经营基础与对标需求','外部参考采集与精确分析','首周详细排期与派单','企业化脚本与执行方案','首批复刻制作与验收','首批发布与建立基线','新询盘承接与知识补充','冷启动复盘与下周建议'],account_repair:['审计基线与经营目标','双来源分析与调性提取','双来源排期与派单','双路线脚本与执行复核','迭代/探索制作与验收','发布与历史关联','老客推进＋新询盘承接','双来源复盘与配额调整']};
const sideNames={cold_start:{1:'首批真人拍摄/上传',2:'首次配置/事实/权利/预算补齐',4:'首发失败/未知回执',5:'首批数据观察',6:'首批内容模板提炼与核验',8:'冷启动计划修订',9:'跨周延续与画像升级建议'},account_repair:{1:'历史素材补齐/增量拍摄',2:'历史证据/授权/事实/预算补齐',4:'双路线发布失败/对账',5:'历史与双来源数据比较',6:'自有与外部内容模板提炼与核验',8:'双来源计划修订',9:'跨周库存/未结任务衔接'}};
const sameRef=(a:unknown,b:unknown)=>{const x=object(a),y=object(b);return Boolean(x.type&&x.id&&Number.isSafeInteger(x.version)&&x.type===y.type&&x.id===y.id&&x.version===y.version);};
function scopedPackage(task:WeeklyExecutionTask,pkg?:WeeklyOperatingPackage){return pkg&&pkg.programId===task.programId&&pkg.packageId===task.packageId&&pkg.version===task.packageVersion?pkg:null;}
function publication(v:unknown):SocialWeeklyPublicationTask|null{const p=object(v);return text(p.publicationTaskId)&&text(p.motherContentId)&&text(p.accountId)&&platforms[String(p.platform)]?p as unknown as SocialWeeklyPublicationTask:null;}
function samePublication(a:SocialWeeklyPublicationTask,b:SocialWeeklyPublicationTask){return a.publicationTaskId===b.publicationTaskId&&a.motherContentId===b.motherContentId&&a.accountId===b.accountId&&a.platform===b.platform;}
function publicationsForTask(task:WeeklyExecutionTask,pkg:WeeklyOperatingPackage|null){const input=object(task.inputSnapshot),single=publication(input.publicationTask);let actual:SocialWeeklyPublicationTask[]=[];if(input.publicationTask&&!single)return[];if(input.variants&&!Array.isArray(input.variants))return[];if(single){if(task.publicationTaskId&&single.publicationTaskId!==task.publicationTaskId||task.accountId&&single.accountId!==task.accountId)return[];actual=[single];}else if(Array.isArray(input.variants)){const raw=input.variants.map(publication);if(raw.some(p=>!p)||new Set(raw.map(p=>p!.publicationTaskId)).size!==raw.length)return[];actual=raw as SocialWeeklyPublicationTask[];if(text(input.motherContentId)&&actual.some(p=>p.motherContentId!==input.motherContentId))return[];}else if(pkg){actual=pkg.socialContentPackage.publicationTasks.filter(p=>task.publicationTaskId?p.publicationTaskId===task.publicationTaskId:task.accountId?p.accountId===task.accountId:text(input.motherContentId)?p.motherContentId===input.motherContentId:false);}
 if(actual.some(p=>task.accountId&&p.accountId!==task.accountId||task.publicationTaskId&&p.publicationTaskId!==task.publicationTaskId))return[];
 if(pkg&&actual.some(p=>pkg.socialContentPackage.publicationTasks.filter(q=>samePublication(p,q)).length!==1))return[];return actual;}
function topicFor(task:WeeklyExecutionTask,pub:SocialWeeklyPublicationTask,pkg:WeeklyOperatingPackage|null){if(!pkg)return null;const plan=pkg.agentPlanning,dispatch=plan?.dispatch;if(!plan||!Array.isArray(dispatch?.scheduleItems)||plan.packageId!==pkg.packageId||plan.packageVersion!==pkg.version||!dispatch||dispatch.packageId!==pkg.packageId||dispatch.packageVersion!==pkg.version)return null;const frozenRef=object(task.inputSnapshot).dispatchRef;if(frozenRef&&!sameRef(frozenRef,{type:'business_content_dispatch',id:dispatch.dispatchId,version:1}))return null;const matches=dispatch.scheduleItems.filter(i=>i.publicationTaskId===pub.publicationTaskId&&i.accountId===pub.accountId&&i.platform===pub.platform);if(matches.length!==1)return null;const frozen=object(object(task.inputSnapshot).detailedScheduleItem);if(frozen.publicationTaskId&&(frozen.publicationTaskId!==pub.publicationTaskId||frozen.scheduleItemId!==matches[0]!.scheduleItemId||frozen.topic!==matches[0]!.topic))return null;return text(matches[0]!.topic);}
export function executionCalendarChains(task:WeeklyExecutionTask,options:ExecutionCalendarPresentationOptions={}){const storedRoute=task.chainProfile==='b2b_cold_start'?'cold_start':task.chainProfile==='b2b_established'?'account_repair':null;const route=storedRoute??options.profile;if(options.pkg&&!scopedPackage(task,options.pkg))return undefined;if(storedRoute&&options.profile&&storedRoute!==options.profile)return undefined;if(task.chainProfile&&options.pkg?.referenceSourcePolicy?.profile!==task.chainProfile)return undefined;if(!route||!mainNames[route])return undefined;const prefix=route==='cold_start'?'Z':'H';const storedMain=task.chainTaskCode?.startsWith(`${prefix}-M`)?Number(task.chainTaskCode.slice(3)):null;const main=storedMain&&storedMain>=1&&storedMain<=8?storedMain:mainSteps[task.schedule.stepKind];const parts=main?[`${prefix}-M${main} ${mainNames[route][main-1]}`]:[];const side=new Set<1|2|4|5|6|8|9>();if(task.schedule.stepKind==='performance_monitoring')side.add(5);if(['template_extraction','template_performance_validation'].includes(task.schedule.stepKind))side.add(6);const input=object(task.inputSnapshot),pkg=scopedPackage(task,options.pkg);if(pkg&&sameRef(input.scheduleRevisionRef,(pkg as WeeklyScheduledPackage).scheduleRevisionRef))side.add(8);if(task.continuationObservation?.status==='ready'&&task.continuationObservation.sourceTaskId&&Number.isSafeInteger(task.continuationObservation.sourceVersion)&&task.continuationObservation.sourceVersion!<task.packageVersion)side.add(9);const code=task.lastError?.code,activeError=task.status!=='succeeded'&&task.status!=='cancelled';const material=object(object(input.publicationTask).materialRequirement);if(activeError&&code==='weekly_required_materials_missing'&&material.required===true&&Array.isArray(material.requestIds)&&material.requestIds.length>0)side.add(1);if(activeError&&['weekly_required_material_contract_missing','weekly_real_publishing_disabled','authorization_revoked','reception_binding_missing','reception_binding_invalid'].includes(code??''))side.add(2);if(activeError&&task.schedule.stepKind==='publishing'&&['publication_receipt_reconciliation_pending','publication_rejected'].includes(code??''))side.add(4);for(const s of side)parts.push(`${prefix}-S${s} ${s===9?'已核验原版本任务衔接':sideNames[route][s]}`);return parts.join(' · ')||undefined;}
export function executionCalendarPresentation(task:WeeklyExecutionTask,label:string,options:ExecutionCalendarPresentationOptions={}){const pkg=scopedPackage(task,options.pkg),input=object(task.inputSnapshot);const pubs=publicationsForTask(task,pkg);const topics=[...new Set(pubs.map(p=>topicFor(task,p,pkg)).filter((v):v is string=>Boolean(v)))];const source=input.referenceSource==='owned'||input.referenceSource==='external'?input.referenceSource:pkg?.agentPlanning?.skeleton?.slots?.find(s=>s.motherContentId===(pubs[0]?.motherContentId??input.motherContentId))?.referenceSource;const sourceLabel=source==='owned'?(options.profile==='account_repair'?'自有迭代':'自有参考'):source==='external'?(options.profile==='account_repair'?'外部探索':'外部参考'):null;
 const frozenContext=Boolean(pkg||pubs.length||text(input.objective));const packageLevel=!pubs.length&&!task.publicationTaskId&&!task.accountId&&!text(input.motherContentId);const unresolved=pubs.filter(p=>!topicFor(task,p,pkg)).length;const topic=topics.length?`${topics.join(' / ')}${unresolved?` / ${unresolved}条待编导明确`:''}`:packageLevel?text(input.objective)||text(pkg?.objective):'待编导明确';const title=frozenContext?`${label}${topic?` · ${topic}`:''}`:label;const accounts=[...new Set(pubs.map(p=>`${platforms[p.platform]} · ${text(p.accountPositioning)||`账号 ${p.accountId}`}`))];const context=pubs.length?`${accounts.join(' / ')}${sourceLabel?` · ${sourceLabel}`:''} · ${pubs.length===1?'发布任务':'关联发布'} ${pubs.map(p=>p.publicationTaskId).join('、')}`:pkg?`${pkg.weekStart} — ${pkg.weekEnd}${task.accountId?` · 账号 ${task.accountId}`:''}${sourceLabel?` · ${sourceLabel}`:''}${!packageLevel?' · 主题待编导明确':''}`:task.publicationTaskId?`视频任务 ${task.publicationTaskId}`:task.accountId?`账号 ${task.accountId}`:`周任务包 ${task.packageId}`;
 return{title,context,topic:topics.length?`${topics.join(' / ')}${unresolved?` / ${unresolved}条待编导明确`:''}`:null,chain:executionCalendarChains(task,options)};}
