import {createHash} from 'node:crypto';
export type InstagramArchivedStreamProof={version:'instagram_mp4_stream_v1';fileSha256:string;bytes:number;status:'passed'|'blocked'|'unknown';reasons:string[];proofHash:string};
type Atom={type:string;start:number;body:number;end:number};
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
/** Exact archived bytes, no filenames or caller supplied stream claims. Unsupported layouts fail closed. */
export function inspectInstagramArchivedStreamProof(bytes:Buffer):InstagramArchivedStreamProof{
 const reasons:string[]=[];let status:InstagramArchivedStreamProof['status']='passed';
 const atoms=(start:number,end:number):Atom[]=>{const out:Atom[]=[];while(start<end){if(end-start<8)throw Error('truncated_atom');let size=bytes.readUInt32BE(start),header=8;if(size===1){if(end-start<16)throw Error('truncated_atom');const big=bytes.readBigUInt64BE(start+8);if(big>BigInt(Number.MAX_SAFE_INTEGER))throw Error('oversized_atom');size=Number(big);header=16;}else if(size===0)size=end-start;if(size<header||start+size>end)throw Error('invalid_atom_size');out.push({type:bytes.toString('ascii',start+4,start+8),start,body:start+header,end:start+size});if(out.length>100000)throw Error('atom_limit');start+=size;}return out;};
 const child=(parent:Atom,type:string)=>{const found=atoms(parent.body,parent.end).filter(a=>a.type===type);if(found.length!==1)throw Error(`missing_or_duplicate_${type}`);return found[0];};
 const table=(a:Atom,stride:number):number=>{if(a.end-a.body<8)throw Error('truncated_table');const n=bytes.readUInt32BE(a.body+4);if(n>1000000||a.body+8+n*stride!==a.end)throw Error('invalid_table');return n;};
 try{
 if(bytes.length>110*1024*1024)throw Error('proof_byte_limit');const top=atoms(0,bytes.length);if(top.some(a=>a.type==='moof'))throw Error('fragmented_mp4_unsupported');const moov=top.find(a=>a.type==='moov'),mdats=top.filter(a=>a.type==='mdat');if(!moov||!mdats.length)throw Error('missing_moov_or_mdat');if(moov.start>mdats[0].start){status='blocked';reasons.push('moov_after_mdat');}
 let videos=0;
 for(const trak of atoms(moov.body,moov.end).filter(a=>a.type==='trak')){
 if(atoms(trak.body,trak.end).some(a=>a.type==='edts')){status='blocked';reasons.push('edit_list_present');}
 const mdia=child(trak,'mdia'),hdlr=child(mdia,'hdlr');if(hdlr.end-hdlr.body<12)throw Error('truncated_handler');if(bytes.toString('ascii',hdlr.body+8,hdlr.body+12)!=='vide')continue;videos++;
 const stbl=child(child(mdia,'minf'),'stbl'),stsd=child(stbl,'stsd');if(stsd.end-stsd.body<8||bytes.readUInt32BE(stsd.body+4)!==1)throw Error('sample_description_unsupported');const descriptions=atoms(stsd.body+8,stsd.end);if(descriptions.length!==1||descriptions[0].type!=='avc1')throw Error('codec_unsupported');const entry=descriptions[0];if(entry.end-entry.body<78)throw Error('truncated_avc_entry');const avcc=atoms(entry.body+78,entry.end).find(a=>a.type==='avcC');if(!avcc||avcc.end-avcc.body<5||bytes[avcc.body]!==1)throw Error('missing_avcc');const nalLength=(bytes[avcc.body+4]&3)+1;if(nalLength===3)throw Error('invalid_nal_length');
 const stsz=child(stbl,'stsz');if(stsz.end-stsz.body<12)throw Error('truncated_stsz');const fixed=bytes.readUInt32BE(stsz.body+4),count=bytes.readUInt32BE(stsz.body+8);if(!count||count>1000000||stsz.body+12+(fixed?0:count*4)!==stsz.end)throw Error('invalid_stsz');const sizes=Array.from({length:count},(_,i)=>fixed||bytes.readUInt32BE(stsz.body+12+i*4));
 const stss=child(stbl,'stss'),syncCount=table(stss,4),sync=new Set<number>();for(let i=0;i<syncCount;i++){const n=bytes.readUInt32BE(stss.body+8+i*4);if(!n||n>count||sync.has(n))throw Error('invalid_sync_table');sync.add(n);}if(!sync.has(1))throw Error('first_sample_not_idr');
 const stsc=child(stbl,'stsc'),mappingCount=table(stsc,12),mapping=Array.from({length:mappingCount},(_,i)=>({first:bytes.readUInt32BE(stsc.body+8+i*12),samples:bytes.readUInt32BE(stsc.body+12+i*12),description:bytes.readUInt32BE(stsc.body+16+i*12)}));if(!mapping.length||mapping[0].first!==1||mapping.some((m,i)=>!m.samples||m.description!==1||(i>0&&m.first<=mapping[i-1].first)))throw Error('invalid_chunk_mapping');const offsetAtoms=atoms(stbl.body,stbl.end).filter(a=>['stco','co64'].includes(a.type));if(offsetAtoms.length!==1)throw Error('missing_chunk_offsets');const offsets=offsetAtoms[0],wide=offsets.type==='co64',chunks=table(offsets,wide?8:4);if(mapping.at(-1)!.first>chunks)throw Error('invalid_chunk_mapping');let sample=0,map=0;
 for(let c=1;c<=chunks;c++){while(map+1<mapping.length&&mapping[map+1].first<=c)map++;const raw=wide?bytes.readBigUInt64BE(offsets.body+8+(c-1)*8):BigInt(bytes.readUInt32BE(offsets.body+8+(c-1)*4));if(raw>BigInt(bytes.length))throw Error('chunk_outside_file');let position=Number(raw);for(let j=0;j<mapping[map].samples;j++){if(sample>=count)throw Error('sample_count_mismatch');const end=position+sizes[sample];if(!mdats.some(a=>position>=a.body&&end<=a.end))throw Error('sample_outside_mdat');let idr=false,vcl=false,nonIdr=false;while(position<end){if(position+nalLength>end)throw Error('truncated_nal');let length=0;for(let n=0;n<nalLength;n++)length=length*256+bytes[position+n];position+=nalLength;if(!length||position+length>end)throw Error('invalid_nal');if(bytes[position]&128)throw Error('forbidden_nal_bit');const type=bytes[position]&31;if(type>=1&&type<=5)vcl=true;if(type===5)idr=true;if(type>=1&&type<=4)nonIdr=true;position+=length;}if(!vcl||(idr&&nonIdr)||sync.has(sample+1)!==idr)throw Error('sync_sample_not_idr');sample++;}}
 if(sample!==count)throw Error('sample_count_mismatch');
 }
 if(videos!==1)throw Error('video_track_count_unsupported');
 }catch(error){if(status!=='blocked')status='unknown';reasons.push(error instanceof Error?error.message:'stream_proof_failed');}
 const body={version:'instagram_mp4_stream_v1' as const,fileSha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,status,reasons};return {...body,proofHash:hash(body)};
}
export function verifyInstagramArchivedStreamProof(proof:InstagramArchivedStreamProof,fileSha256:string):boolean{const {proofHash,...body}=proof;return proof.version==='instagram_mp4_stream_v1'&&['passed','blocked','unknown'].includes(proof.status)&&Array.isArray(proof.reasons)&&proof.fileSha256===fileSha256&&/^[a-f0-9]{64}$/.test(fileSha256)&&proof.bytes>0&&proofHash===hash(body);}
