import type {WeeklyOwnedProductIdentityPorts} from '../runtime/weeklyOwnedProductIdentityDemand.js';
import {assessWeeklyOwnedProductIdentity} from '../runtime/weeklyOwnedProductIdentityDemand.js';
import {readVerifiedNoSharedMaterialDemand,freezeOriginalRunMaterialDemand} from '../runtime/socialWeeklyOriginalRunMaterialDemand.js';
import {assertExecutionPackageGate,executionPackageFrozen} from '../socialPrograms/weeklyExecutionGate.js';
import {assertStoredWeeklyProductionCoverage} from '../runtime/weeklyProductionCoverageAdmission.js';
import {socialContentSourceOptions} from './socialContentSourceOptions.js';
import type {Starter198Repository} from './repository.js';
import type {WeeklyOperatingPackage,WeeklyAgentPlanningState,WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';
import {requireSocialTask} from './socialContentRecords.js';
import {socialJson,socialObject,socialRequestHash,SocialContentWorkflowError} from './socialContentValidation.js';
import {checkWeeklyMaterialClassification,checkWeeklyHumanRequirementBindings} from '../runtime/socialWeeklyMaterialClassificationAdmission.js';
import {createWeeklyRequiredMaterialAdmission} from '../socialPrograms/weeklyRequiredMaterialAdmission.js';
import type {WeeklyMaterialPorts} from '../socialPrograms/weeklyMaterialRequests.js';
function fail(code:string):never{throw new SocialContentWorkflowError(code,409);}
export async function assertWeeklyProductionMaterialAdmission(input:{repository:Starter198Repository;tenantId:string;taskId:string},ports:WeeklyMaterialPorts={},ownedPorts?:WeeklyOwnedProductIdentityPorts):Promise<void>{
 const task=await requireSocialTask(input),authority=socialObject(socialObject(socialJson(task.brief))?._weeklyAuthority);if(!authority&&!String(task.create_idempotency_key??'').startsWith('weekly-production:'))return;
 const store=input.repository.dataStore;if(!store||!authority)fail('weekly_production_start_authority_invalid');
 const frozen=socialObject(authority.weeklyPackage),frozenPub=socialObject(authority.publicationTask);if(!frozen||!frozenPub)fail('weekly_production_start_authority_invalid');
 const rows=await store!.list<any>('social_weekly_operating_packages',{where:{tenant_id:input.tenantId,program_id:String(frozen!.programId),package_id:String(frozen!.packageId),version:Number(frozen!.version)},perPage:2});const pkg=socialJson(rows.items[0]?.payload) as WeeklyOperatingPackage|null;
 if(rows.totalItems!==1||rows.items.length!==1||rows.items[0].tenant_id!==input.tenantId||rows.items[0].program_id!==frozen.programId||rows.items[0].package_id!==frozen.packageId||rows.items[0].version!==frozen.version||!pkg||pkg.programId!==frozen!.programId||pkg.packageId!==frozen!.packageId||pkg.version!==frozen!.version||!['draft','active'].includes(pkg.status))fail('weekly_production_material_scope_changed');
 const pubs=pkg!.socialContentPackage.publicationTasks.filter(pub=>pub.publicationTaskId===frozenPub!.publicationTaskId);if(pubs.length!==1)fail('weekly_production_material_scope_changed');const pub=pubs[0]!;const {status:_actualStatus,...actualPublication}=pub;const {status:_frozenStatus,...frozenPublication}=frozenPub!;if(socialRequestHash(actualPublication)!==socialRequestHash(frozenPublication))fail('weekly_production_material_scope_changed');
 await assertStoredWeeklyProductionCoverage({store:store!,tenantId:input.tenantId,package:pkg!,publicationTaskId:pub.publicationTaskId,frozenPlanning:frozen!.agentPlanning as WeeklyAgentPlanningState});
 const plans=await store!.list<any>('social_weekly_agent_planning',{where:{tenant_id:input.tenantId,program_id:pkg!.programId,package_id:pkg!.packageId,package_version:pkg!.version},sort:'-planning_version',perPage:1});const plan=socialJson(plans.items[0]?.payload) as WeeklyAgentPlanningState|null;
 if(plans.items.length!==1||!plan||plans.items[0].tenant_id!==input.tenantId||plans.items[0].program_id!==pkg.programId||plans.items[0].package_id!==pkg.packageId||plans.items[0].package_version!==pkg.version||plans.items[0].planning_version!==plan.version||plan.packageId!==pkg.packageId||plan.packageVersion!==pkg.version||plan.status!=='dispatched')fail('weekly_production_planning_missing');
 const item=plan?.detailedSchedule?.items.find(item=>item.publicationTaskId===pub.publicationTaskId);if(!item||!plan?.dispatch||!plan.dispatch.scheduleItems.some(item=>item.publicationTaskId===pub.publicationTaskId))fail('weekly_production_planning_missing');
 const analysis=plan!.directorAnalyses.find(analysis=>analysis.analysisId===item!.directorAnalysisRef?.id);const classification=await checkWeeklyMaterialClassification({store:store!,tenantId:input.tenantId,programId:pkg!.programId,packageId:pkg!.packageId,packageVersion:pkg!.version,item:item!,analysis});if(!classification.ready)fail(classification.code);
 if(classification.contract.items.some(item=>item.classification==='unknown'))fail('weekly_material_evidence_configuration_required');
 if(!pub.materialRequirement){if(classification.contract.items.some(item=>item.classification==='human_irreplaceable'))fail('weekly_required_material_contract_missing');
 const owned=await assessWeeklyOwnedProductIdentity(store,{tenantId:input.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:pub.publicationTaskId,contentTaskId:input.taskId},{...ownedPorts,repository:input.repository,materialPorts:ownedPorts?.materialPorts??ports});if(owned.required){if(owned.status!=='ready')fail(owned.gaps[0]??'weekly_owned_product_identity_verification_required');return;}
 const demandScope={tenantId:input.tenantId,taskId:input.taskId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:pub.publicationTaskId,accountId:pub.accountId,factRefs:pub.factRefs};
 let demand=await readVerifiedNoSharedMaterialDemand(store,task,demandScope,{repository:input.repository});
 // Freeze only under the existing caller's package admission gate; standalone queue checks remain read-only.
 if(!demand&&await assertExecutionPackageGate(store,{tenantId:input.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version})){if(await executionPackageFrozen(store,{tenantId:input.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version}))fail('weekly_execution_package_frozen');demand=await freezeOriginalRunMaterialDemand(store,demandScope,{repository:input.repository});}
 if(!demand)fail('weekly_material_contract_required');return;}
 const graph=await store!.list<any>('social_weekly_execution_tasks',{where:{tenant_id:input.tenantId,program_id:pkg!.programId,package_id:pkg!.packageId,package_version:pkg!.version},perPage:500});if(graph.totalItems!==graph.items.length)fail('weekly_material_consumer_identity_invalid');const consumers=graph.items.map(row=>({row,task:socialJson(row.payload) as WeeklyExecutionTask})).filter(value=>value.task?.publicationTaskId===pub.publicationTaskId&&value.task.schedule?.stepKind==='material_readiness');if(consumers.length!==1)fail('weekly_material_consumer_missing');const {row:consumerRow,task:consumer}=consumers[0]!;
 if(consumerRow.tenant_id!==input.tenantId||consumerRow.program_id!==pkg.programId||consumerRow.package_id!==pkg.packageId||consumerRow.package_version!==pkg.version||consumerRow.task_id!==consumer.taskId)fail('weekly_material_consumer_identity_invalid');
 if(consumer.tenantId!==input.tenantId||consumer.programId!==pkg!.programId||consumer.packageId!==pkg!.packageId||consumer.packageVersion!==pkg!.version||consumer.accountId!==pub.accountId||['cancelled','dead_letter'].includes(consumer.status))fail('weekly_material_consumer_identity_invalid');
 const gap=await checkWeeklyHumanRequirementBindings({store:store!,tenantId:input.tenantId,programId:pkg!.programId,packageId:pkg!.packageId,packageVersion:pkg!.version,consumerTaskId:consumer.taskId,publication:pub,contract:classification.contract});if(gap)fail(gap);
 const admission=await createWeeklyRequiredMaterialAdmission(store!,ports)({tenantId:input.tenantId,programId:pkg!.programId,consumerTaskId:consumer.taskId,requirement:pub.materialRequirement});if(admission.status!=='ready'||!admission.materials.length)fail('weekly_required_materials_missing');
 const sources=await input.repository.list('starter_social_task_sources',input.tenantId,{where:{task_id:input.taskId},perPage:500});if(sources.totalItems!==sources.items.length)fail('weekly_material_source_scan_incomplete');
 for(const material of admission.materials){const sourceRef=`socialmaterial:${Buffer.from(`pb-${material.recordId}`).toString('base64url')}`;const option=await (ownedPorts?.sourceOptions??socialContentSourceOptions).resolve({tenantId:input.tenantId,kind:'material',sourceRef});const matching=sources.items.filter(row=>row.status==='active'&&row.source_kind==='material'&&row.source_ref===sourceRef);if(!option||option.kind!=='material'||option.sourceRef!==sourceRef||!option.sourceVersion||matching.length!==1||matching[0].tenant_id!==input.tenantId||matching[0].task_id!==input.taskId||matching[0].source_version!==option.sourceVersion)fail('weekly_material_source_not_bound');}
}
