import { persistSocialProductionWorkspace } from './socialContentProductionWorkspace.js';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import type {Record_} from '../storage/datastore.js';
import type {Starter198Repository,StarterRecord} from './repository.js';
import {STARTER_COLLECTIONS} from './repository.js';
import type {SocialSceneReworkWorkerPorts} from './socialContentSceneReworkWorker.js';
import {reworkFrozenRenderManifest} from './socialContentSceneReworkWorker.js';
import {createSocialSceneReworkService,SOCIAL_SCENE_INTENT_COLLECTION} from './socialContentSceneReworkService.js';
import {socialJson,socialObject,socialRequestHash} from './socialContentValidation.js';
import {sceneReworkHash} from './socialContentSceneRework.js';
import {storeTransientSocialContentFile,registerSocialContentFile,socialContentFileDownloadUrl,type SocialContentBackendFilePort} from './socialContentFiles.js';
import type {SocialContentAccessResolver} from './socialContentAccess.js';
import {createSocialContentArtifact} from './socialContentOutputs.js';
import {parseSocialProductionHandoffRecord,persistSocialProductionHandoff,buildSocialProductionReceipt,persistSocialProductionReceipt,type SocialProductionHandoff} from './socialContentProductionHandoff.js';
import {initialSceneG4Evidence,initialSceneCacheInputFingerprint,initialSceneSourceHashes,persistInitialSocialSceneCache,type InitialSceneQualityReport} from './socialContentInitialSceneCache.js';
import type {SocialProductionResult} from '../../shared/contracts/socialContentWorkflow.js';
import {openSocialArtifactPreviewMedia} from './socialArtifactMedia.js';
function fail(code:string):never{throw Error(code);}
/** Persist only the already rendered, authorized visual replacement. Never executes supply or a production start. */
export function createSocialSceneReworkOutputPort(config:{repository:Starter198Repository;backendFilePort?:SocialContentBackendFilePort;accessResolver?:SocialContentAccessResolver}):SocialSceneReworkWorkerPorts['persistOutput']{
 return async input=>{
  const {repository}=config,store=repository.dataStore;if(!store)return fail('scene_rework_persistent_store_required');const {job,intent}=input;
  async function live(){const actual=await store!.getById<Record_>('content_execution_jobs',job.id),run=await store!.getById<Record_>('workflow_runs',job.runId);const leases=await store!.list<Record_>('durable_operation_leases',{where:{tenant_id:job.tenantId,lease_scope:'content_execution_job',subject_id:job.id},perPage:2}),lease=leases.items[0];if(!actual||actual.tenant_id!==job.tenantId||actual.task_id!==job.taskId||actual.run_id!==job.runId||actual.user_id!==job.userId||actual.task_type!==`social_scene_rework:${intent.operationId}`||actual.status!=='running'||!job.workerId||actual.worker_id!==job.workerId||!run||run.tenant_id!==job.tenantId||run.status!=='running'||leases.totalItems!==1||leases.items.length!==1||!lease||lease.owner_id!==job.workerId||typeof lease.lease_token!=='string'||!lease.lease_token||lease.expires_at!==actual.lease_expires_at||!Number.isFinite(Date.parse(String(lease.expires_at)))||Date.parse(String(lease.expires_at))<=Date.now())return fail('scene_rework_output_lease_invalid');return actual;}
  await live();const context=await createSocialSceneReworkService(repository).readForJob({tenantId:job.tenantId,taskId:job.taskId,runId:job.runId,actorUserId:job.userId,operationId:intent.operationId});if(sceneReworkHash(context.intent)!==sceneReworkHash(intent))return fail('scene_rework_output_intent_mismatch');
  const rows=await store.list<Record_>(SOCIAL_SCENE_INTENT_COLLECTION,{where:{tenant_id:job.tenantId,operation_id:intent.operationId},perPage:2});const checkpoint=socialObject(socialJson(rows.items[0]?.execution));if(rows.totalItems!==1||rows.items.length!==1||!checkpoint)return fail('scene_rework_output_supply_checkpoint_missing');const {hash,...payload}=checkpoint;if(hash!==socialRequestHash(payload)||checkpoint.operationId!==intent.operationId||checkpoint.cacheHash!==context.cache.recordHash||socialRequestHash(checkpoint.supply)!==socialRequestHash(input.supply))return fail('scene_rework_output_supply_checkpoint_mismatch');
  const {outputPersistence:existingObservation,...supplyPayload}=payload;void existingObservation;const supplyCheckpointHash=socialRequestHash(supplyPayload);
  const expected=reworkFrozenRenderManifest(context.cache.renderInput.manifest,intent,input.supply,context.baseline.scenes.map(s=>s.sceneId));if(socialRequestHash(expected)!==socialRequestHash(input.manifest))return fail('scene_rework_output_manifest_drift');const outputBytes=await readFile(input.outputPath);if(createHash('sha256').update(outputBytes).digest('hex')!==input.sha256)return fail('scene_rework_output_bytes_drift');
  const assetHashes=checkpoint.assetHashes;if(!Array.isArray(assetHashes)||assetHashes.length!==input.supply.assets.length)return fail('scene_rework_output_supply_bytes_missing');for(const asset of input.supply.assets){const matched=assetHashes.filter(raw=>socialObject(raw)?.id===asset.id);if(!asset.localPath||matched.length!==1||socialObject(matched[0])?.sha256!==createHash('sha256').update(await readFile(asset.localPath)).digest('hex'))return fail('scene_rework_output_supply_bytes_drift');}
  const parentRows=await repository.list(STARTER_COLLECTIONS.socialContentArtifacts,job.tenantId,{where:{task_id:job.taskId,artifact_id:intent.parentArtifactId},perPage:2});if(parentRows.totalItems!==1||parentRows.items.length!==1)return fail('scene_rework_output_parent_missing');const parentContent=socialObject(socialJson(parentRows.items[0]!.content));if(!parentContent||parentRows.items[0]!.content_hash!==intent.parentArtifactHash)return fail('scene_rework_output_parent_changed');const lineage=Object.fromEntries(['directorPlanReference','scriptBaseline','directorPlan','contentHandoff','outputSpec','adaptedScript','scriptAdaptation','narration'].filter(key=>parentContent[key]!==undefined).map(key=>[key,structuredClone(parentContent[key])]));
  const sourceRows=await repository.list(STARTER_COLLECTIONS.socialProductionHandoffs,job.tenantId,{where:{task_id:job.taskId,handoff_id:context.handoffId,handoff_version:context.handoffVersion},perPage:2});if(sourceRows.totalItems!==1||sourceRows.items.length!==1)return fail('scene_rework_output_source_handoff_missing');const source=parseSocialProductionHandoffRecord(sourceRows.items[0]! as StarterRecord);
  const inputHash=socialRequestHash({operationId:intent.operationId,jobId:job.id,runId:job.runId,outputHash:input.sha256,manifest:input.manifest,supply:input.supply,quality:input.quality});let observation=socialObject(checkpoint.outputPersistence);if(observation){const{recordHash,...observed}=observation;if(recordHash!==socialRequestHash(observed)||observation.inputHash!==inputHash||observation.operationId!==intent.operationId||observation.runId!==job.runId||typeof observation.observedAt!=='string'||!Number.isFinite(Date.parse(observation.observedAt)))return fail('scene_rework_output_observation_drift');}else{const observed={schemaVersion:'scene-rework-output-observation.v1',operationId:intent.operationId,runId:job.runId,inputHash,observedAt:new Date().toISOString()};observation={...observed,recordHash:socialRequestHash(observed)};const updated={...payload,outputPersistence:observation};await live();if(!await store.update(SOCIAL_SCENE_INTENT_COLLECTION,rows.items[0]!.id,{execution:{...updated,hash:socialRequestHash(updated)}}))return fail('scene_rework_output_observation_save_failed');}const now=new Date(String(observation.observedAt));
  const stored=await storeTransientSocialContentFile({filePath:input.outputPath,tenantId:job.tenantId,name:`scene-rework-${intent.operationId}.mp4`,mimeType:'video/mp4'});if(stored.sha256!==input.sha256)return fail('scene_rework_output_bytes_drift');await live();const file=await registerSocialContentFile({repository,tenantId:job.tenantId,userId:job.userId,taskId:job.taskId,usage:'artifact_media',idempotencyKey:`scene-rework-file:${intent.operationId}`,stored,...(stored.storageKind==='backend_file'?{transientPath:input.outputPath}:{}),backendFilePort:config.backendFilePort,now});
  const report:InitialSceneQualityReport={schemaVersion:'initial-scene-quality.v1',visual:input.quality.visual,scenes:input.quality.scenes,audio:{ok:input.quality.audioDecoded,error:input.quality.audioDecoded?null:'真实新成片音轨解码失败'}};
  const failures=[...report.visual.failures,...report.scenes.issues.map(issue=>issue.reason),...(!report.audio.ok?['真实新成片音轨解码失败']:[])];
  const productionResult:SocialProductionResult={productionResultId:`production_result_${socialRequestHash({operationId:intent.operationId,runId:job.runId}).slice(0,24)}`,version:`rework:${intent.operationId}`,executionPlanId:source.executionPlan.executionPlanId,executionPlanVersion:source.executionPlan.version,executionPlanReviewId:source.executionPlanReview.reviewId,artifactId:null,creativeReviewId:`pending_creative_review:${intent.operationId}`,publishAssignmentId:null,status:'asset_review',sceneResults:source.executionPlan.scenes.map(scene=>({sceneId:scene.sceneId,idempotencyKey:scene.idempotencyKey,sourceStrategy:scene.selectedSourceStrategy,feasibility:scene.feasibility,provenanceCandidateIds:scene.recommendedCandidateIds})),technicalReview:{approved:false,checkedScenes:report.scenes.checkedScenes,failures:[...failures,'格式、时长、同步、字幕与敏感信息仍待独立核验']},creativeReview:{approved:false,failedCriteria:['局部重制后需重新进行真实创意审核'],reviewedBy:'director_agent'},artifactResourceRef:file.fileRef,createdAt:now.toISOString()};
  // Reuse the exact old locked director authority, in a separate immutable output envelope.
  const {recordHash:ignored,...original}=source;void ignored;const version=`${source.version}:rework:${intent.operationId}`;
  const handoffPayload={...structuredClone(original),handoffId:`production_handoff_${socialRequestHash({taskId:job.taskId,version,directorBriefId:source.directorBrief.directorBriefId}).slice(0,24)}`,version,createdAt:now.toISOString(),variantDifference:{...structuredClone(source.variantDifference),variantId:productionResult.productionResultId,baselineVariantId:String(intent.parentArtifactId),changedSceneIds:context.cache.scenes.filter(scene=>intent.affectedSceneIds.includes(scene.sceneId)).map(scene=>scene.productionSceneId),dimensions:['visual'] as SocialProductionHandoff['variantDifference']['dimensions'],hypothesis:'仅替换已明确失败的视觉供给，表现与创意结果尚未核验。',surfaceHashes:{...structuredClone(source.variantDifference.surfaceHashes),render:{baseline:intent.parentArtifactHash,current:input.sha256}}}};const handoff:SocialProductionHandoff={...handoffPayload,recordHash:socialRequestHash(handoffPayload)};await persistSocialProductionHandoff(repository,job.tenantId,handoff);
  const initialInput={plan:context.plan,baseline:context.baseline,execution:input.supply.execution,manifest:input.manifest,productionSceneIds:context.cache.scenes.map(s=>s.productionSceneId)};const sourceHashes=await initialSceneSourceHashes({assets:input.supply.assets,execution:input.supply.execution,voicePath:context.cache.renderInput.voice.localPath,bgmUrl:context.cache.renderInput.bgm?.localPath??null});
  await live();const created=await createSocialContentArtifact({repository,tenantId:job.tenantId,userId:job.userId,taskId:job.taskId,idempotencyKey:`scene-rework-artifact:${intent.operationId}`,trustedAgentOrigin:true,backendFilePort:config.backendFilePort,accessResolver:config.accessResolver,now,value:{kind:'short_video',platform:source.directorBrief.platforms[0],language:source.directorBrief.languages[0],origin:'agent',parentArtifactId:intent.parentArtifactId,resourceRef:file.fileRef,content:{...lineage,productionWorkspaceSource:{type:'actual_social_render',creationMode:socialObject(parentContent.productionWorkspaceSource)?.creationMode||'material_processing',runId:job.runId,baselineHash:socialRequestHash(context.baseline),manifestHash:socialRequestHash(input.manifest),outputSha256:input.sha256},workflowSchema:'social-content.scene-rework.v1',mediaStorage:{provider:stored.storageKind==='object'?'object_storage':'pocketbase_file',video:{fileRef:file.fileRef,fileId:file.fileId,sha256:file.sha256,url:socialContentFileDownloadUrl(file.fileId),byteSize:file.size,mimeType:file.mimeType}},productionResult,technicalQualityReport:report,initialSceneCacheInput:initialSceneCacheInputFingerprint(initialInput),initialSceneSourceHashes:sourceHashes,assetSupplyExecution:input.supply.execution,sceneRework:{operationId:intent.operationId,operationHash:socialRequestHash(intent),sourceRunId:intent.sourceRunId,executionRunId:job.runId,parentArtifactId:intent.parentArtifactId,parentArtifactHash:intent.parentArtifactHash,sourceCacheHash:context.cache.recordHash,sourceHandoffRef:{id:source.handoffId,version:source.version,recordHash:source.recordHash},handoffRef:{id:handoff.handoffId,version:handoff.version,recordHash:handoff.recordHash},manifest:input.manifest,manifestHash:socialRequestHash(input.manifest),supplyCheckpointHash},render:{completed:true,qualityPassed:false,audioDecoded:report.audio.ok},review:{state:'requires_user_approval',technicalChecksPassed:false,creativeChecksPassed:false,automatedChecksPassed:false,failures}}}});
  if(created.artifact.status!=='review_required')return fail('scene_rework_output_must_require_review');const qualityReceiptIds:string[]=[];for(const [index,scene] of context.cache.scenes.entries()){const {status,checks}=initialSceneG4Evidence(report,index,context.cache.scenes.length,String((assetHashes.find(raw=>socialObject(raw)?.id===input.supply.execution.shots.find(s=>s.sceneId===scene.sceneId)?.assetId) as Record<string,unknown>|undefined)?.sha256??scene.sha256));const receipt=buildSocialProductionReceipt({handoff,productionResult,gate:'G4',sceneId:scene.productionSceneId,attempt:1,status,artifactRefs:[file.fileRef],evidenceRefs:[`artifact_report:${created.artifact.artifactId}:${socialRequestHash(report)}`],checks,actor:'content_agent',now});await live();await persistSocialProductionReceipt(repository,job.tenantId,receipt);qualityReceiptIds.push(receipt.receiptId);}
  await live();await persistInitialSocialSceneCache({repository,tenantId:job.tenantId,taskId:job.taskId,runId:job.runId,artifactId:created.artifact.artifactId,handoff,plan:context.plan,baseline:context.baseline,execution:input.supply.execution,assets:input.supply.assets,productionSceneIds:initialInput.productionSceneIds,manifest:input.manifest,voicePath:context.cache.renderInput.voice.localPath,bgmUrl:context.cache.renderInput.bgm?.localPath??null,report});
  const media=await openSocialArtifactPreviewMedia({repository,tenantId:job.tenantId,taskId:job.taskId,artifactId:created.artifact.artifactId,backendFilePort:config.backendFilePort});const digest=createHash('sha256');for await(const bytes of media.body)digest.update(bytes);if(digest.digest('hex')!==input.sha256)return fail('scene_rework_output_owned_media_drift');await live();try{await persistSocialProductionWorkspace({repository,tenantId:job.tenantId,userId:job.userId,taskId:job.taskId,runId:job.runId,artifactId:created.artifact.artifactId,baseline:context.baseline,manifest:input.manifest,backendFilePort:config.backendFilePort});}catch{/* Saved output stays real; missing playable workspace is an explicit read-side gap, never an inferred project. */}return {artifactId:created.artifact.artifactId,fileRef:file.fileRef,sha256:input.sha256,parentArtifactId:intent.parentArtifactId,reviewStatus:'review_required',qualityReceiptIds};
 };
}
