import {Router,type RequestHandler,type ErrorRequestHandler} from 'express';
import type {AuthLocals} from '../middleware/auth.js';
import type {createSocialWeeklyG6ReviewService} from './socialWeeklyG6ReviewService.js';
export function createSocialWeeklyG6ReviewRouter(service:ReturnType<typeof createSocialWeeklyG6ReviewService>){const router=Router({mergeParams:true});const string=(v:unknown)=>{if(typeof v!=='string'||!v.trim()||v!==v.trim()||v.length>200)throw Error('scene_g6_input_invalid');return v;};const body=(v:unknown,allowed:string[])=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!allowed.includes(k)))throw Error('scene_g6_input_invalid');return v as Record<string,unknown>;};const targetKeys=['programId','packageId','packageVersion','publicationTaskId'];const target=(b:Record<string,unknown>,query=false)=>{const version=query&&typeof b.packageVersion==='string'?Number(b.packageVersion):b.packageVersion;if(!Number.isSafeInteger(version)||Number(version)<1)throw Error('scene_g6_input_invalid');return {programId:string(b.programId),packageId:string(b.packageId),packageVersion:Number(version),publicationTaskId:string(b.publicationTaskId)};};const scope=(req:Parameters<RequestHandler>[0],res:Parameters<RequestHandler>[1],b:Record<string,unknown>,query=false)=>{const a=res.locals as AuthLocals;if(!a.tenantId||!a.userId)throw Error('scene_g6_auth_required');return {authority:{tenantId:a.tenantId,taskId:string(req.params.taskId),runId:string(req.params.runId),artifactId:string(req.params.artifactId),...target(b,query)},actor:a.userId};};const route=(f:RequestHandler):RequestHandler=>(req,res,next)=>Promise.resolve(f(req,res,next)).catch(next);
 router.get('/',route(async(req,res)=>{const b=body(req.query,targetKeys),a=scope(req,res,b,true);res.json({item:await service.context(a.authority,a.actor)});}));
 router.get('/requests/:requestId',route(async(req,res)=>{const b=body(req.query,targetKeys),a=scope(req,res,b,true);res.json(await service.get(a.authority,a.actor,string(req.params.requestId)));}));
 router.post('/check',route(async(req,res)=>{const b=body(req.body,[...targetKeys,'requestId','expectedContextHash']),a=scope(req,res,b);res.status(201).json(await service.check(a.authority,a.actor,{...target(b),requestId:string(b.requestId),expectedContextHash:string(b.expectedContextHash)}));}));
 router.post('/requests/:requestId/resume',route(async(req,res)=>{const b=body(req.body,targetKeys),a=scope(req,res,b);res.json(await service.resume(a.authority,a.actor,string(req.params.requestId)));}));
 const error:ErrorRequestHandler=(err,_req,res,_next)=>{const code=err instanceof Error&&/^scene_g6_[a-z_]+$/.test(err.message)?err.message:'scene_g6_storage_unavailable';res.status(code==='scene_g6_auth_required'?401:code==='scene_g6_input_invalid'?400:code.includes('forbidden')?403:409).json({error:code});};router.use(error);return router;}
