import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';import{createHash}from'node:crypto';
import{fixture}from'../socialPrograms/weeklyContentTemplates.fixture.js';
import{createStarter198Repository}from'./repository.js';
import{socialRequestHash}from'./socialContentValidation.js';
import{createSocialAssetSupplyPlan}from'../../shared/socialContentAssetSupply.js';
import{alignSocialAssetSupplyPlanToBaseline}from'./socialContentAssetSupplyExecution.js';
import{sealSocialSceneMediaCache,sceneReworkHash}from'./socialContentSceneRework.js';
import{createSocialSceneReworkService,SOCIAL_SCENE_CACHE_COLLECTION,SOCIAL_SCENE_INTENT_COLLECTION}from'./socialContentSceneReworkService.js';
import{sceneReworkHandoff,productionResult,checks}from'./socialContentSceneRework.fixture.js';
import{persistSocialProductionHandoff,buildSocialProductionReceipt,persistSocialProductionReceipt}from'./socialContentProductionHandoff.js';
import type{StoredSocialScriptBaseline}from'./socialContentScriptBaseline.js';
import{prepared}from'./socialContentSceneReworkService.fixture.js';
test('persistent actual artifact/receipts create one intent and durable operation job across reload; unknown provider receipt preserved',async()=>{const f=await prepared();try{await f.service.saveCache(f.context);const input={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact',actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset' as const};const first=await f.service.createIntent(input);const job=f.tables.content_execution_jobs![0]!;job.provider_receipts=[{provider:'real',requestId:'request',state:'unknown',providerTaskId:null,firstRecordedAt:'2026-10-09T00:00:00Z',updatedAt:'2026-10-09T00:00:00Z',metadata:{}}];const service=createSocialSceneReworkService(createStarter198Repository(f.store)),retry=await service.createIntent(input);assert.equal(retry.job.id,first.job.id);assert.equal(retry.job.providerReceipts[0]?.state,'unknown');assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length,1);assert.equal(f.tables[SOCIAL_SCENE_CACHE_COLLECTION]?.length,1);const actual=await service.readForJob({...input,runId:'rework-run',operationId:first.intent.operationId});await actual.verifyReceipt(f.context.cache.scenes[0]!.technicalReceiptId,'scene-hook','passed');await assert.rejects(service.createIntent({...input,changeKind:'voiceover'} as never),/new_director_required/);await assert.rejects(service.readCache({...input,tenantId:'other'}),/cache_missing/);await assert.rejects(service.readForJob({...input,runId:'rework-run',operationId:first.intent.operationId,actorUserId:'other'}),/intent_scope/);}finally{await f.cleanup();}});
test('persisted cache tamper and missing real receipt cannot create or execute retry',async()=>{const f=await prepared();try{await f.service.saveCache(f.context);const scope={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact'};const row=f.tables[SOCIAL_SCENE_CACHE_COLLECTION]![0]!,original=row.content_hash;row.content_hash='forged';await assert.rejects(f.service.readCache(scope),/record_corrupt/);row.content_hash=original;f.tables.starter_social_production_receipts=[];await assert.rejects(f.service.createIntent({...scope,actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset'}),/receipt_missing/);assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length??0,0);}finally{await f.cleanup();}});

test('new actual G4 receipt is a readonly proof overlay and invalidates an older persisted intent',async()=>{const f=await prepared();try{await f.service.saveCache(f.context);const scope={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact'},input={...scope,actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset' as const};const old=await f.service.createIntent(input),mediaRow=f.tables[SOCIAL_SCENE_CACHE_COLLECTION]![0]!,originalHash=mediaRow.content_hash;const receipt=buildSocialProductionReceipt({handoff:f.handoff,productionResult:f.result,gate:'G4',sceneId:'scene-cta',attempt:2,status:'failed',actor:'content_agent',artifactRefs:[f.result.artifactResourceRef],evidenceRefs:['actual-second-inspection'],checks:checks('G4').map(c=>({...c,passed:c.code!=='render'}))});await persistSocialProductionReceipt(createStarter198Repository(f.store),'t',receipt);const refreshed=await f.service.readCache(scope);assert.equal(refreshed.cache.scenes[1]!.technicalReceiptId,receipt.receiptId);assert.equal(mediaRow.content_hash,originalHash);await assert.rejects(f.service.readForJob({...scope,runId:'rework-run',actorUserId:'owner',operationId:old.intent.operationId}),/intent_stale/);}finally{await f.cleanup();}});

test('actual pending G4 persists cache but cannot be reused as a passed scene',async()=>{const f=await prepared();try{const pending=buildSocialProductionReceipt({handoff:f.handoff,productionResult:f.result,gate:'G4',sceneId:'scene-hook',attempt:2,status:'review_required',actor:'content_agent',artifactRefs:[f.result.artifactResourceRef],evidenceRefs:['actual-detection-insufficient'],checks:checks('G4').map(c=>({...c,passed:c.code!=='sensitive_data'}))});await persistSocialProductionReceipt(createStarter198Repository(f.store),'t',pending);const cache=sealSocialSceneMediaCache({...f.context.cache,scenes:f.context.cache.scenes.map(s=>s.sceneId==='scene-hook'?{...s,technicalReceiptId:pending.receiptId,status:'review_required'}:s)});const{recordHash,...payload}=cache;const actual=sealSocialSceneMediaCache(payload);await f.service.saveCache({...f.context,cache:actual});const scope={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact'};assert.equal((await f.service.readCache(scope)).cache.scenes[0]!.status,'review_required');await assert.rejects(f.service.createIntent({...scope,actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset'}),/unselected_review_required/);assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length??0,0);}finally{await f.cleanup();}});

test('same ended source run, missing run authorization and foreign execution run cannot admit paid retry',async()=>{const f=await prepared();try{await f.service.saveCache(f.context);const input={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact',actorUserId:'owner',executionRunId:'run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset' as const};await assert.rejects(f.service.createIntent(input),/independent_run_required/);await assert.rejects(f.service.createIntent({...input,executionRunId:'missing'}),/execution_authorization_required/);const newrun=f.tables.workflow_runs!.find(r=>r.id==='rework-run')!;newrun.tenant_id='foreign';await assert.rejects(f.service.createIntent({...input,executionRunId:'rework-run'}),/execution_authorization_required/);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length??0,0);}finally{await f.cleanup();}});
test('first durable job write failure retains the explicit intent and retry repairs the same operation',async()=>{const f=await prepared();try{await f.service.saveCache(f.context);const original=f.store.create;let first=true;f.store.create=async(c,value)=>{if(c==='content_execution_jobs'&&first){first=false;throw Error('actual job write failure');}return original(c,value);};const input={tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact',actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset' as const};await assert.rejects(f.service.createIntent(input),/job write failure/);assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length,1);assert.equal(f.tables.content_execution_jobs?.length??0,0);const restored=await f.service.createIntent(input);assert.equal(restored.intent.executionRunId,'rework-run');assert.equal(f.tables[SOCIAL_SCENE_INTENT_COLLECTION]?.length,1);assert.equal(f.tables.content_execution_jobs?.length,1);}finally{await f.cleanup();}});
