import test from 'node:test';
import type {Record_,ListQuery} from '../storage/datastore.js';
import assert from 'node:assert/strict';
import {outputFixture} from './socialContentSceneReworkCompletionRecovery.fixture.js';
import {createStarter198Repository} from './repository.js';
import {DurableContentExecutionWorker} from '../contentExecution/durableQueue.js';
import {completeSocialSceneReworkRun} from './socialContentSceneReworkExecution.js';
import {socialRequestHash} from './socialContentValidation.js';
import {recoverSocialSceneReworkCompletions} from './socialContentSceneReworkCompletionRecovery.js';
import {currentDataAuthority} from '../storage/dataAuthority.js';
async function succeededWithUnwrittenRun(){
 const x=await outputFixture();const repository=createStarter198Repository(x.f.store);let executions=0;const originalSource=structuredClone(x.f.tables.workflow_runs!.find(r=>r.id==='run'));
 Object.assign(x.f.tables.content_execution_jobs![0]!,{status:'queued',worker_id:'',lease_expires_at:''});x.f.tables.durable_operation_leases=x.f.tables.durable_operation_leases!.filter(r=>r.id!=='live');
 const update=x.f.store.update.bind(x.f.store);let fail=true;x.f.store.update=async(collection,id,data)=>{if(fail&&collection==='workflow_runs'&&id==='rework-run'&&data.status==='completed'){fail=false;throw Error('fixture_write_failure');}return update(collection,id,data);};
 let resolve!:()=>void;const settled=new Promise<void>(r=>resolve=r);
 const worker=new DurableContentExecutionWorker({dataStore:x.f.store,dataAuthority:'local',execute:async job=>{executions++;const output=await x.port({...x.input,job});const run=await x.f.store.getById('workflow_runs',job.runId);const receipt={operationId:x.input.intent.operationId,jobId:job.id,executionRunId:job.runId,...output};await x.f.store.update('workflow_runs',job.runId,{starter_context:{...(run!.starter_context as object),sceneReworkOutput:{...receipt,recordHash:socialRequestHash(receipt)}}});},onSucceeded:async job=>{try{await completeSocialSceneReworkRun(repository,job);}finally{resolve();}}});
 await worker.drain();await Promise.race([settled,new Promise((_,reject)=>{const t=setTimeout(()=>reject(Error('worker_timeout')),10000);t.unref();})]);worker.stop();assert.equal(x.f.tables.content_execution_jobs![0]!.status,'succeeded');assert.equal(x.f.tables.workflow_runs!.find(r=>r.id==='rework-run')!.status,'running');
 return {...x,repository,originalSource,getExecutions:()=>executions};
}
test('real succeeded worker output recovers failed run projection without producing again; repeat is idempotent and stays local',async()=>{const x=await succeededWithUnwrittenRun();try{const list=x.f.store.list.bind(x.f.store);x.f.store.list=async<T=Record_>(c:string,q?:ListQuery)=>{assert.equal(currentDataAuthority(),'local');return list<T>(c,q);};const report=await recoverSocialSceneReworkCompletions({repository:x.repository,dataAuthority:'local'});assert.equal(report.recovered,1);assert.equal(report.failed,0);const completed=x.f.tables.workflow_runs!.find(r=>r.id==='rework-run')!;assert.equal(completed.status,'completed');const time=completed.completed_at;const again=await recoverSocialSceneReworkCompletions({repository:x.repository,dataAuthority:'local'});assert.equal(again.recovered,0);assert.equal(completed.completed_at,time);assert.equal(x.getExecutions(),1);assert.deepEqual(x.f.tables.workflow_runs!.find(r=>r.id==='run'),x.originalSource);}finally{await x.f.cleanup();}});
test('bounded cursor scans skip ordinary jobs, isolate invalid succeeded evidence and still recover actual output',async()=>{const x=await succeededWithUnwrittenRun();try{x.f.tables.content_execution_jobs!.push({id:'000',status:'succeeded',task_type:'ordinary'},{id:'001',status:'succeeded',task_type:x.input.job.taskType,tenant_id:'foreign',task_id:'bad',run_id:'bad'} as any);const first=await recoverSocialSceneReworkCompletions({repository:x.repository,pageSize:1,maxRows:1});assert.equal(first.scanned,1);assert.equal(first.skipped,1);assert.ok(first.nextCursor);const rest=await recoverSocialSceneReworkCompletions({repository:x.repository,pageSize:1,maxRows:10,maxPages:10,cursor:first.nextCursor!});assert.equal(rest.failed,1);assert.equal(rest.recovered,1);assert.equal(rest.nextCursor,null);assert.equal(x.getExecutions(),1);}finally{await x.f.cleanup();}});
test('empty datastore page with zero totalPages is a successful empty scan',async()=>{const x=await outputFixture();try{x.f.tables.content_execution_jobs=[];const list=x.f.store.list.bind(x.f.store);x.f.store.list=async<T=Record_>(c:string,q?:ListQuery)=>{const page=await list<T>(c,q);return c==='content_execution_jobs'?{...page,totalPages:0}:page;};const report=await recoverSocialSceneReworkCompletions({repository:createStarter198Repository(x.f.store)});assert.equal(report.scanned,0);assert.equal(report.nextCursor,null);}finally{await x.f.cleanup();}});
test('actual succeeded output receipt drift blocks completion and sanitizes unexpected errors',async()=>{const x=await succeededWithUnwrittenRun();try{const run=x.f.tables.workflow_runs!.find(r=>r.id==='rework-run')!;((run.starter_context as any).sceneReworkOutput).recordHash='bad';const r=await recoverSocialSceneReworkCompletions({repository:x.repository});assert.equal(r.recovered,0);assert.equal(r.failed,1);assert.equal(run.status,'running');assert.match(r.errors[0]!.code,/^scene_rework_[a-z0-9_]+$/);assert.equal(x.getExecutions(),1);}finally{await x.f.cleanup();}});
test('archived succeeded rows invalidate prior page/offset safely and reset cursor, while truncated full pages reject',async()=>{const x=await outputFixture();try{x.f.tables.content_execution_jobs=[];const repository=createStarter198Repository(x.f.store);for(const cursor of [{page:3,offset:0},{page:1,offset:1}]){const r=await recoverSocialSceneReworkCompletions({repository,pageSize:2,cursor});assert.equal(r.nextCursor,null);assert.equal(r.scanned,0);}const list=x.f.store.list.bind(x.f.store);x.f.store.list=async<T=Record_>(c:string,q?:ListQuery)=>{const r=await list<T>(c,q);return c==='content_execution_jobs'?{...r,totalPages:2,totalItems:4}:r;};await assert.rejects(recoverSocialSceneReworkCompletions({repository,pageSize:2}),/page_incomplete/);}finally{await x.f.cleanup();}});
