import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import {prepared,authorizeSceneFixture} from './socialContentSceneReworkService.fixture.js';
import {createStarter198Repository} from './repository.js';
import {sealSocialSceneMediaCache,executeSocialSceneReworkSupply} from './socialContentSceneRework.js';
import {socialRequestHash} from './socialContentValidation.js';
import {reworkFrozenRenderManifest} from './socialContentSceneReworkWorker.js';
import {resolveSceneCacheSourceRun} from './socialContentSceneCacheSource.js';
import {createSocialSceneReworkOutputPort} from './socialContentSceneReworkOutput.js';
import {runVisualFfmpeg} from '../lib/renderVisualQuality.js';
import type {SocialContentBackendFilePort} from './socialContentFiles.js';
async function outputFixture(){const f=await prepared();
 const manifest={jobId:'old',spec:{duration:6},voiceover:{url:f.local},subtitles:{cues:[{start:0,end:3},{start:3,end:6}]},timeline:f.context.baseline.scenes.map((s,index)=>({sceneId:s.sceneId,type:'video',url:f.local,trimStart:0,trimEnd:3,speed:1,targetStart:index*3,targetEnd:(index+1)*3}))};
 const artifact=f.tables.starter_social_content_artifacts![0]!,content=artifact.content as Record<string,unknown>,frozen=content.initialSceneCacheInput as Record<string,unknown>;frozen.manifestHash=socialRequestHash(manifest);artifact.content_hash=socialRequestHash({resourceRef:artifact.resource_ref,content});const{recordHash,...original}=f.context.cache;void recordHash;f.context.cache=sealSocialSceneMediaCache({...original,parentArtifactHash:String(artifact.content_hash),renderInput:{...original.renderInput,manifest,sourceManifest:manifest}});authorizeSceneFixture(f,f.context);await f.service.saveCache(f.context);
 const{job,intent}=await f.service.createIntent({tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact',actorUserId:'owner',executionRunId:'rework-run',affectedSceneIds:['scene-cta'],changeKind:'visual_asset'});const expires=new Date(Date.now()+60000).toISOString();Object.assign(job,{status:'running',workerId:'actual-worker',leaseExpiresAt:expires});Object.assign(f.tables.content_execution_jobs![0]!,{status:'running',worker_id:'actual-worker',lease_expires_at:expires});f.tables.durable_operation_leases=[...(f.tables.durable_operation_leases??[]),{id:'live',tenant_id:'t',lease_scope:'content_execution_job',subject_id:job.id,owner_id:'actual-worker',lease_token:'actual-token',expires_at:expires}];
 const context=await f.service.readForJob({tenantId:'t',taskId:'content',runId:'rework-run',actorUserId:'owner',operationId:intent.operationId});const supply=await executeSocialSceneReworkSupply({...context,actorUserId:'owner',parentArtifactHash:context.cache.parentArtifactHash,outputDirectory:f.local+'.supply',adapters:[{adapterId:'test-real-output-adapter',sourceStrategies:['customer_real_asset'],execute:async()=>({...f.context.cache.scenes[1]!.result,asset:{...f.context.cache.scenes[1]!.result.asset,id:'replacement'}})}]});const assetHashes=await Promise.all(supply.assets.map(async asset=>({id:asset.id,sha256:createHash('sha256').update(await readFile(asset.localPath!)).digest('hex')})));const payload={operationId:intent.operationId,cacheHash:f.context.cache.recordHash,supply,assetHashes};f.tables.starter_social_scene_rework_intents![0]!.execution={...payload,hash:socialRequestHash(payload)};
 const outputs=new Map<string,Buffer>();const backendFilePort:SocialContentBackendFilePort={attach:async a=>{outputs.set(a.recordId,await readFile(a.path));return a.name;},fetch:async a=>{const buf=outputs.get(a.recordId);return buf?{buf,contentType:'video/mp4'}:null;}};
 const outputPath=f.local+'.new.mp4';const rendered=await runVisualFfmpeg(['-y','-f','lavfi','-i','color=c=blue:s=128x128:d=1','-c:v','libx264','-pix_fmt','yuv420p',outputPath]);assert.equal(rendered.ok,true,rendered.stderr);const sha256=createHash('sha256').update(await readFile(outputPath)).digest('hex');const input={job,intent,outputPath,sha256,manifest:reworkFrozenRenderManifest(manifest,intent,supply,f.context.baseline.scenes.map(s=>s.sceneId)),supply,quality:{visual:{passed:true,failures:[],metrics:{sampleCount:2,contentFrameCount:2,nonBackgroundFrameRatio:1,meanBrightness:100,meanLumaDeviation:20,meanEdgeRatio:1,meanFrameDifference:1,maxFrameDifference:1,motionDetected:true,estimatedDistinctFrames:2,nearDuplicateFrameRatio:0,sharpFrameRatio:1},evidenceFrames:[]},scenes:{passed:true,issues:[],checkedScenes:2},audioDecoded:true}};
 const port=createSocialSceneReworkOutputPort({repository:createStarter198Repository(f.store),backendFilePort,accessResolver:{resolve:async()=>({kind:'subscription',subscription:{status:'active',plan:'customer',expiresAt:null}})}});delete (f.tables.starter_social_content_tasks![0]!.brief as Record<string,unknown>)._weeklyAuthority;Object.assign(f.tables.starter_social_content_tasks![0]!.brief as Record<string,unknown>,{programRef:{objectType:'social_program',id:'p',version:'1'},title:'已锁定企业产品视频',objective:'按已审核场景替换失败视觉',markets:[],languages:['zh'],platforms:['tiktok'],formats:['video'],restrictions:[],requestedOutputCount:1});Object.assign(f.tables.starter_social_content_tasks![0]!,{status:'producing',source_count:0,knowledge_source_count:0,material_source_count:0,artifact_count:1,approved_artifact_count:1,delivery_package_count:0,publication_count:0,metric_submission_count:0,package_selection:['industry_launch','content_rocket','task_express'].map(kind=>({kind,packageKey:kind,version:'1',name:kind})),version:'1',created_at:'2026-10-01T00:00:00.000Z',updated_at:'2026-10-01T00:00:00.000Z'});return {f,input,port,outputs};
}
test('authorized new run persists owned output with separate handoff/G4, pending reviews and stable operation replay',async()=>{const x=await outputFixture();try{const before=x.f.tables.starter_social_content_artifacts!.length,oldReceipts=x.f.tables.starter_social_production_receipts!.map(r=>String(r.receipt_id));const result=await x.port(x.input);assert.equal(result.reviewStatus,'review_required');assert.equal(result.parentArtifactId,'artifact');assert.equal(result.sha256,x.input.sha256);const again=await x.port(x.input);assert.deepEqual(again,result);assert.equal(x.f.tables.starter_social_content_artifacts!.length,before+1);const row=x.f.tables.starter_social_content_artifacts!.find(r=>r.artifact_id===result.artifactId)!;const content=row.content as any;assert.equal(content.sceneRework.executionRunId,'rework-run');assert.equal(content.sceneRework.sourceRunId,'run');assert.equal(content.productionResult.version,'1');assert.notEqual(content.productionResult.productionResultId,(x.f.tables.starter_social_content_artifacts![0]!.content as any).productionResult.productionResultId);assert.equal(content.sceneRework.operationId,x.input.intent.operationId);assert.equal(content.productionResult.technicalReview.approved,false);assert.equal(content.productionResult.creativeReview.approved,false);assert.notEqual(content.sceneRework.handoffRef.id,x.f.handoff.handoffId);for(const id of result.qualityReceiptIds){const receipt=x.f.tables.starter_social_production_receipts!.find(r=>r.receipt_id===id)!.payload as any;assert.equal(receipt.status,'review_required');assert.equal(receipt.handoffId,content.sceneRework.handoffRef.id);assert.equal(receipt.productionResultRef.id,content.productionResult.productionResultId);}assert.ok(oldReceipts.every(id=>x.f.tables.starter_social_production_receipts!.some(r=>r.receipt_id===id)));await x.f.service.readCache({tenantId:'t',taskId:'content',runId:'run',parentArtifactId:'artifact'});const repository=createStarter198Repository(x.f.store);assert.equal(await resolveSceneCacheSourceRun(repository,{tenantId:'t',taskId:'content',parentArtifactId:result.artifactId}),'rework-run');assert.equal(x.f.tables.starter_social_content_tasks![0]!.run_id,'run');const newCache=await x.f.service.readCache({tenantId:'t',taskId:'content',runId:'rework-run',parentArtifactId:result.artifactId});assert.ok(newCache.cache.scenes.every(scene=>scene.status==='review_required'));assert.equal(newCache.handoffId,content.sceneRework.handoffRef.id);x.f.tables.workflow_runs!.find(row=>row.id==='rework-run')!.status='succeeded';await x.f.service.readCache({tenantId:'t',taskId:'content',runId:'rework-run',parentArtifactId:result.artifactId});}finally{await x.f.cleanup();}});
test('manifest narration drift and output byte drift cannot persist a new artifact',async()=>{const x=await outputFixture();try{const before=x.f.tables.starter_social_content_artifacts!.length;await assert.rejects(x.port({...x.input,manifest:{...x.input.manifest,voiceover:{url:'other-voice.wav'}}}),/manifest_drift/);await assert.rejects(x.port({...x.input,sha256:'f'.repeat(64)}),/bytes_drift/);assert.equal(x.f.tables.starter_social_content_artifacts!.length,before);}finally{await x.f.cleanup();}});
test('expired lease prevents owned-file or artifact writes',async()=>{const x=await outputFixture();try{x.f.tables.durable_operation_leases!.find(r=>r.id==='live')!.expires_at='2020-01-01T00:00:00Z';await assert.rejects(x.port(x.input),/output_lease_invalid/);assert.equal(x.outputs.size,0);}finally{await x.f.cleanup();}});
test('receipt persistence interruption resumes same owned file/artifact and observed output time',async()=>{const x=await outputFixture();try{const create=x.f.store.create.bind(x.f.store);let interrupted=false;x.f.store.create=async(...args:Parameters<typeof create>)=>{if(args[0]==='starter_social_production_receipts'&&!interrupted){interrupted=true;throw Error('transient-receipt-write');}return create(...args);};await assert.rejects(x.port(x.input),/starter_198_storage_unavailable/);const artifacts=x.f.tables.starter_social_content_artifacts!.length,files=x.f.tables.starter_social_content_files!.length;const checkpoint=x.f.tables.starter_social_scene_rework_intents![0]!.execution as any;const observedAt=checkpoint.outputPersistence.observedAt;const recovered=await x.port(x.input);assert.equal(x.f.tables.starter_social_content_artifacts!.length,artifacts);assert.equal(x.f.tables.starter_social_content_files!.length,files);const output=x.f.tables.starter_social_content_artifacts!.find(r=>r.artifact_id===recovered.artifactId)!;assert.equal(output.created_at,observedAt);assert.notEqual(output.created_at,x.input.job.createdAt);assert.equal(recovered.qualityReceiptIds.length,2);}finally{await x.f.cleanup();}});
test('another execution run or changed provider supply cannot borrow a rendered-output intent',async()=>{const x=await outputFixture();try{await assert.rejects(x.port({...x.input,job:{...x.input.job,runId:'run'}}),/output_lease_invalid/);const supply=structuredClone(x.input.supply);supply.execution.shots[0]!.providerId='forged-provider';await assert.rejects(x.port({...x.input,supply}),/supply_checkpoint_mismatch/);assert.equal(x.outputs.size,0);}finally{await x.f.cleanup();}});

test('new output source-run resolution rejects forged operation or foreign execution run even with recomputed artifact content hash',async()=>{const x=await outputFixture();try{const result=await x.port(x.input),row=x.f.tables.starter_social_content_artifacts!.find(r=>r.artifact_id===result.artifactId)!;const content=row.content as any;const original=content.sceneRework.operationHash;content.sceneRework.operationHash='f'.repeat(64);row.content_hash=socialRequestHash({resourceRef:row.resource_ref,content});await assert.rejects(resolveSceneCacheSourceRun(createStarter198Repository(x.f.store),{tenantId:'t',taskId:'content',parentArtifactId:result.artifactId}),/source_intent_invalid/);content.sceneRework.operationHash=original;content.sceneRework.executionRunId='foreign-run';row.content_hash=socialRequestHash({resourceRef:row.resource_ref,content});await assert.rejects(resolveSceneCacheSourceRun(createStarter198Repository(x.f.store),{tenantId:'t',taskId:'content',parentArtifactId:result.artifactId}));}finally{await x.f.cleanup();}});
