import {Router,type Request,type Response} from 'express';
import type {Starter198Repository} from './repository.js';
import {readSocialSceneReworkStatus} from './socialContentSceneReworkRead.js';
import {createSocialSceneReworkCostPolicyService} from './socialContentSceneReworkCostPolicy.js';
import {socialObject} from './socialContentValidation.js';
/** Mount at /:operationId/cost-policy beneath the authenticated scene-rework router. Never starts or resumes work. */
export function createSocialSceneReworkCostPolicyRouter(input:{repository:Starter198Repository;authorize:(req:Request,res:Response,level:'read'|'start')=>Promise<{tenantId:string;userId:string}>;env?:NodeJS.ProcessEnv}) {
 const router=Router({mergeParams:true}),service=createSocialSceneReworkCostPolicyService(input.repository,input.env);
 const safe=(fn:(req:Request,res:Response)=>Promise<void>)=>(req:Request,res:Response)=>{void fn(req,res).catch(error=>{const code=error instanceof Error?error.message:'';const status=typeof error==='object'&&error!==null&&'status'in error?error.status:undefined;res.status(typeof status==='number'&&[400,401,403,404,409,503].includes(status)?status:409).json({error:/^(scene_rework_|starter_198_|social_content_)[a-z_]+$/.test(code)?code:'scene_rework_cost_unavailable'});});};
 async function scope(req:Request,res:Response,level:'read'|'start'){const actor=await input.authorize(req,res,level);if(Object.keys(req.query).length)throw new Error('scene_rework_cost_query_invalid');const status=await readSocialSceneReworkStatus({repository:input.repository,tenantId:actor.tenantId,actorUserId:actor.userId,taskId:req.params.taskId,operationId:req.params.operationId});return{scope:{tenantId:actor.tenantId,actorUserId:actor.userId,taskId:status.taskId,operationId:status.operationId,runId:status.executionRunId},status};}
 router.get('/',safe(async(req,res)=>{const actual=await scope(req,res,'read');res.json({item:actual.status.runStatus==='running'?await service.read(actual.scope):{quote:null,gaps:['scene_rework_cost_quote_requires_active_run'],policy:await service.readConfirmedRecord(actual.scope)},jobStatus:actual.status.jobStatus,runStatus:actual.status.runStatus,automaticallyResumed:false});}));
 router.post('/confirm',safe(async(req,res)=>{const actual=await scope(req,res,'start'),body=socialObject(req.body);if(!body||Object.keys(body).some(key=>!['expectedQuoteHash','authorizedMaximumCostCny'].includes(key))||typeof body.expectedQuoteHash!=='string'||!/^[a-f0-9]{64}$/.test(body.expectedQuoteHash)||typeof body.authorizedMaximumCostCny!=='number'||!Number.isFinite(body.authorizedMaximumCostCny))throw new Error('scene_rework_cost_confirmation_invalid');if(actual.status.runStatus!=='running'||!['queued','retry_wait','reconciling','blocked','running'].includes(actual.status.jobStatus))throw new Error('scene_rework_cost_confirmation_status_invalid');res.json({item:await service.confirm(actual.scope,{expectedQuoteHash:body.expectedQuoteHash,authorizedMaximumCostCny:body.authorizedMaximumCostCny}),automaticallyResumed:false});}));
 return router;
}
