import {createHash} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import type {Starter198Repository} from './repository.js';
import {STARTER_COLLECTIONS} from './repository.js';
import type {SocialAssetSupplyPlan,SocialProductionResult} from '../../shared/contracts/socialContentWorkflow.js';
import type {StoredSocialScriptBaseline} from './socialContentScriptBaseline.js';
import type {SocialProductionAsset} from './socialContentProductionPlan.js';
import type {SocialAssetSupplyExecution,SocialAssetSupplyAdapterResult} from './socialContentAssetSupplyExecution.js';
import {alignSocialAssetSupplyPlanToBaseline} from './socialContentAssetSupplyExecution.js';
import {buildSocialProductionReceipt,persistSocialProductionHandoff,persistSocialProductionReceipt,type SocialProductionHandoff} from './socialContentProductionHandoff.js';
import {sealSocialSceneMediaCache,sceneReworkHash,type SocialSceneMediaCache} from './socialContentSceneRework.js';
import {createSocialSceneReworkService} from './socialContentSceneReworkService.js';
import {socialJson,socialObject,socialRequestHash} from './socialContentValidation.js';
import type {RenderVisualQualityResult} from '../lib/renderVisualQuality.js';
export interface InitialSceneQualityReport {schemaVersion:'initial-scene-quality.v1';visual:RenderVisualQualityResult;scenes:{passed:boolean;issues:Array<{sceneIndex:number;start:number;end:number;code:string;reason:string}>;checkedScenes:number};audio:{ok:boolean;error:string|null};}
async function sourceBytes(source:string){return /^data:[^;]+;base64,/.test(source)?Buffer.from(source.slice(source.indexOf(',')+1),'base64'):readFile(source);}
export async function initialSceneSourceHashes(input:{assets:SocialProductionAsset[];execution:SocialAssetSupplyExecution;voicePath:string;bgmUrl:string|null}){const sources:Array<{role:string;id:string;source:string}>=[{role:'voice',id:'voice',source:input.voicePath},...(input.bgmUrl?[{role:'bgm',id:'bgm',source:input.bgmUrl}]:[])];for(const assetId of new Set(input.execution.shots.map(s=>s.assetId))){const asset=input.assets.filter(a=>a.id===assetId);if(asset.length!==1||!asset[0]!.localPath)throw Error('scene_cache_original_supply_bytes_required');sources.push({role:'asset',id:assetId,source:asset[0]!.localPath!});}return Promise.all(sources.map(async source=>{const bytes=await sourceBytes(source.source);if(!bytes.length)throw Error('scene_cache_media_empty');return {...source,sha256:createHash('sha256').update(bytes).digest('hex')};}));}
export async function copyInitialSceneMedia(input:{root:string;source:string;extension:string}):Promise<{localPath:string;sha256:string}>{const data=await sourceBytes(input.source);if(!data.length)throw Error('scene_cache_media_empty');const sha256=createHash('sha256').update(data).digest('hex');await mkdir(input.root,{recursive:true});const localPath=path.join(input.root,`${sha256}.${input.extension.replace(/[^a-z0-9]/gi,'')||'bin'}`);await writeFile(localPath,data);return {localPath,sha256};}
export function initialSceneCacheInputFingerprint(input:{plan:SocialAssetSupplyPlan;baseline:StoredSocialScriptBaseline;execution:SocialAssetSupplyExecution;manifest:Record<string,unknown>;productionSceneIds:string[]}){return {schemaVersion:'initial-scene-cache-input.v1',planHash:sceneReworkHash(alignSocialAssetSupplyPlanToBaseline({plan:input.plan,baseline:input.baseline})),baselineHash:sceneReworkHash(input.baseline),executionHash:sceneReworkHash(input.execution),manifestHash:sceneReworkHash(input.manifest),productionSceneIds:input.productionSceneIds};}
export function initialSceneG4Evidence(report:InitialSceneQualityReport,index:number,sceneCount:number,linkedHash:string){const issues=report.scenes.issues.filter(issue=>issue.sceneIndex===index),actualFailure=issues.length>0||!report.visual.passed||!report.audio.ok;const status=actualFailure?'failed' as const:'review_required' as const;const checks=[{code:'format',passed:false,message:'未执行独立容器及平台格式检测，保留待核验。'},{code:'duration',passed:false,message:'未测量最终成片逐镜实际时长，不能以计划时长代替。'},{code:'audio_visual_sync',passed:false,message:report.audio.ok?'实际音轨可解码；尚无逐镜同步检测证据。':report.audio.error||'实际音轨解码失败。'},{code:'caption',passed:false,message:'字幕已交给合成器；尚无烧录字幕检测凭据。'},{code:'linked_assets',passed:true,message:`实际供给素材已读取并封存字节SHA256:${linkedHash}`},{code:'render',passed:!issues.length&&report.scenes.checkedScenes===sceneCount&&report.visual.passed,message:issues.length?issues.map(issue=>issue.reason).join('；'):'已执行实际逐镜抽帧检测；原完整报告随产物保存。'},{code:'sensitive_data',passed:false,message:'尚无画面敏感数据检测或指定人工核验凭据。'}];return {status,checks};}
/** First-run media only; no extraction of scene supply from the final MP4. */
export async function persistInitialSocialSceneCache(input:{repository:Starter198Repository;tenantId:string;taskId:string;runId:string;artifactId:string;handoff:SocialProductionHandoff;plan:SocialAssetSupplyPlan;baseline:StoredSocialScriptBaseline;execution:SocialAssetSupplyExecution;assets:SocialProductionAsset[];productionSceneIds:string[];manifest:Record<string,unknown>;voicePath:string;bgmUrl:string|null;report:InitialSceneQualityReport}){
 const rows=await input.repository.list(STARTER_COLLECTIONS.socialContentArtifacts,input.tenantId,{where:{task_id:input.taskId,artifact_id:input.artifactId},perPage:2});if(rows.totalItems!==1||!rows.items[0])throw Error('scene_cache_original_artifact_missing');const artifact=rows.items[0],content=socialObject(socialJson(artifact.content)),result=content?.productionResult as unknown as SocialProductionResult;if(!content||!result||socialRequestHash(content.technicalQualityReport)!==socialRequestHash(input.report))throw Error('scene_cache_original_report_mismatch');
 if(socialRequestHash(content.initialSceneCacheInput)!==socialRequestHash(initialSceneCacheInputFingerprint(input))||socialRequestHash(content.assetSupplyExecution)!==socialRequestHash(input.execution))throw Error('scene_cache_original_inputs_mismatch');
 if(socialRequestHash(content.initialSceneSourceHashes)!==socialRequestHash(await initialSceneSourceHashes(input)))throw Error('scene_cache_original_source_bytes_mismatch');
 const plan=alignSocialAssetSupplyPlanToBaseline({plan:input.plan,baseline:input.baseline});if(plan.shots.length!==input.execution.shots.length||input.productionSceneIds.length!==plan.shots.length)throw Error('scene_cache_original_supply_incomplete');
 const root=path.resolve('data/social-content-scene-cache',sceneReworkHash([input.tenantId,input.taskId,input.runId,input.artifactId]));const remap=new Map<string,string>();const voice=await copyInitialSceneMedia({root,source:input.voicePath,extension:'wav'});remap.set(input.voicePath,voice.localPath);const bgm=input.bgmUrl?await copyInitialSceneMedia({root,source:input.bgmUrl,extension:'mp3'}):null;if(bgm)remap.set(input.bgmUrl!,bgm.localPath);
 await persistSocialProductionHandoff(input.repository,input.tenantId,input.handoff);const scenes:SocialSceneMediaCache['scenes']=[];
 for(const [index,shot] of plan.shots.entries()){const sceneId=input.baseline.scenes[index]!.sceneId,executions=input.execution.shots.filter(entry=>entry.sceneId===sceneId);if(executions.length!==1)throw Error('scene_cache_original_supply_identity');const executed=executions[0]!,assets=input.assets.filter(asset=>asset.id===executed.assetId);if(assets.length!==1||!assets[0]!.localPath)throw Error('scene_cache_original_supply_bytes_required');const asset=assets[0]!,copied=await copyInitialSceneMedia({root,source:asset.localPath!,extension:path.extname(asset.localPath!).slice(1)||'bin'});remap.set(asset.localPath!,copied.localPath);remap.set(asset.url,copied.localPath);const supplied:SocialAssetSupplyAdapterResult={asset:{...structuredClone(asset),localPath:copied.localPath,url:copied.localPath,contentHash:copied.sha256},sourceStrategy:executed.sourceStrategy,providerId:executed.providerId,sourceRef:executed.sourceRef,...structuredClone(executed.provenance)};
  const {status,checks}=initialSceneG4Evidence(input.report,index,plan.shots.length,copied.sha256);const receipt=buildSocialProductionReceipt({handoff:input.handoff,productionResult:result,gate:'G4',sceneId:input.productionSceneIds[index],attempt:1,status,artifactRefs:[String(artifact.resource_ref)],evidenceRefs:[`artifact_report:${input.artifactId}:${socialRequestHash(input.report)}`],checks,actor:'content_agent',now:new Date(input.handoff.createdAt)});await persistSocialProductionReceipt(input.repository,input.tenantId,receipt);scenes.push({sceneId,productionSceneId:input.productionSceneIds[index]!,shotHash:sceneReworkHash(shot),sha256:copied.sha256,result:supplied,technicalReceiptId:receipt.receiptId,status});
 }
 const manifest=structuredClone(input.manifest);const usedSources=new Set<string>();const replace=(source:unknown)=>{if(typeof source!=='string')return source;const target=remap.get(source);if(target)usedSources.add(source);return target??source;};if(Array.isArray(manifest.timeline))for(const raw of manifest.timeline){const clip=socialObject(raw);if(clip)clip.url=replace(clip.url);}const voiceover=socialObject(manifest.voiceover);if(voiceover)voiceover.url=replace(voiceover.url);if(typeof manifest.bgm==='string')manifest.bgm=replace(manifest.bgm);else{const music=socialObject(manifest.bgm);if(music)music.url=replace(music.url);} const timeline=manifest.timeline;if(!Array.isArray(timeline)||timeline.length!==scenes.length||timeline.some((clip,index)=>socialObject(clip)?.sceneId!==scenes[index]!.sceneId))throw Error('scene_cache_timeline_identity');const cache=sealSocialSceneMediaCache({schemaVersion:'social-scene-media-cache.v1',tenantId:input.tenantId,taskId:input.taskId,runId:input.runId,parentArtifactId:input.artifactId,parentArtifactHash:String(artifact.content_hash),planVersion:plan.planVersion,planHash:sceneReworkHash(plan),scenes,renderInput:{manifest,sourceManifest:structuredClone(input.manifest),mediaRemap:[...remap].filter(([source])=>usedSources.has(source)).map(([source,target])=>({source,target})),voice,bgm}});return createSocialSceneReworkService(input.repository).saveCache({cache,plan,baseline:input.baseline,handoffId:input.handoff.handoffId,handoffVersion:input.handoff.version});
}
