import type {DataStore,Record_} from '../storage/datastore.js';
import {socialJson,socialObject,socialRequestHash} from './socialContentValidation.js';
/** Read-only observation, not production admission or a claim of completed assets. */
export async function readWeeklyStageObservation(store:DataStore,scope:{tenantId:string;taskId:string;runId:string}){
 const run=await store.getById<Record_>('workflow_runs',scope.runId),context=socialObject(socialJson(run?.starter_context)),handoff=socialObject(context?.weeklyPreSupplyHandoff);
 if(!run||run.id!==scope.runId||run.tenant_id!==scope.tenantId||run.status!=='running'||context?.socialTaskId!==scope.taskId||!handoff)return null;
 const {recordHash,...body}=handoff;if(handoff.schemaVersion!=='weekly-pre-supply-handoff.v1'||handoff.tenantId!==scope.tenantId||handoff.taskId!==scope.taskId||handoff.runId!==scope.runId||recordHash!==socialRequestHash(body))return null;
 const jobs=await store.list<Record_>('content_execution_jobs',{where:{tenant_id:scope.tenantId,task_id:scope.taskId,run_id:scope.runId},perPage:2});if(jobs.totalItems!==1||jobs.items.length!==1)return null;const job=jobs.items[0]!,stage=socialObject(socialObject(socialJson(job.checkpoint))?.weeklyStage);
 if(job.tenant_id!==scope.tenantId||job.task_id!==scope.taskId||job.run_id!==scope.runId||!stage||stage.schemaVersion!=='weekly-production-stage.v1'||!['waiting_asset_claim','assets_authorized'].includes(String(stage.stage))||stage.taskId!==scope.taskId||stage.runId!==scope.runId||stage.handoffHash!==recordHash||typeof stage.assetTaskId!=='string'||typeof stage.materialTaskId!=='string'||job.status!=='paused')return null;
 for(const [id,step] of [[stage.assetTaskId,'asset_generation'],[stage.materialTaskId,'material_readiness']] as const){const rows=await store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:scope.tenantId,task_id:id},perPage:2});if(rows.totalItems!==1||rows.items.length!==1)return null;const row=rows.items[0]!;const task=socialObject(socialJson(row.payload)),schedule=socialObject(task?.schedule);if(row.task_id!==id||row.tenant_id!==scope.tenantId||row.program_id!==handoff.programId||row.package_id!==handoff.packageId||row.package_version!==handoff.packageVersion||!task||row.workflow_kind!==task.workflowKind||row.status!==task.status||task.taskId!==id||task.tenantId!==scope.tenantId||task.programId!==handoff.programId||task.packageId!==handoff.packageId||task.packageVersion!==handoff.packageVersion||task.publicationTaskId!==handoff.publicationTaskId||schedule?.stepKind!==step)return null;}
 return {stage:stage.stage as 'waiting_asset_claim'|'assets_authorized',jobId:job.id,runId:scope.runId,assetTaskId:stage.assetTaskId,materialTaskId:stage.materialTaskId,updatedAt:typeof job.updated_at==='string'?job.updated_at:null,evidence:'observed_checkpoint' as const};
}
