import {createHash} from 'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';
import {prepareDirectorG5Fixture,g5FixtureScope,passedDirectorChecks} from './socialDirectorG5ReviewService.fixture.js';
import {assertSocialDirectorG5Audit,SOCIAL_DIRECTOR_G5_REVIEWS} from './socialDirectorG5ReviewService.js';
test('real assigned human director audit binds current G4 and pending immutable artifact, never labels director_agent',async()=>{const f=await prepareDirectorG5Fixture();try{const original=f.tables.starter_social_content_artifacts![0]!.content_hash;const ctx=await f.g5.context(g5FixtureScope,'owner');assert.deepEqual(ctx.gaps,[]);assert.equal(ctx.g4.ready,true);assert.equal(ctx.reviewerUserId,null);await f.g5.assign(g5FixtureScope,'owner',{reviewerUserId:'owner'});const assigned=await f.g5.context(g5FixtureScope,'owner');const body={requestId:'real-human-director-review-0001',expectedContextHash:assigned.contextHash,checks:passedDirectorChecks(assigned)};const read=await f.g5.human(g5FixtureScope,'owner',body);assert.equal(read.projectionStatus,'applied');assert.equal(read.item!.status,'passed');const proof=await assertSocialDirectorG5Audit(f.repository,g5FixtureScope);assert.equal(proof.receipt.actor,'human_director_reviewer');assert.equal(proof.receipt.evidenceKind,'human_director_review');assert.equal(f.tables.starter_social_content_artifacts![0]!.content_hash,original);assert.equal(f.result.technicalReview.approved,false);assert.deepEqual(await f.g5.human(g5FixtureScope,'owner',body),read);await assert.rejects(f.g5.context({...g5FixtureScope,tenantId:'foreign'},'owner'),/actor_forbidden/);const row=f.tables[SOCIAL_DIRECTOR_G5_REVIEWS]!.find(r=>r.kind==='outcome')!;row.content_hash='a'.repeat(64);await assert.rejects(assertSocialDirectorG5Audit(f.repository,g5FixtureScope),/record_corrupt/);}finally{await f.cleanup();}});
import type {DirectorG5RuntimePort} from './socialDirectorG5Runtime.js';
for(const scenario of ['known','unknown_usage','cached_without_tariff','provider_unknown','budget_overrun'] as const)test(`independent agent actual owned frames and explicit production-budget authorization: ${scenario}`,async()=>{let calls=0;const runtime:DirectorG5RuntimePort={descriptor:()=>({configured:true,model:'controlled-director-vl',reservedCostCny:.25,inputPricePerMillion:1,outputPricePerMillion:2}),execute:async input=>{calls++;assert.equal(input.frames.length,6);assert.ok(input.frames.every(f=>Buffer.from(f.base64,'base64')[0]===255));if(scenario==='provider_unknown')throw Error('provider timeout');const checks=passedDirectorChecks(input.context);return {model:'controlled-director-vl',providerResponseId:'actual-controlled-response',inputTokens:scenario==='unknown_usage'?null:scenario==='budget_overrun'?1000000:100,outputTokens:20,cacheTokens:scenario==='cached_without_tariff'?50:0,checks,rawOutput:JSON.stringify({checks})};}};const f=await prepareDirectorG5Fixture({runtime});try{const ctx=await f.g5.context(g5FixtureScope,'owner');assert.ok(ctx.agent.gaps.includes('director_usage_policy_missing'));await assert.rejects(f.g5.agent(g5FixtureScope,'owner',{requestId:'agent-no-authorization-0001',expectedContextHash:ctx.contextHash}),/not_permitted/);await f.g5.authorizeExecution(g5FixtureScope,'owner',{expectedContextHash:ctx.contextHash,model:'controlled-director-vl',maximumCostCny:.5,budgetBucket:'content',purpose:'director_review'});const authorized=await f.g5.context(g5FixtureScope,'owner');assert.equal(authorized.agent.authorization!.executionActor,'director_agent');const input={requestId:`agent-${scenario}-request-0001`,expectedContextHash:authorized.contextHash},result=await f.g5.agent(g5FixtureScope,'owner',input);assert.equal(calls,1);assert.deepEqual(await f.g5.agent(g5FixtureScope,'owner',input),result);assert.equal(calls,1);if(scenario==='known'){assert.equal(result.item!.status,'passed');assert.equal((await assertSocialDirectorG5Audit(f.repository,g5FixtureScope)).receipt.actor,'director_agent');}else{assert.equal(result.item!.state,'unknown');assert.equal(result.runtimeObservationResumeAvailable,false);assert.equal(result.item!.receiptId,null);await assert.rejects(f.g5.agent(g5FixtureScope,'owner',{...input,requestId:'fresh-agent-request-0001'}),/original_request_unresolved/);assert.equal(calls,1);}}finally{await f.cleanup();}});
for(const fault of ['settlement','projection'] as const)test(`known original provider response recovers ${fault} persistence with no provider repeat`,async()=>{let calls=0;const runtime:DirectorG5RuntimePort={descriptor:()=>({configured:true,model:'controlled-director-vl',reservedCostCny:.25,inputPricePerMillion:1,outputPricePerMillion:2}),execute:async input=>{calls++;const checks=passedDirectorChecks(input.context);return {model:'controlled-director-vl',providerResponseId:'original-response-only',inputTokens:100,outputTokens:20,cacheTokens:0,checks,rawOutput:JSON.stringify({checks})};}};const f=await prepareDirectorG5Fixture({runtime});try{let ctx=await f.g5.context(g5FixtureScope,'owner');await f.g5.authorizeExecution(g5FixtureScope,'owner',{expectedContextHash:ctx.contextHash,model:'controlled-director-vl',maximumCostCny:.5,budgetBucket:'content',purpose:'director_review'});ctx=await f.g5.context(g5FixtureScope,'owner');const original=f.store.create;let fail=true;f.store.create=async(c,value)=>{if(fail&&(fault==='settlement'?c==='starter_usage_ledger'&&value.event_type==='terminal':c==='starter_social_production_receipts'&&value.gate==='G5')){fail=false;throw Error('durable write unavailable');}return original(c,value);};const input={requestId:`recover-${fault}-original-0001`,expectedContextHash:ctx.contextHash};await assert.rejects(f.g5.agent(g5FixtureScope,'owner',input));assert.equal(calls,1);assert.ok(f.tables[SOCIAL_DIRECTOR_G5_REVIEWS]!.some(r=>r.kind==='runtime_result'));const read=await f.g5.get(g5FixtureScope,'owner',input.requestId);assert.equal(read.projectionStatus,'pending');assert.equal(read.runtimeObservationResumeAvailable,fault==='settlement');const resumed=await f.g5.resumeProjection(g5FixtureScope,'owner',input.requestId);assert.equal(resumed.projectionStatus,'applied');assert.equal(resumed.item!.status,'passed');assert.equal(calls,1);assert.equal((await assertSocialDirectorG5Audit(f.repository,g5FixtureScope)).receipt.actor,'director_agent');}finally{await f.cleanup();}});
import {appendFile} from 'node:fs/promises';
test('actual owned file and explicit human audit records cannot drift or lose trusted provenance',async()=>{const f=await prepareDirectorG5Fixture();try{await f.g5.assign(g5FixtureScope,'owner',{reviewerUserId:'owner'});const ctx=await f.g5.context(g5FixtureScope,'owner');await f.g5.human(g5FixtureScope,'owner',{requestId:'human-drift-audit-request-0001',expectedContextHash:ctx.contextHash,checks:passedDirectorChecks(ctx)});await appendFile(f.local,'changed');await assert.rejects(assertSocialDirectorG5Audit(f.repository,g5FixtureScope),/integrity|bytes|changed|corrupt/);}finally{await f.cleanup();}});
for(const stop of ['paused','cancelled','package_revoked','version_stale','missing_authority','cancellation_receipt'] as const)test(`new independent review never calls provider after ${stop}`,async()=>{let calls=0;const runtime:DirectorG5RuntimePort={descriptor:()=>({configured:true,model:'controlled-director-vl',reservedCostCny:.25,inputPricePerMillion:1,outputPricePerMillion:2}),execute:async()=>{calls++;throw Error('must not call');}};const f=await prepareDirectorG5Fixture({runtime});try{let ctx=await f.g5.context(g5FixtureScope,'owner');await f.g5.authorizeExecution(g5FixtureScope,'owner',{expectedContextHash:ctx.contextHash,model:'controlled-director-vl',maximumCostCny:.5,budgetBucket:'content',purpose:'director_review'});ctx=await f.g5.context(g5FixtureScope,'owner');const task=f.tables.starter_social_content_tasks![0]!,row=f.tables.social_weekly_operating_packages![0]!;if(stop==='paused'||stop==='cancelled')task.status=stop;else if(stop==='cancellation_receipt')f.tables.social_weekly_cancellations=[{id:createHash('sha256').update('t\0week1\0'+1).digest('hex').slice(0,15),tenant_id:'t',package_id:'week1',package_version:1,status:'in_progress',checkpoints:[],effects:[]}];else if(stop==='missing_authority'){const brief={...(task.brief as Record<string,unknown>)};delete brief._weeklyAuthority;task.brief=brief;}else if(stop==='package_revoked')(row.payload as {status:string}).status='cancelled';else f.tables.social_weekly_operating_packages!.push({...row,id:'new-head',version:2,payload:{...(row.payload as object),version:2,status:'draft'}});await assert.rejects(f.g5.agent(g5FixtureScope,'owner',{requestId:`stop-${stop}-request-0001`,expectedContextHash:ctx.contextHash}));assert.equal(calls,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);assert.equal((await f.g5.context(g5FixtureScope,'owner')).agent.executionPermitted,false);await assert.rejects(f.g5.assign(g5FixtureScope,'owner',{reviewerUserId:'owner'}));}finally{await f.cleanup();}});
test('cancellation after provider return retains real response and reconciles without new execution',async()=>{let calls=0;let cancel:()=>void=()=>{};const runtime:DirectorG5RuntimePort={descriptor:()=>({configured:true,model:'controlled-director-vl',reservedCostCny:.25,inputPricePerMillion:1,outputPricePerMillion:2}),execute:async input=>{calls++;cancel();const checks=passedDirectorChecks(input.context);return {model:'controlled-director-vl',providerResponseId:'paid-before-cancel-response',inputTokens:100,outputTokens:20,cacheTokens:0,checks,rawOutput:JSON.stringify({checks})};}};const f=await prepareDirectorG5Fixture({runtime});try{cancel=()=>{f.tables.starter_social_content_tasks![0]!.status='cancelled';};let ctx=await f.g5.context(g5FixtureScope,'owner');await f.g5.authorizeExecution(g5FixtureScope,'owner',{expectedContextHash:ctx.contextHash,model:'controlled-director-vl',maximumCostCny:.5,budgetBucket:'content',purpose:'director_review'});ctx=await f.g5.context(g5FixtureScope,'owner');const input={requestId:'cancel-after-provider-0001',expectedContextHash:ctx.contextHash};await assert.rejects(f.g5.agent(g5FixtureScope,'owner',input),/paused_or_cancelled/);assert.equal(calls,1);assert.ok(f.tables[SOCIAL_DIRECTOR_G5_REVIEWS]!.some(r=>r.kind==='runtime_result'));assert.equal((await f.g5.get(g5FixtureScope,'owner',input.requestId)).item!.state,'running');assert.equal((await f.g5.resumeProjection(g5FixtureScope,'owner',input.requestId)).projectionStatus,'applied');assert.equal(calls,1);assert.equal((await f.g5.context(g5FixtureScope,'owner')).agent.executionPermitted,false);}finally{await f.cleanup();}});

import {freezeSocialAccountProductionConstraints} from './socialAccountProductionConstraints.js';
// Controlled frozen rule input; real artifact/cache/G4 and formal G5 context.
// This checks requirement delivery, not upstream playbook approval or semantic compliance.
test('formal G5 reads the full frozen account rule requirement without treating it as an acceptance verdict',async()=>{
 const constraints=freezeSocialAccountProductionConstraints({targetAccountRef:{objectType:'owned_social_account',id:'account',version:'3'},accountPlaybookRef:{objectType:'account_playbook',id:'rules',version:'2',accountRef:'account'},verifiedAccountPlaybook:{recordHash:'a'.repeat(64),audience:['采购负责人'],pillars:['产品能力'],recurringFormats:['实测'],evidenceRules:['仅真实参数'],visualRules:['保留真实外观'],languageRules:['中文'],presenterRules:['授权企业人员'],fixedFactors:['品牌调性'],experimentFactors:['开场'],conversionRoute:{routeId:'contact',entryType:'direct_message',entryRef:null,callToAction:'询问产品信息',qualificationFields:[],handoffTarget:null,verifiedAt:null}}});assert.ok(constraints);
 const f=await prepareDirectorG5Fixture({runtime:{descriptor:()=>({configured:false,model:'controlled-not-used',reservedCostCny:null,inputPricePerMillion:null,outputPricePerMillion:null}),execute:async()=>{throw Error('read-only context must not execute');}}},undefined,constraints);try{
  const current=await f.g5.context(g5FixtureScope,'owner');
  assert.deepEqual(current.requirements.accountPlaybook,constraints);
  assert.equal(current.requirements.accountPlaybook?.reviewStatus,'unverified');
  assert.deepEqual(current.requirements.accountPlaybook?.rules.experimentFactors,['开场']);
  assert.ok(current.agent.gaps.includes('director_runtime_not_configured')||!current.agent.configured);
  assert.equal((await f.g5.get(g5FixtureScope,'owner','readonly-account-rules-no-review')).item,null);
  assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 }finally{await f.cleanup();}
});
