import test from 'node:test';import assert from 'node:assert/strict';
import {prepareInstagramDeliveryFixture} from './socialInstagramDeliveryService.fixture.js';
import {createSocialInstagramDeliveryService} from './socialInstagramDeliveryService.js';
import {INSTAGRAM_DELIVERY_TECHNICAL_CHECKS,INSTAGRAM_DELIVERY_CREATIVE_CHECKS} from '../../shared/contracts/socialInstagramDelivery.js';
test('real owned source prepares one archive, original review is not inherited, independent reviews bind delivery SHA',async t=>{
 const f=await prepareInstagramDeliveryFixture();t.after(f.cleanup);const source=await f.g6.context(f.scope,'owner');
 const service=createSocialInstagramDeliveryService(f.repository);const body={requestId:'prepare_delivery_actual_0001',expectedContextHash:source.contextHash};
 const first=await service.prepare(f.scope,'owner',body);assert.equal(first.currentSourceVerified,true);assert.equal(first.reviews.length,0);assert.deepEqual(first.gaps,['packaged_technical_review_required','packaged_creative_review_required']);assert.notEqual(first.item!.fileSha256,first.item!.sourceFileSha256);
 const replay=await service.prepare(f.scope,'owner',body);assert.equal(replay.item!.deliveryId,first.item!.deliveryId);assert.equal(f.tables.starter_social_instagram_deliveries!.length,1);
 for(const kind of ['technical','creative'] as const){const codes=kind==='technical'?INSTAGRAM_DELIVERY_TECHNICAL_CHECKS:INSTAGRAM_DELIVERY_CREATIVE_CHECKS;await service.review(f.scope,'owner',{requestId:`actual_delivery_review_${kind}_0001`,expectedDeliveryHash:first.item!.recordHash,kind,checks:codes.map(code=>({code,outcome:'passed',observation:'已观察归档包装后视频的对应项目'}))});}
 const final=await service.read(f.scope,'owner');assert.equal(final.reviews.length,2);assert.equal(final.gaps.length,0);assert.ok(final.reviews.every(r=>r.fileSha256===first.item!.fileSha256));
 const g6=await f.g6.context(f.scope,'owner');assert.equal(g6.fileSha256,first.item!.sourceFileSha256);assert.equal(g6.metadata!.fileSha256,first.item!.fileSha256);assert.equal(g6.checks.find(c=>c.code==='platform_format')!.status,'passed');assert.ok(g6.instagramDelivery);const {createInstagramDeliveryPublicationProof}=await import('../publishing/instagramDeliveryPublicationProof.js');await assert.rejects(createInstagramDeliveryPublicationProof(f.store,f.scope),/g6_not_passed/);
 const original=f.tables.starter_social_content_tasks![0]!.status;assert.equal(original,'asset_review');assert.equal(f.tables.publish_attempts?.length??0,0);
 await assert.rejects(service.read({...f.scope,tenantId:'foreign'},'owner'));
 const {socialRequestHash}=await import('./socialContentValidation.js');const row=f.tables.starter_social_instagram_delivery_reviews![0]!,saved=structuredClone(row);const review=row.payload as {recordHash:string;status:string;checks:Array<{outcome:string}>};review.checks[0]!.outcome='unknown';const {recordHash,...bodyReview}=review;review.recordHash=socialRequestHash(bodyReview);row.content_hash=review.recordHash;await assert.rejects(service.read(f.scope,'owner'),/review_status_invalid/);Object.assign(row,saved);
 const sourceScope={tenantId:f.scope.tenantId,taskId:f.scope.taskId,runId:f.scope.runId,artifactId:f.scope.artifactId};const g5ctx=await f.g5.context(sourceScope,'owner');const {passedDirectorChecks}=await import('./socialDirectorG5ReviewService.fixture.js');await f.g5.human(sourceScope,'owner',{requestId:'actual_source_reaudit_changed_0001',expectedContextHash:g5ctx.contextHash,checks:passedDirectorChecks(g5ctx)});await assert.rejects(service.read(f.scope,'owner'),/source_audit_changed/);
});
