import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile,unlink,rm} from 'node:fs/promises';
import path from 'node:path';
import {prepared} from './socialContentSceneReworkService.fixture.js';
import {createStarter198Repository} from './repository.js';
import {socialRequestHash} from './socialContentValidation.js';
import {persistInitialSocialSceneCache,initialSceneCacheInputFingerprint,initialSceneSourceHashes,type InitialSceneQualityReport} from './socialContentInitialSceneCache.js';
import type {SocialAssetSupplyExecution} from './socialContentAssetSupplyExecution.js';
import {sceneReworkHash} from './socialContentSceneRework.js';
async function firstRun(){
 const f=await prepared();f.tables.starter_social_production_receipts=[];f.tables.starter_social_scene_media_caches=[];
 const report:InitialSceneQualityReport={schemaVersion:'initial-scene-quality.v1',visual:{passed:false,failures:['实际抽帧解码失败'],metrics:{sampleCount:0,contentFrameCount:0,nonBackgroundFrameRatio:0,meanBrightness:0,meanLumaDeviation:0,meanEdgeRatio:0,meanFrameDifference:0,maxFrameDifference:0,motionDetected:false,estimatedDistinctFrames:0,nearDuplicateFrameRatio:0,sharpFrameRatio:0},evidenceFrames:[]},scenes:{passed:false,issues:f.context.baseline.scenes.map((_,sceneIndex)=>({sceneIndex,start:sceneIndex*3,end:(sceneIndex+1)*3,code:'decode',reason:'实际抽帧解码失败'})),checkedScenes:0},audio:{ok:false,error:'实际音轨解码失败'}};
 const artifact=f.tables.starter_social_content_artifacts![0]!,content=artifact.content as Record<string,unknown>;content.technicalQualityReport=report;artifact.content_hash=socialRequestHash({resourceRef:artifact.resource_ref,content});
 const transient=path.join(path.dirname(f.local),'transient-voice.wav');await writeFile(transient,Buffer.from('actual voice bytes'));
 const execution:SocialAssetSupplyExecution={schemaVersion:'social-content.asset-supply-execution.v1',planVersion:f.context.plan.planVersion,creationMode:f.context.plan.creationMode,productionRoute:f.context.plan.productionRoute,managementMode:f.context.plan.managementMode,executedAt:'2026-10-01T00:00:00Z',shots:f.context.plan.shots.map((shot,index)=>({shotId:shot.shotId,sceneId:f.context.baseline.scenes[index]!.sceneId,function:shot.function,requestedSourceStrategy:shot.sourceStrategy,sourceStrategy:'customer_real_asset',fallbackApplied:false,providerId:'actual-provider',assetId:'asset',sourceRef:'asset',truthBoundary:shot.truthBoundary,functionalEquivalentReplacement:shot.functionalEquivalentReplacement,provenance:{synthetic:false,representation:'non_evidentiary_visual',authorizationRef:null,disclosure:null},attempts:[{sourceStrategy:'customer_real_asset',adapterId:'actual-provider',status:'completed',reason:null}]}))};
 const input={repository:createStarter198Repository(f.store),tenantId:'t',taskId:'content',runId:'run',artifactId:'artifact',handoff:f.handoff,plan:f.context.plan,baseline:f.context.baseline,execution,assets:[{id:'asset',name:'实际供给',type:'video' as const,sourceId:'source',url:f.local,localPath:f.local,duration:3,visualObservations:['实际供给'],segments:[]}],productionSceneIds:f.handoff.shotTraces.map(s=>s.sceneId),manifest:{timeline:f.context.baseline.scenes.map(s=>({sceneId:s.sceneId,url:f.local})),voiceover:{url:transient,volume:0.8},captions:[{text:'实际字幕',start:0,end:1}],cover:{title:'实际封面'}},voicePath:transient,bgmUrl:null,report};
 content.initialSceneSourceHashes=await initialSceneSourceHashes(input);content.initialSceneCacheInput=initialSceneCacheInputFingerprint(input);content.assetSupplyExecution=execution;artifact.content_hash=socialRequestHash({resourceRef:artifact.resource_ref,content});
 const cleanup=async()=>{await f.cleanup();await rm(path.resolve('data/social-content-scene-cache',sceneReworkHash(['t','content','run','artifact'])),{recursive:true,force:true});};return{f,input,cleanup,transient};
}
test('first-run actual supplies and full compositor manifest survive transient voice cleanup; failures never become passed',async()=>{const x=await firstRun();try{const runCount=x.f.tables.workflow_runs!.length,artifactCount=x.f.tables.starter_social_content_artifacts!.length;const stored=await persistInitialSocialSceneCache(x.input);const again=await persistInitialSocialSceneCache(x.input);assert.equal(again.cache.recordHash,stored.cache.recordHash);await unlink(x.transient);assert.equal((await readFile(stored.cache.renderInput.voice.localPath)).toString(),'actual voice bytes');assert.deepEqual(stored.cache.renderInput.manifest.captions,x.input.manifest.captions);assert.equal((stored.cache.renderInput.manifest.voiceover as {url:string}).url,stored.cache.renderInput.voice.localPath);assert.ok(stored.cache.scenes.every(s=>s.status==='failed'&&s.result.providerId==='actual-provider'));for(const row of x.f.tables.starter_social_production_receipts!){const receipt=row.payload as any;assert.equal(receipt.status,'failed');assert.equal(receipt.checks.find((c:any)=>c.code==='caption').passed,false);assert.equal(receipt.checks.find((c:any)=>c.code==='sensitive_data').passed,false);}assert.equal(x.f.tables.workflow_runs!.length,runCount);assert.equal(x.f.tables.starter_social_content_artifacts!.length,artifactCount);}finally{await x.cleanup();}});
test('stored detection report drift blocks before receipts/cache are synthesized',async()=>{const x=await firstRun();try{x.input.report=structuredClone(x.input.report);x.input.report.audio.ok=true;await assert.rejects(persistInitialSocialSceneCache(x.input),/original_report_mismatch/);assert.equal(x.f.tables.starter_social_production_receipts!.length,0);assert.equal(x.f.tables.starter_social_scene_media_caches!.length,0);}finally{await x.cleanup();}});
test('missing original scene supply bytes cannot be reconstructed from final video',async()=>{const x=await firstRun();try{x.input.assets[0]!.localPath='';await assert.rejects(persistInitialSocialSceneCache(x.input),/original_supply_bytes_required/);assert.equal(x.f.tables.starter_social_scene_media_caches!.length,0);}finally{await x.cleanup();}});

test('actual frozen supply provenance drift blocks cache even when final artifact exists',async()=>{const x=await firstRun();try{x.input.execution=structuredClone(x.input.execution);x.input.execution.shots[0]!.providerId='different-provider';await assert.rejects(persistInitialSocialSceneCache(x.input),/original_inputs_mismatch/);assert.equal(x.f.tables.starter_social_scene_media_caches!.length,0);}finally{await x.cleanup();}});
test('first-run original voice bytes drift is rejected against artifact frozen media hashes',async()=>{const x=await firstRun();try{await writeFile(x.transient,'changed narration bytes');await assert.rejects(persistInitialSocialSceneCache(x.input),/original_source_bytes_mismatch/);assert.equal(x.f.tables.starter_social_scene_media_caches!.length,0);}finally{await x.cleanup();}});
test('passing visual/audio detector-port results preserve unknown G4 caption and sensitive checks as review_required',async()=>{const x=await firstRun();try{const report=structuredClone(x.input.report);report.visual.passed=true;report.visual.failures=[];report.scenes={passed:true,issues:[],checkedScenes:x.input.baseline.scenes.length};report.audio={ok:true,error:null};x.input.report=report;const artifact=x.f.tables.starter_social_content_artifacts![0]!,content=artifact.content as Record<string,unknown>;content.technicalQualityReport=report;artifact.content_hash=socialRequestHash({resourceRef:artifact.resource_ref,content});const stored=await persistInitialSocialSceneCache(x.input);assert.ok(stored.cache.scenes.every(s=>s.status==='review_required'));for(const row of x.f.tables.starter_social_production_receipts!){const receipt=row.payload as any;assert.equal(receipt.status,'review_required');assert.ok(receipt.checks.some((c:any)=>c.code==='caption'&&!c.passed));}}finally{await x.cleanup();}});
