import test from 'node:test';import assert from 'node:assert/strict';import type {DataStore,Record_,ListQuery} from '../storage/datastore.js';import {socialRequestHash} from './socialContentValidation.js';import {readWeeklyStageObservation} from './socialWeeklyStageObservation.js';
test('read-only paused checkpoint observation requires same run/hash/unique real downstream scope and mutates nothing',async()=>{
 const scope={tenantId:'t',taskId:'content',runId:'original'},body={schemaVersion:'weekly-pre-supply-handoff.v1',...scope,programId:'p',packageId:'week',packageVersion:1,publicationTaskId:'pub'},handoff={...body,recordHash:socialRequestHash(body)};
 const stage={schemaVersion:'weekly-production-stage.v1',stage:'waiting_asset_claim',taskId:'content',runId:'original',handoffHash:handoff.recordHash,assetTaskId:'asset',materialTaskId:'material'};
 const job:Record_={id:'job',tenant_id:'t',task_id:'content',run_id:'original',status:'paused',checkpoint:{weeklyStage:stage},updated_at:'2026-10-10T10:00:00Z'};const run:Record_={id:'original',tenant_id:'t',status:'running',starter_context:{socialTaskId:'content',weeklyPreSupplyHandoff:handoff}};
 const tasks=['asset','material'].map((id,i)=>({id,tenant_id:'t',task_id:id,program_id:'p',package_id:'week',package_version:1,workflow_kind:'content',status:'blocked',payload:{workflowKind:'content',status:'blocked',taskId:id,tenantId:'t',programId:'p',packageId:'week',packageVersion:1,publicationTaskId:'pub',schedule:{stepKind:i===0?'asset_generation':'material_readiness'}}}));const tables:Record<string,Record_[]>={workflow_runs:[run],content_execution_jobs:[job],social_weekly_execution_tasks:tasks};let writes=0;
 const store:DataStore={async getById<T>(c:string,id:string){return (tables[c]?.find(r=>r.id===id)??null)as T|null;},async list<T>(c:string,q:ListQuery={}){const rows=(tables[c]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));return {items:rows.slice(0,q.perPage??20)as T[],totalItems:rows.length,totalPages:1,page:1,perPage:q.perPage??20};},async create(){writes++;return null;},async update(){writes++;return false;},async delete(){writes++;return false;}};
 assert.equal((await readWeeklyStageObservation(store,scope))?.stage,'waiting_asset_claim');stage.runId='foreign';assert.equal(await readWeeklyStageObservation(store,scope),null);stage.runId='original';stage.handoffHash='f'.repeat(64);assert.equal(await readWeeklyStageObservation(store,scope),null);stage.handoffHash=handoff.recordHash;assert.ok(tables.content_execution_jobs);tables.content_execution_jobs.push({...job,id:'duplicate'});assert.equal(await readWeeklyStageObservation(store,scope),null);tables.content_execution_jobs.pop();const asset=tasks[0];assert.ok(asset);asset.payload.packageVersion=2;assert.equal(await readWeeklyStageObservation(store,scope),null);asset.payload.packageVersion=1;asset.payload.taskId='wrong-card';assert.equal(await readWeeklyStageObservation(store,scope),null);asset.payload.taskId='asset';asset.package_version=2;assert.equal(await readWeeklyStageObservation(store,scope),null);assert.equal(writes,0);
});
