import {readWeeklyCustomerRelationshipScope,evaluateWeeklyCustomerRelationship} from './weeklyCustomerRelationshipScope.js';
import {confirmCustomerRelationship,CUSTOMER_RELATIONSHIP_CONFIRMATIONS} from './customerRelationshipEvidence.js';
import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import type {DataStore,Record_} from '../storage/datastore.js';import {bindWeeklyCustomerRun} from '../runtime/socialWeeklyCustomerBridge.js';import {createWeeklySalesHandoffService,SALES_HANDOFFS,SALES_EVENTS} from '../runtime/socialWeeklySalesHandoff.js';import {createCustomerFeedbackTopicService,FEEDBACK_TOPIC_CANDIDATES,FEEDBACK_TOPIC_CONFIRMATIONS} from './customerFeedbackTopics.js';
const authority={tenantId:'tenant',programId:'program',packageId:'week',packageVersion:1};
function fixture() {
  const scope = { tenant_id: 'tenant', goal_id: 'goal', plan_id: 'plan', run_id: 'run' };
  const taskKeys = ['customer_segmentation', 'followup_batch_draft', 'followup_batch_approval', 'followup_dispatch'];
  const data: Record<string, Record_[]> = {
    social_weekly_operating_packages: [{ id: 'pkg', tenant_id: 'tenant', program_id: 'program', package_id: 'week', version: 1, payload: { programId: 'program', packageId: 'week', version: 1, weekStart: '2026-10-05', weekEnd: '2026-10-11' } }],
    workflow_runs: [{ id: 'run', ...scope, status: 'running' }],
    weekly_goals: [{ id: 'goal', tenant_id: 'tenant', business_line: 'customer_conversion', starts_at: '2026-10-05T00:00:00Z', ends_at: '2026-10-11T23:59:59Z' }],
    weekly_plans: [{ id: 'plan', tenant_id: 'tenant', goal_id: 'goal' }],
    workflow_tasks: taskKeys.map(key => ({ id: key, ...scope, task_key: key, agent_role: 'customer', status: 'succeeded' })),
    customer_segments: [{ id: 'segment', ...scope, task_id: 'customer_segmentation', status: 'generated', version: 1, criteria: {}, criteria_hash: createHash('sha256').update('{}').digest('hex'), snapshot_at: '2026-10-06T10:00:00Z', member_count: 1 }],
    customer_segment_members: [{ id: 'member', tenant_id: 'tenant', segment_id: 'segment', customer_id: 'buyer', customer_snapshot: { id: 'buyer', name: 'Real persisted buyer' }, membership: 'included' }],
    followup_batches: [{ id: 'batch', ...scope, task_id: 'followup_batch_draft', segment_id: 'segment', version: 2, content_hash: 'batch-hash', approval_id: 'approval', approved_version: 2, approved_by: 'owner' }],
    followup_batch_items: [{ id: 'item', tenant_id: 'tenant', batch_id: 'batch', segment_member_id: 'member', customer_id: 'buyer', draft_body: 'Approved buyer-specific draft', content_hash: createHash('sha256').update(JSON.stringify('Approved buyer-specific draft')).digest('hex'), send_mode: 'session_message', status: 'sent', exclusion_reason: '', provider_message_id: 'wamid.real-provider-receipt', provider_receipt: { id: 'wamid.real-provider-receipt' }, sent_at: '2026-10-06T12:00:00Z' }],
    approval_requests: [{ id: 'approval', ...scope, task_id: 'followup_batch_approval', subject_version: 2, content_hash: 'batch-hash', status: 'approved', decided_by: 'owner', decided_at: '2026-10-06T11:00:00Z' }],
  };
  const batchHash = createHash('sha256').update(JSON.stringify(data.followup_batch_items!.map(row => row.content_hash))).digest('hex');
  data.followup_batches![0]!.content_hash = batchHash; data.approval_requests![0]!.content_hash = batchHash;
  const store = {
    async getById<T>(collection: string, id: string) { return (data[collection]?.find(row => row.id === id) ?? null) as T | null; },
    async list<T>(collection: string, query: any = {}) { let found = (data[collection] ?? []).filter(row => Object.entries(query.where ?? {}).every(([key, value]) => row[key] === value)); if(query.sort){const desc=query.sort.startsWith('-');const field=desc?query.sort.slice(1):query.sort;found=[...found].sort((a,b)=>(Number(a[field])-Number(b[field]))*(desc?-1:1));}const per = query.perPage ?? 250; const page = query.page ?? 1; return { items: found.slice((page - 1) * per, page * per) as T[], totalItems: found.length, totalPages: Math.ceil(found.length / per), page, perPage: per }; },
    async create<T>(collection: string, values: Record<string, unknown>) { const row = { id: `${collection}-${data[collection]?.length ?? 0}`, ...values }; (data[collection] ??= []).push(row); return row as T; },
    async update(collection:string,id:string,values:Record<string,unknown>) { if(collection.startsWith('social_weekly_sales'))throw Error('Sales remains immutable');const row=data[collection]?.find(r=>r.id===id);if(!row)return false;Object.assign(row,values);return true; },
    async delete(collection:string,id:string){if(collection.startsWith('social_weekly_sales'))throw Error('Sales remains immutable');data[collection]=(data[collection]??[]).filter(r=>r.id!==id);return true;},
  } as unknown as DataStore;
  return { store, data };
}

async function prepared(){const f=fixture();f.data.users=[{id:'owner',tenantId:'tenant',role:'admin'},{id:'sales',tenantId:'tenant',role:'customer_service'}];f.data.social_programs=[{id:'program-row',tenant_id:'tenant',program_id:'program',payload:{route:'cold_start'}}];f.data.whatsapp_customers=[{id:'buyer-row',tenant_id:'tenant',customer_id:'buyer',payload:{id:'buyer',tenantId:'tenant',createdAt:'2026-10-06T00:00:00Z'}}];f.data.whatsapp_interactions=[{id:'conversation-row',tenant_id:'tenant',customer_id:'buyer',interaction_id:'inquiry',payload:{id:'inquiry',tenantId:'tenant',customerId:'buyer',body:'Please send the specification',type:'msg_in',timestamp:Date.parse('2026-10-06T01:00:00Z'),metaMessageId:'wamid.real-inquiry'}}];await confirmCustomerRelationship(f.store,{tenantId:'tenant',customerId:'buyer',actorUserId:'owner',classification:'new_inquiry',weekStart:'2026-10-05T00:00:00Z',weekEnd:'2026-10-11T23:59:59Z',firstInteractionId:'inquiry',relationshipSince:'2026-10-06T01:00:00Z',reason:'实名人工确认首询，核对未发现此前客户往来'});await bindWeeklyCustomerRun(f.store,authority,'run','owner');const scope=await readWeeklyCustomerRelationshipScope(f.store,'tenant','run');const relation=await evaluateWeeklyCustomerRelationship(f.store,scope!,'buyer');f.data.customer_segment_members![0]!.customer_snapshot={id:'buyer',weeklyRelationship:relation.frozen};return {...f,service:createWeeklySalesHandoffService(f.store)};}
const input={runId:'run',memberId:'member',sourceInteractionId:'inquiry',ownerUserId:'sales',claimDueAt:'2026-10-07T00:00:00Z',feedbackDueAt:'2026-10-08T00:00:00Z'};

async function topicFixture(){const f=await prepared();const hand=await f.service.create(authority,'owner',input);await f.service.transition(authority,hand.id,'sales',{expectedVersion:1,operationId:'claim',action:'claim'});f.data.whatsapp_interactions!.push({id:'human-row',tenant_id:'tenant',customer_id:'buyer',interaction_id:'human-reply',payload:{id:'human-reply',tenantId:'tenant',customerId:'buyer',type:'msg_out_human',metaMessageId:'provider-human-reply',body:'Human answer',timestamp:Date.now()}});await f.service.transition(authority,hand.id,'sales',{expectedVersion:2,operationId:'feedback',action:'feedback',feedback:{result:'Requirements discussed; sales outcome unknown',evidenceInteractionIds:['human-reply'],nextStep:'Confirm buyer needs',nextDueAt:'2026-10-12T00:00:00Z'}});const topics=createCustomerFeedbackTopicService(f.store);const args={tenantId:'tenant',programId:'program',actorUserId:'owner',sourcePackageId:'week',sourcePackageVersion:1,handoffId:hand.id,interactionId:'inquiry',excerptStart:0,excerptEnd:29,topicAngle:'Explain the product specification with verified details'};return{...f,hand,topics,args};}
test('actual buyer question and feedback version create an evidence-bound topic candidate without attribution',async()=>{const f=await topicFixture();const c=await f.topics.create(f.args);assert.equal(c.source.question,'Please send the specification');assert.equal(c.source.handoffVersion,3);assert.equal(c.attributionConclusion,'not_measured');assert.equal(c.source.customerRelationship,'unknown');assert.equal((await f.topics.create(f.args)).id,c.id);assert.equal((f.data[FEEDBACK_TOPIC_CANDIDATES]??[]).length,1);assert.equal((f.data.social_weekly_execution_tasks??[]).length,0);});
test('human outbound, synthetic input, false excerpt and unauthorized actor cannot become buyer evidence',async()=>{for(const change of [(args:any,f:any)=>{args.interactionId='human-reply';args.excerptEnd=5;},(args:any,f:any)=>{f.data.whatsapp_interactions[0].payload.synthetic=true;},(args:any)=>{args.excerptEnd=9999;},(args:any)=>{args.tenantId='foreign';},(args:any,f:any)=>{f.data.users.push({id:'unrelated',tenantId:'tenant',role:'social_operator'});args.actorUserId='unrelated';}]){const f=await topicFixture();const args={...f.args};change(args,f);await assert.rejects(f.topics.create(args));assert.equal((f.data[FEEDBACK_TOPIC_CANDIDATES]??[]).length,0);}});
test('next-week confirmation remains a pending proposal until exact revision and publication ref exist',async()=>{const f=await topicFixture();const c=await f.topics.create(f.args);const target:any={packageId:'next',programId:'program',version:1,status:'draft',weekStart:'2026-10-12',weekEnd:'2026-10-18',socialContentPackage:{publicationTasks:[{publicationTaskId:'next-video',status:'planned'}]}};f.data.social_weekly_operating_packages!.push({id:'next-1',tenant_id:'tenant',program_id:'program',package_id:'next',version:1,payload:target});const proposal=await f.topics.proposeNextRevision({tenantId:'tenant',programId:'program',actorUserId:'owner',candidateId:c.id,targetPackageId:'next',expectedTargetPackageVersion:1,publicationTaskId:'next-video'});assert.equal(proposal.status,'pending_next_revision');assert.equal(proposal.target.packageVersion,2);const ref={type:'customer_feedback_topic_confirmation',id:proposal.id,version:1};const next:any={...target,version:2,socialContentPackage:{publicationTasks:[{publicationTaskId:'next-video',status:'planned',customerFeedbackTopicRef:ref}]}};await assert.rejects(f.topics.verifiedPlanningReference({tenantId:'tenant',programId:'program',pkg:next,publicationTaskId:'next-video',ref}));f.data.social_weekly_operating_packages!.push({id:'next-2',tenant_id:'tenant',program_id:'program',package_id:'next',version:2,payload:next});assert.equal((await f.topics.verifiedPlanningReference({tenantId:'tenant',programId:'program',pkg:next,publicationTaskId:'next-video',ref})).candidate.source.question,c.source.question);await assert.rejects(f.topics.verifiedPlanningReference({tenantId:'tenant',programId:'program',pkg:next,publicationTaskId:'another-video',ref}));assert.equal((f.data[FEEDBACK_TOPIC_CONFIRMATIONS]??[]).length,1);assert.equal((f.data.social_weekly_execution_tasks??[]).length,0);});
test('question bytes and feedback evidence drift invalidate an existing candidate',async()=>{for(const change of [(f:any)=>{f.data.whatsapp_interactions[0].payload.body='Edited question';},(f:any)=>{f.data[SALES_EVENTS][1].payload.feedback.result='Altered feedback';}]){const f=await topicFixture();const c=await f.topics.create(f.args);change(f);await assert.rejects(f.topics.get('tenant','program',c.id,'owner'));}});
test('same-week or superseded target and non-operator confirmation are rejected',async()=>{const f=await topicFixture();const c=await f.topics.create(f.args);(f.data.social_weekly_operating_packages![0]!.payload as any).status='draft';(f.data.social_weekly_operating_packages![0]!.payload as any).socialContentPackage={publicationTasks:[{publicationTaskId:'video',status:'planned'}]};await assert.rejects(f.topics.proposeNextRevision({tenantId:'tenant',programId:'program',actorUserId:'owner',candidateId:c.id,targetPackageId:'week',expectedTargetPackageVersion:1,publicationTaskId:'video'}));await assert.rejects(f.topics.proposeNextRevision({tenantId:'tenant',programId:'program',actorUserId:'sales',candidateId:c.id,targetPackageId:'week',expectedTargetPackageVersion:1,publicationTaskId:'video'}));});

function planningPackage(): any {
  const publication = {
    publicationTaskId: 'publication-1', motherContentId: 'mother-1', adaptationOfPublicationTaskId: null,
    platform: 'tiktok' as const, accountId: 'owned-account-1', accountPositioning: 'B2B factory', businessProposition: 'OEM proof', cta: 'Contact sales',
    factRefs: [{ type: 'enterprise_fact', id: 'fact-1', version: 1 }], metricTargets: ['qualified_inquiry'], publishWindow: '2026-10-08T10:00:00Z', status: 'planned' as const,
  };
  return {
    packageId: 'package-1', programId: 'program', version: 1, status: 'draft', weekStart: '2026-10-05', weekEnd: '2026-10-11', objective: '获得 B2B 询盘',
    enterpriseProfileRef: null, monthlyPlanRef: null, workflows: [], workflowTasks: [], appliedWorkflowEvents: [], taskVersionMappings: [], planningBlockers: [],
    capacityPlanRef: null, automationPolicyRef: null, discoveryBudgetCny: 10,
    socialContentPackage: {
      contentPackageId: 'content-package-1', operatingPackageId: 'package-1', version: 1, status: 'draft', originalContentTarget: 1, adaptationVersionTarget: 0,
      publicationTaskTarget: 1, publicationTasks: [publication], weeklyBudgetCny: 100, perItemBudgetCny: 100, capacityNotes: [],
      authorization: { mode: 'bounded', accountIds: ['owned-account-1'], maxPublishItems: 1, weekStart: '2026-10-05', weekEnd: '2026-10-11', allowRealPublishing: false, authorizedBy: null, authorizedAt: null, revokedBy: null, revokedAt: null },
    },
    successCriteria: ['1 条完成'], changeReason: null, previousVersion: null, createdBy: 'owner', createdAt: '2026-10-01T00:00:00Z', updatedAt: '2026-10-01T00:00:00Z',
  };
}


test('explicit next-week frozen question reference actually becomes a director topic and merged schedule item',async()=>{const f=await topicFixture();const c=await f.topics.create(f.args);const target:any={...planningPackage(),packageId:'next',weekStart:'2026-10-12',weekEnd:'2026-10-18'};f.data.social_weekly_operating_packages!.push({id:'next-1',tenant_id:'tenant',program_id:'program',package_id:'next',version:1,payload:target});const proposal=await f.topics.proposeNextRevision({tenantId:'tenant',programId:'program',actorUserId:'owner',candidateId:c.id,targetPackageId:'next',expectedTargetPackageVersion:1,publicationTaskId:'publication-1'});const next:any={...target,version:2,socialContentPackage:{...target.socialContentPackage,publicationTasks:target.socialContentPackage.publicationTasks.map((p:any)=>({...p,customerFeedbackTopicRef:{type:'customer_feedback_topic_confirmation',id:proposal.id,version:1}}))}};f.data.social_weekly_operating_packages!.push({id:'next-2',tenant_id:'tenant',program_id:'program',package_id:'next',version:2,payload:next});const dataStore=f.store;
  await dataStore.create('social_discovery_scopes', {
    tenant_id: 'tenant', program_id: 'program', status: 'active', keyword_set_id: 'set-1', version: 1,
    payload: { approval: { status: 'approved', scopeVersion: 1 }, keywordSet: { scope: { audienceRole: 'brand_buyer' }, graph: { sceneClusters: [] } } },
  });
  await dataStore.create('social_candidate_evidence', {
    tenant_id: 'tenant', evidenceId: 'evidence-video-1', version: 1, tenantId: 'tenant', candidateId: 'video-1', inputFingerprint: 'fp',
    evidence: {
      inspirationId: 'video-1', discoveryPath: ['keyword'], sceneIds: [], relevance: { level: 'high', reasons: [] }, momentum: { level: 'high_performance', reasons: [], confidence: 0.8 },
      transferability: { level: 'high', mechanisms: ['demo'], limitations: [] }, evidenceRefs: ['source'],
      qualityScore: { ruleVersion: 'discovery-score-v1', overall: 90, dimensions: { relevance: 90, transferability: 90, momentum: 75, evidence: 80, platformPriority: 100, businessModelFit: 100 }, decision: 'accepted', reasons: ['B2B'], blockers: [], scoredAt: '2026-10-01T00:00:00Z' },
      classification: { businessModel: 'b2b', platform: 'tiktok', keywordTier: 'medium' },
    },
    g1: { sourceUrl: 'https://www.tiktok.com/video-1' }, completeness: 'complete', createdAt: '2026-10-01T00:00:00Z', supersedesEvidenceId: null,
  });
  await dataStore.create('trend_videos', { id: 'video-1', tenantId: 'tenant', platform: 'tiktok', title: 'OEM factory capability proof', sourceUrl: 'https://www.tiktok.com/video-1' });
  await dataStore.create('social_tracked_accounts', {
    tenant_id: 'tenant', accountId: 'https://www.tiktok.com/@oem_factory', decision: 'track', status: 'tracked', accountRole: 'brand_factory', reasons: ['OEM factory wholesale supplier'],
    evidenceVideoIds: ['video-1', 'video-2', 'video-3'], relatedSceneIds: [], missingEvidence: [], confidence: 0.95,
    businessConfirmation: { status: 'confirmed', confirmedBy: 'business_agent', decisionRef: 'decision-1', reason: null, confirmedAt: '2026-10-01T00:00:00Z' },
  });

 const{createWeeklyPlanningAuthority}=await import('./planningAuthority.js');const authority=createWeeklyPlanningAuthority(f.store);const outline=await authority.initialize('tenant',next);const analyzed=await authority.runDirectorAnalysis({tenantId:'tenant',programId:'program',packageId:'next',packageVersion:2,expectedPlanningVersion:outline.version,actor:'director_agent'});assert.equal(analyzed.directorAnalyses[0]!.customerFeedbackTopicRefs?.[0]?.id,proposal.id);assert.match(analyzed.directorAnalyses[0]!.contentDirection,/Please send the specification/);const merged=await authority.mergeDetailedSchedule({tenantId:'tenant',programId:'program',package:next,expectedPlanningVersion:analyzed.version,actor:'business_agent'});assert.equal(merged.detailedSchedule!.items[0]!.topic,c.topicAngle);assert.equal(merged.status,'awaiting_confirmation');assert.equal((f.data.social_weekly_execution_tasks??[]).length,0);
});
test('calendar-invalid source week is rejected before drafting buyer evidence',async()=>{const f=await topicFixture();(f.data.social_weekly_operating_packages![0]!.payload as any).weekEnd='2026-02-30';await assert.rejects(f.topics.create(f.args));});
test('sources and candidate lists reveal only actual authorized buyer messages',async()=>{const f=await topicFixture();const sources=await f.topics.sources({tenantId:'tenant',programId:'program',actorUserId:'owner',sourcePackageId:'week',sourcePackageVersion:1});assert.equal(sources.items.length,1);assert.equal(sources.items[0]!.interactionId,'inquiry');assert.equal(sources.gaps[0]!.interactionId,'human-reply');const c=await f.topics.create(f.args);assert.equal((await f.topics.list({tenantId:'tenant',programId:'program',actorUserId:'owner'})).items[0]!.id,c.id);f.data.users!.push({id:'unrelated',tenantId:'tenant',role:'admin'});assert.equal((await f.topics.list({tenantId:'tenant',programId:'program',actorUserId:'unrelated'})).items.length,0);});
test('actual HTTP topic routes preserve source permission and reject forged buyer selection',async()=>{const f=await topicFixture();const{default:express}=await import('express');const{createSocialCustomerFeedbackTopicsRouter}=await import('../routes/socialCustomerFeedbackTopics.js');const app=express();app.use(express.json());app.use((req,res,next)=>{if(req.header('x-auth')!=='none')res.locals={tenantId:req.header('x-tenant')||'tenant',userId:'owner'};next();});app.use('/programs/:programId/topics',createSocialCustomerFeedbackTopicsRouter(f.store));const server=app.listen(0);await new Promise<void>(resolve=>server.once('listening',resolve));const address=server.address() as {port:number};const url=`http://127.0.0.1:${address.port}/programs/program/topics`;try{const source=await fetch(`${url}/sources?sourcePackageId=week&sourcePackageVersion=1`);assert.equal(source.status,200);const data=await source.json();assert.equal(data.items[0].body,'Please send the specification');assert.equal(data.items[0].customerRelationship,'unknown');assert.equal((await fetch(`${url}/sources?sourcePackageId=week&sourcePackageVersion=1`,{headers:{'x-auth':'none'}})).status,401);assert.equal((await fetch(`${url}/sources?sourcePackageId=week&sourcePackageVersion=1`,{headers:{'x-tenant':'foreign'}})).status,403);const{tenantId,programId,actorUserId,...body}=f.args;const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(response.status,201);const created=await response.json();assert.equal((await fetch(`${url}/${created.item.id}`)).status,200);assert.equal((await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,interactionId:'human-reply',excerptEnd:5})})).status,409);assert.equal((await fetch(`${url}/${created.item.id}/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetPackageId:'week',expectedTargetPackageVersion:'1',publicationTaskId:'video'})})).status,400);}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}});
