import { publicationInstant } from './publicationDeadlines.js';
import type {DataStore} from '../storage/datastore.js';
import type {CustomerFeedbackTopicCandidate,CustomerFeedbackTopicConfirmation} from '../../shared/contracts/socialCustomerFeedbackTopic.js';
import type {WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import {createWeeklySalesHandoffService,SALES_HANDOFFS,SALES_EVENTS} from '../runtime/socialWeeklySalesHandoff.js';
import {socialJson,socialObject,socialRequestHash} from '../starter198/socialContentValidation.js';import {organizationRoleOrNull} from '../lib/organizationRole.js';import {SocialProgramError} from './service.js';
export const FEEDBACK_TOPIC_CANDIDATES='social_customer_feedback_topic_candidates';export const FEEDBACK_TOPIC_CONFIRMATIONS='social_customer_feedback_topic_confirmations';
const fail=(code:string,status=409):never=>{throw new SocialProgramError(code,status,code);};
const obj=(v:unknown)=>socialObject(socialJson(v));
async function user(store:DataStore,tenantId:string,id:string,operator=false){const u=await store.getById<Record<string,unknown>>('users',id);const role=organizationRoleOrNull(u?.role);if(!u||u.tenantId!==tenantId||!role||u.disabled===true||u.active===false||['disabled','suspended'].includes(String(u.status))||operator&&!['super_admin','admin','social_operator'].includes(role))fail('customer_feedback_topic_forbidden',403);}
async function uniqueRows(store:DataStore,collection:string,where:Record<string,string|number>){const r=await store.list<any>(collection,{where,perPage:2});if(r.totalItems!==1||r.items.length!==1)fail('customer_feedback_topic_evidence_not_unique');return r.items[0]!;}
async function pkg(store:DataStore,tenantId:string,programId:string,packageId:string,version:number){const row=await uniqueRows(store,'social_weekly_operating_packages',{tenant_id:tenantId,program_id:programId,package_id:packageId,version});const p=obj(row.payload) as unknown as WeeklyOperatingPackage|null;if(!p||p.packageId!==packageId||p.programId!==programId||p.version!==version||typeof p.weekStart!=='string'||typeof p.weekEnd!=='string'||publicationInstant(`${p.weekStart}T00:00:00Z`)===null||publicationInstant(`${p.weekEnd}T00:00:00Z`)===null||p.weekEnd<p.weekStart)fail('customer_feedback_topic_package_invalid');return p!;}
async function buyerInteraction(store:DataStore,tenantId:string,customerId:string,id:string){const row=await uniqueRows(store,'whatsapp_interactions',{tenant_id:tenantId,customer_id:customerId,interaction_id:id});const p=obj(row.payload);if(!p||p.id!==id||p.tenantId!==tenantId||p.customerId!==customerId||p.type!=='msg_in'||typeof p.body!=='string'||!p.body.trim()||typeof p.timestamp!=='number'||!Number.isFinite(p.timestamp)||p.timestamp<=0||p.mock||p.synthetic||p.simulated||obj(p.audit)?.mock||obj(p.meta)?.synthetic)fail('customer_feedback_topic_buyer_message_required');return p!;}
async function immutable<T extends {id:string;recordHash:string}>(store:DataStore,collection:string,item:T,metadata:Record<string,unknown>){const old=await store.getById<any>(collection,item.id);if(old){if(old.record_hash!==item.recordHash||socialRequestHash(obj(old.payload))!==socialRequestHash(item))fail('customer_feedback_topic_replay_conflict');return item;}try{const saved=await store.create(collection,{id:item.id,...metadata,record_hash:item.recordHash,payload:item});if(!saved)throw Error('write_failed');}catch(error){const concurrent=await store.getById<any>(collection,item.id);if(!concurrent||concurrent.record_hash!==item.recordHash||socialRequestHash(obj(concurrent.payload))!==socialRequestHash(item))throw error;}return item;}
async function scanRows(store:DataStore,collection:string,where:Record<string,string|number>){const all:any[]=[];const seen=new Set<string>();let count:number|undefined;for(let page=1;page<=1000;page++){const r=await store.list<any>(collection,{where,page,perPage:250,sort:'id'});if(!Number.isSafeInteger(r.totalItems)||r.totalItems<0||count!==undefined&&count!==r.totalItems)fail('customer_feedback_topic_pagination_changed');count=r.totalItems;for(const row of r.items){if(!row?.id||seen.has(row.id))fail('customer_feedback_topic_pagination_duplicate');seen.add(row.id);all.push(row);}if(all.length===count)return all;if(!r.items.length)fail('customer_feedback_topic_pagination_incomplete');}return fail('customer_feedback_topic_pagination_incomplete');}
export function createCustomerFeedbackTopicService(store:DataStore){const sales=createWeeklySalesHandoffService(store);
 const candidate=async(tenantId:string,programId:string,id:string,actor:string):Promise<CustomerFeedbackTopicCandidate>=>{await user(store,tenantId,actor);const row=await store.getById<any>(FEEDBACK_TOPIC_CANDIDATES,id);const c=obj(row?.payload) as unknown as CustomerFeedbackTopicCandidate|null;if(!row||!c||row.tenant_id!==tenantId||row.program_id!==programId||c.tenantId!==tenantId||c.programId!==programId||c.id!==id||c.schemaVersion!=='customer-feedback-topic.v1'||row.record_hash!==c.recordHash)fail('customer_feedback_topic_not_found',404);const{recordHash,...payload}=c!;if(socialRequestHash(payload)!==recordHash)fail('customer_feedback_topic_corrupt');
  // The actor must retain actual permission to the source conversation, including during confirmation.
  await sales.get({tenantId,programId,packageId:c!.source.packageId,packageVersion:c!.source.packageVersion},c!.source.handoffId,actor);
  const base=await store.getById<any>(SALES_HANDOFFS,c!.source.handoffId);if(!base||base.tenant_id!==tenantId||socialRequestHash(obj(base.payload))!==c!.source.handoffBaseHash)fail('customer_feedback_topic_source_changed');const event=await store.getById<any>(SALES_EVENTS,c!.source.feedbackEventId);const ep=obj(event?.payload);if(!event||event.tenant_id!==tenantId||event.handoff_id!==c!.source.handoffId||event.version!==c!.source.handoffVersion||socialRequestHash(ep)!==c!.source.feedbackEventHash||!obj(ep?.feedback))fail('customer_feedback_topic_feedback_changed');
  const message=await buyerInteraction(store,tenantId,c!.source.customerId,c!.source.interactionId);if(socialRequestHash(message)!==c!.source.interactionHash||message.body!==c!.source.body||c!.source.question!==c!.source.body.slice(c!.source.excerptStart,c!.source.excerptEnd)||c!.attributionConclusion!=='not_measured')fail('customer_feedback_topic_question_changed');return c!;};
 return {get:candidate,
 async sources(input:{tenantId:string;programId:string;actorUserId:string;sourcePackageId:string;sourcePackageVersion:number}){await user(store,input.tenantId,input.actorUserId);const authority={tenantId:input.tenantId,programId:input.programId,packageId:input.sourcePackageId,packageVersion:input.sourcePackageVersion};const handoffs=(await sales.list(authority,input.actorUserId)).filter(h=>h.packageId===input.sourcePackageId&&h.packageVersion===input.sourcePackageVersion&&h.feedback&&['handled','needs_information'].includes(h.status));const items:Array<{sourcePackageId:string;sourcePackageVersion:number;handoffId:string;handoffVersion:number;interactionId:string;customerId:string;body:string;timestamp:number;customerRelationship:'new_inquiry'|'existing_customer'|'unknown'}>=[];const gaps:Array<{handoffId:string;interactionId:string;code:string}>=[];for(const h of handoffs){for(const id of new Set([h.sourceInteractionId,...h.feedback!.evidenceInteractionIds])){try{const message=await buyerInteraction(store,input.tenantId,h.customerId,id);items.push({sourcePackageId:h.packageId,sourcePackageVersion:h.packageVersion,handoffId:h.id,handoffVersion:h.version,interactionId:id,customerId:h.customerId,body:String(message.body),timestamp:Number(message.timestamp),customerRelationship:'unknown'});}catch(error){gaps.push({handoffId:h.id,interactionId:id,code:error instanceof SocialProgramError?error.code:'customer_feedback_topic_source_unavailable'});}}}return{items,gaps};},
 async list(input:{tenantId:string;programId:string;actorUserId:string}){await user(store,input.tenantId,input.actorUserId);const rows=await scanRows(store,FEEDBACK_TOPIC_CANDIDATES,{tenant_id:input.tenantId,program_id:input.programId});const items:CustomerFeedbackTopicCandidate[]=[];const gaps:Array<{id:string;code:string}>=[];for(const row of rows){try{items.push(await candidate(input.tenantId,input.programId,row.id,input.actorUserId));}catch(error){if(error instanceof SocialProgramError&&error.status===403)continue;gaps.push({id:row.id,code:error instanceof SocialProgramError?error.code:'customer_feedback_topic_source_unavailable'});}}return{items,gaps};},
 async confirmations(input:{tenantId:string;programId:string;actorUserId:string}){await user(store,input.tenantId,input.actorUserId,true);const rows=await scanRows(store,FEEDBACK_TOPIC_CONFIRMATIONS,{tenant_id:input.tenantId,program_id:input.programId});const items:CustomerFeedbackTopicConfirmation[]=[];const gaps:Array<{id:string;code:string}>=[];for(const row of rows){try{const r=obj(row.payload) as unknown as CustomerFeedbackTopicConfirmation|null;if(!r||r.id!==row.id||r.tenantId!==input.tenantId||r.programId!==input.programId||r.schemaVersion!=='customer-feedback-topic-confirmation.v1')fail('customer_feedback_topic_confirmation_corrupt');const{recordHash,...payload}=r!;if(recordHash!==socialRequestHash(payload)||row.record_hash!==recordHash)fail('customer_feedback_topic_confirmation_corrupt');const c=await candidate(input.tenantId,input.programId,r!.candidateRef.id,input.actorUserId);if(c.recordHash!==r!.candidateRef.recordHash)fail('customer_feedback_topic_confirmation_corrupt');items.push(r!);}catch(error){if(error instanceof SocialProgramError&&error.status===403)continue;gaps.push({id:row.id,code:error instanceof SocialProgramError?error.code:'customer_feedback_topic_source_unavailable'});}}return{items,gaps};},
 async create(input:{tenantId:string;programId:string;actorUserId:string;sourcePackageId:string;sourcePackageVersion:number;handoffId:string;interactionId:string;excerptStart:number;excerptEnd:number;topicAngle:string}){await user(store,input.tenantId,input.actorUserId);const p=await pkg(store,input.tenantId,input.programId,input.sourcePackageId,input.sourcePackageVersion);const handoff=await sales.get({tenantId:input.tenantId,programId:input.programId,packageId:p.packageId,packageVersion:p.version},input.handoffId,input.actorUserId);if(!handoff.feedback||!['handled','needs_information'].includes(handoff.status))fail('customer_feedback_topic_feedback_required');if(input.interactionId!==handoff.sourceInteractionId&&!handoff.feedback!.evidenceInteractionIds.includes(input.interactionId))fail('customer_feedback_topic_message_not_in_feedback');const message=await buyerInteraction(store,input.tenantId,handoff.customerId,input.interactionId);const body=String(message.body);if(!Number.isSafeInteger(input.excerptStart)||!Number.isSafeInteger(input.excerptEnd)||input.excerptStart<0||input.excerptEnd<=input.excerptStart||input.excerptEnd>body.length||input.excerptEnd-input.excerptStart>2000||!body.slice(input.excerptStart,input.excerptEnd).trim()||typeof input.topicAngle!=='string'||!input.topicAngle.trim()||input.topicAngle.length>1000)fail('customer_feedback_topic_excerpt_invalid',400);
  const base=await store.getById<any>(SALES_HANDOFFS,handoff.id);const event=await uniqueRows(store,SALES_EVENTS,{tenant_id:input.tenantId,handoff_id:handoff.id,version:handoff.version});const ep=obj(event.payload);if(!obj(ep?.feedback)||event.actor_id!==handoff.ownerUserId)fail('customer_feedback_topic_feedback_event_invalid');const source={packageId:p.packageId,packageVersion:p.version,weekStart:p.weekStart,weekEnd:p.weekEnd,handoffId:handoff.id,handoffVersion:handoff.version,handoffBaseHash:socialRequestHash(obj(base?.payload)),feedbackEventId:String(event.id),feedbackEventHash:socialRequestHash(ep),interactionId:input.interactionId,interactionHash:socialRequestHash(message),customerId:handoff.customerId,timestamp:Number(message.timestamp),body,excerptStart:input.excerptStart,excerptEnd:input.excerptEnd,question:body.slice(input.excerptStart,input.excerptEnd),customerRelationship:'unknown' as const};
  const identity={tenantId:input.tenantId,programId:input.programId,source,topicAngle:input.topicAngle.trim(),createdBy:input.actorUserId};const id=socialRequestHash(identity).slice(0,15);const existing=await store.getById<any>(FEEDBACK_TOPIC_CANDIDATES,id);if(existing)return candidate(input.tenantId,input.programId,id,input.actorUserId);const payload={schemaVersion:'customer-feedback-topic.v1' as const,id,version:1 as const,...identity,attributionConclusion:'not_measured' as const,createdAt:new Date().toISOString()};const c={...payload,recordHash:socialRequestHash(payload)};return immutable(store,FEEDBACK_TOPIC_CANDIDATES,c,{tenant_id:input.tenantId,program_id:input.programId,source_package_id:p.packageId,source_package_version:p.version});},
 async proposeNextRevision(input:{tenantId:string;programId:string;actorUserId:string;candidateId:string;targetPackageId:string;expectedTargetPackageVersion:number;publicationTaskId:string}){await user(store,input.tenantId,input.actorUserId,true);const c=await candidate(input.tenantId,input.programId,input.candidateId,input.actorUserId);const p=await pkg(store,input.tenantId,input.programId,input.targetPackageId,input.expectedTargetPackageVersion);const rows=await store.list<any>('social_weekly_operating_packages',{where:{tenant_id:input.tenantId,program_id:input.programId,package_id:p.packageId},perPage:500});if(rows.totalItems>rows.items.length||rows.items.some(r=>Number(r.version)>p.version)||p.status!=='draft'||p.weekStart<=c.source.weekEnd||!p.socialContentPackage?.publicationTasks.some(t=>t.publicationTaskId===input.publicationTaskId&&t.status!=='cancelled'))fail('customer_feedback_topic_next_draft_required');const target={packageId:p.packageId,packageVersion:p.version+1,publicationTaskId:input.publicationTaskId,weekStart:p.weekStart,weekEnd:p.weekEnd};const identity={tenantId:input.tenantId,programId:input.programId,candidateRef:{id:c.id,version:1 as const,recordHash:c.recordHash},target,confirmedBy:input.actorUserId};const id=socialRequestHash(identity).slice(0,15);const existing=await store.getById<any>(FEEDBACK_TOPIC_CONFIRMATIONS,id);if(existing){const old=obj(existing.payload) as unknown as CustomerFeedbackTopicConfirmation|null;if(!old)fail('customer_feedback_topic_confirmation_corrupt');const{recordHash,...payload}=old!;if(recordHash!==socialRequestHash(payload))fail('customer_feedback_topic_confirmation_corrupt');return old!;}
 const payload={schemaVersion:'customer-feedback-topic-confirmation.v1' as const,id,version:1 as const,...identity,status:'pending_next_revision' as const,confirmedAt:new Date().toISOString()};return immutable(store,FEEDBACK_TOPIC_CONFIRMATIONS,{...payload,recordHash:socialRequestHash(payload)},{tenant_id:input.tenantId,program_id:input.programId,target_package_id:p.packageId,target_package_version:p.version+1,publication_task_id:input.publicationTaskId});},
 async verifiedPlanningReference(input:{tenantId:string;programId:string;pkg:WeeklyOperatingPackage;publicationTaskId:string;ref:VersionedSocialRef}){if(input.ref.type!=='customer_feedback_topic_confirmation'||input.ref.version!==1)fail('customer_feedback_topic_ref_invalid');const row=await store.getById<any>(FEEDBACK_TOPIC_CONFIRMATIONS,input.ref.id);const r=obj(row?.payload) as unknown as CustomerFeedbackTopicConfirmation|null;if(!row||!r||row.tenant_id!==input.tenantId||row.program_id!==input.programId||r.tenantId!==input.tenantId||r.programId!==input.programId||r.id!==input.ref.id||r.version!==1||r.status!=='pending_next_revision')fail('customer_feedback_topic_confirmation_missing');const{recordHash,...payload}=r!;if(recordHash!==socialRequestHash(payload)||row.record_hash!==recordHash||r!.target.packageId!==input.pkg.packageId||r!.target.packageVersion!==input.pkg.version||r!.target.publicationTaskId!==input.publicationTaskId||r!.target.weekStart!==input.pkg.weekStart||r!.target.weekEnd!==input.pkg.weekEnd)fail('customer_feedback_topic_target_invalid');await user(store,input.tenantId,r!.confirmedBy,true);const actual=await pkg(store,input.tenantId,input.programId,input.pkg.packageId,input.pkg.version);const publication=actual.socialContentPackage.publicationTasks.find(t=>t.publicationTaskId===input.publicationTaskId);if(!publication||socialRequestHash(publication.customerFeedbackTopicRef)!==socialRequestHash(input.ref))fail('customer_feedback_topic_not_frozen');const c=await candidate(input.tenantId,input.programId,r!.candidateRef.id,r!.confirmedBy);if(c.recordHash!==r!.candidateRef.recordHash||input.pkg.weekStart<=c.source.weekEnd)fail('customer_feedback_topic_source_week_invalid');return {candidate:c,confirmation:r!};}
 };
}
