import type {DataStore} from '../storage/datastore.js';
import type {WeeklyMaterialEvidenceConfiguration,WeeklyAgentPlanningState} from '../../shared/contracts/socialProgram.js';
import type {SocialInspirationHandoff} from '../../shared/contracts/socialContentWorkflow.js';
import {socialJson,socialObject,socialRequestHash} from '../starter198/socialContentValidation.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {SocialProgramError} from './service.js';
import {classifyMaterialEvidence} from './materialEvidenceClassification.js';
export const MATERIAL_EVIDENCE_CONFIGURATIONS='social_weekly_material_evidence_configurations';
type Scope=WeeklyMaterialEvidenceConfiguration['scope'];
type Ref=WeeklyMaterialEvidenceConfiguration['handoffRef'];
const fail=(code:string,status=409):never=>{throw new SocialProgramError(code,status,'素材分类配置与当前冻结来源或计划版本不一致，请刷新并逐项确认。');};
async function authorized(store:DataStore,tenantId:string,userId:string){const u=await store.getById<Record<string,unknown>>('users',userId);if(!u||u.tenantId!==tenantId||!['super_admin','admin','social_operator'].includes(organizationRoleOrNull(u.role)??'')||u.disabled===true||u.status==='disabled')fail('material_evidence_configuration_forbidden',403);}
export async function readMaterialEvidenceConfiguration(store:DataStore,input:{tenantId:string;programId:string;scope:Scope;handoffRef:Ref;ref:{id:string;version:number;recordHash:string}}):Promise<WeeklyMaterialEvidenceConfiguration|null>{
 const row=await store.getById<any>(MATERIAL_EVIDENCE_CONFIGURATIONS,input.ref.id);const c=socialObject(socialJson(row?.payload)) as unknown as WeeklyMaterialEvidenceConfiguration|null;
 if(!row||!c||row.tenant_id!==input.tenantId||row.program_id!==input.programId||c.tenantId!==input.tenantId||c.programId!==input.programId||c.configurationId!==row.id||c.configurationId!==input.ref.id||c.version!==input.ref.version||c.recordHash!==input.ref.recordHash||row.record_hash!==c.recordHash||socialRequestHash(c.scope)!==socialRequestHash(input.scope)||socialRequestHash(c.handoffRef)!==socialRequestHash(input.handoffRef)||c.schemaVersion!=='weekly-material-evidence-configuration.v1')return null;
 const{recordHash,...payload}=c;if(socialRequestHash(payload)!==recordHash)return null;
 try{await authorized(store,input.tenantId,c.configuredBy);}catch{return null;}return c;
}
export async function latestMaterialEvidenceConfiguration(store:DataStore,input:{tenantId:string;programId:string;scope:Scope;handoffRef:Ref}):Promise<WeeklyMaterialEvidenceConfiguration|null>{
 const rows=await store.list<any>(MATERIAL_EVIDENCE_CONFIGURATIONS,{where:{tenant_id:input.tenantId,program_id:input.programId,package_id:input.scope.packageId,package_version:input.scope.packageVersion,slot_id:input.scope.slotId,source_hash:input.handoffRef.recordHash},perPage:100});if(rows.totalItems>rows.items.length)fail('material_evidence_configuration_scan_incomplete');
 const entries=rows.items.map(r=>socialObject(socialJson(r.payload)) as unknown as WeeklyMaterialEvidenceConfiguration|null).filter((c):c is WeeklyMaterialEvidenceConfiguration=>Boolean(c&&Number.isSafeInteger(c.version)&&c.version>0)).sort((a,b)=>b.version-a.version);if(!entries.length)return null;if(entries[1]?.version===entries[0]!.version)fail('material_evidence_configuration_ambiguous');const c=entries[0]!;
 const verified=await readMaterialEvidenceConfiguration(store,{...input,ref:{id:c.configurationId,version:c.version,recordHash:c.recordHash}});if(!verified)fail('material_evidence_configuration_storage_invalid');return verified;
}
export async function saveMaterialEvidenceConfiguration(store:DataStore,input:{tenantId:string;programId:string;scope:Scope;actorUserId:string;expectedPlanningVersion:number;decisions:WeeklyMaterialEvidenceConfiguration['decisions'];now?:Date}):Promise<WeeklyMaterialEvidenceConfiguration>{
 if(!input.tenantId||!input.programId||!input.scope.packageId?.trim()||!input.scope.slotId?.trim()||!Number.isSafeInteger(input.scope.packageVersion)||input.scope.packageVersion<1||!Array.isArray(input.decisions)||!input.decisions.length||input.decisions.length>100)fail('material_evidence_configuration_invalid',400);
 await authorized(store,input.tenantId,input.actorUserId);if(!Number.isSafeInteger(input.expectedPlanningVersion)||input.expectedPlanningVersion<1)fail('material_evidence_configuration_version_required',400);
 const load=async()=>{const rows=await store.list<any>('social_weekly_agent_planning',{where:{tenant_id:input.tenantId,program_id:input.programId,package_id:input.scope.packageId,package_version:input.scope.packageVersion},perPage:500});if(rows.totalItems>rows.items.length)fail('material_evidence_configuration_plan_scan_incomplete');const states=rows.items.map(r=>socialObject(socialJson(r.payload)) as unknown as WeeklyAgentPlanningState|null).filter((p):p is WeeklyAgentPlanningState=>Boolean(p&&Number.isSafeInteger(p.version))).sort((a,b)=>b.version-a.version);const p=states[0];if(!p||p.version!==input.expectedPlanningVersion||['confirmed','dispatched'].includes(p.status))fail('material_evidence_configuration_plan_not_editable');return p!;};
 const p=await load();const analysis=p.directorAnalyses.find(a=>a.slotId===input.scope.slotId);const base=analysis?.materialEvidenceRequirements;if(!base?.handoffRef||!base.source||base.scope.packageId!==input.scope.packageId||base.scope.packageVersion!==input.scope.packageVersion)fail('material_evidence_configuration_source_required');
 const refs=base!.handoffRef!;const rows=await store.list<any>('starter_social_inspiration_handoff_versions',{where:{tenant_id:input.tenantId,handoff_version:refs.version,record_hash:refs.recordHash},perPage:2});const actual=rows.items.map(r=>socialJson(r.payload) as SocialInspirationHandoff).filter(h=>h?.inspirationId===refs.inspirationId&&socialRequestHash(h)===refs.recordHash);if(rows.totalItems>rows.items.length||actual.length!==1)fail('material_evidence_configuration_source_missing');
 let decisions=structuredClone(input.decisions);
 if(base!.configurationRef){const priorConfiguration=await readMaterialEvidenceConfiguration(store,{tenantId:input.tenantId,programId:input.programId,scope:input.scope,handoffRef:refs,ref:base!.configurationRef});if(!priorConfiguration)fail('material_evidence_configuration_prior_invalid');decisions=[...priorConfiguration!.decisions.filter(d=>!decisions.some(next=>next.requirementId===d.requirementId)),...decisions];}
 const version=input.expectedPlanningVersion;const configurationId=socialRequestHash({tenantId:input.tenantId,programId:input.programId,scope:input.scope,version}).slice(0,15);
 const prior=await store.getById<any>(MATERIAL_EVIDENCE_CONFIGURATIONS,configurationId);if(prior){const c=await readMaterialEvidenceConfiguration(store,{tenantId:input.tenantId,programId:input.programId,scope:input.scope,handoffRef:refs,ref:{id:configurationId,version,recordHash:String(prior.record_hash)}});if(!c||socialRequestHash(c.decisions)!==socialRequestHash(decisions)||c.configuredBy!==input.actorUserId)fail('material_evidence_configuration_conflict');return c!;}
 const configuredAt=(input.now??new Date()).toISOString();const payload={schemaVersion:'weekly-material-evidence-configuration.v1' as const,configurationId,version,tenantId:input.tenantId,programId:input.programId,scope:structuredClone(input.scope),handoffRef:refs,decisions,configuredBy:input.actorUserId,configuredAt};const config={...payload,recordHash:socialRequestHash(payload)};
 try{classifyMaterialEvidence({scope:input.scope,handoff:actual[0],handoffRef:refs,configuration:config});}catch{fail('material_evidence_configuration_boundary_invalid',400);}
 await load();try{const saved=await store.create(MATERIAL_EVIDENCE_CONFIGURATIONS,{id:configurationId,tenant_id:input.tenantId,program_id:input.programId,package_id:input.scope.packageId,package_version:input.scope.packageVersion,slot_id:input.scope.slotId,configuration_version:version,source_hash:refs.recordHash,record_hash:config.recordHash,payload:config});if(!saved)throw Error('configuration_write_conflict');}catch{const concurrent=await store.getById<any>(MATERIAL_EVIDENCE_CONFIGURATIONS,configurationId);const c=await readMaterialEvidenceConfiguration(store,{tenantId:input.tenantId,programId:input.programId,scope:input.scope,handoffRef:refs,ref:{id:configurationId,version,recordHash:String(concurrent?.record_hash)}});if(!c||socialRequestHash(c.decisions)!==socialRequestHash(config.decisions)||c.configuredBy!==config.configuredBy)fail('material_evidence_configuration_conflict');return c!;}return config;
}
