import test from 'node:test';import assert from 'node:assert/strict';
import type {DataStore,Record_,ListQuery} from '../storage/datastore.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {classifyMaterialEvidence,verifyMaterialEvidenceRequirements} from './materialEvidenceClassification.js';
import {saveMaterialEvidenceConfiguration,readMaterialEvidenceConfiguration,latestMaterialEvidenceConfiguration,MATERIAL_EVIDENCE_CONFIGURATIONS} from './materialEvidenceConfiguration.js';
function memory(): DataStore {
  const data = new Map<string, Record_[]>();
  return {
    async getById<T>(c: string, id: string) { return structuredClone(data.get(c)?.find(r => r.id === id) ?? null) as T | null; },
    async list<T>(c: string, q: ListQuery = {}) { const rows = (data.get(c) ?? []).filter(r => Object.entries(q.where ?? {}).every(([k,v]) => r[k] === v)); return { items: structuredClone(rows) as T[], totalItems: rows.length, totalPages: 1, page: 1, perPage: q.perPage ?? 30 }; },
    async create<T>(c: string, d: Record<string, unknown>) { const rows = data.get(c) ?? []; if(d.id&&rows.some(r=>r.id===d.id)) return null as T; const row = { id: `${c}-${rows.length}`, ...structuredClone(d) }; data.set(c, [...rows, row]); return structuredClone(row) as T; },
    async update(c: string, id: string, d: Record<string, unknown>) { const row = data.get(c)?.find(r => r.id === id); if (!row) return false; Object.assign(row, structuredClone(d)); return true; },
    async delete(c: string, id: string) { data.set(c,(data.get(c) ?? []).filter(r => r.id !== id)); return true; },
  };
}

async function fixture(){const store=memory();const scope={packageId:'pack',packageVersion:1,slotId:'slot'};const h:any={inspirationId:'video',version:'1',analysisVersion:'1',readiness:'production_reference',rights:{mayAnalyze:true,mayAdapt:true},productionImplications:{requiredEvidence:['产品细节镜头'],likelyAssetNeeds:[]},adaptationBoundary:{reusable:[],mustReplace:[],prohibited:[]}};const ref={inspirationId:'video',version:'1',recordHash:socialRequestHash(h)};const base=classifyMaterialEvidence({scope,handoff:h,handoffRef:ref});await store.create('users',{id:'operator',tenantId:'tenant',role:'social_operator'});await store.create('starter_social_inspiration_handoff_versions',{tenant_id:'tenant',handoff_version:'1',record_hash:ref.recordHash,payload:h});const plan:any={version:2,status:'director_analyzing',directorAnalyses:[{slotId:'slot',materialEvidenceRequirements:base}]};const row:any=await store.create('social_weekly_agent_planning',{tenant_id:'tenant',program_id:'program',package_id:'pack',package_version:1,payload:plan});const args={tenantId:'tenant',programId:'program',scope,actorUserId:'operator',expectedPlanningVersion:2,decisions:[{requirementId:base.items[0]!.requirementId,classification:'human_irreplaceable' as const,reason:'客户确认需展示自有产品',shotUsage:'中段产品细节实拍'}],now:new Date('2026-10-09T00:00:00Z')};return{store,scope,h,ref,base,plan,row,args};}
test('explicit human intent saves immutable evidence and reanalysis binds actual configuration',async()=>{const f=await fixture();const c=await saveMaterialEvidenceConfiguration(f.store,f.args);assert.deepEqual(await saveMaterialEvidenceConfiguration(f.store,f.args),c);assert.deepEqual(await latestMaterialEvidenceConfiguration(f.store,{tenantId:'tenant',programId:'program',scope:f.scope,handoffRef:f.ref}),c);const resolved=classifyMaterialEvidence({scope:f.scope,handoff:f.h,handoffRef:f.ref,configuration:c});assert.equal(resolved.items[0]!.classification,'human_irreplaceable');assert.equal(verifyMaterialEvidenceRequirements(resolved,f.scope,[f.ref],f.h),false);assert.equal(verifyMaterialEvidenceRequirements(resolved,f.scope,[f.ref],f.h,c),true);assert.equal(f.plan.directorAnalyses[0].materialEvidenceRequirements.items[0].classification,'unknown');});
test('labels cannot expand AI boundaries or resolve missing analysis',async()=>{const f=await fixture();await assert.rejects(saveMaterialEvidenceConfiguration(f.store,{...f.args,decisions:[{...f.args.decisions[0]!,classification:'generatable_non_evidentiary' as any}]}),/素材分类配置/);await assert.rejects(saveMaterialEvidenceConfiguration(f.store,{...f.args,decisions:[{...f.args.decisions[0]!,requirementId:'missing'}]}));f.plan.directorAnalyses[0].materialEvidenceRequirements=classifyMaterialEvidence({scope:f.scope});await f.store.update('social_weekly_agent_planning',f.row.id,{payload:f.plan});await assert.rejects(saveMaterialEvidenceConfiguration(f.store,f.args));});
test('tenant authorization, stale planning and confirmed plans cannot save configuration',async()=>{const f=await fixture();await assert.rejects(saveMaterialEvidenceConfiguration(f.store,{...f.args,tenantId:'other'}));await assert.rejects(saveMaterialEvidenceConfiguration(f.store,{...f.args,expectedPlanningVersion:1}));f.plan.status='dispatched';await f.store.update('social_weekly_agent_planning',f.row.id,{payload:f.plan});await assert.rejects(saveMaterialEvidenceConfiguration(f.store,f.args));});
test('conflicting concurrent intent never overwrites immutable configuration',async()=>{const f=await fixture();const c=await saveMaterialEvidenceConfiguration(f.store,f.args);await assert.rejects(saveMaterialEvidenceConfiguration(f.store,{...f.args,decisions:[{...f.args.decisions[0]!,reason:'另一项不同承诺'}]}));assert.equal((await f.store.list(MATERIAL_EVIDENCE_CONFIGURATIONS)).totalItems,1);assert.equal((await readMaterialEvidenceConfiguration(f.store,{tenantId:'tenant',programId:'program',scope:f.scope,handoffRef:f.ref,ref:{id:c.configurationId,version:c.version,recordHash:c.recordHash}}))?.recordHash,c.recordHash);});
test('trusted lookup rejects malicious payload, changed scope and actor authorization',async()=>{const f=await fixture();const c=await saveMaterialEvidenceConfiguration(f.store,f.args);const input={tenantId:'tenant',programId:'program',scope:f.scope,handoffRef:f.ref,ref:{id:c.configurationId,version:c.version,recordHash:c.recordHash}};assert.equal(await readMaterialEvidenceConfiguration(f.store,{...input,scope:{...f.scope,packageVersion:2}}),null);await f.store.update('users','operator',{disabled:true});assert.equal(await readMaterialEvidenceConfiguration(f.store,input),null);await f.store.update(MATERIAL_EVIDENCE_CONFIGURATIONS,c.configurationId,{payload:null});assert.equal(await readMaterialEvidenceConfiguration(f.store,input),null);});

test('parallel conflicting configurations preserve a single authority row',async()=>{const f=await fixture();const results=await Promise.allSettled([saveMaterialEvidenceConfiguration(f.store,f.args),saveMaterialEvidenceConfiguration(f.store,{...f.args,decisions:[{...f.args.decisions[0]!,reason:'另一项承诺'}]})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await f.store.list(MATERIAL_EVIDENCE_CONFIGURATIONS)).totalItems,1);});
test('subsequent partial configuration retains earlier verified human decisions',async()=>{const f=await fixture();f.h.productionImplications.requiredEvidence.push('设备镜头');const ref={...f.ref,recordHash:socialRequestHash(f.h)};await f.store.create('starter_social_inspiration_handoff_versions',{tenant_id:'tenant',handoff_version:'1',record_hash:ref.recordHash,payload:f.h});const base=classifyMaterialEvidence({scope:f.scope,handoff:f.h,handoffRef:ref});f.plan.directorAnalyses[0].materialEvidenceRequirements=base;await f.store.update('social_weekly_agent_planning',f.row.id,{payload:f.plan});const first=await saveMaterialEvidenceConfiguration(f.store,{...f.args,decisions:[{...f.args.decisions[0]!,requirementId:base.items[0]!.requirementId}]});f.plan.version=3;f.plan.directorAnalyses[0].materialEvidenceRequirements=classifyMaterialEvidence({scope:f.scope,handoff:f.h,handoffRef:ref,configuration:first});await f.store.update('social_weekly_agent_planning',f.row.id,{payload:f.plan});const second=await saveMaterialEvidenceConfiguration(f.store,{...f.args,expectedPlanningVersion:3,decisions:[{...f.args.decisions[0]!,requirementId:base.items[1]!.requirementId,shotUsage:'设备特写'}]});assert.equal(second.decisions.length,2);assert.deepEqual(classifyMaterialEvidence({scope:f.scope,handoff:f.h,handoffRef:ref,configuration:second}).items.map(i=>i.classification),['human_irreplaceable','human_irreplaceable']);});
