import test from 'node:test';import assert from 'node:assert/strict';
import type {SocialInspirationHandoff} from '../../shared/contracts/socialContentWorkflow.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {classifyMaterialEvidence,verifyMaterialEvidenceRequirements,materialEvidenceRequiresConfiguration} from './materialEvidenceClassification.js';
const scope={packageId:'pack',packageVersion:1,slotId:'slot'};
const handoff={inspirationId:'video',version:'1',analysisVersion:'1',readiness:'production_reference',rights:{mayAnalyze:true,mayAdapt:true},productionImplications:{requiredEvidence:['真实产品实拍证据'],likelyAssetNeeds:['AI纯装饰非证据背景','细节镜头']},adaptationBoundary:{reusable:['结构'],mustReplace:['产品事实'],prohibited:[]}} as unknown as SocialInspirationHandoff;
const ref={inspirationId:'video',version:'1',recordHash:socialRequestHash(handoff)};
test('actual evidence is classified individually; unknown and human never acquire AI fallback',()=>{const c=classifyMaterialEvidence({scope,handoff,handoffRef:ref});assert.deepEqual(c.items.map(i=>i.classification),['human_irreplaceable','generatable_non_evidentiary','unknown']);assert.equal(materialEvidenceRequiresConfiguration(c),true);assert.equal(verifyMaterialEvidenceRequirements(c,scope,[ref],handoff),true);});
test('scope and actual source hash fence drift and classification forgery',()=>{const c=classifyMaterialEvidence({scope,handoff,handoffRef:ref});assert.equal(verifyMaterialEvidenceRequirements(c,{...scope,packageVersion:2},[ref],handoff),false);assert.equal(verifyMaterialEvidenceRequirements(c,scope,[ref]),false);const forged=structuredClone(c);forged.items[0]!.classification='generatable_non_evidentiary';const{recordHash,...payload}=forged;forged.recordHash=socialRequestHash(payload);assert.equal(verifyMaterialEvidenceRequirements(forged,scope,[ref],handoff),false);assert.equal(verifyMaterialEvidenceRequirements(c,scope,[ref],{...handoff,productionImplications:{...handoff.productionImplications,requiredEvidence:[]}}),false);});
test('missing or empty handoff requires explicit configuration, never fabricated factory evidence',()=>{for(const input of [{scope},{scope,handoff:{...handoff,productionImplications:{...handoff.productionImplications,requiredEvidence:[],likelyAssetNeeds:[]}},handoffRef:ref}]){const c=classifyMaterialEvidence(input);assert.equal(c.items[0]!.classification,'unknown');assert.equal(materialEvidenceRequiresConfiguration(c),true);assert.doesNotMatch(c.items[0]!.description,/工厂/);}});

test('source requirement identities survive explicit week revision while the scoped contract changes',()=>{const a=classifyMaterialEvidence({scope,handoff,handoffRef:ref});const next={...scope,packageVersion:2,slotId:'another-slot'};const b=classifyMaterialEvidence({scope:next,handoff,handoffRef:ref});assert.deepEqual(a.items.map(i=>i.requirementId),b.items.map(i=>i.requirementId));assert.notEqual(a.recordHash,b.recordHash);assert.equal(verifyMaterialEvidenceRequirements(a,next,[ref],handoff),false);const changed={...handoff,productionImplications:{...handoff.productionImplications,requiredEvidence:['真实工厂实拍证据']}};const c=classifyMaterialEvidence({scope:next,handoff:changed,handoffRef:{...ref,recordHash:socialRequestHash(changed)}});assert.notEqual(a.items[0]!.requirementId,c.items[0]!.requirementId);});
