import {readWeeklyQueueSchedulingEvidence} from './weeklyQueueSchedulingEvidence.js';
import {createWeeklyExecutionContinuationService,weeklyContinuationInputHash} from './weeklyExecutionContinuations.js';
import {withExecutionPackageGate,freezeExecutionPackage} from './weeklyExecutionGate.js';
import {randomUUID} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {acquireDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
import type {WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import type {WeeklyScheduleCapacityInput,WeeklyScheduleProposal,WeeklyScheduleSnapshot,WeeklyScheduleConfirmation,WeeklyScheduledPackage} from '../../shared/contracts/socialWeeklyScheduleRevision.js';
import {SocialProgramError} from './service.js';
import {latestPackageRow} from './weeklyOperatingPackageSupport.js';
import {listWeeklyExecutionTasks,materializeWeeklyExecutionTasks} from './executionTasks.js';
import {createWeeklyOperatingPackageService} from './weeklyOperatingPackages.js';
import {createWeeklyMaterialRequestService} from './weeklyMaterialRequests.js';
import {planWeeklyBackwardSchedule} from './weeklyBackwardSchedule.js';
import {publicationInstant} from './publicationDeadlines.js';
import {SCHEDULE_PROPOSALS,SCHEDULE_SNAPSHOTS,scheduleHash,scheduleTaskSignature,scheduleStable} from './weeklyScheduleSnapshots.js';
interface Scope{tenantId:string;programId:string;packageId:string;packageVersion:number;actorUserId:string;}
interface Ports{now?:()=>string;revise?:(a:Scope,ref:VersionedSocialRef)=>Promise<WeeklyOperatingPackage>;}
function fail(code:string,status=409):never{throw new SocialProgramError(code,status,code);}
async function rows(store:DataStore,collection:string,where:Record<string,string|number>){const all:Record_[]=[],seen=new Set<string>();let total:number|undefined;for(let page=1;;page++){const r=await store.list<Record_>(collection,{where,page,perPage:250,sort:'id'});if(!Number.isSafeInteger(r.totalPages)||!Number.isSafeInteger(r.totalItems)||r.totalItems<0||total!==undefined&&total!==r.totalItems)fail('weekly_schedule_pagination_invalid');total=r.totalItems;for(const item of r.items){if(seen.has(item.id))fail('weekly_schedule_pagination_duplicate');seen.add(item.id);all.push(item);}if(page>=r.totalPages){if(all.length!==r.totalItems)fail('weekly_schedule_pagination_truncated');return all;}if(!r.items.length)fail('weekly_schedule_pagination_truncated');}}
export function createWeeklyScheduleRevisionService(store:DataStore,ports:Ports={}){
 const continuations=createWeeklyExecutionContinuationService(store);
 async function finalizeOldAuthorization(a:Scope,snapshot:WeeklyScheduleSnapshot){
  const previous=await store.list<Record_>('social_weekly_operating_packages',{where:{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.packageVersion},perPage:2});
  if(previous.totalItems!==1||previous.items.length!==1)fail('weekly_schedule_previous_package_missing');
  const row=previous.items[0]!,pkg=row.payload as WeeklyOperatingPackage;
  if(snapshot.previousPublishingAuthorizationAllowed&&pkg.socialContentPackage.authorization.allowRealPublishing){const timestamp=now();const next={...pkg,socialContentPackage:{...pkg.socialContentPackage,authorization:{...pkg.socialContentPackage.authorization,allowRealPublishing:false,revokedBy:a.actorUserId,revokedAt:timestamp}},updatedAt:timestamp};if(!await store.update('social_weekly_operating_packages',row.id,{payload:next,updated_by:a.actorUserId,updated_at:timestamp}))fail('weekly_schedule_previous_authorization_revoke_failed',503);}
  return snapshot.previousPublishingAuthorizationAllowed;
 }
 const now=()=>{const value=ports.now?.()??new Date().toISOString();if(publicationInstant(value)===null)fail('weekly_schedule_clock_invalid',500);return value;};
 async function authority(a:Scope){const user=await store.getById<Record_>('users',a.actorUserId);if(!user||user.tenantId!==a.tenantId||!organizationRoleOrNull(user.role)||user.disabled===true||user.active===false||['disabled','suspended'].includes(String(user.status)))fail('weekly_schedule_user_forbidden',403);if(!Number.isSafeInteger(a.packageVersion)||a.packageVersion<1)fail('weekly_schedule_version_invalid',400);}
 async function input(a:Scope){await authority(a);const pkg=await latestPackageRow(store,a.tenantId,a.programId,a.packageId);if(!pkg)fail('weekly_schedule_package_not_found',404);if(pkg.payload.programId!==a.programId||pkg.payload.packageId!==a.packageId||pkg.payload.version!==pkg.version)fail('weekly_schedule_package_corrupt');if(pkg.payload.version!==a.packageVersion)fail('weekly_schedule_version_conflict');const tasks=await listWeeklyExecutionTasks(store,a.tenantId,a.programId,a.packageId,a.packageVersion);if(!tasks.length)fail('weekly_schedule_tasks_missing');if(tasks.some(t=>t.tenantId!==a.tenantId||t.programId!==a.programId||t.packageId!==a.packageId||t.packageVersion!==a.packageVersion))fail('weekly_schedule_task_scope_invalid');const signatures=tasks.map(scheduleTaskSignature);if(new Set(signatures).size!==tasks.length)fail('weekly_schedule_task_mapping_ambiguous');const requests=await createWeeklyMaterialRequestService(store).list(a.tenantId,a.programId,a.actorUserId);const referenced=new Set(pkg.payload.socialContentPackage.publicationTasks.flatMap(t=>t.materialRequirement?.requestIds??[]));const materials=requests.filter(r=>referenced.has(r.requestId));if(materials.length!==referenced.size)fail('weekly_schedule_required_material_missing');return {pkg:pkg.payload,tasks,materials};}
 async function proposal(a:Scope,id:string){await authority(a);const r=await rows(store,SCHEDULE_PROPOSALS,{tenant_id:a.tenantId,proposal_id:id});if(r.length!==1)fail('weekly_schedule_proposal_not_found',404);const p=r[0]!.payload as WeeklyScheduleProposal;if(p.programId!==a.programId||p.packageId!==a.packageId||p.packageVersion!==a.packageVersion||p.createdBy!==a.actorUserId||r[0]!.content_hash!==scheduleHash(p))fail('weekly_schedule_proposal_forbidden',403);return p;}
 async function repairMaterials(a:Scope,pkg:WeeklyOperatingPackage){if(!ports.revise)await materializeWeeklyExecutionTasks(store,a.tenantId,pkg);if(!pkg.socialContentPackage.publicationTasks.some(t=>t.materialRequirement?.requestIds.length))return [];const service=createWeeklyMaterialRequestService(store),requests=await service.list(a.tenantId,a.programId,a.actorUserId);const tasks=await materializeWeeklyExecutionTasks(store,a.tenantId,pkg);const oldTasks=await listWeeklyExecutionTasks(store,a.tenantId,a.programId,a.packageId,a.packageVersion);const issues:WeeklyScheduleConfirmation['materialConsumerRepairs']=[];
  for(const publication of pkg.socialContentPackage.publicationTasks){for(const requestId of publication.materialRequirement?.requestIds??[]){try{const request=requests.find(r=>r.requestId===requestId);if(!request)fail('weekly_schedule_material_missing');const targets=tasks.filter(t=>t.publicationTaskId===publication.publicationTaskId&&t.schedule.stepKind==='material_readiness');if(targets.length!==1)fail('weekly_schedule_material_consumer_ambiguous');const target=targets[0]!;if(request.consumers.some(c=>c.taskId===target.taskId&&c.packageVersion===pkg.version))continue;const previous=request.consumers.filter(c=>c.packageId===a.packageId&&c.packageVersion===a.packageVersion&&oldTasks.some(t=>t.taskId===c.taskId&&t.publicationTaskId===publication.publicationTaskId));if(previous.length!==1)fail('weekly_schedule_material_source_ambiguous');await service.revise({tenantId:a.tenantId,programId:a.programId,requestId,actorUserId:a.actorUserId,reason:'用户确认倒排后，将冻结必需素材显式关联新版本消费者',addConsumers:[{...previous[0]!,taskId:target.taskId,packageId:pkg.packageId,packageVersion:pkg.version}]});}catch(e){issues.push({requestId,reason:e instanceof Error?e.message:'消费者追加失败'});}}}return issues;
 }
 return {read:proposal,
 async propose(a:Scope,capacity:WeeklyScheduleCapacityInput):Promise<WeeklyScheduleProposal>{return withExecutionPackageGate(store,a,async()=>{const actual=await input(a);if(Object.keys(capacity).some(k=>!['constraints','resources','remainingBudgetCny','operationalDeadlines'].includes(k)))fail('weekly_schedule_capacity_field_invalid',400);if(Object.keys(capacity.constraints??{}).some(id=>!actual.tasks.some(t=>t.taskId===id)))fail('weekly_schedule_foreign_constraint',400);const captured=now();const evidence=await continuations.derivePlannerEvidence(a,captured,capacity);const queueCapacityEvidence=await readWeeklyQueueSchedulingEvidence(store,actual.tasks,new Date(captured),actual.pkg);let plan;try{plan=planWeeklyBackwardSchedule({...capacity,...evidence,queueCapacityEvidence,tasks:actual.tasks,now:captured,frozenOperationalWeek:{weekStart:actual.pkg.weekStart,weekEnd:actual.pkg.weekEnd}});}catch(e){fail('weekly_schedule_capacity_invalid',400);}const p:WeeklyScheduleProposal={proposalId:`wsp_${randomUUID()}`,...a,createdBy:a.actorUserId,createdAt:captured,inputEvidenceHash:scheduleHash(actual),capacity:structuredClone(capacity),plan,inputAuthority:'stored_tasks_with_user_confirmed_capacity_assumptions'};const saved=await store.create(SCHEDULE_PROPOSALS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion,proposal_id:p.proposalId,payload:p,content_hash:scheduleHash(p)});if(!saved)fail('weekly_schedule_proposal_storage_failed',503);return p;});},
 async confirm(a:Scope,request:{proposalId:string;expectedVersion:number;inputEvidenceHash:string}):Promise<WeeklyScheduleConfirmation>{await authority(a);if(request.expectedVersion!==a.packageVersion)fail('weekly_schedule_version_conflict');const p=await proposal(a,request.proposalId);if(p.inputEvidenceHash!==request.inputEvidenceHash)fail('weekly_schedule_evidence_mismatch');const lease=await acquireDurableOperationLease({dataStore:store,tenantId:a.tenantId,scope:'social-weekly-schedule-revision',subjectId:scheduleHash([a.programId,a.packageId]),ownerId:a.actorUserId,now:new Date(now()),leaseDurationMs:120000});if(!lease)fail('weekly_schedule_confirmation_busy');try{return await withExecutionPackageGate(store,a,async gateAssert=>{
  const snapshots=await rows(store,SCHEDULE_SNAPSHOTS,{tenant_id:a.tenantId,proposal_id:p.proposalId});if(snapshots.length>1)fail('weekly_schedule_snapshot_ambiguous');let snapshot=snapshots[0]?.payload as WeeklyScheduleSnapshot|undefined;if(snapshot&&(snapshots[0]!.content_hash!==scheduleHash(snapshot)||snapshot.tenantId!==a.tenantId||snapshot.programId!==a.programId||snapshot.packageId!==a.packageId||snapshot.sourceVersion!==a.packageVersion||snapshot.targetVersion!==a.packageVersion+1))fail('weekly_schedule_snapshot_corrupt');const latest=await latestPackageRow(store,a.tenantId,a.programId,a.packageId);
  if(snapshot&&latest&&latest.payload.version===snapshot.targetVersion&&(latest.payload as WeeklyScheduledPackage).scheduleRevisionRef?.id===snapshot.snapshotId){if(latest.payload.status!=='draft')fail('weekly_schedule_confirmed_version_not_draft');const materials=await repairMaterials(a,latest.payload);const revoked=await finalizeOldAuthorization(a,snapshot);return {item:latest.payload,snapshot,materialConsumerRepairs:materials,activated:false,previousPublishingAuthorizationRevoked:revoked};}
  const actual=await input(a);if(scheduleHash(actual)!==p.inputEvidenceHash)fail('weekly_schedule_proposal_stale');const captured=now();const evidence=await continuations.derivePlannerEvidence(a,captured,p.capacity);const queueCapacityEvidence=await readWeeklyQueueSchedulingEvidence(store,actual.tasks,new Date(captured),actual.pkg);if(p.plan.queueConfigurationHash&&p.plan.queueConfigurationHash!==queueCapacityEvidence.configurationHash)fail('weekly_schedule_queue_configuration_changed');if(p.plan.queueCapacityEvidenceHash&&p.plan.queueCapacityEvidenceHash!==queueCapacityEvidence.inputEvidenceHash)fail('weekly_schedule_queue_identity_changed');const fresh=planWeeklyBackwardSchedule({...p.capacity,...evidence,queueCapacityEvidence,tasks:actual.tasks,now:captured,frozenOperationalWeek:{weekStart:actual.pkg.weekStart,weekEnd:actual.pkg.weekEnd}});
  if(fresh.publicationGap!==0||fresh.assignments.some(x=>!x.startAt||!x.finishAt||(x.mode!=='completed_verified'&&!x.resourceKey)||x.reasons.some(r=>r!=='human_completion_not_verified'))||fresh.publications.length!==p.plan.publications.length||fresh.publicationGap!==p.plan.publicationGap)fail('weekly_schedule_fresh_capacity_not_feasible');
  if(snapshot){if(snapshot.inputEvidenceHash!==p.inputEvidenceHash||snapshot.confirmedBy!==a.actorUserId||snapshot.assignments.some(x=>(x.mode??'planned')==='planned'&&Date.parse(x.startAt)<Date.parse(captured)))fail('weekly_schedule_saved_confirmation_stale');}
  else{snapshot={snapshotId:`wss_${randomUUID()}`,proposalId:p.proposalId,tenantId:a.tenantId,programId:a.programId,packageId:a.packageId,sourceVersion:a.packageVersion,targetVersion:a.packageVersion+1,confirmedBy:a.actorUserId,confirmedAt:captured,inputEvidenceHash:p.inputEvidenceHash,queueConfigurationHash:queueCapacityEvidence.configurationHash,queueCapacityEvidenceHash:queueCapacityEvidence.inputEvidenceHash,assignments:fresh.assignments.map(x=>({sourceTaskId:x.taskId,signature:scheduleTaskSignature(actual.tasks.find(t=>t.taskId===x.taskId)!),startAt:x.startAt!,finishAt:x.finishAt!,resourceKey:x.resourceKey,mode:x.mode as 'planned'|'completed_verified'|'running_reserved',sourceInputHash:weeklyContinuationInputHash(actual.tasks.find(t=>t.taskId===x.taskId)!)})),publicationTimes:actual.pkg.socialContentPackage.publicationTasks.map(t=>({publicationTaskId:t.publicationTaskId,publishWindow:t.publishWindow})),capacity:p.capacity,previousPublishingAuthorizationAllowed:actual.pkg.socialContentPackage.authorization.allowRealPublishing};const saved=await store.create(SCHEDULE_SNAPSHOTS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,target_version:snapshot.targetVersion,proposal_id:p.proposalId,snapshot_id:snapshot.snapshotId,payload:snapshot,content_hash:scheduleHash(snapshot)});if(!saved)fail('weekly_schedule_snapshot_storage_failed',503);}
  if(scheduleHash(await input(a))!==p.inputEvidenceHash)fail('weekly_schedule_source_changed_during_confirm');
  if((await readWeeklyQueueSchedulingEvidence(store,actual.tasks,new Date(captured),actual.pkg)).inputEvidenceHash!==queueCapacityEvidence.inputEvidenceHash)fail('weekly_schedule_queue_configuration_changed');
  await gateAssert();await freezeExecutionPackage(store,a,{snapshotId:snapshot.snapshotId,targetVersion:snapshot.targetVersion,actorUserId:a.actorUserId,inputEvidenceHash:snapshot.inputEvidenceHash,confirmedAt:snapshot.confirmedAt});await gateAssert();
  const ref={type:'weekly_schedule_snapshot',id:snapshot.snapshotId,version:1};const next=ports.revise?await ports.revise(a,ref):await createWeeklyOperatingPackageService(store).revise(a.tenantId,a.actorUserId,a.programId,a.packageId,{expectedVersion:a.packageVersion,changeReason:'用户明确确认容量倒排，保留发布时刻并创建新草稿'}, {scheduleRevisionRef:ref});const issues=await repairMaterials(a,next);return {item:next,snapshot,materialConsumerRepairs:issues,activated:false,previousPublishingAuthorizationRevoked:actual.pkg.socialContentPackage.authorization.allowRealPublishing};
 });}finally{await releaseDurableOperationLease({dataStore:store,lease});}}
 };
}
