import {randomUUID} from 'node:crypto';
import {acquireDurableOperationLease,assertDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
import {withLocalQueue} from '../routes/digitalEmployeeRecords.js';
const recoveryQueues=new Map<string,Promise<void>>();
import type {DataStore,Record_} from '../storage/datastore.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {publicationInstant} from './publicationDeadlines.js';
import {SocialProgramError} from './service.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {CHANNEL_SEND_REQUESTS,readWeeklyNativeSendRequestEvidence} from '../digitalEmployees/customerChannelSendRequests.js';
import {reconcileWeeklyNativeAcceptedRequest,validateWeeklyNativeSendReceipt} from '../digitalEmployees/weeklyNativeFollowupDispatch.js';
import type {WeeklyNativeSendRecovery,WeeklyNativeSendRecoveryScope,WeeklyNativeSendRecoverySource} from '../../shared/contracts/weeklyNativeSendRecovery.js';
export const NATIVE_SEND_RECOVERIES='social_weekly_native_send_recoveries';
const obj=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return obj(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
function check(v:unknown,code:string,status=409):asserts v{if(!v)throw new SocialProgramError(code,status,code);}
async function actor(store:DataStore,tenantId:string,id:string){const u=await store.getById<Record_>('users',id),role=organizationRoleOrNull(u?.role);check(u?.tenantId===tenantId&&role&&['customer_service','admin','super_admin'].includes(role)&&u.disabled!==true&&u.active!==false&&!['disabled','suspended'].includes(String(u.status)),'weekly_native_recovery_actor_forbidden',403);return role;}
async function rows(store:DataStore,c:string,where:Record<string,string|number>){const all:Record_[]=[];let total:number|undefined;for(let page=1;page<=1000;page++){const r=await store.list<Record_>(c,{where,page,perPage:250,sort:'id'});check(Number.isSafeInteger(r.totalItems)&&r.totalItems>=0&&(total===undefined||total===r.totalItems),'weekly_native_recovery_pagination_changed');total=r.totalItems;check(r.items.every(v=>Object.entries(where).every(([k,w])=>v[k]===w)&&!all.some(old=>old.id===v.id)),'weekly_native_recovery_pagination_invalid');all.push(...r.items);if(all.length===total)return all;check(r.items.length===250,'weekly_native_recovery_pagination_incomplete');}throw Error('weekly_native_recovery_pagination_incomplete');}
function allowedRead(p:WeeklyNativeSendRecovery,who:string,role:string){return [p.ownerUserId,p.createdBy,p.originalActorUserId].includes(who)||['admin','super_admin'].includes(role);}
function content(row:Record_,a:WeeklyNativeSendRecoveryScope){const p=obj(row.payload) as WeeklyNativeSendRecovery;const {recordHash,...frozen}=obj(row.payload);check(row.tenant_id===a.tenantId&&row.program_id===a.programId&&row.package_id===a.packageId&&row.package_version===a.packageVersion&&row.source_key===socialRequestHash({channel:p.channel,requestId:p.requestId})&&p.id===row.id&&p.tenantId===a.tenantId&&p.programId===a.programId&&p.packageId===a.packageId&&p.packageVersion===a.packageVersion&&row.content_hash===recordHash&&socialRequestHash(frozen)===recordHash,'weekly_native_recovery_record_invalid');return frozen as WeeklyNativeSendRecovery;}
async function source(store:DataStore,a:WeeklyNativeSendRecoveryScope,input:{channel:'messenger'|'instagram';requestId:string}){const e=await readWeeklyNativeSendRequestEvidence(store,{tenantId:a.tenantId,...input});check(e&&e.authority.programId===a.programId&&e.authority.packageId===a.packageId&&e.authority.packageVersion===a.packageVersion,'weekly_native_recovery_source_scope_invalid');const tasks=await rows(store,'workflow_tasks',{tenant_id:a.tenantId,run_id:e.authority.runId}),dispatch=tasks.filter(t=>t.task_key==='followup_dispatch'&&t.agent_role==='customer');check(dispatch.length===1,'weekly_native_recovery_task_ambiguous');return {...e,task:dispatch[0]!};}
function currentGap(request:{status:string;deliveryStatus:string;historyWritebackPending:boolean}){return request.status!=='accepted'?'weekly_native_send_provider_identity_gap':request.deliveryStatus==='failed'?'weekly_native_send_delivery_failed':request.historyWritebackPending?'weekly_native_send_history_pending':'weekly_native_send_projection_pending';}
function stored(p:WeeklyNativeSendRecovery){const {resolvedProof,overdue,gap,...base}=p;void resolvedProof;void overdue;void gap;const record={...base};return {...record,recordHash:socialRequestHash(record)};}
export function createWeeklyNativeSendRecoveryService(store:DataStore){return {
 async sources(a:WeeklyNativeSendRecoveryScope,who:string):Promise<WeeklyNativeSendRecoverySource[]>{const role=await actor(store,a.tenantId,who);const result:WeeklyNativeSendRecoverySource[]=[];for(const row of await rows(store,CHANNEL_SEND_REQUESTS,{tenant_id:a.tenantId})){const p=obj(row.payload),s=obj(p.weeklySource);if(!['messenger','instagram'].includes(p.channel)||s.programId!==a.programId||s.packageId!==a.packageId||s.packageVersion!==a.packageVersion)continue;const e=await source(store,a,{channel:p.channel,requestId:p.requestId});const batch=await store.getById<Record_>('followup_batches',e.authority.batchId);const allowed=e.authority.actorUserId===who||batch?.approved_by===who||['admin','super_admin'].includes(role);if(!allowed)continue;const item=await store.getById<Record_>('followup_batch_items',e.authority.itemId);if(e.request.status==='accepted'&&e.request.deliveryStatus!=='failed'&&e.task.status==='succeeded'&&['sent','delivered','read'].includes(String(item?.status))&&!e.request.historyWritebackPending)continue;result.push({channel:e.authority.channel,runId:e.authority.runId,taskId:e.task.id,batchId:e.authority.batchId,itemId:e.authority.itemId,customerId:e.authority.customerId,requestId:e.request.requestId,recipientMasked:e.request.recipientMasked,status:e.request.status,gap:currentGap(e.request),canCreate:true});}return result;},
 async create(a:WeeklyNativeSendRecoveryScope,who:string,input:{channel:'messenger'|'instagram';requestId:string;ownerUserId:string;deadlineAt:string;reason:string}){check(input&&typeof input==='object'&&!Array.isArray(input)&&Object.keys(input).every(k=>['channel','requestId','ownerUserId','deadlineAt','reason'].includes(k)),'weekly_native_recovery_input_invalid',400);const role=await actor(store,a.tenantId,who);check(['messenger','instagram'].includes(input.channel)&&publicationInstant(input.deadlineAt)!==null&&typeof input.reason==='string'&&input.reason.trim()&&input.reason.length<=2000,'weekly_native_recovery_input_invalid',400);await actor(store,a.tenantId,input.ownerUserId);const e=await source(store,a,input),batch=await store.getById<Record_>('followup_batches',e.authority.batchId);check(e.authority.actorUserId===who||batch?.approved_by===who||['admin','super_admin'].includes(role),'weekly_native_recovery_create_forbidden',403);const id=socialRequestHash({scope:a,requestId:input.requestId,channel:input.channel}).slice(0,15);const previous=await store.getById<Record_>(NATIVE_SEND_RECOVERIES,id);if(previous){const p=content(previous,a);check(p.ownerUserId===input.ownerUserId&&p.deadlineAt===input.deadlineAt&&p.reason===input.reason.trim()&&p.createdBy===who,'weekly_native_recovery_intent_conflict');return this.get(a,id,who);}
 const sourceItem=await store.getById<Record_>('followup_batch_items',e.authority.itemId);check(e.request.status!=='accepted'||e.request.deliveryStatus==='failed'||e.request.historyWritebackPending||e.task.status!=='succeeded'||!['sent','delivered','read'].includes(String(sourceItem?.status)),'weekly_native_recovery_no_actual_gap');
 const p:WeeklyNativeSendRecovery={id,version:1,status:'awaiting_receipt',channel:input.channel,...a,runId:e.authority.runId,taskId:e.task.id,batchId:e.authority.batchId,batchVersion:e.authority.batchVersion,batchHash:e.authority.batchHash,itemId:e.authority.itemId,itemHash:e.authority.itemHash,memberId:e.authority.memberId,customerId:e.authority.customerId,requestId:input.requestId,originalActorUserId:e.authority.actorUserId,weeklyAuthorityHash:e.request.weeklyAuthorityHash!,intentHash:e.intentHash,bodyHash:e.request.bodyHash,recipientHash:e.request.recipientHash,recipientMasked:e.request.recipientMasked,accountId:e.request.accountId,accountAuthorityHash:e.request.accountAuthorityHash,selectionHash:e.authority.selectionHash,ownerUserId:input.ownerUserId,createdBy:who,deadlineAt:input.deadlineAt,reason:input.reason.trim(),createdAt:new Date().toISOString(),resolvedAt:null,gap:currentGap(e.request),overdue:false};const value=stored(p);try{await store.create(NATIVE_SEND_RECOVERIES,{id,tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion,source_key:socialRequestHash({channel:input.channel,requestId:input.requestId}),content_hash:value.recordHash,payload:value});}catch(error){const winner=await store.getById<Record_>(NATIVE_SEND_RECOVERIES,id);if(!winner)throw error;const saved=content(winner,a);check(saved.ownerUserId===input.ownerUserId&&saved.deadlineAt===input.deadlineAt&&saved.reason===input.reason.trim()&&saved.createdBy===who,'weekly_native_recovery_intent_conflict');}return this.get(a,id,who);},
 async get(a:WeeklyNativeSendRecoveryScope,id:string,who:string):Promise<WeeklyNativeSendRecovery>{const role=await actor(store,a.tenantId,who),row=await store.getById<Record_>(NATIVE_SEND_RECOVERIES,id);check(row,'weekly_native_recovery_not_found',404);const p=content(row,a);check(allowedRead(p,who,role),'weekly_native_recovery_read_forbidden',403);const e=await source(store,a,p);check(e.task.id===p.taskId&&e.intentHash===p.intentHash&&e.authority.actorUserId===p.originalActorUserId&&e.request.weeklyAuthorityHash===p.weeklyAuthorityHash,'weekly_native_recovery_source_changed');const result={...p,gap:currentGap(e.request),overdue:publicationInstant(p.deadlineAt)!<Date.now()};if(p.status==='resolved'){try{const item=await store.getById<Record_>('followup_batch_items',p.itemId);check(item&&e.task.status==='succeeded','weekly_native_recovery_original_task_pending');const {readWeeklyCustomerStep}=await import('../runtime/socialWeeklyCustomerBridge.js');const complete=await readWeeklyCustomerStep(store,a,p.runId,'customer_followup_dispatch');check(complete.status==='succeeded','weekly_native_recovery_original_batch_proof_gap');const proof=await validateWeeklyNativeSendReceipt(store,item,{tenantId:p.tenantId,runId:p.runId,programId:p.programId,packageId:p.packageId,packageVersion:p.packageVersion});result.resolvedProof={taskId:p.taskId,runId:p.runId,requestId:proof.requestId,providerMessageId:proof.providerMessageId!,evidenceHash:socialRequestHash({item:proof,batchId:p.batchId,taskId:p.taskId,items:(await rows(store,'followup_batch_items',{tenant_id:p.tenantId,batch_id:p.batchId})).map(row=>({id:row.id,status:row.status,contentHash:row.content_hash,providerMessageId:row.provider_message_id,sentAt:row.sent_at,receipt:row.provider_receipt})).sort((l,r)=>l.id.localeCompare(r.id))}),verifiedAt:new Date().toISOString()};result.gap='';}catch{result.gap='weekly_native_recovery_resolved_proof_gap';}}return result;},
 async list(a:WeeklyNativeSendRecoveryScope,who:string){const role=await actor(store,a.tenantId,who);const list:WeeklyNativeSendRecovery[]=[];for(const row of await rows(store,NATIVE_SEND_RECOVERIES,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion})){const p=content(row,a);if(allowedRead(p,who,role))list.push(await this.get(a,p.id,who));}return list;},
 async resolve(a:WeeklyNativeSendRecoveryScope,id:string,who:string,input:{expectedVersion:number}){check(input&&typeof input==='object'&&!Array.isArray(input)&&Object.keys(input).length===1&&Object.keys(input)[0]==='expectedVersion'&&Number.isSafeInteger(input.expectedVersion),'weekly_native_recovery_input_invalid',400);return withLocalQueue(recoveryQueues,JSON.stringify([a.tenantId,id]),async()=>{const lease=await acquireDurableOperationLease({dataStore:store,tenantId:a.tenantId,scope:'weekly_native_send_recovery',subjectId:id,ownerId:randomUUID()});check(lease,'weekly_native_recovery_busy');try{await actor(store,a.tenantId,who);const p=await this.get(a,id,who);check(p.ownerUserId===who,'weekly_native_recovery_owner_required',403);check(input.expectedVersion===p.version,'weekly_native_recovery_version_conflict');if(p.status==='resolved'){check(p.resolvedProof,'weekly_native_recovery_resolved_proof_gap');return {item:p,messagesSent:0 as const,runAdvanced:false as const};}const result=await reconcileWeeklyNativeAcceptedRequest(store,{tenantId:a.tenantId,channel:p.channel,requestId:p.requestId,expectedScope:{runId:p.runId,programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion}});check(result.originalTaskCompleted,'weekly_native_recovery_original_task_pending');const value=stored({...p,version:p.version+1,status:'resolved',resolvedAt:p.resolvedAt??new Date().toISOString()});await assertDurableOperationLease({dataStore:store,lease});check(await store.update(NATIVE_SEND_RECOVERIES,id,{payload:value,content_hash:value.recordHash}),'weekly_native_recovery_save_failed');return {item:await this.get(a,id,who),messagesSent:0 as const,runAdvanced:false as const};}finally{await releaseDurableOperationLease({dataStore:store,lease});}});}
};}
