import {socialRequestHash} from '../starter198/socialContentValidation.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import type {DataStore,ListQuery,Record_} from '../storage/datastore.js';
import {createWeeklyProfileUpgradeService} from './weeklyProfileUpgrade.js';
import {createWeeklyOperatingPackageService} from './weeklyOperatingPackages.js';
function fixture(){
 const a={tenantId:'t',programId:'p',packageId:'w',packageVersion:1};
 const c={tenantId:'t',accountId:'connection',channelId:'tiktok',externalContentId:'video',status:'published',source:'official_api',publicUrl:'https://example.com/video',publishedAt:'2026-10-05T00:00:00Z'};
 const snap={tenantId:'t',snapshotId:'metrics',accountId:'connection',channelId:'tiktok',externalContentId:'video',capturedAt:'2026-10-08T00:00:00Z',source:'provider',metrics:{views:100,likes:0,shares:0,comments:0}};
 const data:Record<string,Record_[]>={users:[{id:'u',tenantId:'t',role:'social_operator'}],social_weekly_operating_packages:[{id:'wrow',tenant_id:'t',program_id:'p',package_id:'w',version:1,payload:{packageId:'w',programId:'p',version:1,weekStart:'2026-10-05',weekEnd:'2026-10-11',referenceSourcePolicy:{profile:'b2b_cold_start',ownedPercent:0,externalPercent:100,allocationUnit:'mother_content'}}}],social_owned_accounts:[{id:'account',tenant_id:'t',program_id:'p',payload:{programId:'p',accountId:'owned',connectionId:'connection',platform:'tiktok',version:1}}],social_external_contents:[{id:'history',tenant_id:'t',account_id:'connection',channel_id:'tiktok',external_content_id:'video',content:c}],social_channel_metric_snapshots:[{id:'metric',tenant_id:'t',snapshot_id:'metrics',account_id:'connection',channel_id:'tiktok',external_content_id:'video',snapshot:snap}],starter_social_inspiration_handoff_versions:[],social_weekly_profile_upgrades:[]};
 let counter=0;
 const store:DataStore={async getById<T>(col:string,id:string){return structuredClone(data[col]?.find(r=>r.id===id)??null) as T|null;},async list<T>(col:string,q:ListQuery={}){const all=(data[col]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));const page=q.page??1,perPage=q.perPage??30;return {items:structuredClone(all.slice((page-1)*perPage,page*perPage)) as T[],totalItems:all.length,totalPages:Math.ceil(all.length/perPage),page,perPage};},async create<T>(col:string,input:Record<string,unknown>){const r={...structuredClone(input),id:String(input.id??`new-${++counter}`)};(data[col]??=[]).push(r);return structuredClone(r) as T;},async update(col:string,id:string,input:Record<string,unknown>){const r=data[col]?.find(r=>r.id===id);if(!r)return false;Object.assign(r,structuredClone(input));return true;},async delete(col:string,id:string){const i=data[col]?.findIndex(r=>r.id===id)??-1;if(i<0)return false;data[col].splice(i,1);return true;}};
 return {a,data,c,snap,service:createWeeklyProfileUpgradeService(store),store};
}
test('actual own published history, zero engagement and observation window support explicit 20/80 next-week confirmation without changing cold current week',async()=>{const f=fixture(),before=structuredClone(f.data.social_weekly_operating_packages);const e=await f.service.evidence(f.a,'u');assert.equal(e.thresholdPolicy,'not_defined');assert.equal(e.items[0].metrics.likes,0);assert.equal(e.items[0].observationSeconds,3*86400);const p=await f.service.propose(f.a,'u',{targetWeekStart:e.targetWeekStart,basis:'history_material_or_engagement_insufficient',reason:'真人审查历史表现，材料不足；不自动计算弱表现阈值。',selectedEvidenceRefs:[e.items[0].evidenceRef]});await assert.rejects(f.service.readForNextWeek(f.a,'u',p.id,e.targetWeekStart),{code:'profile_upgrade_confirmation_required'});const confirmed=await f.service.confirm(f.a,'u',p.id,{expectedVersion:1,evidenceHash:p.evidenceHash});assert.equal(confirmed.confirmedBy,'u');assert.equal((await f.service.readForNextWeek(f.a,'u',p.id,e.targetWeekStart)).referenceSourcePolicy.ownedPercent,20);assert.deepEqual(f.data.social_weekly_operating_packages,before);await assert.rejects(f.service.readForNextWeek(f.a,'u',p.id,'2026-10-19'),{code:'profile_upgrade_confirmation_required'});});
test('no inventory/account-only maturity; unknown metrics and missing immutable tone never imply weak performance or clear tone',async()=>{const f=fixture(),input={targetWeekStart:'2026-10-12',basis:'tone_clear_growth_stalled' as const,reason:'增长停滞',selectedEvidenceRefs:['owned_content:history']};await assert.rejects(f.service.propose(f.a,'u',input),{code:'profile_upgrade_tone_handoff_required'});(f.snap.metrics as Record<string,unknown>).comments=null;await assert.rejects(f.service.propose(f.a,'u',{...input,basis:'history_material_or_engagement_insufficient'}),{code:'profile_upgrade_performance_unknown'});f.c.status='processing';assert.deepEqual((await f.service.evidence(f.a,'u')).items,[]);});
test('fresh evidence, tenant actor and already-created next week are checked before consuming confirmation',async()=>{const f=fixture(),p=await f.service.propose(f.a,'u',{targetWeekStart:'2026-10-12',basis:'history_material_or_engagement_insufficient',reason:'可复用材料不足',selectedEvidenceRefs:['owned_content:history']});await f.service.confirm(f.a,'u',p.id,{expectedVersion:1,evidenceHash:p.evidenceHash});f.snap.metrics.views=101;await assert.rejects(f.service.readForNextWeek(f.a,'u',p.id,'2026-10-12'),{code:'profile_upgrade_evidence_changed'});f.snap.metrics.views=100;f.data.social_weekly_operating_packages.push({id:'next',tenant_id:'t',program_id:'p',week_start:'2026-10-12'});await assert.rejects(f.service.readForNextWeek(f.a,'u',p.id,'2026-10-12'),{code:'profile_upgrade_target_week_exists'});await assert.rejects(f.service.evidence({...f.a,tenantId:'foreign'},'u'),{code:'profile_upgrade_actor_forbidden'});});

test('40/60 requires actual immutable own video tone handoff and binds future consumption to its unchanged hash',async()=>{const f=fixture();const h={inspirationId:'actual-own-video',version:'1',analysisVersion:'1',readiness:'production_reference',source:{platform:'tiktok',sourceUrl:f.c.publicUrl},reusableLogic:{hookTypes:['问题'],revealOrder:['问题','实证'],proofPlacement:['中段'],pacing:'先慢后快',emotionalProgression:'疑问到理解',ctaPosition:'结尾'},evidenceRefs:[{description:'实际片段观察',confidence:0.9,needsReview:false}],rights:{mayAnalyze:true,mayAdapt:true,mayUseOriginalMedia:false}};f.data.starter_social_inspiration_handoff_versions.push({id:'handoff',tenant_id:'t',record_hash:socialRequestHash(h),payload:h});const p=await f.service.propose(f.a,'u',{targetWeekStart:'2026-10-12',basis:'tone_clear_growth_stalled',reason:'真人确认调性清晰，增长停滞；四指标不是获客判定。',selectedEvidenceRefs:['owned_content:history']});assert.equal(p.policy.ownedPercent,40);await f.service.confirm(f.a,'u',p.id,{expectedVersion:1,evidenceHash:p.evidenceHash});h.reusableLogic.pacing='已改动';await assert.rejects(f.service.readForNextWeek(f.a,'u',p.id,'2026-10-12'),{code:'profile_upgrade_evidence_changed'});});

test('actual next-week package creation consumes confirmed receipt without updating program route or source package',async()=>{
 const f=fixture();f.data.social_programs=[{id:'program',tenant_id:'t',program_id:'p',payload:{programId:'p',route:'cold_start',version:1,readiness:{},status:'active'}}];
 const p=await f.service.propose(f.a,'u',{targetWeekStart:'2026-10-12',basis:'history_material_or_engagement_insufficient',reason:'材料不足',selectedEvidenceRefs:['owned_content:history']});await f.service.confirm(f.a,'u',p.id,{expectedVersion:1,evidenceHash:p.evidenceHash});
 const next=await createWeeklyOperatingPackageService(f.store).create('t','u','p',{weekStart:'2026-10-12',objective:'真实下一周',successCriteria:['发布计划'],accountPlans:[{accountId:'owned',publicationCount:1}],profileUpgradeRef:{id:p.id,sourcePackageId:'w',sourcePackageVersion:1}});
 assert.equal(next.referenceSourcePolicy?.profile,'b2b_established');assert.equal(next.referenceSourcePolicy?.ownedPercent,20);assert.equal((f.data.social_programs[0].payload as {route:string}).route,'cold_start');assert.equal((f.data.social_weekly_operating_packages[0].payload as {referenceSourcePolicy:{externalPercent:number}}).referenceSourcePolicy.externalPercent,100);
});
