import test from'node:test';import assert from'node:assert/strict';import type{DataStore,Record_}from'../storage/datastore.js';import{buildFrozenWeeklyReview}from'../socialReview/service.js';import{readWeeklyReviewEvidence}from'./weeklyReviewEvidence.js';
const scope={tenantId:'tenant',actorUserId:'operator',programId:'program',packageId:'week',packageVersion:1,taskId:'monitor',now:new Date('2026-10-09T12:00:00Z')};
function fixture(){const pkg={programId:'program',packageId:'week',version:1,status:'active',weekStart:'2026-10-05',weekEnd:'2026-10-11'};const task=(taskId:string,stepKind:string)=>({tenantId:'tenant',programId:'program',packageId:'week',packageVersion:1,taskId,accountId:stepKind==='weekly_review'?null:'account',publicationTaskId:stepKind==='weekly_review'?null:'video',workflowKind:stepKind==='weekly_review'?'review':'engagement',status:'queued',schedule:{stepKind,estimatedFinishAt:'2026-10-11T12:00:00Z'},resultRefs:[],ownBlockingReasons:[],inheritedBlockingTaskIds:[],lastError:null});const monitor=task('monitor','performance_monitoring'),review=task('review','weekly_review');const data:Record<string,Record_[]>={users:[{id:'operator',tenantId:'tenant',role:'social_operator'}],social_weekly_operating_packages:[{id:'pkg',tenant_id:'tenant',program_id:'program',package_id:'week',version:1,payload:pkg}],social_weekly_execution_tasks:[monitor,review].map(p=>({id:p.taskId,tenant_id:'tenant',program_id:'program',package_id:'week',package_version:1,task_id:p.taskId,payload:p})),social_metric_snapshots:[{id:'metric-real',tenant_id:'tenant',account_id:'account',content_id:'real-content',captured_at:'2026-10-08T12:00:00Z',source:'platform_api',metrics:{views:0,likes:2}}]};const queries:Array<{collection:string;where:any}>=[];const store={async getById<T>(c:string,id:string){return structuredClone(data[c]?.find(r=>r.id===id)??null)as T|null;},async list<T>(c:string,q:any={}){queries.push({collection:c,where:q.where});const values=(data[c]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));return{items:structuredClone(values)as T[],totalItems:values.length,totalPages:values.length?1:0,page:1,perPage:250};},async create(){throw Error('Read must never create/scan/freeze');},async update(){throw Error('Read must never mutate');},async delete(){throw Error('Read must never delete');}}as DataStore;return{store,data,queries,monitor,review};}
function report(f:ReturnType<typeof fixture>){const snapshot=buildFrozenWeeklyReview({tenantId:'tenant',actorId:'worker',weekRef:'week',programId:'program',operatingPackageRef:{type:'weekly_operating_package',id:'week',version:1},startsAt:'2026-10-05T00:00:00.000Z',endsAt:'2026-10-12T00:00:00.000Z',frozenAt:'2026-10-12T01:00:00.000Z',contents:[{businessDirection:'Actual business',platform:'tiktok',accountId:'account',contentId:'real-content',publicationTaskId:'video',evidenceKind:'owned_content_result',attributionStatus:'unknown'}],metricSnapshots:[{id:'metric-real',platform:'tiktok',accountId:'account',contentId:'real-content',capturedAt:'2026-10-08T12:00:00.000Z',valueKind:'daily',metrics:{views:0}}]});f.data.social_weekly_review_snapshots=[{id:'row',tenant_id:'tenant',program_id:'program',package_id:'week',package_version:1,snapshot_id:snapshot.snapshotId,source_digest:snapshot.sourceDigest,frozen_by:'worker',frozen_at:snapshot.window.frozenAt,snapshot}];return snapshot;}
test('pre-window and missing report read genuine state and never freeze or fill missing metrics with zero',async()=>{const f=fixture();const before=await readWeeklyReviewEvidence(f.store,scope);assert.equal(before.state,'waiting_window');assert.equal(before.report,null);assert.equal(before.metrics.length,0);assert.equal(before.task.status,'queued');const after=await readWeeklyReviewEvidence(f.store,{...scope,taskId:'review',now:new Date('2026-10-12T02:00:00Z')});assert.equal(after.state,'waiting_evidence');assert.equal(after.window.semantics,'existing_worker_utc_reporting_window');assert.ok(f.queries.every(q=>q.where?.tenant_id==='tenant'));});
test('actual task metric refs preserve true zero and unknown shares/comments without inferring acquisition',async t=>{
 t.mock.timers.enable({apis:['Date'],now:new Date('2026-10-07T10:00:00Z')});
 const {prepareWeeklyInventoryG6Fixture}=await import('../runtime/weeklyInventoryG6.fixture.js');
 const {executeWeeklyPublication}=await import('../publishing/weeklyLineage.js');
 const f=await prepareWeeklyInventoryG6Fixture();t.after(f.cleanup);t.mock.timers.setTime(new Date('2026-10-07T13:00:00Z').getTime());
 const actual=(await f.store.list<{payload:typeof f.next}>('social_weekly_operating_packages',{where:{tenant_id:'t',package_id:'week2',version:2},perPage:2})).items[0]!.payload;
 const attempt=await executeWeeklyPublication({assignment:f.assignment.payload,publicationPackage:f.actualPackage,dataStore:f.store,contentPackage:actual.socialContentPackage,existingPublishedCount:0,adapter:{provider:'tiktok-content-posting-api',platform:'tiktok',capability:'available',async publish(){return{status:'published',providerReceiptId:'review-view-receipt',platformPostId:'review-view-post'};},async reconcile(){throw Error('unused');}}});
 assert.equal(attempt.status,'published');
 const monitor=structuredClone(f.targetPublishing);monitor.taskId='review-view-monitor';monitor.workflowKind='engagement';monitor.schedule.stepKind='performance_monitoring';monitor.status='queued';monitor.resultRefs=[{type:'social_metric_snapshot',id:'review-view-metric',version:1}];
 await f.store.create('social_weekly_execution_tasks',{tenant_id:'t',program_id:'p',package_id:monitor.packageId,package_version:monitor.packageVersion,task_id:monitor.taskId,payload:monitor});
 const metric=await f.store.create<Record_>('social_metric_snapshots',{id:'review-view-metric',tenant_id:'t',account_id:'account',platform:'tiktok',content_id:'review-view-post',captured_at:'2026-10-08T12:00:00Z',source:'platform_api',metrics:{views:0,likes:2}});
 assert.ok(metric,'the metric must actually persist before it can authorize monitoring');
 // Some stores generate IDs; freeze the actual persisted identity into the task.
 monitor.resultRefs[0]!.id=metric.id;
 const taskRow=f.tables.social_weekly_execution_tasks!.find(row=>row.task_id===monitor.taskId)!;await f.store.update('social_weekly_execution_tasks',taskRow.id,{payload:monitor});
 const input={tenantId:'t',actorUserId:'owner',programId:'p',packageId:monitor.packageId,packageVersion:monitor.packageVersion,taskId:monitor.taskId,now:new Date('2026-10-09T12:00:00Z')};
 const view=await readWeeklyReviewEvidence(f.store,input);assert.equal(view.state,'monitoring_evidence');assert.deepEqual(view.metrics[0]!.values,{views:0,likes:2,shares:null,comments:null});
 await f.store.update('social_metric_snapshots',metric.id,{tenant_id:'foreign'});const denied=await readWeeklyReviewEvidence(f.store,input);assert.equal(denied.metrics.length,0);assert.equal(denied.state,'blocked');
});
test('only exact frozen package report is returned and task result reference must match',async()=>{const f=fixture(),snapshot=report(f);(f.review.resultRefs as any[]).push({type:'weekly_review_snapshot',id:snapshot.snapshotId,version:1});const view=await readWeeklyReviewEvidence(f.store,{...scope,taskId:'review',now:new Date('2026-10-12T02:00:00Z')});assert.equal(view.state,'report_frozen');assert.equal(view.report?.snapshotId,snapshot.snapshotId);assert.equal(view.report?.contents[0]?.metrics.views?.value,0);assert.equal(view.report?.contents[0]?.metrics.likes?.value,null);assert.equal(view.report?.contents[0]?.attributionStatus,'unknown');f.review.resultRefs[0]={type:'weekly_review_snapshot',id:'forged',version:1}as never;const changed=await readWeeklyReviewEvidence(f.store,{...scope,taskId:'review',now:new Date('2026-10-12T02:00:00Z')});assert.equal(changed.state,'blocked');});
test('cross scope, ambiguous report, corrupt source and synthetic frozen rows cannot become a report',async()=>{for(const change of [{packageVersion:2},{programId:'other'},{taskId:'other'},{tenantId:'foreign'}]){const f=fixture();await assert.rejects(readWeeklyReviewEvidence(f.store,{...scope,...change}));}for(const mutate of [(f:ReturnType<typeof fixture>)=>{f.data.social_weekly_review_snapshots!.push({...f.data.social_weekly_review_snapshots![0]!,id:'duplicate'});},(f:ReturnType<typeof fixture>)=>{f.data.social_weekly_review_snapshots![0]!.source_digest='forged';},(f:ReturnType<typeof fixture>)=>{f.data.social_weekly_review_snapshots![0]!.synthetic=true;},(f:ReturnType<typeof fixture>)=>{(f.data.social_weekly_review_snapshots![0]!.snapshot as any).operatingPackageRef.version=2;}]){const f=fixture();report(f);mutate(f);await assert.rejects(readWeeklyReviewEvidence(f.store,{...scope,taskId:'review',now:new Date('2026-10-12T02:00:00Z')}));}});
test('HTTP read factory enforces auth, exact version and task scope without invoking a worker',async()=>{const express=(await import('express')).default;const{createSocialWeeklyReviewEvidenceRouter}=await import('../routes/socialWeeklyReviewEvidence.js');const f=fixture(),app=express();app.use((req,res,next)=>{res.locals={tenantId:req.headers['x-tenant'],userId:req.headers['x-user']};next();});app.use('/programs/:programId/packages/:packageId/review',createSocialWeeklyReviewEvidenceRouter(f.store));const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const address=server.address();if(!address||typeof address==='string')throw Error('address');const base=`http://127.0.0.1:${address.port}/programs/program/packages/week/review`;try{assert.equal((await fetch(`${base}/monitor?version=1`)).status,401);const headers={'x-tenant':'tenant','x-user':'operator'};assert.equal((await fetch(`${base}/monitor?version=1&version=2`,{headers})).status,400);assert.equal((await fetch(`${base}/other?version=1`,{headers})).status,404);assert.equal((await fetch(`${base}/monitor?version=1`,{headers})).status,200);}finally{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));}});
