import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareWeeklyNonPresenterPlanningFixture} from '../runtime/weeklyNonPresenterProduction.fixture.js';
import {createWeeklyOperatingPackageService} from './weeklyOperatingPackages.js';
import {createSocialOperatingDecisionService} from '../socialOperating/service.js';
import {planCapacity} from '../socialOperating/capacityPlanner.js';
import {resolveAutomationPolicy} from '../socialOperating/automationPolicyResolver.js';
import {setContentExecutionLimit} from '../contentExecution/durableQueue.js';
import {materializeWeeklyExecutionTasks,listWeeklyExecutionTasks,applyBusinessDispatchToExecutionTasks} from './executionTasks.js';
import {createWeeklyPlanningAuthority} from './planningAuthority.js';
import {createWeeklyExecutionTaskService} from './executionTasks.js';
import {INITIAL_CAPACITY_SCHEDULE_REQUIRED} from './weeklyInitialScheduleGate.js';
import {createWeeklyInitialScheduleService} from './weeklyInitialSchedule.js';
import {scheduleHash,applyFrozenWeeklySchedule} from './weeklyScheduleSnapshots.js';
import {WEEKLY_EXECUTION_FREEZES} from './weeklyExecutionGate.js';
import type {Record_} from '../storage/datastore.js';

test('first draft explicit capacity confirmation freezes actual full graph without prior cancellation or production',async t=>{
 const setup=await prepareWeeklyNonPresenterPlanningFixture(t,{ownedReferenceBytes:true,primaryStructure:true,metricTargets:['播放量']}),{f}=setup;
 const clock='2026-10-01T08:00:00Z',decisions=createSocialOperatingDecisionService(f.store,()=>clock);
 const goalRef=setup.pkg.businessContentGoalRef!;
 const goal=await decisions.getGoal('t','p',goalRef.id,goalRef.version);
 const options={operator:{type:'user' as const,id:'owner'},decidedAt:clock};
 const capacity=planCapacity({goal,desiredOriginalContents:1,desiredAdaptations:0,costPerOriginalCny:1,costPerAdaptationCny:1,readyMaterialUnits:1,materialUnitsPerOriginal:1,productionItemsPerDay:1,daysUntilDeadline:7,accounts:[{ref:{type:'owned_social_account',id:'account',version:2},accountId:'account',status:'active',weeklyPublicationCapacity:1}],interactionItemsPerWeek:10,salesLeadsPerWeek:10,expectedInteractionsPerPublication:1,expectedLeadsPerPublication:1,capabilities:{'studio.production':'available','publishing.calendar':'available','customer.attribution':'available'}},options);
 assert.equal(capacity.plan.status,'ready');await decisions.saveOperatingDecision('t','p',capacity.decision);
 const policy=resolveAutomationPolicy({goal,mode:'managed',action:'draft',capability:{key:'studio.production',availability:'available'},factsVerified:true,withinBudget:true,rightsSufficient:true},options);
 assert.equal(policy.policy.status,'allowed');await decisions.saveOperatingDecision('t','p',policy.decision);
 const packages=createWeeklyOperatingPackageService(f.store);
 const source=await packages.create('t','owner','p',{weekStart:'2026-10-05',objective:goal.objective,successCriteria:['实际发布一条视频'],enterpriseProfileRef:{type:'enterprise_profile',id:'profile',version:1},businessContentGoalRef:goalRef,capacityPlanRef:{type:'capacity_plan',id:capacity.decision.decisionId,version:1},automationPolicyRef:{type:'automation_policy',id:policy.decision.decisionId,version:1},referenceSourcePolicy:setup.pkg.referenceSourcePolicy,publicationTasks:structuredClone(setup.pkg.socialContentPackage.publicationTasks)});
 const planning=createWeeklyPlanningAuthority(f.store),initial=await planning.initialize('t',source);
 const director=await planning.runDirectorAnalysis({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:initial.version,actor:'director_agent'});
 const detailed=await planning.mergeDetailedSchedule({tenantId:'t',programId:'p',package:source,expectedPlanningVersion:director.version,actor:'business_agent'});
 const confirmed=await planning.confirm({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:detailed.version,userId:'owner'});
 const dispatched=await planning.dispatch({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:confirmed.version,actor:'business_agent'});
 assert(dispatched.dispatch);await applyBusinessDispatchToExecutionTasks(f.store,'t','p',source.packageId,source.version,dispatched.dispatch,clock);

 const old=await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,source.version);
 assert(old.some(task=>task.schedule.stepKind==='material_preparation'));assert(old.find(task=>task.schedule.stepKind==='script')!.ownBlockingReasons.includes(INITIAL_CAPACITY_SCHEDULE_REQUIRED));assert(!old.find(task=>task.schedule.stepKind==='business_outline')!.ownBlockingReasons.includes(INITIAL_CAPACITY_SCHEDULE_REQUIRED));await createWeeklyExecutionTaskService(f.store).unblock('t','p',source.packageId,old.find(task=>task.schedule.stepKind==='script')!.taskId,INITIAL_CAPACITY_SCHEDULE_REQUIRED);assert((await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,source.version)).find(task=>task.schedule.stepKind==='script')!.ownBlockingReasons.includes(INITIAL_CAPACITY_SCHEDULE_REQUIRED));
 const oldHash=scheduleHash(await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,source.version));
 for(const [scope,scopeKey]of [['tenant','*'],['account','account'],['task_type','social_content_weekly']] as const)await setContentExecutionLimit({dataStore:f.store,tenantId:'t',scope,scopeKey,maxRunning:2,updatedBy:'owner',now:new Date(clock)});
 const authority={tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,actorUserId:'owner'},service=createWeeklyInitialScheduleService(f.store,{now:()=>clock}),preview=await service.preview(authority),graph=preview.graph;assert.equal(preview.authority,'estimated_task_durations_only');assert(preview.requiredInputs.every(row=>row.missing.includes('resourceWorkingWindows')));
 const userCapacity={constraints:Object.fromEntries(graph.tasks.map(task=>[task.taskId,{resourceKey:'production',remainingMinutes:task.schedule.estimatedDurationMinutes,remainingCostCny:1,bufferMinutes:0,availableAt:clock}])),resources:{production:{concurrency:2,workingWindows:[{startAt:clock,finishAt:'2026-10-15T20:00:00Z'}]}},remainingBudgetCny:100,operationalDeadlines:Object.fromEntries(graph.tasks.filter(task=>['performance_monitoring','weekly_review','template_extraction','template_performance_validation'].includes(task.schedule.stepKind)).map(task=>[task.taskId,'2026-10-15T18:00:00Z']))};
 const newPreparation=graph.bindings.find(binding=>graph.tasks.find(task=>task.taskId===binding.planningTaskId)?.schedule.stepKind==='material_preparation')!;
 assert(newPreparation);const missing=structuredClone(userCapacity);delete missing.constraints[newPreparation.planningTaskId];
 const incomplete=await service.propose(authority,missing);assert.equal(incomplete.plan.assignments.find(row=>row.taskId===newPreparation.planningTaskId)!.startAt,null);
 await assert.rejects(service.confirm(authority,{proposalId:incomplete.proposalId,expectedVersion:source.version,inputEvidenceHash:incomplete.inputEvidenceHash}),{code:'weekly_schedule_fresh_capacity_not_feasible'});
 assert.equal((await f.store.list(WEEKLY_EXECUTION_FREEZES)).totalItems,0);assert.equal(scheduleHash(await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,source.version)),oldHash);
 const proposal=await service.propose(authority,userCapacity);
 assert.deepEqual(await service.readConfirmation(authority,proposal.proposalId),{status:'not_committed',proposalId:proposal.proposalId,sourceVersion:source.version,targetVersion:source.version+1});
 const sourceRow=(await f.store.list<Record_>('social_weekly_operating_packages',{where:{tenant_id:'t',package_id:source.packageId,version:source.version},perPage:2})).items[0]!;
 const originalPayload=sourceRow.payload;
 await f.store.update('social_weekly_operating_packages',sourceRow.id,{payload:{...source,status:'active'}});
 await assert.rejects(service.confirm(authority,{proposalId:proposal.proposalId,expectedVersion:source.version,inputEvidenceHash:proposal.inputEvidenceHash}),{code:'weekly_initial_schedule_not_pristine'});
 assert.equal((await f.store.list(WEEKLY_EXECUTION_FREEZES)).totalItems,0);
 await f.store.update('social_weekly_operating_packages',sourceRow.id,{payload:originalPayload});
 assert.equal(proposal.plan.publicationGap,0,JSON.stringify(proposal.plan.assignments.filter(a=>a.reasons.length)));
 const result=await service.confirm(authority,{proposalId:proposal.proposalId,expectedVersion:source.version,inputEvidenceHash:proposal.inputEvidenceHash});
 const committed=await service.readConfirmation(authority,proposal.proposalId);assert.equal(committed.status,'committed');if(committed.status==='committed'){assert.equal(committed.item.version,result.item.version);assert.equal(committed.snapshot.snapshotId,result.snapshot.snapshotId);}
 const retried=await service.confirm(authority,{proposalId:proposal.proposalId,expectedVersion:source.version,inputEvidenceHash:proposal.inputEvidenceHash});assert.equal(retried.item.version,result.item.version);
 assert.equal(result.item.version,source.version+1);assert.equal(result.item.executionGraphVersion,3);assert.equal(result.activated,false);
 const actual=await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,result.item.version),prep=actual.find(task=>task.schedule.stepKind==='material_preparation')!,script=actual.find(task=>task.schedule.stepKind==='script')!,video=actual.find(task=>task.schedule.stepKind==='video_generation')!,publish=actual.find(task=>task.schedule.stepKind==='publishing')!;assert(!actual.some(task=>task.schedule.stepKind==='rework'));
 assert.equal(result.snapshot.assignments.find(row=>row.targetTaskId===prep.taskId)!.sourceTaskId,newPreparation.sourceTaskId);assert.equal(result.snapshot.assignments.find(row=>row.targetTaskId===prep.taskId)!.mode,'planned');
 assert(prep);assert(!prep.ownBlockingReasons.includes(INITIAL_CAPACITY_SCHEDULE_REQUIRED));assert(!script.ownBlockingReasons.includes(INITIAL_CAPACITY_SCHEDULE_REQUIRED));assert(script.dependsOnTaskIds.includes(prep.taskId));assert(Date.parse(prep.schedule.estimatedFinishAt)<=Date.parse(script.schedule.estimatedStartAt));assert(Date.parse(video.schedule.estimatedFinishAt)<=Date.parse(publish.schedule.estimatedStartAt)-86_400_000);
 assert.equal(scheduleHash(await listWeeklyExecutionTasks(f.store,'t','p',source.packageId,source.version)),oldHash);assert.equal((await f.store.list(WEEKLY_EXECUTION_FREEZES)).totalItems,1);
 const targetRow=(await f.store.list<Record_>('social_weekly_operating_packages',{where:{tenant_id:'t',package_id:source.packageId,version:result.item.version},perPage:2})).items[0]!;await f.store.delete('social_weekly_operating_packages',targetRow.id);const pending=await service.readConfirmation(authority,proposal.proposalId);assert.equal(pending.status,'pending_recovery');if(pending.status==='pending_recovery')assert.equal(pending.snapshot.snapshotId,result.snapshot.snapshotId);
 const drifted=structuredClone(actual);drifted.find(task=>task.taskId===prep.taskId)!.inputSnapshot.injectedFact='changed after confirmation';await assert.rejects(applyFrozenWeeklySchedule(f.store,'t',result.item,drifted),{code:'weekly_schedule_target_graph_changed'});
 assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.social_publication_attempts?.length??0,0);
});
