import {withExecutionPackageGate} from './weeklyExecutionGate.js';
import {randomUUID} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,WeeklyOperatingPackage} from '../../shared/contracts/socialProgram.js';
import type {WeeklyPublicationRecovery,WeeklyPublicationRecoveryScope,WeeklyPublicationRecoverySource} from '../../shared/contracts/weeklyPublicationRecovery.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {SocialProgramError} from './service.js';
import {publicationInstant} from './publicationDeadlines.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {readStarterPublicationPackage} from '../publishing/starterPublicationPackage.js';
import {PUBLICATION_ASSIGNMENTS,PUBLICATION_ATTEMPTS,reconcileWeeklyPublication,type StoredPublicationAssignment,type DurablePublicationAttempt,type WeeklyPublishingProviderAdapter} from '../publishing/weeklyLineage.js';
import {buildPublicationAssignment} from '../digitalEmployees/publishingExecution.js';
import {createWeeklyPublishingAdapter} from '../publishing/weeklyPublishingAdapter.js';
import {validateWeeklyExecutionResults,validateWeeklyPublicationAcceptance} from '../runtime/socialWeeklyResultValidation.js';
import {createWeeklyExecutionTaskService} from './executionTasks.js';
import {withLocalQueue} from '../routes/digitalEmployeeRecords.js';
import {acquireDurableOperationLease,assertDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
export const PUBLICATION_RECOVERIES='social_weekly_publication_recoveries';
const queues=new Map<string,Promise<void>>();const obj=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return obj(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
function check(v:unknown,c:string,status=409):asserts v{if(!v)throw new SocialProgramError(c,status,c);}
async function rows(store:DataStore,c:string,where:Record<string,string|number>){const all:Record_[]=[];let total:number|undefined;for(let page=1;page<=1000;page++){const r=await store.list<Record_>(c,{where,page,perPage:250,sort:'id'});check(Number.isSafeInteger(r.totalItems)&&r.totalItems>=0&&(total===undefined||total===r.totalItems),'weekly_publication_recovery_pagination_changed');total=r.totalItems;check(r.items.every(v=>Object.entries(where).every(([k,x])=>v[k]===x)&&!all.some(o=>o.id===v.id)),'weekly_publication_recovery_pagination_invalid');all.push(...r.items);if(all.length===total)return all;check(r.items.length===250,'weekly_publication_recovery_pagination_incomplete');}throw Error('weekly_publication_recovery_pagination_incomplete');}
async function actor(store:DataStore,tenant:string,id:string){const u=await store.getById<Record_>('users',id),role=organizationRoleOrNull(u?.role);check(u?.tenantId===tenant&&role&&['social_operator','admin','super_admin'].includes(role)&&u.disabled!==true&&u.active!==false&&!['disabled','suspended'].includes(String(u.status)),'weekly_publication_recovery_actor_forbidden',403);return role;}
function metadata(p:WeeklyPublicationRecovery){const {gap,overdue,originalTaskStatus,completionProof,...base}=p;void gap;void overdue;void originalTaskStatus;void completionProof;return {...base,recordHash:socialRequestHash(base)};}
function readRecord(row:Record_,a:WeeklyPublicationRecoveryScope){const {recordHash,...p}=obj(row.payload);check(row.tenant_id===a.tenantId&&row.program_id===a.programId&&row.package_id===a.packageId&&row.package_version===a.packageVersion&&p.id===row.id&&p.tenantId===a.tenantId&&p.programId===a.programId&&p.packageId===a.packageId&&p.packageVersion===a.packageVersion&&recordHash===row.content_hash&&socialRequestHash(p)===recordHash&&row.source_key===socialRequestHash({tenantId:p.tenantId,attemptId:p.attemptId}),'weekly_publication_recovery_record_invalid');return p as WeeklyPublicationRecovery;}
async function source(store:DataStore,a:WeeklyPublicationRecoveryScope,taskId:string){
 const packages=await rows(store,'social_weekly_operating_packages',{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.packageVersion});check(packages.length===1,'weekly_publication_recovery_package_missing');const pkg=obj(packages[0]!.payload)as WeeklyOperatingPackage;check(pkg.programId===a.programId&&pkg.packageId===a.packageId&&pkg.version===a.packageVersion,'weekly_publication_recovery_package_invalid');const candidates=await rows(store,'social_weekly_execution_tasks',{tenant_id:a.tenantId,task_id:taskId});check(candidates.length===1,'weekly_publication_recovery_task_missing');const task=obj(candidates[0]!.payload)as WeeklyExecutionTask;check(candidates[0]!.program_id===a.programId&&candidates[0]!.package_id===a.packageId&&candidates[0]!.package_version===a.packageVersion&&candidates[0]!.status===task.status&&task.taskId===taskId&&task.tenantId===a.tenantId&&task.programId===a.programId&&task.packageId===a.packageId&&task.packageVersion===a.packageVersion&&task.workflowKind==='publishing'&&task.schedule?.stepKind==='publishing','weekly_publication_recovery_task_scope_invalid');const pub=pkg.socialContentPackage?.publicationTasks.find(p=>p.publicationTaskId===task.publicationTaskId&&p.accountId===task.accountId);check(pub,'weekly_publication_recovery_publication_missing');
 const assignments=await rows(store,PUBLICATION_ASSIGNMENTS,{tenant_id:a.tenantId,operating_package_id:a.packageId,operating_package_version:a.packageVersion,publication_task_id:pub.publicationTaskId});check(assignments.length>0,'weekly_publication_recovery_assignment_missing');check(assignments.length===1,'weekly_publication_recovery_assignment_ambiguous');const assignment=assignments[0]as unknown as StoredPublicationAssignment;const manifest=await readStarterPublicationPackage(a.tenantId,assignment.package_id,store);check(manifest&&manifest.tenantId===a.tenantId&&manifest.platform===pub.platform&&assignment.account_id===pub.accountId&&assignment.platform===pub.platform&&assignment.payload.assignmentId===assignment.assignment_id&&assignment.payload.assignmentHash===assignment.assignment_hash&&manifest.operatingLineage?.assignmentHash===assignment.assignment_hash,'weekly_publication_recovery_lineage_invalid');
 const rebuilt=buildPublicationAssignment({tenantId:a.tenantId,operatingPackage:pkg,publicationTask:pub,productionResult:{productionResultId:assignment.production_result_id,contentId:manifest.contentId,contentVersion:manifest.contentVersion,contentHash:manifest.contentHash,title:manifest.copy.title,body:manifest.copy.body,assets:manifest.assets.map(v=>({kind:v.kind,fileName:v.fileName,downloadUrl:v.downloadUrl,contentHash:v.contentHash})),sourceRefs:manifest.operatingLineage.upstreamRefs,acceptedAt:manifest.generatedAt}});check(socialRequestHash(rebuilt)===socialRequestHash(assignment.payload)&&rebuilt.packageId===manifest.packageId,'weekly_publication_recovery_assignment_changed');
 const attempts=await rows(store,PUBLICATION_ATTEMPTS,{tenant_id:a.tenantId,assignment_id:assignment.assignment_id});check(attempts.length>0,'weekly_publication_recovery_attempt_missing');check(attempts.length===1,'weekly_publication_recovery_attempt_ambiguous');const attempt=attempts[0]as unknown as DurablePublicationAttempt;check(attempt.package_id===manifest.packageId&&publicationInstant(attempt.started_at)!==null&&attempt.attempt_id&&attempt.provider&&!/mock|simulat|test[_-]?provider/i.test(attempt.provider),'weekly_publication_recovery_attempt_invalid');
 if(attempt.status==='published')check(publicationInstant(attempt.resolved_at??'')!==null&&publicationInstant(attempt.resolved_at??'')!>=publicationInstant(attempt.started_at)!,'weekly_publication_recovery_result_time_invalid');
 const accountCollection=pub.platform==='youtube'?'youtube_accounts':'social_accounts';const account=await store.getById<Record_>(accountCollection,pub.accountId);check(account?.tenantId===a.tenantId&&(pub.platform==='youtube'||account.platform===pub.platform),'weekly_publication_recovery_account_invalid');const accountIdentityHash=socialRequestHash({collection:accountCollection,id:account.id,tenantId:account.tenantId,platform:pub.platform,providerAccountId:account.providerAccountId??null,channelId:account.channelId??null,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null,clientId:account.clientId??null,refreshTokenHash:pub.platform==='youtube'?socialRequestHash(account.refreshToken??account.credentialRef??null):null});
 const {status:publicationStatus,...publicationInput}=pub;void publicationStatus;const publicationInputHash=socialRequestHash(publicationInput),taskInputHash=socialRequestHash({taskId:task.taskId,idempotencyKey:task.idempotencyKey,inputSnapshot:task.inputSnapshot,upstreamVersionRefs:task.upstreamVersionRefs,dependencies:task.dependsOnTaskIds,stepKind:task.schedule.stepKind});return {pkg,task,pub,assignment,manifest,attempt,accountIdentityHash,publicationInputHash,taskInputHash,accountStatus:String(account.status)};
}
function gap(attempt:DurablePublicationAttempt,accountStatus?:string){if(accountStatus&&accountStatus!=='connected')return 'weekly_publication_recovery_account_not_connected';return attempt.status==='failed'?'weekly_publication_recovery_safe_retry_not_verified':attempt.status==='published'?'weekly_publication_recovery_original_task_pending':!attempt.provider_receipt_id?'weekly_publication_recovery_provider_identity_gap':'weekly_publication_recovery_receipt_pending';}
export interface WeeklyPublicationRecoveryPorts{adapterFactory:(assignment:StoredPublicationAssignment)=>Promise<WeeklyPublishingProviderAdapter>}
export function createWeeklyPublicationRecoveryService(store:DataStore,ports:Partial<WeeklyPublicationRecoveryPorts>={}){const factory=ports.adapterFactory??(assignment=>createWeeklyPublishingAdapter({tenantId:assignment.tenant_id,accountId:assignment.account_id,platform:assignment.platform,dataStore:store}));return {
 async sources(a:WeeklyPublicationRecoveryScope,who:string):Promise<WeeklyPublicationRecoverySource[]>{await actor(store,a.tenantId,who);const found:WeeklyPublicationRecoverySource[]=[];for(const row of await rows(store,'social_weekly_execution_tasks',{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion})){const task=obj(row.payload);if(task.schedule?.stepKind!=='publishing'||task.status==='succeeded')continue;let s:Awaited<ReturnType<typeof source>>;try{s=await source(store,a,String(task.taskId));}catch(error){if(error instanceof SocialProgramError&&['weekly_publication_recovery_assignment_missing','weekly_publication_recovery_attempt_missing'].includes(error.code))continue;throw error;}found.push({taskId:s.task.taskId,publicationTaskId:s.pub.publicationTaskId,motherContentId:s.pub.motherContentId,adaptationOfPublicationTaskId:s.pub.adaptationOfPublicationTaskId??null,accountId:s.pub.accountId,platform:s.pub.platform,attemptId:s.attempt.attempt_id,attemptStatus:s.attempt.status,gap:gap(s.attempt,s.accountStatus)});}return found;},
 async create(a:WeeklyPublicationRecoveryScope,who:string,input:{taskId:string;ownerUserId:string;deadlineAt:string;reason:string}){await actor(store,a.tenantId,who);check(input&&typeof input==='object'&&!Array.isArray(input)&&Object.keys(input).every(k=>['taskId','ownerUserId','deadlineAt','reason'].includes(k))&&publicationInstant(input.deadlineAt)!==null&&typeof input.reason==='string'&&input.reason.trim()&&input.reason.length<=2000,'weekly_publication_recovery_input_invalid',400);await actor(store,a.tenantId,input.ownerUserId);const s=await source(store,a,input.taskId);const id=socialRequestHash({tenantId:a.tenantId,attemptId:s.attempt.attempt_id}).slice(0,15),old=await store.getById<Record_>(PUBLICATION_RECOVERIES,id);if(old){const p=readRecord(old,a);check(p.ownerUserId===input.ownerUserId&&p.deadlineAt===input.deadlineAt&&p.reason===input.reason.trim()&&p.createdBy===who,'weekly_publication_recovery_intent_conflict');return this.get(a,id,who);}check(s.task.status!=='succeeded','weekly_publication_recovery_no_actual_gap');await validateWeeklyPublicationAcceptance(store,s.task,s.assignment.production_result_id);const p:WeeklyPublicationRecovery={id,version:1,status:'awaiting_receipt',...a,taskId:s.task.taskId,publicationTaskId:s.pub.publicationTaskId,motherContentId:s.pub.motherContentId,adaptationOfPublicationTaskId:s.pub.adaptationOfPublicationTaskId??null,referenceSource:String(obj(s.pub).referenceSource??'')||null,assignmentId:s.assignment.assignment_id,assignmentHash:s.assignment.assignment_hash,publicationInputHash:s.publicationInputHash,taskInputHash:s.taskInputHash,publicationPackageId:s.manifest.packageId,publicationPackageHash:s.manifest.packageHash,productionResultId:s.assignment.production_result_id,accountId:s.pub.accountId,accountIdentityHash:s.accountIdentityHash,platform:s.pub.platform,attemptId:s.attempt.attempt_id,attemptStartedAt:s.attempt.started_at,attemptProvider:s.attempt.provider,providerReceiptId:s.attempt.provider_receipt_id??null,ownerUserId:input.ownerUserId,createdBy:who,deadlineAt:input.deadlineAt,reason:input.reason.trim(),createdAt:new Date().toISOString(),resumedAt:null,gap:gap(s.attempt,s.accountStatus),overdue:false,originalTaskStatus:s.task.status};const data=metadata(p);try{await store.create(PUBLICATION_RECOVERIES,{id,tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion,source_key:socialRequestHash({tenantId:a.tenantId,attemptId:p.attemptId}),payload:data,content_hash:data.recordHash});}catch(error){const saved=await store.getById<Record_>(PUBLICATION_RECOVERIES,id);if(!saved)throw error;const prior=readRecord(saved,a);check(prior.ownerUserId===input.ownerUserId&&prior.deadlineAt===input.deadlineAt&&prior.reason===input.reason.trim()&&prior.createdBy===who,'weekly_publication_recovery_intent_conflict');}return this.get(a,id,who);},
 async get(a:WeeklyPublicationRecoveryScope,id:string,who:string):Promise<WeeklyPublicationRecovery>{const role=await actor(store,a.tenantId,who),row=await store.getById<Record_>(PUBLICATION_RECOVERIES,id);check(row,'weekly_publication_recovery_not_found',404);const p=readRecord(row,a);check([p.ownerUserId,p.createdBy].includes(who)||['admin','super_admin'].includes(role),'weekly_publication_recovery_read_forbidden',403);const s=await source(store,a,p.taskId);check(p.publicationInputHash===s.publicationInputHash&&p.taskInputHash===s.taskInputHash&&p.assignmentId===s.assignment.assignment_id&&p.assignmentHash===s.assignment.assignment_hash&&p.publicationPackageId===s.manifest.packageId&&p.publicationPackageHash===s.manifest.packageHash&&p.productionResultId===s.assignment.production_result_id&&p.accountId===s.pub.accountId&&p.accountIdentityHash===s.accountIdentityHash&&p.motherContentId===s.pub.motherContentId&&p.adaptationOfPublicationTaskId===(s.pub.adaptationOfPublicationTaskId??null)&&p.attemptId===s.attempt.attempt_id&&p.attemptStartedAt===s.attempt.started_at&&p.attemptProvider===s.attempt.provider&&(!['unknown','in_flight'].includes(s.attempt.status)||(!p.providerReceiptId||p.providerReceiptId===(s.attempt.provider_receipt_id??null))),'weekly_publication_recovery_source_changed');const result={...p,gap:gap(s.attempt,s.accountStatus),overdue:publicationInstant(p.deadlineAt)!<Date.now(),originalTaskStatus:s.task.status};if(s.task.status==='succeeded'){try{await validateWeeklyExecutionResults(store,s.task,[{type:'weekly_publication_attempt',id:p.attemptId,version:1}]);check(s.task.ownBlockingReasons.length===0&&s.task.inheritedBlockingTaskIds.length===0,'weekly_publication_recovery_completion_blockers');const started=publicationInstant(s.task.schedule.actualStartedAt??''),finished=publicationInstant(s.task.schedule.actualFinishedAt??'');check(started!==null&&finished!==null&&finished>=started&&finished>=publicationInstant(s.attempt.started_at)!&&finished>=publicationInstant(s.attempt.resolved_at??'')!&&finished<=Date.now(),'weekly_publication_recovery_completion_time_unverified');result.completionProof={actualFinishedAt:s.task.schedule.actualFinishedAt!,taskId:p.taskId,attemptId:p.attemptId,platformPostId:s.attempt.platform_post_id!,providerReceiptId:s.attempt.provider_receipt_id!,evidenceHash:socialRequestHash(s.attempt),verifiedAt:new Date().toISOString()};result.gap='';}catch{result.gap='weekly_publication_recovery_completion_proof_gap';}}return result;},
 async list(a:WeeklyPublicationRecoveryScope,who:string){const role=await actor(store,a.tenantId,who),all:WeeklyPublicationRecovery[]=[];for(const row of await rows(store,PUBLICATION_RECOVERIES,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion})){const p=readRecord(row,a);if([p.createdBy,p.ownerUserId].includes(who)||['admin','super_admin'].includes(role))all.push(await this.get(a,p.id,who));}return all;},
 async resolve(a:WeeklyPublicationRecoveryScope,id:string,who:string,input:{expectedVersion:number}){return this.resume(a,id,who,input);},
 async resume(a:WeeklyPublicationRecoveryScope,id:string,who:string,input:{expectedVersion:number}){check(input&&typeof input==='object'&&!Array.isArray(input)&&Object.keys(input).length===1&&Number.isSafeInteger(input.expectedVersion),'weekly_publication_recovery_input_invalid',400);return withLocalQueue(queues,JSON.stringify([a.tenantId,id]),async()=>withExecutionPackageGate(store,a,async assert=>{const lease=await acquireDurableOperationLease({dataStore:store,tenantId:a.tenantId,scope:'weekly_publication_recovery',subjectId:id,ownerId:randomUUID(),leaseDurationMs:120000});check(lease,'weekly_publication_recovery_busy');try{const p=await this.get(a,id,who);check(p.ownerUserId===who,'weekly_publication_recovery_owner_required',403);check(p.version===input.expectedVersion,'weekly_publication_recovery_version_conflict');let s=await source(store,a,p.taskId);check(s.accountStatus==='connected','weekly_publication_recovery_account_not_connected');check(s.task.status!=='leased'&&!s.task.lease&&!['cancelled','dead_letter'].includes(s.task.status),'weekly_publication_recovery_task_not_recoverable');if(s.attempt.status==='failed')throw new SocialProgramError('weekly_publication_recovery_safe_retry_not_verified',409,'平台明确拒绝后的安全重试尚未确认，保留原尝试。');if(s.attempt.status!=='published'){check(s.attempt.provider_receipt_id,'weekly_publication_recovery_provider_identity_gap');const adapter=await factory(s.assignment);check(adapter.provider===p.attemptProvider&&adapter.platform===s.pub.platform&&adapter.capability==='available','weekly_publication_recovery_lookup_unavailable');await assert();await reconcileWeeklyPublication({assignment:s.assignment.payload,publicationPackage:s.manifest,adapter,dataStore:store});await assert();s=await source(store,a,p.taskId);await this.get(a,id,who);}check(s.attempt.status==='published','weekly_publication_recovery_receipt_pending');await validateWeeklyExecutionResults(store,s.task,[{type:'weekly_publication_attempt',id:p.attemptId,version:1}]);
 check(s.pkg.status==='active','weekly_publication_recovery_package_inactive');if(s.task.status!=='succeeded'){const allowed=new Set(['weekly_real_publishing_disabled','publishing_provider_unavailable','weekly_publication_admission_failed','weekly_content_acceptance_unverified','publication_receipt_reconciliation_pending','provider_capability_not_verified','provider_capability_revoked','provider_capability_expired_or_unavailable',...(['youtube','facebook','instagram','tiktok'].flatMap(platform=>[`${platform}_account_not_connected`,`${platform}_credential_unavailable`,`${platform}_account_not_found`]))]);if(s.task.lastError?.code&&allowed.has(s.task.lastError.code))allowed.add(s.task.lastError.code);const service=createWeeklyExecutionTaskService(store);for(const reason of s.task.ownBlockingReasons.filter(r=>allowed.has(r))){await assertDurableOperationLease({dataStore:store,lease});await service.unblock(a.tenantId,a.programId,a.packageId,s.task.taskId,reason);}}
 const data=metadata({...p,providerReceiptId:p.providerReceiptId??s.attempt.provider_receipt_id??null,status:'resume_requested',version:p.status==='resume_requested'?p.version:p.version+1,resumedAt:p.resumedAt??new Date().toISOString()});await assert();await assertDurableOperationLease({dataStore:store,lease});check(await store.update(PUBLICATION_RECOVERIES,id,{payload:data,content_hash:data.recordHash}),'weekly_publication_recovery_save_failed');return {item:await this.get(a,id,who),publishesSubmitted:0 as const,originalAttemptId:p.attemptId};}finally{await releaseDurableOperationLease({dataStore:store,lease});}}));}
};}
