import {createHash} from 'node:crypto';
import {planMobileChatMessages} from '../agents/mobileChatStyle.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {publicationInstant} from './publicationDeadlines.js';
import {SocialProgramError} from './service.js';
import {readWeeklyCustomerStep,WEEKLY_CUSTOMER_BINDINGS,type WeeklyCustomerAuthority} from '../runtime/socialWeeklyCustomerBridge.js';
import {withDigitalEmployeeRunLock} from '../digitalEmployees/runControl.js';
import type {WeeklyCustomerSendRecovery,WeeklyCustomerSendRecoverySource} from '../../shared/contracts/weeklyCustomerSendRecovery.js';
export const CUSTOMER_SEND_RECOVERIES='social_weekly_customer_send_recoveries';
const obj=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return obj(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
const fail=(code:string,status=409):never=>{throw new SocialProgramError(code,status,code);};
function requireProof(v:unknown,code:string):asserts v{if(!v)fail(code);}
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
async function rows(store:DataStore,c:string,where:Record<string,string|number>){const all:Record_[]=[];for(let page=1;;page++){const r=await store.list<Record_>(c,{where,page,perPage:250,sort:'id'});requireProof(r.items.every(row=>Object.entries(where).every(([k,v])=>row[k]===v))&&!r.items.some(row=>all.some(x=>x.id===row.id)),'weekly_send_recovery_pagination_invalid');all.push(...r.items);if(page>=r.totalPages){requireProof(all.length===r.totalItems,'weekly_send_recovery_pagination_incomplete');return all;}requireProof(r.items.length===250,'weekly_send_recovery_pagination_incomplete');}}
async function member(store:DataStore,tenant:string,id:string){const u=await store.getById<Record_>('users',id);const role=organizationRoleOrNull(u?.role);if(!u||u.tenantId!==tenant||!role||u.disabled===true||u.status==='disabled')fail('weekly_send_recovery_actor_forbidden',403);return role!;}
const sameScope=(a:WeeklyCustomerAuthority,p:WeeklyCustomerSendRecovery)=>p.tenantId===a.tenantId&&p.programId===a.programId&&p.packageId===a.packageId&&p.packageVersion===a.packageVersion;
async function scopeContext(store:DataStore,a:WeeklyCustomerAuthority,runId:string,itemId:string){
 const bindings=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion});requireProof(bindings.length===1&&bindings[0]!.run_id===runId,'weekly_send_recovery_binding_invalid');
 const run=await store.getById<Record_>('workflow_runs',runId);
 const observation=await readWeeklyCustomerStep(store,a,runId,'customer_followup_dispatch');const task=await store.getById<Record_>('workflow_tasks',observation.taskId);requireProof(task?.tenant_id===a.tenantId&&task.run_id===runId&&task.task_key==='followup_dispatch'&&task.agent_role==='customer','weekly_send_recovery_task_invalid');
 const item=await store.getById<Record_>('followup_batch_items',itemId);requireProof(item?.tenant_id===a.tenantId,'weekly_send_recovery_item_invalid');const batch=await store.getById<Record_>('followup_batches',String(item.batch_id));requireProof(batch?.tenant_id===a.tenantId&&batch.run_id===runId&&['approved','completed','needs_attention','partial_failed'].includes(String(batch.status))&&batch.approved_version===batch.version,'weekly_send_recovery_approval_invalid');const drafts=await rows(store,'workflow_tasks',{tenant_id:a.tenantId,run_id:runId,task_key:'followup_batch_draft'});requireProof(drafts.length===1&&batch.task_id===drafts[0]!.id&&batch.goal_id===run?.goal_id,'weekly_send_recovery_batch_scope_invalid');const allBatches=(await rows(store,'followup_batches',{tenant_id:a.tenantId,run_id:runId})).filter(b=>b.task_id===drafts[0]!.id&&b.segment_id===batch.segment_id&&b.goal_id===batch.goal_id).sort((l,r)=>Number(r.version)-Number(l.version));requireProof(allBatches[0]?.id===batch.id&&allBatches.filter(b=>b.version===batch.version).length===1,'weekly_send_recovery_old_approval');const approval=await readWeeklyCustomerStep(store,a,runId,'customer_followup_approval');requireProof(approval.status==='succeeded'||approval.reason==='weekly_customer_approval_pending','weekly_send_recovery_approval_invalid');const receipt=obj(item.provider_receipt);requireProof(typeof receipt.claimToken==='string'&&/^[a-f0-9-]{36}$/i.test(receipt.claimToken)&&receipt.approvedBatchVersion===batch.version&&receipt.approvedContentHash===item.content_hash,'weekly_send_recovery_claim_invalid');
 return {observation,task,item,batch,receipt,run};
}
/** Only signed, current per-message provider evidence can discharge an unknown send. Never sends. */
export function verifyCompleteSignedFollowupReceipt(item:Record_,batch:Record_){
 const r=obj(item.provider_receipt),expected=r.expectedMessages,messages=r.messages,statuses=r.statuses;const actualExpected=item.send_mode==='template'?[item.draft_body]:planMobileChatMessages(item.draft_body).messages;const claimedAt=publicationInstant(r.claimedAt);requireProof(claimedAt!==null&&JSON.stringify(expected)===JSON.stringify(actualExpected),'weekly_send_recovery_frozen_request_invalid');
 requireProof(r.approvedBatchVersion===batch.version&&r.approvedContentHash===item.content_hash&&Array.isArray(expected)&&expected.length>0&&Array.isArray(messages)&&messages.length===expected.length&&Array.isArray(statuses),'weekly_send_recovery_receipt_incomplete');
 const ids=new Set<string>();for(let index=0;index<expected.length;index++){const ms=messages.filter((m:any)=>m.index===index);requireProof(ms.length===1&&typeof ms[0].messageId==='string'&&!/^(mock|simulat)/i.test(ms[0].messageId)&&ms[0].body===expected[index]&&!ids.has(ms[0].messageId),'weekly_send_recovery_message_identity_invalid');ids.add(ms[0].messageId);const ss=statuses.filter((s:any)=>s.messageId===ms[0].messageId);requireProof(ss.length===1&&['sent','delivered','read'].includes(ss[0].status)&&publicationInstant(ss[0].occurredAt)!==null&&publicationInstant(ss[0].occurredAt)!>=Math.floor(claimedAt!/1000)*1000,'weekly_send_recovery_terminal_receipt_required');const signed=obj(ss[0].signedClaimEvidence);requireProof(signed.verifiedSignature===true&&signed.claimToken===r.claimToken&&signed.index===index&&String(signed.recipientId).replace(/\D/g,'')===String(item.wa_number).replace(/\D/g,'')&&signed.approvedBatchVersion===batch.version&&signed.approvedContentHash===item.content_hash,'weekly_send_recovery_signed_identity_invalid');}
 return {messageIds:[...ids],claimToken:r.claimToken};
}
export function createWeeklyCustomerSendRecoveryService(store:DataStore){
 const publicItem=(p:WeeklyCustomerSendRecovery&{claimToken?:string;recipient?:string})=>{const {claimToken,recipient,...safe}=p;void claimToken;void recipient;return safe;};
 async function get(a:WeeklyCustomerAuthority,id:string,actor:string){await member(store,a.tenantId,actor);const row=await store.getById<Record_>(CUSTOMER_SEND_RECOVERIES,id);const p=obj(row?.payload) as WeeklyCustomerSendRecovery;requireProof(row?.tenant_id===a.tenantId&&p.id===id&&sameScope(a,p)&&row.content_hash===hash(p),'weekly_send_recovery_not_found');const c=await scopeContext(store,a,p.runId,p.itemId);requireProof(c.task.id===p.taskId&&c.batch.id===p.batchId&&c.batch.version===p.batchVersion&&c.batch.content_hash===p.batchContentHash&&c.item.content_hash===p.itemContentHash&&hash(c.receipt.claimToken)===p.claimTokenHash&&String(c.item.segment_member_id)===p.memberId&&String(c.item.customer_id)===p.customerId&&hash(String(c.item.wa_number).replace(/\D/g,''))===p.recipientHash,'weekly_send_recovery_source_drift');if(p.status==='resolved'){requireProof(c.task.status==='succeeded','weekly_send_recovery_resolved_task_drift');const items=await rows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:c.batch.id});const receipts=items.filter(i=>!['excluded','cancelled'].includes(String(i.status))).map(item=>({itemId:item.id,...verifyCompleteSignedFollowupReceipt(item,c.batch)}));const receiptIds=receipts.flatMap(r=>r.messageIds);requireProof(new Set(receiptIds).size===receiptIds.length,'weekly_send_recovery_receipt_duplicate');return {...publicItem(p),resolvedProof:{taskId:c.task.id,runId:p.runId,receiptIds,evidenceHash:hash({scope:a,batchVersion:p.batchVersion,batchHash:p.batchContentHash,receipts}),verifiedAt:new Date().toISOString()}};}return publicItem(p);}
 async function sources(a:WeeklyCustomerAuthority,actor:string):Promise<WeeklyCustomerSendRecoverySource[]>{const role=await member(store,a.tenantId,actor);const bindings=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion});requireProof(bindings.length<=1,'weekly_send_recovery_binding_invalid');if(!bindings.length)return [];const runId=String(bindings[0]!.run_id);const batches=await rows(store,'followup_batches',{tenant_id:a.tenantId,run_id:runId});const result:WeeklyCustomerSendRecoverySource[]=[];for(const batch of batches){const items=await rows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:batch.id});for(const item of items.filter(i=>i.exclusion_reason==='send_outcome_unknown'||i.status==='partial_sent')){const c=await scopeContext(store,a,runId,item.id);result.push({channel:'whatsapp',runId,taskId:c.task.id,batchId:batch.id,itemId:item.id,customerId:String(item.customer_id),memberId:String(item.segment_member_id),recipientMasked:'…'+String(item.wa_number).slice(-4),status:String(item.status),claimTokenHash:hash(c.receipt.claimToken),batchVersion:Number(batch.version),reason:String(item.exclusion_reason||'partial_sent'),canCreate:['super_admin','admin'].includes(role)||actor===c.batch.approved_by||actor===c.run?.started_by||actor===c.run?.created_by});}}return result;}
 return {get,sources,async list(a:WeeklyCustomerAuthority,actor:string){await member(store,a.tenantId,actor);const found=await rows(store,CUSTOMER_SEND_RECOVERIES,{tenant_id:a.tenantId});return Promise.all(found.filter(r=>sameScope(a,obj(r.payload) as WeeklyCustomerSendRecovery)).map(r=>get(a,r.id,actor)));},
 async create(a:WeeklyCustomerAuthority,actor:string,input:{runId:string;itemId:string;ownerUserId:string;deadlineAt:string;reason:string}){
 const role=await member(store,a.tenantId,actor);await member(store,a.tenantId,input.ownerUserId);requireProof(publicationInstant(input.deadlineAt)!==null&&typeof input.reason==='string'&&input.reason.trim(),'weekly_send_recovery_input_invalid');return withDigitalEmployeeRunLock(a.tenantId,input.runId,async()=>{const c=await scopeContext(store,a,input.runId,input.itemId);if(!['super_admin','admin'].includes(role)&&actor!==c.batch.approved_by&&actor!==c.batch.created_by&&actor!==c.run?.started_by&&actor!==c.run?.created_by)fail('weekly_send_recovery_issuer_forbidden',403);requireProof(c.item.exclusion_reason==='send_outcome_unknown'||c.item.status==='partial_sent','weekly_send_recovery_anomaly_required');const key=hash([a,input.runId,input.itemId,c.receipt.claimToken]);const old=await rows(store,CUSTOMER_SEND_RECOVERIES,{tenant_id:a.tenantId,source_key:key});requireProof(old.length<=1,'weekly_send_recovery_ambiguous');if(old.length){const p=await get(a,old[0]!.id,actor);requireProof(p.ownerUserId===input.ownerUserId&&p.deadlineAt===input.deadlineAt&&p.reason===input.reason.trim(),'weekly_send_recovery_intent_conflict');return p;}const id=key.slice(0,15);const p:WeeklyCustomerSendRecovery={...a,channel:'whatsapp',id,runId:input.runId,taskId:c.task.id,batchId:c.batch.id,itemId:c.item.id,customerId:String(c.item.customer_id),ownerUserId:input.ownerUserId,createdBy:actor,deadlineAt:input.deadlineAt,reason:input.reason.trim(),batchVersion:Number(c.batch.version),batchContentHash:String(c.batch.content_hash),itemContentHash:String(c.item.content_hash),claimTokenHash:hash(c.receipt.claimToken),memberId:String(c.item.segment_member_id),recipientMasked:'…'+String(c.item.wa_number).slice(-4),recipientHash:hash(String(c.item.wa_number).replace(/\D/g,'')),sourceRef:{type:'weekly_customer_followup_batch',id:c.batch.id,version:Number(c.batch.version)},status:'awaiting_receipt',version:1,createdAt:new Date().toISOString(),resolvedAt:null};requireProof(await store.create(CUSTOMER_SEND_RECOVERIES,{id,tenant_id:a.tenantId,source_key:key,payload:p,content_hash:hash(p)}),'weekly_send_recovery_save_failed');return p;});
 },
 async resolve(a:WeeklyCustomerAuthority,id:string,actor:string,input:{expectedVersion:number}){const original=await get(a,id,actor);if(original.ownerUserId!==actor)fail('weekly_send_recovery_owner_required',403);return withDigitalEmployeeRunLock(a.tenantId,original.runId,async()=>{const p=await get(a,id,actor);if(p.status==='resolved'){requireProof(input.expectedVersion===p.version||input.expectedVersion===p.version-1,'weekly_send_recovery_version_conflict');return {item:p,recoveredTaskId:p.taskId,runAdvanced:false as const,messagesSent:0 as const};}requireProof(input.expectedVersion===p.version,'weekly_send_recovery_version_conflict');const c=await scopeContext(store,a,p.runId,p.itemId);requireProof(c.batch.version===p.batchVersion&&c.batch.content_hash===p.batchContentHash&&c.item.content_hash===p.itemContentHash&&hash(c.receipt.claimToken)===p.claimTokenHash,'weekly_send_recovery_source_drift');verifyCompleteSignedFollowupReceipt(c.item,c.batch);
 const items=await rows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:c.batch.id});for(const item of items.filter(x=>!['excluded','cancelled'].includes(String(x.status))))verifyCompleteSignedFollowupReceipt(item,c.batch);
 requireProof(c.observation.status==='succeeded'||c.observation.reason==='weekly_customer_dispatch_pending','weekly_send_recovery_original_proof_pending');const run=await store.getById<Record_>('workflow_runs',p.runId);requireProof(run?.tenant_id===a.tenantId&&!['paused','cancelled','failed'].includes(String(run.status)),'weekly_send_recovery_run_not_recoverable');requireProof(!['running','cancelled','skipped'].includes(String(c.task.status))&&!c.task.lease_token,'weekly_send_recovery_task_not_recoverable');const upstream=await rows(store,'workflow_tasks',{tenant_id:a.tenantId,run_id:p.runId});const rawDeps=typeof c.task.depends_on==='string'?JSON.parse(c.task.depends_on):c.task.depends_on??[];requireProof(Array.isArray(rawDeps)&&rawDeps.every(key=>typeof key==='string'&&upstream.filter(t=>t.task_key===key).length===1&&['succeeded','skipped'].includes(String(upstream.find(t=>t.task_key===key)?.status))),'weekly_send_recovery_dependencies_pending');
 if(c.task.status!=='succeeded')requireProof(await store.update('workflow_tasks',c.task.id,{status:'succeeded',blocked_reason:'',business_refs:c.observation.resultRefs,output:{...obj(c.task.output),sendRecovery:{recoveryId:id,batchId:c.batch.id,claimTokenHash:p.claimTokenHash,messagesSent:0,source:'verified_provider_receipts'},dataStatus:'verified'},updated_at:new Date().toISOString()}),'weekly_send_recovery_task_save_failed');
 const saved:WeeklyCustomerSendRecovery={...p,status:'resolved',version:p.version+1,resolvedAt:new Date().toISOString()};requireProof(await store.update(CUSTOMER_SEND_RECOVERIES,id,{payload:saved,content_hash:hash(saved)}),'weekly_send_recovery_save_failed');return {item:saved,recoveredTaskId:c.task.id,runAdvanced:false as const,messagesSent:0 as const};});}
 };
}
