import test from 'node:test';import assert from 'node:assert/strict';
import type {SocialWeeklyPublicationTask,WeeklyOperatingPackage,WeeklyReferenceSourcePolicy} from '../../shared/contracts/socialProgram.js';
import {weeklyProductionPopulation} from './weeklyProductionPopulation.js';
import {allocateWeeklyReferenceSources} from './weeklyReferenceSources.js';
import {buildWeeklyOperatingScheduleSkeleton} from './planningAuthority.js';
const pub=(id:string,mother=id,inventory=false)=>({publicationTaskId:id,motherContentId:mother,accountId:'account',platform:'tiktok',publishWindow:'2026-10-15T12:00:00Z',...(inventory?{inventoryReuseRef:{type:'weekly_inventory_binding',id:'a'.repeat(15),version:1}}:{})})as SocialWeeklyPublicationTask;
const newItems=Array.from({length:5},(_,i)=>pub(`new${i}`));
test('inventory never changes confirmed source percentages or owns a new-production allocation',()=>{for(const ownedPercent of [40,20]){const policy:WeeklyReferenceSourcePolicy={profile:'b2b_established',ownedPercent,externalPercent:100-ownedPercent,allocationUnit:'mother_content'},mixed=[pub('stock1','stock1',true),...newItems,pub('stock2','new0',true),pub('variant','new1')];assert.deepEqual([...allocateWeeklyReferenceSources(mixed,policy)], [...allocateWeeklyReferenceSources(newItems,policy)]);assert.equal(allocateWeeklyReferenceSources(mixed,policy).has('stock1'),false);assert.equal([...allocateWeeklyReferenceSources(mixed,policy).values()].filter(s=>s==='owned').length,ownedPercent===40?2:1);}});
test('planning skeleton excludes inventory even if inventory and new publication share a mother label',()=>{const items=[pub('stock','new0',true),...newItems,pub('variant','new1')],pkg={packageId:'w',version:2,objective:'周交付',createdAt:'2026-10-10T00:00:00Z',referenceSourcePolicy:{profile:'b2b_established',ownedPercent:40,externalPercent:60,allocationUnit:'mother_content'},socialContentPackage:{publicationTasks:items}}as WeeklyOperatingPackage;const skeleton=buildWeeklyOperatingScheduleSkeleton(pkg);assert.equal(skeleton.slots.length,5);assert.ok(skeleton.slots.every(s=>!s.publicationTaskIds.includes('stock')));assert.equal(skeleton.slots.find(s=>s.motherContentId==='new1')?.quantity,2);assert.equal(skeleton.slots.filter(s=>s.referenceSource==='owned').length,2);});
test('all inventory gives zero new mother/variant counts and no synthetic planning slots',()=>{const items=[pub('stock1','m',true),pub('stock2','m',true)],count=weeklyProductionPopulation(items);assert.equal(count.newMotherContentTarget,0);assert.equal(count.newAdaptationVersionTarget,0);assert.equal(count.inventoryPublicationTarget,2);assert.equal(count.totalPublicationTarget,2);assert.equal(allocateWeeklyReferenceSources(items,null).size,0);const skeleton=buildWeeklyOperatingScheduleSkeleton({packageId:'w',version:1,createdAt:'now',socialContentPackage:{publicationTasks:items}}as WeeklyOperatingPackage);assert.equal(skeleton.slots.length,0);});
import {packageFromInput} from './weeklyOperatingPackageSupport.js';
function normalized(publications:SocialWeeklyPublicationTask[],originalContentTarget:number){return packageFromInput({input:{weekStart:'2026-10-12',objective:'交付',successCriteria:['发布'],originalContentTarget,accountPlans:[{accountId:'account',publicationCount:publications.length}],publicationTasks:publications,referenceSourcePolicy:{profile:'b2b_established',ownedPercent:40,externalPercent:60,allocationUnit:'mother_content'}},programId:'p',userId:'u',accounts:[{accountId:'account',programId:'p',platform:'tiktok',status:'active'}as any],packageId:'w',contentPackageId:'content',version:1,previousVersion:null,program:{route:'account_repair'}});}
test('normalized mixed package counts only new producers and never chooses inventory as adaptation parent',()=>{const p=normalized([pub('stock','same',true),pub('new','same'),pub('variant','same'),pub('stock2','other',true)],2);assert.equal(p.socialContentPackage.originalContentTarget,1);assert.equal(p.socialContentPackage.adaptationVersionTarget,1);assert.equal(p.socialContentPackage.publicationTaskTarget,4);assert.equal(p.socialContentPackage.publicationTasks[1]!.adaptationOfPublicationTaskId,null);assert.equal(p.socialContentPackage.publicationTasks[2]!.adaptationOfPublicationTaskId,'new');});
test('zero new mothers survives all-inventory normalization and rejects any new producer with zero quota',()=>{const items=[pub('stock1','m',true),pub('stock2','m',true)];const p=normalized(items,0);assert.equal(p.socialContentPackage.originalContentTarget,0);assert.equal(p.socialContentPackage.adaptationVersionTarget,0);assert.equal(p.socialContentPackage.publicationTaskTarget,2);const again=normalized(p.socialContentPackage.publicationTasks,p.socialContentPackage.originalContentTarget);assert.equal(again.socialContentPackage.originalContentTarget,0);assert.deepEqual(again.socialContentPackage.publicationTasks,p.socialContentPackage.publicationTasks);assert.throws(()=>normalized([pub('stock','m',true),pub('new','new')],0),e=>(e as any).code==='weekly_new_mother_target_required');});
test('explicit ordinary mother labels report actual population rather than an unattained numeric quota',()=>{const p=normalized([pub('a','one'),pub('b','one'),pub('c','one')],2);assert.equal(p.socialContentPackage.originalContentTarget,1);assert.equal(p.socialContentPackage.adaptationVersionTarget,2);assert.equal(p.socialContentPackage.publicationTasks[1]!.adaptationOfPublicationTaskId,'a');assert.equal(p.socialContentPackage.publicationTasks[2]!.adaptationOfPublicationTaskId,'a');});
