import test from 'node:test';import assert from 'node:assert/strict';import {runningEvidenceFixture as prepared} from './weeklyRunningResourceEvidence.fixture.js';

test('durable running identity/lease/receipts/queue limits are observable without inventing ETA, resource or zero cost',async()=>{const f=await prepared();try{const result=await f.service.read(f.scope);assert.equal(result.lease.status,'live');assert.match(result.lease.tokenHash!,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(result).includes('private-token'));assert.equal(result.providerReceipts[0]?.providerTaskId,'remote');assert.equal(result.configuredQueueLimits[0]?.maxRunning,2);assert.equal(result.remainingCostCny,null);assert.equal(result.expectedFinishAt,null);assert.equal(result.resourceKey,null);assert.equal(result.reservationEligible,false);assert.ok(result.gaps.includes('remaining_operation_manifest_missing'));assert.ok(!JSON.stringify(result).includes('estimatedRemainingSeconds'));}finally{await f.cleanup();}});
test('expired real lease remains explicit gap, cross version and duplicate content bindings reject',async()=>{const f=await prepared();try{f.tables.durable_operation_leases![0]!.expires_at='2026-10-08T23:59:59Z';f.tables.content_execution_jobs![0]!.lease_expires_at='2026-10-08T23:59:59Z';assert.equal((await f.service.read(f.scope)).lease.status,'expired');await assert.rejects(f.service.read({...f.scope,packageVersion:2}));f.tables.starter_social_content_tasks!.push({...f.tables.starter_social_content_tasks![0]!,id:'duplicate'});await assert.rejects(f.service.read(f.scope));}finally{await f.cleanup();}});
test('known terminal cost and unknown initiated operation never prove whole remaining cost is zero',async()=>{const f=await prepared();try{const common={tenant_id:'t',run_id:'run',task_id:'content',schema_version:'starter-198.usage.v1',agent_role:'content',capability:'studio.ai_video',occurred_at:f.now.toISOString()};const usage={cost_status:'known',estimated_cost_cny:5,reserved_cost_delta_cny:5,settled_cost_cny:0,output_count:0};f.tables.starter_usage_ledger=[{id:'reserve',...common,reservation_id:'paid',event_type:'reserve',state:'reserved',usage},{id:'terminal',...common,reservation_id:'paid',event_type:'terminal',state:'settled',usage:{...usage,reserved_cost_delta_cny:-5,settled_cost_cny:5,output_count:1}},{id:'unknown',...common,reservation_id:'future',event_type:'reserve',state:'reserved',usage:{...usage,cost_status:'unknown',estimated_cost_cny:null,reserved_cost_delta_cny:null,settled_cost_cny:null}}];const evidence=await f.service.read(f.scope);assert.equal(evidence.operationCosts.length,3);assert.equal(evidence.remainingCostCny,null);assert.equal(evidence.operationCosts.find(c=>c.reservationId==='future')?.settledCostCny,null);assert.ok(evidence.gaps.includes('initiated_operation_cost_unknown'));f.tables.starter_usage_ledger.push({...f.tables.starter_usage_ledger[0]!,id:'duplicate'});await assert.rejects(f.service.read(f.scope));}finally{await f.cleanup();}});

test('the actual three queue limits stay independent and exact overrides beat wildcard configuration',async()=>{const f=await prepared();try{
 const stamp=f.now.toISOString();f.tables.content_execution_limits!.push({id:'account-default',tenant_id:'t',limit_scope:'account',scope_key:'*',max_running:5,updated_by:'owner',created_at:stamp,updated_at:stamp},{id:'account-exact',tenant_id:'t',limit_scope:'account',scope_key:'account',max_running:1,updated_by:'owner',created_at:stamp,updated_at:stamp},{id:'video-limit',tenant_id:'t',limit_scope:'task_type',scope_key:'social_video',max_running:3,updated_by:'owner',created_at:stamp,updated_at:stamp});
 const item=await f.service.read(f.scope);assert.equal(item.observedResources.length,3);const tenant=item.observedResources.find(r=>r.scope==='tenant')!,account=item.observedResources.find(r=>r.scope==='account')!,type=item.observedResources.find(r=>r.scope==='task_type')!;
 assert.equal(tenant.observation.availableSlots,1);assert.equal(account.configuration.limitId,'account-exact');assert.equal(account.configuration.maximumRunning,1);assert.equal(account.observation.availableSlots,0);assert.equal(type.observation.availableSlots,2);assert.equal(new Set(item.observedResources.map(r=>r.resourceKey)).size,3);assert.equal(item.resourceKey,null);assert.equal(item.reservationEligible,false);assert.equal(item.expectedFinishAt,null);assert.equal(item.remainingCostCny,null);assert.ok(item.gaps.includes('planner_resource_vector_integration_missing'));assert.ok(!JSON.stringify(item.observedResources).includes('private-token'));
 }finally{await f.cleanup();}});
test('missing or expired occupation proof never becomes a free resource slot',async()=>{const f=await prepared();try{
 f.tables.content_execution_jobs!.push({...f.tables.content_execution_jobs![0]!,id:'running-without-lease',job_key:'second',run_id:'other-real-run'});
 const item=await f.service.read(f.scope),tenant=item.observedResources[0]!;assert.equal(tenant.observation.runningJobCount,2);assert.equal(tenant.observation.verifiedOccupiedCount,1);assert.equal(tenant.observation.unverifiedOccupancyCount,1);assert.equal(tenant.observation.availableSlots,null);assert.ok(item.gaps.includes('queue_resource_occupancy_unverified'));
 f.tables.content_execution_jobs!.pop();f.tables.durable_operation_leases![0]!.expires_at='2026-10-08T23:59:59Z';f.tables.content_execution_jobs![0]!.lease_expires_at='2026-10-08T23:59:59Z';const expired=await f.service.read(f.scope);assert.equal(expired.observedResources[0]!.observation.verifiedOccupiedCount,0);assert.equal(expired.observedResources[0]!.observation.availableSlots,null);
 }finally{await f.cleanup();}});
test('actual resource scan traverses more than one page and excludes foreign tenant work',async()=>{const f=await prepared();try{
 const job=f.tables.content_execution_jobs![0]!,lease=f.tables.durable_operation_leases![0]!;for(let i=1;i<=110;i++){f.tables.content_execution_jobs!.push({...job,id:`job-${i}`,job_key:`job:key-${i}`,run_id:`run-${i}`});f.tables.durable_operation_leases!.push({...lease,id:`lease-${i}`,subject_id:`job-${i}`});}
 f.tables.content_execution_jobs!.push({...job,id:'foreign-job',tenant_id:'foreign',job_key:'foreign'});f.tables.durable_operation_leases!.push({...lease,id:'foreign-lease',tenant_id:'foreign',subject_id:'foreign-job'});
 const item=await f.service.read(f.scope),pool=item.observedResources[0]!;assert.equal(pool.observation.runningJobCount,111);assert.equal(pool.observation.verifiedOccupiedCount,111);assert.equal(pool.observation.availableSlots,0);assert.equal(pool.observation.unverifiedOccupancyCount,0);assert.ok(!pool.observation.liveJobIds.includes('foreign-job'));
 }finally{await f.cleanup();}});

test('a real occupancy mutation during observation rejects the mixed snapshot',async()=>{const f=await prepared();try{
 const original=f.store.list;let reads=0;f.store.list=async<T>(collection:string,query:import('../storage/datastore.js').ListQuery={})=>{if(collection==='content_execution_jobs'&&query.where?.status==='running'&&query.page===1&&++reads===2)f.tables.content_execution_jobs![0]!.worker_id='another-live-worker';return original<T>(collection,query);};
 await assert.rejects(f.service.read(f.scope),(error:unknown)=>Boolean(error&&typeof error==='object'&&'code' in error&&error.code==='weekly_queue_resource_observation_changed'));
 }finally{await f.cleanup();}});
