import {createHash}from'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import {createCrossWeekMaterialContinuationService,crossWeekMaterialSourceInputHash} from './weeklyCrossWeekMaterialContinuations.js';
import type {WeeklyMaterialRequest} from './weeklyMaterialRequests.js';
export function fixture(){const request:WeeklyMaterialRequest={requestId:'originalrequest',tenantId:'tenant',programId:'program',requirementKey:'real-product',requirements:'真实产品正面',assigneeUserId:'uploader',reviewerUserId:'reviewer',dueAt:'2026-10-09T08:00:00Z',verificationDueAt:'2026-10-09T09:00:00Z',timeZone:'UTC',status:'missing',consumers:[{taskId:'original',packageId:'old',packageVersion:1,requirement:'真实产品正面'}],submissions:[],history:[{action:'created',actor:'issuer',at:'2026-10-01T00:00:00Z'}],createdAt:'2026-10-01T00:00:00Z',updatedAt:'2026-10-01T00:00:00Z'};
 const data:Record<string,Record_[]>={users:['uploader','reviewer','issuer','other'].map(id=>({id,tenantId:'tenant',role:'admin'})),social_weekly_material_requests:[{id:request.requestId,tenant_id:'tenant',program_id:'program',status:request.status,payload:request}],social_weekly_operating_packages:[],social_weekly_execution_tasks:[]};
 for(const id of ['old','next']){const pub={publicationTaskId:`pub-${id}`,materialRequirement:{required:true,requestIds:[request.requestId],bindings:[{requirementId:'required-product',requestId:request.requestId}]}};data.social_weekly_operating_packages!.push({id:`pkg-${id}`,tenant_id:'tenant',program_id:'program',package_id:id,version:1,payload:{programId:'program',packageId:id,version:1,weekStart:id==='old'?'2026-10-05':'2026-10-12',socialContentPackage:{publicationTasks:[pub]},agentPlanning:{dispatch:{scheduleItems:[{publicationTaskId:pub.publicationTaskId,materialEvidenceRequirements:{items:[{requirementId:'required-product',classification:'human_irreplaceable'}]}}]}}}});for(const step of ['material_readiness','script']){const taskId=step==='script'?`script-${id}`:id==='old'?'original':'target';data.social_weekly_execution_tasks!.push({id:`row-${taskId}`,tenant_id:'tenant',program_id:'program',package_id:id,package_version:1,task_id:taskId,payload:{taskId,tenantId:'tenant',programId:'program',packageId:id,packageVersion:1,publicationTaskId:pub.publicationTaskId,scope:'content',status:'blocked',lease:null,inputSnapshot:{publicationTask:pub},schedule:{stepKind:step,estimatedStartAt:id==='old'?'2026-10-09T10:00:00Z':'2026-10-13T10:00:00Z',latestFinishAt:'2026-10-13T12:00:00Z'}}});}}
 const writes:string[]=[];let seq=0;const store={async getById<T>(c:string,id:string){return structuredClone(data[c]?.find(r=>r.id===id)??null)as T|null;},async list<T>(c:string,q:any={}){const all=(data[c]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));const per=q.perPage??250,page=q.page??1;return{items:structuredClone(all.slice((page-1)*per,page*per))as T[],totalItems:all.length,totalPages:Math.ceil(all.length/per),page,perPage:per};},async create<T>(c:string,p:Record<string,unknown>){if(data[c]?.some(r=>r.id===p.id))throw Error('unique');const r={...structuredClone(p),id:String(p.id??`new${++seq}`)};(data[c]??=[]).push(r);writes.push(c);return structuredClone(r)as T;},async update(c:string,id:string,p:Record<string,unknown>){const r=data[c]?.find(r=>r.id===id);if(!r)return false;Object.assign(r,structuredClone(p));writes.push(c);return true;},async delete(c:string,id:string){data[c]=(data[c]??[]).filter(r=>r.id!==id);return true;}}as DataStore;
 const bytes=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]);const sha=createHash('sha256').update(bytes).digest('hex');const materialPorts={getMaterial:async()=>({id:'material0000001',tenantId:'tenant',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'product.png',sourceType:'licensed_upload'}),materialBytes:{fetch:async()=>new Response(bytes,{headers:{'content-type':'image/png','content-length':String(bytes.length)}})}};const service=createCrossWeekMaterialContinuationService(store,{materials:materialPorts,targetRequirement:async()=> '新视频真实产品正面近景',now:()=> '2026-10-12T08:00:00Z'});const authority={tenantId:'tenant',programId:'program',packageId:'next',packageVersion:1,actorUserId:'reviewer'};const input={source:{packageId:'old',packageVersion:1,consumerTaskId:'original',requestId:request.requestId,expectedSourceInputHash:crossWeekMaterialSourceInputHash(request,'original')},targetConsumerTaskId:'target',requirementId:'required-product',verificationDueAt:'2026-10-13T09:00:00Z',reason:'明确沿用未结任务；新视频逐镜重新核验'};return{service,store,data,writes,authority,input,request,materialPorts,sha,byteSize:bytes.length};}
