import {readCustomerTaskApprovalNavigation} from '../digitalEmployees/customerTaskApprovalNavigation';
import test from 'node:test';import assert from 'node:assert/strict';
import {exceptionFixture} from './weeklyCustomerKnowledgeQuote.fixture';
import {createWeeklyCustomerKnowledgeQuoteService} from './weeklyCustomerKnowledgeQuote';
import {createDigitalEmployeeApprovalDecisionApplication} from '../digitalEmployees/approvalDecision';
async function pending(kind:'quote'|'knowledge'='quote'){
 const f=await exceptionFixture(),service=createWeeklyCustomerKnowledgeQuoteService(f.store);
 let r=await service.create(f.scope,'owner',{...f.createInput,kind});
 const ref=kind==='quote'?{type:'confirmed_quote' as const,id:'quote',version:2}:{type:'approved_faq' as const,id:'faq',version:1,factVersionId:f.profile.factVersion.id,factContentHash:f.profile.factVersion.contentHash};
 r=await service.submit(f.scope,'owner',r.requestId,r.version,ref);r=await service.verify(f.scope,'reviewer',r.requestId,r.version);
 const applied=await service.apply(f.scope,'owner',r.requestId,r.version);
 Object.assign(f.table('workflow_runs')[0]!,{status:'waiting_external'});
 f.table('workflow_tasks').push({id:'approval-task',tenant_id:'tenant',run_id:'run',goal_id:'goal',task_key:'followup_batch_approval',status:'succeeded'});
 const receipt=await service.requestApproval(f.scope,'owner',applied.item.requestId,applied.item.version);let calls=0;
 const decide=createDigitalEmployeeApprovalDecisionApplication({store:f.store,async buildPublishingPackage(){throw Error('not publishing');},async listConnectedPublishingAccounts(){return[];},async createPublishingCalendarEntries(){throw Error('no publishing');},async applyFollowupBatchDecision(input){calls++;await f.store.update('followup_batches',input.batchId,{status:input.decision});},async appendAudit(){},async appendEvent(){},async continueRun(){}});
 const frozen=await readCustomerTaskApprovalNavigation(f.store,{tenantId:f.scope.tenantId,runId:f.scope.runId,taskId:receipt.approvalTaskId});
 return{...f,applied,receipt,frozen,decide,calls:()=>calls,approve:()=>decide({tenantId:f.scope.tenantId,userId:'reviewer',approvalId:receipt.approvalId,decision:'approved',expectedSubjectVersion:String(frozen.batchVersion),expectedContentHash:frozen.contentHash,expectedRequestHash:frozen.requestHash})};
}
test('actual decision rejects quote expiry after approval request, before changing approval or batch',async()=>{const f=await pending();f.quote.confirmedAt='2020-01-01T00:00:00Z';await assert.rejects(f.approve,/quote_expired/);assert.equal(f.calls(),0);assert.equal(f.table('approval_requests')[0]!.status,'pending');assert.equal(f.table('followup_batches').find(b=>b.id===f.applied.batch.id)!.status,'pending_approval');});
test('actual decision rejects reviewed FAQ version drift and member relationship drift',async()=>{const f=await pending('knowledge');f.profile.faq[0]!.answer='Changed reviewed fact';await assert.rejects(f.approve,/knowledge_version_changed/);assert.equal(f.calls(),0);const g=await pending();const member=g.table('customer_segment_members').find(m=>m.customer_id==='sibling')!;const snapshot=member.customer_snapshot as Record<string,unknown>;snapshot.handlingReason='Mutated after request';await assert.rejects(g.approve,/consumer_changed/);assert.equal(g.calls(),0);assert.equal(g.table('approval_requests')[0]!.status,'pending');});
test('actual decision rejects missing item evidence and body tampering even if batch row hash was unchanged',async()=>{const f=await pending();const item=f.table('followup_batch_items').find(i=>i.batch_id===f.applied.batch.id)!;item.weeklyKnowledgeQuoteEvidence=null;await assert.rejects(f.approve,/item_evidence_missing/);assert.equal(f.calls(),0);const g=await pending();g.table('followup_batch_items').find(i=>i.batch_id===g.applied.batch.id)!.draft_body='Spoofed message';await assert.rejects(g.approve,/approval_items_changed/);assert.equal(g.calls(),0);});
test('fresh evidence permits actual approval application while preserving blocked human items and no sends',async()=>{const f=await pending();await f.approve();assert.equal(f.calls(),1);assert.equal(f.table('approval_requests')[0]!.status,'approved');assert.ok(f.table('followup_batch_items').filter(i=>i.batch_id===f.applied.batch.id).every(i=>i.status==='blocked'&&!i.provider_message_id));});
test('removing typed request policy cannot turn frozen knowledge quote batch into ordinary unguarded approval',async()=>{const f=await pending();const batch=f.table('followup_batches').find(b=>b.id===f.applied.batch.id)!;batch.delivery_policy={};await assert.rejects(f.approve,/approval_policy_changed/);assert.equal(f.calls(),0);assert.equal(f.table('approval_requests')[0]!.status,'pending');});

test('duplicate actual approval decision applies the frozen batch only once and retains blocked items',async()=>{const f=await pending();const first=await f.approve();const second=await f.approve();assert.equal(first.state,'decided');assert.equal(second.state,'already_decided');assert.equal(f.calls(),1);assert.equal(f.table('approval_requests').length,1);assert.ok(f.table('followup_batch_items').filter(i=>i.batch_id===f.applied.batch.id).every(i=>i.status==='blocked'&&!i.provider_message_id&&!i.sent_at));});
test('actual approval rejects omitted or stale frozen request/version/content fields before any decision write',async()=>{
 for(const changed of [{expectedSubjectVersion:'999'},{expectedContentHash:'f'.repeat(64)},{expectedRequestHash:'f'.repeat(64)},{expectedContentHash:undefined},{expectedRequestHash:undefined},{tenantId:'foreign'}]){const f=await pending();const before=structuredClone(f.table('approval_requests'));await assert.rejects(()=>f.decide({tenantId:f.scope.tenantId,userId:'reviewer',approvalId:f.receipt.approvalId,decision:'approved',expectedSubjectVersion:String(f.frozen.batchVersion),expectedContentHash:f.frozen.contentHash,expectedRequestHash:f.frozen.requestHash,...changed}));assert.equal(f.calls(),0);assert.deepEqual(f.table('approval_requests'),before);assert.equal(f.table('followup_batches').find(b=>b.id===f.applied.batch.id)!.status,'pending_approval');}
});
test('actual approval rejects approval task, request evidence and batch identity drift while preserving pending decision',async()=>{
 for(const [index,mutate] of [(f:Awaited<ReturnType<typeof pending>>)=>{f.table('approval_requests')[0]!.action_summary='changed after user read';},(f:Awaited<ReturnType<typeof pending>>)=>{f.table('approval_requests')[0]!.task_id='foreign-task';},(f:Awaited<ReturnType<typeof pending>>)=>{f.table('followup_batches').find(b=>b.id===f.applied.batch.id)!.version=99;},(f:Awaited<ReturnType<typeof pending>>)=>{f.table('followup_batch_items').find(i=>i.batch_id===f.applied.batch.id)!.customer_id='foreign-customer';},(f:Awaited<ReturnType<typeof pending>>)=>{f.table('followup_batch_items').find(i=>i.batch_id===f.applied.batch.id)!.segment_member_id='member1';}].entries()){const f=await pending();mutate(f);await assert.rejects(f.approve,`drift index ${index}`);assert.equal(f.calls(),0);assert.equal(f.table('approval_requests')[0]!.status,'pending');assert.ok(f.table('followup_batch_items').filter(i=>i.batch_id===f.applied.batch.id).every(i=>!i.provider_message_id&&!i.sent_at));}
});
