import test from 'node:test';import assert from 'node:assert/strict';
import {nativeDispatchFixture} from '../digitalEmployees/weeklyNativeFollowupDispatch.fixture.js';
import {createWeeklyNativeSendRecoveryService} from './weeklyNativeSendRecovery.js';
const a={tenantId:'tenant',programId:'program',packageId:'week',packageVersion:1};
const command={channel:'messenger' as const,ownerUserId:'issuer',deadlineAt:'2026-10-06T13:00:00+00:00',reason:'核对原平台请求，禁止重新发送'};
test('unknown native supplier result becomes persistent assigned task; no MID input can make it completed',async()=>{const f=await nativeDispatchFixture('messenger',true);try{await assert.rejects(f.service.dispatch(f.command),/provider_identity_gap/);assert.equal(f.sends(),1);const service=createWeeklyNativeSendRecoveryService(f.store),source=(await service.sources(a,'owner'))[0]!;assert.equal(source.status,'unknown');const request=await service.create(a,'owner',{...command,requestId:source.requestId});assert.equal(request.originalActorUserId,'owner');assert.equal(request.ownerUserId,'issuer');assert.equal(request.gap,'weekly_native_send_provider_identity_gap');assert.equal(request.deadlineAt,command.deadlineAt);assert.equal(request.overdue,true);assert.equal('recipientId'in request,false);assert.equal('body'in request,false);assert.equal((await service.list(a,'issuer')).length,1);await assert.rejects(service.get(a,request.id,'stranger'),/read_forbidden/);await assert.rejects(service.resolve(a,request.id,'owner',{expectedVersion:1}),/owner_required/);await assert.rejects(service.resolve(a,request.id,'issuer',{expectedVersion:2}),/version_conflict/);await assert.rejects(service.resolve(a,request.id,'issuer',{expectedVersion:1,providerMessageId:'mid.user-upload'} as unknown as {expectedVersion:number}),/input_invalid/);await assert.rejects(service.resolve(a,request.id,'issuer',{expectedVersion:1}),/accepted_receipt_required/);assert.equal(f.sends(),1);assert.equal((await service.get(a,request.id,'issuer')).status,'awaiting_receipt');const sources=await f.service.sources('tenant','owner','run',f.command.expectedScope);assert.equal(sources[0]?.gap,'weekly_native_dispatch_unknown_send');}finally{f.restore();}});
test('accepted original ledger repairs only original task with zero sends and immutable late deadline',async()=>{const f=await nativeDispatchFixture();try{const task=f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!;task.depends_on=['missing'];await assert.rejects(f.service.dispatch(f.command),/dependencies_pending/);assert.equal(f.sends(),1);const service=createWeeklyNativeSendRecoveryService(f.store),source=(await service.sources(a,'owner'))[0]!;const request=await service.create(a,'owner',{...command,requestId:source.requestId});const same=await service.create(a,'owner',{...command,requestId:source.requestId});assert.equal(same.id,request.id);task.depends_on=['followup_batch_approval'];const result=await service.resolve(a,request.id,'issuer',{expectedVersion:1});assert.equal(result.messagesSent,0);assert.equal(result.runAdvanced,false);assert.equal(result.item.status,'resolved');assert.equal(result.item.version,2);await assert.rejects(service.resolve(a,request.id,'issuer',{expectedVersion:1}),/version_conflict/);assert.equal(result.item.deadlineAt,command.deadlineAt);assert.equal(result.item.resolvedProof?.taskId,task.id);assert.equal(f.sends(),1);assert.equal((await service.resolve(a,request.id,'issuer',{expectedVersion:result.item.version})).messagesSent,0);await assert.rejects(service.get({...a,tenantId:'other'},request.id,'issuer'),/actor_forbidden/);const originalTaskId=task.id;task.id='replacement-task';await assert.rejects(service.get(a,request.id,'issuer'),/source_changed/);task.id=originalTaskId;const batch=f.data.followup_batches![0]!;batch.approved_version=3;await assert.rejects(service.get(a,request.id,'issuer'),/not_approved/);}finally{f.restore();}});

test('accepted receipts cannot erase unrelated safety blockers',async()=>{const f=await nativeDispatchFixture();try{const task=f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!;task.depends_on=['missing'];await assert.rejects(f.service.dispatch(f.command));f.item.exclusion_reason='send_outcome_unknown;human_handling_in_progress';const service=createWeeklyNativeSendRecoveryService(f.store),source=(await service.sources(a,'owner'))[0]!;const request=await service.create(a,'owner',{...command,requestId:source.requestId});task.depends_on=['followup_batch_approval'];await assert.rejects(service.resolve(a,request.id,'issuer',{expectedVersion:1}),/original_task_pending/);assert.equal(f.item.exclusion_reason,'human_handling_in_progress');assert.equal(f.item.status,'blocked');assert.equal(task.status,'waiting_external');assert.equal(f.sends(),1);}finally{f.restore();}});
