import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyInventoryG4,inventoryPublicationHash,createWeeklyInventoryReuseService} from './weeklyInventoryReuse.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import type {SocialProductionReceipt} from '../starter198/socialContentProductionHandoff.js';
import type {DataStore} from '../storage/datastore.js';
const production={productionResultId:'prod',version:'1',sceneResults:[{sceneId:'scene1'},{sceneId:'scene2'}]};
const receipt=(sceneId:string,attempt=1,status='passed')=>({receiptId:sceneId+attempt,gate:'G4',sceneId,attempt,status,actor:'content_agent',checks:['format','duration','audio_visual_sync','caption','linked_assets','render','sensitive_data'].map(code=>({code,passed:true})),artifactRefs:['socialfile:owned'],productionResultRef:{id:'prod',version:'1',recordHash:socialRequestHash(production)}} as SocialProductionReceipt);
test('inventory requires every actual scene latest G4 passed, no old-success fallback',()=>{assert.equal(verifyInventoryG4({production,fileRef:'socialfile:owned',receipts:[receipt('scene1'),receipt('scene2')]}).length,2);for(const receipts of [[receipt('scene1')],[receipt('scene1'),receipt('scene2'),receipt('scene2',2,'review_required')],[receipt('scene1'),receipt('scene2'),receipt('scene2')]])assert.throws(()=>verifyInventoryG4({production,fileRef:'socialfile:owned',receipts}));});
test('G4 binds actual output bytes, production version/hash and approved checks',()=>{for(const change of [{artifactRefs:['socialfile:other']},{productionResultRef:{id:'prod',version:'1',recordHash:'wrong'}},{checks:[{code:'caption',passed:false}]}])assert.throws(()=>verifyInventoryG4({production,fileRef:'socialfile:owned',receipts:[receipt('scene1'),{...receipt('scene2'),...change} as SocialProductionReceipt]}));});
test('publication identity excludes only immutable reuse reference, preserves account and facts',()=>{const p={publicationTaskId:'p',accountId:'a',factRefs:[{id:'f'}]} as any;assert.equal(inventoryPublicationHash(p),inventoryPublicationHash({...p,inventoryReuseRef:{type:'weekly_inventory_binding',id:'b',version:1}}));assert.notEqual(inventoryPublicationHash(p),inventoryPublicationHash({...p,accountId:'other'}));});
test('candidate reads require actual same tenant actor, never render or mutate',async()=>{let writes=0;const store={getById:async()=>({id:'u',tenantId:'foreign',role:'social_operator'}),list:async()=>({items:[],totalItems:0}),create:async()=>{writes++;},update:async()=>{writes++;},delete:async()=>{writes++;}}as unknown as DataStore;await assert.rejects(()=>createWeeklyInventoryReuseService(store).candidates({tenantId:'tenant',programId:'p',packageId:'w',packageVersion:1,actorUserId:'u'}),/库存/);assert.equal(writes,0);});
function partialStore(){const rows:Record<string,any[]>={users:[{id:'u',tenantId:'t',role:'social_operator'}],social_programs:[{id:'pr',tenant_id:'t',program_id:'p',payload:{programId:'p',route:'account_repair'}}],social_weekly_operating_packages:[{id:'pkg',tenant_id:'t',program_id:'p',package_id:'w',version:1,payload:{packageId:'w',version:1,programId:'p',status:'draft',weekStart:'2026-10-12',socialContentPackage:{publicationTasks:[{publicationTaskId:'pub',accountId:'a',platform:'instagram'}]}}}]};let writes=0;const store={async getById(c:string,id:string){return rows[c]?.find(r=>r.id===id)??null;},async list(c:string,q:any={}){const found=(rows[c]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));return{items:found,totalItems:found.length};},async create(){writes++;return null;},async update(){writes++;return false;},async delete(){writes++;return false;}}as unknown as DataStore;return{rows,store,writes:()=>writes};}
const authority={tenantId:'t',programId:'p',packageId:'w',packageVersion:1,actorUserId:'u'};
const intent={artifactRef:{type:'starter_social_content_artifact',id:'art',version:1},expectedSourceHash:'source',publicationTaskId:'pub',expectedTargetPublicationHash:'forged',reason:'reason',rightsStatement:'right',timelinessStatement:'current'};
test('confirm cannot mutate current draft or accept client target hash/profile/active version',async()=>{const f=partialStore(),service=createWeeklyInventoryReuseService(f.store);await assert.rejects(()=>service.confirm(authority,intent),e=>(e as any).code==='inventory_target_changed');f.rows.social_programs[0].payload.route='cold_start';await assert.rejects(()=>service.confirm(authority,intent),e=>(e as any).code==='inventory_existing_account_profile_required');f.rows.social_programs[0].payload.route='account_repair';f.rows.social_weekly_operating_packages[0].payload.status='active';await assert.rejects(()=>service.confirm(authority,intent),e=>(e as any).code==='inventory_target_revision_required');assert.equal(f.writes(),0);});
test('legacy approved marker with no immutable lineage is a source gap, never new production',async()=>{const f=partialStore();f.rows.starter_social_content_artifacts=[{id:'a',tenant_id:'t',artifact_id:'art',version:'1',status:'approved',content:{productionResult:{productionResultId:'prod'}}}];const result=await createWeeklyInventoryReuseService(f.store).candidates(authority);assert.equal(result.items.length,0);assert.ok(result.gaps.includes('inventory_artifact_content_changed')||result.gaps.includes('inventory_record_missing'));assert.equal(f.writes(),0);});
test('corrupted or foreign inventory records cannot be loaded as trusted binding',async()=>{const f=partialStore();f.rows.social_weekly_inventory_bindings=[{id:'bad',payload:{bindingId:'bad',ref:{type:'weekly_inventory_binding',id:'bad',version:1},version:1,target:{packageId:'foreign'},source:{},tenantId:'other'},content_hash:'notmatching'}];await assert.rejects(()=>createWeeklyInventoryReuseService(f.store).get(authority,'bad'),e=>(e as any).code==='inventory_binding_integrity_invalid');assert.equal(f.writes(),0);});
