import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './weeklyContentTemplates.fixture.js';import {readWeeklyTemplateStructure,validateWeeklyTemplateProductionOutput} from './weeklyTemplateStructure.js';import {freezeSocialScriptBaseline,parseStoredSocialScriptBaseline} from '../starter198/socialContentScriptBaseline.js';
test('real confirmed template planned intention validates without pretending post-supply assets and rejects drift',async()=>{const f=await fixture();try{const scope={tenantId:'t',programId:'p'},target={...scope,packageId:'week2',packageVersion:1,publicationTaskId:'next'},c=await f.service.create(scope,f.input),ref={type:'weekly_content_template',id:c.templateId,version:1};await f.service.confirm(scope,{actorUserId:'owner',templateRef:ref,candidateHash:c.recordHash,usage:'trial',reason:'小规模结构试验'});const b=await f.service.bind(target,{actorUserId:'owner',templateRef:ref,candidateHash:c.recordHash,expectedTargetVersion:2}),bindingRef={type:'weekly_content_template_binding',id:b.bindingId,version:1};const row=f.tables.social_weekly_operating_packages!.find(x=>x.package_id==='week2')!,pkg=structuredClone(row.payload) as any;pkg.version=2;pkg.socialContentPackage.publicationTasks[0].contentTemplateBindingRef=bindingRef;f.tables.social_weekly_operating_packages!.push({...row,id:'target2',version:2,payload:pkg});const actualTarget={...target,packageVersion:2},constraint=await readWeeklyTemplateStructure(f.store,actualTarget,bindingRef);assert.deepEqual(constraint.roles,['hook','proof','cta']);assert(!JSON.stringify(constraint).includes('产品全貌'));assert(!JSON.stringify(constraint).includes('/verified.mp4'));const baseline=freezeSocialScriptBaseline({contentTemplateStructure:constraint,brief:{title:'本周新产品',productRef:'当前工业传感器',languages:['zh'],callToAction:'申请当前产品参数'} as any,theme:{themeId:'product_value'} as any,verifiedContext:{productName:'当前工业传感器',facts:[{key:'current-fact',label:'防护等级',value:'已确认达到IP67'}],source:'enterprise_product',confidence:1},lockedAt:'2026-10-09T02:00:00Z'});assert.deepEqual(baseline.match?.verifiedFactKeys,['current-fact']);assert(baseline.scenes.some(s=>s.narration?.includes('当前工业传感器')));assert(!baseline.scenes.some(s=>s.script==='产品全貌'));assert.equal(parseStoredSocialScriptBaseline(baseline)?.contentTemplateStructure?.bindingRef.id,b.bindingId);const task={tenantId:'t',programId:'p',packageId:'week2',packageVersion:2,publicationTaskId:'next',workflowKind:'directing',schedule:{stepKind:'storyboard'}} as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask;
const contentRow={task_id:'targetcontent',brief:{_weeklyAuthority:{publicationTask:pkg.socialContentPackage.publicationTasks[0]}},script_baseline:baseline};
// Controlled intention projection: real confirmed template + new locked script, no generated assets/director plan.
const preSupply={...actualTarget,baseline,assetAvailability:'planned_not_generated' as const,templateIntention:{structure:constraint,pace:constraint.pace,voiceSpeed:constraint.voiceSpeed,pauseStyle:constraint.pauseStyle}};
await validateWeeklyTemplateProductionOutput({store:f.store,task,contentRow,preSupply});
await assert.rejects(validateWeeklyTemplateProductionOutput({store:f.store,task,contentRow,preSupply:{...preSupply,templateIntention:{...preSupply.templateIntention,voiceSpeed:constraint.voiceSpeed+.1}}}),(e:unknown)=>e instanceof Error&&'code' in e&&e.code==='content_template_pre_supply_mismatch');
await assert.rejects(validateWeeklyTemplateProductionOutput({store:f.store,task,contentRow,preSupply:{...preSupply,packageVersion:1}}),(e:unknown)=>e instanceof Error&&'code' in e&&e.code==='content_template_pre_supply_mismatch');
await assert.rejects(validateWeeklyTemplateProductionOutput({store:f.store,task,contentRow}),(e:unknown)=>e instanceof Error&&'code' in e&&e.code==='content_template_output_mismatch');
await assert.rejects(validateWeeklyTemplateProductionOutput({store:f.store,task,contentRow,preSupply,artifactRow:{task_id:'targetcontent'}}),(e:unknown)=>e instanceof Error&&'code' in e&&e.code==='content_template_pre_supply_mismatch');
}finally{await f.cleanup();}});
