import {createHash}from'node:crypto';
import test from 'node:test';import assert from 'node:assert/strict';
import type {DataStore,Record_} from '../storage/datastore.js';
import {createCrossWeekMaterialContinuationService,crossWeekMaterialSourceInputHash} from './weeklyCrossWeekMaterialContinuations.js';
import type {WeeklyMaterialRequest} from './weeklyMaterialRequests.js';
import {fixture}from'./weeklyCrossWeekMaterialContinuationFixtures.js';

test('cross different real weeks attaches original request once and preserves owner/upload deadline',async()=>{const f=fixture();const receipt=await f.service.confirm(f.authority,f.input);assert.equal(receipt.attachment,'attached');assert.equal(receipt.materialStatus,'pending_verification');assert.equal(receipt.countsAsNewMotherContent,false);assert.equal(receipt.startsProduction,false);const r=f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest;assert.equal(r.requestId,f.request.requestId);assert.equal(r.consumers.length,2);assert.equal(r.assigneeUserId,'uploader');assert.equal(r.dueAt,'2026-10-09T08:00:00Z');assert.equal(r.verificationDueAt,'2026-10-09T09:00:00Z');assert.equal((r.consumers[1]as any).verificationDueAt,f.input.verificationDueAt);assert.deepEqual(await f.service.confirm(f.authority,f.input),receipt);assert.equal(f.writes.filter(c=>c==='social_weekly_execution_tasks').length,0);});
test('tenant/program/version/source drift and absent frozen mapping rejected',async()=>{const f=fixture();await assert.rejects(f.service.confirm({...f.authority,tenantId:'foreign'},f.input));await assert.rejects(f.service.confirm({...f.authority,packageVersion:2},f.input));await assert.rejects(f.service.confirm(f.authority,{...f.input,source:{...f.input.source,expectedSourceInputHash:'forged'}}),{code:'cross_week_material_source_input_changed'});const p=f.data.social_weekly_operating_packages![1]!.payload as any;p.socialContentPackage.publicationTasks[0].materialRequirement.bindings=[];await assert.rejects(f.service.confirm(f.authority,f.input),{code:'cross_week_material_frozen_mapping_missing'});});
test('independent verification deadline must precede actual new production and readonly witness drifts block',async()=>{const f=fixture();await assert.rejects(f.service.confirm(f.authority,{...f.input,verificationDueAt:'2026-10-13T11:00:00Z'}),{code:'cross_week_material_target_start_unverified'});const r=await f.service.confirm(f.authority,f.input);(f.data.social_weekly_execution_tasks!.find(t=>t.task_id==='target')!.payload as any).inputSnapshot.changed='changed';await assert.rejects(f.service.get(f.authority,r.item.continuationId),{code:'cross_week_material_target_input_changed'});});
test('other employee cannot confirm, same package is not cross week, cancelled request remains closed',async()=>{const f=fixture();await assert.rejects(f.service.confirm({...f.authority,actorUserId:'other'},f.input),{code:'cross_week_material_confirmation_forbidden'});await assert.rejects(f.service.confirm({...f.authority,packageId:'old'},f.input),{code:'cross_week_material_not_future_package'});f.data.social_weekly_material_requests![0]!.status='cancelled';(f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest).status='cancelled';await assert.rejects(f.service.confirm(f.authority,f.input),{code:'cross_week_material_source_cancelled'});});

test('accepted old material evidence never approves the new week consumer without its own review',async()=>{const f=fixture();const request=f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest;request.status='accepted';f.data.social_weekly_material_requests![0]!.status='accepted';request.submissions=[{version:1,submittedAt:'2026-10-09T08:00:00Z',submittedBy:'uploader',materials:[{recordId:'material0000001',sha256:f.sha,type:'image',byteSize:f.byteSize}],verification:{reviewedAt:'2026-10-09T09:00:00Z',reviewedBy:'reviewer',decision:'accepted',consumerDecisions:[{taskId:'original',accepted:true,factCheck:'原产品真实',rightsCheck:'原视频授权',visualCheck:'原视频正面符合要求'}]}}];const receipt=await f.service.confirm(f.authority,f.input);assert.equal(receipt.materialStatus,'pending_verification');const revised=f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest;assert.equal(revised.status,'pending_verification');assert.equal(revised.submissions[0]!.verification!.consumerDecisions.length,1);const {createWeeklyMaterialRequestService}=await import('./weeklyMaterialRequests.js');const materials=createWeeklyMaterialRequestService(f.store,f.materialPorts);await materials.review({tenantId:'tenant',programId:'program',requestId:request.requestId,actorUserId:'reviewer',submissionVersion:1,consumerDecisions:[...request.submissions[0]!.verification!.consumerDecisions,{taskId:'target',accepted:true,factCheck:'新视频产品事实复核',rightsCheck:'新视频使用授权复核',visualCheck:'新视频近景实际可辨'}]});const ready=await f.service.get(f.authority,receipt.item.continuationId);assert.equal(ready.materialStatus,'ready');assert.equal(ready.consumerVerification!.consumerTaskId,'target');assert.equal(ready.consumerVerification!.submissionVersion,1);assert.equal(ready.consumerVerification!.consumerDecision.factCheck,'新视频产品事实复核');assert.equal(ready.consumerVerification!.materialRefs[0]!.sha256,f.sha);assert.match(ready.consumerVerification!.recordHash,/^[a-f0-9]{64}$/);});

test('readonly actual source candidates provide hash and mapping gap rather than handwritten IDs',async()=>{const f=fixture();const first=await f.service.candidates(f.authority);assert.equal(first.items.length,1);assert.equal(first.items[0]!.source.expectedSourceInputHash,f.input.source.expectedSourceInputHash);assert.equal(first.items[0]!.originalOwnerUserId,'uploader');assert.equal(first.items[0]!.gap,null);assert.equal(f.writes.length,0);const p=f.data.social_weekly_operating_packages![1]!.payload as any;p.socialContentPackage.publicationTasks[0].materialRequirement.bindings=[];const next=await f.service.candidates(f.authority);assert.equal(next.items[0]!.gap,'cross_week_material_frozen_mapping_missing');assert.equal(f.writes.length,0);});

test('unknown append write preserves a readonly pending receipt and explicit retry does not duplicate requests',async()=>{const f=fixture();const update=f.store.update;f.store.update=async(c,id,p)=>c==='social_weekly_material_requests'?false:update(c,id,p);await assert.rejects(f.service.confirm(f.authority,f.input),{code:'weekly_material_save_failed'});const records=f.data.social_cross_week_material_continuations!;assert.equal(records.length,1);assert.equal((await f.service.get(f.authority,records[0]!.id)).attachment,'pending');f.store.update=update;const recoveredRecords=await f.service.list(f.authority);assert.equal(recoveredRecords.length,1);assert.equal(recoveredRecords[0]!.attachment,'pending');assert.equal(recoveredRecords[0]!.item.continuationId,records[0]!.id);const recovered=await f.service.confirm(f.authority,f.input);assert.equal(recovered.attachment,'attached');assert.equal(f.data.social_weekly_material_requests!.length,1);assert.equal((f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest).consumers.length,2);assert.equal(f.data.social_cross_week_material_continuations!.length,1);assert.equal(f.writes.includes('social_weekly_execution_tasks'),false);});

test('production verifier cannot accept a text-only human requirement and source task/deadline drift revokes receipt',async()=>{const f=fixture();const production=createCrossWeekMaterialContinuationService(f.store);await assert.rejects(production.confirm(f.authority,f.input),{code:'weekly_material_classification_required'});assert.equal(f.data.social_cross_week_material_continuations,undefined);const receipt=await f.service.confirm(f.authority,f.input);(f.data.social_weekly_execution_tasks!.find(t=>t.task_id==='original')!.payload as any).inputSnapshot.modified=true;await assert.rejects(f.service.get(f.authority,receipt.item.continuationId),{code:'cross_week_material_source_task_changed'});delete(f.data.social_weekly_execution_tasks!.find(t=>t.task_id==='original')!.payload as any).inputSnapshot.modified;(f.data.social_weekly_material_requests![0]!.payload as WeeklyMaterialRequest).dueAt='2026-10-10T08:00:00Z';await assert.rejects(f.service.get(f.authority,receipt.item.continuationId),{code:'cross_week_material_source_input_changed'});});

test('scoped records recover a lost successful response without computing or submitting another ID',async()=>{const f=fixture();await f.service.confirm(f.authority,f.input);const recovered=await f.service.list(f.authority);assert.equal(recovered.length,1);assert.equal(recovered[0]!.attachment,'attached');assert.equal(recovered[0]!.materialStatus,'pending_verification');assert.equal(f.data.social_cross_week_material_continuations!.length,1);await assert.rejects(f.service.list({...f.authority,tenantId:'foreign'}));assert.equal((await f.service.list({...f.authority,actorUserId:'other'})).length,0);});
