import {randomBytes} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,VersionedSocialRef,WeeklyOperatingPackage} from '../../shared/contracts/socialProgram.js';
import {scheduleHash,scheduleTaskSignature,readScheduleSnapshot} from './weeklyScheduleSnapshots.js';
import {withExecutionPackageGate,WEEKLY_EXECUTION_FREEZES,type ExecutionPackageScope} from './weeklyExecutionGate.js';
import {publicationInstant} from './publicationDeadlines.js';
import {backwardTaskEvidenceFingerprint,type BackwardCompletedEvidence} from './weeklyBackwardSchedule.js';
import {observeWeeklyContinuationProduction} from './weeklyContinuationProductionObserver.js';
import {SocialProgramError} from './service.js';
export const WEEKLY_EXECUTION_CONTINUATIONS='social_weekly_execution_continuations';
export interface WeeklyExecutionContinuation {continuationId:string;ref:VersionedSocialRef;tenantId:string;programId:string;packageId:string;sourceVersion:number;targetVersion:number;sourceTaskId:string;targetTaskId:string;snapshotId:string;mode:'completed_verified'|'running_reserved';sourceInputHash:string;targetInputHash:string;createdAt:string;}
export interface ContinuationTarget {tenantId:string;programId:string;packageId:string;targetVersion:number;targetTaskId:string;}
export interface ContinuationRead {status:'ready'|'pending'|'blocked';sourceTask:WeeklyExecutionTask;resultRefs:VersionedSocialRef[];detail:WeeklyExecutionContinuation;code?:string;observedCompletedAt?:string;}
export interface WeeklyContinuationPorts {validateResults?:(task:WeeklyExecutionTask,refs:VersionedSocialRef[],now:string)=>Promise<void>;validateTargetMaterials?:(target:WeeklyExecutionTask,source:WeeklyExecutionTask)=>Promise<void>;now?:()=>string;}
const fail=(code:string):never=>{throw new SocialProgramError(code,409,'真实生产承接证据不足或输入已改变，未重新启动生产。');};
/** Excludes only scheduler metadata; all real facts, references, publication and material inputs remain frozen. */
export function weeklyContinuationInputHash(t:WeeklyExecutionTask):string {const input={...t.inputSnapshot};delete input.scheduleRevisionRef;delete input.weeklyContinuationPending;delete input.weeklyContinuationRef;delete input.directorTaskId;if(t.workflowKind==='content'||t.workflowKind==='directing'){const normalize=(value:unknown)=>{if(!value||typeof value!=='object'||Array.isArray(value))return value;const copy={...(value as Record<string,unknown>)};delete copy.status;return copy;};if(input.publicationTask)input.publicationTask=normalize(input.publicationTask);if(Array.isArray(input.variants))input.variants=input.variants.map(normalize);}return scheduleHash({tenantId:t.tenantId,programId:t.programId,packageId:t.packageId,workflowKind:t.workflowKind,scope:t.scope,subjectId:t.subjectId,accountId:t.accountId,publicationTaskId:t.publicationTaskId,stepKind:t.schedule.stepKind,responsibleActor:t.schedule.responsibleActor,input,refs:t.upstreamVersionRefs.filter(r=>!['weekly_schedule_snapshot','weekly_execution_continuation'].includes(r.type)),budget:t.budget});}
export function createWeeklyExecutionContinuationService(store:DataStore,ports:WeeklyContinuationPorts={}) {
 const now=()=>ports.now?.()??new Date().toISOString();
 const validate=ports.validateResults??(async(t,refs,at)=>{const {validateWeeklyExecutionResults}=await import('../runtime/socialWeeklyResultValidation.js');await validateWeeklyExecutionResults(store,t,refs,new Date(at));});
 const task=async(scope:ExecutionPackageScope,id:string)=>{const r=await store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:scope.tenantId,program_id:scope.programId,package_id:scope.packageId,package_version:scope.packageVersion,task_id:id},perPage:2});if(r.totalItems!==1||r.items.length!==1)fail('weekly_continuation_task_missing');const t=r.items[0]!.payload as WeeklyExecutionTask;if(!t||t.taskId!==id||t.tenantId!==scope.tenantId||t.programId!==scope.programId||t.packageId!==scope.packageId||t.packageVersion!==scope.packageVersion||!t.schedule||!Array.isArray(t.resultRefs))fail('weekly_continuation_task_identity');return t;};
 const pkg=async(a:ContinuationTarget)=>{const r=await store.list<Record_>('social_weekly_operating_packages',{where:{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.targetVersion},perPage:2});if(r.totalItems!==1||r.items.length!==1)fail('weekly_continuation_package_missing');const p=r.items[0]!.payload as WeeklyOperatingPackage;if(!p||p.version!==a.targetVersion||p.packageId!==a.packageId||p.programId!==a.programId)fail('weekly_continuation_package_identity');return p;};
 const validateMaterials=ports.validateTargetMaterials??(async(target:WeeklyExecutionTask)=>{const p=await pkg({tenantId:target.tenantId,programId:target.programId,packageId:target.packageId,targetVersion:target.packageVersion,targetTaskId:target.taskId});const publication=p.socialContentPackage.publicationTasks.find(x=>x.publicationTaskId===target.publicationTaskId);const planning=p.agentPlanning;const item=planning?.dispatch?.scheduleItems.find(x=>x.publicationTaskId===target.publicationTaskId);if(!publication?.materialRequirement||!item)fail('weekly_continuation_material_classification_required');const {checkWeeklyMaterialClassification,checkWeeklyHumanRequirementBindings}=await import('../runtime/socialWeeklyMaterialClassificationAdmission.js');const classification=await checkWeeklyMaterialClassification({store,tenantId:target.tenantId,programId:target.programId,packageId:target.packageId,packageVersion:target.packageVersion,item:item!,analysis:planning?.directorAnalyses?.find(x=>x.analysisId===item!.directorAnalysisRef?.id)});if(!classification.ready)fail(classification.code);const rows=await store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:target.tenantId,program_id:target.programId,package_id:target.packageId,package_version:target.packageVersion},perPage:500});if(rows.totalItems!==rows.items.length)fail('weekly_continuation_material_graph_incomplete');const consumers=rows.items.map(r=>r.payload as WeeklyExecutionTask).filter(t=>t.publicationTaskId===target.publicationTaskId&&t.schedule?.stepKind==='material_readiness');if(consumers.length!==1)fail('weekly_continuation_material_consumer_missing');const consumer=await task({...target},consumers[0]!.taskId);if(classification.ready){const gap=await checkWeeklyHumanRequirementBindings({store,tenantId:target.tenantId,programId:target.programId,packageId:target.packageId,packageVersion:target.packageVersion,consumerTaskId:consumer.taskId,publication:publication!,contract:classification.contract});if(gap)fail(gap);}const {createWeeklyRequiredMaterialAdmission}=await import('./weeklyRequiredMaterialAdmission.js');const admitted=await createWeeklyRequiredMaterialAdmission(store)({tenantId:target.tenantId,programId:target.programId,consumerTaskId:consumer.taskId,requirement:publication!.materialRequirement});if(admitted.status!=='ready'||!admitted.materials.length)fail('weekly_continuation_target_materials_unverified');});
 const authority=async(a:ContinuationTarget)=>{const p=await pkg(a),ref=(p as WeeklyOperatingPackage&{scheduleRevisionRef?:VersionedSocialRef}).scheduleRevisionRef;if(!ref)return null;const snapshot=await readScheduleSnapshot(store,a.tenantId,p,ref);const target=await task({...a,packageVersion:a.targetVersion},a.targetTaskId);const assignment=snapshot.assignments.find(x=>x.signature===scheduleTaskSignature(target));if(!assignment||!assignment.mode||assignment.mode==='planned')return null;const fences=await store.list<Record_>(WEEKLY_EXECUTION_FREEZES,{where:{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:snapshot.sourceVersion},perPage:2});if(fences.totalItems!==1||fences.items.length!==1||fences.items[0]!.snapshot_id!==snapshot.snapshotId||fences.items[0]!.target_version!==a.targetVersion)fail('weekly_continuation_fence_missing');if(snapshot.sourceVersion>=a.targetVersion)fail('weekly_continuation_version_invalid');const source=await task({...a,packageVersion:snapshot.sourceVersion},assignment.sourceTaskId);if(assignment.sourceInputHash!==weeklyContinuationInputHash(source)||weeklyContinuationInputHash(source)!==weeklyContinuationInputHash(target))fail('weekly_continuation_input_changed');if(source.dependsOnTaskIds.length!==target.dependsOnTaskIds.length)fail('weekly_continuation_dependency_changed');for(let i=0;i<source.dependsOnTaskIds.length;i++){const s=await task({...a,packageVersion:snapshot.sourceVersion},source.dependsOnTaskIds[i]!),t=await task({...a,packageVersion:a.targetVersion},target.dependsOnTaskIds[i]!);if(scheduleTaskSignature(s)!==scheduleTaskSignature(t)||weeklyContinuationInputHash(s)!==weeklyContinuationInputHash(t))fail('weekly_continuation_dependency_changed');}return {snapshot,target,source,assignment};};
 const ensureForTarget=async(a:ContinuationTarget):Promise<WeeklyExecutionContinuation|null>=>{const evidence=await authority(a);if(!evidence)return null;return withExecutionPackageGate(store,{...a,packageVersion:a.targetVersion},async assertTarget=>{const live=await authority(a);if(!live)return fail('weekly_continuation_authority_changed');const existing=await store.list<Record_>(WEEKLY_EXECUTION_CONTINUATIONS,{where:{tenant_id:a.tenantId,target_task_id:a.targetTaskId},perPage:2});if(existing.totalItems>1||existing.totalItems!==existing.items.length)fail('weekly_continuation_duplicate');if(existing.items.length){const c=existing.items[0]!.payload as WeeklyExecutionContinuation;if(existing.items[0]!.content_hash!==scheduleHash(c)||c.sourceInputHash!==weeklyContinuationInputHash(live.source)||c.targetVersion!==a.targetVersion||c.snapshotId!==live.snapshot.snapshotId)fail('weekly_continuation_corrupt');return c;}if(live.assignment.mode==='completed_verified'){if(live.source.status!=='succeeded'||publicationInstant(live.source.schedule.actualStartedAt??'')===null||publicationInstant(live.source.schedule.actualFinishedAt??'')===null)fail('weekly_continuation_completion_unverified');await validate(live.source,live.source.resultRefs,now());}else if(!live.source.schedule.actualStartedAt||!live.source.productionProgress?.contentTaskId||!live.source.productionProgress.runId)fail('weekly_continuation_running_unverified');const id=randomBytes(8).toString('hex').slice(0,15);const c:WeeklyExecutionContinuation={...a,continuationId:id,ref:{type:'weekly_execution_continuation',id,version:1},sourceVersion:live.snapshot.sourceVersion,sourceTaskId:live.source.taskId,snapshotId:live.snapshot.snapshotId,mode:live.assignment.mode as WeeklyExecutionContinuation['mode'],sourceInputHash:weeklyContinuationInputHash(live.source),targetInputHash:weeklyContinuationInputHash(live.target),createdAt:now()};await assertTarget();const saved=await store.create(WEEKLY_EXECUTION_CONTINUATIONS,{id,tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,source_version:c.sourceVersion,target_version:c.targetVersion,source_task_id:c.sourceTaskId,target_task_id:c.targetTaskId,snapshot_id:c.snapshotId,content_hash:scheduleHash(c),payload:c});if(!saved)fail('weekly_continuation_storage_failed');return c;});};
 const readValidated=async(a:ContinuationTarget&{ref:VersionedSocialRef},at=now()):Promise<ContinuationRead>=>{if(a.ref.type!=='weekly_execution_continuation'||a.ref.version!==1)fail('weekly_continuation_ref_invalid');const row=await store.getById<Record_>(WEEKLY_EXECUTION_CONTINUATIONS,a.ref.id),c=row?.payload as WeeklyExecutionContinuation;if(!row||!c||row.content_hash!==scheduleHash(c)||c.tenantId!==a.tenantId||c.programId!==a.programId||c.packageId!==a.packageId||c.targetVersion!==a.targetVersion||c.targetTaskId!==a.targetTaskId||c.continuationId!==a.ref.id||c.ref?.id!==a.ref.id||c.ref?.type!==a.ref.type||c.ref?.version!==1||c.sourceVersion>=c.targetVersion)fail('weekly_continuation_identity_invalid');const live=await authority(a);if(!live)return fail('weekly_continuation_authority_changed');if(c.sourceTaskId!==live.source.taskId||c.snapshotId!==live.snapshot.snapshotId||c.sourceInputHash!==weeklyContinuationInputHash(live.source)||c.targetInputHash!==weeklyContinuationInputHash(live.target))fail('weekly_continuation_input_changed');const base={sourceTask:live.source,resultRefs:[] as VersionedSocialRef[],detail:c};if((live.target.inputSnapshot.publicationTask as {materialRequirement?:unknown}|undefined)?.materialRequirement){try{await validateMaterials(live.target,live.source);}catch{return {...base,status:'blocked',code:'weekly_continuation_target_materials_unverified'};}}if(live.source.status==='succeeded'){await validate(live.source,live.source.resultRefs,at);return {...base,status:'ready',resultRefs:live.source.resultRefs};}if(['failed','cancelled','dead_letter'].includes(live.source.status))return {...base,status:'blocked',code:'weekly_continuation_source_failed'};if(c.mode==='running_reserved'){const observed=await observeWeeklyContinuationProduction(store,live.source,at,validate);return {...base,...observed};}return {...base,status:'pending',code:'weekly_continuation_waiting_real_source_settlement'};};
 const derivePlannerEvidence=async(scope:ExecutionPackageScope,at:string,_capacity?:unknown)=>{const completedEvidence:Record<string,BackwardCompletedEvidence>={};let page=1,total=0;do{const rows=await store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:scope.tenantId,program_id:scope.programId,package_id:scope.packageId,package_version:scope.packageVersion},page,perPage:500});total=rows.totalPages;for(const row of rows.items){const t=await task(scope,String((row.payload as WeeklyExecutionTask)?.taskId??''));if(t.status!=='succeeded')continue;if(publicationInstant(t.schedule.actualStartedAt??'')===null||publicationInstant(t.schedule.actualFinishedAt??'')===null||!t.resultRefs.length)fail('weekly_continuation_completion_unverified');await validate(t,t.resultRefs,at);completedEvidence[t.taskId]={taskFingerprint:backwardTaskEvidenceFingerprint(t),verifiedAt:at,actualStartedAt:t.schedule.actualStartedAt!,actualFinishedAt:t.schedule.actualFinishedAt!,resultRefs:t.resultRefs};}page++;}while(page<=total);return {completedEvidence,observedReservations:{}};};
 return {ensureForTarget,readValidated,derivePlannerEvidence};
}
