import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {createHash} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import {socialObject,socialJson,socialRequestHash} from '../starter198/socialContentValidation.js';
import {readWeeklyCustomerRelationshipScope} from './weeklyCustomerRelationshipScope.js';
import {verifyWeeklyCustomerChannelReceipt} from './weeklyCustomerChannelSelections.js';
import {nativeWeeklyConversationPort} from './weeklyCustomerChannelScope.js';
import type {WeeklyCustomerAuthority} from '../runtime/socialWeeklyCustomerBridge.js';
import type {WeeklySalesConversationMessage} from '../../shared/contracts/weeklySalesConversationEvidence.js';
import {SocialProgramError} from './service.js';
const ledgerHash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const object=(v:unknown)=>socialObject(socialJson(v))??{};
function check(v:unknown,code:string):asserts v{if(!v)throw new SocialProgramError(code,409,code);}
export function nativeSalesMember(snapshot:unknown){const selection=object(object(snapshot).weeklyChannelSelection);return ['messenger','instagram'].includes(String(selection.channel));}
const identity=(channel:string,account:string,customer:string,id:string)=>`native:${socialRequestHash([channel,account,customer,id])}`;
export async function readNativeSalesEvidence(store:DataStore,a:WeeklyCustomerAuthority,runId:string,memberId:string){
 const scope=await readWeeklyCustomerRelationshipScope(store,a.tenantId,runId);check(scope&&scope.programId===a.programId&&scope.packageId===a.packageId&&scope.packageVersion===a.packageVersion,'sales_handoff_native_scope_changed');
 const member=await store.getById<Record_>('customer_segment_members',memberId);check(member&&member.tenant_id===a.tenantId&&member.membership==='included','sales_handoff_native_member_missing');
 const segment=await store.getById<Record_>('customer_segments',String(member.segment_id));check(segment&&segment.tenant_id===a.tenantId&&segment.run_id===runId,'sales_handoff_native_member_scope_changed');
 const frozen=object(object(member.customer_snapshot).weeklyChannelSelection);check(nativeSalesMember(member.customer_snapshot),'sales_handoff_native_selection_missing');
 let receipt:Awaited<ReturnType<typeof verifyWeeklyCustomerChannelReceipt>>;try{receipt=await verifyWeeklyCustomerChannelReceipt(store,scope,String(frozen.channel));}catch(error){throw new SocialProgramError(error instanceof Error?error.message:'sales_handoff_native_evidence_unavailable',409,'原渠道证据已变化，请核验原询盘。');}check(receipt&&receipt.customerId===member.customer_id&&receipt.recordHash===frozen.recordHash,'sales_handoff_native_selection_changed');
 const conversations=(await nativeWeeklyConversationPort.read(a.tenantId,receipt.channel)).filter(c=>c.tenantId===a.tenantId&&c.customerId===receipt.customerId&&c.channel===receipt.channel&&c.nativeAccountId===receipt.nativeAccountId&&c.recipientId===receipt.recipientId&&c.conversationId===receipt.conversationId);check(conversations.length===1,'sales_handoff_native_conversation_ambiguous');
 const conversation=conversations[0]!,messages:WeeklySalesConversationMessage[]=[],seen=new Set<string>();
 const ledger=await store.list<Record_>('customer_channel_send_requests',{where:{tenant_id:a.tenantId},perPage:1000});check(ledger.totalItems===ledger.items.length,'sales_handoff_native_receipt_scan_incomplete');
 for(const value of conversation.messages){const m=object(value),audit=object(m.audit);if(typeof m.id!=='string'||!m.id||typeof m.body!=='string'||!m.body.trim()||typeof m.timestamp!=='number'||!Number.isFinite(m.timestamp)||m.timestamp<=0||m.timestamp>Date.now()||audit.providerMessageId!==m.id||audit.providerRecipientId!==receipt.recipientId||m.mock||m.synthetic||m.simulated||audit.mock||audit.synthetic)continue;
  if(!['buyer','seller'].includes(String(m.actor)))continue;
  if(m.actor==='seller'){const rows=ledger.items.filter(row=>{const p=object(row.payload);return p.channel===receipt.channel&&p.customerId===receipt.customerId&&p.accountId===receipt.accountId&&p.providerMessageId===m.id;});if(rows.length!==1)continue;const row=rows[0]!,p=object(row.payload),{recordHash,...body}=p,provider=object(p.providerReceipt);const account=await store.getById<Record_>('social_accounts',receipt.accountId),actor=await store.getById<Record_>('users',String(p.actorUserId));if(!account||account.tenantId!==a.tenantId||account.status!=='connected'||account.providerAccountId!==receipt.nativeAccountId||!actor||actor.tenantId!==a.tenantId||!organizationRoleOrNull(actor.role)||actor.disabled===true||actor.active===false||['disabled','suspended'].includes(String(actor.status)))continue;if(p.requestKey!==ledgerHash([a.tenantId,receipt.channel,p.requestId])||row.request_key!==p.requestKey||p.accountAuthorityHash!==ledgerHash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null}))continue;if(row.tenant_id!==a.tenantId||row.content_hash!==recordHash||recordHash!==ledgerHash(body)||p.status!=='accepted'||p.bodyHash!==ledgerHash(m.body)||p.recipientId!==receipt.recipientId||provider.messageId!==m.id||provider.recipientId!==receipt.recipientId||p.body!==m.body||Date.parse(String(provider.acceptedAt))!==m.timestamp)continue;}
  check(!seen.has(m.id),'sales_handoff_native_message_duplicate');seen.add(m.id);messages.push({interactionId:identity(receipt.channel,receipt.nativeAccountId,receipt.customerId,m.id),type:m.actor==='buyer'?'msg_in':'msg_out_human',body:m.body,timestamp:m.timestamp,providerMessageId:m.id,recordHash:socialRequestHash(m)});
 }
 return {receipt,member,scope,customerName:String(conversation.customerSnapshot?.name||receipt.customerId),messages};
}
export async function verifyNativeSalesSource(store:DataStore,a:WeeklyCustomerAuthority,input:{runId:string;memberId:string;customerId:string;sourceInteractionId:string;sourceEvidence:Record<string,unknown>;sourceKind:string}){const live=await readNativeSalesEvidence(store,a,input.runId,input.memberId);const expected=object(input.sourceEvidence.native);check(live.receipt.customerId===input.customerId&&expected.channel===live.receipt.channel&&expected.accountId===live.receipt.accountId&&expected.nativeAccountId===live.receipt.nativeAccountId&&expected.conversationId===live.receipt.conversationId&&expected.selectionHash===live.receipt.recordHash&&input.sourceKind===live.receipt.classification,'sales_handoff_native_source_changed');const source=live.messages.find(m=>m.interactionId===input.sourceInteractionId&&m.type==='msg_in');check(source&&source.recordHash===expected.messageHash&&input.sourceEvidence.interactionId===source.interactionId&&input.sourceEvidence.timestamp===source.timestamp&&input.sourceEvidence.body===source.body,'sales_handoff_native_source_message_changed');return live;}
