import test from 'node:test';
import {planMobileChatMessages} from '../agents/mobileChatStyle.js';
import assert from 'node:assert/strict';
import {sendRecoveryFixture} from './weeklyCustomerSendRecovery.fixture.js';
import {createWeeklyCustomerSendRecoveryService,verifyCompleteSignedFollowupReceipt} from './weeklyCustomerSendRecovery.js';
import {bindWeeklyCustomerRun,readWeeklyCustomerStep} from '../runtime/socialWeeklyCustomerBridge.js';
import {ingestFollowupDeliveryStatuses} from '../digitalEmployees/followupDispatchWorker.js';
import {store as globalStore} from '../storage/index.js';
const a={tenantId:'tenant',programId:'program',packageId:'week',packageVersion:1};
const token='12345678-1234-1234-1234-123456789abc';
async function fixture(){const f=sendRecoveryFixture();await bindWeeklyCustomerRun(f.store,a,'run','owner');const item=f.data.followup_batch_items![0]!;const batch=f.data.followup_batches![0]!;Object.assign(batch,{status:'approved',created_by:'issuer'});Object.assign(item,{status:'blocked',exclusion_reason:'send_outcome_unknown',wa_number:'15551234567',provider_message_id:'',provider_receipt:{claimToken:token,claimedAt:'2026-10-05T12:00:00Z',approvedBatchVersion:batch.version,approvedContentHash:item.content_hash,expectedMessages:[item.draft_body],messages:[]}});Object.assign(f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!,{status:'waiting_external',blocked_reason:'weekly_customer_send_outcome_unknown'});const original={getById:globalStore.getById,list:globalStore.list,update:globalStore.update,create:globalStore.create};Object.assign(globalStore,{getById:f.store.getById.bind(f.store),list:f.store.list.bind(f.store),update:f.store.update.bind(f.store),create:f.store.create.bind(f.store)});return {...f,item,batch,service:createWeeklyCustomerSendRecoveryService(f.store),restore:()=>Object.assign(globalStore,original)};}
const command={runId:'run',itemId:'item',ownerUserId:'owner',deadlineAt:'2026-10-07T12:00:00+08:00',reason:'核对本次平台发送结果，不重复联系客户'};
function webhook(patch:Record<string,unknown>={}){return {entry:[{changes:[{value:{statuses:[{id:'wamid.recovered.actual',status:'delivered',timestamp:'1791266400',recipient_id:'15551234567',biz_opaque_callback_data:`followup:${token}:0`,...patch}]}}]}]};}
test('real signed webhook reconciles current claim and assigned human resumes only original dispatch with zero sends',async()=>{const f=await fixture();try{const sources=await f.service.sources(a,'issuer');assert.equal(sources.length,1);assert.equal(sources[0]!.recipientMasked,'…4567');const request=await f.service.create(a,'issuer',command);assert.equal('claimToken' in request,false);assert.equal((await f.service.list(a,'owner')).length,1);await assert.rejects(f.service.resolve(a,request.id,'owner',{expectedVersion:1}),/receipt_incomplete/);assert.equal(await ingestFollowupDeliveryStatuses('tenant',webhook(),{verifiedSignature:true}),1);const result=await f.service.resolve(a,request.id,'owner',{expectedVersion:1});assert.equal(result.messagesSent,0);assert.equal(result.runAdvanced,false);assert.equal(result.item.status,'resolved');assert.equal((await readWeeklyCustomerStep(f.store,a,'run','customer_followup_dispatch')).status,'succeeded');assert.equal(f.data.workflow_runs![0]!.status,'running');assert.equal((await f.service.resolve(a,request.id,'owner',{expectedVersion:1})).item.version,2);}finally{f.restore();}});
test('unverified, foreign recipient/request or old approval cannot resolve unknown, and actors are actual tenant enabled members',async()=>{for(const patch of [{recipient_id:'19999999999'},{biz_opaque_callback_data:'followup:12345678-1234-1234-1234-000000000000:0'}]){const f=await fixture();try{const req=await f.service.create(a,'issuer',command);await ingestFollowupDeliveryStatuses('tenant',webhook(patch),{verifiedSignature:true});await assert.rejects(f.service.resolve(a,req.id,'owner',{expectedVersion:1}));assert.equal(f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!.status,'waiting_external');}finally{f.restore();}}const f=await fixture();try{const req=await f.service.create(a,'issuer',command);await ingestFollowupDeliveryStatuses('tenant',webhook(),{verifiedSignature:false});await assert.rejects(f.service.resolve(a,req.id,'owner',{expectedVersion:1}));await assert.rejects(f.service.resolve(a,req.id,'stranger',{expectedVersion:1}),/owner_required/);f.data.users!.find(u=>u.id==='owner')!.disabled=true;await assert.rejects(f.service.get(a,req.id,'owner'),/actor_forbidden/);await assert.rejects(f.service.get({...a,tenantId:'foreign'},req.id,'issuer'),/actor_forbidden/);}finally{f.restore();}});
test('partial current claim stays blocked until every ordered message receives actual signed terminal receipt',async()=>{const f=await fixture();try{const r=f.item.provider_receipt as any;f.item.draft_body='First useful update. Second useful update. Third useful update. Fourth useful update.';r.expectedMessages=planMobileChatMessages(f.item.draft_body).messages;assert.equal(r.expectedMessages.length,2);r.messages=[{index:0,messageId:'wamid.first',body:r.expectedMessages[0]}];r.statuses=[{messageId:'wamid.first',status:'delivered',occurredAt:'2026-10-06T12:00:00Z',signedClaimEvidence:{verifiedSignature:true,claimToken:token,index:0,recipientId:f.item.wa_number,approvedBatchVersion:f.batch.version,approvedContentHash:f.item.content_hash}}];assert.throws(()=>verifyCompleteSignedFollowupReceipt(f.item,f.batch),/incomplete/);r.messages.push({index:1,messageId:'wamid.second',body:r.expectedMessages[1]});r.statuses.push({...r.statuses[0],messageId:'wamid.second',signedClaimEvidence:{...r.statuses[0].signedClaimEvidence,index:1}});assert.equal(verifyCompleteSignedFollowupReceipt(f.item,f.batch).messageIds.length,2);r.statuses[1].signedClaimEvidence.approvedBatchVersion=1;assert.throws(()=>verifyCompleteSignedFollowupReceipt(f.item,f.batch),/signed_identity_invalid/);r.statuses[1].signedClaimEvidence.approvedBatchVersion=f.batch.version;r.statuses[1].status='failed';assert.throws(()=>verifyCompleteSignedFollowupReceipt(f.item,f.batch),/terminal_receipt_required/);}finally{f.restore();}});
test('actual two-message partial webhook recovery waits for final index, rejects source drift and outstanding dependencies',async()=>{const f=await fixture();try{f.item.draft_body='First useful update. Second useful update. Third useful update. Fourth useful update.';const {createHash}=await import('node:crypto');const h=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');f.item.content_hash=h(f.item.draft_body);f.batch.content_hash=h([f.item.content_hash]);f.data.approval_requests![0]!.content_hash=f.batch.content_hash;const r=f.item.provider_receipt as any;r.approvedContentHash=f.item.content_hash;r.expectedMessages=planMobileChatMessages(f.item.draft_body).messages;const req=await f.service.create(a,'issuer',command);await ingestFollowupDeliveryStatuses('tenant',webhook(),{verifiedSignature:true});assert.equal(f.item.status,'partial_sent');await assert.rejects(f.service.resolve(a,req.id,'owner',{expectedVersion:1}));await ingestFollowupDeliveryStatuses('tenant',webhook({id:'wamid.actual.second',biz_opaque_callback_data:`followup:${token}:1`}),{verifiedSignature:true});const task=f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!;task.depends_on=['followup_batch_approval'];f.data.workflow_tasks!.find(t=>t.task_key==='followup_batch_approval')!.status='pending';await assert.rejects(f.service.resolve(a,req.id,'owner',{expectedVersion:1}),/dependencies_pending/);f.data.workflow_tasks!.find(t=>t.task_key==='followup_batch_approval')!.status='succeeded';assert.equal((await f.service.resolve(a,req.id,'owner',{expectedVersion:1})).item.status,'resolved');f.item.wa_number='19991234567';await assert.rejects(f.service.get(a,req.id,'owner'),/source_drift/);}finally{f.restore();}});
