import {INITIAL_CAPACITY_SCHEDULE_REQUIRED} from './weeklyInitialScheduleGate.js';
import {createHash} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import type {WeeklyScheduledPackage,WeeklyScheduleSnapshot} from '../../shared/contracts/socialWeeklyScheduleRevision.js';
import {SocialProgramError} from './service.js';
import {publicationInstant} from './publicationDeadlines.js';
export const SCHEDULE_PROPOSALS='social_weekly_schedule_proposals',SCHEDULE_SNAPSHOTS='social_weekly_schedule_snapshots';
export function scheduleStable(v:unknown):string{if(Array.isArray(v))return `[${v.map(scheduleStable).join(',')}]`;if(v&&typeof v==='object')return `{${Object.entries(v).sort(([a],[b])=>a.localeCompare(b)).map(([k,x])=>`${JSON.stringify(k)}:${scheduleStable(x)}`).join(',')}}`;return JSON.stringify(v);}
export const scheduleHash=(v:unknown)=>createHash('sha256').update(scheduleStable(v)).digest('hex');
export const scheduleTaskSignature=(t:WeeklyExecutionTask)=>scheduleHash([t.workflowKind,t.scope,t.subjectId,t.publicationTaskId??null,t.schedule.stepKind,t.schedule.responsibleActor]);
export function scheduleTargetGraphFingerprint(pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[],inputHash:(task:WeeklyExecutionTask)=>string):string{
 const byId=new Map(tasks.map(t=>[t.taskId,t]));
 return scheduleHash({executionGraphVersion:pkg.executionGraphVersion??1,version:pkg.version,previousVersion:pkg.previousVersion,publicationTasks:pkg.socialContentPackage.publicationTasks.map(({status,...p})=>p),tasks:tasks.map(t=>({signature:scheduleTaskSignature(t),inputHash:inputHash(t),dependencies:t.dependsOnTaskIds.map(id=>{const dependency=byId.get(id);if(!dependency)throw new SocialProgramError('weekly_schedule_target_dependency_missing',409,'目标图依赖缺失。');return scheduleTaskSignature(dependency);}),latestStartAt:t.schedule.latestStartAt??null,latestFinishAt:t.schedule.latestFinishAt??null})).sort((a,b)=>a.signature.localeCompare(b.signature))});
}
export async function readScheduleSnapshot(store:DataStore,tenantId:string,pkg:WeeklyOperatingPackage,ref:VersionedSocialRef):Promise<WeeklyScheduleSnapshot>{
 const rows=await store.list<Record_>(SCHEDULE_SNAPSHOTS,{where:{tenant_id:tenantId,snapshot_id:ref.id},perPage:2});if(ref.type!=='weekly_schedule_snapshot'||ref.version!==1||rows.items.length!==1||rows.totalItems!==1)throw new SocialProgramError('weekly_schedule_snapshot_missing',409,'缺少真实冻结容量排期。');const s=rows.items[0]!.payload as WeeklyScheduleSnapshot;
 if(!s||s.tenantId!==tenantId||s.programId!==pkg.programId||s.packageId!==pkg.packageId||s.targetVersion!==pkg.version||s.sourceVersion!==pkg.previousVersion||s.confirmedBy!==pkg.createdBy||publicationInstant(s.confirmedAt)===null||rows.items[0]!.content_hash!==scheduleHash(s))throw new SocialProgramError('weekly_schedule_snapshot_corrupt',409,'冻结容量排期身份或证据不一致。');
 if(s.targetExecutionGraphVersion!==undefined&&s.targetExecutionGraphVersion!==(pkg.executionGraphVersion??1))throw new SocialProgramError('weekly_schedule_target_graph_version_changed',409,'目标任务图版本与已确认倒排不同。');
 const times=pkg.socialContentPackage.publicationTasks.map(t=>({publicationTaskId:t.publicationTaskId,publishWindow:t.publishWindow}));if(scheduleStable(times)!==scheduleStable(s.publicationTimes))throw new SocialProgramError('weekly_schedule_publication_changed',409,'发布时刻与已确认倒排不一致。');return s;
}
export async function applyFrozenWeeklySchedule(store:DataStore,tenantId:string,pkg:WeeklyOperatingPackage,tasks:WeeklyExecutionTask[]):Promise<WeeklyExecutionTask[]>{
 const ref=(pkg as WeeklyScheduledPackage).scheduleRevisionRef;if(!ref)return tasks;const s=await readScheduleSnapshot(store,tenantId,pkg,ref);if(s.targetGraphHash){const {weeklyContinuationInputHash}=await import('./weeklyExecutionContinuations.js');if(s.targetGraphHash!==scheduleTargetGraphFingerprint(pkg,tasks,weeklyContinuationInputHash))throw new SocialProgramError('weekly_schedule_target_graph_changed',409,'目标图实际输入与已确认排期不同。');}const bySignature=new Map(s.assignments.map(a=>[a.signature,a]));if(bySignature.size!==s.assignments.length||tasks.length!==s.assignments.length)throw new SocialProgramError('weekly_schedule_graph_changed',409,'任务图与确认倒排不同。');const seen=new Set<string>();const scheduled=tasks.map(t=>{const signature=scheduleTaskSignature(t),a=bySignature.get(signature);if(!a||seen.has(signature)||a.targetTaskId&&a.targetTaskId!==t.taskId||a.origin==='new_planned'&&(a.sourceTaskId!==null||(a.mode??'planned')!=='planned'||a.sourceInputHash!==undefined)||a.origin==='existing_source'&&typeof a.sourceTaskId!=='string'||publicationInstant(a.startAt)===null||publicationInstant(a.finishAt)===null||Date.parse(a.finishAt)<Date.parse(a.startAt)||((a.mode??'planned')!=='completed_verified'&&!a.resourceKey)||(a.mode&&a.mode!=='planned'&&(!a.sourceTaskId||!a.sourceInputHash||!/^[a-f0-9]{64}$/.test(a.sourceInputHash))))throw new SocialProgramError('weekly_schedule_assignment_invalid',409,'冻结任务分配不完整。');seen.add(signature);return {...t,ownBlockingReasons:t.ownBlockingReasons.filter(reason=>reason!==INITIAL_CAPACITY_SCHEDULE_REQUIRED),upstreamVersionRefs:[...t.upstreamVersionRefs,{type:'weekly_schedule_snapshot',id:s.snapshotId,version:1}],inputSnapshot:{...t.inputSnapshot,...(a.mode&&a.mode!=='planned'?{weeklyContinuationPending:{mode:a.mode,sourceTaskId:a.sourceTaskId,sourceInputHash:a.sourceInputHash,snapshotId:s.snapshotId}}:{}),scheduleRevisionRef:{type:'weekly_schedule_snapshot',id:s.snapshotId,version:1}},schedule:{...t.schedule,estimatedStartAt:a.startAt,estimatedFinishAt:a.finishAt,estimatedDurationMinutes:(Date.parse(a.finishAt)-Date.parse(a.startAt))/60000},nextAttemptAt:a.startAt};});
 const byId=new Map(scheduled.map(t=>[t.taskId,t]));for(const t of scheduled){const start=Date.parse(t.schedule.estimatedStartAt),finish=Date.parse(t.schedule.estimatedFinishAt);if(t.dependsOnTaskIds.some(id=>!byId.has(id)||Date.parse(byId.get(id)!.schedule.estimatedFinishAt)>start)||t.schedule.latestFinishAt&&finish>Date.parse(t.schedule.latestFinishAt))throw new SocialProgramError('weekly_schedule_dependency_deadline_changed',409,'新任务依赖或截止与冻结倒排不一致。');if(t.schedule.stepKind==='publishing'){const publication=pkg.socialContentPackage.publicationTasks.find(p=>p.publicationTaskId===t.publicationTaskId);if(!publication||publicationInstant(publication.publishWindow)!==start)throw new SocialProgramError('weekly_schedule_publish_time_changed',409,'倒排不可改动明确发布时刻。');}}return scheduled;
}
