import test from 'node:test';
import assert from 'node:assert/strict';
import type {WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import {weeklyContinuationInputHash,createWeeklyExecutionContinuationService} from './weeklyExecutionContinuations.js';
const source=():WeeklyExecutionTask=>({tenantId:'t',programId:'p',packageId:'w',packageVersion:1,taskId:'old',workflowKind:'content',scope:'publication',subjectId:'video',accountId:'a',publicationTaskId:'video',inputSnapshot:{publicationTask:{title:'real fact',publishWindow:'2026-10-09T10:00:00Z'}},upstreamVersionRefs:[{type:'enterprise_profile',id:'profile',version:1}],budget:{},dependsOnTaskIds:[],schedule:{stepKind:'video_generation',responsibleActor:'content_agent',actualStartedAt:'2026-10-09T01:00:00Z',actualFinishedAt:'2026-10-09T02:00:00Z'},status:'succeeded',resultRefs:[{type:'real_artifact',id:'artifact',version:1}]} as unknown as WeeklyExecutionTask);
test('semantic fingerprint survives settlement and schedule metadata, but real facts/source versions change it',()=>{const old=source(),next=structuredClone(old);next.packageVersion=2;next.taskId='new';next.status='queued';next.inputSnapshot.scheduleRevisionRef={type:'weekly_schedule_snapshot',id:'schedule',version:1};next.schedule.actualFinishedAt=null;assert.equal(weeklyContinuationInputHash(old),weeklyContinuationInputHash(next));next.upstreamVersionRefs[0]!.version=2;assert.notEqual(weeklyContinuationInputHash(old),weeklyContinuationInputHash(next));next.upstreamVersionRefs=old.upstreamVersionRefs;next.inputSnapshot.publicationTask={title:'changed fact'};assert.notEqual(weeklyContinuationInputHash(old),weeklyContinuationInputHash(next));});
function memory(t:WeeklyExecutionTask):DataStore {const row={id:'row',payload:t};return {list:async<T=Record_>(_c:string)=>({items:[row as unknown as T],totalItems:1,totalPages:1,page:1,perPage:500}),getById:async()=>null,create:async()=>null,update:async()=>false,delete:async()=>false};}
test('completed planner receipt is derived from raw actual timestamps and calls validator with original scope',async()=>{const old=source();let observed=false;const service=createWeeklyExecutionContinuationService(memory(old),{validateResults:async(t,refs)=>{assert.equal(t.packageVersion,1);assert.deepEqual(refs,old.resultRefs);observed=true;}});const result=await service.derivePlannerEvidence({tenantId:'t',programId:'p',packageId:'w',packageVersion:1},'2026-10-09T03:00:00Z');assert(observed);assert.equal(result.completedEvidence.old!.actualFinishedAt,old.schedule.actualFinishedAt);assert.deepEqual(result.observedReservations,{});});
test('missing raw completion time fails rather than using updatedAt or server now',async()=>{const old=source();old.schedule.actualFinishedAt=null;old.updatedAt='2026-10-09T02:00:00Z';await assert.rejects(()=>createWeeklyExecutionContinuationService(memory(old),{validateResults:async()=>{}}).derivePlannerEvidence({tenantId:'t',programId:'p',packageId:'w',packageVersion:1},'2026-10-09T03:00:00Z'),/承接证据/);});
