import {controlledMessengerAccount} from '../messenger/controlledCapability.fixture.js';
import test from 'node:test';import assert from 'node:assert/strict';
import type {DataStore} from '../storage/datastore.js';
import {selectWeeklyChannelConversation,verifyWeeklyChannelSelection,type WeeklyChannelConversation,type WeeklyChannelConversationPort} from './weeklyCustomerChannelScope.js';
import type {WeeklyCustomerRelationshipScope} from './weeklyCustomerRelationshipScope.js';
const scope:WeeklyCustomerRelationshipScope={tenantId:'tenant',programId:'program',packageId:'week',packageVersion:1,runId:'run',goalId:'goal',route:'cold_start',weekStart:'2026-10-05T00:00:00+08:00',weekEnd:'2026-10-11T23:59:59+08:00'};
function fixture(){const account:Record<string,unknown>=controlledMessengerAccount({accountId:'account',tenantId:'tenant',pageId:'page'});
 const c:WeeklyChannelConversation={tenantId:'tenant',customerId:'buyer',channel:'messenger',nativeAccountId:'page',recipientId:'native-buyer',conversationId:'messenger:page:native-buyer',messages:[{id:'mid.native',actor:'buyer',body:'What is the minimum order?',timestamp:Date.parse('2026-10-06T01:00:00Z'),audit:{providerMessageId:'mid.native',providerRecipientId:'native-buyer'}}]};
 const store={async getById(){return structuredClone(account);}}as unknown as DataStore;const port:WeeklyChannelConversationPort={async read(){return structuredClone([c]);}};return {account,c,store,port,input:{scope,channel:'messenger' as const,accountId:'account',customerId:'buyer',inboundMessageId:'mid.native'}};}
test('freezes actual account and provider inbound without inferring new relationship or completion',async()=>{const f=fixture();const value=await selectWeeklyChannelConversation(f.store,f.input,f.port);assert.equal(value.conversationId,f.c.conversationId);assert.equal(value.inboundAt,'2026-10-06T01:00:00.000Z');assert.equal('classification' in value,false);assert.deepEqual(await verifyWeeklyChannelSelection(f.store,scope,value,f.port),value);});
test('disconnected channel and foreign account remain gaps',async()=>{const f=fixture();f.account.status='disconnected';await assert.rejects(selectWeeklyChannelConversation(f.store,f.input,f.port),/not_connected/);f.account.status='connected';f.account.tenantId='other';await assert.rejects(selectWeeklyChannelConversation(f.store,f.input,f.port),/not_connected/);});
test('seller, missing provider identity and duplicate messages cannot count as inbound',async()=>{for(const change of [(m:any)=>m.actor='seller',(m:any)=>delete m.audit,(m:any)=>m.audit.providerRecipientId='other']){const f=fixture();change(f.c.messages[0]);await assert.rejects(selectWeeklyChannelConversation(f.store,f.input,f.port),/real_inbound_required/);}const f=fixture();f.c.messages.push(f.c.messages[0]);await assert.rejects(selectWeeklyChannelConversation(f.store,f.input,f.port),/ambiguous/);});
test('scope, account authority or provider message bytes drift revokes frozen selection',async()=>{const f=fixture();const v=await selectWeeklyChannelConversation(f.store,f.input,f.port);await assert.rejects(verifyWeeklyChannelSelection(f.store,{...scope,packageVersion:2},v,f.port),/scope_changed/);(f.c.messages[0]as any).body='Changed';await assert.rejects(verifyWeeklyChannelSelection(f.store,scope,v,f.port),/evidence_changed/);});
test('Instagram resolves its actual own native account identity, never Facebook account',async()=>{const f=fixture();f.account.platform='instagram';f.account.providerAccountId='ig';f.c.channel='instagram';f.c.nativeAccountId='ig';f.c.conversationId='instagram:ig:native-buyer';assert.equal((await selectWeeklyChannelConversation(f.store,{...f.input,channel:'instagram'},f.port)).nativeAccountId,'ig');await assert.rejects(selectWeeklyChannelConversation(f.store,f.input,f.port),/not_connected/);});
