import type {DataStore} from '../storage/datastore.js';
import type {VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import type {ContentTemplateStructureConstraint,ContentTemplateRole} from '../../shared/socialContentTemplateStructure.js';
import {validContentTemplateStructure} from '../../shared/socialContentTemplateStructure.js';
import {createWeeklyContentTemplateService,type TemplateTarget} from './weeklyContentTemplates.js';
import {socialObject} from '../starter198/socialContentValidation.js';
import {SocialProgramError} from './service.js';
function role(value:unknown):ContentTemplateRole{const text=typeof value==='string'?value.toLowerCase():'';if(/hook|opening|开场/.test(text))return 'hook';if(/cta|closing|收束|引导/.test(text))return 'cta';if(/proof|evidence|quality|证明|证据|质量/.test(text))return 'proof';if(/process|过程|流程/.test(text))return 'process';if(/context|scenario|场景/.test(text))return 'context';if(/value|benefit|价值/.test(text))return 'value';return 'information';}
/** Extracts a fixed vocabulary and numeric pacing only. No source sentence, brand, face, fact or asset identifier can enter the new script. */
export async function readWeeklyTemplateStructure(store:DataStore,target:TemplateTarget,bindingRef:VersionedSocialRef):Promise<ContentTemplateStructureConstraint>{if(bindingRef.type!=='weekly_content_template_binding'||bindingRef.version!==1)throw new SocialProgramError('content_template_binding_ref_invalid',409,'模板绑定版本无效。');const read=await createWeeklyContentTemplateService(store).readForPlanning(target,bindingRef.id),baseline=socialObject(read.template.structure.scriptBaseline),plan=socialObject(read.template.structure.directorPlan),direction=socialObject(plan?.direction),voice=socialObject(direction?.voiceover);const rows=Array.isArray(baseline?.scenes)?baseline.scenes:[];const c:ContentTemplateStructureConstraint={schemaVersion:'content-template-structure.v1',bindingRef,templateRef:read.binding.templateRef,candidateHash:read.template.recordHash,roles:rows.map(s=>role(socialObject(s)?.shotFunction)),pace:direction?.pace as ContentTemplateStructureConstraint['pace'],voiceSpeed:Number(voice?.speed),pauseStyle:voice?.pauseStyle as ContentTemplateStructureConstraint['pauseStyle']};if(!validContentTemplateStructure(c))throw new SocialProgramError('content_template_structure_unusable',409,'已确认模板缺少可核验的结构或节奏。');return c;}
/** Called by the real artifact validator after original production identity/file checks. */
export async function validateWeeklyTemplateProductionOutput(input:{store:DataStore;task:import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask;contentRow:Record<string,unknown>;artifactRow?:Record<string,unknown>;preSupply?:Pick<import('../starter198/socialWeeklyPreSupplyHandoff.js').WeeklyPreSupplyHandoff,'tenantId'|'programId'|'packageId'|'packageVersion'|'publicationTaskId'|'assetAvailability'|'templateIntention'|'baseline'>}):Promise<void>{
const {parseStoredSocialScriptBaseline}=await import('../starter198/socialContentScriptBaseline.js'),{parseStoredSocialDirectorPlan}=await import('../starter198/socialContentDirectorPlan.js'),{contentTemplateOutputMatches,contentTemplateScriptMatches}=await import('../../shared/socialContentTemplateStructure.js'),{socialJson}=await import('../starter198/socialContentValidation.js');
const rows=await input.store.list<import('../storage/datastore.js').Record_>('social_weekly_operating_packages',{where:{tenant_id:input.task.tenantId,program_id:input.task.programId,package_id:input.task.packageId,version:input.task.packageVersion},perPage:2});if(rows.totalItems!==1||rows.items.length!==1)throw new SocialProgramError('content_template_actual_package_missing',409,'模板输出缺少实际冻结周版本。');
const pkg=socialObject(socialJson(rows.items[0]!.payload)),pubs=socialObject(pkg?.socialContentPackage)?.publicationTasks,actual=Array.isArray(pubs)?pubs.map(socialObject).filter(p=>p?.publicationTaskId===input.task.publicationTaskId):[];if(pkg?.packageId!==input.task.packageId||pkg.version!==input.task.packageVersion||pkg.programId!==input.task.programId||actual.length!==1||!actual[0])throw new SocialProgramError('content_template_actual_publication_missing',409,'模板输出缺少实际发布条目。');
const actualRef=socialObject(actual[0].contentTemplateBindingRef),authority=socialObject(socialObject(socialJson(input.contentRow.brief))?._weeklyAuthority),publication=socialObject(authority?.publicationTask),ref=socialObject(publication?.contentTemplateBindingRef),baseline=parseStoredSocialScriptBaseline(input.contentRow.script_baseline);
if(!actualRef){if(ref||baseline?.contentTemplateStructure)throw new SocialProgramError('content_template_unbound_output',409,'产物宣称使用了未绑定模板。');return;}
if(!ref||ref.type!==actualRef.type||ref.id!==actualRef.id||ref.version!==actualRef.version||publication?.publicationTaskId!==input.task.publicationTaskId)throw new SocialProgramError('content_template_authority_binding_missing',409,'生产身份遗漏或改变了实际冻结模板绑定。');
const constraint=await readWeeklyTemplateStructure(input.store,{tenantId:input.task.tenantId,programId:input.task.programId,packageId:input.task.packageId,packageVersion:input.task.packageVersion,publicationTaskId:input.task.publicationTaskId!},actualRef as unknown as VersionedSocialRef);if(!baseline||JSON.stringify(baseline.contentTemplateStructure)!==JSON.stringify(constraint)||!contentTemplateScriptMatches(constraint,baseline))throw new SocialProgramError('content_template_output_mismatch',409,'实际脚本输出未满足确认的模板结构。');if(input.task.schedule?.stepKind==='script')return;
if(input.preSupply){const h=input.preSupply,t=h.templateIntention;if(input.task.workflowKind!=='directing'||input.task.schedule?.stepKind!=='storyboard'||input.artifactRow||h.tenantId!==input.task.tenantId||h.programId!==input.task.programId||h.packageId!==input.task.packageId||h.packageVersion!==input.task.packageVersion||h.publicationTaskId!==input.task.publicationTaskId||h.assetAvailability!=='planned_not_generated'||!t||JSON.stringify(t.structure)!==JSON.stringify(constraint)||JSON.stringify(h.baseline)!==JSON.stringify(baseline)||t.pace!==constraint.pace||t.voiceSpeed!==constraint.voiceSpeed||t.pauseStyle!==constraint.pauseStyle)throw new SocialProgramError('content_template_pre_supply_mismatch',409,'实际制作前结构与确认模板不一致。');return;}
const plan=parseStoredSocialDirectorPlan(input.contentRow.director_plan);if(!plan||!contentTemplateOutputMatches(constraint,baseline,plan))throw new SocialProgramError('content_template_output_mismatch',409,'实际分镜输出未满足确认的模板结构和节奏。');
if(input.artifactRow||['asset_generation','video_generation','quality_check','rework'].includes(input.task.schedule?.stepKind)){if(!input.artifactRow||input.artifactRow.task_id!==input.contentRow.task_id)throw new SocialProgramError('content_template_artifact_lineage_required',409,'模板产物缺少真实生成版本凭据。');const content=socialObject(socialJson(input.artifactRow.content)),artifactBaseline=socialObject(content?.scriptBaseline),artifactPlan=socialObject(content?.directorPlan);const {resolveSocialDirectorArtifactLineage}=await import('../starter198/socialContentDirectorPlanVersions.js'),{createStarter198Repository}=await import('../starter198/repository.js'),{socialRequestHash}=await import('../starter198/socialContentValidation.js');const frozen=await resolveSocialDirectorArtifactLineage({repository:createStarter198Repository(input.store),tenantId:input.task.tenantId,taskId:String(input.contentRow.task_id),reference:content?.directorPlanReference});if(artifactBaseline?.version!==baseline.version||artifactPlan?.version!==frozen.version||artifactPlan.baselineVersion!==baseline.version||frozen.factSnapshot.captureMode!=='verified_context'||frozen.factSnapshot.baselineHash!==socialRequestHash(baseline)||frozen.plan.scriptSource.baselineVersion!==baseline.version||!contentTemplateOutputMatches(constraint,baseline,frozen.plan))throw new SocialProgramError('content_template_artifact_input_changed',409,'成片生成时使用的真实冻结输入与模板结构不一致。');}}

