import type{DataStore,Record_}from'../storage/datastore.js';import type{WeeklyExecutionTask,VersionedSocialRef}from'../../shared/contracts/socialProgram.js';import type{WeeklyCreativeRepairAuditReceipt}from'../../shared/contracts/weeklyCreativeRepairAudit.js';import type{WeeklyCreativeRepairChildExecution}from'../../shared/contracts/weeklyCreativeRepairExecution.js';import type{WeeklyProductionRepairCase}from'../../shared/contracts/weeklyProductionRepairCase.js';
import{createStarter198Repository}from'../starter198/repository.js';import{createSocialSceneReworkService}from'../starter198/socialContentSceneReworkService.js';import{assertSocialDirectorG5Audit}from'../starter198/socialDirectorG5ReviewService.js';import{socialJson,socialObject,socialRequestHash}from'../starter198/socialContentValidation.js';import{assertNoFrozenTechnicalFailure}from'../runtime/weeklyContentQualityAudit.js';import{resolveWeeklyCreativeRepairAuthority}from'../runtime/weeklyCreativeRepairAuthority.js';import{getWeeklyExecutionTaskRow,recomputePackageExecution,withWeeklyExecutionTaskMutation,writeWeeklyExecutionTask}from'./executionTasks.js';import{withWeeklyProductionAdmissionGuard}from'./weeklyCancellation.js';import{createWeeklyProductionRepairCaseService,WEEKLY_PRODUCTION_REPAIR_CASES}from'./weeklyProductionRepairCases.js';import{SocialProgramError}from'./service.js';
export const WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS='social_weekly_creative_repair_child_executions',WEEKLY_CREATIVE_REPAIR_AUDITS='social_weekly_creative_repair_audits';
const fail=(c:string,s=409):never=>{throw new SocialProgramError(`weekly_creative_repair_completion_${c}`,s,'创意返工子成片的执行或复检证据尚未满足恢复条件。');};const need:(v:unknown,c:string)=>asserts v=(v,c)=>{if(!v)fail(c);};
async function one(store:DataStore,collection:string,where:Record<string,string|number>,code:string){const r=await store.list<Record_>(collection,{where,perPage:2});if(r.totalItems!==1||r.items.length!==1)fail(code,r.totalItems?503:409);return r.items[0]!;}
function decode(row:Record_){const x=socialObject(socialJson(row.payload))as unknown as WeeklyCreativeRepairChildExecution|null;need(x&&x.schemaVersion==='weekly-creative-repair-child-execution.v1'&&x.version===1,'mapping_corrupt');const{recordHash,...body}=x;need(recordHash===socialRequestHash(body)&&row.content_hash===socialRequestHash(x)&&row.case_id===x.caseId,'mapping_corrupt');return structuredClone(x);}
function ref(row:Record_):VersionedSocialRef{const version=Number(String(row.version).replace(/^v/,''));need(Number.isSafeInteger(version)&&version>0,'artifact_version_invalid');return{type:'starter_social_content_artifact',id:String(row.artifact_id),version};}
/** Reads existing durable execution and audits. It never starts or completes production. */
export function createWeeklyCreativeRepairCompletionService(store:DataStore,clock:()=>Date=()=>new Date()){
 const cases=createWeeklyProductionRepairCaseService(store,clock),repository=createStarter198Repository(store);
 async function execution(t:string,c:string){return decode(await one(store,WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS,{tenant_id:t,case_id:c},'mapping_missing'));}
 async function saveCase(item:WeeklyProductionRepairCase,state:WeeklyProductionRepairCase['state'],childArtifactRef:VersionedSocialRef,assert:()=>Promise<void>){const row=await one(store,WEEKLY_PRODUCTION_REPAIR_CASES,{tenant_id:item.tenantId,case_id:item.caseId},'case_changed');need(row.content_hash===socialRequestHash(item),'case_changed');const{recordHash:_,...body}=item,b={...body,state,childArtifactRef,updatedAt:clock().toISOString()},next={...b,recordHash:socialRequestHash(b)};await assert();need(await store.update(WEEKLY_PRODUCTION_REPAIR_CASES,row.id,{state,content_hash:socialRequestHash(next),payload:next}),'case_save_failed');return next;}
 async function existingAudit(t:string,c:string){const r=await store.list<Record_>(WEEKLY_CREATIVE_REPAIR_AUDITS,{where:{tenant_id:t,case_id:c},perPage:2});if(r.totalItems!==r.items.length||r.items.length>1)fail('audit_ambiguous',503);if(!r.items.length)return null;const x=socialObject(socialJson(r.items[0]!.payload))as unknown as WeeklyCreativeRepairAuditReceipt|null;need(x&&r.items[0]!.content_hash===socialRequestHash(x),'audit_corrupt');const{recordHash,...body}=x;need(recordHash===socialRequestHash(body),'audit_corrupt');return x;}
 return{execution,async reconcile(tenantId:string,actorUserId:string,caseId:string){const initial=await cases.read(tenantId,caseId);return withWeeklyProductionAdmissionGuard({dataStore:store,tenantId,packageId:initial.packageId,packageVersion:initial.packageVersion,action:async assert=>{
  const item=await cases.read(tenantId,caseId),mapped=await execution(tenantId,caseId);need(item.kind==='creative_revision'&&item.execution&&['running','awaiting_audit','resolved'].includes(item.state),'case_state_invalid');need(actorUserId===item.ownerUserId||actorUserId===item.reviewerUserId,'actor_forbidden');need(mapped.state==='running'&&mapped.childTaskId&&mapped.runId&&mapped.jobId&&mapped.caseRequestHash===item.requestHash&&mapped.parentArtifactHash===item.parent.artifactHash&&mapped.runId===item.execution.runId&&mapped.jobId===item.execution.jobId,'mapping_changed');
  const task=await one(store,'starter_social_content_tasks',{tenant_id:tenantId,task_id:mapped.childTaskId},'task_missing'),authority=await resolveWeeklyCreativeRepairAuthority({store,tenantId,task,now:clock()});need(authority&&authority.proof.caseId===caseId&&authority.proof.originalAuthorityHash===mapped.authorityHash&&authority.configuration.recordHash===mapped.configurationHash,'authority_changed');const run=await store.getById<Record_>('workflow_runs',mapped.runId),job=await store.getById<Record_>('content_execution_jobs',mapped.jobId);need(task.run_id===mapped.runId&&run?.tenant_id===tenantId&&job?.tenant_id===tenantId&&job.task_id===mapped.childTaskId&&job.run_id===mapped.runId,'execution_scope_changed');
  const productionSettled=['succeeded','completed'].includes(String(run.status))||run.status==='waiting_external'&&run.pause_reason==='automatic_acceptance_evidence_incomplete';if(!productionSettled||job.status!=='succeeded')return item;need(job.completed_at&&(['succeeded','completed'].includes(String(run.status))?run.completed_at:true),'completion_evidence_missing');
  const ar=await store.list<Record_>('starter_social_content_artifacts',{where:{tenant_id:tenantId,task_id:mapped.childTaskId},perPage:2});need(ar.totalItems===1&&ar.items.length===1,'artifact_missing');const artifact=ar.items[0]!,content=socialObject(socialJson(artifact.content));need(content&&artifact.content_hash===socialRequestHash({resourceRef:artifact.resource_ref,content})&&artifact.origin==='agent'&&artifact.artifact_kind==='short_video'&&['draft','review_required','approved'].includes(String(artifact.status))&&socialObject(content.render)?.completed===true,'artifact_changed');assertNoFrozenTechnicalFailure(content);const childRef=ref(artifact),cache=await createSocialSceneReworkService(repository).readCache({tenantId,taskId:mapped.childTaskId,runId:mapped.runId,parentArtifactId:childRef.id});need(cache.cache.parentArtifactHash===artifact.content_hash&&cache.cache.scenes.length>0&&cache.cache.scenes.every(s=>s.status==='passed'),'g4_pending');const auditing=item.state==='running'?await saveCase(item,'awaiting_audit',childRef,assert):item;const audit=await assertSocialDirectorG5Audit(repository,{tenantId,taskId:mapped.childTaskId,runId:mapped.runId,artifactId:childRef.id,artifactHash:String(artifact.content_hash)}),result=socialObject(content.productionResult),g5=audit.receipt;need(result&&g5.gate==='G5'&&g5.status==='passed'&&g5.handoffId===cache.handoffId&&g5.handoffVersion===cache.handoffVersion&&g5.productionResultRef.id===result.productionResultId&&g5.productionResultRef.version===result.version&&g5.productionResultRef.recordHash===socialRequestHash(result)&&g5.artifactRefs.includes(String(artifact.resource_ref)),'g5_source_changed');
  const prior=await existingAudit(tenantId,caseId),body={schemaVersion:'weekly-creative-repair-audit.v1'as const,version:1 as const,tenantId,programId:item.programId,packageId:item.packageId,packageVersion:item.packageVersion,caseId,caseRequestHash:item.requestHash,executionRecordHash:mapped.recordHash,childTaskId:mapped.childTaskId,childRunId:mapped.runId,childJobId:mapped.jobId,childArtifactRef:childRef,childArtifactHash:String(artifact.content_hash),sceneCacheHash:cache.cache.recordHash,g5ReviewId:audit.review.reviewId,g5ReviewHash:audit.review.recordHash,g5ReceiptId:g5.receiptId,g5ReceiptHash:g5.recordHash,verifiedBy:actorUserId,verifiedAt:clock().toISOString()},receipt={...body,recordHash:socialRequestHash(body)};if(prior)need(prior.executionRecordHash===mapped.recordHash&&prior.childArtifactHash===artifact.content_hash&&prior.g5ReceiptHash===g5.recordHash,'audit_changed');else{await assert();need(await store.create(WEEKLY_CREATIVE_REPAIR_AUDITS,{tenant_id:tenantId,program_id:item.programId,package_id:item.packageId,package_version:item.packageVersion,case_id:caseId,content_hash:socialRequestHash(receipt),payload:receipt}),'audit_save_failed');}
  const resolved=auditing.state==='resolved'?auditing:await saveCase(auditing,'resolved',childRef,assert);await withWeeklyExecutionTaskMutation(store,tenantId,item.approvalTaskId,async()=>{const row=await getWeeklyExecutionTaskRow(store,tenantId,item.approvalTaskId),approval:WeeklyExecutionTask=row.payload;need(approval.programId===item.programId&&approval.packageId===item.packageId&&approval.packageVersion===item.packageVersion&&approval.publicationTaskId===item.publicationTaskId&&approval.schedule.stepKind==='user_approval'&&!approval.lease&&!['cancelled','dead_letter'].includes(approval.status),'approval_scope_changed');const own=approval.ownBlockingReasons.filter(r=>r!==`weekly_repair_case_open:${caseId}`);if(own.length===approval.ownBlockingReasons.length)return;await assert();await writeWeeklyExecutionTask(store,row,{...approval,ownBlockingReasons:own,status:own.length||approval.inheritedBlockingTaskIds.length?'blocked':'queued',resultRefs:[],updatedAt:clock().toISOString()});});await recomputePackageExecution(store,tenantId,item.programId,item.packageId,item.packageVersion,clock().toISOString(),false);return resolved;
 }});}};
}
