import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyProductionRepairCase} from '../../shared/contracts/weeklyProductionRepairCase.js';
import type {WeeklyCreativeRepairCapacityPreview,WeeklyCreativeRepairChildExecution} from '../../shared/contracts/weeklyCreativeRepairExecution.js';
import {socialJson,socialObject,socialRequestHash} from '../starter198/socialContentValidation.js';
import {createWeeklyProductionRepairCaseService,WEEKLY_PRODUCTION_REPAIR_CASES} from './weeklyProductionRepairCases.js';
import {createWeeklyCreativeRepairConfigurationService,type CreativeRepairConfiguration} from './weeklyCreativeRepairConfiguration.js';
import {withWeeklyProductionAdmissionGuard} from './weeklyCancellation.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {SocialProgramError} from './service.js';

export const WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS='social_weekly_creative_repair_child_executions';

export interface WeeklyCreativeRepairProductionPort {
  preview(input:{case:WeeklyProductionRepairCase;configuration:CreativeRepairConfiguration;actorUserId:string}):Promise<WeeklyCreativeRepairCapacityPreview>;
  confirmCapacity(input:{case:WeeklyProductionRepairCase;configuration:CreativeRepairConfiguration;actorUserId:string;preview:WeeklyCreativeRepairCapacityPreview;authorizedMaximumCostCny:number;startIdempotencyKey:string}):Promise<{reservationId:string;expiresAt:string}>;
  start(input:{case:WeeklyProductionRepairCase;configuration:CreativeRepairConfiguration;actorUserId:string;mapping:WeeklyCreativeRepairChildExecution}):Promise<{status:'started';childTaskId:string;childBindingKey:string;runId:string;jobId:string}|{status:'unknown'}>;
  reconcileStart(input:{case:WeeklyProductionRepairCase;configuration:CreativeRepairConfiguration;mapping:WeeklyCreativeRepairChildExecution}):Promise<{status:'started';childTaskId:string;childBindingKey:string;runId:string;jobId:string}|{status:'absent'}|{status:'unknown'}>;
}

function fail(code:string,status=409):never{throw new SocialProgramError(`weekly_creative_repair_execution_${code}`,status,'创意返工容量、权限或生产回执已变化，请重新核验。');}
const validHash=(value:string)=>/^[a-f0-9]{64}$/.test(value);
const validId=(value:string)=>/^[a-zA-Z0-9._:@-]{1,240}$/.test(value);
const seal=(value:Omit<WeeklyCreativeRepairChildExecution,'recordHash'>|WeeklyCreativeRepairChildExecution):WeeklyCreativeRepairChildExecution=>{const{recordHash:_,...body}=value as WeeklyCreativeRepairChildExecution;return{...body,recordHash:socialRequestHash(body)};};

export function createWeeklyCreativeRepairExecutionService(store:DataStore,port:WeeklyCreativeRepairProductionPort,clock:()=>Date=()=>new Date()){
 const cases=createWeeklyProductionRepairCaseService(store,clock),configurations=createWeeklyCreativeRepairConfigurationService(store,clock);
 async function actor(tenantId:string,userId:string){const row=await store.getById<Record_>('users',userId),role=organizationRoleOrNull(row?.role);if(!row||row.tenantId!==tenantId||row.disabled===true||row.active===false||['disabled','suspended'].includes(String(row.status))||!role||!['social_operator','admin','super_admin'].includes(role))fail('actor_forbidden',403);}
 async function rows(tenantId:string,caseId:string){const result=await store.list<Record_>(WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS,{where:{tenant_id:tenantId,case_id:caseId},perPage:2});if(result.totalItems!==result.items.length||result.items.length>1)fail('mapping_ambiguous',503);return result.items;}
 function decode(row:Record_){
  const value=socialObject(socialJson(row.payload)) as unknown as WeeklyCreativeRepairChildExecution;
  if(!value||row.content_hash!==socialRequestHash(value)||value.schemaVersion!=='weekly-creative-repair-child-execution.v1'||value.version!==1)fail('mapping_corrupt',503);
  const{recordHash,...body}=value;
  if(recordHash!==socialRequestHash(body)||row.tenant_id!==value.tenantId||row.case_id!==value.caseId)fail('mapping_corrupt',503);
  const ids=[value.childTaskId,value.childBindingKey,value.runId,value.jobId],all=ids.every(v=>typeof v==='string'&&validId(v)),none=ids.every(v=>v===null);
  if((value.state==='running'&&!all)||(value.state!=='running'&&!none))fail('mapping_corrupt',503);
  return structuredClone(value);
 }
 async function read(tenantId:string,caseId:string){const found=await rows(tenantId,caseId);return found.length?decode(found[0]!):null;}
 async function scope(tenantId:string,actorUserId:string,caseId:string){await actor(tenantId,actorUserId);const item=await cases.read(tenantId,caseId);if(item.kind!=='creative_revision'||item.ownerUserId!==actorUserId)fail('owner_required',403);const configuration=await configurations.read(tenantId,caseId);if(!configuration)fail('configuration_required');if(configuration.parentArtifactHash!==item.parent.artifactHash||configuration.decisionOperationId!==(item.trigger.type==='user_changes_requested'?item.trigger.operationId:'')||configuration.feedbackHash!==(item.trigger.type==='user_changes_requested'?item.trigger.noteHash:''))fail('configuration_changed');return{item,configuration};}
 function validatePreview(item:WeeklyProductionRepairCase,configuration:CreativeRepairConfiguration,preview:WeeklyCreativeRepairCapacityPreview){if(preview.caseId!==item.caseId||preview.caseRecordHash!==item.recordHash||preview.configurationHash!==configuration.recordHash||!validHash(preview.previewHash)||!validHash(preview.authorityHash)||preview.estimatedDurationMinutes!==configuration.estimatedDurationMinutes||preview.maximumCostCny!==configuration.maximumCostCny||!Number.isFinite(Date.parse(preview.availableUntil))||Date.parse(preview.availableUntil)<=clock().getTime()||(!preview.localOnly&&!preview.quoteHash)||preview.localOnly&&preview.quoteHash!==null)fail('preview_invalid',503);}
 async function caseRow(item:WeeklyProductionRepairCase){const result=await store.list<Record_>(WEEKLY_PRODUCTION_REPAIR_CASES,{where:{tenant_id:item.tenantId,case_id:item.caseId},perPage:2});if(result.totalItems!==1||result.items.length!==1||result.items[0]!.content_hash!==socialRequestHash(item))fail('case_changed');return result.items[0]!;}
 async function writeCase(item:WeeklyProductionRepairCase,state:'ready'|'running',mapping:WeeklyCreativeRepairChildExecution){const row=await caseRow(item),{recordHash:_,...body}=item,updatedBody={...body,state,execution:state==='running'?{operationId:mapping.childTaskId!,runId:mapping.runId!,jobId:mapping.jobId!}:null,updatedAt:clock().toISOString()},updated={...updatedBody,recordHash:socialRequestHash(updatedBody)};if(!await store.update(WEEKLY_PRODUCTION_REPAIR_CASES,row.id,{state,content_hash:socialRequestHash(updated),payload:updated}))fail('case_save_failed',503);return updated;}
 async function writeMapping(current:WeeklyCreativeRepairChildExecution,next:WeeklyCreativeRepairChildExecution){const found=await rows(current.tenantId,current.caseId);if(found.length!==1||found[0]!.content_hash!==socialRequestHash(current))fail('mapping_changed');if(!await store.update(WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS,found[0]!.id,{state:next.state,content_hash:socialRequestHash(next),payload:next}))fail('mapping_save_failed',503);return next;}
 async function bindRunning(item:WeeklyProductionRepairCase,mapping:WeeklyCreativeRepairChildExecution){if(mapping.state!=='running'||!mapping.childTaskId||!mapping.runId||!mapping.jobId)fail('receipt_invalid',503);if(item.execution){if(item.execution.operationId!==mapping.childTaskId||item.execution.runId!==mapping.runId||item.execution.jobId!==mapping.jobId)fail('case_execution_conflict',503);return item;}if(!['ready','running'].includes(item.state))fail('case_state_invalid');return writeCase(item,'running',mapping);}
 async function acceptReceipt(item:WeeklyProductionRepairCase,mapping:WeeklyCreativeRepairChildExecution,receipt:{status:'started';childTaskId:string;childBindingKey:string;runId:string;jobId:string}){const expectedBinding=`weekly-creative-repair:${item.packageId}:${item.packageVersion}:${item.publicationTaskId}:${item.caseId}`;if(![receipt.childTaskId,receipt.runId,receipt.jobId].every(validId)||receipt.childBindingKey!==expectedBinding)fail('receipt_invalid',503);const now=clock().toISOString(),next=seal({...mapping,state:'running',childTaskId:receipt.childTaskId,childBindingKey:receipt.childBindingKey,runId:receipt.runId,jobId:receipt.jobId,lastReconciledAt:now,updatedAt:now});const saved=await writeMapping(mapping,next);return bindRunning(item,saved);}
 return{read,
  async previewCapacity(tenantId:string,actorUserId:string,caseId:string){const{item,configuration}=await scope(tenantId,actorUserId,caseId);if(!['awaiting_capacity','ready'].includes(item.state)||item.execution)fail('case_state_invalid');const preview=await port.preview({case:item,configuration,actorUserId});validatePreview(item,configuration,preview);return preview;},
  async confirmCapacity(tenantId:string,actorUserId:string,caseId:string,input:{expectedCaseRecordHash:string;expectedConfigurationHash:string;expectedPreviewHash:string;expectedAuthorityHash:string;expectedQuoteHash?:string;authorizedMaximumCostCny:number}){const initial=await cases.read(tenantId,caseId);return withWeeklyProductionAdmissionGuard({dataStore:store,tenantId,packageId:initial.packageId,packageVersion:initial.packageVersion,action:async assert=>{const{item,configuration}=await scope(tenantId,actorUserId,caseId),existing=await read(tenantId,caseId);if(existing){if(existing.configurationHash!==input.expectedConfigurationHash||existing.previewHash!==input.expectedPreviewHash||existing.authorityHash!==input.expectedAuthorityHash||existing.quoteHash!==(input.expectedQuoteHash??null)||existing.authorizedMaximumCostCny!==input.authorizedMaximumCostCny)fail('capacity_immutable');if(item.state==='awaiting_capacity')return writeCase(item,'ready',existing);return item;}
   if(item.recordHash!==input.expectedCaseRecordHash||configuration.recordHash!==input.expectedConfigurationHash||item.state!=='awaiting_capacity'||item.execution)fail('version_conflict');const preview=await port.preview({case:item,configuration,actorUserId});validatePreview(item,configuration,preview);if(preview.previewHash!==input.expectedPreviewHash||preview.authorityHash!==input.expectedAuthorityHash||preview.quoteHash!==(input.expectedQuoteHash??null)||input.authorizedMaximumCostCny<0||input.authorizedMaximumCostCny>configuration.maximumCostCny||(preview.localOnly&&input.authorizedMaximumCostCny!==0))fail('capacity_changed');const startIdempotencyKey=`weekly-creative-repair-start:${caseId}:${configuration.recordHash}`;await assert();const reservation=await port.confirmCapacity({case:item,configuration,actorUserId,preview,authorizedMaximumCostCny:input.authorizedMaximumCostCny,startIdempotencyKey});if(!validId(reservation.reservationId)||!Number.isFinite(Date.parse(reservation.expiresAt))||Date.parse(reservation.expiresAt)<=clock().getTime()||Date.parse(reservation.expiresAt)>Date.parse(configuration.deadlineAt))fail('reservation_invalid',503);const now=clock().toISOString(),body={schemaVersion:'weekly-creative-repair-child-execution.v1' as const,version:1 as const,tenantId,caseId,caseRequestHash:item.requestHash,configurationHash:configuration.recordHash,parentTaskId:item.parent.taskId,parentRunId:item.parent.runId,parentArtifactHash:item.parent.artifactHash,authorityHash:preview.authorityHash,previewHash:preview.previewHash,capacityReservationId:reservation.reservationId,capacityExpiresAt:new Date(reservation.expiresAt).toISOString(),localOnly:preview.localOnly,quoteHash:preview.quoteHash,authorizedMaximumCostCny:input.authorizedMaximumCostCny,startIdempotencyKey,state:'capacity_confirmed' as const,childTaskId:null,childBindingKey:null,runId:null,jobId:null,confirmedBy:actorUserId,confirmedAt:now,lastReconciledAt:null,createdAt:now,updatedAt:now},mapping=seal(body);const created=await store.create(WEEKLY_CREATIVE_REPAIR_CHILD_EXECUTIONS,{id:socialRequestHash([tenantId,caseId]).slice(0,15),tenant_id:tenantId,case_id:caseId,state:mapping.state,content_hash:socialRequestHash(mapping),payload:mapping});if(!created){const recovered=await read(tenantId,caseId);if(!recovered||recovered.recordHash!==mapping.recordHash)fail('mapping_save_failed',503);}return writeCase(item,'ready',mapping);}});},
  async start(tenantId:string,actorUserId:string,caseId:string,input:{expectedCaseRecordHash:string}){const initial=await cases.read(tenantId,caseId);return withWeeklyProductionAdmissionGuard({dataStore:store,tenantId,packageId:initial.packageId,packageVersion:initial.packageVersion,action:async assert=>{let{item,configuration}=await scope(tenantId,actorUserId,caseId);let mapping=await read(tenantId,caseId);if(!mapping)fail('capacity_required');if(mapping.caseRequestHash!==item.requestHash||mapping.configurationHash!==configuration.recordHash||mapping.parentArtifactHash!==item.parent.artifactHash)fail('mapping_scope_invalid',503);if(mapping.state==='running')return bindRunning(item,mapping);if(item.recordHash!==input.expectedCaseRecordHash||item.state!=='ready'||item.execution)fail('version_conflict');if(clock().getTime()>Date.parse(mapping.capacityExpiresAt))fail('capacity_expired');
   if(mapping.state==='start_pending'||mapping.state==='reconciling'){await assert();const reconciled=await port.reconcileStart({case:item,configuration,mapping});if(reconciled.status==='started')return acceptReceipt(item,mapping,reconciled);const now=clock().toISOString();if(reconciled.status==='unknown'){if(mapping.state!=='reconciling'){mapping=await writeMapping(mapping,seal({...mapping,state:'reconciling',lastReconciledAt:now,updatedAt:now}));}fail('start_outcome_unknown',503);}mapping=await writeMapping(mapping,seal({...mapping,state:'start_pending',lastReconciledAt:now,updatedAt:now}));}
   if(mapping.state==='capacity_confirmed'){const now=clock().toISOString();mapping=await writeMapping(mapping,seal({...mapping,state:'start_pending',updatedAt:now}));}
   await assert();
   try {
    const result=await port.start({case:item,configuration,actorUserId,mapping});
    if(result.status==='started')return acceptReceipt(item,mapping,result);
    const now=clock().toISOString();
    await writeMapping(mapping,seal({...mapping,state:'reconciling',lastReconciledAt:now,updatedAt:now}));
    fail('start_outcome_unknown',503);
   } catch(error) {
    if(error instanceof SocialProgramError)throw error;
    const now=clock().toISOString();
    await writeMapping(mapping,seal({...mapping,state:'reconciling',lastReconciledAt:now,updatedAt:now}));
    fail('start_outcome_unknown',503);
   }
  }});}
 };
}
