import {ownedReferenceChannelId} from './ownedReferenceSupply.js';
import {createHash} from 'node:crypto';import type {DataStore,Record_} from '../storage/datastore.js';import type {WeeklyExecutionTask,WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';import {SocialProgramError} from './service.js';import {socialJson,socialObject,socialRequestHash} from '../starter198/socialContentValidation.js';import {createWeeklyPlanningAuthority} from './planningAuthority.js';import {listSocialDiscoverySupply} from '../socialDiscovery/supply.js';import {ownedReferenceSupply} from './ownedReferenceSupply.js';import {publicationInstant} from './publicationDeadlines.js';
export const OWNED_METRIC_GAP='owned_reference_metrics_required';
export interface OwnedMetricSupplementAuthority{tenantId:string;programId:string;packageId:string;packageVersion:number;actorUserId:string}
import type {OwnedMetricSupplementOption} from '../../shared/contracts/weeklySupplementRequests.js';
export type {OwnedMetricSupplementOption} from '../../shared/contracts/weeklySupplementRequests.js';
const fail=(code:string):never=>{throw new SocialProgramError(code,409,code);};const obj=(v:unknown)=>socialObject(socialJson(v))??{};
async function unique(store:DataStore,c:string,where:Record<string,string|number>){const r=await store.list<Record_>(c,{where,page:1,perPage:2});if(r.totalItems!==1||r.items.length!==1||Object.entries(where).some(([k,v])=>r.items[0]![k]!==v))fail('owned_metric_supplement_source_not_unique');return r.items[0]!;}
export async function readOwnedMetricSupplement(store:DataStore,a:OwnedMetricSupplementAuthority,t:WeeklyExecutionTask,ref?:VersionedSocialRef){
 if(t.tenantId!==a.tenantId||t.programId!==a.programId||t.packageId!==a.packageId||t.packageVersion!==a.packageVersion||t.workflowKind!=='directing'||!['benchmark_scoring','director_analysis'].includes(t.schedule.stepKind)||t.inputSnapshot.referenceSource!=='owned'||typeof t.inputSnapshot.motherContentId!=='string')fail('owned_metric_supplement_consumer_invalid');
 const pkg=obj((await unique(store,'social_weekly_operating_packages',{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.packageVersion})).payload) as unknown as WeeklyOperatingPackage;
 if(pkg.programId!==a.programId||pkg.version!==a.packageVersion||pkg.referenceSourcePolicy?.profile!=='b2b_established'||!['draft','active'].includes(pkg.status))fail('owned_metric_supplement_profile_invalid');
 const plan=await createWeeklyPlanningAuthority(store).get(a.tenantId,a.programId,a.packageId,a.packageVersion);if(socialRequestHash(plan.referenceSourcePolicy)!==socialRequestHash(pkg.referenceSourcePolicy))fail('owned_metric_supplement_policy_changed');
 const slots=plan.skeleton.slots.filter(s=>s.motherContentId===t.inputSnapshot.motherContentId&&s.referenceSource==='owned');if(slots.length!==1)fail('owned_metric_supplement_slot_invalid');const slot=slots[0]!;
 const analyses=plan.directorAnalyses.filter(x=>x.slotId===slot.slotId);if(analyses.length!==1||!analyses[0]!.benchmarkVideoRefs?.length||analyses[0]!.benchmarkVideoRefs.length!==1)fail('owned_metric_supplement_reference_required');const analysis=analyses[0]!;
 const videos=await listSocialDiscoverySupply({tenantId:a.tenantId,dataStore:store,filters:{candidateType:'video',decision:'accepted',businessModel:'b2b',sort:'score',perPage:100}});
 const video=videos.items.find(v=>v.candidateId===analysis.benchmarkVideoRefs[0]!.id&&v.evidenceVersion===analysis.benchmarkVideoRefs[0]!.version);if(!video)return fail('owned_metric_supplement_reference_changed');
 const pairs=(await ownedReferenceSupply(store,a.tenantId,a.programId,[video])).filter(p=>slot.accountIds.includes(p.account.accountId)&&analysis.benchmarkAccountRefs.some(r=>r.type==='owned_social_account'&&r.id===p.account.accountId&&r.version===p.account.version));if(pairs.length!==1)fail('owned_metric_supplement_account_content_mismatch');const pair=pairs[0]!;
 const contentRow=await store.getById<Record_>('social_external_contents',pair.evidenceRef.slice('owned_content:'.length));const content=obj(contentRow?.content);if(!contentRow||contentRow.tenant_id!==a.tenantId||content.accountId!==contentRow.account_id||![pair.account.accountId,pair.account.connectionId].includes(String(content.accountId))||content.externalContentId!==pair.externalContentId)return fail('owned_metric_supplement_account_content_mismatch');
 const sourceHash=socialRequestHash({scope:{tenantId:a.tenantId,programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion},policy:pkg.referenceSourcePolicy,slot,videoRef:analysis.benchmarkVideoRefs[0],account:pair.account,externalContentId:pair.externalContentId,ownedContentRef:pair.evidenceRef,sourceUrl:video.sourceUrl,frozenHandoffRefs:analysis.frozenHandoffRefs});
 let snapshot:OwnedMetricSupplementOption['snapshot']=null;const performance=pair.historicalPerformance;
 if(performance){const row=await unique(store,'social_channel_metric_snapshots',{tenant_id:a.tenantId,snapshot_id:performance.snapshotRef.id});const s=obj(row.snapshot),metrics=obj(s.metrics);const keys=['views','likes','comments','shares','favorites','completionRate','followerDelta','attributedInquiries'];const canonicalMetrics=Object.fromEntries(keys.map(k=>[k,typeof metrics[k]==='number'&&Number.isFinite(metrics[k])?metrics[k]:null]));const subject={tenantId:a.tenantId,channelId:content.channelId,accountId:content.accountId,externalContentId:pair.externalContentId,source:s.source,capturedAt:s.capturedAt,metrics:canonicalMetrics};const canonicalId=`sms_${createHash('sha256').update(JSON.stringify(subject)).digest('hex').slice(0,24)}`;
 if(s.schemaVersion!=='social-metric-snapshot.v1'||!['official_api','assisted_browser','public_page'].includes(String(s.source))||s.snapshotId!==canonicalId||s.tenantId!==a.tenantId||s.accountId!==subject.accountId||s.channelId!==content.channelId||ownedReferenceChannelId(pair.account.platform)!==ownedReferenceChannelId(String(s.channelId))||s.externalContentId!==pair.externalContentId||row.account_id!==s.accountId||row.channel_id!==s.channelId||row.external_content_id!==s.externalContentId||publicationInstant(String(s.capturedAt))===null||Date.parse(String(s.capturedAt))>Date.now()||row.source!==s.source||row.captured_at!==s.capturedAt)fail('owned_metric_supplement_platform_snapshot_unverified');
 const value=(k:string)=>typeof metrics[k]==='number'&&Number.isFinite(metrics[k])&&Number(metrics[k])>=0?Number(metrics[k]):null;snapshot={ref:{type:'social_channel_metric_snapshot',id:String(s.snapshotId),version:1},capturedAt:String(s.capturedAt),source:String(s.source),metrics:{views:value('views'),likes:value('likes'),shares:value('shares'),comments:value('comments')}};
 }
 if(ref&&(!snapshot||ref.type!=='social_channel_metric_snapshot'||ref.version!==1||ref.id!==snapshot.ref.id))fail('owned_metric_supplement_snapshot_changed');
 const missingMetrics=(['views','likes','shares','comments'] as const).filter(k=>snapshot?.metrics[k]===null||snapshot?.metrics[k]===undefined);
 const requiredBefore=t.schedule.latestStartAt;const deadline=publicationInstant(requiredBefore??'')!==null?String(requiredBefore):null;
 const option:OwnedMetricSupplementOption={consumerTaskId:t.taskId,slotId:slot.slotId,motherContentId:slot.motherContentId,accountId:pair.account.accountId,connectionId:String(content.accountId),platform:String(pair.account.platform),externalContentId:pair.externalContentId,videoTitle:video.title,videoUrl:video.sourceUrl,missingMetrics,requiredBefore:deadline,sourceHash,ready:missingMetrics.length===0,gapCode:missingMetrics.length?OWNED_METRIC_GAP:'',snapshot};
 return{ready:option.ready,code:option.gapCode,sourceHash,evidenceRef:option.ready?snapshot!.ref:null,option};
}
export async function reanalyzeOwnedMetricConsumer(store:DataStore,a:OwnedMetricSupplementAuthority,t:WeeklyExecutionTask,ref:VersionedSocialRef){const before=await readOwnedMetricSupplement(store,a,t,ref);if(!before.ready)fail('owned_metric_supplement_still_missing');const authority=createWeeklyPlanningAuthority(store),plan=await authority.get(a.tenantId,a.programId,a.packageId,a.packageVersion);if(plan.status==='dispatched')fail('owned_metric_supplement_requires_new_revision');const existing=plan.directorAnalyses.find(x=>x.slotId===before.option.slotId);if(existing?.historicalPerformance?.snapshotRef.id===ref.id&&existing.ownedReferenceDiagnosis?.performanceStatus==='complete'&&!existing.ownedReferenceDiagnosis.missingMetrics.length)return plan;const next=await authority.runDirectorAnalysis({...a,expectedPlanningVersion:plan.version,actor:'director_agent',selectedSlotIds:[before.option.slotId],preserveOwnedReferences:true});const slot=next.skeleton.slots.find(s=>s.slotId===before.option.slotId);const analysis=next.directorAnalyses.find(x=>x.slotId===before.option.slotId);if(slot?.referenceSource!=='owned'||socialRequestHash(next.referenceSourcePolicy)!==socialRequestHash(plan.referenceSourcePolicy)||analysis?.historicalPerformance?.snapshotRef.id!==ref.id||analysis?.ownedReferenceDiagnosis?.missingMetrics.length||analysis?.ownedReferenceDiagnosis?.performanceStatus!=='complete')fail('owned_metric_supplement_reanalysis_receipt_invalid');return next;}
