import type{DataStore,Record_}from'../storage/datastore.js';
import type{WeeklyExecutionTask,WeeklyOperatingPackage}from'../../shared/contracts/socialProgram.js';
import type{WeeklyReviewEvidenceView}from'../../shared/contracts/weeklyReviewEvidence.js';
import type{FrozenWeeklyReview}from'../../shared/contracts/socialReview.js';
import{socialJson,socialObject}from'../starter198/socialContentValidation.js';
import{organizationRoleOrNull}from'../lib/organizationRole.js';
import{weeklyReviewWindowBounds}from'../socialReview/weeklyReviewTiming.js';
import{validateWeeklyExecutionResults}from'../runtime/socialWeeklyResultValidation.js';
import{SocialProgramError}from'./service.js';
const object=(v:unknown)=>socialObject(socialJson(v))??{};
function fail(code:string,status=409):never{throw new SocialProgramError(code,status,code);}
async function rows(store:DataStore,c:string,where:Record<string,string|number>){const all:Record_[]=[];const ids=new Set<string>();let count:number|undefined;for(let page=1;page<=1000;page++){const r=await store.list<Record_>(c,{where,page,perPage:250,sort:'id'});if(!Number.isSafeInteger(r.totalItems)||r.totalItems<0||count!==undefined&&count!==r.totalItems)fail('weekly_review_read_pagination_changed');count=r.totalItems;for(const row of r.items){if(!row?.id||ids.has(row.id))fail('weekly_review_read_pagination_duplicate');ids.add(row.id);all.push(row);}if(all.length===count)return all;if(!r.items.length)break;}return fail('weekly_review_read_pagination_incomplete');}
/** Scope-only read. Never invokes review scans, freezing, promotion allocation or production. */
export async function readWeeklyReviewEvidence(store:DataStore,input:{tenantId:string;actorUserId:string;programId:string;packageId:string;packageVersion:number;taskId:string;now?:Date}):Promise<WeeklyReviewEvidenceView>{if(!Number.isSafeInteger(input.packageVersion)||input.packageVersion<=0)fail('weekly_review_read_version_invalid',400);const now=input.now??new Date();if(!Number.isFinite(now.getTime()))fail('weekly_review_read_clock_invalid');const actor=await store.getById<Record_>('users',input.actorUserId);if(actor?.tenantId!==input.tenantId||!organizationRoleOrNull(actor.role)||actor.disabled===true||actor.active===false||['disabled','suspended'].includes(String(actor.status)))fail('weekly_review_read_actor_forbidden',403);
 const packRows=await rows(store,'social_weekly_operating_packages',{tenant_id:input.tenantId,program_id:input.programId,package_id:input.packageId,version:input.packageVersion});const raw=object(packRows[0]?.payload);if(packRows.length!==1||raw.programId!==input.programId||raw.packageId!==input.packageId||raw.version!==input.packageVersion)fail('weekly_review_read_package_missing',404);if(packRows[0]?.mock||packRows[0]?.simulated||packRows[0]?.synthetic||raw.mock||raw.simulated||raw.synthetic)fail('weekly_review_read_synthetic_package');const pkg=raw as unknown as WeeklyOperatingPackage;let bounds:ReturnType<typeof weeklyReviewWindowBounds>;try{bounds=weeklyReviewWindowBounds(pkg);}catch{fail('weekly_review_read_window_invalid');}
 const taskRows=await rows(store,'social_weekly_execution_tasks',{tenant_id:input.tenantId,program_id:input.programId,package_id:input.packageId,package_version:input.packageVersion,task_id:input.taskId});const task=object(taskRows[0]?.payload)as unknown as WeeklyExecutionTask;if(taskRows.length!==1||task.tenantId!==input.tenantId||task.programId!==input.programId||task.packageId!==input.packageId||task.packageVersion!==input.packageVersion||task.taskId!==input.taskId||!['performance_monitoring','weekly_review'].includes(task.schedule?.stepKind)||!Array.isArray(task.resultRefs)||(task.schedule.stepKind==='weekly_review'?task.workflowKind!=='review':task.workflowKind!=='engagement'))fail('weekly_review_read_task_missing',404);
 if(taskRows[0]?.mock||taskRows[0]?.simulated||taskRows[0]?.synthetic||!['pending_activation','queued','leased','succeeded','blocked','cancelled','dead_letter'].includes(task.status))fail('weekly_review_read_task_unverified');
 const gaps:string[]=[],metrics:WeeklyReviewEvidenceView['metrics']=[];
 for(const ref of task.resultRefs){if(!ref||typeof ref.type!=='string'||typeof ref.id!=='string'||!Number.isSafeInteger(ref.version)||ref.version<=0)fail('weekly_review_read_result_ref_invalid');if(ref.type==='social_metric_snapshot'&&task.schedule.stepKind==='performance_monitoring'){try{await validateWeeklyExecutionResults(store,task,[ref],now);const row=await store.getById<Record_>('social_metric_snapshots',ref.id);const values=object(row?.metrics);metrics.push({ref,accountId:String(row!.account_id),contentId:typeof row!.content_id==='string'?row!.content_id:null,capturedAt:String(row!.captured_at),source:String(row!.source||'未记录来源类型'),values:{views:typeof values.views==='number'?values.views:null,likes:typeof values.likes==='number'?values.likes:null,shares:typeof values.shares==='number'?values.shares:null,comments:typeof values.comments==='number'?values.comments:null}});}catch{gaps.push(`指标引用 ${ref.id} 无法按真实执行范围核验`);}}else if(ref.type!=='weekly_review_snapshot'||task.schedule.stepKind!=='weekly_review')gaps.push(`未支持的复盘证据类型：${ref.type}`);}
 const reportRows=await rows(store,'social_weekly_review_snapshots',{tenant_id:input.tenantId,program_id:input.programId,package_id:input.packageId,package_version:input.packageVersion});if(reportRows.length>1)fail('weekly_review_read_snapshot_ambiguous');let report:FrozenWeeklyReview|null=null;const row=reportRows[0];if(row){const s=object(row.snapshot),window=object(s.window),ref=object(s.operatingPackageRef);if(row.tenant_id!==input.tenantId||row.program_id!==input.programId||row.package_id!==input.packageId||row.package_version!==input.packageVersion||row.mock||row.simulated||row.synthetic||s.tenantId!==input.tenantId||s.programId!==input.programId||ref.type!=='weekly_operating_package'||ref.id!==input.packageId||ref.version!==input.packageVersion||s.version!==1||s.snapshotId!==row.snapshot_id||typeof row.source_digest!=='string'||!/^[0-9a-f]{64}$/.test(row.source_digest)||s.sourceDigest!==row.source_digest||typeof row.frozen_by!=='string'||!row.frozen_by||window.frozenAt!==row.frozen_at||window.startsAt!==bounds.startsAt||window.endsAt!==bounds.endsAt||!Number.isFinite(Date.parse(String(window.frozenAt)))||Date.parse(String(window.frozenAt))<Date.parse(bounds.endsAt)||Date.parse(String(window.frozenAt))>now.getTime()||!Array.isArray(s.contents)||!Array.isArray(s.byAccount)||!Array.isArray(s.byBusinessDirection)||!socialObject(s.sampleSufficiency)||!socialObject(s.evidenceBoundary)||!socialObject(s.maintenanceEffort))fail('weekly_review_read_snapshot_unverified');const sample=object(s.sampleSufficiency),boundary=object(s.evidenceBoundary),effort=object(s.maintenanceEffort);if(!['sufficient','insufficient','unavailable'].includes(String(sample.status))||!Array.isArray(sample.reasons)||!sample.reasons.every(r=>typeof r==='string')||['ownedContentCount','attributableContentCount','minimumOwnedContent'].some(k=>!Number.isSafeInteger(sample[k])||Number(sample[k])<0)||!Array.isArray(boundary.externalReferenceContentIds)||!Array.isArray(boundary.ownedContentIds)||!['available','unknown','unavailable'].includes(String(effort.availability)))fail('weekly_review_read_snapshot_shape_invalid');for(const c of s.contents){const content=object(c),metric=object(content.metrics);if(typeof content.contentId!=='string'||typeof content.accountId!=='string'||typeof content.platform!=='string'||typeof content.businessDirection!=='string'||!socialObject(content.metrics)||!['external_reference','owned_content_result'].includes(String(content.evidenceKind))||(!Array.isArray(content.metricSnapshotRefs)||!content.metricSnapshotRefs.every(r=>typeof r==='string')))fail('weekly_review_read_content_invalid');for(const value of Object.values(metric)){const m=object(value);if(!['available','unknown','unavailable'].includes(String(m.availability))||(m.availability==='available'?(typeof m.value!=='number'||!Number.isFinite(m.value)||m.value<0):m.value!==null))fail('weekly_review_read_metric_invalid');}}report=s as unknown as FrozenWeeklyReview;}
 for(const ref of task.resultRefs.filter(r=>r.type==='weekly_review_snapshot'))if(ref.version!==1||!report||report.snapshotId!==ref.id)gaps.push(`冻结报告引用 ${ref.id} 不属于当前周版本`);
 const closed=now.getTime()>=Date.parse(bounds.endsAt);if(!report){if(!closed)gaps.push('真实周复盘窗口尚未结束');else gaps.push('本周版本尚无已冻结的真实社媒报告');}if(task.schedule.stepKind==='performance_monitoring'&&!metrics.length)gaps.push('此执行任务尚无可核验的指标引用；未观测值保持未知');
 const taskBlocking=[...(Array.isArray(task.ownBlockingReasons)?task.ownBlockingReasons.filter(r=>typeof r==='string'):[]),...(Array.isArray(task.inheritedBlockingTaskIds)?task.inheritedBlockingTaskIds.filter(id=>typeof id==='string').map(id=>`等待上游 ${id}`):[])];const state:WeeklyReviewEvidenceView['state']=gaps.some(g=>g.includes('无法')||g.includes('不属于')||g.includes('未支持'))?'blocked':report?'report_frozen':metrics.length?'monitoring_evidence':!closed?'waiting_window':task.status==='blocked'||task.status==='dead_letter'?'blocked':'waiting_evidence';
 return{scope:{programId:input.programId,packageId:input.packageId,packageVersion:input.packageVersion,taskId:input.taskId},task:{stepKind:task.schedule.stepKind as WeeklyReviewEvidenceView['task']['stepKind'],status:task.status,accountId:task.accountId??null,publicationTaskId:task.publicationTaskId??null,resultRefs:task.resultRefs,scheduledFinishAt:task.schedule.estimatedFinishAt,blockingReasons:taskBlocking,lastError:typeof task.lastError?.message==='string'?task.lastError.message:null},window:{...bounds,closed,semantics:'existing_worker_utc_reporting_window'},metrics,report,state,gaps,checkedAt:now.toISOString()};}
