import test from 'node:test';import assert from 'node:assert/strict';
import {prepareFiveMotherOwnedReferenceFixture} from '../runtime/weeklyFiveMotherOwnedReference.fixture';
import {createWeeklyPlanningAuthority} from './planningAuthority';
import {socialRequestHash} from '../starter198/socialContentValidation';
import type {Record_} from '../storage/datastore';
const copyWithoutId=(row:Record_):Record<string,unknown>=>{const {id,...body}=structuredClone(row);return body;};
test('single owned slot reanalysis preserves its whole-week reference index and unrelated external bindings',async t=>{
 const f=await prepareFiveMotherOwnedReferenceFixture(t,40),id=`${f.ownedReferenceId}-second`,url=`https://www.tiktok.com/@owned/video/${id}`;
 const video=structuredClone(f.f.tables.trend_videos!.find(r=>r.id===f.ownedReferenceId)!);Object.assign(video,{id,sourceUrl:url,title:'Second controlled owned reference'});await f.f.store.create('trend_videos',video);
 const evidence=copyWithoutId(f.f.tables.social_candidate_evidence!.find(r=>r.candidateId===f.ownedReferenceId)!);evidence.evidenceId=`evidence-${id}`;evidence.candidateId=id;(evidence.evidence as Record<string,unknown>).inspirationId=id;(evidence.g1 as Record<string,unknown>).sourceUrl=url;await f.f.store.create('social_candidate_evidence',evidence);
 const handoffRow=f.f.tables.starter_social_inspiration_handoff_versions!.find(r=>(r.payload as Record<string,unknown>).inspirationId===f.ownedReferenceId)!,handoff=structuredClone(handoffRow.payload) as Record<string,unknown>;handoff.inspirationId=id;handoff.analysisId=`analysis-${id}`;(handoff.source as Record<string,unknown>).sourceUrl=url;await f.f.store.create('starter_social_inspiration_handoff_versions',{tenant_id:'t',handoff_version:'1',record_hash:socialRequestHash(handoff),payload:handoff});
 const content=copyWithoutId(f.f.tables.social_external_contents!.find(r=>r.external_content_id===f.ownedReferenceId)!);content.external_content_id=id;Object.assign(content.content as Record<string,unknown>,{externalContentId:id,publicUrl:url});await f.f.store.create('social_external_contents',content);
 const snapshot=copyWithoutId(f.f.tables.social_channel_metric_snapshots!.find(r=>r.external_content_id===f.ownedReferenceId)!);snapshot.external_content_id=id;snapshot.snapshot_id=`metrics-${id}`;const payload=snapshot.snapshot as Record<string,unknown>;Object.assign(payload,{snapshotId:snapshot.snapshot_id,externalContentId:id});(payload.metrics as Record<string,unknown>).views=1000;await f.f.store.create('social_channel_metric_snapshots',snapshot);
 f.f.tables.social_weekly_agent_planning=[];const service=createWeeklyPlanningAuthority(f.f.store),outline=await service.initialize('t',f.pkg),scope={tenantId:'t',programId:'p',packageId:f.pkg.packageId,packageVersion:f.pkg.version},now=new Date('2026-10-02T00:00:00Z');const all=await service.runDirectorAnalysis({...scope,expectedPlanningVersion:outline.version,actor:'director_agent',now});const owned=all.skeleton.slots.filter(s=>s.referenceSource==='owned');assert.equal(owned.length,2);const second=all.directorAnalyses.find(a=>a.slotId===owned[1]!.slotId)!;assert.equal(second.benchmarkVideoRefs[0]!.id,id);const unrelated=all.directorAnalyses.filter(a=>a.slotId!==second.slotId);const partial=await service.runDirectorAnalysis({...scope,expectedPlanningVersion:all.version,actor:'director_agent',selectedSlotIds:[second.slotId],now});assert.deepEqual(partial.directorAnalyses.find(a=>a.slotId===second.slotId)!.benchmarkVideoRefs,second.benchmarkVideoRefs);assert.deepEqual(partial.directorAnalyses.filter(a=>a.slotId!==second.slotId),unrelated);assert.equal(f.f.tables.content_execution_jobs?.length??0,0);
});
