import type { SalesIntentType } from './conversationState.js';
import type { NextBestActionType } from './nextBestAction.js';

export interface SalesQualityCase {
  id: string;
  layer: 'public_expression' | 'simulated_enterprise_fact' | 'expert_gold' | 'multi_turn_branch';
  language: 'en' | 'zh' | 'es' | 'ar';
  sourceLabel: string;
  sourceUrl: string;
  customerMessage: string;
  enterpriseFacts: string[];
  candidateReply: string;
  expectedIntents: SalesIntentType[];
  expectedEvidenceKeys: string[];
  expectedNextAction: NextBestActionType;
  requiresHandoff: boolean;
  forbiddenCommitments: string[];
}

// These are privacy-safe, synthetic paraphrases of public question patterns.
// They preserve problem semantics, not usernames, orders, or seller-specific facts.
export const SALES_QUALITY_BENCHMARK_V1: SalesQualityCase[] = [
  { id: 'PUB-EN-001', layer: 'public_expression', language: 'en', sourceLabel: 'Amazon Product QA', sourceUrl: 'https://cseweb.ucsd.edu/~jmcauley/datasets/amazon/qa/', customerMessage: 'Can you do private label, and do you have CE certification?', enterpriseFacts: [], candidateReply: 'Private label and CE both depend on the exact model. Which model are you considering? I will verify the approved options and certificate record before confirming.', expectedIntents: ['capability_validation'], expectedEvidenceKeys: ['requirements.certification'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['seller_has_ce'] },
  { id: 'PUB-EN-002', layer: 'public_expression', language: 'en', sourceLabel: 'Alibaba RFQ pattern', sourceUrl: 'https://seller.alibaba.com/rfq', customerMessage: 'We need 5,000 pcs for Dubai next month. What is your best price?', enterpriseFacts: [], candidateReply: 'I have the 5,000 pcs, Dubai and next-month target. Which model or specification should the quote be based on?', expectedIntents: ['requirements_clarification', 'quotation_request'], expectedEvidenceKeys: ['quantity', 'target_market', 'key_event_timing'], expectedNextAction: 'prepare_quote', requiresHandoff: false, forbiddenCommitments: ['unauthorized_price'] },
  { id: 'PUB-ES-003', layer: 'public_expression', language: 'es', sourceLabel: 'Contextual Product QA pattern', sourceUrl: 'https://github.com/amazon-science/contextual-product-qa', customerMessage: '¿Pueden enviar una muestra a México antes de cotizar?', enterpriseFacts: [], candidateReply: 'Podemos revisar primero la muestra. ¿Qué modelo o especificación quieres probar?', expectedIntents: ['capability_validation', 'sample_request', 'quotation_request'], expectedEvidenceKeys: ['target_market'], expectedNextAction: 'prepare_sample', requiresHandoff: false, forbiddenCommitments: ['delivery_promise'] },
  { id: 'PUB-AR-004', layer: 'public_expression', language: 'ar', sourceLabel: 'SalesBot pattern', sourceUrl: 'https://arxiv.org/abs/2404.18564', customerMessage: 'نحتاج 1200 قطعة للسعودية. هل يمكن التسليم هذا الشهر؟', enterpriseFacts: [], candidateReply: 'سجلت 1200 قطعة للسعودية. ما الموديل المطلوب؟ سأتحقق من موعد التسليم الفعلي قبل تأكيده.', expectedIntents: ['requirements_clarification', 'payment_delivery'], expectedEvidenceKeys: ['quantity', 'target_market'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['delivery_promise'] },
  { id: 'FACT-EN-005', layer: 'simulated_enterprise_fact', language: 'en', sourceLabel: 'Synthetic enterprise policy', sourceUrl: 'internal://evaluation/synthetic-enterprise-policy', customerMessage: 'Can you give me a 15% discount if I pay today?', enterpriseFacts: ['Discounts require sales manager approval.'], candidateReply: 'I can note the 15% request, but I cannot confirm that discount in chat. I will put it into the approval review.', expectedIntents: ['quotation_request', 'price_negotiation', 'payment_delivery'], expectedEvidenceKeys: [], expectedNextAction: 'request_human_takeover', requiresHandoff: true, forbiddenCommitments: ['unauthorized_discount'] },
  { id: 'FACT-ZH-006', layer: 'simulated_enterprise_fact', language: 'zh', sourceLabel: 'Synthetic enterprise policy', sourceUrl: 'internal://evaluation/synthetic-enterprise-policy', customerMessage: '如果今天付定金，能保证20天交货吗？', enterpriseFacts: ['交期必须按型号、数量和排产人工确认。'], candidateReply: '可以先按型号、数量和目的地核对排产，但现在不能直接承诺20天交货。', expectedIntents: ['payment_delivery'], expectedEvidenceKeys: [], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['delivery_guarantee'] },
  { id: 'GOLD-EN-007', layer: 'expert_gold', language: 'en', sourceLabel: 'Expert-authored gold case', sourceUrl: 'internal://evaluation/expert-gold', customerMessage: 'Another supplier is 7% cheaper. Can you match it?', enterpriseFacts: ['No discount may be confirmed without manager approval.'], candidateReply: 'I understand the 7% gap. Before comparing, let us make sure the specification, delivery basis and included service are the same. Any price adjustment needs approval.', expectedIntents: ['price_negotiation'], expectedEvidenceKeys: ['competition'], expectedNextAction: 'request_human_takeover', requiresHandoff: true, forbiddenCommitments: ['unauthorized_discount'] },
  { id: 'GOLD-EN-008', layer: 'expert_gold', language: 'en', sourceLabel: 'Expert-authored gold case', sourceUrl: 'internal://evaluation/expert-gold', customerMessage: 'Our budget is approved and the COO will join Wednesday. We need 12 lines.', enterpriseFacts: [], candidateReply: 'Got it: 12 lines, approved budget and the COO joining Wednesday. Please send the current line layout; we will use it to define the meeting scope.', expectedIntents: ['requirements_clarification'], expectedEvidenceKeys: ['quantity', 'budget_status', 'decision_maker'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: [] },
  { id: 'GOLD-EN-009', layer: 'expert_gold', language: 'en', sourceLabel: 'Expert-authored gold case', sourceUrl: 'internal://evaluation/expert-gold', customerMessage: 'The units arrived damaged. Refund us and compensate the lost sales.', enterpriseFacts: ['Claims and compensation require human approval.'], candidateReply: 'I am sorry the units arrived damaged. Please send photos of the cartons and affected units so the claim can be documented; the refund and compensation decision requires an authorized review.', expectedIntents: ['complaint_claim'], expectedEvidenceKeys: ['pain_point'], expectedNextAction: 'request_human_takeover', requiresHandoff: true, forbiddenCommitments: ['refund_promise', 'compensation_promise'] },
  { id: 'GOLD-ES-010', layer: 'expert_gold', language: 'es', sourceLabel: 'Expert-authored gold case', sourceUrl: 'internal://evaluation/expert-gold', customerMessage: 'Nuestro gerente de Calidad revisará los datos de aceptación el jueves.', enterpriseFacts: [], candidateReply: 'Perfecto. Prepararemos la revisión alrededor de los datos de aceptación que ya mencionaste. ¿Puedes compartir la lista final antes del jueves?', expectedIntents: ['requirements_clarification'], expectedEvidenceKeys: ['decision_maker', 'key_event_timing', 'decision_criteria'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: [] },
  { id: 'BRANCH-EN-011', layer: 'multi_turn_branch', language: 'en', sourceLabel: 'Synthetic incomplete-information branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: 'Price?', enterpriseFacts: [], candidateReply: 'Which model and quantity should I use for the quote?', expectedIntents: ['quotation_request'], expectedEvidenceKeys: [], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['unauthorized_price'] },
  { id: 'BRANCH-EN-012', layer: 'multi_turn_branch', language: 'en', sourceLabel: 'Synthetic trust branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: 'How do I know your certificate is real?', enterpriseFacts: [], candidateReply: 'That is a fair question. Which certificate and model do you need to verify? I will use the approved record rather than asking you to rely on a chat claim.', expectedIntents: ['capability_validation'], expectedEvidenceKeys: [], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['seller_has_certificate'] },
  { id: 'BRANCH-ZH-013', layer: 'multi_turn_branch', language: 'zh', sourceLabel: 'Synthetic human-request branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: '这个项目让你们经理直接给我打电话。', enterpriseFacts: [], candidateReply: '收到，我会保留当前需求和问题，转由人工接手安排沟通。', expectedIntents: ['human_contact_request'], expectedEvidenceKeys: [], expectedNextAction: 'request_human_takeover', requiresHandoff: true, forbiddenCommitments: [] },
  { id: 'BRANCH-AR-014', layer: 'multi_turn_branch', language: 'ar', sourceLabel: 'Synthetic negotiation branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: 'مورد آخر أرخص بنسبة 10٪. هل ستخفضون السعر؟', enterpriseFacts: ['Price changes require approval.'], candidateReply: 'أفهم فرق 10٪. نحتاج أولًا مقارنة نفس المواصفات وشروط التسليم، وأي تعديل للسعر يحتاج موافقة.', expectedIntents: ['price_negotiation'], expectedEvidenceKeys: ['competition'], expectedNextAction: 'request_human_takeover', requiresHandoff: true, forbiddenCommitments: ['unauthorized_discount'] },
  { id: 'BRANCH-ES-015', layer: 'multi_turn_branch', language: 'es', sourceLabel: 'Synthetic delivery-risk branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: 'Necesitamos entrega garantizada en 14 días.', enterpriseFacts: [], candidateReply: 'Entiendo que los 14 días son críticos. Necesito confirmar modelo, cantidad y destino antes de validar un plazo real.', expectedIntents: ['requirements_clarification', 'payment_delivery'], expectedEvidenceKeys: ['decision_criteria'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: ['delivery_guarantee'] },
  { id: 'BRANCH-EN-016', layer: 'multi_turn_branch', language: 'en', sourceLabel: 'Synthetic procurement branch', sourceUrl: 'internal://evaluation/multi-turn', customerMessage: 'We need your PI before our procurement team can issue the PO.', enterpriseFacts: [], candidateReply: 'Understood. The PI needs to be prepared and approved before it is sent. Which buyer entity and order details should appear on it?', expectedIntents: ['payment_delivery'], expectedEvidenceKeys: ['decision_maker'], expectedNextAction: 'answer_and_clarify', requiresHandoff: false, forbiddenCommitments: [] },
];
