import { assessmentQuestions, assessMaturity, gapLabels, maturityLabels, maturityProfiles, normalizeAssessment, type Maturity, type OperatingAssessment, type Gap } from '../lib/operatingMaturity';

export default function OperatingAssessmentEditor({ value, maturity, disabled, onChange, onAdopt }: { value?: OperatingAssessment; maturity: Maturity; disabled?: boolean; onChange: (value: OperatingAssessment) => void; onAdopt: (maturity: Maturity) => void }) {
  const assessment = normalizeAssessment(value);
  const result = assessMaturity(assessment);
  return <div className="space-y-5 text-sm text-text-primary">
    <p className="leading-6 text-text-secondary">依据过去四周的实际情况识别运营能力，不按企业年限、团队人数或发帖数量划分。以下为客户自述，可结合记录核实。</p>
    <div className="grid overflow-hidden border-y border-border sm:grid-cols-3 sm:divide-x sm:divide-border">{Object.entries(maturityProfiles).map(([key, profile]) => <div key={key} className={`border-b border-border p-4 last:border-b-0 sm:border-b-0 ${key === maturity ? 'bg-[#eff7f1]' : 'bg-surface'}`}><p className={`font-bold ${key === maturity ? 'text-accent' : 'text-text-primary'}`}>{maturityLabels[key as Maturity]}</p><p className="mt-2 text-xs leading-5 text-text-secondary">{profile.features}</p></div>)}</div>
    <div className="divide-y divide-border border-y border-border">{assessmentQuestions.map((q, i) => <fieldset key={q.id} className="px-1 py-4"><legend className="px-1 font-semibold text-text-primary">{i + 1}. {q.title}</legend><select aria-label={q.title} className="ui-field mt-2 !min-h-10 !rounded-md !px-3 !py-2 !text-sm" disabled={disabled} value={assessment.answers[q.id]?.value || 'unknown'} onChange={e => onChange({ ...assessment, answers: { ...assessment.answers, [q.id]: { evidence: assessment.answers[q.id]?.evidence || '', value: e.target.value as 'yes' | 'no' | 'unknown' } } })}><option value="unknown">待了解</option><option value="yes">是</option><option value="no">否</option></select><textarea aria-label={`${q.title}的事实依据`} className="ui-field mt-2 !min-h-16 !rounded-md !px-3 !py-2 !text-sm" rows={2} disabled={disabled} placeholder={q.evidence} value={assessment.answers[q.id]?.evidence || ''} maxLength={500} onChange={e => onChange({ ...assessment, answers: { ...assessment.answers, [q.id]: { value: assessment.answers[q.id]?.value || 'unknown', evidence: e.target.value } } })}/></fieldset>)}</div>
    <fieldset><legend className="mb-2 font-semibold">补充短板标签</legend><div className="flex flex-wrap gap-x-4 gap-y-2">{Object.entries(gapLabels).map(([id, label]) => <label key={id} className="flex items-center gap-2 text-text-secondary"><input className="accent-accent" type="checkbox" disabled={disabled} checked={assessment.gaps.includes(id as Gap)} onChange={e => onChange({ ...assessment, gaps: e.target.checked ? [...assessment.gaps, id as Gap] : assessment.gaps.filter(g => g !== id) })}/>{label}</label>)}</div><p className="mt-2 text-xs text-text-muted">回答“否”产生的短板也会自动纳入推荐。</p></fieldset>
    <div role="status" className="border-l-2 border-amber bg-amber-dim px-4 py-4"><p className="font-bold text-text-primary">{result.maturity ? `建议阶段：${maturityLabels[result.maturity]}` : '尚不能判定阶段'}</p><p className="mt-1 leading-6 text-text-secondary">{result.reason}</p>{result.gaps.length > 0 && <p className="mt-2 text-[#805c47]">优先补齐：{result.gaps.map(g => gapLabels[g]).join('、')}</p>}{result.maturity && <button type="button" disabled={disabled} className="mt-3 rounded-md bg-accent px-3 py-2 font-semibold text-white transition-colors hover:bg-accent-dim focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/25 disabled:opacity-40" onClick={() => onAdopt(result.maturity!)}>采用阶段建议</button>}</div>
  </div>;
}
