import { assessmentQuestions, assessMaturity, gapLabels, maturityLabels, maturityProfiles, normalizeAssessment, type Maturity, type OperatingAssessment, type Gap } from '../lib/operatingMaturity';

export default function OperatingAssessmentEditor({ value, maturity, disabled, onChange, onAdopt }: { value?: OperatingAssessment; maturity: Maturity; disabled?: boolean; onChange: (value: OperatingAssessment) => void; onAdopt: (maturity: Maturity) => void }) {
  const assessment = normalizeAssessment(value);
  const result = assessMaturity(assessment);
  return <div className="space-y-4 text-sm">
    <p className="text-slate-500">依据过去四周的实际情况识别运营能力，不按企业年限、团队人数或发帖数量划分。以下为客户自述，可结合记录核实。</p>
    <div className="grid gap-3 sm:grid-cols-3">{Object.entries(maturityProfiles).map(([key, profile]) => <div key={key} className={`rounded-xl border p-3 ${key === maturity ? 'border-emerald-400 bg-emerald-50' : 'border-slate-200'}`}><p className="font-bold">{maturityLabels[key as Maturity]}</p><p className="mt-2 text-xs leading-5 text-slate-600">{profile.features}</p></div>)}</div>
    {assessmentQuestions.map((q, i) => <fieldset key={q.id} className="rounded-xl border border-slate-200 p-3"><legend className="px-1 font-semibold">{i + 1}. {q.title}</legend><select aria-label={q.title} className="mt-1 w-full rounded-lg border border-slate-200 bg-white p-2" disabled={disabled} value={assessment.answers[q.id]?.value || 'unknown'} onChange={e => onChange({ ...assessment, answers: { ...assessment.answers, [q.id]: { evidence: assessment.answers[q.id]?.evidence || '', value: e.target.value as 'yes' | 'no' | 'unknown' } } })}><option value="unknown">待了解</option><option value="yes">是</option><option value="no">否</option></select><textarea aria-label={`${q.title}的事实依据`} className="mt-2 w-full rounded-lg border border-slate-200 p-2" rows={2} disabled={disabled} placeholder={q.evidence} value={assessment.answers[q.id]?.evidence || ''} maxLength={500} onChange={e => onChange({ ...assessment, answers: { ...assessment.answers, [q.id]: { value: assessment.answers[q.id]?.value || 'unknown', evidence: e.target.value } } })}/></fieldset>)}
    <fieldset><legend className="mb-2 font-semibold">补充短板标签</legend><div className="flex flex-wrap gap-3">{Object.entries(gapLabels).map(([id, label]) => <label key={id} className="flex items-center gap-1"><input type="checkbox" disabled={disabled} checked={assessment.gaps.includes(id as Gap)} onChange={e => onChange({ ...assessment, gaps: e.target.checked ? [...assessment.gaps, id as Gap] : assessment.gaps.filter(g => g !== id) })}/>{label}</label>)}</div><p className="mt-2 text-xs text-slate-500">回答“否”产生的短板也会自动纳入推荐。</p></fieldset>
    <div role="status" className="rounded-xl bg-slate-50 p-4"><p className="font-bold">{result.maturity ? `建议阶段：${maturityLabels[result.maturity]}` : '尚不能判定阶段'}</p><p className="mt-1 text-slate-600">{result.reason}</p>{result.gaps.length > 0 && <p className="mt-2">优先补齐：{result.gaps.map(g => gapLabels[g]).join('、')}</p>}{result.maturity && <button type="button" disabled={disabled} className="mt-3 rounded-lg bg-emerald-700 px-3 py-2 font-semibold text-white disabled:opacity-40" onClick={() => onAdopt(result.maturity!)}>采用阶段建议</button>}</div>
  </div>;
}
