import { useEffect, useRef, useState } from 'react';
import { CalendarClock, Check, ChevronDown, Edit3, Loader2, Plus, Trash2, X } from 'lucide-react';
import { digitalEmployeeApi } from '../lib/digitalEmployees';
import type { DigitalEmployeeOverview } from '../lib/digitalEmployees';
import { nextReviewWeek, reviewTodoDraft, todoIssues, todoKindLabels, type ReviewTodo, type ReviewTodoBoard } from '../lib/reviewTodos';
import type { ReviewInsight } from '../lib/reviewInsights';
export interface ReviewTodoApi { get: (week: string) => Promise<ReviewTodoBoard>; save: (board: ReviewTodoBoard) => Promise<ReviewTodoBoard>; dispatch: (week: string, revision: number) => Promise<ReviewTodoBoard> }
export const reviewTodoApi: ReviewTodoApi = {
  get: week => digitalEmployeeApi.reviewTodos(week), save: board => digitalEmployeeApi.saveReviewTodos(board), dispatch: (week, revision) => digitalEmployeeApi.dispatchReviewTodos(week, revision),
};
export default function ReviewTodoFloat({ data, incoming, onConsumed, onGoal, api = reviewTodoApi, onBoard }: { data: DigitalEmployeeOverview; incoming: ReviewInsight | null; onConsumed: () => void; onGoal: (goalId: string) => void; api?: ReviewTodoApi; onBoard?: (board: ReviewTodoBoard) => void }) {
  const [open, setOpen] = useState(false), [board, setBoard] = useState<ReviewTodoBoard | null>(null), [editing, setEditing] = useState<ReviewTodo | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [confirmStart, setConfirmStart] = useState(false), [mergeIds, setMergeIds] = useState<string[]>([]);
  const [week, setWeek] = useState(nextReviewWeek());
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const receive = (next: ReviewTodoBoard) => { if (!mounted.current) return; setBoard(next); onBoard?.(next); };
  const load = () => { setBusy(true); setError(''); return api.get(week).then(receive).catch(e => setError(e.message)).finally(() => setBusy(false)); };
  useEffect(() => { void load(); }, [api, week]);
  useEffect(() => {
    if (!incoming || !board) return;
    if (week !== nextReviewWeek()) { setBoard(null); setWeek(nextReviewWeek()); return; }
    const existing = board.items.find(i => i.sourceIds.includes(incoming.id));
    setOpen(true); setEditing(existing?.status === 'assigned' ? null : existing || reviewTodoDraft(incoming)); setMergeIds([]); onConsumed();
  }, [incoming, board]);
  async function save(next: ReviewTodoBoard) {
    setBusy(true); setError('');
    try { const result = await api.save({ ...next, sourceGoalId: next.sourceGoalId || data.goal?.id || '' }); receive(result); return true; }
    catch (e) { setError((e as Error).message); return false; }
    finally { setBusy(false); }
  }
  const pending = board?.items.filter(i => i.status !== 'assigned') || [];
  const targets = data.goals.filter(g => g.startsAt === week && g.status === 'draft');
  const field = (name: 'title' | 'requirements' | 'acceptance' | 'materials' | 'reference', label: string, rows = 3) => <label className="block text-xs font-medium text-text-secondary">{label}{name === 'title' ? <input aria-label={label} value={editing![name]} onChange={e => setEditing({ ...editing!, [name]: e.target.value })} maxLength={180} className="ui-field mt-1.5 !min-h-10 !rounded-md !px-3 !py-2 !text-sm"/> : <textarea aria-label={label} rows={rows} value={editing![name]} onChange={e => setEditing({ ...editing!, [name]: e.target.value })} maxLength={4000} className="ui-field mt-1.5 !rounded-md !px-3 !py-2 !text-sm !leading-6"/>}</label>;
  return <aside aria-label="下周任务待办" className="fixed bottom-24 right-4 z-[45] max-w-[calc(100vw-32px)] sm:right-6">
    {!open ? <button type="button" onClick={() => setOpen(true)} className="flex items-center gap-2 rounded-md border border-border-bright bg-white px-4 py-3 text-sm font-semibold text-accent shadow-[0_8px_24px_rgba(23,61,49,.10)] transition-colors hover:bg-surface-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent/25"><CalendarClock size={18}/>下周待办{board ? ` · ${pending.length}` : ''}{board?.recentWeeks?.some(w=>w.week<nextReviewWeek()&&w.pending>0) && <span className="text-xs text-amber">往期待处理</span>}{board?.autoAssign && <span className="border-l border-border pl-2 text-xs font-normal text-text-secondary">周一 09:00</span>}{error && <span className="text-amber">!</span>}</button> : <div className="flex max-h-[calc(100dvh-128px)] w-[430px] max-w-[calc(100vw-32px)] flex-col overflow-hidden rounded-md border border-border bg-white shadow-[0_16px_40px_rgba(23,61,49,.14)]">
      <header className="flex shrink-0 items-center justify-between border-b border-border px-5 py-4"><h2 className="flex items-center gap-2 font-bold text-text-primary"><CalendarClock size={18} className="text-accent"/>下周待办 <span className="text-xs font-normal text-text-muted">{week} 起</span></h2><button type="button" onClick={() => setOpen(false)} aria-label="收起下周待办" className="rounded-md p-2 text-text-secondary hover:bg-surface-2"><ChevronDown size={18}/></button></header>
      <div className="min-h-0 flex-1 space-y-4 overflow-y-auto p-5">
        {error && <div role="alert" className="border-l-2 border-red bg-surface-2 p-3 text-xs leading-5 text-red">{error}<button disabled={busy} onClick={() => void load()} className="ml-2 font-semibold underline">重新加载</button></div>}
        {!board && !error && <p className="text-sm text-text-muted">正在读取待办…</p>}
        {board && !editing && <label className="block text-xs text-text-secondary">待办周期<select aria-label="待办周期" disabled={busy} value={week} onChange={e=>{setBoard(null);setWeek(e.target.value);setConfirmStart(false);}} className="ml-3 rounded-md border border-border bg-white p-2 text-xs text-text-primary outline-none focus:border-accent">{[...new Set([nextReviewWeek(),week,...(board.recentWeeks||[]).map(w=>w.week)])].sort().reverse().map(w=><option key={w} value={w}>{w===nextReviewWeek()?'下周':w} · {w===board.week?pending.length:board.recentWeeks?.find(v=>v.week===w)?.pending||0} 项待分配</option>)}</select></label>}
        {board?.lastError && <p role="status" className="border-l-2 border-amber bg-amber-dim p-3 text-xs leading-6 text-amber">{board.lastError} · 自动分配已暂停，补充后可再次启动。</p>}
        {editing && board ? <form className="space-y-4" onSubmit={async e => { e.preventDefault(); const issues = todoIssues(editing); if (issues.length) {setError(issues.join('；'));return;} const next = { ...board, items: [...board.items.filter(i => i.id !== editing.id && !mergeIds.includes(i.id)), editing] }; if (await save(next)) {setEditing(null);setMergeIds([]);} }}>
          <div className="flex items-center justify-between"><h3 className="text-sm font-semibold">{mergeIds.length ? '合并并确认执行要求' : '编辑执行要求'}</h3><button type="button" onClick={() => {setEditing(null);setMergeIds([]);}} aria-label="取消待办编辑"><X size={16}/></button></div>
          {field('title', '待办标题')}
          <label className="block text-xs font-medium text-text-secondary">任务类型<select aria-label="任务类型" className="ui-field mt-1.5 !min-h-10 !rounded-md !px-3 !py-2 !text-sm" value={editing.kind} onChange={e => setEditing({...editing, kind:e.target.value as ReviewTodo['kind']})}>{Object.entries(todoKindLabels).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></label>
          {editing.kind === 'video' && <div className="border-l-2 border-accent bg-surface-2 p-3"><label className="text-xs font-medium text-text-primary">覆盖视频数量<input aria-label="覆盖视频数量" type="number" min={1} max={30} value={editing.quantity} onChange={e => setEditing({...editing,quantity:Number(e.target.value)})} className="ml-3 w-16 rounded-md border border-border bg-white p-2 outline-none focus:border-accent"/></label><p className="mt-2 text-xs leading-5 text-text-secondary">占用下周原定视频名额，分配到第 1 镜 0–3 秒，不额外增加视频。</p><label className="mt-3 block text-xs text-text-secondary">指定视频序号（可选，如 1,3,5）<input className="mt-1 w-full rounded-md border border-border bg-white p-2 outline-none focus:border-accent" defaultValue={editing.videoIndexes.map(i=>i+1).join(',')} onChange={e => setEditing({...editing,videoIndexes:e.target.value.split(/[,，]/).filter(s=>s.trim()).map(s=>Number(s.trim())-1)})}/></label></div>}
          {field('requirements', editing.kind === 'video' ? '首镜保留什么、允许改什么' : '具体执行要求')}
          {field('reference', '来源依据 / 参考片段', 2)}
          {field('materials', editing.kind === 'video' ? '首镜需要哪些素材' : '所需资料 / 客户 / 业务对象', 2)}
          {field('acceptance', '完成后如何验收', 2)}
          <p className="text-xs leading-5 text-text-muted">来源：{editing.sourceTitle}</p>
          {pending.some(i=>i.id!==editing.id && i.kind===editing.kind && !mergeIds.includes(i.id)) && <div className="border-y border-border bg-surface-2 p-3"><p className="text-xs font-medium text-text-secondary">已有同类待办，可合并后统一分配</p>{pending.filter(i=>i.id!==editing.id && i.kind===editing.kind && !mergeIds.includes(i.id)).map(i=><button key={i.id} type="button" className="mt-2 block text-left text-xs text-accent hover:text-accent-dim" onClick={()=>{setMergeIds([...mergeIds,i.id]);setEditing({...editing,sourceIds:[...new Set([...editing.sourceIds,...i.sourceIds])],requirements:editing.requirements+'\n'+i.requirements,acceptance:editing.acceptance+'\n'+i.acceptance,materials:editing.materials+'\n'+i.materials,reference:editing.reference+'\n'+i.reference});}}>合并：{i.title}</button>)}</div>}
          <button disabled={busy} type="submit" className="w-full rounded-md bg-accent py-2.5 text-sm font-semibold text-white hover:bg-accent-dim disabled:opacity-50">{busy ? '正在保存…' : '保存到下周待办'}</button>
        </form> : board && <>
          <label className="block text-xs text-text-secondary">归入下周目标<select aria-label="下周目标" value={board.targetGoalId} disabled={busy || board.items.some(i=>i.status==='assigned')} onChange={e => void save({...board,targetGoalId:e.target.value})} className="ui-field mt-2 !min-h-10 !rounded-md !px-3 !py-2 !text-sm"><option value="">沿用下周草稿；没有则按本轮安排建立</option>{targets.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}{board.targetGoalId && !targets.some(g=>g.id===board.targetGoalId) && <option value={board.targetGoalId}>已关联下周目标</option>}</select></label>
          {board.targetGoalId && <button type="button" onClick={()=>onGoal(board.targetGoalId)} className="text-xs font-medium text-accent hover:text-accent-dim">查看并完善下周目标</button>}
          {!board.items.length && <p className="border-y border-border py-7 text-center text-sm leading-7 text-text-muted">还没有下周待办<br/>从洞察卡片加入，或手动记录执行要求。</p>}
          {board.items.map(item=><article key={item.id} className="rounded-md border border-border p-3.5"><div className="flex justify-between gap-3"><span className="text-[11px] text-text-muted">{todoKindLabels[item.kind]}</span><span className={`text-[11px] ${item.status==='assigned'?'text-accent':item.status==='needs_input'?'text-amber':'text-text-secondary'}`}>{item.status==='assigned'?'已分配':item.status==='needs_input'?'需补充':'待分配'}</span></div><h3 className="mt-2 text-sm font-semibold leading-6 text-text-primary">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-6 text-text-secondary">{item.kind==='video'?`${item.quantity} 条视频 · 第1镜0–3秒 · `:''}{item.requirements}</p><div className="mt-3 flex items-center justify-between gap-3"><span className="max-w-[230px] truncate text-[10px] text-text-muted" title={item.sourceTitle}>来源：{item.sourceTitle}</span>{item.status==='assigned'?<button onClick={()=>onGoal(item.assignedGoalId!)} className="shrink-0 text-xs text-accent hover:text-accent-dim">查看目标</button>:<span className="flex gap-3 text-text-secondary"><button aria-label={`编辑 ${item.title}`} disabled={busy} onClick={()=>setEditing(item)}><Edit3 size={14}/></button><button aria-label={`删除 ${item.title}`} disabled={busy} onClick={()=>void save({...board,items:board.items.filter(i=>i.id!==item.id)})}><Trash2 size={14}/></button></span>}</div></article>)}
          <button type="button" disabled={busy || !data.goal} onClick={()=>setEditing({id:crypto.randomUUID(),sourceIds:[],sourceTitle:'手动记录',title:'',kind:'operation',requirements:'',acceptance:'',materials:'',reference:'',quantity:1,videoIndexes:[],status:'pending',reason:''})} className="flex items-center gap-2 text-xs font-medium text-accent hover:text-accent-dim disabled:opacity-40"><Plus size={14}/>记录一条待办</button>
        </>}
      </div>
      {board && !editing && <footer className="shrink-0 space-y-3 border-t border-border bg-surface-2 p-4"><label className="flex items-center justify-between gap-3 text-xs font-medium text-text-primary"><span>{week===nextReviewWeek()?'下周一 09:00 自动分配':`${week} 09:00 自动分配`}<span className="mt-1 block text-[10px] font-normal text-text-muted">北京时间 · 离开页面后仍有效</span></span><input aria-label="下周一自动分配" type="checkbox" checked={board.autoAssign} disabled={busy || !pending.length} onChange={e=>void save({...board,autoAssign:e.target.checked})} className="h-4 w-4 accent-accent"/></label><p className="text-[11px] leading-5 text-text-secondary">分配后启动下周目标的准备任务；发布、发送与知识入库仍需审核。当前目标未结束时将提示处理。</p>{confirmStart ? <div className="border-l-2 border-amber bg-white p-3"><p className="text-xs leading-6 text-text-primary">现在分配 {pending.length} 项，并启动关联下周目标中的任务？</p><div className="mt-2 flex justify-end gap-3"><button onClick={()=>setConfirmStart(false)} className="text-xs text-text-secondary">取消</button><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{receive(await api.dispatch(board.week,board.revision));setConfirmStart(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}} className="rounded-md bg-accent px-3 py-2 text-xs text-white hover:bg-accent-dim">确认启动</button></div></div> : <button disabled={busy || !pending.length} onClick={()=>setConfirmStart(true)} className="flex w-full items-center justify-center gap-2 rounded-md bg-accent py-2.5 text-sm font-semibold text-white hover:bg-accent-dim disabled:opacity-40">{busy?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>}立即分配并启动</button>}</footer>}
    </div>}
  </aside>;
}
