import { VIDEO_LANGUAGES } from '../lib/videoLanguages';
import { useEffect, useState } from 'react';
import { authHeader } from '../lib/auth';
import type { DigitalEmployeeConfig, PublishingPlatform } from '../lib/digitalEmployees';
import { normalizeVideoPlan, VIDEO_ROUTES, VIDEO_PRESENTATIONS, usesDigitalPresenter, defaultMixedScenes, videoPlanErrors, type VideoCreationPlan } from '../lib/videoCreationPlan';

type Options = { products: Array<{ id: string; name: string; materialIds: string[] }>; assets: Array<{ id: string; name: string }>; references: Array<{ id: string; name: string }> };
const field = 'w-full rounded-lg border border-slate-200 bg-white p-2 text-sm';
export default function VideoPlanEditor({ plans, config, platforms, onChange }: { plans: VideoCreationPlan[]; config: DigitalEmployeeConfig; platforms: PublishingPlatform[]; onChange: (plans: VideoCreationPlan[]) => void }) {
  const [options, setOptions] = useState<Options>({ products: [], assets: [], references: [] });
  const [avatars, setAvatars] = useState<Array<{ id: string; name: string; gender?: string }>>([]);
  const [notice, setNotice] = useState('');
  const [languages, setLanguages] = useState<Array<{code: string; label: string; available: boolean}>>([]);
  useEffect(() => { let live = true; fetch('/api/overseas/studio/tts/capabilities', { headers: authHeader() }).then(response => { if (!response.ok) throw Error('配音能力加载失败'); return response.json(); }).then(data => { if (live) setLanguages(data.languages || []); }).catch(error => { if (live) setNotice(error.message); }); return () => { live = false; }; }, []);
  useEffect(() => { let live = true; fetch('/api/overseas/digital-employees/planning-options', { headers: authHeader() }).then(async response => { if (!response.ok) throw Error('制作资料加载失败，请刷新后重试'); return response.json(); }).then(value => { if (live) setOptions(value); }).catch(error => { if (live) setNotice(error.message); }); return () => { live = false; }; }, []);
  const needAvatar = plans.some(usesDigitalPresenter);
  useEffect(() => { if (!needAvatar) return; let live = true; fetch('/api/overseas/studio/digital-human/avatars', { headers: authHeader() }).then(async response => { const value = await response.json(); if (!response.ok) throw Error(value.error || 'HeyGen 人物加载失败'); return value; }).then(value => { if (live) setAvatars(value.items || []); }).catch(error => { if (live) setNotice(error.message); }); return () => { live = false; }; }, [needAvatar]);
  const change = (index: number, patch: Partial<VideoCreationPlan>) => onChange(plans.map((plan, i) => i === index ? normalizeVideoPlan({ ...plan, ...patch }) : plan));
  return <section className="space-y-4 rounded-2xl border border-blue-100 bg-blue-50/40 p-4">
    <div><h3 className="font-bold">逐条确认视频制作计划</h3><p className="mt-1 text-xs text-slate-600">脚本来源与成片方式分别选择；批准后按此计划生成，缺少资料时暂停提示。</p></div>
    {notice && <p role="alert" className="text-sm text-amber-700">{notice}</p>}
    {plans.map((plan, index) => <div key={index} className="space-y-3 rounded-xl border bg-white p-4">
      <div className="flex justify-between"><b>第 {index + 1} 条</b>{plans.length > 1 && <button type="button" onClick={() => onChange(plans.filter((_, i) => i !== index))}>移除此条</button>}</div>
      <div className="grid gap-3 md:grid-cols-2">
        <label>脚本来源<select className={field} value={plan.route} onChange={event => change(index, { route: event.target.value as VideoCreationPlan['route'], materialIds: [], referenceId: '' })}>{Object.entries(VIDEO_ROUTES).filter(([route]) => config.enabledWorkflows.includes(({ clone: 'viral_clone', material: 'material_content', product: 'product_content' } as const)[route as keyof typeof VIDEO_ROUTES])).map(([route, label]) => <option key={route} value={route}>{label}</option>)}</select></label>
        <label>产品<select className={field} value={plan.productName} onChange={event => change(index, { productName: event.target.value, materialIds: [], scenePlan: plan.scenePlan?.map(scene => ({ ...scene, materialId: '' })) })}><option value="">请选择产品</option>{options.products.map(product => <option key={product.id} value={product.name}>{product.name}</option>)}</select></label>
        <label className="md:col-span-2">本条主题 / 买家问题<input className={field} value={plan.theme} onChange={event => change(index, { theme: event.target.value })} /></label>
        <label>语言<select className={field} value={plan.language} onChange={event => change(index, { language: event.target.value })}>{Object.entries(VIDEO_LANGUAGES).map(([id, name]) => <option key={id} value={id} disabled={languages.some(item => item.code === id && !item.available)}>{name}{languages.some(item => item.code === id && !item.available) ? '（需配置配音服务）' : ''}</option>)}</select></label>
        <label>目标时长（秒）<input className={field} type="number" min={10} max={180} value={plan.duration} onChange={event => change(index, { duration: Number(event.target.value) })} /></label>
        <label>制作平台<select className={field} value={plan.platform} onChange={event => change(index, { platform: event.target.value as PublishingPlatform })}>{platforms.map(platform => <option key={platform}>{platform}</option>)}</select>{!platforms.includes(plan.platform) && <span className="text-xs text-amber-700">请重新选择本周范围内的平台</span>}</label>
        <label>成片方式<select className={field} value={plan.presenter} onChange={event => change(index, { presenter: event.target.value as VideoCreationPlan['presenter'], scenePlan: event.target.value === 'heygen' ? plan.scenePlan || defaultMixedScenes() : undefined })}>{Object.entries(VIDEO_PRESENTATIONS).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>
        <p className="md:col-span-2 text-xs text-slate-500">{plan.presenter === 'avatar' ? '全片数字人出镜，配完整口播与字幕；从素材生成脚本时仍需选择参考素材。' : plan.presenter === 'heygen' ? '逐镜指定数字人或产品素材，沿用同一条配音和字幕；缺素材会暂停。' : '画面全部使用已授权素材，可配音及字幕，不调用数字人生成。'}</p>
        {plan.route === 'clone' && <label className="md:col-span-2">爆款参考<select className={field} value={plan.referenceId} onChange={event => change(index, { referenceId: event.target.value })}><option value="">请选择已分析的参考视频</option>{options.references.map(reference => <option key={reference.id} value={reference.id}>{reference.name}</option>)}</select></label>}
        <fieldset className="md:col-span-2"><legend>{plan.presenter === 'avatar' ? '脚本参考素材' : '本条画面素材'}{plan.presenter !== 'avatar' && plan.route === 'product' ? '（可先生成脚本，缺画面时提示补充）' : ''}</legend>{(options.products.find(product => product.name === plan.productName)?.materialIds || []).map(id => <label key={id} className="mr-3 inline-flex items-center gap-1 text-xs"><input type="checkbox" checked={plan.materialIds.includes(id)} onChange={event => change(index, { materialIds: event.target.checked ? [...plan.materialIds, id] : plan.materialIds.filter(item => item !== id) })} />{options.assets.find(asset => asset.id === id)?.name || '已关联产品素材'}</label>)}{!options.products.find(product => product.name === plan.productName)?.materialIds.length && <p className="text-xs text-amber-700">{plan.presenter === 'avatar' && plan.route !== 'material' ? '此模式无需画面素材。' : '此产品暂无画面素材，请补充并选择所需素材。'}</p>}</fieldset>
        {usesDigitalPresenter(plan) && <><label>HeyGen 人物<select className={field} value={plan.heygenAvatarId} onChange={event => change(index, { heygenAvatarId: event.target.value, avatarConsent: false, voice: avatars.find(item => item.id === event.target.value)?.gender === 'male' ? 'v2' : 'v1' })}><option value="">选择 HeyGen 人物</option>{avatars.map(avatar => <option key={avatar.id} value={avatar.id}>{avatar.name}</option>)}</select></label><label>口播声音<select className={field} value={plan.voice} onChange={event => change(index, { voice: event.target.value })}><option value="v1">女声 · Cherry</option><option value="v2">男声 · Ethan</option></select></label><label className="md:col-span-2 text-sm"><input type="checkbox" checked={plan.avatarConsent} onChange={event => change(index, { avatarConsent: event.target.checked })} /> 我确认可使用所选人物，将本条口播音频提交 HeyGen 生成视频</label></>}
        {plan.presenter === 'heygen' && <fieldset className="md:col-span-2 space-y-2"><legend className="text-sm font-bold">分镜画面安排</legend><p className="text-xs text-slate-500">默认数字人开场和收尾，可逐镜修改；生成脚本按此镜头数量与来源编排。</p>{(plan.scenePlan || defaultMixedScenes()).map((scene, sceneIndex) => <div key={sceneIndex} className="flex flex-wrap items-center gap-2"><span className="text-xs">第 {sceneIndex + 1} 镜</span><select aria-label={`第 ${index + 1} 条第 ${sceneIndex + 1} 镜画面来源`} className="rounded border p-2 text-xs" value={scene.source} onChange={event => change(index, { scenePlan: (plan.scenePlan || defaultMixedScenes()).map((item, i) => i === sceneIndex ? { source: event.target.value as 'avatar' | 'material', materialId: '' } : item) })}><option value="avatar">数字人</option><option value="material">素材</option></select>{scene.source === 'material' && <select aria-label={`第 ${index + 1} 条第 ${sceneIndex + 1} 镜素材`} className="min-w-0 flex-1 rounded border p-2 text-xs" value={scene.materialId} onChange={event => change(index, { scenePlan: (plan.scenePlan || defaultMixedScenes()).map((item, i) => i === sceneIndex ? { ...item, materialId: event.target.value } : item) })}><option value="">从已选素材按内容匹配</option>{plan.materialIds.map(id => <option key={id} value={id}>{options.assets.find(asset => asset.id === id)?.name || id}</option>)}</select>}<button type="button" disabled={(plan.scenePlan || defaultMixedScenes()).length <= 3} onClick={() => change(index, { scenePlan: (plan.scenePlan || defaultMixedScenes()).filter((_, i) => i !== sceneIndex) })} className="text-xs disabled:opacity-30">移除此镜</button></div>)}<button type="button" className="rounded border p-2 text-xs" disabled={(plan.scenePlan || defaultMixedScenes()).length >= 8} onClick={() => change(index, { scenePlan: [...(plan.scenePlan || defaultMixedScenes()), { source: 'material', materialId: '' }] })}>添加分镜</button></fieldset>}
      </div>
      {plan.reviewRequirements?.map(r => <div key={r.todoId} className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs leading-6"><p className="font-bold text-emerald-800">来自复盘 · 第1镜 0–3 秒</p><p>保留要求：{r.requirements}</p><p>素材要求：{r.materials}</p><p>验收条件：{r.acceptance}</p><p className="text-slate-500">参考：{r.reference}</p></div>)}
      {videoPlanErrors(plan).length > 0 && <p className="text-xs text-amber-700">{videoPlanErrors(plan).join('；')}</p>}
    </div>)}
    <button type="button" className="rounded-lg border bg-white px-3 py-2 text-sm" disabled={plans.length >= 30} onClick={() => onChange([...plans, normalizeVideoPlan({ ...config.videoDefaults, route: plans[0]?.route || 'product', platform: platforms[0], productName: options.products[0]?.name })])}>添加视频计划</button>
  </section>;
}
