const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
function load(file,bindings={}) {const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,file),'utf8'),{module,Date,...bindings});return module.exports;}
const model=load('lib/workbench.js');
function page(api={},wx={}) {let definition;load('pages/workbench/index.js',{Page:p=>definition=p,require:id=>id.endsWith('workbench')?model:id.endsWith('starter')?load('lib/starter.js',{require:()=>model}):api,wx:{getStorageSync:()=>[],...wx},setInterval:()=>1,clearInterval:()=>{}});return {...definition,data:structuredClone(definition.data),setData(patch){for(const [key,value]of Object.entries(patch)){const keys=key.split('.');let target=this.data;for(const k of keys.slice(0,-1))target=target[k];target[keys.at(-1)]=value;}}};}
test('old-account task result cannot populate same-ID new-account detail',async()=>{let resolve;const p=page({request:()=>new Promise(r=>resolve=r)});p.data.detail={id:'same'};const pending=p.loadTaskEvents({id:'same',run_id:'run'});p.session({user:{id:'new'}});p.data.detail={id:'same'};resolve({task:{output:{secret:'old account'}},events:[]});await pending;assert.equal(p.data.detail.result,undefined);});
test('account change cancels approval modal before it can submit',async()=>{let options;let calls=0;const p=page({request:async()=>calls++},{showModal:r=>options=r});p.data.detail={approval:{id:'a'}};p.decideApproval({currentTarget:{dataset:{decision:'approved'}}});p.session({user:{id:'new'}});await options.success({confirm:true});assert.equal(calls,0);});
test('sign out invalidates pending assistant response and status cleanup',async()=>{let resolve;const p=page({chat:()=>new Promise(r=>resolve=r),clearToken:()=>{}});p.data.loggedIn=true;p.data.input='进度';const pending=p.send();p.signOut();resolve('secret');await pending;assert.equal(p.data.loggedIn,false);assert.equal(p.data.messages.length,0);assert.equal(p.data.sending,false);});
test('offline refresh preserves last successful data and explains staleness',async()=>{let calls=0;const p=page({request:async()=>calls++});p.data.loggedIn=true;p.data.offline=true;p.data.tasks=[{id:'previous'}];await p.refresh();assert.equal(calls,0);assert.equal(p.data.tasks[0].id,'previous');assert.match(p.data.error,/上次同步/);});
test('task detail error stays local and can retry without closing the task',async()=>{const p=page({request:async()=>{throw Error('同步失败')}});p.data.detail={id:'t',run_id:'r'};await p.loadTaskEvents(p.data.detail);assert.equal(p.data.detail.loading,false);assert.equal(p.data.detail.loadError,'同步失败');assert.equal(p.data.error,'');});
test('read-only assistant questions never submit backend work commands',async()=>{let commands=0;const p=page({command:async()=>commands++});p.workspaceKind='starter';p.data.starterWorkspace={generatedAt:'2026-10-10',run:{cycleLabel:'当前周期'},today:{inProgress:[{id:'t',what:'制作视频',status:'running'}]}};p.data.input='这周完成多少任务';await p.send();assert.equal(commands,0);assert.match(p.data.messages[1].content,/当前周期/);assert.match(p.data.messages[1].content,/周统计/);});
test('working instruction requires confirmation and only then submits one command',async()=>{let modal;let commands=0;const p=page({command:async()=>{commands++;return {message:'已接收'}}},{showModal:r=>modal=r,setStorageSync:()=>{}});p.workspaceKind='starter';p.data.input='推进视频制作';p.submitInstruction();assert.equal(commands,0);assert.match(modal.content,/启动新周期/);await modal.success({confirm:true});assert.equal(commands,1);});
