const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
function load(file,bindings={}) {const module={exports:{}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,file),'utf8'),{module,Date,...bindings});return module.exports;}
const model=load('lib/workbench.js');
function page(api={},wx={}) {if(!api.assistantContract){const original=api.request;api={...api,request:(route,method,body)=>route.includes('mobile-workbench/assistant/')?assistantApi().request(route,method,body):original?original(route,method,body):Promise.resolve({})};}let definition;load('pages/workbench/index.js',{Page:p=>definition=p,require:id=>id.endsWith('assistant')?load('lib/assistant.js',{setTimeout:()=>1,clearTimeout:()=>{}}):id.endsWith('agentSchedule')?load('lib/agentSchedule.js',{require:()=>model}):id.endsWith('workbench')?model:id.endsWith('starter')?load('lib/starter.js',{require:()=>model}):api,wx:{getStorageSync:()=>null,setStorageSync:()=>{},...wx},setInterval:()=>1,clearInterval:()=>{}});return {...definition,data:structuredClone(definition.data),setData(patch){for(const [key,value]of Object.entries(patch)){const keys=key.split('.');let target=this.data;for(const k of keys.slice(0,-1))target=target[k];target[keys.at(-1)]=value;}}};}
test('old-account task result cannot populate same-ID new-account detail',async()=>{let resolve;const p=page({request:()=>new Promise(r=>resolve=r)});p.data.detail={id:'same'};const pending=p.loadTaskEvents({id:'same',run_id:'run'});p.session({user:{id:'new'}});p.data.detail={id:'same'};resolve({task:{output:{secret:'old account'}},events:[]});await pending;assert.equal(p.data.detail.result,undefined);});
test('account change cancels approval modal before it can submit',async()=>{let options;let calls=0;const p=page({request:async()=>calls++},{showModal:r=>options=r});p.data.detail={approval:{id:'a'}};p.decideApproval({currentTarget:{dataset:{decision:'approved'}}});p.session({user:{id:'new'}});await options.success({confirm:true});assert.equal(calls,0);});
test('offline refresh preserves last successful data and explains staleness',async()=>{let calls=0;const p=page({request:async()=>calls++});p.data.loggedIn=true;p.data.offline=true;p.data.tasks=[{id:'previous'}];await p.refresh();assert.equal(calls,0);assert.equal(p.data.tasks[0].id,'previous');assert.match(p.data.error,/上次同步/);});
test('task detail error stays local and can retry without closing the task',async()=>{const p=page({request:async()=>{throw Error('同步失败')}});p.data.detail={id:'t',run_id:'r'};await p.loadTaskEvents(p.data.detail);assert.equal(p.data.detail.loading,false);assert.equal(p.data.detail.loadError,'同步失败');assert.equal(p.data.error,'');});
test('work home keeps the weekly metrics and only the Agent schedule below them',()=>{const markup=fs.readFileSync(path.join(__dirname,'pages/workbench/index.wxml'),'utf8');const work=markup.slice(markup.indexOf("<view wx:if=\"{{tab === 'work'}}\">"),markup.indexOf("<view wx:elif=\"{{tab === 'todo'}}\">"));assert.match(work,/工作播报/);assert.match(work,/class=\"metrics panel\"/);assert.match(work,/Agent 排期/);assert.doesNotMatch(work,/Agent 正在做什么|内容排期|本周任务推进|class=\"days\"|class=\"stage-strip\"/);});

function assistantApi(override=()=>undefined) {
  return {assistantContract:true,clearToken:()=>{},request:async(path,method,body)=>{
    const result=await override(path,method,body);if(result!==undefined)return result;
    if(path.endsWith('/context'))return {quickQuestions:[{topic:'weekly',label:'本周进度'}]};
    if(path.endsWith('/sessions'))return {sessions:[{id:'session-1'}]};
    if(path.endsWith('/messages'))return {messages:[{id:'a',role:'assistant',text:'本周数据已核实'}]};
    if(path.endsWith('/query'))return {text:'本周数据已核实',evidence:[{source:'tasks',generatedAt:'2026-10-10T10:00:00Z'}],links:[{type:'matter',id:'task:1'}],actions:[{label:'重试',action:{kind:'retry_task',targetId:'1'}}]};
    if(path.endsWith('/preview'))return {previewId:'preview-1',target:{title:'重试任务'},requiresConfirmation:true,confirmation:{body:{kind:'retry_task',targetId:'1',expectedVersion:'v1',payload:{}}}};
    if(path.endsWith('/actions'))return {receipt:{id:'receipt-1',status:'accepted'}};
    if(path.includes('/actions/'))return {receipt:{id:'receipt-1',status:'succeeded'}};
    if(path.endsWith('/commands'))return {ok:true};
    return {};
  }};
}
async function ready(p){p.scope='tenant:user';p.initializeAssistant();await p.assistantController.restore(p.scope);}
test('sign out invalidates pending assistant response and status cleanup',async()=>{let resolve;const p=page(assistantApi(path=>path.endsWith('/query')?new Promise(r=>resolve=r):undefined));await ready(p);p.data.loggedIn=true;p.data.input='进度';const pending=p.send();await new Promise(r=>setImmediate(r));p.signOut();resolve({text:'secret'});await pending;assert.equal(p.data.loggedIn,false);assert.equal(p.data.messages.length,0);assert.equal(p.data.sending,false);});
test('read-only assistant query uses server session without client business prompt',async()=>{const calls=[];const p=page(assistantApi((path,method,body)=>{calls.push({path,body});}));await ready(p);p.data.input='这周完成多少任务';await p.send();assert.equal(calls.some(c=>c.path.endsWith('/actions')),false);assert.equal(p.data.messages[0].content,'本周数据已核实');const query=calls.find(c=>c.path.endsWith('/query'));assert.equal(query.body.sessionId,'session-1');assert.equal(query.body.input,'这周完成多少任务');assert.equal(query.body.messages,undefined);});
test('execution candidate requires server preview then explicit confirmation',async()=>{let commands=0;const p=page(assistantApi(path=>{if(path.endsWith('/actions'))commands++;}));await ready(p);p.refresh=async()=>{};p.data.input='重试失败任务';await p.send();assert.equal(commands,0);await p.previewAssistantAction({currentTarget:{dataset:{index:0}}});assert.equal(p.data.assistantPreview.previewId,'preview-1');assert.equal(commands,0);await p.confirmAssistantAction();assert.equal(commands,1);assert.equal(p.data.assistantReceipts[0].statusLabel,'操作已完成');});
test('assistant evidence link opens matching actionable matter',()=>{const p=page();const matter={id:'task:1',title:'修复授权',type:'task',task:{id:'1'}};p.data.matters=[matter];p.data.assistantLinks=[{type:'matter',id:'task:1'}];p.assistantAction({currentTarget:{dataset:{index:0}}});assert.equal(p.data.tab,'todo');assert.equal(p.data.activeMatter.id,'task:1');assert.equal(p.data.detail.id,'1');});
test('assistant session restore failure preserves logged-in work home',async()=>{const p=page(assistantApi(path=>{if(path.endsWith('/context'))throw Error('助手同步失败');}));p.data.metrics=[{key:'tasks',value:8}];p.data.loggedIn=true;await ready(p);assert.equal(p.data.loggedIn,true);assert.equal(p.data.tab,'work');assert.equal(p.data.metrics[0].value,8);assert.match(p.data.error,/助手同步失败/);assert.equal(p.data.assistantLoading,false);});
