import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,copyFile,writeFile,rm} from 'node:fs/promises';import {tmpdir,homedir} from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
test('PocketBase 0.39.5 isolated rehearsal rejects old initial state then accepts forward schema',async t=>{
 const binary=process.env.PB_REHEARSAL_BIN??path.join(homedir(),'.local/share/lingshu/pocketbase/pocketbase');const version=spawnSync(binary,['--version'],{encoding:'utf8'});assert.equal(version.status,0,'actual PocketBase binary is required');assert.match(version.stdout,/0\.39\.5/);
 const dir=await mkdtemp(path.join(tmpdir(),'pb-content-zero-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const migrations=path.join(dir,'migrations');await import('node:fs/promises').then(fs=>fs.mkdir(migrations));
 await copyFile('pb_migrations/1791072008_create_content_execution_queue.js',path.join(migrations,'1791072008_schema.js'));
 const probe=(expect:string)=>`migrate(app=>{const now='2026-10-10T00:00:00Z'; const cases={content_execution_jobs:{tenant_id:'t',job_key:'${expect}',task_id:'${expect}',run_id:'run',user_id:'owner',account_id:'account',task_type:'video',status:'queued',attempt:0,reconciliation_attempt:0,provider_state:'none',provider_receipts:[],created_at:now,updated_at:now},content_execution_limits:{tenant_id:'t',limit_scope:'tenant',scope_key:'${expect}',max_running:0,updated_by:'owner',created_at:now,updated_at:now},studio_social_presenter_jobs:{tenant_id:'t',task_id:'task',shot_id:'s',request_id:'${expect}',status:'queued',provider:'controlled-no-network',presenter_asset_id:'p',authorization_ref:'a',consent_ref:'c',visual_control:{},created_at:now,updated_at:now}};for(const name of Object.keys(cases)){const r=new Record(app.findCollectionByNameOrId(name));for(const k of Object.keys(cases[name]))r.set(k,cases[name][k]);let accepted=false;try{app.save(r);accepted=true;}catch(e){console.log('REJECTION '+name+' '+e);}if(accepted!==${expect==='accepted'})throw Error('unexpected '+name+' ${expect}');console.log('PROOF ${expect} '+name);}},app=>{});`;
 await writeFile(path.join(migrations,'1791072049_before.js'),probe('rejected'));await copyFile('pb_migrations/1791072050_allow_initial_content_queue_zero_state.js',path.join(migrations,'1791072050_forward.js'));await writeFile(path.join(migrations,'1791072051_after.js'),probe('accepted'));
 const run=spawnSync(binary,['migrate','up',`--dir=${path.join(dir,'fresh-data')}`,`--migrationsDir=${migrations}`],{encoding:'utf8'});assert.equal(run.status,0,run.stdout+run.stderr);for(const name of ['content_execution_jobs','content_execution_limits','studio_social_presenter_jobs']){assert.match(run.stdout+run.stderr,new RegExp(`PROOF rejected ${name}`));assert.match(run.stdout+run.stderr,new RegExp(`PROOF accepted ${name}`));}
});
