import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=name=>readFileSync(path.join(root,name),'utf8');
// Run only the original pure configuration function, in an isolated VM env.
// No application imports, credentials, subprocess, network or live service.
function pureFunction(file,name,env){const source=read(file);const start=source.indexOf(`function ${name}(`);assert.ok(start>=0);const open=source.indexOf('{',start);let depth=1,end=open+1;for(;depth&&end<source.length;end++){if(source[end]==='{')depth++;if(source[end]==='}')depth--;}const fn=source.slice(start,end).replace(/\): (?:boolean|number)\s*\{/,'){');return vm.runInNewContext(`${fn}; ${name}()`,{process:{env:{...env}}});}
test('production rejects every contradictory local fallback flag combination',()=>{for(const enable of [undefined,'true','false','TRUE','1'])for(const disable of [undefined,'true','false','FALSE','0'])assert.equal(pureFunction('server/lib/localFallbackPolicy.ts','localFallbacksEnabled',{NODE_ENV:'production',ENABLE_LOCAL_DEV_FALLBACK:enable,DISABLE_LOCAL_AUTH_FALLBACK:disable}),false);});
test('non-production defaults fail closed and only exact legacy/explicit opt-in enables fallback',()=>{for(const env of ['development','test',undefined]){assert.equal(pureFunction('server/lib/localFallbackPolicy.ts','localFallbacksEnabled',{NODE_ENV:env}),false);assert.equal(pureFunction('server/lib/localFallbackPolicy.ts','localFallbacksEnabled',{NODE_ENV:env,ENABLE_LOCAL_DEV_FALLBACK:'true'}),true);assert.equal(pureFunction('server/lib/localFallbackPolicy.ts','localFallbacksEnabled',{NODE_ENV:env,DISABLE_LOCAL_AUTH_FALLBACK:'false'}),true);assert.equal(pureFunction('server/lib/localFallbackPolicy.ts','localFallbacksEnabled',{NODE_ENV:env,ENABLE_LOCAL_DEV_FALLBACK:'TRUE',DISABLE_LOCAL_AUTH_FALLBACK:'FALSE'}),false);}});
test('original cache and timeout parsers preserve explicit bounds and zero-auth-cache option',()=>{for(const [raw,expected] of [[undefined,5000],['0',0],['-1',0],['99999',30000],['invalid',5000]])assert.equal(pureFunction('server/storage/pb.ts','authCacheTtlMs',{PB_AUTH_CACHE_TTL_MS:raw}),expected);for(const [raw,expected]of [[undefined,10000],['0',500],['99999',60000],['invalid',10000]])assert.equal(pureFunction('server/storage/pb.ts','pbRequestTimeoutMs',{PB_REQUEST_TIMEOUT_MS:raw}),expected);for(const [raw,expected]of [[undefined,2000],['0',250],['99999',10000],['invalid',2000]])assert.equal(pureFunction('server/runtime/readiness.ts','readinessCacheTtlMs',{READINESS_CACHE_TTL_MS:raw}),expected);});
test('actual registered probe handlers distinguish liveness 200 from degraded readiness 503',async()=>{const source=read('server/index.ts');const first=source.indexOf("app.get('/api/overseas/health'");const end=source.indexOf("app.use('/api',",first);assert.ok(first>0&&end>first);const handlers=new Map();const run=issues=>{handlers.clear();vm.runInNewContext(source.slice(first,end),{app:{get:(route,handler)=>handlers.set(route,handler)},startupReadinessIssues:issues,PORT:8788,processRole:'web',runtimeBuildInfo:()=>({commit:'offline-fixture'}),isDemoMode:()=>false,demoLimits:()=>({}),runtimeCapabilities:()=>({}),readinessProbe:async()=>({status:issues.length?'degraded':'ready',issues})});};const response=()=>({code:200,headers:{},body:null,status(code){this.code=code;return this;},setHeader(name,value){this.headers[name]=value;},json(body){this.body=body;return this;}});run(['isolated_fixture_issue']);let res=response();await handlers.get('/api/overseas/health')({},res);assert.equal(res.code,200);assert.equal(res.body.status,'degraded');res=response();await handlers.get('/api/overseas/ready')({},res);assert.equal(res.code,503);assert.equal(res.headers['Cache-Control'],'no-store');run([]);res=response();await handlers.get('/api/overseas/ready')({},res);assert.equal(res.code,200);assert.equal(res.body.status,'ready');});
test('checked-in production defaults and canonical update keep auth/ready and volume boundaries',()=>{const compose=read('docker-compose.yml'),env=read('deploy/make-production-env.sh'),update=read('deploy/update.sh');assert.match(compose,/NODE_ENV: production/);assert.match(compose,/api\/overseas\/ready/);assert.match(env,/DISABLE_LOCAL_AUTH_FALLBACK=true/);assert.match(env,/ENABLE_LOCAL_DEV_FALLBACK=false/);assert.match(env,/RUNTIME_SCHEMA_REPAIR_ENABLED=false/);assert.match(update,/--require-existing/);assert.match(update,/stop caddy app worker/);assert.match(update,/api\/overseas\/ready/);assert.doesNotMatch(update,/docker compose.*down.*-v|migrate down/);});
