import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {runReadonly,evaluateReadOnlyCatalog,READONLY_SQL,READONLY_EXPECTED_COLUMNS as columns,READONLY_EXPECTED_INDEXES as indexes,canonicalSQL,parseManifest} from './infra-prep-postgres-readonly.mjs';
const fixture=()=>({readOnly:'on',isolation:'repeatable read',serverVersion:'160002',tls:{ssl:true,version:'TLSv1.3'},tables:Object.entries(columns).map(([name,cols])=>({table:name,kind:'r',columns:Object.entries(cols).map(([name,[type,notNull]])=>({name,type,notNull})),constraints:[{type:'p',validated:true,definition:name==='lingshu_records'?'PRIMARY KEY(collection,id)':name==='lingshu_migration_runs'?'PRIMARY KEY(id)':'PRIMARY KEY(run_id,collection)'},...(name==='lingshu_records'?[{type:'c',validated:true,definition:"CHECK (jsonb_typeof(data) = 'object'::text)"},{type:'c',validated:true,definition:"CHECK (collection ~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$'::text)"}]:name==='lingshu_migration_runs'?[{type:'c',validated:true,definition:"CHECK ((status = ANY (ARRAY['planning'::text, 'running'::text, 'verifying'::text, 'completed'::text, 'failed'::text])))"}]:[{type:'f',validated:true,definition:'FOREIGN KEY (run_id) REFERENCES lingshu_migration_runs(id) ON DELETE CASCADE'}])]})),indexes:Object.entries(indexes).map(([name,i])=>({name,unique:true,valid:true,ready:true,immediate:true,keys:i.fields.length,expressions:i.fields.map(f=>`(data ->> '${f}'::text)`).join(', '),predicate:i.predicate})),collections:[{collection:'durable_operation_leases',actual_count:'3',pg_only_or_untracked:'1',secret:'must not echo'}],migrationRuns:[{runId:'manifest-run',status:'completed'}],migrationCollections:[{runId:'manifest-run',collection:'durable_operation_leases',sourceCount:'3',targetCount:'3'}]});
const env={DATABASE_URL:'postgresql://fixture:secret@fixture.invalid:5432/fixture',DATABASE_SSL_MODE:'verify-full'};
test('default and absent credentials never execute any child',()=>{let calls=0;const exec=()=>{calls++;throw Error('unexpected spawn');};assert.equal(runReadonly([],env,exec).report.mode,'dry-run');assert.equal(runReadonly(['--execute'],{},exec).report.code,'postgres_connection_configuration_required');assert.equal(runReadonly(['--execute'],{PGSERVICE:'unknown'},exec).exitCode,2);assert.equal(runReadonly(['--execute','--apply'],env,exec).exitCode,2);assert.equal(calls,0);});
test('SQL consists of readonly transaction and catalog/inventory SELECT, not DDL or reports writes',()=>{assert.match(READONLY_SQL,/BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY/);assert.doesNotMatch(READONLY_SQL,/\b(?:CREATE|ALTER|DROP|INSERT|UPDATE|DELETE|COPY|TRUNCATE|CALL)\b/);assert.doesNotMatch(READONLY_SQL,/source_hash IS NOT NULL/);assert.match(READONLY_SQL,/count\(\*\) FILTER \(WHERE source_hash IS NULL\)/);});
test('mock executor receives safe argv, clear inherited PG settings and never leaks connection errors',()=>{let calls=0;const result=runReadonly(['--execute'],{...env,PGOPTIONS:'-c search_path=evil',PGSERVICE:'evil',PGHOST:'evil',PGPASSWORD:'evil',APIFY_TOKEN:'must-clear',REDIS_URL:'must-clear',NODE_OPTIONS:'must-clear'},(cmd,args,options)=>{calls++;assert.equal(cmd,'psql');assert.ok(args.includes('-X'));assert.ok(args.includes('--no-password'));assert.ok(!args.some(a=>a.includes('secret')));assert.equal(options.env.PGSERVICE,undefined);assert.equal(options.env.PGHOST,undefined);assert.equal(options.env.PGPASSWORD,undefined);assert.equal(options.env.APIFY_TOKEN,undefined);assert.equal(options.env.REDIS_URL,undefined);assert.equal(options.env.NODE_OPTIONS,undefined);assert.equal(options.env.PGOPTIONS,'-c default_transaction_read_only=on');assert.equal(options.env.PGSSLMODE,'verify-full');assert.equal(options.input,READONLY_SQL);return{status:0,stdout:JSON.stringify(fixture())};});assert.equal(calls,1);assert.equal(result.report.schemaReady,true);assert.equal(result.report.migrationReady,false);assert.equal(result.report.currentDataVerified,false);assert.ok(!JSON.stringify(result).includes('must not echo'));assert.ok(!JSON.stringify(result).includes('secret'));const failed=runReadonly(['--execute'],env,()=>({status:1,stderr:env.DATABASE_URL,error:Error(env.DATABASE_URL)}));assert.equal(failed.report.code,'postgres_readonly_probe_failed');assert.ok(!JSON.stringify(failed).includes('secret'));assert.equal(runReadonly(['--execute'],env,()=>{throw Error(env.DATABASE_URL);}).report.code,'postgres_readonly_probe_failed');});
test('TLS conflict/disabled and options injection block before spawn',()=>{let calls=0;const exec=()=>{calls++;};for(const e of [{...env,DATABASE_SSL_MODE:'disable'},{...env,DATABASE_URL:env.DATABASE_URL+'?sslmode=require'},{...env,DATABASE_URL:env.DATABASE_URL+'?options=search_path%3Devil'}])assert.equal(runReadonly(['--execute'],e,exec).report.code,'postgres_tls_or_target_conflict');for(const key of ['host','hostaddr','port','dbname','user','password','options','service','sslrootcert'])assert.equal(runReadonly(['--execute'],{...env,DATABASE_URL:env.DATABASE_URL+'?'+key+'=override'},exec).exitCode,2);assert.equal(runReadonly(['--execute'],{...env,DATABASE_URL:'postgresql://fixture@fixture.invalid/fixture'},exec).exitCode,2);assert.equal(calls,0);const f=fixture();f.tls.ssl=false;assert.ok(evaluateReadOnlyCatalog(f).issues.includes('postgres_tls_not_proven'));});
test('exact unique index scope and literal boundaries reject similar or overbroad indexes',()=>{assert.notEqual(canonicalSQL("collection='durable_operation_lea ses'"),canonicalSQL("collection='durable_operation_leases'"));assert.notEqual(canonicalSQL("collection='durable_(operation)_leases'"),canonicalSQL("collection='durable_operation_leases'"));for(const patch of [{predicate:"collection='durable_operation_lea ses'"},{predicate:"collection='durable_operation_leases' OR collection='other'"},{immediate:false},{valid:false},{keys:2},{expressions:"(data->>'tenant_id'),(data->>'scope'),(data->>'subject_id')"}]){const f=fixture();Object.assign(f.indexes[0],patch);assert.equal(evaluateReadOnlyCatalog(f).schemaReady,false);}const f=fixture();f.tables[0].columns.find(c=>c.name==='data').type='text';assert.equal(evaluateReadOnlyCatalog(f).schemaReady,false);});
test('manifest independently checks required reports counts and uniques but never claims current content verified',()=>{const m=parseManifest({runId:'manifest-run',collections:[{name:'durable_operation_leases',expectedCount:3,requiredUniqueIndexes:[{name:'idx_lingshu_durable_operation_lease_subject',...indexes.idx_lingshu_durable_operation_lease_subject}]}]});const r=evaluateReadOnlyCatalog(fixture(),m);assert.equal(r.manifestCoverageReady,true);assert.equal(r.migrationMetadataReady,true);assert.equal(r.currentDataVerified,false);assert.equal(r.migrationReady,false);for(const change of [f=>f.migrationRuns[0].status='failed',f=>f.migrationCollections=[],f=>f.collections[0].actual_count='4',f=>f.indexes[0].unique=false]){const f=fixture();change(f);assert.equal(evaluateReadOnlyCatalog(f,m).manifestCoverageReady,false);}assert.throws(()=>parseManifest({...m,password:'secret'}));const f=fixture();f.collections.push({collection:'secret\nDATABASE_URL=credential',actual_count:'1',pg_only_or_untracked:'0'});assert.ok(!JSON.stringify(evaluateReadOnlyCatalog(f)).includes('credential'));});
test('actual spawn executes only isolated fake psql executable without any socket',t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'infra-pg-readonly-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const executable=path.join(directory,'fake-psql.mjs');fs.writeFileSync(executable,`#!${process.execPath}\nimport fs from 'node:fs';const sql=fs.readFileSync(0,'utf8');if(!sql.startsWith('BEGIN TRANSACTION')||!sql.includes('READ ONLY')||process.env.PGSERVICE||process.env.PGOPTIONS!=='-c default_transaction_read_only=on')process.exit(7);console.log(${JSON.stringify(JSON.stringify(fixture()))});\n`,{mode:0o700});const result=runReadonly(['--execute'],{...env,INFRA_PREP_PSQL_BIN:executable,PGSERVICE:'must-clear'});assert.equal(result.exitCode,0);assert.equal(result.report.executed,true);assert.equal(result.report.schemaReady,true);assert.equal(result.report.migrationReady,false);});

test('placeholder credentials and URL fragments fail before executor',()=>{let calls=0;for(const url of ['postgresql://REPLACE_USER:REPLACE_PASSWORD@postgres.invalid/REPLACE_DATABASE',env.DATABASE_URL+'#hidden-target'])assert.equal(runReadonly(['--execute'],{...env,DATABASE_URL:url},()=>{calls++;}).exitCode,2);assert.equal(calls,0);});
