import test from 'node:test';
import assert from 'node:assert/strict';
import {runBackupPrecheck,validateBackupManifest,runCommand,verifyBackupArtifacts} from './infra-prep-backup-restore.mjs';
const manifest={schemaVersion:'infra-backup.v1',cutoverId:'isolated',createdAt:'2026-10-10T00:00:00Z',sourceCommit:'73c78766',postgres:{artifact:'pg.dump',sha256:'a'.repeat(64),version:'17'},redis:{artifact:'dump.rdb',sha256:'b'.repeat(64),version:'7'},activeJobIds:[],unknownAttemptIds:[],admissionStopped:true,cutoverPhase:'pre-cutover',postBackupWrites:false,consistentRecoveryPoint:true};
const env={DATABASE_SSL_MODE:'require',DATABASE_URL:'postgresql://fixture:secret@127.0.0.1:5432/isolated',REDIS_URL:'rediss://fixture:secret@127.0.0.1:6380/9'};
const outputs=['17\nt | CREATE UNIQUE INDEX idx_lingshu_durable_operation_lease_subject','PONG','loading:0\nrdb_last_bgsave_status:ok','redis_version:7.2.0'];
test('default dry-run never invokes command; missing credentials fail before commands',async()=>{let calls=0;const fake=async()=>{calls++;throw Error('forbidden');};assert.equal((await runBackupPrecheck({},fake)).connect,false);await assert.rejects(runBackupPrecheck({execute:true,env:{},manifest},fake),/postgres_url_invalid/);assert.equal(calls,0);});
test('isolated fake commands prove SELECT/INFO/PING only, secrets not arguments or output',async()=>{let calls=0;const result=await runBackupPrecheck({execute:true,env,manifest,verifyArtifacts:()=>{}},async command=>{assert.ok(!JSON.stringify(command.args).includes('secret'));assert.ok(!command.args.some(a=>/^(BGSAVE|SAVE|RESTORE|FLUSHALL|FLUSHDB)$/i.test(a)));if(command.bin==='psql'){assert.ok(command.env.PGOPTIONS.includes('default_transaction_read_only=on'));assert.ok(!command.args.some(a=>/\b(INSERT|DELETE|UPDATE|CREATE|DROP)\b/.test(a)));}return{code:0,stdout:outputs[calls++]};});assert.equal(calls,4);assert.equal(result.mutations,0);assert.equal(result.restored,false);assert.ok(!JSON.stringify(result).includes('secret'));});
test('each command failure stops immediately; incomplete metadata/persistence blocks',async()=>{for(let fail=0;fail<4;fail++){let calls=0;await assert.rejects(runBackupPrecheck({execute:true,env,manifest,verifyArtifacts:()=>{}},async()=>{const index=calls++;return{code:index===fail?1:0,stdout:outputs[index]};}),new RegExp(`step_${fail+1}_failed`));assert.equal(calls,fail+1);}let calls=0;await assert.rejects(runBackupPrecheck({execute:true,env,manifest,verifyArtifacts:()=>{}},async()=>({code:0,stdout:outputs[calls++].replace('loading:0','loading:1')})),/persistence_unhealthy/);assert.equal(calls,3);});
test('manifest requires independent PostgreSQL and Redis hashes and active/unknown evidence forbids blind rollback eligibility',()=>{assert.throws(()=>validateBackupManifest({...manifest,redis:null}),/redis_invalid/);assert.equal(validateBackupManifest({...manifest,activeJobIds:['running']}).restoreEligible,false);assert.equal(validateBackupManifest({...manifest,unknownAttemptIds:['unknown']}).restoreEligible,false);assert.equal(validateBackupManifest({...manifest,admissionStopped:false}).restoreEligible,false);});

test('missing backup artifact stops before any metadata connection',async()=>{let calls=0;await assert.rejects(runBackupPrecheck({execute:true,env,manifest},async()=>{calls++;return{code:0,stdout:''};}),/backup_artifact_postgres_unreadable/);assert.equal(calls,0);});

test('backup manifest major versions must match read-only target metadata',async()=>{let calls=0;await assert.rejects(runBackupPrecheck({execute:true,env,manifest:{...manifest,postgres:{...manifest.postgres,version:'16'}},verifyArtifacts:()=>{}},async()=>({code:0,stdout:outputs[calls++]})),/postgres_version_mismatch/);assert.equal(calls,1);});

import {mkdtempSync,writeFileSync,chmodSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
test('real fake child executables validate sanitized env and safe commands without service connection',async t=>{const dir=mkdtempSync(join(tmpdir(),'infra-precheck-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const pg=join(dir,'fake-psql'),redis=join(dir,'fake-redis');writeFileSync(pg,"#!/bin/sh\n[ -z \"$PGSERVICE\" ] || exit 9\n[ \"$PGSSLMODE\" = require ] || exit 9\nprintf '17\\nt | CREATE UNIQUE INDEX idx_lingshu_durable_operation_lease_subject\\n'\n");writeFileSync(redis,"#!/bin/sh\ncase \"$*\" in *PING*) printf PONG;; *persistence*) printf 'loading:0\\nrdb_last_bgsave_status:ok';; *server*) printf 'redis_version:7.2.0';; *) exit 9;; esac\n");chmodSync(pg,0o700);chmodSync(redis,0o700);let calls=0;const result=await runBackupPrecheck({execute:true,env:{...env,PGSERVICE:'must-not-inherit',PGOPTIONS:'unsafe'},manifest,verifyArtifacts:()=>{}},command=>{calls++;return runCommand({...command,bin:command.bin==='psql'?pg:redis});});assert.equal(calls,4);assert.equal(result.mutations,0);});
test('streamed real artifact hashes fail before connection on mismatch',async t=>{const dir=mkdtempSync(join(tmpdir(),'infra-artifact-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const artifact=join(dir,'isolated.dump');writeFileSync(artifact,'controlled backup');const valid=createHash('sha256').update('controlled backup').digest('hex');await verifyBackupArtifacts({...manifest,postgres:{...manifest.postgres,artifact,sha256:valid},redis:{...manifest.redis,artifact,sha256:valid}});await assert.rejects(verifyBackupArtifacts({...manifest,postgres:{...manifest.postgres,artifact}}),/hash_mismatch/);});
test('SSL downgrade/conflict and absent PostgreSQL database/user reject before commands; eligibility is preliminary',async()=>{for(const changes of [{DATABASE_SSL_MODE:'disable'},{DATABASE_URL:env.DATABASE_URL+'?sslmode=disable'},{DATABASE_URL:'postgresql://:secret@127.0.0.1/db'},{DATABASE_URL:'postgresql://fixture:secret@127.0.0.1/'}]){await assert.rejects(runBackupPrecheck({execute:true,env:{...env,...changes},manifest},()=>{throw Error('must not spawn');}));}assert.equal(validateBackupManifest({...manifest,postBackupWrites:true}).restoreEligible,false);assert.equal(validateBackupManifest({...manifest,cutoverPhase:'post-cutover'}).restoreEligible,false);assert.equal(validateBackupManifest({...manifest,consistentRecoveryPoint:false}).restoreEligible,false);assert.equal(validateBackupManifest(manifest).eligibility,'preliminary');});

import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
test('CLI default is zero-connect and malformed private manifest errors never echo content',t=>{const dir=mkdtempSync(join(tmpdir(),'infra-cli-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const file=join(dir,'private.json');writeFileSync(file,'{"synthetic-private-secret" broken');const script=fileURLToPath(new URL('./infra-prep-backup-restore.mjs',import.meta.url));let result=spawnSync(process.execPath,[script],{env:{PATH:process.env.PATH},encoding:'utf8'});assert.equal(result.status,0);assert.equal(JSON.parse(result.stdout).connect,false);result=spawnSync(process.execPath,[script,'--manifest='+file],{env:{PATH:process.env.PATH},encoding:'utf8'});assert.notEqual(result.status,0);assert.ok(!result.stderr.includes('synthetic-private-secret'));assert.match(result.stderr,/backup_precheck_failed/);});

test('review template credentials never connect even when execute is requested',async()=>{let calls=0;for(const overrides of [{DATABASE_URL:'postgresql://REPLACE_USER:REPLACE_PASSWORD@postgres.invalid/REPLACE_DATABASE'},{REDIS_URL:'rediss://:REPLACE_PASSWORD@redis.invalid/0'}])await assert.rejects(runBackupPrecheck({execute:true,env:{...env,...overrides},manifest,verifyArtifacts:()=>{}},async()=>{calls++;}));assert.equal(calls,0);});
