import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';
dotenv.config({path:path.resolve('../local-preview-1002/.env'),quiet:true});
dotenv.config({path:path.resolve('../local-preview-1002/.env.local'),override:true,quiet:true});
const {inspectStoryboardAigcFramesWithQwen}=await import('../server/agents/qwen.js');
const {buildStoryboardQaReport,inspectStoryboardTechnicalFrames}=await import('../server/lib/storyboardAigcQuality.js');
const root=path.resolve('data/acceptance/real-shot-replication-20261008');
const state=JSON.parse(fs.readFileSync(path.join(root,'nonperson-shot-state.json'),'utf8'));
const material=state.result.material;
const tenant='local_tenant_customer_1b2913131e2c46deab66172228c4df0a';
const generatedPath=path.resolve('data/media/object-storage/materials/tenants',Buffer.from(tenant).toString('base64url'),`${material.id}.jpg`);
const productPath=path.resolve(`data/media/tenants/${tenant}/rongshang-products/rongshang-product-14.png`);
const generated=fs.readFileSync(generatedPath),product=fs.readFileSync(productPath);
const observations=await inspectStoryboardAigcFramesWithQwen({phase:'first_frame',sceneType:'product',frames:[{base64:generated.toString('base64'),mimeType:'image/jpeg',timeLabel:'候选首帧'}],productReferences:[{base64:product.toString('base64'),mimeType:'image/png',timeLabel:'企业产品身份参考：GUIANFA 丝蛋白生物基抗皱干膜，包装印刷女模特图案属于产品身份'}],storyboard:material.provenance.shotSpec.description+' “不出现人物脸”指真人出镜脸，不包含包装印刷人像；包装印刷人像应严格保留。',productInfo:'企业目标产品：GUIANFA 丝蛋白生物基抗皱干膜；以企业参考图实际包装为准，不是无品牌包装。包装正面女模特印刷图、面膜轮廓、品牌、文字与配色都属于身份约束。'});
const technical=await inspectStoryboardTechnicalFrames('first_frame',[{bytes:generated,timeLabel:'候选首帧'}]);
const report=buildStoryboardQaReport({phase:'first_frame',sceneType:'product',hasProduct:true,hasNamedPerson:false,hasEnvironmentReference:false,hasContact:true,hasAction:false,observations:[...observations.filter(item=>!technical.some(t=>t.key===item.key)),...technical],evidenceFrameLabels:['候选首帧']});
fs.writeFileSync(path.join(root,'nonperson-first-frame-recheck.json'),JSON.stringify({materialId:material.id,generatedPath,productPath,reviewKind:'independent_real_qwen_recheck_brand_identity_context_corrected',originalReport:state.result.firstFrameQuality,report,businessAccepted:false,humanConfirmation:false},null,2));
console.log(JSON.stringify({status:report.status,passed:report.passed,findings:report.findings},null,2));
