import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { reviseContent } from './contentRevision.js';
import { contentAcceptanceHash } from './contentAcceptance.js';
import { parseDirection, selectedSegments } from './contentDirection.js';
import { verifiedAudioCues } from '../integrations/qwenAlignment.js';
import { safeContentFile, projectOutputs } from '../routes/contentLibrary.js';
const spec:any={script:'approved script',lang:'en',duration:10,contentOrder:{videoPlan:{presenter:'heygen',voice:'v2'}},renderOutputPath:'/video.mp4',alignedCuesByLang:{en:[{start:0,end:4,text:'Hello world.'}]},sceneSourcePlan:[{assetId:'a'},{assetId:'b'},{assetId:'a'}],automation:{contentVersion:1,routePlan:{assetIds:['a','b']},renderOutputPath:'/video.mp4'},contentAcceptance:{approvedBy:'human'}};
assert.equal(reviseContent(spec,'music',{bgm:'music',volume:24}).automation.stage,'heygen');
const voice=reviseContent(spec,'voice',{voice:'v2',speed:1.1});assert.equal(voice.automation.stage,'voice_subtitles');assert.equal(voice.automation.heygenJobId,'');assert.equal(voice.contentAcceptance,null);
assert.equal(reviseContent(spec,'cover',{title:'Hello',frameTime:2}).renderOutputPath,'/video.mp4');
assert.equal(reviseContent(spec,'export',{ratio:'16:9',resolution:'720p'}).ratio,'16:9');
assert.throws(()=>reviseContent(spec,'music',{bgm:'x',volume:NaN}));
assert.throws(()=>reviseContent(spec,'subtitles',{cues:[{start:0,end:3,text:'Invented fact'}]}));
assert.throws(()=>reviseContent(spec,'subtitles',{cues:[{start:4,end:3,text:'Hello world.'}]}));
assert.equal(reviseContent(spec,'subtitles',{cues:[{start:1,end:4,text:'Hello world.'}],fontScale:1.2}).subtitleAlignmentSource,'human_reviewed');
assert.throws(()=>reviseContent(spec,'shots',{scenes:Array.from({length:3},()=>({source:'material',materialId:'foreign',trimStart:0}))}));
assert.notEqual(contentAcceptanceHash(spec),contentAcceptanceHash({...spec,subtitleStyle:{fontScale:1.2}}));
assert.throws(()=>parseDirection(JSON.stringify({voice:'v1',speed:1,scenes:[{source:'material',materialId:'a',trimStart:0,confidence:.2,reason:'unknown'}]}),1,['a'],'material'));
assert.throws(()=>selectedSegments([{id:'a',type:'video',duration:5}],[4],[{trimStart:2}]));
assert.equal(selectedSegments([{id:'a',type:'video',duration:8}],[4],[{trimStart:2}])[0].trimEnd,6);
const raw={transcripts:[{sentences:[{words:[{begin_time:100,end_time:500,text:'Hello'},{begin_time:600,end_time:1100,text:'world',punctuation:'.'}]}]}]};
assert.equal(verifiedAudioCues(raw,'Hello world.',2)[1].start,.6);
assert.throws(()=>verifiedAudioCues(raw,'Different content.',2));
const tenant='test-lifecycle-'+Date.now(),dir=path.resolve('data/publishing-uploads',tenant);fs.mkdirSync(dir,{recursive:true});
const file=path.join(dir,'video.mp4');fs.writeFileSync(file,'fixture');
assert.equal(safeContentFile(tenant,file),file);assert.equal(safeContentFile('foreign',file),'');
const outside=path.join(os.tmpdir(),'lifecycle-'+Date.now());fs.writeFileSync(outside,'secret');fs.symlinkSync(outside,path.join(dir,'escape.mp4'));assert.equal(safeContentFile(tenant,path.join(dir,'escape.mp4')),'');
fs.rmSync(dir,{recursive:true});fs.unlinkSync(outside);
const outputs=projectOutputs({id:'p',title:'video',spec:{...spec,languageRenderOutputs:{en:{status:'done',path:'/video.mp4'}},revisionHistory:[{renderOutputPath:'/old.mp4',version:1}]}});assert.equal(outputs.length,2);assert.equal(outputs[1].current,false);
console.log('Content lifecycle: node revisions, timeline constraints, audio alignment, output history and tenant file boundaries passed');
