import {createHash,randomUUID} from 'node:crypto';
import {acquireDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
import {withLocalQueue} from '../routes/digitalEmployeeRecords.js';
const sendIntentQueues=new Map<string,Promise<void>>();
import type {WeeklyNativeSendAuthority} from '../../shared/contracts/weeklyNativeSendAuthority.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {publicationInstant} from '../socialPrograms/publicationDeadlines.js';
import {SocialProgramError} from '../socialPrograms/service.js';
import type {CustomerChannelSendRequest,CustomerChannelSendReceipt,SignedChannelMessageReceipt} from '../../shared/contracts/customerChannelSendRequest.js';
export const CHANNEL_SEND_REQUESTS='customer_channel_send_requests';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const fail=(code:string,status=409):never=>{throw new SocialProgramError(code,status,code);};
function check(v:unknown,code:string):asserts v{if(!v)fail(code);}
const object=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return object(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
interface FrozenRequest extends CustomerChannelSendRequest {weeklyAuthority?:WeeklyNativeSendAuthority;activeKey:string;signedReceipts?:SignedChannelMessageReceipt[];body:string;recipientId:string;recordHash:string;providerReceipt:CustomerChannelSendReceipt|null;requestKey:string}
async function actor(store:DataStore,tenantId:string,id:string){const u=await store.getById<Record_>('users',id);const role=organizationRoleOrNull(u?.role);if(!u||u.tenantId!==tenantId||!role||u.disabled===true||u.status==='disabled')fail('channel_send_actor_forbidden',403);return role!;}
function publicRequest(r:FrozenRequest):CustomerChannelSendRequest{const{weeklyAuthority,activeKey,signedReceipts,body,recipientId,providerReceipt,recordHash,requestKey,...p}=r;void weeklyAuthority;void activeKey;void signedReceipts;void body;void recipientId;void providerReceipt;void recordHash;void requestKey;return p;}
function seal(p:Omit<FrozenRequest,'recordHash'>):FrozenRequest{return {...p,recordHash:hash(p)};}
async function read(store:DataStore,tenantId:string,requestId:string,channel:'messenger'|'instagram'){
 const requestKey=hash([tenantId,channel,requestId]);const rows=await store.list<Record_>(CHANNEL_SEND_REQUESTS,{where:{tenant_id:tenantId,request_key:requestKey},page:1,perPage:2});check(rows.totalItems===rows.items.length&&rows.items.length<=1,'channel_send_request_ambiguous');if(!rows.items.length)return null;const row=rows.items[0]!;const p=object(row.payload) as FrozenRequest;const{recordHash,...content}=p;check(row.tenant_id===tenantId&&row.request_key===requestKey&&p.tenantId===tenantId&&p.channel===channel&&p.requestId===requestId&&p.requestKey===requestKey&&recordHash===hash(content)&&row.content_hash===recordHash,'channel_send_request_corrupt');return {row,p};
}
export async function resolveCustomerChannelOutboxContext(store:DataStore,input:{tenantId:string;actorUserId:string;customerId:string;channel:'messenger'|'instagram';nativeAccountId:string}){
 await actor(store,input.tenantId,input.actorUserId);const candidates=await store.list<Record_>('social_accounts',{where:{tenantId:input.tenantId,platform:input.channel==='messenger'?'facebook':'instagram',status:'connected',providerAccountId:input.nativeAccountId},page:1,perPage:2});check(candidates.totalItems===1&&candidates.items.length===1,'channel_send_account_ambiguous');const account=candidates.items[0]!;check(account.tenantId===input.tenantId&&account.providerAccountId===input.nativeAccountId&&account.status==='connected','channel_send_account_invalid');return {tenantId:input.tenantId,actorUserId:input.actorUserId,customerId:input.customerId,channel:input.channel,accountId:account.id,accountAuthorityHash:hash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null})};
}
/** A unique durable row is the first-send fence. Existing sending/unknown intent never calls transport again. */
export function createCustomerChannelSendRequestService(store:DataStore){
 async function executeUnderFence(input:{tenantId:string;actorUserId:string;requestId:string;channel:'messenger'|'instagram';customerId:string;accountId:string;recipientId:string;body:string;weeklyAuthority?:WeeklyNativeSendAuthority;send:()=>Promise<{messageId:string;recipientId:string;raw:Record<string,unknown>}>;recordHistory:(receipt:CustomerChannelSendReceipt)=>Promise<void>|void}):Promise<CustomerChannelSendReceipt>{
 await actor(store,input.tenantId,input.actorUserId);check(typeof input.requestId==='string'&&/^[a-zA-Z0-9_-]{8,120}$/.test(input.requestId),'channel_send_request_id_required');check([input.customerId,input.accountId,input.recipientId,input.body].every(v=>typeof v==='string'&&v.trim()),'channel_send_scope_invalid');const account=await store.getById<Record_>('social_accounts',input.accountId);check(account?.tenantId===input.tenantId&&account.status==='connected'&&account.platform===(input.channel==='messenger'?'facebook':'instagram')&&typeof account.providerAccountId==='string'&&account.providerAccountId.trim(),'channel_send_account_invalid');
 if(input.weeklyAuthority){const {readWeeklyNativeDispatchAuthority}=await import('./weeklyNativeSendAuthority.js');const actual=await readWeeklyNativeDispatchAuthority(store,{tenantId:input.tenantId,actorUserId:input.actorUserId,batchId:input.weeklyAuthority.batchId,itemId:input.weeklyAuthority.itemId});check(socialRequestHash(actual)===socialRequestHash(input.weeklyAuthority)&&actual.channel===input.channel&&actual.accountId===input.accountId&&actual.customerId===input.customerId&&actual.recipientId===input.recipientId,'channel_send_weekly_authority_invalid');const item=await store.getById<Record_>('followup_batch_items',actual.itemId);check(item,'channel_send_weekly_item_missing');const {assertAppliedKnowledgeQuoteDraftItemEvidence}=await import('../socialPrograms/weeklyCustomerKnowledgeQuote.js');await assertAppliedKnowledgeQuoteDraftItemEvidence(store,item);check(item?.draft_body===input.body,'channel_send_weekly_body_changed');}
 const accountAuthorityHash=hash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null});
 const requestKey=hash([input.tenantId,input.channel,input.requestId]);const bodyHash=hash(input.body),recipientHash=hash(input.recipientId);const existing=await read(store,input.tenantId,input.requestId,input.channel);const same=(p:FrozenRequest)=>p.actorUserId===input.actorUserId&&p.customerId===input.customerId&&p.accountId===input.accountId&&p.accountAuthorityHash===accountAuthorityHash&&p.bodyHash===bodyHash&&p.recipientHash===recipientHash&&p.weeklyAuthorityHash===(input.weeklyAuthority?socialRequestHash(input.weeklyAuthority):undefined);
 if(existing){check(same(existing.p),'channel_send_request_intent_conflict');if(existing.p.status==='accepted'&&existing.p.providerReceipt){if(existing.p.historyWritebackPending){try{await input.recordHistory(existing.p.providerReceipt);const{recordHash,...base}=existing.p;void recordHash;const next=seal({...base,historyWritebackPending:false});check(await store.update(CHANNEL_SEND_REQUESTS,existing.row.id,{payload:next,content_hash:next.recordHash}),'channel_send_history_writeback_failed');}catch{/* Retain pending; never resend. */}}return existing.p.providerReceipt;}return fail(existing.p.recoveryGap??'channel_send_request_pending_identity_gap');}
 // A new request ID cannot bypass an unresolved identical send to the same recipient.
 for(let page=1;;page++){const pending=await store.list<Record_>(CHANNEL_SEND_REQUESTS,{where:{tenant_id:input.tenantId},page,perPage:250,sort:'id'});for(const row of pending.items){const candidate=object(row.payload);if(candidate.channel===input.channel&&candidate.accountId===input.accountId&&candidate.recipientHash===recipientHash&&candidate.bodyHash===bodyHash&&['sending','unknown'].includes(candidate.status))fail('channel_send_unresolved_prior_request');}if(page>=pending.totalPages)break;check(pending.items.length===250,'channel_send_request_scan_incomplete');}
 const activeKey=hash([input.tenantId,input.channel,input.accountId,input.recipientId,input.body]);
 const p=seal({...input.weeklyAuthority?{weeklyAuthority:input.weeklyAuthority,weeklyAuthorityHash:socialRequestHash(input.weeklyAuthority),weeklySource:{programId:input.weeklyAuthority.programId,packageId:input.weeklyAuthority.packageId,packageVersion:input.weeklyAuthority.packageVersion,runId:input.weeklyAuthority.runId,batchId:input.weeklyAuthority.batchId,batchVersion:input.weeklyAuthority.batchVersion,itemId:input.weeklyAuthority.itemId,itemHash:input.weeklyAuthority.itemHash,selectionHash:input.weeklyAuthority.selectionHash}}:{},activeKey,requestId:input.requestId,requestKey,channel:input.channel,tenantId:input.tenantId,actorUserId:input.actorUserId,customerId:input.customerId,accountId:input.accountId,body:input.body,bodyHash,accountAuthorityHash,recipientId:input.recipientId,recipientHash,recipientMasked:'…'+input.recipientId.slice(-4),deliveryStatus:'unverified',status:'sending',providerMessageId:null,providerReceipt:null,createdAt:new Date().toISOString(),settledAt:null,recoveryGap:null,historyWritebackPending:false});
 let row:Record_|null=null;try{row=await store.create<Record_>(CHANNEL_SEND_REQUESTS,{id:requestKey.slice(0,15),tenant_id:input.tenantId,request_key:requestKey,active_key:activeKey,payload:p,content_hash:p.recordHash});}catch{const winner=await read(store,input.tenantId,input.requestId,input.channel);if(!winner){const held=await store.list<Record_>(CHANNEL_SEND_REQUESTS,{where:{tenant_id:input.tenantId,active_key:activeKey},page:1,perPage:2});if(held.totalItems>0)fail('channel_send_unresolved_prior_request');return fail('channel_send_request_save_failed');}check(same(winner.p),'channel_send_request_intent_conflict');if(winner.p.status==='accepted'&&winner.p.providerReceipt)return winner.p.providerReceipt;return fail('channel_send_request_pending_identity_gap');}check(row,'channel_send_request_save_failed');
 const save=async(next:FrozenRequest)=>{check(await store.update(CHANNEL_SEND_REQUESTS,row!.id,{payload:next,content_hash:next.recordHash,active_key:next.status==='accepted'?'':activeKey}),'channel_send_request_save_failed');};
 let receipt:CustomerChannelSendReceipt;try{const actual=await input.send();check(typeof actual.messageId==='string'&&actual.messageId.trim()&&!/^(mock|simulat)/i.test(actual.messageId)&&actual.recipientId===input.recipientId,'channel_send_provider_identity_invalid');receipt={...actual,requestId:input.requestId,acceptedAt:new Date().toISOString()};}catch{try{const{recordHash,...base}=p;void recordHash;await save(seal({...base,status:'unknown',settledAt:new Date().toISOString(),recoveryGap:'provider_identity_gap'}));}catch{/* Durable sending fence remains: never send again. */}return fail('provider_identity_gap');}
 const{recordHash,...base}=p;void recordHash;const accepted=seal({...base,status:'accepted',providerMessageId:receipt.messageId,providerReceipt:receipt,settledAt:new Date().toISOString(),historyWritebackPending:true});try{await save(accepted);}catch{return fail('provider_response_save_gap');}
 try{await input.recordHistory(receipt);const{recordHash:old,...known}=accepted;void old;await save(seal({...known,historyWritebackPending:false}));}catch{/* Provider evidence is durable. A replay returns it without sending again. */}
 return receipt;
 }
 return {
 async get(tenantId:string,actorUserId:string,channel:'messenger'|'instagram',requestId:string){const role=await actor(store,tenantId,actorUserId);const r=await read(store,tenantId,requestId,channel);if(r&&r.p.actorUserId!==actorUserId&&!['admin','super_admin'].includes(role))fail('channel_send_request_actor_forbidden',403);return r?publicRequest(r.p):null;},
 /** Internal ingress only: caller has verified the tenant app HMAC and native account ownership. */
 async recordSignedChannelReceipt(input:SignedChannelMessageReceipt){
 check(input.verifiedSignature===true&&['messenger','instagram'].includes(input.channel)&&/^[a-f0-9]{64}$/.test(input.eventHash)&&/^[a-f0-9]{64}$/.test(input.signedBodyHash)&&publicationInstant(input.occurredAt)!==null&&['sent','delivered','read','failed'].includes(input.status)&&['echo','delivery','read'].includes(input.eventKind),'channel_send_signed_receipt_invalid');
 const found:Record_[]=[];for(let page=1;;page++){const rows=await store.list<Record_>(CHANNEL_SEND_REQUESTS,{where:{tenant_id:input.tenantId},page,perPage:250,sort:'id'});check(rows.items.every(r=>r.tenant_id===input.tenantId),'channel_send_receipt_tenant_invalid');found.push(...rows.items);if(page>=rows.totalPages){check(found.length===rows.totalItems,'channel_send_receipt_scan_incomplete');break;}check(rows.items.length===250,'channel_send_receipt_scan_incomplete');}
 const candidates=found.filter(row=>{const p=object(row.payload);return p.channel===input.channel&&p.status==='accepted'&&p.providerMessageId===input.providerMessageId;});check(candidates.length<=1,'channel_send_provider_identity_ambiguous');if(!candidates.length)return {matched:false as const};const candidate=object(candidates[0]!.payload);const actual=await read(store,input.tenantId,String(candidate.requestId),input.channel);check(actual&&actual.p.status==='accepted'&&actual.p.providerReceipt?.messageId===input.providerMessageId,'channel_send_receipt_request_invalid');const p=actual.p;const account=await store.getById<Record_>('social_accounts',p.accountId);check(account?.tenantId===input.tenantId&&account.providerAccountId===input.nativeAccountId&&hash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null})===p.accountAuthorityHash&&p.recipientId===input.recipientId&&p.providerReceipt?.recipientId===input.recipientId,'channel_send_signed_source_identity_invalid');check(publicationInstant(input.occurredAt)!>=Date.parse(p.createdAt)&&(!('body' in input)||hash(input.body)===p.bodyHash),'channel_send_signed_source_content_invalid');const prior=p.signedReceipts??[];const same=prior.find(r=>r.eventHash===input.eventHash&&r.signedBodyHash===input.signedBodyHash);if(same){check(hash(same)===hash(input),'channel_send_signed_event_conflict');return {matched:true as const,item:publicRequest(p)};}
 const newest=[...prior].sort((a,b)=>Date.parse(b.occurredAt)-Date.parse(a.occurredAt))[0];const rank={unverified:0,sent:1,delivered:2,read:3,failed:1};const status=newest&&Date.parse(newest.occurredAt)>Date.parse(input.occurredAt)?p.deliveryStatus:input.status==='failed'?input.status:rank[input.status]>=rank[p.deliveryStatus]?input.status:p.deliveryStatus;const{recordHash,...base}=p;void recordHash;const next=seal({...base,deliveryStatus:status,signedReceipts:[...prior,input]});check(await store.update(CHANNEL_SEND_REQUESTS,actual.row.id,{payload:next,content_hash:next.recordHash}),'channel_send_signed_receipt_save_failed');return {matched:true as const,item:publicRequest(next)};
 },
 async repairHistory(input:{tenantId:string;actorUserId:string;channel:'messenger'|'instagram';requestId:string;customerId:string;recordHistory:(receipt:CustomerChannelSendReceipt,body:string,account:Record_)=>Promise<void>|void}){
 const role=await actor(store,input.tenantId,input.actorUserId);const actual=await read(store,input.tenantId,input.requestId,input.channel);check(actual&&actual.p.customerId===input.customerId,'channel_send_request_not_found');if(actual.p.actorUserId!==input.actorUserId&&!['admin','super_admin'].includes(role))fail('channel_send_request_actor_forbidden',403);check(actual.p.status==='accepted'&&actual.p.providerReceipt&&actual.p.providerMessageId===actual.p.providerReceipt.messageId,'channel_send_history_requires_real_receipt');const account=await store.getById<Record_>('social_accounts',actual.p.accountId);check(account?.tenantId===input.tenantId&&hash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null})===actual.p.accountAuthorityHash,'channel_send_account_authority_drift');check(hash(actual.p.body)===actual.p.bodyHash&&actual.p.providerReceipt.recipientId===actual.p.recipientId&&actual.p.providerReceipt.requestId===input.requestId,'channel_send_request_corrupt');if(actual.p.historyWritebackPending){await input.recordHistory(actual.p.providerReceipt,actual.p.body,account);const{recordHash,...base}=actual.p;void recordHash;const next=seal({...base,historyWritebackPending:false});check(await store.update(CHANNEL_SEND_REQUESTS,actual.row.id,{payload:next,content_hash:next.recordHash}),'channel_send_history_writeback_failed');return publicRequest(next);}return publicRequest(actual.p);
 },
 execute(input:Parameters<typeof executeUnderFence>[0]){const subject=hash([input.tenantId,input.channel,input.accountId,input.recipientId,input.body]);return withLocalQueue(sendIntentQueues,subject,async()=>{const lease=await acquireDurableOperationLease({dataStore:store,tenantId:input.tenantId,scope:'customer_channel_send_intent',subjectId:subject,ownerId:randomUUID()});check(lease,'channel_send_intent_busy');try{return await executeUnderFence(input);}finally{await releaseDurableOperationLease({dataStore:store,lease});}});}
};}

/** Internal weekly recovery read: validates immutable request bytes without exposing body or recipient in HTTP DTOs. */
export async function readWeeklyNativeSendRequestEvidence(store:DataStore,input:{tenantId:string;channel:'messenger'|'instagram';requestId:string}){
 const r=await read(store,input.tenantId,input.requestId,input.channel);if(!r)return null;const a=r.p.weeklyAuthority;
 check(a&&r.p.weeklyAuthorityHash===socialRequestHash(a)&&a.tenantId===input.tenantId&&a.channel===input.channel&&a.actorUserId===r.p.actorUserId&&a.customerId===r.p.customerId&&a.accountId===r.p.accountId&&a.recipientId===r.p.recipientId&&hash(r.p.body)===r.p.bodyHash&&hash(r.p.recipientId)===r.p.recipientHash,'channel_send_weekly_request_identity_invalid');
 const {readWeeklyNativeDispatchAuthority}=await import('./weeklyNativeSendAuthority.js');const actual=await readWeeklyNativeDispatchAuthority(store,{tenantId:input.tenantId,actorUserId:a.actorUserId,batchId:a.batchId,itemId:a.itemId});check(socialRequestHash(actual)===socialRequestHash(a),'channel_send_weekly_request_source_changed');
 if(r.p.status==='accepted')check(r.p.providerReceipt&&r.p.providerReceipt.messageId===r.p.providerMessageId&&r.p.providerReceipt.requestId===r.p.requestId&&r.p.providerReceipt.recipientId===r.p.recipientId&&r.p.providerMessageId&&!/^(mock|simulat)/i.test(r.p.providerMessageId)&&publicationInstant(r.p.providerReceipt.acceptedAt)!==null&&publicationInstant(r.p.settledAt??'')!==null,'channel_send_weekly_request_receipt_invalid');
 return {request:publicRequest(r.p),authority:a,intentHash:hash({authority:a,requestId:r.p.requestId,bodyHash:r.p.bodyHash,recipientHash:r.p.recipientHash,accountAuthorityHash:r.p.accountAuthorityHash}),receipt:r.p.providerReceipt};
}
