import assert from 'node:assert/strict';
import { store } from '../storage/index.js';
import { buildPublishingApprovalPackage, createPublishingCalendarEntries } from './publishingExecution.js';
const rows:Record<string,any[]>={};
const original={list:store.list,create:store.create,update:store.update,getById:store.getById};
const originalFetch=globalThis.fetch;
let networkCalls=0;
let failureMode: 'none' | 'before' | 'after' = 'none';
store.list=(async(c:string,q:any={})=>{const items=(rows[c]||[]).filter(r=>Object.entries(q.where||{}).every(([k,v])=>r[k]===v));return{items:structuredClone(items),totalItems:items.length,totalPages:1,page:1,perPage:500};}) as typeof store.list;
store.getById=(async(c:string,id:string)=>structuredClone((rows[c]||[]).find(r=>r.id===id)||null)) as typeof store.getById;
store.create=(async(c:string,body:any)=>{if(c==='posts'&&failureMode==='before'){failureMode='none';throw Error('fixture create rejected');}const r={...structuredClone(body),id:`${c}-${(rows[c]||[]).length+1}`};(rows[c]||=[]).push(r);if(c==='posts'&&failureMode==='after'){failureMode='none';throw Error('fixture acknowledgement lost');}return structuredClone(r);}) as typeof store.create;
store.update=(async(c:string,id:string,patch:any)=>{const r=(rows[c]||[]).find(r=>r.id===id);if(!r)return false;Object.assign(r,structuredClone(patch));return true;}) as typeof store.update;
globalThis.fetch=(async()=>{networkCalls++;throw Error('network forbidden in fixture');}) as typeof fetch;
try {
 const pack=buildPublishingApprovalPackage({tenantId:'mock-account-slots',projects:[{id:'mock-project',status:'ready_for_approval',spec:{automation:{managedBy:'digital_employee',stage:'completed',renderOutputPath:'/mock/video.mp4',quality:{passed:true,ruleVersion:9}}}}],targets:[{platform:'youtube',accountId:'ny',accountLabel:'New York',timezone:'America/New_York'},{platform:'youtube',accountId:'sh',accountLabel:'Shanghai',timezone:'Asia/Shanghai'}],goalPlatforms:['youtube'],allowRealPublishing:false,now:new Date('2026-09-06T00:00:00Z'),scheduling:{startsAt:'2026-09-06',endsAt:'2026-09-07',timezone:'account'}});
 const input={tenantId:'mock-account-slots',runId:'run',approvalTaskId:'approve',approvalId:'approval',approvedContentHash:pack.contentHash,package:pack};
 const createEntries=(value:Parameters<typeof createPublishingCalendarEntries>[0])=>createPublishingCalendarEntries(value,{verifySource:async(_tenantId,claim)=>claim});
 const altered=structuredClone(pack);altered.items[0].videoPath='/mock/changed-after-approval.mp4';
 await assert.rejects(()=>createEntries({...input,package:altered}),/approval_subject_changed/,'changed items cannot reuse the old approval hash');
 assert.equal((rows.posts||[]).length,0);
 const created=await createEntries(input);
 assert.equal(new Set(created.map(r=>r.id)).size,2,'each account requires its own calendar record');
 assert.equal(rows.posts.length,2);
 assert.deepEqual(rows.posts.map(p=>p.stats.targetAccountIds),[['ny'],['sh']]);
 assert.notEqual(rows.posts[0].published_at,rows.posts[1].published_at);
 assert.ok(rows.posts.every(p=>p.stats.status==='awaiting_manual_publish'&&!p.stats.realPublishingAuthorized));
 const again=await createEntries(input);
 assert.deepEqual(again,created);assert.equal(rows.posts.length,2,'retry must not duplicate either account');
 const other=await createEntries({...input,tenantId:'other-tenant'});
 assert.equal(other.length,2);assert.equal(rows.posts.length,4,'identical external keys must remain tenant scoped');
 const parallelInput={...input,runId:'parallel'};
 const [left,right]=await Promise.all([createEntries(parallelInput),createEntries(parallelInput)]);
 assert.deepEqual(left,right);assert.equal(rows.posts.length,6,'parallel invocation must serialize creation');
 failureMode='before';
 await assert.rejects(()=>createEntries({...input,runId:'failed-before'}),/create rejected/);
 assert.equal(rows.posts.length,6,'rejected create must not report successful calendar entries');
 const recoveredBefore=await createEntries({...input,runId:'failed-before'});
 assert.equal(recoveredBefore.length,2);assert.equal(rows.posts.length,8);
 failureMode='after';
 await assert.rejects(()=>createEntries({...input,runId:'failed-after'}),/acknowledgement lost/);
 assert.equal(rows.posts.length,9);
 assert.ok(rows.posts.at(-1).stats.approvedContentHash,'persisted record already contains recovery identity');
 const recoveredAfter=await createEntries({...input,runId:'failed-after'});
 assert.equal(new Set(recoveredAfter.map(r=>r.id)).size,2);assert.equal(rows.posts.length,10,'retry reuses persisted first account rather than orphaning it');
 assert.equal(networkCalls,0);
 console.log('Per-account timezone calendar creation, concurrent retry, ambiguous persistence recovery and tenant isolation passed');
}finally{Object.assign(store,original);globalThis.fetch=originalFetch;}
