import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeDispatchFixture as fixture} from './weeklyNativeFollowupDispatch.fixture.js';
import {validateWeeklyNativeSendReceipt} from './weeklyNativeFollowupDispatch.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
const scope={runId:'run',programId:'program',packageId:'week',packageVersion:1};
test('actual approved native weekly scope binds a real durable provider receipt; replay never resends',async()=>{for(const channel of ['messenger','instagram']as const){const f=await fixture(channel);try{const candidates=await f.service.sources('tenant','owner','run',scope);assert.equal(candidates[0]?.gap,null);const receipt=await f.service.dispatch(f.command);assert.equal(receipt.status,'sent');assert.equal(receipt.originalTaskCompleted,true);assert.equal(f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!.status,'succeeded');assert.equal(f.data.workflow_runs![0]!.status,'running');assert.equal(f.sends(),1);assert.equal((await f.service.dispatch(f.command)).messagesSent,0);assert.equal(f.sends(),1);assert.equal((await validateWeeklyNativeSendReceipt(f.store,f.item,{tenantId:'tenant',...scope})).providerMessageId,'mid.actual-native');f.item.provider_receipt={...(f.item.provider_receipt as object),weeklyAuthorityHash:socialRequestHash('forged')};await assert.rejects(validateWeeklyNativeSendReceipt(f.store,f.item,{tenantId:'tenant',...scope}),/authority_changed/);}finally{f.restore();}}});
test('unapproved items, drift and foreign operating scopes stop before any provider operation',async()=>{for(const change of ['approval','scope','source']as const){const f=await fixture();try{if(change==='approval')f.item.approved_at='';if(change==='source')f.source.recipientId='different-native';const command=change==='scope'?{...f.command,expectedScope:{...scope,packageVersion:2}}:f.command;await assert.rejects(f.service.dispatch(command));assert.equal(f.sends(),0);}finally{f.restore();}}});
test('a provider success survives completion projection failure and explicit replay repairs without resending',async()=>{const f=await fixture();try{const task=f.data.workflow_tasks!.find(t=>t.task_key==='followup_dispatch')!;task.depends_on=['missing-real-dependency'];await assert.rejects(f.service.dispatch(f.command),/dependencies_pending/);assert.equal(f.sends(),1);assert.equal(f.item.status,'sent');assert.equal(task.status,'waiting_external');task.depends_on=['followup_batch_approval'];const result=await f.service.dispatch(f.command);assert.equal(result.messagesSent,0);assert.equal(result.originalTaskCompleted,true);assert.equal(f.sends(),1);}finally{f.restore();}});
