import {assertLegacyExternalEffectAllowed,withLegacyExternalEffectAllowed} from '../starter198/legacyEffectGuard.js';
import {createStarter198Repository} from '../starter198/repository.js';
import {createCustomerManualTakeoverService} from '../customerService/customerManualTakeover.js';
import {organizationRoleOrNull} from '../lib/organizationRole.js';
import {readWeeklyCustomerRelationshipScope} from '../socialPrograms/weeklyCustomerRelationshipScope.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import {readWeeklyNativeDispatchAuthority,readWeeklyNativeScheduledDispatchAuthority} from './weeklyNativeSendAuthority.js';
import {createCustomerChannelSendRequestService,readWeeklyNativeSendRequestEvidence} from './customerChannelSendRequests.js';
import {sendTenantMessengerText} from '../messenger/conversations.js';
import {sendTenantInstagramText} from '../instagram/send.js';
import {readCustomerMessagingAuthorization,type CustomerMessagingAuthorization} from './customerMessagingPolicy.js';
import {followupOutcome} from './executionDiagnostics.js';
import {nextFollowupDeliveryWindow} from './followupDispatchWorker.js';
import {withDigitalEmployeeRunLock} from './runControl.js';
import {publicationInstant} from '../socialPrograms/publicationDeadlines.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {guardOutboundSync} from '../autonomy/outboundGuard.js';
import type {WeeklyNativeSendAuthority} from '../../shared/contracts/weeklyNativeSendAuthority.js';
import type {CustomerChannelSendReceipt} from '../../shared/contracts/customerChannelSendRequest.js';
const obj=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return obj(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
function check(v:unknown,c:string):asserts v{if(!v)throw Error(c);}
export const weeklyNativeSendRequestId=(a:WeeklyNativeSendAuthority)=>'weekly-native-'+socialRequestHash(a).slice(0,40);
export interface WeeklyNativeDispatchScope {runId:string;programId:string;packageId:string;packageVersion:number}
function verifyScope(a:WeeklyNativeSendAuthority,s:WeeklyNativeDispatchScope){check(a.runId===s.runId&&a.programId===s.programId&&a.packageId===s.packageId&&a.packageVersion===s.packageVersion,'weekly_native_dispatch_expected_scope_changed');}
export interface WeeklyNativeScheduledDispatchInput {tenantId:string;batchId:string;itemId:string;expectedBatchVersion:number;expectedItemHash:string;expectedScope:WeeklyNativeDispatchScope}
export interface WeeklyNativeDispatchPorts {
 assertScheduledProductAccess:(tenantId:string)=>Promise<void>;
 executeScheduledProductEffect:<T>(tenantId:string,effect:()=>Promise<T>)=>Promise<T>;
 authorization:(tenantId:string,channel:'messenger'|'instagram')=>Promise<CustomerMessagingAuthorization>;
 send:(a:WeeklyNativeSendAuthority,body:string,requestId:string)=>Promise<CustomerChannelSendReceipt>;
 autoPermission:(a:WeeklyNativeSendAuthority,accountHash:string,send:()=>Promise<CustomerChannelSendReceipt>)=>Promise<CustomerChannelSendReceipt>;
 humanPermission:(a:WeeklyNativeSendAuthority,accountHash:string,send:()=>Promise<CustomerChannelSendReceipt>)=>Promise<CustomerChannelSendReceipt>;
 now:()=>Date;
}
function defaultPorts(store:DataStore):WeeklyNativeDispatchPorts{const repository=createStarter198Repository(store);return {assertScheduledProductAccess:tenantId=>assertLegacyExternalEffectAllowed(tenantId,repository),executeScheduledProductEffect:(tenantId,effect)=>withLegacyExternalEffectAllowed(tenantId,effect,repository,store),autoPermission:(a,_accountHash,send)=>createCustomerManualTakeoverService(store).withAutoSendPermission({tenantId:a.tenantId,customerId:a.customerId,channel:a.channel},send),humanPermission:(a,accountHash,send)=>createCustomerManualTakeoverService(store).withHumanSendPermission({tenantId:a.tenantId,customerId:a.customerId,channel:a.channel,actorUserId:a.actorUserId,expectedScope:{accountId:a.accountId,nativeAccountId:a.nativeAccountId,conversationId:a.conversationId,accountHash}},send),authorization:(tenant,channel)=>readCustomerMessagingAuthorization(tenant,channel,{dataStore:store}),send:(a,body,requestId)=>a.channel==='instagram'?sendTenantInstagramText({tenantId:a.tenantId,actorUserId:a.actorUserId,customerId:a.customerId,body,requestId,weeklyAuthority:a}):sendTenantMessengerText({tenantId:a.tenantId,actorUserId:a.actorUserId,customerId:a.customerId,body,requestId,weeklyAuthority:a}),now:()=>new Date()};}
/** Explicit human and internal scheduled single-item execution share the same frozen request and run fence. */
export function createWeeklyNativeFollowupDispatchService(store:DataStore,ports:Partial<WeeklyNativeDispatchPorts>={}){const actual={...defaultPorts(store),...ports};
 async function scheduledPreflight(input:WeeklyNativeScheduledDispatchInput){
  try{
   await actual.assertScheduledProductAccess(input.tenantId);
   const a=await readWeeklyNativeScheduledDispatchAuthority(store,input);verifyScope(a,input.expectedScope);
   check(a.batchVersion===input.expectedBatchVersion&&a.itemHash===input.expectedItemHash,'weekly_native_dispatch_expected_source_changed');
   const item=await store.getById<Record_>('followup_batch_items',a.itemId),batch=await store.getById<Record_>('followup_batches',a.batchId);check(item&&batch,'weekly_native_dispatch_source_missing');
   const now=actual.now(),scheduled=publicationInstant(String(item.scheduled_at));check(Number.isFinite(now.getTime())&&scheduled!==null,'weekly_native_dispatch_schedule_invalid');
   if(scheduled>now.getTime())return {status:'future' as const,code:'weekly_native_dispatch_schedule_not_due',scheduledAt:item.scheduled_at};
   check(typeof item.time_zone==='string'&&item.time_zone&&nextFollowupDeliveryWindow(item.time_zone,batch.delivery_policy,now).getTime()<=now.getTime(),'weekly_native_dispatch_work_window_closed');
   const selection=obj(item.channel_selection),inbound=publicationInstant(selection.inboundAt);check(inbound!==null&&inbound<=now.getTime()&&now.getTime()-inbound<24*60*60*1000,'weekly_native_dispatch_message_window_closed');
   check(item.status==='approved'&&Number.isFinite(Date.parse(String(item.approved_at)))&&!String(item.exclusion_reason??'').trim()&&guardOutboundSync(String(item.draft_body)).allowed,'weekly_native_dispatch_item_not_sendable');
   const auth=await actual.authorization(a.tenantId,a.channel);check(auth.tenantId===a.tenantId&&auth.channel===a.channel&&auth.scheduledFollowupSendAllowed,'weekly_native_dispatch_scheduled_not_authorized');
   return {status:'eligible' as const,code:null,scheduledAt:item.scheduled_at};
  }catch(error){return {status:'blocked' as const,code:error instanceof Error?error.message:'weekly_native_dispatch_preflight_failed',scheduledAt:null};}
 }
 async function dispatchItem(input:WeeklyNativeScheduledDispatchInput&{actorUserId:string},mode:'manual'|'scheduled'){
 const before=await readWeeklyNativeDispatchAuthority(store,input);verifyScope(before,input.expectedScope);check(before.batchVersion===input.expectedBatchVersion&&before.itemHash===input.expectedItemHash,'weekly_native_dispatch_expected_source_changed');return withDigitalEmployeeRunLock(input.tenantId,before.runId,async()=>{const a=await readWeeklyNativeDispatchAuthority(store,input);verifyScope(a,input.expectedScope);check(socialRequestHash(a)===socialRequestHash(before),'weekly_native_dispatch_authority_changed');const item=await store.getById<Record_>('followup_batch_items',a.itemId),batch=await store.getById<Record_>('followup_batches',a.batchId);check(item&&batch,'weekly_native_dispatch_source_missing');const requestId=weeklyNativeSendRequestId(a);
 if(['sent','delivered','read'].includes(String(item.status))){const receipt=await validateWeeklyNativeSendReceipt(store,item,{tenantId:a.tenantId,runId:a.runId,programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion});const completion=await reconcileDispatchTask(store,a);return {itemId:a.itemId,requestId:receipt.requestId,status:'sent' as const,messagesSent:0,...completion};}
 const existing=await createCustomerChannelSendRequestService(store).get(a.tenantId,a.actorUserId,a.channel,requestId);if(existing?.status==='accepted'){check(existing.deliveryStatus!=='failed','weekly_native_dispatch_delivery_failed');await persistItemReceipt(store,a,item,existing.providerMessageId!,requestId,existing);return {itemId:a.itemId,requestId,status:'sent' as const,messagesSent:0,...await reconcileDispatchTask(store,a)};}if(existing)throw Error(existing.recoveryGap??'weekly_native_dispatch_unknown_send');
 const run=await store.getById<Record_>('workflow_runs',a.runId);check(run?.tenant_id===a.tenantId&&['running','waiting_external','waiting_approval'].includes(String(run.status)),'weekly_native_dispatch_run_unavailable');
 const now=actual.now(),scheduled=publicationInstant(String(item.scheduled_at));check(Number.isFinite(now.getTime())&&scheduled!==null&&scheduled<=now.getTime(),'weekly_native_dispatch_schedule_not_due');check(typeof item.time_zone==='string'&&item.time_zone&&nextFollowupDeliveryWindow(item.time_zone,batch.delivery_policy,now).getTime()<=now.getTime(),'weekly_native_dispatch_work_window_closed');const selection=obj(item.channel_selection);check(publicationInstant(selection.inboundAt)!==null&&publicationInstant(selection.inboundAt)!<=now.getTime()&&now.getTime()-publicationInstant(selection.inboundAt)!<24*60*60*1000,'weekly_native_dispatch_message_window_closed');
 const reasons=String(item.exclusion_reason??'').split(/[,;]/).map(s=>s.trim()).filter(Boolean);check(reasons.length===0,'weekly_native_dispatch_other_blockers');check(item.status==='approved'&&Number.isFinite(Date.parse(String(item.approved_at)))&&guardOutboundSync(String(item.draft_body)).allowed,'weekly_native_dispatch_item_not_sendable');const authorization=await actual.authorization(a.tenantId,a.channel);check(authorization.tenantId===a.tenantId&&authorization.channel===a.channel&&(mode==='scheduled'?authorization.scheduledFollowupSendAllowed:authorization.manualFollowupSendAllowed),'weekly_native_dispatch_customer_messages_not_authorized');
 let attempted=false;
 try{const receipt=await (mode==='scheduled'?actual.autoPermission:actual.humanPermission)(a,String(selection.accountHash),async()=>{if(mode==='scheduled'){const latest=await readWeeklyNativeScheduledDispatchAuthority(store,input);check(socialRequestHash(latest)===socialRequestHash(a),'weekly_native_dispatch_authority_changed');const auth=await actual.authorization(a.tenantId,a.channel);check(auth.tenantId===a.tenantId&&auth.channel===a.channel&&auth.scheduledFollowupSendAllowed,'weekly_native_dispatch_scheduled_not_authorized');}check(await store.update('followup_batch_items',item.id,{status:'sending',provider_receipt:{weeklyAuthorityHash:socialRequestHash(a),requestId,dispatchMode:mode},updated_at:now.toISOString()}),'weekly_native_dispatch_attempt_save_failed');attempted=true;return actual.send(a,String(item.draft_body),requestId);});const ledger=await createCustomerChannelSendRequestService(store).get(a.tenantId,a.actorUserId,a.channel,requestId);check(ledger?.status==='accepted'&&ledger.weeklyAuthorityHash===socialRequestHash(a)&&ledger.providerMessageId===receipt.messageId&&receipt.requestId===requestId,'weekly_native_dispatch_real_receipt_pending');await persistItemReceipt(store,a,item,receipt.messageId,requestId,ledger,mode);return {itemId:a.itemId,requestId,status:'sent' as const,messagesSent:1,...await reconcileDispatchTask(store,a)};}catch(error){const persisted=await store.getById<Record_>('followup_batch_items',item.id);if(attempted&&!['sent','delivered','read'].includes(String(persisted?.status)))await store.update('followup_batch_items',item.id,{status:'blocked',exclusion_reason:'send_outcome_unknown',last_error:error instanceof Error?error.message:'weekly_native_dispatch_unknown_send',updated_at:new Date().toISOString()});throw error;}
 });}
 return {
 async sources(tenantId:string,actorUserId:string,runId:string,scope:WeeklyNativeDispatchScope){check(runId===scope.runId,'weekly_native_dispatch_expected_scope_changed');const user=await store.getById<Record_>('users',actorUserId),role=organizationRoleOrNull(user?.role);check(user?.tenantId===tenantId&&role&&['customer_service','admin','super_admin'].includes(role)&&user.disabled!==true&&user.active!==false&&!['disabled','suspended'].includes(String(user.status)),'weekly_native_dispatch_actor_forbidden');const actualScope=await readWeeklyCustomerRelationshipScope(store,tenantId,scope.runId);check(actualScope&&actualScope.programId===scope.programId&&actualScope.packageId===scope.packageId&&actualScope.packageVersion===scope.packageVersion,'weekly_native_dispatch_expected_scope_changed');const batches=await allRows(store,'followup_batches',{tenant_id:tenantId,run_id:scope.runId});const result:Array<{batchId:string;itemId:string;customerId:string;channel:'messenger'|'instagram';expectedBatchVersion:number;expectedItemHash:string;scheduledAt:string|null;status:string;gap:string|null;draftBody:string|null;taskId:string|null;recipientMasked:string|null;accountId:string|null}>=[];for(const batch of batches){const items=await allRows(store,'followup_batch_items',{tenant_id:tenantId,batch_id:batch.id});for(const item of items.filter(i=>['messenger','instagram'].includes(String(i.channel)))){let gap:string|null=null,draftBody:string|null=null,taskId:string|null=null,recipientMasked:string|null=null,accountId:string|null=null;try{const a=await readWeeklyNativeDispatchAuthority(store,{tenantId,actorUserId,batchId:batch.id,itemId:item.id});verifyScope(a,scope);draftBody=String(item.draft_body);accountId=a.accountId;recipientMasked='…'+a.recipientId.slice(-4);const originalTasks=(await allRows(store,'workflow_tasks',{tenant_id:tenantId,run_id:a.runId})).filter(t=>t.task_key==='followup_dispatch'&&t.agent_role==='customer');check(originalTasks.length===1,'weekly_native_dispatch_task_identity_invalid');taskId=originalTasks[0]!.id;const requestId=typeof obj(item.provider_receipt).requestId==='string'?obj(item.provider_receipt).requestId:weeklyNativeSendRequestId(a);const evidence=await readWeeklyNativeSendRequestEvidence(store,{tenantId,channel:a.channel,requestId});if(evidence)gap=evidence.request.status==='accepted'?'weekly_native_dispatch_readonly_reconciliation_required':'weekly_native_dispatch_unknown_send';}catch(error){gap=error instanceof Error&&error.message.startsWith('weekly_')?error.message:'weekly_native_dispatch_source_unverified';}result.push({batchId:batch.id,itemId:item.id,customerId:String(item.customer_id),channel:item.channel as 'messenger'|'instagram',expectedBatchVersion:Number(batch.version),expectedItemHash:String(item.content_hash),scheduledAt:publicationInstant(String(item.scheduled_at))!==null?String(item.scheduled_at):null,status:String(item.status),gap,draftBody,taskId,recipientMasked,accountId});}}return result;},
 preflightScheduled:scheduledPreflight,
 async dispatchScheduled(input:WeeklyNativeScheduledDispatchInput){await actual.assertScheduledProductAccess(input.tenantId);return actual.executeScheduledProductEffect(input.tenantId,async()=>{const a=await readWeeklyNativeScheduledDispatchAuthority(store,input);return dispatchItem({...input,actorUserId:a.actorUserId},'scheduled');});},
 async dispatch(input:WeeklyNativeScheduledDispatchInput&{actorUserId:string}){return dispatchItem(input,'manual');}
 };}
async function persistItemReceipt(store:DataStore,a:WeeklyNativeSendAuthority,item:Record_,messageId:string,requestId:string,ledger:{settledAt:string|null;deliveryStatus:string;weeklyAuthorityHash?:string},dispatchMode?:'manual'|'scheduled'){check(ledger.weeklyAuthorityHash===socialRequestHash(a)&&ledger.settledAt&&publicationInstant(ledger.settledAt)!==null&&messageId,'weekly_native_dispatch_ledger_identity_invalid');check(await store.update('followup_batch_items',item.id,{status:remainingSendBlockers(item)?'blocked':'sent',exclusion_reason:remainingSendBlockers(item),provider_message_id:messageId,provider_receipt:{requestId,channel:a.channel,weeklyAuthorityHash:socialRequestHash(a),weeklyAuthority:a,providerMessageId:messageId,deliveryStatus:ledger.deliveryStatus,dispatchMode:dispatchMode??obj(item.provider_receipt).dispatchMode??'manual'},sent_at:ledger.settledAt,updated_at:new Date().toISOString()}),'weekly_native_dispatch_receipt_save_failed');}
/** Read only. A direct private-message success without this exact weekly authority is insufficient. */
export async function validateWeeklyNativeSendReceipt(store:DataStore,item:Record_,scope:{tenantId:string;runId:string;programId:string;packageId:string;packageVersion:number}){
 const r=obj(item.provider_receipt),frozen=obj(r.weeklyAuthority) as WeeklyNativeSendAuthority;check(frozen.tenantId===scope.tenantId&&frozen.runId===scope.runId&&frozen.programId===scope.programId&&frozen.packageId===scope.packageId&&frozen.packageVersion===scope.packageVersion,'weekly_native_dispatch_receipt_scope_invalid');const live=await readWeeklyNativeDispatchAuthority(store,{tenantId:scope.tenantId,actorUserId:frozen.actorUserId,batchId:String(item.batch_id),itemId:item.id});check(socialRequestHash(live)===r.weeklyAuthorityHash&&socialRequestHash(live)===socialRequestHash(frozen)&&r.requestId===weeklyNativeSendRequestId(live),'weekly_native_dispatch_receipt_authority_changed');const ledger=await createCustomerChannelSendRequestService(store).get(live.tenantId,live.actorUserId,live.channel,r.requestId);check(ledger?.status==='accepted'&&ledger.deliveryStatus!=='failed'&&ledger.weeklyAuthorityHash===r.weeklyAuthorityHash&&ledger.providerMessageId===item.provider_message_id&&item.sent_at===ledger.settledAt&&['sent','delivered','read'].includes(String(item.status)),'weekly_native_dispatch_receipt_unverified');return {requestId:r.requestId,providerMessageId:ledger.providerMessageId,weeklyAuthorityHash:r.weeklyAuthorityHash};
}

async function allRows(store:DataStore,collection:string,where:Record<string,string>){const found:Record_[]=[];let total:number|undefined;for(let page=1;page<=1000;page++){const r=await store.list<Record_>(collection,{where,page,perPage:250,sort:'id'});check(Number.isSafeInteger(r.totalItems)&&r.totalItems>=0&&(total===undefined||total===r.totalItems),'weekly_native_dispatch_sources_incomplete');total=r.totalItems;check(r.items.every(row=>Object.entries(where).every(([k,v])=>row[k]===v)&&!found.some(old=>old.id===row.id)),'weekly_native_dispatch_sources_invalid');found.push(...r.items);if(found.length===total)return found;check(r.items.length===250,'weekly_native_dispatch_sources_incomplete');}throw Error('weekly_native_dispatch_sources_incomplete');}

/** No run advancement: only the original dispatch task can settle after every current batch item has actual proof. */
async function reconcileDispatchTask(store:DataStore,a:WeeklyNativeSendAuthority){const {readWeeklyCustomerStep}=await import('../runtime/socialWeeklyCustomerBridge.js');const proof=await readWeeklyCustomerStep(store,{tenantId:a.tenantId,programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion},a.runId,'customer_followup_dispatch');if(proof.status!=='succeeded'&&proof.reason!=='weekly_customer_dispatch_pending')return {originalTaskCompleted:false,completionGap:proof.reason,runAdvanced:false as const};const tasks=await allRows(store,'workflow_tasks',{tenant_id:a.tenantId,run_id:a.runId}),matches=tasks.filter(t=>t.task_key==='followup_dispatch'&&t.agent_role==='customer');check(matches.length===1,'weekly_native_dispatch_task_identity_invalid');const task=matches[0]!;if(task.status==='succeeded'){await settleNativeBatchProjection(store,a);return {originalTaskCompleted:true,completionGap:null,runAdvanced:false as const};}check(!['running','cancelled','skipped','failed'].includes(String(task.status))&&!task.lease_token,'weekly_native_dispatch_task_not_recoverable');let deps:unknown=task.depends_on??[];if(typeof deps==='string'){try{deps=JSON.parse(deps);}catch{throw Error('weekly_native_dispatch_dependencies_invalid');}}check(Array.isArray(deps)&&deps.every(key=>typeof key==='string'&&tasks.filter(t=>t.task_key===key).length===1&&['succeeded','skipped'].includes(String(tasks.find(t=>t.task_key===key)?.status))),'weekly_native_dispatch_dependencies_pending');check(await store.update('workflow_tasks',task.id,{status:'succeeded',blocked_reason:'',business_refs:proof.resultRefs,output:{...obj(task.output),nativeDispatch:{batchId:a.batchId,source:'actual_weekly_channel_provider_requests',runAdvanced:false},dataStatus:'verified'},updated_at:new Date().toISOString()}),'weekly_native_dispatch_task_save_failed');await settleNativeBatchProjection(store,a);return {originalTaskCompleted:true,completionGap:null,runAdvanced:false as const};}

function remainingSendBlockers(item:Record_){return String(item.exclusion_reason??'').split(/[,;]/).map(v=>v.trim()).filter(v=>v&&v!=='send_outcome_unknown').join(';');}

/** Internal explicit recovery only; never invokes a provider or changes the frozen original sending actor. */
export async function reconcileWeeklyNativeAcceptedRequest(store:DataStore,input:{tenantId:string;channel:'messenger'|'instagram';requestId:string;expectedScope:WeeklyNativeDispatchScope}){const evidence=await readWeeklyNativeSendRequestEvidence(store,input);check(evidence,'weekly_native_recovery_request_missing');verifyScope(evidence.authority,input.expectedScope);return withDigitalEmployeeRunLock(input.tenantId,evidence.authority.runId,async()=>{const fresh=await readWeeklyNativeSendRequestEvidence(store,input);check(fresh&&fresh.intentHash===evidence.intentHash&&fresh.request.status==='accepted'&&fresh.request.deliveryStatus!=='failed'&&!fresh.request.historyWritebackPending,'weekly_native_recovery_accepted_receipt_required');const item=await store.getById<Record_>('followup_batch_items',fresh.authority.itemId);check(item,'weekly_native_recovery_item_missing');await persistItemReceipt(store,fresh.authority,item,fresh.request.providerMessageId!,input.requestId,fresh.request);const completion=await reconcileDispatchTask(store,fresh.authority);return {...completion,messagesSent:0 as const};});}

/** Batch completion follows original-task completion and reverified mixed-channel receipts, never transport acceptance alone. */
async function settleNativeBatchProjection(store:DataStore,a:WeeklyNativeSendAuthority){
 const {readWeeklyCustomerStep}=await import('../runtime/socialWeeklyCustomerBridge.js');
 const proof=await readWeeklyCustomerStep(store,{tenantId:a.tenantId,programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion},a.runId,'customer_followup_dispatch');
 check(proof.status==='succeeded'&&proof.resultRefs.some(ref=>ref.type==='weekly_customer_followup_batch'&&ref.id===a.batchId&&ref.version===a.batchVersion),'weekly_native_dispatch_batch_completion_proof_pending');
 const batch=await store.getById<Record_>('followup_batches',a.batchId);check(batch?.tenant_id===a.tenantId&&batch.run_id===a.runId&&batch.version===a.batchVersion&&batch.content_hash===a.batchHash,'weekly_native_dispatch_batch_projection_source_changed');
 const items=await allRows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:a.batchId});
 check(followupOutcome(items).complete,'weekly_native_dispatch_batch_outcome_pending');
 const count=(statuses:string[])=>items.filter(item=>statuses.includes(String(item.status))).length;
 const counts={total:items.length,draft:count(['draft']),blocked:count(['blocked']),approved:count(['approved']),sending:count(['sending']),retryWaiting:count(['retry_wait']),partial:count(['partial_sent']),sent:count(['sent','delivered','read']),delivered:count(['delivered','read']),read:count(['read']),failed:count(['failed'])};
 check(await store.update('followup_batches',batch.id,{counts,status:'completed',updated_at:new Date().toISOString()}),'weekly_native_dispatch_batch_projection_save_failed');
}
