import type {DataStore,Record_} from '../storage/datastore.js';
import {readWeeklyNativeDispatchAuthority} from './weeklyNativeSendAuthority.js';
import {createCustomerChannelSendRequestService} from './customerChannelSendRequests.js';
import {sendTenantMessengerText} from '../messenger/conversations.js';
import {sendTenantInstagramText} from '../instagram/send.js';
import {readCustomerMessagingAuthorization,type CustomerMessagingAuthorization} from './customerMessagingPolicy.js';
import {nextFollowupDeliveryWindow} from './followupDispatchWorker.js';
import {withDigitalEmployeeRunLock} from './runControl.js';
import {publicationInstant} from '../socialPrograms/publicationDeadlines.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {guardOutboundSync} from '../autonomy/outboundGuard.js';
import type {WeeklyNativeSendAuthority} from '../../shared/contracts/weeklyNativeSendAuthority.js';
import type {CustomerChannelSendReceipt} from '../../shared/contracts/customerChannelSendRequest.js';
const obj=(v:unknown):Record<string,any>=>{if(typeof v==='string'){try{return obj(JSON.parse(v));}catch{return {};}}return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:{};};
function check(v:unknown,c:string):asserts v{if(!v)throw Error(c);}
export const weeklyNativeSendRequestId=(a:WeeklyNativeSendAuthority)=>'weekly-native-'+socialRequestHash(a).slice(0,40);
export interface WeeklyNativeDispatchPorts {
 authorization:(tenantId:string,channel:'messenger'|'instagram')=>Promise<CustomerMessagingAuthorization>;
 send:(a:WeeklyNativeSendAuthority,body:string,requestId:string)=>Promise<CustomerChannelSendReceipt>;
 now:()=>Date;
}
function defaultPorts():WeeklyNativeDispatchPorts{return {authorization:(tenant,channel)=>readCustomerMessagingAuthorization(tenant,channel),send:(a,body,requestId)=>a.channel==='instagram'?sendTenantInstagramText({tenantId:a.tenantId,actorUserId:a.actorUserId,customerId:a.customerId,body,requestId,weeklyAuthority:a}):sendTenantMessengerText({tenantId:a.tenantId,actorUserId:a.actorUserId,customerId:a.customerId,body,requestId,weeklyAuthority:a}),now:()=>new Date()};}
/** Explicit single-item human action. Never scans or automatically sends native-channel drafts. */
export function createWeeklyNativeFollowupDispatchService(store:DataStore,ports:Partial<WeeklyNativeDispatchPorts>={}){const actual={...defaultPorts(),...ports};return {
 async sources(tenantId:string,actorUserId:string,runId:string){const user=await store.getById<Record_>('users',actorUserId);check(user?.tenantId===tenantId,'weekly_native_dispatch_actor_forbidden');const batches=await store.list<Record_>('followup_batches',{where:{tenant_id:tenantId,run_id:runId},page:1,perPage:250});check(batches.totalItems===batches.items.length,'weekly_native_dispatch_sources_incomplete');const result:Array<{batchId:string;itemId:string;customerId:string;channel:'messenger'|'instagram';expectedBatchVersion:number;expectedItemHash:string;scheduledAt:string|null;status:string;gap:string|null}>=[];for(const batch of batches.items){const items=await store.list<Record_>('followup_batch_items',{where:{tenant_id:tenantId,batch_id:batch.id},page:1,perPage:250});check(items.totalItems===items.items.length,'weekly_native_dispatch_sources_incomplete');for(const item of items.items.filter(i=>['messenger','instagram'].includes(String(i.channel)))){let gap:string|null=null;try{await readWeeklyNativeDispatchAuthority(store,{tenantId,actorUserId,batchId:batch.id,itemId:item.id});}catch(error){gap=error instanceof Error?error.message:'weekly_native_dispatch_source_unverified';}result.push({batchId:batch.id,itemId:item.id,customerId:String(item.customer_id),channel:item.channel as 'messenger'|'instagram',expectedBatchVersion:Number(batch.version),expectedItemHash:String(item.content_hash),scheduledAt:publicationInstant(String(item.scheduled_at))!==null?String(item.scheduled_at):null,status:String(item.status),gap});}}return result;},
 async dispatch(input:{tenantId:string;actorUserId:string;batchId:string;itemId:string;expectedBatchVersion:number;expectedItemHash:string}){
 const before=await readWeeklyNativeDispatchAuthority(store,input);check(before.batchVersion===input.expectedBatchVersion&&before.itemHash===input.expectedItemHash,'weekly_native_dispatch_expected_source_changed');return withDigitalEmployeeRunLock(input.tenantId,before.runId,async()=>{const a=await readWeeklyNativeDispatchAuthority(store,input);check(socialRequestHash(a)===socialRequestHash(before),'weekly_native_dispatch_authority_changed');const item=await store.getById<Record_>('followup_batch_items',a.itemId),batch=await store.getById<Record_>('followup_batches',a.batchId);check(item&&batch,'weekly_native_dispatch_source_missing');const requestId=weeklyNativeSendRequestId(a);
 const existing=await createCustomerChannelSendRequestService(store).get(a.tenantId,a.actorUserId,a.channel,requestId);if(existing?.status==='accepted'){await persistItemReceipt(store,a,item,existing.providerMessageId!,requestId,existing);return {itemId:a.itemId,requestId,status:'sent' as const,messagesSent:0};}if(existing)throw Error(existing.recoveryGap??'weekly_native_dispatch_unknown_send');
 const now=actual.now(),scheduled=publicationInstant(String(item.scheduled_at));check(Number.isFinite(now.getTime())&&scheduled!==null&&scheduled<=now.getTime(),'weekly_native_dispatch_schedule_not_due');check(typeof item.time_zone==='string'&&item.time_zone&&nextFollowupDeliveryWindow(item.time_zone,batch.delivery_policy,now).getTime()<=now.getTime(),'weekly_native_dispatch_work_window_closed');const selection=obj(item.channel_selection);check(publicationInstant(selection.inboundAt)!==null&&now.getTime()-publicationInstant(selection.inboundAt)!<=24*60*60*1000,'weekly_native_dispatch_message_window_closed');
 const reasons=String(item.exclusion_reason??'').split(/[,;]/).map(s=>s.trim()).filter(Boolean);check(reasons.every(r=>r==='weekly_native_channel_dispatch_not_connected'),'weekly_native_dispatch_other_blockers');check(['approved','blocked'].includes(String(item.status))&&guardOutboundSync(String(item.draft_body)).allowed,'weekly_native_dispatch_item_not_sendable');const authorization=await actual.authorization(a.tenantId,a.channel);check(authorization.tenantId===a.tenantId&&authorization.channel===a.channel&&authorization.manualFollowupSendAllowed,'weekly_native_dispatch_customer_messages_not_authorized');
 check(await store.update('followup_batch_items',item.id,{status:'sending',provider_receipt:{weeklyAuthorityHash:socialRequestHash(a),requestId},updated_at:now.toISOString()}),'weekly_native_dispatch_attempt_save_failed');
 try{const receipt=await actual.send(a,String(item.draft_body),requestId);const ledger=await createCustomerChannelSendRequestService(store).get(a.tenantId,a.actorUserId,a.channel,requestId);check(ledger?.status==='accepted'&&ledger.weeklyAuthorityHash===socialRequestHash(a)&&ledger.providerMessageId===receipt.messageId&&receipt.requestId===requestId,'weekly_native_dispatch_real_receipt_pending');await persistItemReceipt(store,a,item,receipt.messageId,requestId,ledger);return {itemId:a.itemId,requestId,status:'sent' as const,messagesSent:1};}catch(error){await store.update('followup_batch_items',item.id,{status:'blocked',exclusion_reason:'send_outcome_unknown',last_error:error instanceof Error?error.message:'weekly_native_dispatch_unknown_send',updated_at:new Date().toISOString()});throw error;}
 });}
};}
async function persistItemReceipt(store:DataStore,a:WeeklyNativeSendAuthority,item:Record_,messageId:string,requestId:string,ledger:{settledAt:string|null;deliveryStatus:string;weeklyAuthorityHash?:string}){check(ledger.weeklyAuthorityHash===socialRequestHash(a)&&ledger.settledAt&&publicationInstant(ledger.settledAt)!==null&&messageId,'weekly_native_dispatch_ledger_identity_invalid');check(await store.update('followup_batch_items',item.id,{status:'sent',exclusion_reason:'',provider_message_id:messageId,provider_receipt:{requestId,channel:a.channel,weeklyAuthorityHash:socialRequestHash(a),weeklyAuthority:a,providerMessageId:messageId,deliveryStatus:ledger.deliveryStatus},sent_at:ledger.settledAt,updated_at:new Date().toISOString()}),'weekly_native_dispatch_receipt_save_failed');}
/** Read only. A direct private-message success without this exact weekly authority is insufficient. */
export async function validateWeeklyNativeSendReceipt(store:DataStore,item:Record_,scope:{tenantId:string;runId:string;programId:string;packageId:string;packageVersion:number}){
 const r=obj(item.provider_receipt),frozen=obj(r.weeklyAuthority) as WeeklyNativeSendAuthority;check(frozen.tenantId===scope.tenantId&&frozen.runId===scope.runId&&frozen.programId===scope.programId&&frozen.packageId===scope.packageId&&frozen.packageVersion===scope.packageVersion,'weekly_native_dispatch_receipt_scope_invalid');const live=await readWeeklyNativeDispatchAuthority(store,{tenantId:scope.tenantId,actorUserId:frozen.actorUserId,batchId:String(item.batch_id),itemId:item.id});check(socialRequestHash(live)===r.weeklyAuthorityHash&&socialRequestHash(live)===socialRequestHash(frozen)&&r.requestId===weeklyNativeSendRequestId(live),'weekly_native_dispatch_receipt_authority_changed');const ledger=await createCustomerChannelSendRequestService(store).get(live.tenantId,live.actorUserId,live.channel,r.requestId);check(ledger?.status==='accepted'&&ledger.weeklyAuthorityHash===r.weeklyAuthorityHash&&ledger.providerMessageId===item.provider_message_id&&item.sent_at===ledger.settledAt&&['sent','delivered','read'].includes(String(item.status)),'weekly_native_dispatch_receipt_unverified');return {requestId:r.requestId,providerMessageId:ledger.providerMessageId,weeklyAuthorityHash:r.weeklyAuthorityHash};
}
