const labels = { running: '进行中', succeeded: '已完成', failed: '失败', waiting_approval: '待确认', waiting_external: '等待外部结果', waiting_review: '待验收', producing: '制作中', planned: '已计划', queued: '排队中', blocked: '受阻', pending: '待开始', idle: '空闲', completed: '已完成', handed_off: '等待人工', cancelled: '已取消', skipped: '已跳过', published: '已发布', scheduled: '已排期' };
const roles = { orchestrator: '灵小枢', customer: '客服 Agent', business: '经营 Agent', director: '编导 Agent', content: '内容 Agent', customer_service: '客服 Agent', strategy: '经营 Agent', traffic: '流量 Agent', conversion: '销售 Agent', retention: '客户 Agent' };
function day(value) { const n = Date.parse(value); return Number.isFinite(n) ? new Date(n + 8 * 3600000).toISOString().slice(0, 10) : ''; }
function week(now = Date.now(), offset = 0) { const date = new Date(now + 8 * 3600000); const weekday = (date.getUTCDay() + 6) % 7; date.setUTCDate(date.getUTCDate() - weekday + offset * 7); const start = date.toISOString().slice(0, 10); const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(date); d.setUTCDate(d.getUTCDate() + i); return { date: d.toISOString().slice(0, 10), label: ['一', '二', '三', '四', '五', '六', '日'][i], number: d.getUTCDate() }; }); return { start, end: days[6].date, days }; }
function sortUrgency(items, now = Date.now()) { const rank = { urgent: 0, critical: 0, high: 1, medium: 2, normal: 2, low: 3 }; return [...items].sort((a, b) => { const overdue = x => Number.isFinite(Date.parse(x.dueAt)) && Date.parse(x.dueAt) < now ? 0 : 1; return overdue(a) - overdue(b) || (rank[a.priority] ?? 2) - (rank[b.priority] ?? 2) || (Date.parse(a.dueAt) || Infinity) - (Date.parse(b.dueAt) || Infinity) || (Date.parse(a.createdAt) || 0) - (Date.parse(b.createdAt) || 0) || String(a.id).localeCompare(String(b.id)); }); }
function swipe(dx, dy) { return Math.abs(dx) >= 85 && Math.abs(dx) > Math.abs(dy) * 1.4 ? dx > 0 ? 'process' : 'later' : ''; }
function taskView(t) { return { ...t, statusLabel: labels[t.status] || t.status || '未知', agentLabel: roles[t.agent_role] || t.agent_role || '未指定', reason: t.blocked_reason || t.description || '', date: day(t.due_at || t.output?.scheduledAt) }; }
function matters(overview, shooting) { const tasks = overview.tasks || []; const items = (overview.approvals || []).filter(a => a.status === 'pending').map(a => { const t = tasks.find(t => t.id === a.task_id); return { id: 'approval:' + a.id, title: t?.title || '任务待确认', reason: a.action_summary, type: 'approval', approval: a, task: t && taskView(t), priority: a.risk_level === 'high' ? 'high' : t?.priority, dueAt: t?.due_at || t?.output?.dueAt, createdAt: a.created_at, action: '查看并确认' }; }); tasks.filter(t => ['failed', 'handed_off'].includes(t.status)).forEach(t => items.push({ id: 'task:' + t.id, title: t.title, reason: t.blocked_reason || '需要人工处理', type: 'task', task: taskView(t), priority: t.priority, dueAt: t.due_at || t.output?.dueAt, createdAt: t.updated_at, action: '查看处理方式' })); shooting.filter(t => !t.uploadedMaterialIds?.length).forEach(t => items.push({ id: 'shoot:' + t.id, title: t.title, reason: t.shotBrief, type: 'shoot', shootingId: t.id, priority: t.priority || 'normal', dueAt: t.dueAt, createdAt: t.createdAt, action: '拍摄或补素材' })); return sortUrgency(items); }
module.exports = { labels, roles, day, week, sortUrgency, swipe, taskView, matters };

