const labels = { running: '进行中', succeeded: '已完成', failed: '失败', waiting_approval: '待确认', waiting_external: '等待外部结果', waiting_review: '待验收', producing: '制作中', planned: '已计划', queued: '排队中', blocked: '受阻', pending: '待开始', idle: '空闲', completed: '已完成', handed_off: '等待人工', cancelled: '已取消', skipped: '已跳过', published: '已发布', scheduled: '已排期' };
const roles = { orchestrator: '灵小枢', customer: '客服 Agent', business: '经营 Agent', director: '编导 Agent', content: '内容 Agent', customer_service: '客服 Agent', strategy: '经营 Agent', traffic: '流量 Agent', conversion: '销售 Agent', retention: '客户 Agent' };
function day(value) { const n = Date.parse(value); return Number.isFinite(n) ? new Date(n + 8 * 3600000).toISOString().slice(0, 10) : ''; }
function time(value) { const n = Date.parse(value); if (!Number.isFinite(n)) return '时间待定'; const d = new Date(n + 8 * 3600000); return String(d.getUTCHours()).padStart(2, '0') + ':' + String(d.getUTCMinutes()).padStart(2, '0'); }
function scheduleNextAction(post) { const status = String(post?.status || ''); if (['failed','partial'].includes(status)) return '查看失败原因并重试'; if (status === 'awaiting_reapproval') return '重新审核发布内容'; if (status === 'awaiting_manual_publish') return '下载发布包并回填链接'; if (['needs_attention','finalize_pending'].includes(status)) return '核对平台回执'; if (status === 'scheduled') return '确认内容与发布时间'; if (status === 'published') return '查看回执与业务结果'; return '查看当前节点'; }
function week(now = Date.now(), offset = 0) { const date = new Date(now + 8 * 3600000); const weekday = (date.getUTCDay() + 6) % 7; date.setUTCDate(date.getUTCDate() - weekday + offset * 7); const start = date.toISOString().slice(0, 10); const days = Array.from({ length: 7 }, (_, i) => { const d = new Date(date); d.setUTCDate(d.getUTCDate() + i); return { date: d.toISOString().slice(0, 10), label: ['一', '二', '三', '四', '五', '六', '日'][i], number: d.getUTCDate() }; }); return { start, end: days[6].date, days }; }
function sortUrgency(items, now = Date.now()) { const rank = { urgent: 0, critical: 0, high: 1, medium: 2, normal: 2, low: 3 }; return [...items].sort((a, b) => { const overdue = x => Number.isFinite(Date.parse(x.dueAt)) && Date.parse(x.dueAt) < now ? 0 : 1; return overdue(a) - overdue(b) || (rank[a.priority] ?? 2) - (rank[b.priority] ?? 2) || (Date.parse(a.dueAt) || Infinity) - (Date.parse(b.dueAt) || Infinity) || (Date.parse(a.createdAt) || 0) - (Date.parse(b.createdAt) || 0) || String(a.id).localeCompare(String(b.id)); }); }
function swipe(dx, dy) { return Math.abs(dx) >= 85 && Math.abs(dx) > Math.abs(dy) * 1.4 ? dx > 0 ? 'process' : 'later' : ''; }
function taskView(t) { return { ...t, statusLabel: labels[t.status] || t.status || '未知', agentLabel: roles[t.agent_role] || t.agent_role || '未指定', reason: t.blocked_reason || t.description || '', date: day(t.due_at || t.output?.scheduledAt) }; }
function actionRoute(item) {
  if (item.type === 'approval') return { title: '确认后让 Agent 继续', cta: '审核并决定', steps: ['核对本次要执行的内容与影响', '选择批准，或写明原因退回', 'Agent 按决定继续，工作页跟踪结果'] };
  if (item.type === 'shoot') return { title: '补齐素材后继续制作', cta: '去拍摄上传', steps: ['查看缺少的镜头和拍摄要求', '拍摄或从相册上传素材', '上传成功后 Agent 自动继续制作'] };
  if (item.task?.status === 'failed') return { title: '排除阻塞后重试', cta: '查看原因并重试', steps: ['查看失败原因和最后一次执行记录', '确认账号授权、素材或依赖已恢复', '提交重试，回到工作页跟踪结果'] };
  if (item.task?.status === 'handed_off') return { title: '补充 Agent 无法决定的信息', cta: '查看并补充指令', steps: ['查看 Agent 停下的原因和所需信息', '向助手补充目标、选项或约束', '提交指令后跟踪 Agent 是否恢复'] };
  return { title: '完成当前所需操作', cta: '查看处理路线', steps: ['查看阻塞原因', '完成页面提示的操作', '回到工作页确认结果'] };
}
function withRoute(item) { const route = actionRoute(item); return { ...item, action: route.cta, route }; }
function matters(overview, shooting) { const tasks = overview.tasks || []; const items = (overview.approvals || []).filter(a => a.status === 'pending').map(a => { const t = tasks.find(t => t.id === a.task_id); return withRoute({ id: 'approval:' + a.id, title: t?.title || '任务待确认', reason: a.action_summary, type: 'approval', approval: a, task: t && taskView(t), priority: a.risk_level === 'high' ? 'high' : t?.priority, dueAt: t?.due_at || t?.output?.dueAt, createdAt: a.created_at }); }); tasks.filter(t => ['failed', 'handed_off'].includes(t.status)).forEach(t => items.push(withRoute({ id: 'task:' + t.id, title: t.title, reason: t.blocked_reason || '需要人工处理', type: 'task', task: taskView(t), priority: t.priority, dueAt: t.due_at || t.output?.dueAt, createdAt: t.updated_at }))); shooting.filter(t => !t.uploadedMaterialIds?.length).forEach(t => items.push(withRoute({ id: 'shoot:' + t.id, title: t.title, reason: t.shotBrief, type: 'shoot', shootingId: t.id, priority: t.priority || 'normal', dueAt: t.dueAt, createdAt: t.createdAt }))); return sortUrgency(items); }
module.exports = { labels, roles, day, time, week, sortUrgency, swipe, taskView, scheduleNextAction, actionRoute, withRoute, matters };
