import test from 'node:test';
import assert from 'node:assert/strict';
import {validateInstagramEvidence,validatePublicationEvidence} from './provider.mjs';
const h='a'.repeat(64),scope={tenantId:'tenant',accountId:'account',accountVersion:2,accountIdentityHash:h};
const now='2026-10-10T12:00:00Z';
function instagram(){return {now,scope:{...scope},account:{...scope,platform:'instagram',status:'connected',providerAccountId:'native-account',oauthProvider:'instagram_login',tokenKind:'instagram_user',graphHost:'https://graph.instagram.com',scopes:['instagram_business_basic','instagram_business_manage_messages'],tokenRef:h,tokenExpiresAt:'2026-10-11T12:00:00Z'},professionalAccount:{...scope,source:'provider_read',provider:'meta',accountType:'BUSINESS',providerAccountId:'native-account',receiptRef:'private-read',rawReceiptHash:h,observedAt:now},recipient:{...scope,source:'signed_webhook',verifiedSignature:true,signedBodyHash:h,eventHash:h,inboundMessageId:'private-message',recipientId:'private-recipient',direction:'inbound',providerAccountId:'native-account',inboundAt:now}};}
function publication(){const x=instagram();x.account={...x.account,platform:'tiktok',scopes:['video.publish']};x.receiptId='private-receipt';x.capabilityReceipts=['publishing.official','publishing.receipt_lookup'].map(capability=>({tenant_id:scope.tenantId,account_id:scope.accountId,account_version:scope.accountVersion,account_identity_hash:h,platform:'tiktok',capability,status:'verified',evidence_source:'provider_probe',evidence_ref:capability==='publishing.official'?'provider:tiktok:account:native-account':'provider:tiktok:receipt:private-receipt',provider_receipt_id:'private-receipt',verified_at:now,expires_at:'2026-10-10T12:15:00Z',raw_receipt_hash:h,receipt_ref:'private-receipt-ref'}));return x;}
test('complete offline Instagram evidence checks contract without claiming provider truth',()=>{const r=validateInstagramEvidence(instagram());assert.equal(r.status,'missing');assert.equal(r.summary.providerVerified,false);assert.equal(r.summary.dryRun,true);assert.ok(!JSON.stringify(r).includes('private-recipient'));});
test('missing evidence differs from malformed or drifted evidence',()=>{assert.equal(validateInstagramEvidence().status,'missing');for(const mutate of [x=>x.recipient.accountVersion++,x=>x.professionalAccount.providerAccountId='foreign',x=>x.recipient.verifiedSignature=false,x=>x.recipient.inboundAt='2026-10-09T11:00:00Z',x=>x.account.graphHost='https://graph.facebook.com',x=>x.account.accessToken='PRIVATE_TOKEN_SENTINEL']){const x=instagram();mutate(x);assert.equal(validateInstagramEvidence(x).status,'failed');assert.ok(!JSON.stringify(validateInstagramEvidence(x)).includes('PRIVATE_TOKEN_SENTINEL'));}});
test('publication token and exact receipt-bound fresh capability contract passes offline',()=>{assert.equal(validatePublicationEvidence(publication()).status,'missing');});
test('publication rejects wrong receipt, duplicate, stale, operator, tenant and hash drift',()=>{for(const mutate of [x=>x.receiptId='foreign',x=>x.capabilityReceipts.push({...x.capabilityReceipts[0]}),x=>x.capabilityReceipts[0].expires_at=now,x=>x.capabilityReceipts[0].evidence_source='operator_review',x=>x.capabilityReceipts[0].tenant_id='foreign',x=>x.capabilityReceipts[0].account_identity_hash='b'.repeat(64),x=>x.account.tokenExpiresAt=now,x=>x.account.scopes={}]){const x=publication();mutate(x);assert.equal(validatePublicationEvidence(x).status,'failed');}});
test('Instagram publication requires publishing permission distinct from messaging',()=>{const x=instagram();x.capabilityReceipts=[{...publication().capabilityReceipts[0],platform:'instagram',evidence_ref:'provider:instagram:account:native-account'}];assert.equal(validatePublicationEvidence(x).status,'failed');x.account.scopes.push('instagram_business_content_publish');assert.equal(validatePublicationEvidence(x).status,'missing');});
