import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import axios from 'axios';
import {IncomingMessage,ServerResponse} from 'node:http';
import {Socket} from 'node:net';
process.env.NODE_ENV='test';process.env.TEST_ONLY_EXTERNAL_EFFECT_LEASE_FALLBACK='true';process.env.ENABLE_LOCAL_DEV_FALLBACK='true';process.env.TENANT_PLATFORM_APP_KEY='controlled-whatsapp-key';
const [{store},{mountWhatsAppOAuthRoutes},{issueLocalIdentityTokenForTest},{whatsappAssetAuthorityHash},{assertWhatsAppSendBoundary},{sendWhatsAppText,sendWhatsAppImage},{encryptSecret}]=await Promise.all([import('../storage/index.js'),import('../routes/whatsappParentMount.js'),import('../auth/localIdentity.js'),import('./assetAuthority.js'),import('./sendBoundary.js'),import('../integrations/whatsapp.js'),import('../lib/tenantPlatformApps.js')]);
import type {Record_} from '../storage/datastore.js';
import type {TenantPlatformAppRecord} from '../lib/tenantPlatformApps.js';
test('production parent OAuth and native send boundary reject foreign assets, revoked authority and mismatched receipts without network',async()=>{
 const old={list:store.list,get:store.getById,update:store.update,create:store.create,axiosGet:axios.get,axiosPost:axios.post,fetch:globalThis.fetch,connect:Socket.prototype.connect};let deniedNetwork=0;let mode='valid';let calls=0;
 globalThis.fetch=async()=>{deniedNetwork++;throw Error('network_denied');};Socket.prototype.connect=function(){deniedNetwork++;throw Error('network_denied');};
 const account:TenantPlatformAppRecord={id:'app',tenant_id:'tenant',platform:'meta',app_id:'app-native',app_secret:encryptSecret('secret'),wa_config_id:'config',waba_id:'waba',phone_number_id:'phone',access_token:encryptSecret('token'),status:'active'};
 const refreshProof=()=>{account.last_checklist=JSON.stringify({whatsappAssetProof:{authorityHash:whatsappAssetAuthorityHash(account),verifiedAt:new Date().toISOString()}});};refreshProof();
 const rows:Record<string,Record_[]>={tenant_platform_apps:[account as unknown as Record_],digital_employee_configs:[{id:'cfg',tenant_id:'tenant',status:'active',config_version:1,config:{enabledWorkflows:['batch_followup'],allowRealCustomerMessages:true}}],whatsapp_interactions:[{id:'in',tenant_id:'tenant',payload:{tenantId:'tenant',type:'msg_in',waNumber:'15551234567',metaMessageId:'wamid.in',timestamp:Date.now(),audit:{inboundSource:'verified_meta_webhook',providerMessageId:'wamid.in',providerRecipientId:'15551234567',accountId:'app',phoneNumberId:'phone',wabaId:'waba'}}}]};
 store.list=(async<T extends Record_>(collection:string,query={})=>{const where=(query as {where?:Record<string,unknown>}).where??{};const items=(rows[collection]??[]).filter(row=>Object.entries(where).every(([k,v])=>row[k]===v));return{items:items as T[],page:1,perPage:250,totalPages:1,totalItems:items.length};}) as typeof store.list;
 store.getById=(async<T extends Record_>(collection:string,id:string)=>((rows[collection]??[]).find(row=>row.id===id) as T|undefined)??null) as typeof store.getById;
 store.create=(async<T extends Record_>(collection:string,patch:Omit<T,'id'>)=>{const row={...patch,id:`controlled-${rows[collection]?.length??0}`} as T;(rows[collection]??=[]).push(row);return row;}) as typeof store.create;
 store.update=async(collection,id,patch)=>{const row=rows[collection]?.find(row=>row.id===id);if(!row)return false;Object.assign(row,patch);return true;};
 axios.get=(async(url:string,config?:import('axios').AxiosRequestConfig)=>{calls++;assert.equal(config?.maxRedirects,0);if(String(url).includes('oauth/access_token'))return{data:{access_token:'newtoken',expires_in:3600}};if(String(url).includes('debug_token'))return{data:{data:{is_valid:true,app_id:'app-native',scopes:['whatsapp_business_management','whatsapp_business_messaging']}}};if(String(url).endsWith('/phone_numbers'))return{data:{data:[{id:mode==='foreign'?'foreign-phone':'phone'}]}};if(mode==='phone-failure')throw Error('controlled_phone_failure');return{data:{id:'phone',display_phone_number:'+15550000000'}};}) as typeof axios.get;
 axios.post=(async(url:string,_body:unknown,config?:import('axios').AxiosRequestConfig)=>{calls++;assert.equal(config?.maxRedirects,0);if(String(url).endsWith('/media'))return{data:{id:'controlled-media'}};if(String(url).endsWith('/subscribed_apps'))return{data:{success:mode!=='subscription-failure'}};return{data:{messages:[{id:'wamid.out'}],contacts:[{wa_id:mode==='wrong-recipient'?'15550000000':'15551234567'}]}};}) as typeof axios.post;
 const app=express();app.use(express.json());mountWhatsAppOAuthRoutes(app);
 const request=(method:string,url:string,body?:unknown)=>new Promise<{status:number;body:Record<string,unknown>}>((resolve,reject)=>{const req=new IncomingMessage(new Socket());req.method=method;req.url=url;const payload=body?JSON.stringify(body):'';req.headers={authorization:`Bearer ${issueLocalIdentityTokenForTest({tenantId:'tenant',userId:'owner',role:'admin'})}`,'content-type':'application/json',...(payload?{'content-length':String(Buffer.byteLength(payload))}:{})};const res=new ServerResponse(req);const chunks:string[]=[];res.write=((chunk:unknown)=>{chunks.push(String(chunk));return true;})as typeof res.write;res.end=((chunk?:unknown)=>{if(chunk)chunks.push(String(chunk));resolve({status:res.statusCode,body:JSON.parse(chunks.join('')||'{}')});return res;})as typeof res.end;req.on('error',reject);app(req,res);req.push(payload||null);if(payload)req.push(null);});
 try{
 assert.equal((await request('GET','/api/oauth/whatsapp/config')).status,200);
 const before=calls;assert.equal((await request('POST','/api/oauth/whatsapp/exchange',{tenantId:'foreign',code:'code',wabaId:'waba',phoneNumberId:'phone'})).status,403);assert.equal(calls,before);
 for(mode of ['foreign','phone-failure','subscription-failure']){const original=account.access_token;assert.equal((await request('POST','/api/oauth/whatsapp/exchange',{code:'code',wabaId:'waba',phoneNumberId:'phone'})).status,502);assert.equal(account.access_token,original);}
 mode='valid';rows.tenant_platform_apps!.push({...account,id:'foreign-app',tenant_id:'foreign'});const beforeForeign=calls;assert.equal((await request('POST','/api/oauth/whatsapp/exchange',{code:'code',wabaId:'waba',phoneNumberId:'phone'})).status,502);assert.equal(calls-beforeForeign,5);rows.tenant_platform_apps!.pop();assert.equal((await request('POST','/api/oauth/whatsapp/exchange',{code:'code',wabaId:'waba',phoneNumberId:'phone'})).status,200);assert.ok(JSON.parse(account.last_checklist!).whatsappAssetProof);
 const proof=await assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567'});assert.ok(proof.accountHash);
 const normalList=store.list,normalGet=store.getById;let configReads=0;
 store.list=(async(collection:string,query:unknown)=>{const result=await normalList(collection,query as Parameters<typeof normalList>[1]);if(collection==='digital_employee_configs'&&++configReads===2)return{...result,items:result.items.map(row=>({...row,config_version:2}))};return result;}) as typeof store.list;
 await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567'}),/authorization_changed/);store.list=normalList;
 let accountReads=0;store.getById=(async(collection:string,id:string)=>{const row=await normalGet(collection,id);if(collection==='tenant_platform_apps'&&++accountReads===2)return{...row,access_token:encryptSecret('transient-other-token')};return row;})as typeof store.getById;
 await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567'}),/version_changed/);store.getById=normalGet;

 await assert.rejects(assertWhatsAppSendBoundary({tenantId:'foreign',to:'15551234567'}));await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15550000000'}),/recipient_scope_unverified/);
 account.access_token=encryptSecret('rotated');await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567'}),/asset_authority_unverified/);refreshProof();await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567',expectedAccountHash:proof.accountHash}),/version_changed/);
 rows.digital_employee_configs![0]!.status='disabled';await assert.rejects(assertWhatsAppSendBoundary({tenantId:'tenant',to:'15551234567'}),/authorization_revoked/);rows.digital_employee_configs![0]!.status='active';mode='wrong-recipient';await assert.rejects(sendWhatsAppText(proof.config,'15551234567','controlled'),/receipt_identity_invalid/);const beforeImage=calls;await assert.rejects(sendWhatsAppImage(proof.config,'15551234567',Buffer.from('controlled'),'caption','controlled.png',undefined,async()=>{throw Error('revoked_between_effects');}),/revoked_between_effects/);assert.equal(calls-beforeImage,1);assert.equal(deniedNetwork,0);
 }finally{store.list=old.list;store.getById=old.get;store.update=old.update;store.create=old.create;axios.get=old.axiosGet;axios.post=old.axiosPost;globalThis.fetch=old.fetch;Socket.prototype.connect=old.connect;}
});
