import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=fs.realpathSync(process.cwd());
if(process.env.VERIFIED_WA_ISOLATED_ROOT!==root){const temp=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'verified-wa-inbound-')));try{for(const name of ['server','src','shared','desktop'])fs.cpSync(path.join(root,name),path.join(temp,name),{recursive:true});fs.copyFileSync(path.join(root,'package.json'),path.join(temp,'package.json'));fs.symlinkSync(path.join(root,'node_modules'),path.join(temp,'node_modules'),'dir');const result=spawnSync(process.execPath,['--import','tsx','server/whatsapp/verifiedInbound.test.ts'],{cwd:temp,env:{PATH:process.env.PATH,HOME:temp,VERIFIED_WA_ISOLATED_ROOT:temp},encoding:'utf8',timeout:30000});process.stdout.write(result.stdout||'');process.stderr.write(result.stderr||'');assert.equal(result.status,0,result.error?.message);}finally{fs.rmSync(temp,{recursive:true,force:true});}}
else{globalThis.fetch=async()=>{throw Error('No external effect allowed');};const{store}=await import('../storage/index.js');const rows:Record<string,any[]>={tenant_platform_apps:[{id:'app',tenant_id:'tenant',platform:'meta',app_id:'native-app',status:'active',waba_id:'waba',phone_number_id:'phone',access_token:'fixture-token',app_secret:'fixture-secret'}]};store.getById=(async(c:string,id:string)=>rows[c]?.find(v=>v.id===id)??null)as typeof store.getById;store.list=(async(c:string,q:any)=>{const items=(rows[c]??[]).filter(v=>Object.entries(q.where??{}).every(([k,val])=>v[k]===val));return{items,page:1,perPage:250,totalPages:1,totalItems:items.length};})as typeof store.list;store.create=(async(c:string,p:any)=>{const row={...p,id:p.id??`row-${rows[c]?.length??0}`};(rows[c]??=[]).push(row);return row;})as typeof store.create;store.update=(async(c:string,id:string,p:any)=>{Object.assign(rows[c]!.find(v=>v.id===id),p);return true;})as typeof store.update;
const{handleVerifiedWhatsAppInbound}=await import('./historyImport.js');const{readCanonicalWeeklyWhatsAppConversations}=await import('../socialPrograms/weeklyCustomerChannelScope.js');const payload=(phone='phone',waba='waba')=>({object:'whatsapp_business_account',entry:[{id:waba,changes:[{field:'messages',value:{metadata:{phone_number_id:phone},messages:[{id:'wamid.actual',from:'15550000000',timestamp:String(Math.floor(Date.now()/1000)-10),text:{body:'Actual buyer question'}}]}}]}]});const binding={appId:'app',phoneNumberId:'phone',wabaId:'waba'};
await handleVerifiedWhatsAppInbound('tenant',payload(),binding);await handleVerifiedWhatsAppInbound('tenant',payload(),binding);assert.equal(rows.whatsapp_interactions!.length,1);const saved=JSON.parse(rows.whatsapp_interactions![0].payload);assert.equal(saved.audit.phoneNumberId,'phone');assert.equal(saved.audit.wabaId,'waba');assert.equal(saved.audit.accountId,'app');assert.equal(saved.audit.providerMessageId,'wamid.actual');const options=await readCanonicalWeeklyWhatsAppConversations(store,'tenant');assert.equal(options.length,1);assert.equal(options[0]!.conversationId,'whatsapp:phone:15550000000');assert.equal(options[0]!.messages.length,1);assert.equal(rows.whatsapp_interactions!.filter(v=>JSON.parse(v.payload).type.startsWith('msg_out')).length,0);
await assert.rejects(handleVerifiedWhatsAppInbound('tenant',payload('other'),binding),/phone_invalid/);await assert.rejects(handleVerifiedWhatsAppInbound('other',payload(),binding));await handleVerifiedWhatsAppInbound('tenant',{object:'whatsapp_business_account',entry:[{changes:[{field:'messages',value:{statuses:[{}]}}]}]},{appId:'missing',phoneNumberId:'none',wabaId:'none'});
const start=new Date(Date.now()-3600000).toISOString(),end=new Date(Date.now()+86400000).toISOString();Object.assign(rows,{users:[{id:'owner',tenantId:'tenant',role:'admin'}],social_weekly_customer_bindings:[{id:'binding',tenant_id:'tenant',run_id:'run',goal_id:'goal',program_id:'program',package_id:'pkg',package_version:1}],workflow_runs:[{id:'run',tenant_id:'tenant',goal_id:'goal'}],weekly_goals:[{id:'goal',tenant_id:'tenant',starts_at:start,ends_at:end}],social_programs:[{id:'program',tenant_id:'tenant',program_id:'program',payload:{route:'cold_start'}}],social_weekly_operating_packages:[{id:'pkg',tenant_id:'tenant',program_id:'program',package_id:'pkg',version:1,payload:{programId:'program',packageId:'pkg',version:1}}]});
const{confirmWeeklyCustomerChannelSelection,verifyWeeklyWhatsAppMember}=await import('../socialPrograms/weeklyCustomerChannelSelections.js');const{createCustomerSegmentSnapshot}=await import('../digitalEmployees/customerWorkflow.js');const authority={tenantId:'tenant',programId:'program',packageId:'pkg',packageVersion:1,runId:'run',actorUserId:'owner'};const actualCustomer=options[0]!.customerSnapshot!;
const receipt=await confirmWeeklyCustomerChannelSelection(store,authority,{runId:'run',packageId:'pkg',packageVersion:1,channel:'whatsapp',accountId:'app',customerId:String(actualCustomer.id),inboundMessageId:'wamid.actual',classification:'new_inquiry',reason:'真实首询实名确认'});const segmented=await createCustomerSegmentSnapshot({tenantId:'tenant',goalId:'goal',runId:'run',taskId:'segment',userId:'owner',criteria:{},idempotent:false},()=>[actualCustomer],store);assert.equal(segmented.members.length,1);assert.equal(segmented.members[0]!.customer_id,actualCustomer.id);assert.equal((segmented.members[0]!.customer_snapshot as any).weeklyChannelSelection.recordHash,receipt.recordHash);await verifyWeeklyWhatsAppMember(store,receipt.scope,String(actualCustomer.id),segmented.members[0]!.customer_snapshot);const badSnapshot=structuredClone(segmented.members[0]!.customer_snapshot)as any;badSnapshot.weeklyChannelSelection.recordHash='forged';await assert.rejects(verifyWeeklyWhatsAppMember(store,receipt.scope,String(actualCustomer.id),badSnapshot),/changed/);rows.tenant_platform_apps![0].access_token='rotated';await assert.rejects(verifyWeeklyWhatsAppMember(store,receipt.scope,String(actualCustomer.id),segmented.members[0]!.customer_snapshot),/evidence_changed/);rows.tenant_platform_apps![0].access_token='fixture-token';
const priorUpdate=store.update;store.update=(async(c:string,id:string,p:any)=>c==='whatsapp_interactions'?false:priorUpdate(c,id,p))as typeof store.update;await assert.rejects(handleVerifiedWhatsAppInbound('tenant',payload(),binding),/interaction_persistence_failed/);store.update=priorUpdate;await handleVerifiedWhatsAppInbound('tenant',payload(),binding);assert.equal(rows.whatsapp_interactions!.length,1);

const priorCreate=store.create;store.create=(async(c:string,p:any)=>c==='whatsapp_interactions'?null:priorCreate(c,p))as typeof store.create;const missing=payload();missing.entry[0]!.changes[0]!.value.messages[0]!.id='wamid.failed-create';await assert.rejects(handleVerifiedWhatsAppInbound('tenant',missing,binding),/interaction_persistence_failed/);store.create=priorCreate;await handleVerifiedWhatsAppInbound('tenant',missing,binding);assert.equal(rows.whatsapp_interactions!.filter(r=>JSON.parse(r.payload).metaMessageId==='wamid.failed-create').length,1);
store.update=(async(c:string,id:string,p:any)=>c==='whatsapp_customers'?false:priorUpdate(c,id,p))as typeof store.update;await assert.rejects(handleVerifiedWhatsAppInbound('tenant',payload(),binding),/customer_persistence_failed/);store.update=priorUpdate;await handleVerifiedWhatsAppInbound('tenant',payload(),binding);
rows.tenant_platform_apps![0].access_token='';assert.deepEqual(await readCanonicalWeeklyWhatsAppConversations(store,'tenant'),[]);console.log('Verified WA actual ingress persisted canonical account evidence, replay safe, readonly weekly source, foreign scope rejected; zero external effects.');}
