import { buildTikTokPostOptions, editTikTokPostSettings, type TikTokCreatorResponse, type TikTokPostSettingsDraft } from '../../lib/tikTokPostSettings';
const privacyLabels:Record<string,string>={PUBLIC_TO_EVERYONE:'所有人',MUTUAL_FOLLOW_FRIENDS:'互相关注的好友',FOLLOWER_OF_CREATOR:'关注者',SELF_ONLY:'仅自己'};
export function TikTokPostSettings({accountId,creator,draft,onChange,disabled=false,loading=false,error='',onRefresh}:{accountId:string;creator:TikTokCreatorResponse|null;draft:TikTokPostSettingsDraft;onChange:(draft:TikTokPostSettingsDraft)=>void;disabled?:boolean;loading?:boolean;error?:string;onRefresh:()=>void}) {
  const edit=(patch:Partial<TikTokPostSettingsDraft>)=>onChange(editTikTokPostSettings(draft,patch));
  const locked=disabled||loading||!creator;
  let validation='';try{if(creator)buildTikTokPostOptions(draft,creator,accountId);}catch(cause){validation=cause instanceof Error?cause.message:'请核对设置';}
  return <fieldset aria-label="TikTok 发布设置" disabled={disabled} className="mt-4 rounded-xl border border-border bg-white p-3 text-xs">
    <legend className="px-1 font-bold">TikTok · 用户发布设置</legend>
    <div className="flex items-center justify-between gap-2"><p>{creator?<>发布账号：<strong>{creator.creator.creator_nickname}</strong> @{creator.creator.creator_username} · 最长 {creator.creator.max_video_post_duration_sec} 秒</>:loading?'正在读取 TikTok 最新创作者设置…':'选择 TikTok 账号后读取最新设置'}</p><button type="button" disabled={!accountId||loading||disabled} onClick={onRefresh} className="rounded border px-2 py-1">刷新账号设置</button></div>
    {error&&<p role="alert" className="mt-2 text-red-700">{error}</p>}
    {creator&&!creator.directPostApproved&&<p role="status" className="mt-2 text-amber-700">TikTok Direct Post 平台审核尚未确认，暂不能提交。</p>}
    <label className="mt-3 block">可见范围<select aria-label="TikTok 可见范围" value={draft.privacyLevel} disabled={locked} onChange={event=>edit({privacyLevel:event.target.value as TikTokPostSettingsDraft['privacyLevel']})} className="ml-2 rounded border p-1"><option value="">请选择可见范围（无默认）</option>{creator?.creator.privacy_level_options.map(value=><option key={value} value={value} disabled={value==='SELF_ONLY'&&draft.commercial.brandedContent}>{privacyLabels[value]}</option>)}</select></label>
    <div className="mt-3 flex flex-wrap gap-4">{([{key:'allowComment',label:'允许评论',blocked:creator?.creator.comment_disabled},{key:'allowDuet',label:'允许合拍',blocked:creator?.creator.duet_disabled},{key:'allowStitch',label:'允许拼接',blocked:creator?.creator.stitch_disabled}] as const).map(item=><label key={item.key} className={item.blocked?'text-text-muted':''}><input type="checkbox" checked={draft[item.key]} disabled={locked||item.blocked} onChange={event=>edit({[item.key]:event.target.checked})}/> {item.label}{item.blocked?'（账号已禁用）':''}</label>)}</div>
    <label className="mt-3 block"><input type="checkbox" checked={draft.disclosureEnabled} disabled={locked} onChange={event=>edit({disclosureEnabled:event.target.checked,commercial:{ownBrand:false,brandedContent:false}})}/> 此内容推广品牌、产品或服务</label>
    {draft.disclosureEnabled&&<div className="mt-2 space-y-2"><label className="block"><input type="checkbox" checked={draft.commercial.ownBrand} disabled={locked} onChange={event=>edit({commercial:{...draft.commercial,ownBrand:event.target.checked}})}/> 自己的品牌（Promotional content）</label><label className="block"><input type="checkbox" checked={draft.commercial.brandedContent} disabled={locked||draft.privacyLevel==='SELF_ONLY'} onChange={event=>edit({commercial:{...draft.commercial,brandedContent:event.target.checked}})}/> 第三方品牌合作（Paid partnership）</label><p className="text-text-muted">品牌合作内容不能设为仅自己可见；开启披露后必须选择至少一项。</p></div>}
    <label className="mt-3 block"><input type="checkbox" checked={draft.isAigc} disabled={locked} onChange={event=>edit({isAigc:event.target.checked})}/> 视频包含 AI 生成内容，标记 AIGC</label>
    <label className="mt-3 block"><input type="checkbox" checked={draft.musicUsageConfirmed} disabled={locked} onChange={event=>onChange({...draft,musicUsageConfirmed:event.target.checked,userConsent:false})}/> {draft.commercial.brandedContent?'我同意 TikTok 品牌内容政策与音乐使用声明':'我同意 TikTok 音乐使用声明'}。<a href="https://www.tiktok.com/legal/page/global/music-usage-confirmation/en" target="_blank" rel="noreferrer" className="underline">查看声明</a>{draft.commercial.brandedContent&&<> · <a href="https://www.tiktok.com/legal/page/global/bc-policy/en" target="_blank" rel="noreferrer" className="underline">品牌内容政策</a></>}</label>
    <label className="mt-3 block font-bold"><input type="checkbox" checked={draft.userConsent} disabled={locked||!draft.musicUsageConfirmed} onChange={event=>onChange({...draft,userConsent:event.target.checked})}/> 我已预览视频、核对标题与配文，并授权按这些设置向上述账号发布本条内容</label>
    {validation&&<p role="status" className="mt-2 text-amber-700">{validation}</p>}
    <p className="mt-2 text-text-muted">编辑内容、账号或发布设置后，需重新确认音乐声明与本次授权。创建审批单不会立即发布。</p>
  </fieldset>;
}
