import assert from 'node:assert/strict';
import { DownloadBudget, RecordWorkRegistry, terminalDownloadFailure } from './downloadExecution.js';
let now = 0;
const budget = new DownloadBudget(150_000, () => now);
assert.equal(budget.remaining(), 150_000);
budget.record('anonymous', Error('network timeout'));
now += 100_000;
assert.equal(budget.remaining(), 50_000, 'cookie retries consume the same budget');
budget.record('chrome', Error('cookie extraction failed'));
now += 50_000;
assert.throws(() => budget.remaining(), /下载累计超时.*anonymous.*network timeout.*chrome.*cookie extraction failed/);
assert.equal(terminalDownloadFailure(Error('Private video')), true);
assert.equal(terminalDownloadFailure(Error('Requested format is not available')), false);
const registry = new RecordWorkRegistry();
let release!: () => void;
let calls = 0;
const pending = new Promise<void>(resolve => {release = resolve;});
const action = async () => { calls += 1; await pending; return 'receipt'; };
const first = registry.run('video-1', action);
assert.equal(registry.has('video-1'), true, 'waiting for a slot is active work too');
assert.equal(registry.run('video-1', action), first);
release();
assert.equal(await first, 'receipt');
assert.equal(calls, 1);
assert.equal(registry.has('video-1'), false);
await assert.rejects(registry.run('video-1', async () => {throw Error('failed');}));
assert.equal(registry.has('video-1'), false, 'a real failure releases the registry for later deliberate recovery');
console.log('Shared download timeout, error evidence and queued-work deduplication passed');
