import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';
import {QwenAsrService} from './qwenAsr.js';import {saveReferenceNarrationBinding,readExistingReferenceNarration,resumeExistingReferenceNarration} from './referenceNarrationRecovery.js';import {readCachedReferenceNarration,REFERENCE_AUDIO_CLOCK_POLICY} from './referenceNarration.js';
test('actual submitted cache binds original source and GET-only resume completes same task without new reservation',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reference-resume-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'original');fs.writeFileSync(file,'actual-owned-original');const sha=createHash('sha256').update(fs.readFileSync(file)).digest('hex'),tenant=`resume_${Date.now()}`,scope={tenantId:tenant,filePath:file,expectedSourceSha256:sha};const root=path.resolve('data/analysis-output/qwen-word-asr-v1');const hash=createHash('sha256').update(`${tenant}:${sha}:measured-word-v2:${REFERENCE_AUDIO_CLOCK_POLICY}`).digest('hex');t.after(()=>{fs.rmSync(path.join(root,tenant),{recursive:true,force:true});for(const extension of ['.json','.binding.json'])fs.rmSync(path.resolve('data/analysis-output/narration-cache',hash+extension),{force:true});});
 const env=['DASHSCOPE_API_KEY','QWEN_ASR_GENERATION_ENABLED','QWEN_ASR_BASE_URL'] as const;const old=Object.fromEntries(env.map(key=>[key,process.env[key]]));t.after(()=>{for(const key of env){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});process.env.DASHSCOPE_API_KEY='controlled';process.env.QWEN_ASR_GENERATION_ENABLED='true';process.env.QWEN_ASR_BASE_URL='https://dashscope.aliyuncs.com/api/v1';
 let submissions=0,reserves=0,reads=0;const request:typeof fetch=async(url,init)=>{
  const value=String(url);if(value.includes('/uploads?'))return Response.json({data:{upload_host:'https://test.oss-cn-beijing.aliyuncs.com',upload_dir:'temporary'}});
  if(value.includes('/transcription')){submissions++;return Response.json({output:{task_id:'actual-original-job',task_status:'PENDING'}});}
  if(value.includes('/tasks/')){assert.equal(init?.method??'GET','GET');reads++;return Response.json({output:{task_status:'SUCCEEDED',result:{transcription_url:'https://test.oss-cn-beijing.aliyuncs.com/result'}}});}
  if(value.endsWith('/result'))return Response.json({transcripts:[{text:'你好。',sentences:[{words:[{text:'你好',punctuation:'。',begin_time:80,end_time:600}]}]}]});return new Response('',{status:200});
 };
 const service=new QwenAsrService(root,request,async()=>{reserves++;},{automaticSubmission:false,onRecord:record=>saveReferenceNarrationBinding(scope,2,{clockPolicy:REFERENCE_AUDIO_CLOCK_POLICY},record)});
 await service.run(tenant,Buffer.from('actual-controlled-audio'),'audio/wav',true);
 const existing=readExistingReferenceNarration(scope);assert.equal(existing?.record.status,'PENDING');assert.equal(existing?.binding.taskId,'actual-original-job');assert.equal(reads,0);
 await assert.rejects(resumeExistingReferenceNarration({...scope,expectedTaskId:'wrong'},{request}));assert.equal(reads,0);
 const resumed=await resumeExistingReferenceNarration({...scope,expectedTaskId:'actual-original-job'},{request});assert.equal(resumed.status,'SUCCEEDED');assert.equal(resumed.result?.segments[0]?.start,.08);assert.equal(readCachedReferenceNarration(file,tenant)?.taskId,'actual-original-job');assert.equal(submissions,1);assert.equal(reserves,1);assert.equal(reads,1);
 fs.writeFileSync(file,'changed-original');assert.throws(()=>readExistingReferenceNarration(scope));await assert.rejects(resumeExistingReferenceNarration({...scope,expectedTaskId:'actual-original-job'},{request}));assert.equal(reads,1);
});

test('real FFmpeg owned video extracts audio and actual prepare retains pending job after controlled GET failure',async t=>{
 const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const {default:ffmpeg}=await import('ffmpeg-static');const {prepareReferenceNarration}=await import('./referenceNarration.js');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reference-actual-audio-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'original.mp4');await promisify(execFile)(ffmpeg||'ffmpeg',['-y','-f','lavfi','-i','color=c=blue:s=160x180:r=10:d=2','-f','lavfi','-i','sine=frequency=440:sample_rate=16000:duration=2','-c:v','libx264','-pix_fmt','yuv420p','-c:a','aac','-shortest',file]);
 const sha=createHash('sha256').update(fs.readFileSync(file)).digest('hex'),tenant=`extract_${Date.now()}`,scope={tenantId:tenant,filePath:file,expectedSourceSha256:sha};const root=path.resolve('data/analysis-output/qwen-word-asr-v1'),hash=createHash('sha256').update(`${tenant}:${sha}:measured-word-v2:${REFERENCE_AUDIO_CLOCK_POLICY}`).digest('hex');t.after(()=>{fs.rmSync(path.join(root,tenant),{recursive:true,force:true});for(const extension of ['.json','.binding.json'])fs.rmSync(path.resolve('data/analysis-output/narration-cache',hash+extension),{force:true});});
 const oldKey=process.env.DASHSCOPE_API_KEY,oldEndpoint=process.env.QWEN_ASR_BASE_URL;t.after(()=>{if(oldKey===undefined)delete process.env.DASHSCOPE_API_KEY;else process.env.DASHSCOPE_API_KEY=oldKey;if(oldEndpoint===undefined)delete process.env.QWEN_ASR_BASE_URL;else process.env.QWEN_ASR_BASE_URL=oldEndpoint;});process.env.DASHSCOPE_API_KEY='controlled-not-real';process.env.QWEN_ASR_BASE_URL='https://dashscope.aliyuncs.com/api/v1';
 let submits=0,gets=0,failGet=true;const request:typeof fetch=async(url,init)=>{const value=String(url);if(value.includes('/uploads?'))return Response.json({data:{upload_host:'https://test.oss-cn-beijing.aliyuncs.com',upload_dir:'temporary'}});if(value.includes('/transcription')){submits++;return Response.json({output:{task_id:'actual-extracted-job',task_status:'PENDING'}});}if(value.includes('/tasks/')){gets++;assert.equal(init?.method??'GET','GET');if(failGet)throw Error('controlled-original-GET-failure');return Response.json({output:{task_status:'SUCCEEDED',result:{transcription_url:'https://test.oss-cn-beijing.aliyuncs.com/result'}}});}if(value.endsWith('/result'))return Response.json({transcripts:[{text:'你好。',sentences:[{words:[{text:'你好',punctuation:'。',begin_time:80,end_time:600}]}]}]});return new Response('',{status:200});};
 await assert.rejects(prepareReferenceNarration(file,2,{tenantId:tenant,request}),/controlled-original-GET-failure/);
 const original=readExistingReferenceNarration(scope);assert.equal(original?.status,'PENDING');assert.equal(original?.binding.taskId,'actual-extracted-job');assert.ok(original?.binding.audioSha256);assert.notEqual(original?.binding.audioSha256,sha);assert.equal((original?.binding.audioExtraction as {audioClockContinuityVerified:boolean}).audioClockContinuityVerified,true);assert.equal(submits,1);
 failGet=false;const result=await resumeExistingReferenceNarration({...scope,expectedTaskId:'actual-extracted-job'},{request});assert.equal(result.result?.sourceVideoSha256,sha);assert.equal(result.result?.words[0]?.start,.08);assert.equal(submits,1);assert.equal(gets,2);assert.equal(readCachedReferenceNarration(file,tenant)?.taskId,'actual-extracted-job');
});

test('original clock binding drift during actual provider GET cannot save aligned candidates',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reference-clock-drift-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'original');fs.writeFileSync(file,'owned-clock-source');const sha=createHash('sha256').update(fs.readFileSync(file)).digest('hex'),tenant=`clock_${Date.now()}`,scope={tenantId:tenant,filePath:file,expectedSourceSha256:sha};const root=path.resolve('data/analysis-output/qwen-word-asr-v1'),hash=createHash('sha256').update(`${tenant}:${sha}:measured-word-v2:${REFERENCE_AUDIO_CLOCK_POLICY}`).digest('hex'),bindingFile=path.resolve('data/analysis-output/narration-cache',hash+'.binding.json');t.after(()=>{fs.rmSync(path.join(root,tenant),{recursive:true,force:true});for(const suffix of ['.json','.binding.json'])fs.rmSync(path.resolve('data/analysis-output/narration-cache',hash+suffix),{force:true});});
 const oldKey=process.env.DASHSCOPE_API_KEY,oldEndpoint=process.env.QWEN_ASR_BASE_URL;process.env.DASHSCOPE_API_KEY='controlled';process.env.QWEN_ASR_BASE_URL='https://dashscope.aliyuncs.com/api/v1';t.after(()=>{if(oldKey===undefined)delete process.env.DASHSCOPE_API_KEY;else process.env.DASHSCOPE_API_KEY=oldKey;if(oldEndpoint===undefined)delete process.env.QWEN_ASR_BASE_URL;else process.env.QWEN_ASR_BASE_URL=oldEndpoint;});
 let posts=0,gets=0;const request:typeof fetch=async(url)=>{const value=String(url);if(value.includes('/uploads?'))return Response.json({data:{upload_host:'https://test.oss-cn-beijing.aliyuncs.com',upload_dir:'temporary'}});if(value.includes('/transcription')){posts++;return Response.json({output:{task_id:'clock-original-task'}});}if(value.includes('/tasks/')){gets++;const binding=JSON.parse(fs.readFileSync(bindingFile,'utf8'));binding.durationSeconds=3;fs.writeFileSync(bindingFile,JSON.stringify(binding));return Response.json({output:{task_status:'SUCCEEDED',result:{transcription_url:'https://test.oss-cn-beijing.aliyuncs.com/result'}}});}if(value.endsWith('/result'))return Response.json({transcripts:[{sentences:[{words:[{text:'原句',begin_time:80,end_time:600}]}]}]});return new Response('',{status:200});};
 const service=new QwenAsrService(root,request,async()=>{}, {automaticSubmission:true,onRecord:record=>saveReferenceNarrationBinding(scope,2,{controlledExtraction:true},record)});await service.run(tenant,Buffer.from('controlled-audio'),'audio/wav',true);
 await assert.rejects(resumeExistingReferenceNarration({...scope,expectedTaskId:'clock-original-task'},{request}),/时钟或来源绑定/);assert.equal(readCachedReferenceNarration(file,tenant),null);assert.equal(posts,1);assert.equal(gets,1);
});
