import {objectStorageUpload} from '../storage/objectStorage.js';
import {acquireDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import os from 'node:os';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import ffmpeg from 'ffmpeg-static';import {createHash} from 'node:crypto';
import {prepareWeeklyQualityAuditFixture} from '../runtime/weeklyContentQualityAudit.fixture.js';import {createExactShotMaterializationService} from './referenceExactShotMaterialization.js';import {socialRequestHash} from '../starter198/socialContentValidation.js';
test('real owned MP4 produces SHA-verified physical shots and frames; only verified files are already ready',async t=>{assert.ok(ffmpeg);const f=await prepareWeeklyQualityAuditFixture();t.after(f.cleanup);const root=await fs.mkdtemp(path.join(os.tmpdir(),'reference-shot-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const destination=path.join(root,'tenants/t/reference-videos');await fs.mkdir(destination,{recursive:true});const source=path.join(destination,'actual.mp4');await promisify(execFile)(ffmpeg,['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=160x180:rate=10','-t','2','-c:v','libx264','-pix_fmt','yuv420p','-y',source]);const sha=createHash('sha256').update(await fs.readFile(source)).digest('hex');const analysis={analysisMode:'exact',analysisQuality:'video',analysisRunId:'source-run',contentSha256:sha,gemini:{scriptDetails15s:[{time:'0-1',visual:'实际测试图第一段'},{time:'1-2',visual:'实际测试图第二段'}]}};await f.store.create('trend_videos',{id:'actual',tenantId:'t',videoFileId:'tenants/t/reference-videos/actual.mp4',aiAnalysis:JSON.stringify(analysis)});const service=createExactShotMaterializationService(f.store,{mediaRoot:root}),scope={tenantId:'t',recordId:'actual',expectedAnalysisRunId:'source-run',expectedSourceSha256:sha,expectedAnalysisHash:socialRequestHash(analysis)};
 await assert.rejects(service.materialize({...scope,tenantId:'foreign'}),{code:'reference_shot_source_not_owned'});await assert.rejects(service.materialize({...scope,expectedAnalysisRunId:'changed'}),{code:'reference_shot_source_changed'});
 const held=await acquireDurableOperationLease({dataStore:f.store,tenantId:'t',scope:'reference-exact-shot-materialization',subjectId:'actual',ownerId:'other-operation',leaseDurationMs:300000});assert.ok(held);await assert.rejects(service.materialize(scope),{code:'reference_shot_materialization_busy'});await releaseDurableOperationLease({dataStore:f.store,lease:held});
 const result=await service.materialize(scope);assert.equal(result.status,'materialized');assert.equal(f.tables.trend_videos!.find(row=>row.id==='actual')!.aiAnalysis,JSON.stringify(analysis),'supplement never overwrites original analysis');assert.equal(f.tables.reference_exact_shot_evidence!.length,1);const merged=await service.readVerifiedAnalysis(scope);assert.ok(merged);assert.ok((merged.gemini.scriptDetails15s[0]!.materialEvidence as {clipSha256:string}).clipSha256);assert.equal(result.shots.length,2);const current={...scope,expectedAnalysisHash:result.analysisHash};assert.equal((await service.materialize(current)).status,'already_ready');for(const shot of result.shots){assert.equal(createHash('sha256').update(await fs.readFile(path.join(root,shot.clipRef.slice('/media/'.length)))).digest('hex'),shot.clipSha256);assert.equal(createHash('sha256').update(await fs.readFile(path.join(root,shot.firstFrameRef.slice('/media/'.length)))).digest('hex'),shot.firstFrameSha256);}
 const savedAnalysis=String(f.tables.trend_videos!.find(row=>row.id==='actual')!.aiAnalysis);
 await fs.writeFile(path.join(root,result.shots[0]!.clipRef.slice('/media/'.length)),Buffer.from('corrupt derived bytes'));assert.equal((await service.materialize(current)).status,'materialized','declared ready with damaged bytes must not be already ready');
 const changedTimeline={...analysis,gemini:{scriptDetails15s:[{time:'0-9',visual:'invalid out of duration'}]}};await f.store.update('trend_videos','actual',{aiAnalysis:JSON.stringify(changedTimeline)});await assert.rejects(service.materialize({...scope,expectedAnalysisHash:socialRequestHash(changedTimeline)}),{code:'reference_shot_timecode_invalid'});
 await f.store.update('trend_videos','actual',{aiAnalysis:savedAnalysis});
 const oldDriver=process.env.OBJECT_STORAGE_DRIVER,oldObjectRoot=process.env.LOCAL_OBJECT_STORAGE_ROOT;process.env.OBJECT_STORAGE_DRIVER='local';process.env.LOCAL_OBJECT_STORAGE_ROOT=path.join(root,'objects');t.after(()=>{if(oldDriver===undefined)delete process.env.OBJECT_STORAGE_DRIVER;else process.env.OBJECT_STORAGE_DRIVER=oldDriver;if(oldObjectRoot===undefined)delete process.env.LOCAL_OBJECT_STORAGE_ROOT;else process.env.LOCAL_OBJECT_STORAGE_ROOT=oldObjectRoot;});
 const objectKey='crawlers/tenants/t/trend-videos/objectactual/video.mp4';await objectStorageUpload({key:objectKey,body:await fs.readFile(source),contentType:'video/mp4'});await f.store.create('trend_videos',{id:'objectactual',tenantId:'t',videoFileId:objectKey,aiAnalysis:JSON.stringify({...analysis,videoObjectKey:objectKey})});const objectScope={...scope,recordId:'objectactual',expectedAnalysisHash:socialRequestHash({...analysis,videoObjectKey:objectKey})};assert.equal((await service.materialize(objectScope)).status,'materialized','real stored-object producer path uses actual streamed bytes, never a URL');
 await f.store.update('trend_videos','objectactual',{videoFileId:'crawlers/tenants/foreign/trend-videos/objectactual/video.mp4',aiAnalysis:JSON.stringify({...analysis,videoObjectKey:'crawlers/tenants/foreign/trend-videos/objectactual/video.mp4'})});await assert.rejects(service.materialize({...objectScope,expectedAnalysisHash:socialRequestHash({...analysis,videoObjectKey:'crawlers/tenants/foreign/trend-videos/objectactual/video.mp4'})}),{code:'reference_shot_owned_bytes_unavailable'});
 await fs.copyFile(source,path.join(destination,'driftactual.mp4'));await f.store.create('trend_videos',{id:'driftactual',tenantId:'t',videoFileId:'tenants/t/reference-videos/driftactual.mp4',aiAnalysis:JSON.stringify(analysis)});let sourceReads=0;const changedAnalysis=JSON.stringify({...analysis,analysisRunId:'new-analysis-run'});const racingStore:import('../storage/datastore.js').DataStore={...f.store,getById:async<T=import('../storage/datastore.js').Record_>(collection:string,recordId:string)=>{if(collection==='trend_videos'&&recordId==='driftactual'&&++sourceReads===2)await f.store.update(collection,recordId,{aiAnalysis:changedAnalysis});return f.store.getById<T>(collection,recordId);}};await assert.rejects(createExactShotMaterializationService(racingStore,{mediaRoot:root}).materialize({...scope,recordId:'driftactual'}),{code:'reference_shot_source_changed'});assert.equal(f.tables.trend_videos!.find(row=>row.id==='driftactual')!.aiAnalysis,changedAnalysis,'concurrent producer analysis is not overwritten');assert.equal(f.tables.reference_exact_shot_evidence!.filter(row=>row.record_id==='driftactual').length,0);
 await fs.writeFile(source,Buffer.from('changed actual bytes'));await assert.rejects(service.materialize(current),{code:'reference_shot_source_bytes_changed'});assert.equal(f.tables.starter_usage_ledger?.length??0,0);assert.equal(f.tables.content_execution_jobs?.length??0,0);
});
