import {objectStorageGetObject} from '../storage/objectStorage.js';
import {acquireDurableOperationLease,assertDurableOperationLease,renewDurableOperationLease,releaseDurableOperationLease} from '../runtime/durableLease.js';
import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash,randomUUID} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import ffmpeg from 'ffmpeg-static';
import {probeReferenceMediaClock} from './referenceMediaClock.js';
import type {DataStore,Record_} from '../storage/datastore.js';import {parseAnalysisTimeRange} from './videoAnalysisCodec.js';import {socialObject,socialJson,socialRequestHash,SocialContentWorkflowError} from '../starter198/socialContentValidation.js';
const exec=promisify(execFile),obj=(value:unknown)=>socialObject(socialJson(value));const hash=(bytes:Buffer)=>createHash('sha256').update(bytes).digest('hex');const id=/^[A-Za-z0-9_-]+$/,hex=/^[a-f0-9]{64}$/;
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../data/media');
export const EXACT_SHOT_EVIDENCE_COLLECTION='reference_exact_shot_evidence';
export interface ExactShotMaterializationScope{tenantId:string;recordId:string;expectedSourceSha256:string;expectedAnalysisRunId:string;expectedAnalysisHash:string}
export interface ExactShotMaterializationReceipt{status:'already_ready'|'materialized';sourceSha256:string;analysisRunId:string;analysisHash:string;shots:Array<{shotIndex:number;startSeconds:number;endSeconds:number;clipSha256:string;firstFrameSha256:string;clipRef:string;firstFrameRef:string}>}
/** Local-only FFmpeg work. Never fetch URLs, invoke a model, alter task sources, or start production. */
export function createExactShotMaterializationService(store:DataStore,options:{mediaRoot?:string}={}){
 const root=path.resolve(options.mediaRoot??defaultRoot);
 function fail(code:string):never{throw new SocialContentWorkflowError(code,409);}
 async function current(scope:ExactShotMaterializationScope){
 if(!id.test(scope.tenantId)||!id.test(scope.recordId)||!hex.test(scope.expectedSourceSha256)||!hex.test(scope.expectedAnalysisHash)||!scope.expectedAnalysisRunId)fail('reference_shot_scope_invalid');
 const row=await store.getById<Record_>('trend_videos',scope.recordId),analysis=obj(row?.aiAnalysis),gemini=obj(analysis?.gemini);
 if(!row||row.id!==scope.recordId||row.tenantId!==scope.tenantId)fail('reference_shot_source_not_owned');
 if(!analysis||analysis.analysisMode!=='exact'||!['video','video_review_required'].includes(String(analysis.analysisQuality))||analysis.analysisRunId!==scope.expectedAnalysisRunId||analysis.contentSha256!==scope.expectedSourceSha256||socialRequestHash(analysis)!==scope.expectedAnalysisHash||!Array.isArray(gemini?.scriptDetails15s)||!gemini.scriptDetails15s.length)fail('reference_shot_source_changed');
 const relative=row.videoFileId;let source: string|null=null;
 if(typeof relative==='string'&&relative===`tenants/${scope.tenantId}/reference-videos/${scope.recordId}.mp4`)source=await fs.realpath(path.resolve(root,relative)).catch(()=>null);
 if(!source){const key=analysis.videoObjectKey;const expected=`crawlers/tenants/${scope.tenantId}/trend-videos/${scope.recordId}/video.mp4`;if(typeof key!=='string'||key!==expected||row.videoFileId!==key)fail('reference_shot_owned_bytes_unavailable');const object=await objectStorageGetObject(key);if(!object)fail('reference_shot_owned_bytes_unavailable');const chunks:Buffer[]=[];let size=0;for await(const chunk of object.body){size+=chunk.length;if(size>100*1024*1024)fail('reference_shot_source_bytes_changed');chunks.push(Buffer.from(chunk));}const bytes=Buffer.concat(chunks);if(!bytes.length||hash(bytes)!==scope.expectedSourceSha256)fail('reference_shot_source_bytes_changed');const folder=path.resolve(root,'tenants',scope.tenantId,'reference-source-cache',scope.recordId);await fs.mkdir(folder,{recursive:true});const cached=path.join(folder,`${scope.expectedSourceSha256}.mp4`);await fs.writeFile(cached,bytes);source=await fs.realpath(cached);}
 const tenantRoot=await fs.realpath(path.resolve(root,'tenants',scope.tenantId)).catch(()=>null);if(!source||!tenantRoot||!source.startsWith(`${tenantRoot}${path.sep}`))fail('reference_shot_owned_bytes_unavailable');
 const bytes=await fs.readFile(source);if(!bytes.length||bytes.length>100*1024*1024||hash(bytes)!==scope.expectedSourceSha256)fail('reference_shot_source_bytes_changed');
 const clock=await probeReferenceMediaClock(source);
 const shots=gemini.scriptDetails15s.map((value,index)=>{const detail=obj(value),range=parseAnalysisTimeRange(String(detail?.time||detail?.timestamp||''));if(!detail||!range||range.start<0||range.end-range.start<.2||range.end>clock.duration+.01)fail('reference_shot_timecode_invalid');return {detail,index,...range};});
 return {row,analysis,gemini,source,shots};
 }
 async function readEvidence(scope:ExactShotMaterializationScope,state:Awaited<ReturnType<typeof current>>){const shots:ExactShotMaterializationReceipt['shots']=[];for(const shot of state.shots){const evidence=obj(shot.detail.materialEvidence);if(evidence?.sourceSha256!==scope.expectedSourceSha256||evidence.analysisRunId!==scope.expectedAnalysisRunId||evidence.startSeconds!==shot.start||evidence.endSeconds!==shot.end||evidence.extractionStatus!=='ready')return null;const refs=[evidence.clipRef,evidence.firstFrameRef],hashes=[evidence.clipSha256,evidence.firstFrameSha256];for(let i=0;i<2;i++){const ref=refs[i],sha=hashes[i];const prefix=`/media/tenants/${scope.tenantId}/reference-evidence/${scope.recordId}/`;if(typeof ref!=='string'||!ref.startsWith(prefix)||typeof sha!=='string'||!hex.test(sha))return null;const file=await fs.realpath(path.resolve(root,ref.slice('/media/'.length))).catch(()=>null);if(!file||!file.startsWith((await fs.realpath(path.resolve(root,prefix.slice('/media/'.length))).catch(()=>''))+path.sep)||hash(await fs.readFile(file))!==sha)return null;}
 shots.push({shotIndex:shot.index+1,startSeconds:shot.start,endSeconds:shot.end,clipSha256:String(evidence.clipSha256),firstFrameSha256:String(evidence.firstFrameSha256),clipRef:String(evidence.clipRef),firstFrameRef:String(evidence.firstFrameRef)});}return shots;}
 async function existingState(scope:ExactShotMaterializationScope,state:Awaited<ReturnType<typeof current>>){const rows=await store.list<Record_>(EXACT_SHOT_EVIDENCE_COLLECTION,{where:{tenant_id:scope.tenantId,record_id:scope.recordId,source_sha256:scope.expectedSourceSha256,analysis_run_id:scope.expectedAnalysisRunId,analysis_hash:scope.expectedAnalysisHash},perPage:2});if(rows.totalItems>1||rows.items.length!==rows.totalItems)fail('reference_shot_evidence_ambiguous');const row=rows.items[0];if(!row)return null;const payload=obj(row.payload);if(!payload||socialRequestHash(payload.scope)!==socialRequestHash(scope)||row.tenant_id!==scope.tenantId||row.record_id!==scope.recordId||row.source_sha256!==scope.expectedSourceSha256||row.analysis_run_id!==scope.expectedAnalysisRunId||row.analysis_hash!==scope.expectedAnalysisHash||row.record_hash!==socialRequestHash(payload)||!Array.isArray(payload.details)||payload.details.length!==state.shots.length)fail('reference_shot_evidence_invalid');const savedDetails=payload.details;if(savedDetails.some((detail,index)=>{const saved=obj(detail);if(!saved)return true;const {materialEvidence:ignored,...rest}=saved;const {materialEvidence:originalIgnored,...original}=state.shots[index]!.detail;return socialRequestHash(rest)!==socialRequestHash(original);}))fail('reference_shot_evidence_invalid');return {...state,shots:state.shots.map((shot,index)=>({...shot,detail:obj(savedDetails[index])??{}}))};}
 return {async readVerifiedAnalysis(scope:ExactShotMaterializationScope){const state=await current(scope),saved=await existingState(scope,state);if(!saved||!await readEvidence(scope,saved))return null;return {...state.analysis,gemini:{...state.gemini,scriptDetails15s:saved.shots.map(shot=>shot.detail)}};},async materialize(scope:ExactShotMaterializationScope):Promise<ExactShotMaterializationReceipt>{let lease=await acquireDurableOperationLease({dataStore:store,tenantId:scope.tenantId,scope:'reference-exact-shot-materialization',subjectId:scope.recordId,ownerId:randomUUID(),leaseDurationMs:300000});if(!lease)fail('reference_shot_materialization_busy');try{const state=await current(scope);const stored=await existingState(scope,state);const existing=stored?await readEvidence(scope,stored):null;if(existing)return {status:'already_ready',sourceSha256:scope.expectedSourceSha256,analysisRunId:scope.expectedAnalysisRunId,analysisHash:scope.expectedAnalysisHash,shots:existing};if(!ffmpeg)fail('reference_shot_ffmpeg_unavailable');
 const fingerprint=socialRequestHash({sourceSha256:scope.expectedSourceSha256,analysisRunId:scope.expectedAnalysisRunId,timeline:state.shots.map(s=>({start:s.start,end:s.end}))});const relative=`tenants/${scope.tenantId}/reference-evidence/${scope.recordId}/${fingerprint}`;const destination=path.resolve(root,relative);await fs.mkdir(destination,{recursive:true});const details=[];
 for(const shot of state.shots){lease=await renewDurableOperationLease({dataStore:store,lease,leaseDurationMs:300000});const temporary=path.join(destination,`${randomUUID()}`),clip=`${temporary}.mp4`,frame=`${temporary}.jpg`;try{await exec(ffmpeg!,['-hide_banner','-loglevel','error','-ss',String(shot.start),'-i',state.source,'-t',String(shot.end-shot.start),'-map','0:v:0','-map','0:a?','-c:v','libx264','-preset','veryfast','-crf','24','-c:a','aac','-movflags','+faststart','-y',clip],{timeout:90000});await exec(ffmpeg!,['-hide_banner','-loglevel','error','-ss',String(shot.start+Math.min(.04,(shot.end-shot.start)/4)),'-i',state.source,'-frames:v','1','-q:v','3','-y',frame],{timeout:30000});const clipBytes=await fs.readFile(clip),frameBytes=await fs.readFile(frame);if(!clipBytes.length||!frameBytes.length)fail('reference_shot_extraction_empty');const clipSha256=hash(clipBytes),firstFrameSha256=hash(frameBytes),clipName=`${clipSha256}.mp4`,frameName=`${firstFrameSha256}.jpg`;await fs.writeFile(path.join(destination,clipName),clipBytes);await fs.writeFile(path.join(destination,frameName),frameBytes);details.push({...shot.detail,materialEvidence:{sourceVideoRef:`/api/overseas/videos/${scope.recordId}/media`,sourceSha256:scope.expectedSourceSha256,analysisRunId:scope.expectedAnalysisRunId,startSeconds:shot.start,endSeconds:shot.end,firstFrameSeconds:shot.start+Math.min(.04,(shot.end-shot.start)/4),clipRef:`/media/${relative}/${clipName}`,firstFrameRef:`/media/${relative}/${frameName}`,clipSha256,firstFrameSha256,extractionStatus:'ready'}});}finally{await Promise.all([fs.unlink(clip).catch(()=>{}),fs.unlink(frame).catch(()=>{})]);}}
 await current(scope);await assertDurableOperationLease({dataStore:store,lease,minimumRemainingMs:10000});const payload={scope,details};const recordHash=socialRequestHash(payload);const rows=await store.list<Record_>(EXACT_SHOT_EVIDENCE_COLLECTION,{where:{tenant_id:scope.tenantId,record_id:scope.recordId,source_sha256:scope.expectedSourceSha256,analysis_run_id:scope.expectedAnalysisRunId,analysis_hash:scope.expectedAnalysisHash},perPage:2});if(rows.totalItems>1)fail('reference_shot_evidence_ambiguous');if(rows.items[0]){if(rows.items[0].record_hash!==recordHash)fail('reference_shot_evidence_changed');}else if(!await store.create(EXACT_SHOT_EVIDENCE_COLLECTION,{tenant_id:scope.tenantId,record_id:scope.recordId,source_sha256:scope.expectedSourceSha256,analysis_run_id:scope.expectedAnalysisRunId,analysis_hash:scope.expectedAnalysisHash,record_hash:recordHash,payload,created_at:new Date().toISOString()}))fail('reference_shot_persistence_failed');const fresh=await current(scope),saved=await existingState(scope,fresh),proof=saved?await readEvidence(scope,saved):null;if(!proof)fail('reference_shot_persistence_failed');return {status:'materialized',sourceSha256:scope.expectedSourceSha256,analysisRunId:scope.expectedAnalysisRunId,analysisHash:scope.expectedAnalysisHash,shots:proof};}finally{await releaseDurableOperationLease({dataStore:store,lease});}}};
}
