import {createHash} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import type {DigitalHumanReferenceCue,SentenceFirstFrameDraftResult} from '../../src/lib/digitalHumanPlan.js';
import type {PresenterAsset} from '../../src/lib/shotProduction.js';
import {clusterSourceFirstFrameMaterialId,planPersonShotClusters} from '../../src/lib/personShotClustering.js';
import {readLocalMaterials,saveLocalMaterials,type MaterialRecord} from './materialLibrary.js';
import {acceptSeedancePortrait} from './presenterAssetAcceptance.js';
import {validatePresenterRightsEvidence} from './presenterAssetTrust.js';
import {firstFrameInputFingerprint,type FirstFrameReference} from './firstFrameGenerator.js';
import {QwenFirstFrameGenerator} from './qwenFirstFrameGenerator.js';
import {produceFirstFrame} from './firstFrameProduction.js';
import {objectStorageDownload,objectStorageHead,objectStorageSignedGetUrl} from '../storage/objectStorage.js';
import {materialAssetContentType} from '../storage/materialAssets.js';

const MEDIA_ROOT=path.resolve(process.cwd(),'data/media');
async function bytesFor(material:MaterialRecord,tenantId:string){if(material.scope!=='shared'&&String(material.tenantId||material.tenant_id||'')!==tenantId)throw new Error('首帧草稿素材不属于当前企业');if(material.file){const file=path.resolve(MEDIA_ROOT,String(material.file));if(file.startsWith(MEDIA_ROOT)&&fs.existsSync(file))return{bytes:fs.readFileSync(file),mimeType:materialAssetContentType(file)};}if(material.objectKey){const object=await objectStorageDownload(String(material.objectKey));if(object)return{bytes:object.buf,mimeType:object.contentType};}throw new Error(`素材 ${material.id} 没有可读取文件`);}
const imageMime=(value:string):FirstFrameReference['mimeType']=>/png/i.test(value)?'image/png':/webp/i.test(value)?'image/webp':'image/jpeg';

export async function runProductionQwenFirstFrameDrafts(input:{tenantId:string;projectId:string;assemblyId:string;presenter:PresenterAsset;cues:DigitalHumanReferenceCue[]}):Promise<SentenceFirstFrameDraftResult>{
  const rights=validatePresenterRightsEvidence(input.presenter.rightsEvidence,{provider:'dashscope',uses:['person_replacement']});if(!rights.ok)throw new Error(`千问人物草稿未获独立授权：${rights.reasons.join(',')}`);
  const materials=readLocalMaterials();const byId=new Map(materials.map(item=>[String(item.id),item]));const presenterIds=[...new Set([...(input.presenter.toolMappings?.seedance?.referenceMaterialIds||[]),...(input.presenter.toolMappings?.sd?.referenceMaterialIds||[]),...(input.presenter.referenceMaterialIds||[])])];let presenterReference:FirstFrameReference|null=null;
  for(const id of presenterIds){const material=byId.get(id);if(!material||material.type!=='image')continue;acceptSeedancePortrait({tenantId:input.tenantId,presenter:input.presenter,material});const loaded=await bytesFor(material,input.tenantId);presenterReference={role:'authorized_presenter',bytes:loaded.bytes,mimeType:imageMime(loaded.mimeType),sha256:createHash('sha256').update(loaded.bytes).digest('hex')};break;}if(!presenterReference)throw new Error('企业人物没有可用于千问草稿的已授权图片');
  const plan=planPersonShotClusters(input.cues,Math.max(1,Number(process.env.DIGITAL_HUMAN_MAX_FIRST_FRAMES_PER_VIDEO)||3));if(plan.state!=='ready')throw new Error(plan.blockers.join('；'));const generator=new QwenFirstFrameGenerator();const draftByCluster=new Map<string,{materialId:string;imageUrl:string;operationId:string;estimatedCostCny:number}>();const created:MaterialRecord[]=[];
  for(const cluster of plan.clusters){const sourceId=clusterSourceFirstFrameMaterialId(cluster,input.cues);const source=byId.get(sourceId);if(!source||source.type!=='image')throw new Error(`构图簇 ${cluster.id} 的源首帧不存在`);const loaded=await bytesFor(source,input.tenantId);const sourceReference:FirstFrameReference={role:'source_composition',bytes:loaded.bytes,mimeType:imageMime(loaded.mimeType),sha256:createHash('sha256').update(loaded.bytes).digest('hex')};const request={tenantId:input.tenantId,videoId:`${input.projectId}:${input.assemblyId}`,compositionId:cluster.fingerprint,presenterVersion:`${input.presenter.id}:${input.presenter.assetVersion||1}`,prompt:'构图草稿：严格保持图一机位、景别、姿态意图、产品位置、背景结构与光线，只用图二已授权企业人物替换图一人物。写实自然，不添加文字、徽标、界面或水印。',ratio:'9:16' as const,references:[sourceReference,presenterReference],idempotencyKey:''};request.idempotencyKey=firstFrameInputFingerprint(request,generator.provider,generator.model);const output=await produceFirstFrame(request,generator);const stored=await objectStorageDownload(output.objectKey);const head=await objectStorageHead(output.objectKey);if(!stored?.buf.length||!head?.etag)throw new Error('千问草稿入库后无法复核');const materialId=`qwen-draft-${output.operationId.slice(0,24)}`;const imageUrl=await objectStorageSignedGetUrl(output.objectKey,900);created.push({id:materialId,name:`千问人物构图草稿 · ${cluster.id}`.slice(0,100),folder:'presenter',type:'image',duration:0,size:`${Math.ceil(stored.buf.length/1024)} KB`,file:'',url:'',objectKey:output.objectKey,objectEtag:head.etag,contentSha256:output.contentSha256,scope:'own',tenantId:input.tenantId,usage:'analysis',sourceType:'digital-human-qwen-first-frame-draft',providerRequestId:output.providerRequestId,providerModel:output.model,estimatedCostCny:output.estimatedCostCny,createdAt:new Date().toISOString()});draftByCluster.set(cluster.fingerprint,{materialId,imageUrl,operationId:output.operationId,estimatedCostCny:output.estimatedCostCny});}
  const createdIds=new Set(created.map(item=>item.id));saveLocalMaterials([...readLocalMaterials().filter(item=>!createdIds.has(String(item.id))),...created]);const clusterByCue=new Map(plan.clusters.flatMap(cluster=>cluster.cueIds.map(cueId=>[cueId,cluster.fingerprint] as const)));const cues=input.cues.map(cue=>{const fingerprint=clusterByCue.get(cue.id);const draft=fingerprint?draftByCluster.get(fingerprint):undefined;return draft?{...cue,draftFirstFrame:{provider:'qwen' as const,materialId:draft.materialId,imageUrl:draft.imageUrl,state:'ready' as const,estimatedCostCny:draft.estimatedCostCny}}:cue;});const drafts=[...draftByCluster.values()];return{cues,operationIds:drafts.map(item=>item.operationId),estimatedCostCny:Number(drafts.reduce((sum,item)=>sum+item.estimatedCostCny,0).toFixed(4)),provider:'qwen',state:'completed'};
}
