import {buildStarterPublicationPackage} from './starterPublicationPackage.js';
import test,{type TestContext} from 'node:test';import assert from 'node:assert/strict';
import type {DataStore,Record_,ListQuery} from '../storage/datastore.js';
import {sealAccountCredential} from '../lib/accountCredentials.js';
import {platformAccountIdentityHash} from './platformCapabilities.js';
import {createWeeklyPublishingAdapter} from './weeklyPublishingAdapter.js';
import type {PublicationAssignment} from '../digitalEmployees/publishingExecution.js';import type {DurablePublicationAttempt} from './weeklyLineage.js';
function fixture(t:TestContext,platform:'tiktok'|'facebook'|'instagram'|'youtube'){
 const originalKey=process.env.PLATFORM_TOKEN_ENCRYPTION_KEY;t.after(()=>{if(originalKey===undefined)delete process.env.PLATFORM_TOKEN_ENCRYPTION_KEY;else process.env.PLATFORM_TOKEN_ENCRYPTION_KEY=originalKey;});process.env.PLATFORM_TOKEN_ENCRYPTION_KEY='receipt-read-only-test-key';const now=new Date('2026-10-10T00:00:00Z'),account:Record_={id:'account',tenantId:'tenant',platform,status:'connected',providerAccountId:'native',channelId:'native',accessToken:sealAccountCredential('token'),clientId:'client',clientSecret:sealAccountCredential('secret'),refreshToken:sealAccountCredential('refresh')};
 const rows:Record<string,Record_[]>={[platform==='youtube'?'youtube_accounts':'social_accounts']:[account],social_platform_capability_evidence:[{id:'publish-revoked',tenant_id:'tenant',account_id:'account',platform,capability:'publishing.official',status:'unavailable',evidence_source:'provider_probe',evidence_ref:`provider:${platform}:account:native`,reason_code:'provider_publish_permission_not_granted',verified_at:now.toISOString(),expires_at:'2026-10-10T00:15:00Z'}]};
 if(platform==='tiktok')rows.social_platform_capability_evidence!.push({id:'receipt',tenant_id:'tenant',account_id:'account',platform,capability:'publishing.receipt_lookup',status:'verified',evidence_source:'provider_probe',evidence_ref:'provider:tiktok:receipt:original',account_identity_hash:platformAccountIdentityHash(account,platform),verified_at:now.toISOString(),expires_at:'2026-10-10T00:15:00Z'});
 const store:DataStore={async getById<T>(c:string,id:string){return (rows[c]?.find(r=>r.id===id)??null) as T|null;},async list<T>(c:string,q:ListQuery={}){const all=(rows[c]??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v)),perPage=q.perPage??100,page=q.page??1;return {items:all.slice((page-1)*perPage,page*perPage) as T[],totalItems:all.length,totalPages:Math.ceil(all.length/perPage),page,perPage};},async create<T>(c:string,data:Record<string,unknown>){const r={id:'created',...data};(rows[c]??=[]).push(r);return r as T;},async update(){return false;},async delete(){return false;}};
 const assignment={schemaVersion:'publication-assignment.v1',tenantId:'tenant',accountId:'account',platform,assignmentId:'assignment',packageId:'package'} as PublicationAssignment;
 const attempt:DurablePublicationAttempt={id:'attempt',tenant_id:'tenant',attempt_id:'attempt',assignment_id:'assignment',package_id:'package',provider:platform==='tiktok'?'tiktok-content-posting-api':platform==='youtube'?'youtube-data-api':'meta-graph-api',status:'unknown',provider_receipt_id:'original',started_at:now.toISOString(),updated_at:now.toISOString()};const publicationPackage=buildStarterPublicationPackage({tenantId:'tenant',contentId:'readonly-unit-content',contentVersion:'v1',contentHash:'a'.repeat(64),platform,copy:{title:'只读查询单元测试',body:'不访问媒体或发起发布',hashtags:[]},assets:[{kind:'video',fileName:'source.mp4',downloadUrl:'https://owned.example/source.mp4',contentHash:'a'.repeat(64)}],idempotencyKey:'readonly-unit-package',now});return {now,account,rows,store,assignment,attempt,publicationPackage};
}
for(const platform of ['tiktok','facebook','instagram','youtube'] as const)test(`${platform}: controlled original receipt GET remains usable with revoked publish permission, lookup never POSTs`,async t=>{
 const f=fixture(t,platform);let reads=0,posts=0;const ports={async publish(){posts++;throw Error('must not publish');},async reconcile(){reads++;return {status:'published' as const,providerReceiptId:'original',platformPostId:platform==='tiktok'?'actual-post':'original',platformUrl:'https://provider.example/post',providerStatus:'published',error:''};}};
 const common={tenantId:'tenant',accountId:'account',platform,dataStore:f.store,now:f.now,ports,tiktokPorts:ports};const publish=await createWeeklyPublishingAdapter(common);assert.equal(publish.capability,'unavailable');
 const lookup=await createWeeklyPublishingAdapter({...common,purpose:'receipt_lookup',providerReceiptId:'original'});assert.equal(lookup.capability,'available');const result=await lookup.reconcile({assignment:f.assignment,attempt:f.attempt,publicationPackage:f.publicationPackage});assert.equal(result.status,'published');assert.equal(reads,1);
 assert.equal((await lookup.publish({assignment:f.assignment,publicationPackage:f.publicationPackage,attemptId:'new'})).status,'rejected');assert.equal(posts,0);
 assert.equal((await lookup.reconcile({assignment:f.assignment,attempt:{...f.attempt,package_id:'foreign'},publicationPackage:f.publicationPackage})).status,'unknown');assert.equal(reads,1);
 f.account.tenantId='foreign';assert.equal((await lookup.reconcile({assignment:f.assignment,attempt:f.attempt,publicationPackage:f.publicationPackage})).status,'unknown');assert.equal(reads,1);
});
for(const platform of ['tiktok','facebook'] as const)test(`${platform}: native identity drift while GET is in flight cannot settle`,async t=>{
 const f=fixture(t,platform);let reads=0;const ports={async publish(){throw Error('no POST');},async reconcile(){reads++;f.account.providerAccountId='another-native';return {status:'published' as const,providerReceiptId:'original',platformPostId:'original',platformUrl:'',providerStatus:'published',error:''};}};
 const adapter=await createWeeklyPublishingAdapter({tenantId:'tenant',accountId:'account',platform,dataStore:f.store,now:f.now,purpose:'receipt_lookup',providerReceiptId:'original',ports,tiktokPorts:ports});const result=await adapter.reconcile({assignment:f.assignment,attempt:f.attempt,publicationPackage:f.publicationPackage});assert.equal(result.status,'unknown');assert.equal(reads,1);
});
test('missing original receipt keeps lookup unavailable and cannot initiate a replacement POST',async t=>{const f=fixture(t,'tiktok');const adapter=await createWeeklyPublishingAdapter({tenantId:'tenant',accountId:'account',platform:'tiktok',dataStore:f.store,now:f.now,purpose:'receipt_lookup'});assert.equal(adapter.capability,'unavailable');assert.equal(adapter.unavailableReason,'provider_receipt_missing');assert.equal((await adapter.publish({assignment:f.assignment,publicationPackage:f.publicationPackage,attemptId:'replacement'})).status,'rejected');});
