import { useMemo, useState } from 'react';
import { AlertTriangle, Check, ChevronDown, ScanFace, ShieldCheck, Video } from 'lucide-react';
import { buildPersonReplacementPlan, PERSON_REPLACEMENT_MODE_CONTRACTS, replacementPlanSummary, type PersonReplacementMode, type PersonReplacementModeSelection, type ReferenceShotForReplacement } from '../../lib/runwayPersonReplacement';

const modes: PersonReplacementMode[] = ['fast', 'expert', 'creative'];

export default function RunwayPersonReplacementPanel({ title, videoUrl, shots }: { title?: string; videoUrl?: string; shots: ReferenceShotForReplacement[] }) {
  const [modeSelection, setModeSelection] = useState<PersonReplacementModeSelection>('auto');
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [sourceDerivativeRights, setSourceDerivativeRights] = useState(false);
  const [targetRightsConfirmed, setTargetRightsConfirmed] = useState(false);
  const sourceKind = sourceDerivativeRights ? 'licensed_asset' : 'external_reference';
  const plan = useMemo(() => buildPersonReplacementPlan(shots, modeSelection, { sourceKind }), [shots, modeSelection, sourceKind]);
  const summary = useMemo(() => replacementPlanSummary(plan), [plan]);
  const recommendedModes = [...new Set(plan.filter(item => item.route !== 'preserve').map(item => item.mode))];
  const selectedDisplayMode: PersonReplacementMode = recommendedModes[0] || (modeSelection === 'auto' ? 'creative' : modeSelection);
  const contract = PERSON_REPLACEMENT_MODE_CONTRACTS[selectedDisplayMode];
  return <section className="mb-4 rounded-2xl border border-violet-200 bg-violet-50/40 p-4" aria-labelledby="runway-person-replacement-title">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ScanFace size={18} className="text-violet-700"/><h3 id="runway-person-replacement-title" className="text-sm font-black text-text-primary">爆款分镜人物处理</h3></div><p className="mt-1 text-xs leading-5 text-text-muted">{title || '参考视频'} · 系统按来源、授权和镜头条件自动选择安全制作方式。</p></div><span className="rounded-full bg-violet-100 px-2.5 py-1 text-[10px] font-black text-violet-700">一键托管 · 逐镜规划</span></div>
    {videoUrl && <video src={videoUrl} controls className="mt-3 max-h-64 w-full rounded-xl bg-black object-contain" />}
    <div className="mt-4 rounded-xl border border-violet-200 bg-white p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-black text-text-primary">系统推荐：{recommendedModes.map(item => PERSON_REPLACEMENT_MODE_CONTRACTS[item].shortLabel).join(' / ') || '沿用原片'}</p><p className="mt-1 text-[10px] leading-4 text-text-muted">普通任务自动托管；模型和供应商由内容 Agent 根据质量、成本和授权动态选择。</p></div><button type="button" onClick={() => setShowAdvanced(value => !value)} className="inline-flex shrink-0 items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-[10px] font-black text-text-secondary">高级设置<ChevronDown size={12} className={`transition ${showAdvanced ? 'rotate-180' : ''}`}/></button></div></div>
    {showAdvanced && <div className="mt-3 rounded-xl border border-border bg-white/80 p-3"><p className="text-[10px] font-black text-text-secondary">人物处理方式</p><div className="mt-2 grid gap-2 lg:grid-cols-4"><button type="button" aria-pressed={modeSelection === 'auto'} onClick={() => setModeSelection('auto')} className={`rounded-lg border p-2 text-left ${modeSelection === 'auto' ? 'border-violet-500 bg-violet-50' : 'border-border bg-white'}`}><span className="text-[11px] font-black">自动推荐</span><span className="mt-1 block text-[9px] text-text-muted">根据来源、授权和镜头条件逐镜选择。</span></button>{modes.map(item => { const option = PERSON_REPLACEMENT_MODE_CONTRACTS[item]; return <button key={item} type="button" aria-pressed={modeSelection === item} onClick={() => setModeSelection(item)} className={`rounded-lg border p-2 text-left ${modeSelection === item ? 'border-violet-500 bg-violet-50' : 'border-border bg-white'}`}><span className="flex items-center justify-between gap-2 text-[11px] font-black"><span>{option.shortLabel}</span><span className={`rounded-full px-1.5 py-0.5 text-[8px] ${option.maturity === 'limited' ? 'bg-emerald-100 text-emerald-700' : option.maturity === 'experimental' ? 'bg-rose-100 text-rose-700' : 'bg-amber-100 text-amber-700'}`}>{option.maturityLabel}</span></span><span className="mt-1 block text-[9px] text-text-muted">{option.description}</span></button>; })}</div></div>}
    <label className="mt-3 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900"><input type="checkbox" checked={sourceDerivativeRights} onChange={event => setSourceDerivativeRights(event.target.checked)} className="mt-0.5"/><span><ShieldCheck size={14} className="mr-1 inline"/>该源视频由客户自有或已明确取得分析、派生制作和商业发布授权。未确认时按外部参考处理，只用于结构分析与重新演绎。</span></label>
    <div className={`mt-3 rounded-xl border p-3 ${contract.allowsCompositionChange ? 'border-sky-200 bg-sky-50' : 'border-emerald-200 bg-emerald-50'}`}><p className={`text-[10px] font-black ${contract.allowsCompositionChange ? 'text-sky-800' : 'text-emerald-800'}`}>{contract.allowsCompositionChange ? '创意路线保留边界' : '保真路线锁定项'}</p><div className="mt-2 flex flex-wrap gap-1.5">{contract.lockedElements.map(item => <span key={item} className={`rounded-full bg-white px-2 py-1 text-[9px] font-bold ${contract.allowsCompositionChange ? 'text-sky-700' : 'text-emerald-700'}`}>{item}</span>)}</div><p className={`mt-2 text-[10px] leading-4 ${contract.allowsCompositionChange ? 'text-sky-800' : 'text-emerald-800'}`}>{contract.allowsCompositionChange ? '系统使用合规素材重新实现镜头功能和表达节奏。' : '候选必须通过自动质检，改变锁定内容时不能进入成片。'}</p></div>
    <div className="mt-3 rounded-xl border border-border bg-white p-3"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-black text-text-secondary">当前可用性</p><span className={`rounded-full px-2 py-1 text-[9px] font-black ${contract.maturity === 'limited' ? 'bg-emerald-50 text-emerald-700' : contract.maturity === 'experimental' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{contract.maturityLabel}</span></div><p className="mt-2 text-[10px] font-bold text-text-secondary">适用：{contract.suitableFor.join('；')}</p><p className="mt-1 text-[10px] leading-4 text-text-muted">限制：{contract.limitations.join('；')}</p></div>
    <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-6">{[['总分镜', summary.total], ['自动生成', summary.replace], ['沿用原片', summary.preserve], ['质检/复核', summary.review], ['已阻断', summary.blocked], ['预计生成', `${summary.billableSeconds}s`]].map(([label, value]) => <div key={String(label)} className="rounded-lg border border-violet-100 bg-white px-3 py-2"><p className="text-[9px] font-bold text-text-muted">{label}</p><p className="mt-0.5 text-sm font-black text-text-primary">{value}</p></div>)}</div>
    <div className="mt-4 space-y-2">{plan.map((shot, index) => <article key={shot.id} className="rounded-xl border border-border bg-white p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-black text-text-primary">镜头 {index + 1} · {shot.start.toFixed(1)}–{shot.end.toFixed(1)} 秒</p><p className="mt-1 line-clamp-2 text-[11px] leading-4 text-text-secondary">{shot.summary}</p><p className="mt-1 text-[10px] font-bold text-violet-700">{shot.publicMethodLabel}</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] font-black ${shot.route === 'replace' ? 'bg-emerald-50 text-emerald-700' : shot.route === 'preserve' ? 'bg-slate-100 text-slate-600' : shot.route === 'blocked' ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'}`}>{shot.route === 'replace' ? '生成候选' : shot.route === 'preserve' ? '沿用原片' : shot.route === 'blocked' ? '权利阻断' : '质检/复核'}</span></div><p className="mt-2 text-[10px] text-text-muted">{shot.reasons.join('；')}</p></article>)}</div>
    {!plan.length && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><AlertTriangle size={14} className="mr-1 inline"/>没有可用的精确分镜时间段，请返回灵感中心重新分析。</p>}
    <label className="mt-4 flex items-start gap-2 rounded-xl border border-violet-100 bg-white p-3 text-xs text-text-secondary"><input type="checkbox" checked={targetRightsConfirmed} onChange={event => setTargetRightsConfirmed(event.target.checked)} className="mt-0.5"/><span><ShieldCheck size={14} className="mr-1 inline text-violet-700"/>我会选择已取得肖像与商业使用授权的企业人物资产。</span></label>
    <button type="button" disabled className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-violet-700 px-4 py-3 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{targetRightsConfirmed ? <Check size={16}/> : <Video size={16}/>}预览生成尚未接入</button>
    <p className="mt-2 text-center text-[10px] text-text-muted">当前仅验证逐镜执行方案与质量门槛；不会调用付费生成服务。</p>
  </section>;
}
