import {socialAccessToken} from '../lib/accountCredentials.js';
import {readCustomerMessagingAuthorization} from '../digitalEmployees/customerMessagingPolicy.js';
import {readCanonicalWhatsAppAccount} from '../whatsapp/canonicalAccount.js';
import {readWeeklyCustomerStep,WEEKLY_CUSTOMER_BINDINGS,type WeeklyCustomerAuthority} from './socialWeeklyCustomerBridge.js';
import {verifyWeeklyCustomerChannelReceipt} from '../socialPrograms/weeklyCustomerChannelSelections.js';
import {socialJson,socialObject,socialRequestHash} from '../starter198/socialContentValidation.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {SocialWeeklyExecutionAdapter} from './socialWeeklyExecutionAdapter.js';
import type {VersionedSocialRef,WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';

export const WEEKLY_CUSTOMER_CHANNEL_EXECUTIONS='social_weekly_customer_channel_executions';
type Channel='whatsapp'|'messenger'|'instagram';
type Authority={channel:Channel;accountId:string;nativeAccountId:string;accountHash:string};
type Evidence={evidenceId:string;version:1;kind:'readiness'|'handoff';tenantId:string;programId:string;packageId:string;packageVersion:number;taskId:string;publicationTaskId:string;publicationAccountId:string;channel:Channel;channelAuthority:Authority;runId:string|null;conversationId:string|null;customerId:string|null;providerMessageIds:string[];resultRefs:VersionedSocialRef[];noData:boolean;verifiedAt:string;taskHash:string;recordHash:string};
type Ports={now?:()=>Date;readAuthorization?:typeof readCustomerMessagingAuthorization;readWhatsApp?:typeof readCanonicalWhatsAppAccount;openSocialToken?:typeof socialAccessToken;readStep?:typeof readWeeklyCustomerStep;verifySelection?:typeof verifyWeeklyCustomerChannelReceipt};
const obj=(value:unknown):Record<string,any>=>socialObject(socialJson(value))??{};
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
function fail(code:string):never{throw Error(code);}
async function rows(store:DataStore,collection:string,where:Record<string,string|number>):Promise<Record_[]>{const out:Record_[]=[];for(let page=1;;page++){const r=await store.list<Record_>(collection,{where,page,perPage:250,sort:'id'});if(!Number.isSafeInteger(r.totalItems)||r.items.some(row=>Object.entries(where).some(([k,v])=>row[k]!==v))||r.items.some(row=>out.some(old=>old.id===row.id)))fail('weekly_customer_channel_read_invalid');out.push(...r.items);if(out.length===r.totalItems)return out;if(!r.items.length)fail('weekly_customer_channel_read_incomplete');}}
function channel(task:WeeklyExecutionTask):Channel{const value=task.inputSnapshot.customerChannel;if(!['whatsapp','messenger','instagram'].includes(String(value)))fail('weekly_customer_channel_task_invalid');return value as Channel;}
function taskHash(task:WeeklyExecutionTask){return socialRequestHash({tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,taskId:task.taskId,publicationTaskId:task.publicationTaskId,accountId:task.accountId,stepKind:task.schedule.stepKind,channel:task.inputSnapshot.customerChannel});}
async function authority(store:DataStore,task:WeeklyExecutionTask,ports:Ports={}):Promise<Authority>{
 const c=channel(task),authorization=await (ports.readAuthorization??readCustomerMessagingAuthorization)(task.tenantId,c,{dataStore:store});
 if(!authorization.tenantAuthorized)fail(authorization.reasons.find(reason=>reason!=='followup_background_worker_disabled')??'customer_channel_not_authorized');
 if(!authorization.providerReady)fail(`${c}_provider_not_ready`);
 if(c==='whatsapp'){
  const apps=await rows(store,'tenant_platform_apps',{tenant_id:task.tenantId,platform:'meta'});if(apps.length!==1)fail('whatsapp_account_ambiguous');
  const proof=await (ports.readWhatsApp??readCanonicalWhatsAppAccount)(store,task.tenantId,apps[0]!.id);return{channel:c,accountId:proof.accountId,nativeAccountId:proof.nativeAccountId,accountHash:proof.accountHash};
 }
 const platform=c==='messenger'?'facebook':'instagram',all=await rows(store,'social_accounts',{tenantId:task.tenantId,platform,status:'connected'});
 const candidates=all.filter(account=>{try{if(!text(account.providerAccountId)||account.mock||account.synthetic||account.simulated)return false;if(c==='messenger'&&account.messengerSubscribed!==true)return false;if(c==='instagram'){const login=account.oauthProvider==='instagram_login',scope=login?'instagram_business_manage_messages':'instagram_manage_messages';if(!new Set(String(account.scope??'').split(/[\s,]+/)).has(scope)||login&&account.instagramWebhookSubscribed!==true||!login&&!text(account.parentPageId))return false;}return Boolean((ports.openSocialToken??socialAccessToken)(account));}catch{return false;}});
 const preferred=candidates.filter(account=>account.id===task.accountId);const selected=preferred.length===1?preferred:candidates;
 if(selected.length!==1)fail(`${c}_account_ambiguous`);const account=selected[0]!;
 return{channel:c,accountId:account.id,nativeAccountId:String(account.providerAccountId),accountHash:socialRequestHash({platform:account.platform,providerAccountId:account.providerAccountId,parentPageId:account.parentPageId??null,oauthProvider:account.oauthProvider??null})};
}
async function binding(store:DataStore,task:WeeklyExecutionTask){const found=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion});if(found.length!==1||!text(found[0]!.run_id))fail(found.length?'weekly_customer_binding_ambiguous':'weekly_customer_binding_missing');return found[0]!;}
async function handoff(store:DataStore,task:WeeklyExecutionTask,a:Authority,ports:Ports={}){
 const b=await binding(store,task),scope:WeeklyCustomerAuthority={tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion};
 const result=await (ports.readStep??readWeeklyCustomerStep)(store,scope,String(b.run_id),'customer_followup_dispatch');
 if(result.status==='blocked')fail(result.reason??'weekly_customer_dispatch_pending');
 if(result.status==='no_data')return{runId:String(b.run_id),conversationId:null,customerId:null,providerMessageIds:[] as string[],resultRefs:result.resultRefs,noData:true};
 const selection=await (ports.verifySelection??verifyWeeklyCustomerChannelReceipt)(store,{tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,runId:String(b.run_id),goalId:String(b.goal_id),route:(obj((await rows(store,'social_programs',{tenant_id:task.tenantId,program_id:task.programId}))[0]?.payload).route),weekStart:String((await store.getById<Record_>('weekly_goals',String(b.goal_id)))?.starts_at),weekEnd:String((await store.getById<Record_>('weekly_goals',String(b.goal_id)))?.ends_at)} as any,a.channel);
 if(!selection||selection.accountId!==a.accountId||selection.nativeAccountId!==a.nativeAccountId)fail('weekly_customer_channel_selection_missing');
 const ref=result.resultRefs.find(item=>item.type==='weekly_customer_followup_batch');if(!ref)fail('weekly_customer_batch_ref_missing');
 const items=await rows(store,'followup_batch_items',{tenant_id:task.tenantId,batch_id:ref.id});const matches=items.filter(item=>item.channel===a.channel&&obj(item.channel_selection).recordHash===selection.recordHash&&!['excluded','cancelled'].includes(String(item.status)));
 if(!matches.length)fail('weekly_customer_channel_dispatch_missing');
 const providerMessageIds=matches.map(item=>text(item.provider_message_id));if(providerMessageIds.some(id=>!id||/^(mock|simulat)/i.test(id))||matches.some(item=>!['sent','delivered','read'].includes(String(item.status))||!Object.keys(obj(item.provider_receipt)).length))fail('weekly_customer_channel_receipt_pending');
 return{runId:String(b.run_id),conversationId:selection.conversationId,customerId:selection.customerId,providerMessageIds,resultRefs:result.resultRefs,noData:false};
}
async function persist(store:DataStore,task:WeeklyExecutionTask,kind:Evidence['kind'],a:Authority,data:Awaited<ReturnType<typeof handoff>>|null,now:Date){const body:Omit<Evidence,'recordHash'>={evidenceId:`wcce_${socialRequestHash([task.taskId,kind]).slice(0,24)}`,version:1,kind,tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,taskId:task.taskId,publicationTaskId:String(task.publicationTaskId),publicationAccountId:String(task.accountId),channel:a.channel,channelAuthority:a,runId:data?.runId??null,conversationId:data?.conversationId??null,customerId:data?.customerId??null,providerMessageIds:data?.providerMessageIds??[],resultRefs:data?.resultRefs??[],noData:data?.noData??false,verifiedAt:now.toISOString(),taskHash:taskHash(task)};const evidence={...body,recordHash:socialRequestHash(body)};const old=await rows(store,WEEKLY_CUSTOMER_CHANNEL_EXECUTIONS,{tenant_id:task.tenantId,task_id:task.taskId});if(old.length>1)fail('weekly_customer_channel_evidence_ambiguous');if(old.length){const p=obj(old[0]!.payload) as Evidence;if(p.taskHash!==evidence.taskHash||p.kind!==kind)fail('weekly_customer_channel_evidence_conflict');await store.update(WEEKLY_CUSTOMER_CHANNEL_EXECUTIONS,old[0]!.id,{payload:evidence,content_hash:evidence.recordHash,updated_at:evidence.verifiedAt});}else await store.create(WEEKLY_CUSTOMER_CHANNEL_EXECUTIONS,{id:evidence.evidenceId,tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion,task_id:task.taskId,content_hash:evidence.recordHash,payload:evidence,created_at:evidence.verifiedAt,updated_at:evidence.verifiedAt});return{type:'weekly_customer_channel_execution',id:evidence.evidenceId,version:1} as VersionedSocialRef;}
export function createSocialWeeklyCustomerChannelAdapter(store:DataStore,options:Ports={}):SocialWeeklyExecutionAdapter{return{async execute(task){try{if(!['customer_channel_readiness','customer_inquiry_handoff'].includes(task.schedule.stepKind)||task.schedule.responsibleActor!=='customer_agent'||!task.publicationTaskId||!task.accountId)return{status:'blocked',code:'weekly_customer_channel_task_invalid',message:'客服承接任务身份无效。'};const a=await authority(store,task,options);if(task.schedule.stepKind==='customer_channel_readiness')return{status:'succeeded',resultRefs:[await persist(store,task,'readiness',a,null,options.now?.()??new Date())]};const data=await handoff(store,task,a,options);return{status:'succeeded',resultRefs:[await persist(store,task,'handoff',a,data,options.now?.()??new Date())]};}catch(error){const code=error instanceof Error?error.message:'weekly_customer_channel_unavailable';const pending=/pending|unknown|identity_gap|receipt/.test(code);return pending?{status:'pending',code,message:'客服渠道正在核对原始回执，不会重复发送。',retryDelayMs:30_000}:{status:'blocked',code,message:'客服渠道授权、周运行绑定或真实承接证据尚未就绪。'};}}};}
export async function validateWeeklyCustomerChannelExecution(store:DataStore,task:WeeklyExecutionTask,refs:VersionedSocialRef[]){if(refs.length!==1||refs[0]!.type!=='weekly_customer_channel_execution'||refs[0]!.version!==1)fail('weekly_customer_channel_result_ref_invalid');const found=await rows(store,WEEKLY_CUSTOMER_CHANNEL_EXECUTIONS,{tenant_id:task.tenantId,task_id:task.taskId});if(found.length!==1)fail('weekly_customer_channel_evidence_missing');const p=obj(found[0]!.payload) as Evidence,{recordHash,...body}=p;if(found[0]!.id!==refs[0]!.id||found[0]!.content_hash!==recordHash||socialRequestHash(body)!==recordHash||p.taskHash!==taskHash(task)||p.channel!==channel(task)||p.publicationTaskId!==task.publicationTaskId||p.publicationAccountId!==task.accountId)fail('weekly_customer_channel_evidence_changed');const a=await authority(store,task);if(socialRequestHash(a)!==socialRequestHash(p.channelAuthority))fail('weekly_customer_channel_authority_changed');if(p.kind==='handoff'){const live=await handoff(store,task,a);if(live.runId!==p.runId||live.conversationId!==p.conversationId||live.customerId!==p.customerId||socialRequestHash(live.providerMessageIds)!==socialRequestHash(p.providerMessageIds)||socialRequestHash(live.resultRefs)!==socialRequestHash(p.resultRefs)||live.noData!==p.noData)fail('weekly_customer_channel_handoff_changed');}else if(task.schedule.stepKind!=='customer_channel_readiness')fail('weekly_customer_channel_evidence_kind_invalid');}
