import {realSalesConversationMessage} from '../socialPrograms/salesConversationMessage.js';
import type {WeeklyCustomerRelationshipCheck} from '../../shared/contracts/customerRelationshipEvidence.js';
import { assessCustomerRelationship } from '../socialPrograms/customerRelationshipEvidence.js';
import { createHash } from 'node:crypto';
import type { DataStore, Record_ } from '../storage/datastore.js';
import { publicationInstant } from '../socialPrograms/publicationDeadlines.js';
import { organizationRoleOrNull } from '../lib/organizationRole.js';
import { SocialProgramError } from '../socialPrograms/service.js';
import { readWeeklyCustomerStep, type WeeklyCustomerAuthority, WEEKLY_CUSTOMER_BINDINGS } from './socialWeeklyCustomerBridge.js';
import type { WeeklySalesHandoff, WeeklySalesStatus, WeeklySalesSource } from '../../shared/contracts/socialWeeklySalesHandoff.js';
export const SALES_HANDOFFS = 'social_weekly_sales_handoffs';
export const SALES_EVENTS = 'social_weekly_sales_events';
function fail(code:string,status=409):never {throw new SocialProgramError(code,status,code);}
const object = (v: unknown): Record<string, any> => { if (typeof v === 'string') { try { return object(JSON.parse(v)); } catch { return {}; } } return v && typeof v === 'object' && !Array.isArray(v) ? v as Record<string, any> : {}; };
const required = (v: unknown): string => typeof v === 'string' && v.trim() ? v.trim() : fail('sales_handoff_required',400);
const date = (v: unknown): string => { const s = required(v); if (publicationInstant(s)===null) fail('sales_handoff_time_invalid',400); return s; };
async function rows(store: DataStore, collection: string, where: Record<string,string|number>) { const all: Record_[]=[];const seen=new Set<string>();let total:number|undefined;for(let page=1;;page++){const r=await store.list<Record_>(collection,{where,page,perPage:250,sort:'id'});if(!Number.isSafeInteger(r.totalPages)||r.totalPages<0||!Number.isSafeInteger(r.totalItems)||r.totalItems<0||total!==undefined&&total!==r.totalItems)fail('sales_handoff_pagination_invalid');total=r.totalItems;for(const row of r.items){if(seen.has(row.id))fail('sales_handoff_pagination_duplicate');seen.add(row.id);all.push(row);}if(page>=r.totalPages){if(all.length!==r.totalItems)fail('sales_handoff_pagination_truncated');return all;}if(!r.items.length)fail('sales_handoff_pagination_truncated');} }
async function user(store:DataStore, tenant:string,id:string) { const r=await store.getById<Record_>('users',required(id)); if (!r || r.tenantId!==tenant || !organizationRoleOrNull(r.role) || r.disabled===true || r.active===false || ['disabled','suspended'].includes(String(r.status))) fail('sales_handoff_user_forbidden',403); return r; }
async function interaction(store:DataStore,tenant:string,customer:string,id:string,types:string[]) {
 const found=await rows(store,'whatsapp_interactions',{tenant_id:tenant,customer_id:customer,interaction_id:required(id)}); if(found.length!==1)fail('sales_handoff_conversation_missing'); const p=object(found[0]!.payload);if(!realSalesConversationMessage(found[0]!,tenant,customer,0,Date.now()))fail('sales_handoff_provider_conversation_required');
 if(p.tenantId!==tenant || p.customerId!==customer || p.id!==id || !types.includes(p.type) || !required(p.body) || !Number.isFinite(p.timestamp) || p.timestamp<=0 || p.mock || p.synthetic || p.simulated || object(p.audit).mock || object(p.meta).synthetic)fail('sales_handoff_conversation_invalid'); return p;
}
async function assertScope(store:DataStore,a:WeeklyCustomerAuthority){const p=await rows(store,'social_weekly_operating_packages',{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.packageVersion});if(p.length!==1)fail('sales_handoff_package_not_found',404);const value=object(p[0]!.payload);if(value.programId!==a.programId||value.packageId!==a.packageId||value.version!==a.packageVersion)fail('sales_handoff_package_corrupt');}
export function createWeeklySalesHandoffService(store:DataStore) {
 const get=async(a:WeeklyCustomerAuthority,id:string,actor:string):Promise<WeeklySalesHandoff>=>{
  await assertScope(store,a);await user(store,a.tenantId,actor); const r=await store.getById<Record_>(SALES_HANDOFFS,id);
  if(!r || r.tenant_id!==a.tenantId || r.program_id!==a.programId)fail('sales_handoff_not_found',404);
  const p={...object(r!.payload),id:r!.id} as WeeklySalesHandoff;if(p.tenantId!==a.tenantId||p.programId!==a.programId)fail('sales_handoff_scope_corrupt');if(p.packageId!==a.packageId||p.packageVersion!==a.packageVersion)fail('sales_handoff_original_scope_required'); if(p.createdBy!==actor && p.ownerUserId!==actor)fail('sales_handoff_actor_forbidden',403);
  const originalBindings=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion});if(originalBindings.length!==1||originalBindings[0]!.run_id!==p.runId)fail('sales_handoff_relationship_binding_missing');const originalGoal=await store.getById<Record_>('weekly_goals',String(originalBindings[0]!.goal_id));const frozenRelation=object(p.sourceEvidence).relationship;if(!originalGoal||frozenRelation?.weekStart!==originalGoal.starts_at||frozenRelation?.weekEnd!==originalGoal.ends_at)fail('sales_handoff_relationship_window_invalid');if(!frozenRelation||!['new_inquiry','existing_customer'].includes(frozenRelation.classification)||frozenRelation.classification!==p.sourceKind||frozenRelation.tenantId!==a.tenantId||frozenRelation.customerId!==p.customerId)fail('sales_handoff_relationship_contract_required');const liveRelation=await assessCustomerRelationship(store,{tenantId:a.tenantId,customerId:p.customerId,weekStart:String(frozenRelation.weekStart),weekEnd:String(frozenRelation.weekEnd)});if(liveRelation.classification!==p.sourceKind||liveRelation.evidenceHash!==frozenRelation.evidenceHash)fail('sales_handoff_relationship_evidence_changed');
  const events=await rows(store,SALES_EVENTS,{tenant_id:a.tenantId,handoff_id:id}); const sorted=events.sort((x,y)=>Number(x.version)-Number(y.version)); let current={...p};
  for(const e of sorted){const patch=object(e.payload);if(e.actor_id!==p.ownerUserId||publicationInstant(String(e.occurred_at))===null||Object.keys(patch).some(k=>!['status','claimedAt','feedback'].includes(k))||!['in_progress','awaiting_feedback','handled','needs_information'].includes(patch.status))fail('sales_handoff_event_corrupt');if(Number(e.version)!==current.version+1)fail('sales_handoff_event_gap');current={...current,...object(e.payload),version:Number(e.version)};}
  return current;
 };
 return {get,
 async sources(a:WeeklyCustomerAuthority,actor:string):Promise<{items:WeeklySalesSource[];gaps:string[];relationshipChecks?:WeeklyCustomerRelationshipCheck[]}>{
  await assertScope(store,a);await user(store,a.tenantId,actor);const bindings=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion});if(bindings.length!==1)return {items:[],gaps:['尚未绑定唯一真实客服运行']};const binding=bindings[0]!;if(binding.bound_by!==actor)fail('sales_handoff_creator_forbidden',403);
  const actualGoal=await store.getById<Record_>('weekly_goals',String(binding.goal_id));if(actualGoal?.tenant_id!==a.tenantId||publicationInstant(String(actualGoal.starts_at))===null||publicationInstant(String(actualGoal.ends_at))===null)fail('sales_handoff_week_invalid');
  const segmentRows=(await rows(store,'customer_segments',{tenant_id:a.tenantId,run_id:String(binding.run_id)})).filter(r=>r.goal_id===binding.goal_id&&Number.isSafeInteger(r.version)).sort((x,y)=>Number(y.version)-Number(x.version));const selectedSegment=segmentRows[0];if(selectedSegment&&segmentRows.filter(r=>r.version===selectedSegment.version).length!==1)fail('sales_handoff_segment_ambiguous');
  const relationshipChecks:WeeklyCustomerRelationshipCheck[]=[];
  if(selectedSegment)for(const member of await rows(store,'customer_segment_members',{tenant_id:a.tenantId,segment_id:selectedSegment.id})){const id=String(member.customer_id);const customers=await rows(store,'whatsapp_customers',{tenant_id:a.tenantId,customer_id:id});const c=object(customers[0]?.payload);if(customers.length!==1||c.id!==id||c.tenantId!==a.tenantId)continue;relationshipChecks.push({programId:a.programId,packageId:a.packageId,packageVersion:a.packageVersion,segmentId:selectedSegment.id,segmentVersion:Number(selectedSegment.version),runId:String(binding.run_id),memberId:member.id,customerId:id,customerName:String(c.name||id),weekStart:String(actualGoal!.starts_at),weekEnd:String(actualGoal!.ends_at),assessment:await assessCustomerRelationship(store,{tenantId:a.tenantId,customerId:id,weekStart:String(actualGoal!.starts_at),weekEnd:String(actualGoal!.ends_at)})});}
  const proof=await readWeeklyCustomerStep(store,a,String(binding.run_id),'customer_followup_approval');if(proof.status!=='succeeded')return {items:[],gaps:[`客服交接资料尚未通过真实批准：${proof.reason??proof.status}`],relationshipChecks};const ref=proof.resultRefs.find(r=>r.type==='weekly_customer_followup_batch');if(!ref)fail('sales_handoff_batch_missing');const batch=await store.getById<Record_>('followup_batches',ref!.id);if(!batch)fail('sales_handoff_batch_missing');
  const allMembers=await rows(store,'customer_segment_members',{tenant_id:a.tenantId,segment_id:String(batch!.segment_id)});const approvedItems=await rows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:batch.id});const members=allMembers.filter(member=>approvedItems.some(i=>i.segment_member_id===member.id&&i.customer_id===member.customer_id&&i.status!=='excluded'&&!i.exclusion_reason&&typeof i.draft_body==='string'&&i.draft_body.trim()));const programs=await rows(store,'social_programs',{tenant_id:a.tenantId,program_id:a.programId});const route=object(programs[0]?.payload).route;if(programs.length!==1||!['cold_start','account_repair'].includes(route))return {items:[],gaps:['经营画像尚未明确']};const goal=await store.getById<Record_>('weekly_goals',String(binding.goal_id));const start=publicationInstant(String(goal?.starts_at)),end=publicationInstant(String(goal?.ends_at));if(start===null||end===null)fail('sales_handoff_week_invalid');
  const items:WeeklySalesSource[]=[],gaps:string[]=[];for(const member of members.filter(r=>r.membership==='included')){const id=String(member.customer_id),customers=await rows(store,'whatsapp_customers',{tenant_id:a.tenantId,customer_id:id});const c=object(customers[0]?.payload);if(customers.length!==1||c.tenantId!==a.tenantId||c.id!==id){gaps.push(`${id}：客户身份不可核验`);continue;}const relationship=await assessCustomerRelationship(store,{tenantId:a.tenantId,customerId:id,weekStart:String(goal!.starts_at),weekEnd:String(goal!.ends_at)});if(relationship.classification==='unknown'){gaps.push(`${id}：新旧关系待真实证据或实名人工确认`);continue;}const sourceKind=relationship.classification;if(route==='cold_start'&&sourceKind==='existing_customer')continue;const interactions=await rows(store,'whatsapp_interactions',{tenant_id:a.tenantId,customer_id:id});let included=0;for(const row of interactions){const p=object(row.payload);if(p.type!=='msg_in')continue;if(sourceKind==='new_inquiry'&&(p.timestamp<start||p.timestamp>end))continue;try{await interaction(store,a.tenantId,id,String(row.interaction_id),['msg_in']);items.push({runId:String(binding.run_id),memberId:member.id,customerId:id,customerName:String(c.name||id),sourceInteractionId:String(row.interaction_id),body:p.body,timestamp:p.timestamp,sourceKind});included++;}catch{gaps.push(`${id}：会话证据不完整`);}}if(!included)gaps.push(`${id}：未发现对应真实买家询盘`);}return {items,gaps,relationshipChecks};
 },
 async list(a:WeeklyCustomerAuthority,actor:string){await assertScope(store,a);await user(store,a.tenantId,actor);const found=await rows(store,SALES_HANDOFFS,{tenant_id:a.tenantId,program_id:a.programId});const eligible=found.filter(r=>{const p=object(r.payload);return p.ownerUserId===actor||p.createdBy===actor;});return Promise.all(eligible.map(r=>{const p=object(r.payload);return get({...a,packageId:p.packageId,packageVersion:p.packageVersion},r.id,actor);}));},
 async create(a:WeeklyCustomerAuthority,actor:string,input:{runId:string;memberId:string;sourceInteractionId:string;ownerUserId:string;claimDueAt:string;feedbackDueAt:string}) {
  await assertScope(store,a);await user(store,a.tenantId,actor);await user(store,a.tenantId,input.ownerUserId);const claimDueAt=date(input.claimDueAt),feedbackDueAt=date(input.feedbackDueAt);if(Date.parse(feedbackDueAt)<Date.parse(claimDueAt))fail('sales_handoff_deadline_order',400);
  const proof=await readWeeklyCustomerStep(store,a,required(input.runId),'customer_followup_approval');if(proof.status!=='succeeded')fail('sales_handoff_approved_material_required');
  const bindings=await rows(store,WEEKLY_CUSTOMER_BINDINGS,{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,package_version:a.packageVersion});if(bindings.length!==1)fail('sales_handoff_binding_ambiguous');const binding=bindings[0];if(!binding||binding.bound_by!==actor)fail('sales_handoff_creator_forbidden',403);
  const member=await store.getById<Record_>('customer_segment_members',required(input.memberId));if(!member||member.tenant_id!==a.tenantId||member.membership!=='included')fail('sales_handoff_member_invalid');
  const segment=await store.getById<Record_>('customer_segments',String(member.segment_id));if(!segment||segment.run_id!==input.runId||segment.tenant_id!==a.tenantId)fail('sales_handoff_member_run_mismatch');
  const ref=proof.resultRefs.find(r=>r.type==='weekly_customer_followup_batch');if(!ref)fail('sales_handoff_batch_missing');const batch=await store.getById<Record_>('followup_batches',ref!.id);if(!batch||batch.segment_id!==segment.id)fail('sales_handoff_batch_member_mismatch');
  const selectedItems=await rows(store,'followup_batch_items',{tenant_id:a.tenantId,batch_id:batch.id,segment_member_id:member.id});if(selectedItems.length!==1||selectedItems[0]!.customer_id!==member.customer_id||selectedItems[0]!.status==='excluded'||selectedItems[0]!.exclusion_reason||!required(selectedItems[0]!.draft_body))fail('sales_handoff_member_material_unapproved');
  const customerId=required(member.customer_id);const customers=await rows(store,'whatsapp_customers',{tenant_id:a.tenantId,customer_id:customerId});if(customers.length!==1)fail('sales_handoff_customer_missing');const customer=object(customers[0]!.payload);if(customer.tenantId!==a.tenantId||customer.id!==customerId)fail('sales_handoff_customer_invalid');
  const source=await interaction(store,a.tenantId,customerId,input.sourceInteractionId,['msg_in']);const pkgRows=await rows(store,'social_weekly_operating_packages',{tenant_id:a.tenantId,program_id:a.programId,package_id:a.packageId,version:a.packageVersion});if(pkgRows.length!==1)fail('sales_handoff_package_missing');const goal=await store.getById<Record_>('weekly_goals',String(binding.goal_id));const start=publicationInstant(String(goal?.starts_at)),end=publicationInstant(String(goal?.ends_at));if(start===null||end===null)fail('sales_handoff_week_invalid');
  const relationship=await assessCustomerRelationship(store,{tenantId:a.tenantId,customerId,weekStart:String(goal!.starts_at),weekEnd:String(goal!.ends_at)});if(relationship.classification==='unknown')fail('sales_handoff_relationship_unknown');const sourceKind=relationship.classification;if(sourceKind==='new_inquiry'&&(source.timestamp<start||source.timestamp>end))fail('sales_handoff_new_inquiry_outside_week');
  const programs=await rows(store,'social_programs',{tenant_id:a.tenantId,program_id:a.programId});const route=object(programs[0]?.payload).route;if(programs.length!==1||!['cold_start','account_repair'].includes(route))fail('sales_handoff_profile_unknown');if(route==='cold_start'&&sourceKind!=='new_inquiry')fail('sales_handoff_existing_customer_not_cold_start');
  const sourceKey=createHash('sha256').update(JSON.stringify([a.tenantId,a.programId,customerId,input.sourceInteractionId])).digest('hex');const old=await rows(store,SALES_HANDOFFS,{tenant_id:a.tenantId,source_key:sourceKey});if(old.length>1)fail('sales_handoff_source_ambiguous');if(old.length){const existing=await get(a,old[0]!.id,actor);if(existing.ownerUserId!==input.ownerUserId||existing.claimDueAt!==claimDueAt||existing.feedbackDueAt!==feedbackDueAt)fail('sales_handoff_source_conflict');return existing;}
  const payload:Omit<WeeklySalesHandoff,'id'>={...a,runId:input.runId,memberId:input.memberId,customerId,sourceInteractionId:input.sourceInteractionId,sourceKind,sourceEvidence:{interactionId:source.id,timestamp:source.timestamp,body:source.body,relationship,attribution:customer.sourcePostId?{postId:customer.sourcePostId,trackCode:customer.sourceTrackCode??null}:null},ownerUserId:input.ownerUserId,createdBy:actor,claimDueAt,feedbackDueAt,approvedBatchId:batch.id,approvedBatchVersion:Number(batch.version),approvedContentHash:String(batch.content_hash),status:'awaiting_claim',version:1,claimedAt:null,feedback:null};
  const created=await store.create<Record_>(SALES_HANDOFFS,{tenant_id:a.tenantId,program_id:a.programId,source_key:sourceKey,payload});if(!created)fail('sales_handoff_persist_failed',500);return {...payload,id:created!.id};
 },
 async transition(a:WeeklyCustomerAuthority,id:string,actor:string,input:{expectedVersion:number;operationId:string;action:'claim'|'request_feedback'|'feedback';feedback?:{result:string;evidenceInteractionIds:string[];nextStep:string;nextDueAt:string;needsInformation?:boolean}}){
  const item=await get(a,id,actor);if(item.ownerUserId!==actor)fail('sales_handoff_owner_required',403);const op=required(input.operationId);const fingerprint=createHash('sha256').update(JSON.stringify(input)).digest('hex');const prior=await rows(store,SALES_EVENTS,{tenant_id:a.tenantId,handoff_id:id,operation_id:op});if(prior.length){if(prior[0]!.input_hash!==fingerprint)fail('sales_handoff_replay_conflict');return item;}if(input.expectedVersion!==item.version)fail('sales_handoff_version_conflict');
  const now=new Date().toISOString();let status:WeeklySalesStatus;let patch:Record<string,unknown>={};
  if(input.action==='claim'){if(item.status!=='awaiting_claim')fail('sales_handoff_transition_invalid');status='in_progress';patch.claimedAt=now;}
  else if(input.action==='request_feedback'){if(item.status!=='in_progress')fail('sales_handoff_transition_invalid');status='awaiting_feedback';}
  else if(input.action==='feedback'){if(!['in_progress','awaiting_feedback','needs_information'].includes(item.status)||!input.feedback)fail('sales_handoff_transition_invalid');const f=input.feedback!;if(!Array.isArray(f.evidenceInteractionIds)||!f.evidenceInteractionIds.length)fail('sales_handoff_feedback_evidence_required');for(const evidence of f.evidenceInteractionIds){const p=await interaction(store,a.tenantId,item.customerId,evidence,['msg_in','msg_out_human']);if(p.timestamp<Date.parse(item.claimedAt!))fail('sales_handoff_feedback_evidence_stale');}status=f.needsInformation?'needs_information':'handled';patch.feedback={result:required(f.result),evidenceInteractionIds:[...new Set(f.evidenceInteractionIds)],nextStep:required(f.nextStep),nextDueAt:date(f.nextDueAt),recordedAt:now};}
  else return fail('sales_handoff_action_invalid',400);
  const saved=await store.create(SALES_EVENTS,{tenant_id:a.tenantId,handoff_id:id,version:item.version+1,operation_id:op,input_hash:fingerprint,actor_id:actor,payload:{...patch,status},occurred_at:now});if(!saved)fail('sales_handoff_event_persist_failed',500);return get(a,id,actor);
 }
 };
}
