import test from 'node:test';
import assert from 'node:assert/strict';

test('actual owned product route exposes exact prerequisite before original scheduler can create a run',async t=>{
 const keys=['SEEDANCE_VIDEO_ENABLED','SEEDANCE_API_KEY','SEEDREAM_API_KEY'] as const;const old=Object.fromEntries(keys.map(key=>[key,process.env[key]]));t.after(()=>{for(const key of keys){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});process.env.SEEDANCE_VIDEO_ENABLED='true';process.env.SEEDANCE_API_KEY='controlled-no-real-provider';process.env.SEEDREAM_API_KEY='controlled-no-real-provider';
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');const {assessWeeklyOwnedProductIdentity,bindWeeklyOwnedProductIdentity,resumeWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const {repository,f,pkg,task,created,actual}=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true});
 const scope={tenantId:task.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:task.publicationTaskId!,contentTaskId:String(created.task_id)};
 const result=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});
 assert.equal(result.required,true);assert.equal(result.status,'blocked');assert.deepEqual(result.gaps,['weekly_owned_product_identity_verification_required']);
 assert.ok(result.consumerTaskId);assert.ok(result.requirements.length);for(const requirement of result.requirements){assert.ok(requirement.sceneIds.length);assert.ok(requirement.productRef);assert.ok(requirement.imageHashes.every(hash=>/^[a-f0-9]{64}$/.test(hash)));}
 assert.equal(actual.lastError?.code,'weekly_owned_product_identity_verification_required');assert.ok(!created.run_id);assert.equal(f.tables.workflow_runs?.filter(row=>(row.starter_context as Record<string,unknown>|undefined)?.socialTaskId===scope.contentTaskId).length??0,0);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,{...scope,tenantId:'foreign'},{repository}),{code:'weekly_owned_product_identity_scope_invalid'});
 const row=f.tables.starter_social_content_tasks!.find(row=>row.task_id===scope.contentTaskId);assert.ok(row);const original=row.brief;row.brief={...(original as object),_weeklyOwnedProductIdentityDemand:{schemaVersion:'weekly-owned-product-identity.v1',...scope,version:Number(row.version),consumerTaskId:result.consumerTaskId,requirementHash:result.requirementHash,requirements:result.requirements,bindings:[],boundBy:'owner',boundAt:new Date().toISOString(),recordHash:'0'.repeat(64)}};
 const forged=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(forged.status,'blocked');assert.deepEqual(forged.gaps,['weekly_owned_product_identity_binding_changed']);row.brief=original;
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(item=>result.requirements[0]?.imageIds.includes(item.id));assert.ok(image);assert.ok(typeof image.url==='string');const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));
 const recordId='material0000001',sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`,sha=String(image.contentSha256);let currentBytes=bytes;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?structuredClone(raw):null,materialBytes:{fetch:async()=>new Response(currentBytes,{headers:{'content-type':'image/png','content-length':String(currentBytes.length)}})}};
 const service=createWeeklyMaterialRequestService(f.store,materialPorts),consumerId=result.consumerTaskId;assert.ok(consumerId);const requirement=result.requirements[0];assert.ok(requirement);assert.equal(result.requirements.length,1);
 const consumerRow=f.tables.social_weekly_execution_tasks!.find(row=>row.task_id===consumerId);assert.ok(consumerRow);(consumerRow.payload as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask).scope='content';
 const request=await service.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-09T08:00:00+08:00',verificationDueAt:'2026-10-09T09:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:consumerId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'实际核验产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const bindingInput={actorUserId:'owner',expectedTaskVersion:result.contentTaskVersion,expectedRequirementHash:result.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]};
 await bindWeeklyOwnedProductIdentity(f.store,scope,bindingInput,ports);assert.equal((await assessWeeklyOwnedProductIdentity(f.store,scope,ports)).status,'blocked');
 await service.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});
 await service.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:consumerId,accepted:true,factCheck:'指定产品外观对应真实企业产品',rightsCheck:'指定企业拥有素材并授权目标账号商业使用',visualCheck:'身份包装与该组镜头要求一致'}]});
 const beforeAttach=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.deepEqual(beforeAttach.gaps,['weekly_owned_product_identity_source_not_bound']);assert.equal(beforeAttach.materials[0]?.sourceBound,false);
 await bindWeeklyOwnedProductIdentity(f.store,scope,{...bindingInput,expectedTaskVersion:beforeAttach.contentTaskVersion},ports);const ready=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.equal(ready.status,'ready');assert.equal(ready.materials[0]?.sourceBound,true);
 currentBytes=Buffer.from('changed actual physical bytes');await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports));assert.ok(!row.run_id);assert.equal(f.tables.content_execution_jobs?.length??0,0);currentBytes=bytes;
 const {startSocialContentTask}=await import('../starter198/socialContentTasks.js');const {scheduleSocialContentWork}=await import('../starter198/socialContentScheduler.js');const {readWeeklyReferenceSources,weeklyReferenceResolver}=await import('./socialWeeklyReferenceSource.js');
 const plans=f.tables.social_weekly_agent_planning!.map(row=>row.payload as import('../../shared/contracts/socialProgram.js').WeeklyAgentPlanningState).filter(plan=>plan.status==='dispatched');assert.equal(plans.length,1);const analysis=plans[0]?.directorAnalyses[0];assert.ok(analysis);const authority=(row.brief as Record<string,unknown>)._weeklyAuthority;const references=await readWeeklyReferenceSources(f.store,'t',authority,analysis);
 const originalVersion=ready.contentTaskVersion;const started=await startSocialContentTask({repository,tenantId:'t',userId:'owner',taskId:scope.contentTaskId,expectedVersion:String(originalVersion),idempotencyKey:'owned-reviewed-original-scheduler-start',referenceResolver:weeklyReferenceResolver(references),orchestratorQueue:{enqueue:queue=>scheduleSocialContentWork({repository,queue,now:new Date(),materialEvidencePorts:ports})}});
 assert.ok(started.runId);const run=f.tables.workflow_runs!.find(run=>run.id===started.runId);assert.ok(run);const context=run.starter_context as Record<string,unknown>;const schedulerProof=context.weeklyMaterialPlan as import('../starter198/socialWeeklySchedulerMaterialPlan.js').WeeklySchedulerMaterialPlanProof;assert.ok(schedulerProof);assert.equal(Number(started.version),Number(schedulerProof.originalTaskVersion)+1);assert.equal(schedulerProof.scheduledTaskVersion,started.version);assert.ok(Number(schedulerProof.originalTaskVersion)>=originalVersion);assert.ok(context.weeklyReplicationAuthority);
 const {readWeeklyReplicationAuthority}=await import('../starter198/socialWeeklyReplicationAuthority.js');const actualTask=await repository.get('starter_social_content_tasks','t',row.id);assert.ok(actualTask);assert.ok(await readWeeklyReplicationAuthority(repository,actualTask));
 const running=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.equal(running.status,'ready');assert.equal(running.materials[0]?.sourceBound,true);assert.equal(f.tables.content_execution_jobs?.length??0,0,'formal scheduler proof does not claim producer or paid supplier execution');assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 await assert.rejects(bindWeeklyOwnedProductIdentity(f.store,scope,{...bindingInput,expectedTaskVersion:Number(started.version)},ports),{code:'weekly_owned_product_identity_binding_changed'});
 const {createSocialWeeklyExecutionWorker}=await import('./socialWeeklyExecutionWorker.js');const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js');
 const {createWeeklyExecutionTaskService}=await import('../socialPrograms/executionTasks.js');const executionService=createWeeklyExecutionTaskService(f.store);await executionService.block('t',pkg.programId,pkg.packageId,consumerId,'unrelated_required_input');const stillBlocked=await resumeWeeklyOwnedProductIdentity(f.store,scope,'owner',ports);assert.equal(stillBlocked.status,'blocked');assert.deepEqual(stillBlocked.ownBlockingReasons,['unrelated_required_input']);await executionService.unblock('t',pkg.programId,pkg.packageId,consumerId,'unrelated_required_input');
 const resumed=await resumeWeeklyOwnedProductIdentity(f.store,scope,'owner',ports);assert.equal(resumed.status,'queued');
 const worker=createSocialWeeklyExecutionWorker(f.store,{ownedProductIdentity:ports});const claim=await worker.claimNext({tenantId:'t',workerId:'actual-owned-prerequisite-worker',kinds:['content'],now:new Date()});assert.ok(claim);assert.equal(claim.task.taskId,consumerId);
 const adapted=await createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports}).execute(claim.task);assert.equal(adapted.status,'succeeded',JSON.stringify(adapted));if(adapted.status!=='succeeded')throw Error('real owned prerequisite must succeed');assert.equal(adapted.resultRefs[0]?.type,'starter_social_owned_product_identity_demand');
 const done=await worker.complete(claim,adapted.resultRefs);assert.equal(done.status,'succeeded');assert.ok(done.schedule.actualFinishedAt);assert.equal(done.resultRefs[0]?.type,'starter_social_owned_product_identity_demand');assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 const {validateWeeklyExecutionResults}=await import('./socialWeeklyResultValidation.js');const consumerTask=consumerRow.payload as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask;const manifest=(row.brief as Record<string,unknown>)._weeklyOwnedProductIdentityDemand as import('../../shared/contracts/weeklyOwnedProductIdentity.js').FrozenWeeklyOwnedProductIdentityDemand;const ownedRef={type:'starter_social_owned_product_identity_demand',id:scope.contentTaskId,version:manifest.version};
 await assert.rejects(validateWeeklyExecutionResults(f.store,{...consumerTask,accountId:'foreign'},[ownedRef]),{code:'weekly_owned_product_identity_consumer_invalid'});
 const status=run.status;for(const invalid of ['cancelled','failed','dead_letter']){run.status=invalid;await assert.rejects(validateWeeklyExecutionResults(f.store,consumerTask,[ownedRef]),{code:'weekly_owned_product_identity_original_run_invalid'});await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_run_invalid'});}run.status=status;const tenant=run.tenant_id;run.tenant_id='foreign';await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_run_invalid'});run.tenant_id=tenant;
 const recordedVersion=row.version;row.version=String(Number(recordedVersion)+1);await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_plan_missing'});row.version=recordedVersion;
 const boundSource=f.tables.starter_social_task_sources!.find(source=>source.task_id===scope.contentTaskId&&source.source_ref===sourceRef);assert.ok(boundSource);const sourceVersion=boundSource.source_version;boundSource.source_version='changed-original-material-version';await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_plan_missing'});boundSource.source_version=sourceVersion;

});

test('new real factory keeps preparation before script and preserves post-storyboard material consumer without fabricated predecessor success',async t=>{
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');const {assessWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const {materializeWeeklyExecutionTasks,planWeeklyExecutionTasks}=await import('../socialPrograms/executionTasks.js');
 const {repository,f,pkg,created}=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true});
 // Discard only this isolated fixture's demonstration execution row. The
 // canonical content/source records remain unchanged; no production proof or
 // predecessor is manufactured to make the real graph executable.
 for(const row of [...(f.tables.social_weekly_execution_tasks??[])])await f.store.delete('social_weekly_execution_tasks',row.id);
 // This earlier production-source fixture intentionally lacks the full week
 // summary. Preserve a visible unresolved readiness blocker for graph-only
 // assessment; this is not a fabricated business approval.
 pkg.planningBlockers=['fixture_weekly_business_readiness_unverified'];
 pkg.executionGraphVersion=2;
 const storedPackage=f.tables.social_weekly_operating_packages.find(row=>row.package_id===pkg.packageId&&row.version===pkg.version);assert.ok(storedPackage);storedPackage.payload=structuredClone(pkg);
 const tasks=await materializeWeeklyExecutionTasks(f.store,'t',pkg),planned=planWeeklyExecutionTasks('t',pkg,pkg.createdAt);assert.deepEqual(tasks.map(task=>task.taskId).sort(),planned.map(task=>task.taskId).sort());
 const material=tasks.find(task=>task.schedule.stepKind==='material_readiness'&&task.publicationTaskId===pkg.socialContentPackage.publicationTasks[0]?.publicationTaskId);assert.ok(material);
 const storyboard=tasks.find(task=>task.schedule.stepKind==='storyboard'&&task.publicationTaskId===material.publicationTaskId),assets=tasks.find(task=>task.schedule.stepKind==='asset_generation'&&task.publicationTaskId===material.publicationTaskId);assert.ok(storyboard);assert.ok(assets);assert.ok(material.dependsOnTaskIds.includes(storyboard.taskId));assert.deepEqual(assets.dependsOnTaskIds,[material.taskId]);assert.notEqual(storyboard.status,'succeeded');assert.notEqual(material.status,'succeeded');
 const preparation=tasks.find(task=>task.schedule.stepKind==='material_preparation'&&task.publicationTaskId===material.publicationTaskId),script=tasks.find(task=>task.schedule.stepKind==='script'&&task.publicationTaskId===material.publicationTaskId);assert.ok(preparation);assert.ok(script);assert.deepEqual(script.dependsOnTaskIds,[preparation.taskId]);assert.ok(!preparation.dependsOnTaskIds.includes(storyboard.taskId));
 const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js');
 const result=await createSocialWeeklyProductionAdapter(f.store,{repository}).execute(preparation);assert.equal(result.status,'blocked');if(result.status==='blocked')assert.equal(result.code,'weekly_owned_product_identity_verification_required');
 const scope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:material.publicationTaskId!,contentTaskId:String(created.task_id)};const actual=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(actual.consumerTaskId,material.taskId);assert.equal(actual.status,'blocked');assert.ok(actual.requirements.length);
 const {createWeeklyExecutionTaskService}=await import('../socialPrograms/executionTasks.js');const executions=createWeeklyExecutionTaskService(f.store);await executions.block('t',pkg.programId,pkg.packageId,preparation.taskId,'weekly_owned_product_identity_verification_required');
 const {recheckWeeklyMaterialPreparation}=await import('./weeklyMaterialPreparationRecovery.js');const recoveryScope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,taskId:preparation.taskId,actorUserId:'owner'};await assert.rejects(recheckWeeklyMaterialPreparation(f.store,recoveryScope,{repository}));
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {bindWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(i=>actual.requirements[0]?.imageIds.includes(i.id));assert.ok(image);assert.ok(image.url);const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));const recordId='material0000002',sha=String(image.contentSha256),sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};let physical=bytes;
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?raw:null,materialBytes:{fetch:async()=>new Response(physical,{headers:{'content-type':'image/png','content-length':String(physical.length)}})}};
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'真实产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const service=createWeeklyMaterialRequestService(f.store,materialPorts),requirement=actual.requirements[0];assert.ok(requirement);assert.equal(actual.requirements.length,1);
 const request=await service.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-09T08:00:00+08:00',verificationDueAt:'2026-10-09T09:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:material.taskId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 await service.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});await service.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:material.taskId,accepted:true,factCheck:'实物产品身份一致',rightsCheck:'企业授权此商业用途',visualCheck:'实物包装符合目标镜头要求'}]});
 await bindWeeklyOwnedProductIdentity(f.store,scope,{actorUserId:'owner',expectedTaskVersion:actual.contentTaskVersion,expectedRequirementHash:actual.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]},ports);
 const adapter=createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports});const prepared=await adapter.execute(preparation);assert.equal(prepared.status,'succeeded');if(prepared.status!=='succeeded')return;assert.equal(prepared.resultRefs[0]?.type,'starter_social_material_preparation');
 const {validateWeeklyExecutionResults}=await import('./socialWeeklyResultValidation.js');await validateWeeklyExecutionResults(f.store,preparation,prepared.resultRefs,new Date(),{ownedProductIdentity:ports});
 const recovered=await recheckWeeklyMaterialPreparation(f.store,recoveryScope,ports);assert.ok(!recovered.ownBlockingReasons.includes('weekly_owned_product_identity_verification_required'));assert.notEqual(recovered.status,'succeeded');assert.ok(recovered.inheritedBlockingTaskIds.length>0);assert.ok(recovered.dependsOnTaskIds.length);
 await assert.rejects(recheckWeeklyMaterialPreparation(f.store,{...recoveryScope,actorUserId:'foreign'},ports));
 physical=Buffer.from('changed bytes');await assert.rejects(validateWeeklyExecutionResults(f.store,preparation,prepared.resultRefs,new Date(),{ownedProductIdentity:ports}));physical=bytes;
 // These are actual factory consumers. The adapter has only read the preparation
 // evidence; it has not forged the unmet business/script/storyboard predecessors.
 assert.notEqual(material.status,'succeeded');assert.notEqual(script.status,'succeeded');assert.ok(!created.run_id);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
});
