import type {Record_} from '../storage/datastore.js';
import {socialAccessToken,youtubeCredentials} from '../lib/accountCredentials.js';
import type {MetricValues} from '../socialMetrics/aggregation.js';
export interface MetricPublication {publicationTaskId:string;accountId:string;platform:string;contentId:string;platformPostId:string;productionResultId:string;receiptRef:string;attemptRef:{type:string;id:string;version:number};packageId:string;}
export interface MetricProviderSample {platformPostId:string;nativeAccountId:string;raw:Record<string,unknown>;metrics:MetricValues;presence:Record<string,boolean>;}
const object=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const numeric=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>=0?v:typeof v==='string'&&/^\d+(\.\d+)?$/.test(v)&&Number.isFinite(Number(v))?Number(v):null;
/** Missing, null and unsupported provider fields stay absent; only observed zero becomes zero. */
export function observedMetricValues(raw:Record<string,unknown>,fields:Record<string,string>) {const metrics:MetricValues={},presence:Record<string,boolean>={};for(const[key,providerKey]of Object.entries(fields)){presence[key]=Object.prototype.hasOwnProperty.call(raw,providerKey)&&numeric(raw[providerKey])!==null;if(presence[key])metrics[key as keyof MetricValues]=numeric(raw[providerKey])!;}return{metrics,presence};}
async function json(url:string,init:RequestInit,fetcher:typeof fetch){const response=await fetcher(url,init);if(!response.ok)throw Error(`weekly_metric_provider_http_${response.status}`);if(response.status===204)throw Error('weekly_metric_provider_empty_response');let body:unknown;try{body=await response.json();}catch{throw Error('weekly_metric_provider_invalid_json');}return object(body);}
export async function readOfficialWeeklyPublicationMetrics(input:{publication:MetricPublication;account:Record_;fetch?:typeof fetch;graphVersion?:string}):Promise<MetricProviderSample>{
 const {publication:p,account:a}=input,fetcher=input.fetch??fetch,native=String(p.platform==='youtube'?a.channelId??'':a.providerAccountId??'');if(!native)throw Error('weekly_metric_native_account_missing');let raw:Record<string,unknown>,observed:{metrics:MetricValues;presence:Record<string,boolean>};
 if(p.platform==='youtube'){
 const credentials=youtubeCredentials(a);let token=credentials.accessToken;
 if(!token){const result=await json('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:credentials.clientId,client_secret:credentials.clientSecret,refresh_token:credentials.refreshToken,grant_type:'refresh_token'})},fetcher);if(typeof result.access_token!=='string'||!result.access_token)throw Error('weekly_metric_credentials_unavailable');token=result.access_token;}
 raw=await json(`https://www.googleapis.com/youtube/v3/videos?part=snippet,statistics&id=${encodeURIComponent(p.platformPostId)}`,{headers:{Authorization:`Bearer ${token}`}},fetcher);const items=Array.isArray(raw.items)?raw.items.map(object):[];if(items.length!==1||items[0]!.id!==p.platformPostId||object(items[0]!.snippet).channelId!==native)throw Error('weekly_metric_provider_identity_invalid');observed=observedMetricValues(object(items[0]!.statistics),{views:'viewCount',likes:'likeCount',comments:'commentCount'});
 }else if(p.platform==='tiktok'){
 const token=socialAccessToken(a),headers={Authorization:`Bearer ${token}`};const owner=await json('https://open.tiktokapis.com/v2/user/info/?fields=open_id',{headers},fetcher);if(object(object(owner.data).user).open_id!==native)throw Error('weekly_metric_provider_identity_invalid');const queried=await json('https://open.tiktokapis.com/v2/video/query/?fields=id,view_count,like_count,comment_count,share_count',{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({filters:{video_ids:[p.platformPostId]}})},fetcher);if(object(queried.error).code&&object(queried.error).code!=='ok')throw Error('weekly_metric_provider_query_rejected');raw={owner,queried};const videos=object(queried.data).videos;if(!Array.isArray(videos)||videos.length!==1||object(videos[0]).id!==p.platformPostId)throw Error('weekly_metric_provider_identity_invalid');observed=observedMetricValues(object(videos[0]),{views:'view_count',likes:'like_count',comments:'comment_count',shares:'share_count'});
 }else if(p.platform==='facebook'||p.platform==='instagram'){
 const token=socialAccessToken(a),version=input.graphVersion??process.env.META_GRAPH_VERSION;if(!version||!/^v\d+\.\d+$/.test(version))throw Error('weekly_metric_graph_version_required');const login=p.platform==='instagram'&&a.oauthProvider==='instagram_login';const base=login?'https://graph.instagram.com':'https://graph.facebook.com',headers={Authorization:`Bearer ${token}`};const identity=await json(`${base}/${version}/${encodeURIComponent(p.platformPostId)}?fields=id,${p.platform==='facebook'?'from':'owner'}`,{headers},fetcher);if(identity.id!==p.platformPostId||object(identity[p.platform==='facebook'?'from':'owner']).id!==native)throw Error('weekly_metric_provider_identity_invalid');const metric=p.platform==='facebook'?'post_impressions_unique,post_video_views':'views,reach,likes,comments,shares,saved';const insight=await json(`${base}/${version}/${encodeURIComponent(p.platformPostId)}/insights?metric=${metric}`,{headers},fetcher);raw={identity,insight};const values:Record<string,unknown>={};if(!Array.isArray(insight.data))throw Error('weekly_metric_provider_empty_response');for(const row of insight.data.map(object)){const key=String(row.name??'');if(Object.prototype.hasOwnProperty.call(values,key))throw Error('weekly_metric_provider_duplicate_field');const entries=Array.isArray(row.values)?row.values.map(object):[];if(entries.length>1)throw Error('weekly_metric_provider_ambiguous_period');values[key]=entries[0]?.value??object(row.total_value).value;}
 observed=observedMetricValues(values,{views:p.platform==='facebook'?'post_video_views':'views',reach:p.platform==='facebook'?'post_impressions_unique':'reach',likes:'likes',comments:'comments',shares:'shares',saves:'saved'});
 }else throw Error('weekly_metric_platform_unsupported');
 if(!Object.keys(observed.metrics).length)throw Error('weekly_metric_provider_numeric_presence_missing');return{platformPostId:p.platformPostId,nativeAccountId:native,raw,...observed};
}
