import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import type {Starter198Repository} from '../starter198/repository.js';
import type {WeeklyOwnedProductIdentityPorts} from './weeklyOwnedProductIdentityDemand.js';
import {readWeeklyCreativeRepairExecutionLineage,WEEKLY_CREATIVE_REPAIR_EXECUTION_STEPS} from './weeklyCreativeRepairExecutionGraph.js';
import {resolveWeeklyCreativeRepairAuthority} from './weeklyCreativeRepairAuthority.js';
import {socialJson,socialObject,socialRequestHash,SocialContentWorkflowError} from '../starter198/socialContentValidation.js';
import {readSocialTaskDetail} from '../starter198/socialContentRecords.js';
import {readWeeklyPreSupplyHandoff} from '../starter198/socialWeeklyPreSupplyHandoff.js';
import {readContentExecutionJob} from '../contentExecution/durableQueue.js';
import type {WeeklyExecutionAdapterResult} from './socialWeeklyExecutionAdapter.js';

export const WEEKLY_CREATIVE_REPAIR_STAGE_EVIDENCE='social_weekly_creative_repair_stage_evidence';
const fail=(code:string):never=>{throw new SocialContentWorkflowError(code,409);};
export async function executeWeeklyCreativeRepairStage(input:{store:DataStore;repository:Starter198Repository;task:WeeklyExecutionTask;now:Date;ownedProductIdentity?:Omit<WeeklyOwnedProductIdentityPorts,'repository'>;assertAdmission:()=>Promise<void>}):Promise<WeeklyExecutionAdapterResult>{
 const lineage=readWeeklyCreativeRepairExecutionLineage(input.task);if(!lineage)return fail('weekly_creative_repair_execution_lineage_required');
 const rows=await input.store.list<Record_>('starter_social_content_tasks',{where:{tenant_id:input.task.tenantId,task_id:lineage.childTaskId},perPage:2}),row=rows.items[0];if(rows.totalItems!==1||rows.items.length!==1||!row)return fail('weekly_creative_repair_execution_child_missing');const authority=await resolveWeeklyCreativeRepairAuthority({store:input.store,tenantId:input.task.tenantId,task:row,now:input.now});if(!authority||authority.proof.caseId!==lineage.caseId||authority.proof.caseRequestHash!==lineage.caseRequestHash||authority.configuration.recordHash!==lineage.configurationHash||authority.proof.originalAuthorityHash!==lineage.authorityHash||authority.bindingKey!==lineage.childBindingKey||input.task.subjectId!==lineage.childTaskId||input.task.publicationTaskId!==`creative-repair:${lineage.caseId}`)return fail('weekly_creative_repair_execution_authority_changed');
 const detail=await readSocialTaskDetail({repository:input.repository,tenantId:input.task.tenantId,taskId:lineage.childTaskId});if(!detail?.runId)return fail('weekly_creative_repair_execution_run_missing');
 const step=input.task.schedule.stepKind;if(!WEEKLY_CREATIVE_REPAIR_EXECUTION_STEPS.includes(step as any))return fail('weekly_creative_repair_execution_step_invalid');let observationHash:string;
 if(step==='material_preparation'||step==='material_readiness'){if(!input.ownedProductIdentity)return fail('weekly_owned_product_identity_verification_required');const {assessWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');const assessment=await assessWeeklyOwnedProductIdentity(input.store,{tenantId:input.task.tenantId,programId:input.task.programId,packageId:input.task.packageId,packageVersion:input.task.packageVersion,publicationTaskId:lineage.originalPublicationTaskId,contentTaskId:lineage.childTaskId},{...input.ownedProductIdentity,repository:input.repository});if(assessment.status!=='ready'||!assessment.materials.length)return fail(assessment.gaps[0]??'weekly_owned_product_identity_verification_required');observationHash=socialRequestHash({requirementHash:assessment.requirementHash,materials:assessment.materials});}
 else if(step==='script'){const baseline=socialObject(socialJson(row.script_baseline));if(!baseline)return fail('weekly_creative_repair_script_missing');observationHash=socialRequestHash(baseline);}
 else if(step==='storyboard'){const handoff=await readWeeklyPreSupplyHandoff(input.repository,input.task.tenantId,lineage.childTaskId);if(!handoff)return fail('weekly_creative_repair_storyboard_missing');observationHash=handoff.recordHash;}
 else {const job=await readContentExecutionJob(input.store,input.task.tenantId,lineage.childTaskId,detail.runId);if(!job)return fail('weekly_creative_repair_execution_job_missing');if(job.status==='paused'&&job.retryClass==='weekly_production_waiting_asset_claim'){const {resumeWeeklyProductionAssetStage}=await import('../starter198/socialWeeklyProductionStageResume.js');await resumeWeeklyProductionAssetStage({repository:input.repository,assetTask:input.task,contentTaskId:lineage.childTaskId,now:input.now,assertAdmission:input.assertAdmission,validationPorts:{ownedProductIdentity:input.ownedProductIdentity?{...input.ownedProductIdentity,repository:input.repository}:undefined}});return{status:'pending',code:'weekly_creative_repair_asset_execution_pending',message:'创意返工资产任务已恢复原生产作业。',retryDelayMs:1000};}if(job.status!=='succeeded')return{status:'pending',code:'weekly_creative_repair_asset_execution_pending',message:'创意返工资产仍在真实生产。',retryDelayMs:1000};const artifacts=await input.store.list<Record_>('starter_social_content_artifacts',{where:{tenant_id:input.task.tenantId,task_id:lineage.childTaskId},perPage:100});if(!artifacts.items.length)return fail('weekly_creative_repair_artifact_missing');observationHash=socialRequestHash(artifacts.items.map(item=>[item.artifact_id,item.content_hash,item.version]));}
 const previous=input.task.dependsOnTaskIds[0]??null,previousRow=previous?await input.store.list<Record_>('social_weekly_creative_repair_stage_evidence',{where:{tenant_id:input.task.tenantId,task_id:previous},perPage:2}):null;if(previous&&(previousRow?.totalItems!==1||previousRow.items.length!==1))return fail('weekly_creative_repair_execution_predecessor_missing');const body={schemaVersion:'weekly-creative-repair-stage-evidence.v1',tenantId:input.task.tenantId,caseId:lineage.caseId,taskId:input.task.taskId,step,lineageHash:lineage.recordHash,previousEvidenceHash:previousRow?.items[0]?.content_hash??null,observationHash,createdAt:input.now.toISOString()},evidence={...body,recordHash:socialRequestHash(body)};await input.assertAdmission();const existing=await input.store.list<Record_>(WEEKLY_CREATIVE_REPAIR_STAGE_EVIDENCE,{where:{tenant_id:input.task.tenantId,task_id:input.task.taskId},perPage:2});if(existing.items.length){if(existing.totalItems!==1||existing.items[0]!.content_hash!==evidence.recordHash)return fail('weekly_creative_repair_execution_evidence_changed');}else if(!await input.store.create(WEEKLY_CREATIVE_REPAIR_STAGE_EVIDENCE,{id:input.task.taskId,tenant_id:input.task.tenantId,task_id:input.task.taskId,case_id:lineage.caseId,step,content_hash:evidence.recordHash,payload:evidence}))return fail('weekly_creative_repair_execution_evidence_save_failed');return{status:'succeeded',resultRefs:[{type:'weekly_creative_repair_stage_evidence',id:input.task.taskId,version:1}]};
}

export async function validateWeeklyCreativeRepairStageEvidence(store:DataStore,task:WeeklyExecutionTask,refs:VersionedSocialRef[]){const lineage=readWeeklyCreativeRepairExecutionLineage(task);if(!lineage||refs.length!==1||refs[0]?.type!=='weekly_creative_repair_stage_evidence'||refs[0].id!==task.taskId||refs[0].version!==1)return fail('weekly_creative_repair_execution_evidence_invalid');const rows=await store.list<Record_>(WEEKLY_CREATIVE_REPAIR_STAGE_EVIDENCE,{where:{tenant_id:task.tenantId,task_id:task.taskId},perPage:2}),row=rows.items[0],payload=socialObject(socialJson(row?.payload));const recordHash=payload?.recordHash,{recordHash:_recordHash,...body}=payload??{};if(rows.totalItems!==1||rows.items.length!==1||!row||!payload||recordHash!==socialRequestHash(body)||row.content_hash!==recordHash||payload.lineageHash!==lineage.recordHash||payload.step!==task.schedule.stepKind)return fail('weekly_creative_repair_execution_evidence_invalid');}
