import test from 'node:test';
import assert from 'node:assert/strict';

test('actual owned product route exposes exact prerequisite before original scheduler can create a run',async t=>{
 const keys=['SEEDANCE_VIDEO_ENABLED','SEEDANCE_API_KEY','SEEDREAM_API_KEY'] as const;const old=Object.fromEntries(keys.map(key=>[key,process.env[key]]));t.after(()=>{for(const key of keys){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});process.env.SEEDANCE_VIDEO_ENABLED='true';process.env.SEEDANCE_API_KEY='controlled-no-real-provider';process.env.SEEDREAM_API_KEY='controlled-no-real-provider';
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');const {assessWeeklyOwnedProductIdentity,bindWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const {repository,f,pkg,task,created,actual}=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true});
 const scope={tenantId:task.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:task.publicationTaskId!,contentTaskId:String(created.task_id)};
 const result=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});
 assert.equal(result.required,true);assert.equal(result.status,'blocked');assert.deepEqual(result.gaps,['weekly_owned_product_identity_verification_required']);
 assert.ok(result.consumerTaskId);assert.ok(result.requirements.length);for(const requirement of result.requirements){assert.ok(requirement.sceneIds.length);assert.ok(requirement.productRef);assert.ok(requirement.imageHashes.every(hash=>/^[a-f0-9]{64}$/.test(hash)));}
 assert.equal(actual.lastError?.code,'weekly_owned_product_identity_verification_required');assert.ok(!created.run_id);assert.equal(f.tables.workflow_runs?.filter(row=>(row.starter_context as Record<string,unknown>|undefined)?.socialTaskId===scope.contentTaskId).length??0,0);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,{...scope,tenantId:'foreign'},{repository}),{code:'weekly_owned_product_identity_scope_invalid'});
 const row=f.tables.starter_social_content_tasks!.find(row=>row.task_id===scope.contentTaskId);assert.ok(row);const original=row.brief;row.brief={...(original as object),_weeklyOwnedProductIdentityDemand:{schemaVersion:'weekly-owned-product-identity.v1',...scope,version:Number(row.version),consumerTaskId:result.consumerTaskId,requirementHash:result.requirementHash,requirements:result.requirements,bindings:[],boundBy:'owner',boundAt:new Date().toISOString(),recordHash:'0'.repeat(64)}};
 const forged=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(forged.status,'blocked');assert.deepEqual(forged.gaps,['weekly_owned_product_identity_binding_changed']);row.brief=original;
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(item=>result.requirements[0]?.imageIds.includes(item.id));assert.ok(image);assert.ok(typeof image.url==='string');const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));
 const recordId='material0000001',sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`,sha=String(image.contentSha256);let currentBytes=bytes;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?structuredClone(raw):null,materialBytes:{fetch:async()=>new Response(currentBytes,{headers:{'content-type':'image/png','content-length':String(currentBytes.length)}})}};
 const service=createWeeklyMaterialRequestService(f.store,materialPorts),consumerId=result.consumerTaskId;assert.ok(consumerId);const requirement=result.requirements[0];assert.ok(requirement);assert.equal(result.requirements.length,1);
 const consumerRow=f.tables.social_weekly_execution_tasks!.find(row=>row.task_id===consumerId);assert.ok(consumerRow);(consumerRow.payload as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask).scope='content';
 const request=await service.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-09T08:00:00+08:00',verificationDueAt:'2026-10-09T09:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:consumerId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'实际核验产品',type:'image' as const}),list:async()=>({items:[],total:0,page:1,perPage:20})}};
 const bindingInput={actorUserId:'owner',expectedTaskVersion:result.contentTaskVersion,expectedRequirementHash:result.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]};
 await bindWeeklyOwnedProductIdentity(f.store,scope,bindingInput,ports);assert.equal((await assessWeeklyOwnedProductIdentity(f.store,scope,ports)).status,'blocked');
 await service.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});
 await service.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:consumerId,accepted:true,factCheck:'指定产品外观对应真实企业产品',rightsCheck:'指定企业拥有素材并授权目标账号商业使用',visualCheck:'身份包装与该组镜头要求一致'}]});
 const beforeAttach=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.deepEqual(beforeAttach.gaps,['weekly_owned_product_identity_source_not_bound']);assert.equal(beforeAttach.materials[0]?.sourceBound,false);
 await bindWeeklyOwnedProductIdentity(f.store,scope,{...bindingInput,expectedTaskVersion:beforeAttach.contentTaskVersion},ports);const ready=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.equal(ready.status,'ready');assert.equal(ready.materials[0]?.sourceBound,true);
 currentBytes=Buffer.from('changed actual physical bytes');await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports));assert.ok(!row.run_id);assert.equal(f.tables.content_execution_jobs?.length??0,0);
});
