import {assertWeeklyProductionCoverage} from './weeklyProductionCoverageAdmission.js';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,VersionedSocialRef,WeeklyOperatingPackage} from '../../shared/contracts/socialProgram.js';
import type {WeeklyOwnedProductIdentityPorts} from './weeklyOwnedProductIdentityDemand.js';
import {assessWeeklyOwnedProductIdentity} from './weeklyOwnedProductIdentityDemand.js';
import {createStarter198Repository} from '../starter198/repository.js';
import {socialObject,socialJson,socialRequestHash,SocialContentWorkflowError} from '../starter198/socialContentValidation.js';
import {readVerifiedNoSharedMaterialDemand} from './socialWeeklyOriginalRunMaterialDemand.js';
import {createWeeklyRequiredMaterialAdmission} from '../socialPrograms/weeklyRequiredMaterialAdmission.js';
import {checkWeeklyHumanRequirementBindings,checkWeeklyMaterialClassification} from './socialWeeklyMaterialClassificationAdmission.js';
import {createWeeklyPlanningAuthority} from '../socialPrograms/planningAuthority.js';
import {socialContentSourceOptions} from '../starter198/socialContentSourceOptions.js';
import {getOwnedCloudMaterialRecord} from '../lib/cloudMaterials.js';
function fail(code:string):never {throw new SocialContentWorkflowError(code,409);}
/** Preparation and post-storyboard readiness consume the same actual review consumer;
 * no prerequisite task is completed and no production operation is performed here. */
export async function validateWeeklyMaterialPreparationEvidence(store:DataStore,task:WeeklyExecutionTask,ref:VersionedSocialRef,ports?:WeeklyOwnedProductIdentityPorts):Promise<void>{
 const repository=ports?.repository??createStarter198Repository(store);if(repository.dataStore!==store)fail('weekly_material_repository_authority_invalid');
 async function one(collection:string,where:Record<string,string|number>){const r=await store.list<Record_>(collection,{where,perPage:2});if(r.totalItems!==1||r.items.length!==1||Object.entries(where).some(([k,v])=>r.items[0]![k]!==v))fail('weekly_material_preparation_scope_invalid');return r.items[0]!;}
 if(ref.type!=='starter_social_material_preparation'||task.workflowKind!=='content'||task.schedule.stepKind!=='material_preparation'||!task.publicationTaskId)fail('weekly_material_preparation_scope_invalid');
 const taskRow=await one('social_weekly_execution_tasks',{tenant_id:task.tenantId,task_id:task.taskId});const actual=socialObject(socialJson(taskRow.payload));
 if(taskRow.program_id!==task.programId||taskRow.package_id!==task.packageId||taskRow.package_version!==task.packageVersion||!actual||actual.taskId!==task.taskId||actual.tenantId!==task.tenantId||actual.workflowKind!=='content'||actual.programId!==task.programId||actual.packageId!==task.packageId||actual.packageVersion!==task.packageVersion||actual.publicationTaskId!==task.publicationTaskId||actual.accountId!==task.accountId||socialRequestHash(actual.inputSnapshot)!==socialRequestHash(task.inputSnapshot)||socialRequestHash(actual.upstreamVersionRefs)!==socialRequestHash(task.upstreamVersionRefs)||socialObject(actual.schedule)?.stepKind!=='material_preparation')fail('weekly_material_preparation_scope_invalid');
 const pkgRow=await one('social_weekly_operating_packages',{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,version:task.packageVersion});const parsed=socialObject(socialJson(pkgRow.payload));if(!parsed||!socialObject(parsed.socialContentPackage)||!Array.isArray(socialObject(parsed.socialContentPackage)?.publicationTasks)||(socialObject(parsed.socialContentPackage)!.publicationTasks as unknown[]).some(p=>!socialObject(p)||typeof socialObject(p)?.publicationTaskId!=='string'||typeof socialObject(p)?.accountId!=='string'))fail('weekly_material_preparation_scope_invalid');const pkg=parsed as unknown as WeeklyOperatingPackage;
 const publications=pkg.socialContentPackage.publicationTasks.filter(p=>p.publicationTaskId===task.publicationTaskId&&p.accountId===task.accountId);if(pkg.programId!==task.programId||pkg.packageId!==task.packageId||pkg.version!==task.packageVersion||pkg.executionGraphVersion!==2||publications.length!==1||!['draft','active'].includes(pkg.status))fail('weekly_material_preparation_scope_invalid');const publication=publications[0]!;
 const row=await one('starter_social_content_tasks',{tenant_id:task.tenantId,task_id:ref.id});if(row.create_idempotency_key!==`weekly-production:${task.packageId}:${task.packageVersion}:${task.publicationTaskId}`||Number(row.version)!==ref.version||['cancelled','paused','attention'].includes(String(row.status)))fail('weekly_material_preparation_content_changed');
 const planning=await createWeeklyPlanningAuthority(store).get(task.tenantId,task.programId,task.packageId,task.packageVersion);assertWeeklyProductionCoverage(pkg,planning,task.publicationTaskId);const item=planning?.dispatch?.scheduleItems.find(i=>i.publicationTaskId===task.publicationTaskId);if(!item)fail('weekly_material_preparation_planning_missing');
 const classification=await checkWeeklyMaterialClassification({store,tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,item,analysis:planning.directorAnalyses.find(a=>a.analysisId===item.directorAnalysisRef?.id)});if(!classification.ready)fail(classification.code);
 const owned=await assessWeeklyOwnedProductIdentity(store,{tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,publicationTaskId:task.publicationTaskId,contentTaskId:ref.id},{...ports,repository});
 if(owned.required){if(owned.status!=='ready'||!owned.materials.every(m=>m.sourceBound))fail(owned.gaps[0]??'weekly_owned_product_identity_verification_required');}
 if(publication.materialRequirement){
  const consumers=await store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion},perPage:500});if(consumers.totalItems!==consumers.items.length)fail('weekly_material_consumer_lookup_incomplete');
  const candidates=consumers.items.filter(r=>{const p=socialObject(socialJson(r.payload));return p?.publicationTaskId===task.publicationTaskId&&socialObject(p.schedule)?.stepKind==='material_readiness';});if(candidates.length!==1)fail('weekly_material_consumer_required');const consumer=candidates[0]!,payload=socialObject(socialJson(consumer.payload));if(consumer.program_id!==task.programId||consumer.package_id!==task.packageId||consumer.package_version!==task.packageVersion||!payload||payload.taskId!==consumer.task_id||payload.tenantId!==task.tenantId||payload.programId!==task.programId||payload.packageId!==task.packageId||payload.packageVersion!==task.packageVersion||payload.accountId!==task.accountId||['cancelled','dead_letter'].includes(String(payload.status)))fail('weekly_material_consumer_identity_invalid');
  const mapping=await checkWeeklyHumanRequirementBindings({store,tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,consumerTaskId:String(consumer.task_id),publication,contract:classification.contract});if(mapping)fail(mapping);
  const admission=await createWeeklyRequiredMaterialAdmission(store,ports?.materialPorts)({tenantId:task.tenantId,programId:task.programId,consumerTaskId:String(consumer.task_id),requirement:publication.materialRequirement});if(admission.status!=='ready'||!admission.materials.length)fail('weekly_required_materials_missing');
  const sources=await repository.list('starter_social_task_sources',task.tenantId,{where:{task_id:ref.id},perPage:500});if(sources.totalItems!==sources.items.length)fail('weekly_material_source_lookup_incomplete');
  for(const material of admission.materials){const sourceRef=`socialmaterial:${Buffer.from(`pb-${material.recordId}`).toString('base64url')}`;const option=await (ports?.sourceOptions??socialContentSourceOptions).resolve({tenantId:task.tenantId,kind:'material',sourceRef});const raw=await (ports?.getMaterial??getOwnedCloudMaterialRecord)(material.recordId,task.tenantId);const bound=sources.items.filter(s=>s.kind==='material'&&s.source_ref===sourceRef&&s.status==='active');if(!option||option.kind!=='material'||option.sourceRef!==sourceRef||!option.sourceVersion||!raw||raw.id!==material.recordId||String(raw.tenantId??raw.tenant_id)!==task.tenantId||String(raw.scope??'own')==='shared'||raw.sha256!==material.sha256||bound.length!==1||bound[0]!.source_version!==option.sourceVersion)fail('weekly_material_source_revision_invalid');}
 }else if(!owned.required){if(classification.contract.items.some(i=>i.classification!=='generatable_non_evidentiary'))fail('weekly_required_material_contract_missing');const demand=await readVerifiedNoSharedMaterialDemand(store,row,{tenantId:task.tenantId,taskId:ref.id,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,publicationTaskId:task.publicationTaskId,accountId:task.accountId!,factRefs:publication.factRefs},{repository});if(!demand)fail('weekly_material_contract_required');}
}
