import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import {socialRequestHash,socialJson,socialObject} from '../starter198/socialContentValidation.js';
import {publicationInstant} from '../socialPrograms/publicationDeadlines.js';
import {SOCIAL_METRIC_KEYS} from '../socialMetrics/aggregation.js';
import {readStarterPublicationEvidenceSnapshot} from '../publishing/starterPublicationPackage.js';
import {SocialProgramError} from '../socialPrograms/service.js';
const fail=(code:string):never=>{throw new SocialProgramError(code,409,'本周发布身份或真实指标证据读取不完整，未核销回流任务。');};
async function all(store:DataStore,collection:string,where:Record<string,string>){const rows:Record_[]=[],ids=new Set<string>();let count:number|null=null;for(let page=1;page<=10000;page++){const result=await store.list<Record_>(collection,{where,sort:'id',page,perPage:100});if(!Number.isSafeInteger(result.totalItems)||result.totalItems<0||(count!==null&&count!==result.totalItems))return fail('weekly_metrics_scan_changed');count=result.totalItems;for(const row of result.items){if(!row.id||ids.has(row.id)||Object.entries(where).some(([key,value])=>row[key]!==value))return fail('weekly_metrics_scan_identity');ids.add(row.id);rows.push(row);}if(rows.length===count)return rows;if(!result.items.length||rows.length>count)return fail('weekly_metrics_scan_incomplete');}return fail('weekly_metrics_scan_limit');}
export interface WeeklyPublicationProof {publicationTaskId:string;accountId:string;platform:string;contentId:string;platformPostId:string;productionResultId:string;providerReceiptId:string;receiptRef:string;attemptRef:VersionedSocialRef;packageId:string;}
export interface WeeklyPublicationMetricRead {publications:WeeklyPublicationProof[];publicationEvidenceIncomplete:boolean;sources:Record_[];missingPublicationIds:string[];receiptRefs:string[];publicationMetricIds:Record<string,string[]>;}
/** Read-only current-week publication attribution; historical account comparisons remain outside this completion proof. */
export async function readWeeklyPublicationMetricEvidence(store:DataStore,task:WeeklyExecutionTask,pkg:WeeklyOperatingPackage,now=new Date(),options:{durableOnly?:boolean}={}):Promise<WeeklyPublicationMetricRead>{
 if(task.workflowKind!=='engagement'||task.schedule.stepKind!=='performance_monitoring'||!task.accountId||pkg.packageId!==task.packageId||pkg.version!==task.packageVersion||pkg.programId!==task.programId)return fail('weekly_metrics_task_scope_invalid');
 const starts=publicationInstant(`${pkg.weekStart}T00:00:00Z`),ends=publicationInstant(`${pkg.weekEnd}T23:59:59.999Z`);if(starts===null||ends===null)return fail('weekly_metrics_window_invalid');
 const pubs=pkg.socialContentPackage.publicationTasks.filter(pub=>pub.accountId===task.accountId&&pub.status!=='cancelled');if(!pubs.length)return fail('weekly_metrics_publications_missing');
 const [metrics,assignments,attempts,packages]=await Promise.all([all(store,'social_metric_snapshots',{tenant_id:task.tenantId,account_id:task.accountId}),all(store,'social_publication_assignments',{tenant_id:task.tenantId,account_id:task.accountId}),all(store,'social_publication_attempts',{tenant_id:task.tenantId}),all(store,'starter_publication_packages',{tenant_id:task.tenantId})]);
 let publicationEvidenceIncomplete=false;const publications:WeeklyPublicationProof[]=[];
 const refs=new Set<string>(),matched=new Map<string,Map<string,number>>();
 for(const pub of pubs){const contentIds=new Map<string,number>();matched.set(pub.publicationTaskId,contentIds);
  for(const assignment of assignments.filter(row=>row.operating_package_id===pkg.packageId&&row.operating_package_version===pkg.version&&row.publication_task_id===pub.publicationTaskId&&row.account_id===pub.accountId&&row.platform===pub.platform)){
   for(const attempt of attempts.filter(row=>row.assignment_id===assignment.assignment_id&&row.package_id===assignment.package_id&&row.status==='published')){const resolved=publicationInstant(String(attempt.resolved_at??''));if(resolved===null||resolved<starts||resolved>ends||resolved>now.getTime())continue;
    const attemptRef={type:'weekly_publication_attempt',id:String(attempt.attempt_id),version:1};const {validateWeeklyExecutionResults}=await import('./socialWeeklyResultValidation.js');try{await validateWeeklyExecutionResults(store,{...task,inputSnapshot:{...task.inputSnapshot,publicationTask:pub,...(pub.inventoryReuseRef?{inventoryReuseRef:pub.inventoryReuseRef}:{})},workflowKind:'publishing',publicationTaskId:pub.publicationTaskId,accountId:pub.accountId,schedule:{...task.schedule,stepKind:'publishing'}},[attemptRef],now);}catch{publicationEvidenceIncomplete=true;continue;}
    const assigned=socialObject(socialJson(assignment.payload));if(!assigned||assigned.tenantId!==task.tenantId||assigned.accountId!==pub.accountId||assigned.platform!==pub.platform||assigned.publicationTaskId!==pub.publicationTaskId||assigned.packageId!==assignment.package_id||assigned.assignmentId!==assignment.assignment_id||assigned.assignmentHash!==assignment.assignment_hash)continue;
    const record=packages.find(row=>row.package_id===assignment.package_id);if(!record)continue;const {readStarterPublicationPackage}=await import('../publishing/starterPublicationPackage.js');const manifest=await readStarterPublicationPackage(task.tenantId,String(record.package_id),store);if(!manifest||manifest.platform!==pub.platform||manifest.operatingLineage?.assignmentId!==assignment.assignment_id||manifest.operatingLineage?.assignmentHash!==assignment.assignment_hash||manifest.operatingLineage?.productionResultRef.id!==assignment.production_result_id||manifest.operatingLineage?.operatingPackageRef.id!==pkg.packageId||manifest.operatingLineage?.operatingPackageRef.version!==pkg.version||manifest.operatingLineage?.weeklyPublicationTaskRef.id!==pub.publicationTaskId)continue;contentIds.set(manifest.contentId,resolved);contentIds.set(String(attempt.platform_post_id),resolved);refs.add(String(attempt.provider_receipt_id));publications.push({publicationTaskId:pub.publicationTaskId,accountId:pub.accountId,platform:pub.platform,contentId:manifest.contentId,platformPostId:String(attempt.platform_post_id),productionResultId:String(assignment.production_result_id),providerReceiptId:String(attempt.provider_receipt_id),receiptRef:socialRequestHash({schemaVersion:'weekly-durable-publication-receipt.v1',tenantId:task.tenantId,assignmentId:assignment.assignment_id,assignmentHash:assignment.assignment_hash,attemptId:attempt.attempt_id,provider:attempt.provider,providerReceiptId:attempt.provider_receipt_id,platformPostId:attempt.platform_post_id,resolvedAt:attempt.resolved_at,productionResultId:assignment.production_result_id,manifestHash:socialRequestHash(manifest)}),attemptRef,packageId:String(assignment.package_id)});
   }
  }
  if(!options.durableOnly)for(const record of packages){const manifest=socialObject(socialJson(record.manifest)),lineage=socialObject(manifest?.operatingLineage),scope=socialObject(lineage?.operatingPackageRef),pubRef=socialObject(lineage?.weeklyPublicationTaskRef);if(scope?.id!==pkg.packageId||scope.version!==pkg.version||pubRef?.id!==pub.publicationTaskId||!assignments.some(assignment=>assignment.assignment_id===lineage?.assignmentId&&assignment.package_id===record.package_id&&assignment.account_id===pub.accountId&&assignment.platform===pub.platform&&assignment.operating_package_id===pkg.packageId&&assignment.operating_package_version===pkg.version&&assignment.publication_task_id===pub.publicationTaskId)||record.status!=='published')continue;let evidence;try{evidence=await readStarterPublicationEvidenceSnapshot(task.tenantId,String(record.package_id),store);}catch{return fail('weekly_metrics_publication_receipt_invalid');}if(!evidence||evidence.package.platform!==pub.platform||evidence.evidence?.verificationStatus!=='verified')continue;const verified=evidence.evidence;const submitted=publicationInstant(verified.submittedAt),checked=publicationInstant(verified.verifiedAt);if(submitted===null||checked===null||submitted<starts||submitted>ends||checked>now.getTime())continue;contentIds.set(evidence.package.contentId,submitted);if(verified.platformPostId)contentIds.set(verified.platformPostId,submitted);refs.add(verified.verificationReceiptHash);}
 }
 const sources:Record_[]=[],missingPublicationIds:string[]=[],publicationMetricIds:Record<string,string[]>={};
 for(const pub of pubs){const contentIds=matched.get(pub.publicationTaskId)!;const current=metrics.filter(row=>{const captured=publicationInstant(String(row.captured_at??'')),values=socialObject(socialJson(row.metrics));return row.tenant_id===task.tenantId&&row.account_id===pub.accountId&&row.platform===pub.platform&&contentIds.has(String(row.content_id??''))&&captured!==null&&captured>=starts&&captured>=contentIds.get(String(row.content_id??''))!&&captured<=ends&&captured<=now.getTime()&&!row.mock&&!row.simulated&&!/mock|simulat/i.test(String(row.source??''))&&values&&SOCIAL_METRIC_KEYS.some(key=>typeof values[key]==='number'&&Number.isFinite(values[key])&&Number(values[key])>=0)&&Object.values(values).every(value=>value===null||value===undefined||(typeof value==='number'&&Number.isFinite(value)&&value>=0));});if(!current.length)missingPublicationIds.push(pub.publicationTaskId);publicationMetricIds[pub.publicationTaskId]=current.map(row=>row.id);sources.push(...current);}
 return {publications,publicationEvidenceIncomplete,sources:[...new Map(sources.map(row=>[row.id,row])).values()],missingPublicationIds,receiptRefs:[...refs],publicationMetricIds};
}
export async function validateWeeklyPublicationMetricRefs(store:DataStore,task:WeeklyExecutionTask,refs:VersionedSocialRef[],now=new Date()):Promise<void>{const rows=await store.list<Record_>('social_weekly_operating_packages',{where:{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,version:task.packageVersion},perPage:2});if(rows.totalItems!==1||rows.items.length!==1)return fail('weekly_metrics_package_missing');const pkg=socialObject(socialJson(rows.items[0]!.payload)) as unknown as WeeklyOperatingPackage,read=await readWeeklyPublicationMetricEvidence(store,task,pkg,now);if(read.missingPublicationIds.length||!refs.length||Object.values(read.publicationMetricIds).some(ids=>!refs.some(ref=>ids.includes(ref.id)))||refs.some(ref=>ref.type!=='social_metric_snapshot'||ref.version!==1||!read.sources.some(row=>row.id===ref.id)))return fail('weekly_metrics_publication_attribution_required');}
