import test from 'node:test';
import assert from 'node:assert/strict';
import type {WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';
import {prepareWeeklyNonPresenterProductionFixture} from './weeklyNonPresenterProduction.fixture.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {STARTER_COLLECTIONS} from '../starter198/repository.js';
import {createWeeklyProductionRepairCaseService} from '../socialPrograms/weeklyProductionRepairCases.js';
import {createWeeklyCreativeRepairConfigurationService} from '../socialPrograms/weeklyCreativeRepairConfiguration.js';
import {createWeeklyCreativeRepairExecutionService} from '../socialPrograms/weeklyCreativeRepairExecution.js';
import {createWeeklyCreativeRepairProductionPort} from './weeklyCreativeRepairProductionPort.js';
import {readSocialTaskDetail} from '../starter198/socialContentRecords.js';
import {assessWeeklyOwnedProductIdentity,bindWeeklyOwnedProductIdentity} from './weeklyOwnedProductIdentityDemand.js';
import {createWeeklyMaterialRequestService} from '../socialPrograms/weeklyMaterialRequests.js';
import {readFile} from 'node:fs/promises';
import path from 'node:path';

test('full frozen planning revalidates owned-product capability and creates one creative child job',async t=>{
 const keys=['SEEDANCE_VIDEO_ENABLED','SEEDANCE_API_KEY','SEEDREAM_API_KEY'] as const,old=Object.fromEntries(keys.map(key=>[key,process.env[key]]));t.after(()=>{for(const key of keys){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});process.env.SEEDANCE_VIDEO_ENABLED='true';process.env.SEEDANCE_API_KEY='controlled-no-provider';process.env.SEEDREAM_API_KEY='controlled-no-provider';
 const x=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,primaryStructure:true,productInventory:true,targetCta:'Contact sales',metricTargets:['播放目标1000','点赞目标20','评论目标5','分享目标5']}),{f,pkg,created,repository}=x;
 pkg.executionGraphVersion=3;pkg.status='active';pkg.socialContentPackage.publicationTasks[0]!.publishWindow='2026-10-15T10:00:00Z';
 const packageRow=f.tables.social_weekly_operating_packages.find(row=>row.package_id===pkg.packageId&&row.version===pkg.version)!;packageRow.payload=pkg;
 const parent=f.tables.starter_social_content_tasks.find(row=>row.id===created.id)!;parent.weekly_plan_id=pkg.packageId;parent.status='plan_review';parent.run_id='';parent.artifact_count=1;parent.approved_artifact_count=0;
 const authority=(parent.brief as any)._weeklyAuthority;authority.weeklyPackage=structuredClone(pkg);authority.publicationTask=structuredClone(pkg.socialContentPackage.publicationTasks[0]);
 const artifact=f.tables.starter_social_content_artifacts![0]!;artifact.task_id=String(parent.task_id);artifact.status='changes_requested';artifact.version='v2';const operationId='full-creative-decision',operationRequestHash=socialRequestHash('full-creative-feedback');artifact.last_operation_id=operationId;
 await f.store.create(STARTER_COLLECTIONS.socialContentOperations,{tenant_id:'t',operation_id:operationId,operation:'decide_social_content_artifact',target_id:parent.task_id,request_hash:operationRequestHash,status:'processing'});
 const base=f.task,preparation:WeeklyExecutionTask={...base,taskId:'full-material-preparation',status:'queued',dependsOnTaskIds:[],ownBlockingReasons:[],inheritedBlockingTaskIds:[],resultRefs:[],lease:null,schedule:{...base.schedule,stepKind:'material_preparation'}},material:WeeklyExecutionTask={...base,scope:'content',taskId:'full-material-readiness',status:'queued',dependsOnTaskIds:[],ownBlockingReasons:[],inheritedBlockingTaskIds:[],resultRefs:[],lease:null,schedule:{...base.schedule,stepKind:'material_readiness'}},quality:WeeklyExecutionTask={...base,taskId:'full-creative-quality',status:'succeeded',dependsOnTaskIds:[],ownBlockingReasons:[],inheritedBlockingTaskIds:[],resultRefs:[],lease:null,schedule:{...base.schedule,stepKind:'quality_check',responsibleActor:'content_agent'}},approval:WeeklyExecutionTask={...quality,taskId:'full-creative-approval',status:'queued',ownBlockingReasons:[],inheritedBlockingTaskIds:[],dependsOnTaskIds:[quality.taskId],schedule:{...quality.schedule,stepKind:'user_approval',responsibleActor:'user'}};
 f.tables.social_weekly_execution_tasks=[preparation,material,quality,approval].map((payload,index)=>({id:`creative-row-${index}`,tenant_id:'t',program_id:pkg.programId,package_id:pkg.packageId,package_version:pkg.version,task_id:payload.taskId,payload}));
 const parentScope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:material.publicationTaskId!,contentTaskId:String(parent.task_id)},assessment=await assessWeeklyOwnedProductIdentity(f.store,parentScope,{repository});assert.equal(assessment.requirements.length,1);const requirement=assessment.requirements[0]!,inventory=await repository.materialLibrary!('t'),image=inventory.items.find(item=>requirement.imageIds.includes(item.id));assert.ok(image?.url);const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,''))),recordId='material0000003',sha=String(image.contentSha256),sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`,materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?{id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'}:null,materialBytes:{fetch:async()=>new Response(bytes,{headers:{'content-type':'image/png','content-length':String(bytes.length)}})}},ports={materialLibrary:repository.materialLibrary,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'creative-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'已核验产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const requests=createWeeklyMaterialRequestService(f.store,materialPorts),request=await requests.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-11T08:00:00Z',verificationDueAt:'2026-10-11T09:00:00Z',timeZone:'Asia/Shanghai',consumers:[{taskId:material.taskId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});await requests.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});await requests.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:material.taskId,accepted:true,factCheck:'产品身份一致',rightsCheck:'商业使用权已确认',visualCheck:'外观满足镜头要求'}]});await bindWeeklyOwnedProductIdentity(f.store,parentScope,{actorUserId:'owner',expectedTaskVersion:assessment.contentTaskVersion,expectedRequirementHash:assessment.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]},{...ports,repository});preparation.status='succeeded';material.status='succeeded';parent.status='asset_review';
 const clock=()=>new Date('2026-10-10T01:00:00Z'),cases=createWeeklyProductionRepairCaseService(f.store,clock),repair=await cases.createCreativeFromDecision({tenantId:'t',actorUserId:'owner',taskId:String(parent.task_id),artifactId:String(artifact.artifact_id),operationId,operationRequestHash,note:'CTA改成预约工厂打样'});
 const configuration=await createWeeklyCreativeRepairConfigurationService(f.store,clock).configure('t','owner',repair.caseId,{expectedCaseHash:repair.recordHash,revisionScope:'只修改CTA分镜和配音，保留产品事实',estimatedDurationMinutes:30,maximumCostCny:6,deadlineAt:'2026-10-14T10:00:00Z'});
 const port=createWeeklyCreativeRepairProductionPort(f.store,clock,ports),service=createWeeklyCreativeRepairExecutionService(f.store,port,clock),preview=await service.previewCapacity('t','owner',repair.caseId),current=await cases.read('t',repair.caseId),ready=await service.confirmCapacity('t','owner',repair.caseId,{expectedCaseRecordHash:current.recordHash,expectedConfigurationHash:configuration.recordHash,expectedPreviewHash:preview.previewHash,expectedAuthorityHash:preview.authorityHash,expectedQuoteHash:preview.quoteHash!,authorizedMaximumCostCny:6});
 const running=await service.start('t','owner',repair.caseId,{expectedCaseRecordHash:ready.recordHash});assert.equal(running.state,'running');assert.ok(running.execution);
 const child=f.tables.starter_social_content_tasks.find(row=>String(row.create_idempotency_key).startsWith('weekly-creative-repair:'));assert.ok(child);const repairGraph=f.tables.social_weekly_execution_tasks.filter(row=>String((row.payload as any).inputSnapshot?.creativeRepairExecution?.caseId??'')===repair.caseId);assert.deepEqual(repairGraph.map(row=>(row.payload as WeeklyExecutionTask).schedule.stepKind),['material_preparation','script','storyboard','material_readiness','asset_generation']);assert.equal(new Set(repairGraph.map(row=>row.task_id)).size,5);const {ensureWeeklyCreativeRepairExecutionGraph}=await import('./weeklyCreativeRepairExecutionGraph.js');await ensureWeeklyCreativeRepairExecutionGraph({store:f.store,tenantId:'t',childTaskId:String(child.task_id),proof:(child.brief as any)._weeklyCreativeRepairProof,configurationHash:configuration.recordHash,authorityHash:preview.authorityHash,now:clock()});assert.equal(f.tables.social_weekly_execution_tasks.filter(row=>String((row.payload as any).inputSnapshot?.creativeRepairExecution?.caseId??'')===repair.caseId).length,5);const detail=await readSocialTaskDetail({repository,tenantId:'t',taskId:String(child.task_id)});assert.ok(detail?.referenceVideoAnalysis);assert.notEqual(detail.referenceVideoAnalysis.status,'analyzing');assert.equal(detail.sources.filter(item=>item.kind==='material'&&item.sourceRef===sourceRef&&item.sourceVersion===sha&&item.status==='active').length,1);assert.ok(child.run_id);assert.equal(detail.agentWorkflow?.executionPlanReview.approved,true);const jobs=f.tables.content_execution_jobs?.filter(row=>row.task_id===child.task_id&&row.run_id===child.run_id)??[];assert.equal(jobs.length,1);assert.equal(jobs[0]!.status,'queued');const {createSocialWeeklyExecutionWorker}=await import('./socialWeeklyExecutionWorker.js'),weeklyWorker=createSocialWeeklyExecutionWorker(f.store),claim=await weeklyWorker.claimNext({tenantId:'t',workerId:'creative-repair-stage-worker',now:new Date()});assert.equal(claim?.task.schedule.stepKind,'material_preparation');assert.ok(claim);const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js'),stageAdapter=createSocialWeeklyProductionAdapter(f.store,{repository,ownedProductIdentity:ports,sourceOptions:ports.sourceOptions,now:()=>new Date()}),stageOutput=await stageAdapter.execute(claim.task);assert.equal(stageOutput.status,'succeeded',JSON.stringify(stageOutput));if(stageOutput.status!=='succeeded')throw Error('creative repair preparation missing');await weeklyWorker.complete(claim,stageOutput.resultRefs,new Date());assert.equal(f.tables.social_weekly_creative_repair_stage_evidence?.length,1);
 const {DurableContentExecutionWorker,readContentExecutionJob}=await import('../contentExecution/durableQueue.js'),{runSocialContentAutoProduction}=await import('../starter198/socialContentProductionExecution.js');let forbiddenSuppliers=0;const preSupplyWorker=new DurableContentExecutionWorker({dataStore:f.store,execute:job=>runSocialContentAutoProduction({repository,tenantId:job.tenantId,userId:job.userId,taskId:job.taskId,runId:job.runId,materialEvidencePorts:{...ports,repository},runtime:{synthesizeVoice:async()=>{forbiddenSuppliers++;throw Error('supplier before asset authorization');},renderComposite:async()=>{forbiddenSuppliers++;throw Error('render before asset authorization');}}}),env:{CONTENT_EXECUTION_TENANT_CONCURRENCY:'1'}});await preSupplyWorker.drain();for(let attempt=0;attempt<500&&preSupplyWorker.isLocallyActive('t',String(child.task_id));attempt++)await new Promise(resolve=>setTimeout(resolve,10));const paused=await readContentExecutionJob(f.store,'t',String(child.task_id),String(child.run_id));assert.equal(paused?.status,'paused',JSON.stringify(paused));assert.equal(paused?.id,jobs[0]!.id);assert.equal(forbiddenSuppliers,0);const {readWeeklyPreSupplyHandoff}=await import('../starter198/socialWeeklyPreSupplyHandoff.js');assert.ok(await readWeeklyPreSupplyHandoff(repository,'t',String(child.task_id)));
 for(const step of ['script','storyboard','material_readiness'] as const){const next=await weeklyWorker.claimNext({tenantId:'t',workerId:`creative-repair-${step}`,now:new Date()});assert.equal(next?.task.schedule.stepKind,step);assert.ok(next);const output=await stageAdapter.execute(next.task);assert.equal(output.status,'succeeded',JSON.stringify(output));if(output.status!=='succeeded')throw Error(`creative repair ${step} missing`);await weeklyWorker.complete(next,output.resultRefs,new Date());}
 const assetClaim=await weeklyWorker.claimNext({tenantId:'t',workerId:'creative-repair-assets',now:new Date()});assert.equal(assetClaim?.task.schedule.stepKind,'asset_generation');assert.ok(assetClaim);const assetPending=await stageAdapter.execute(assetClaim.task);assert.equal(assetPending.status,'pending',JSON.stringify(assetPending));const resumed=await readContentExecutionJob(f.store,'t',String(child.task_id),String(child.run_id));assert.equal(resumed?.id,jobs[0]!.id);assert.equal(resumed?.status,'queued',JSON.stringify(resumed));assert.equal(f.tables.content_execution_jobs?.filter(row=>row.task_id===child.task_id&&row.run_id===child.run_id).length,1);

});
