import assert from 'node:assert/strict';
import test from 'node:test';
import { prepareWeeklyEnterpriseFactFixture } from './weeklyEnterpriseFactSupplement.fixture.js';
import { supplementConsumerHash } from '../socialPrograms/weeklySupplementRequests.js';
import { bindWeeklyPreproductionAuthority, runWeeklyPreproductionProducerScan, readWeeklyPreproductionExecutionGate, listWeeklyPreproductionJobs, WEEKLY_PREPRODUCTION_JOBS } from './weeklyPreproductionProducer.js';
import type { Record_ } from '../storage/datastore.js';
async function setup(t: Parameters<typeof prepareWeeklyEnterpriseFactFixture>[0]) { const c = await prepareWeeklyEnterpriseFactFixture(t); c.task.schedule.stepKind = 'business_outline'; c.task.workflowKind = 'readiness'; c.task.scope = 'package'; c.task.inputSnapshot = {}; await c.store.create('social_weekly_execution_tasks', { tenant_id: c.task.tenantId, program_id: c.task.programId, package_id:c.task.packageId,package_version:c.task.packageVersion,status:c.task.status,task_id: c.task.taskId, idempotency_key: c.task.idempotencyKey, payload: c.task }); return c; }
test('formal actor binding makes outline prerequisite independently of dispatch and retains frozen operating authority', async (t) => { const c = await setup(t); assert.equal((await readWeeklyPreproductionExecutionGate(c.store, c.task)).ready, false); const input = { store: c.store, tenantId: c.task.tenantId, programId: c.task.programId, packageId: c.task.packageId, packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'outline' as const, expectedConsumerInputHash: supplementConsumerHash(c.task) }; const j = await bindWeeklyPreproductionAuthority(input); assert.equal(j.status, 'bound'); const report = await runWeeklyPreproductionProducerScan({ store: c.store }); assert.equal(report.succeeded, 1, JSON.stringify(report)); const gate = await readWeeklyPreproductionExecutionGate(c.store, c.task); assert.equal(gate.ready, true); assert.equal(gate.resultRefs[0]?.id, c.authority.snapshot.snapshotId); assert.equal((await bindWeeklyPreproductionAuthority(input)).jobId, j.jobId); assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).succeeded, 0); assert.equal((await listWeeklyPreproductionJobs(input)).length, 1); });
test('cross tenant, changed deadline and corrupt receipt never prove prerequisite', async (t) => { const c = await setup(t); const input = { store: c.store, tenantId: c.task.tenantId, programId: c.task.programId, packageId: c.task.packageId, packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'outline' as const, expectedConsumerInputHash: supplementConsumerHash(c.task) }; await assert.rejects(bindWeeklyPreproductionAuthority({ ...input, tenantId: 'tenant-b' })); const j = await bindWeeklyPreproductionAuthority(input); await c.store.update(WEEKLY_PREPRODUCTION_JOBS, j.jobId, { record_hash: 'tampered' }); await assert.rejects(readWeeklyPreproductionExecutionGate(c.store, c.task), /corrupt/); assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).failed, 1); });
test('unconfirmed enterprise facts persist blocked and only authenticated rebind can restore authority', async (t) => { const c = await setup(t); const row = (await c.store.list<Record_>('tenant_profiles', { where: { tenant_id: 'tenant-a' } })).items[0]!; const p = structuredClone(c.profile); delete p.factVersion; await c.store.update('tenant_profiles', row.id, { profile: p }); const input = { store: c.store, tenantId: c.task.tenantId, programId: c.task.programId, packageId: c.task.packageId, packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'outline' as const, expectedConsumerInputHash: supplementConsumerHash(c.task) }; const j = await bindWeeklyPreproductionAuthority(input); assert.equal(j.status, 'blocked'); assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).blocked, 1); await c.confirm(); assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).blocked, 1); assert.equal((await bindWeeklyPreproductionAuthority(input)).status, 'bound'); assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).succeeded, 1); });
test('approved M2 scope binds exact consumer, missing credentials persist blocked and empty collection is no_data', async (t) => { const c = await setup(t); c.task.schedule.stepKind = 'benchmark_collection'; await c.store.update('social_weekly_execution_tasks', (await c.store.list<Record_>('social_weekly_execution_tasks')).items[0]!.id, {status:c.task.status,payload:c.task}); const scopeRow = { id: 'scope-a', tenant_id: 'tenant-a', version: 1, status: 'active', payload: { approval: { status: 'approved', scopeVersion: 1, approvedBy: 'owner' }, market: 'US', language: 'en', keywords: [], discoveryBrief: { discoveryBriefId: 'brief', keywordSetId: 'keywords', keywordSetVersion: 1, productRef: 'product', market: 'US', audience: 'buyer', discoverySeedIds: [], trackedSceneIds: [], competitorAccounts: [], discoveryModes: ['momentum'], platforms: ['tiktok'], lookbackDays: 7, resultLimit: 1, budgetLimitCny: 0, productionGap: null, createdBy: 'director_agent', modePolicies: { momentum: { enabled: true, sourceRefs: ['query'], platforms: ['tiktok'], resultLimit: 1, refreshIntervalMinutes: 60, budgetLimitCny: 0 } } } } }; await c.store.create('social_discovery_scopes', scopeRow); const input = { store: c.store, tenantId: c.task.tenantId, programId: c.task.programId, packageId: c.task.packageId, packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'discovery' as const, expectedConsumerInputHash: supplementConsumerHash(c.task), discovery: { scopeId: 'scope-a', scopeVersion: 1, requestedModes: ['momentum' as const] } }; await bindWeeklyPreproductionAuthority(input); const oldToken = process.env.APIFY_TOKEN; delete process.env.APIFY_TOKEN; try {
    assert.equal((await runWeeklyPreproductionProducerScan({ store: c.store })).blocked, 1);
    assert.equal((await readWeeklyPreproductionExecutionGate(c.store, c.task)).ready, false);
    process.env.APIFY_TOKEN = 'controlled-test-port';
    let calls = 0;
    const deps = { dataStore: c.store, async crawl() { calls++; return { platform: 'tiktok' as const, keyword: 'q', imported: 0, refreshed: 0, skipped: 0, skippedExisting: 0, returnedExisting: 0, requested: 1, total: 0, source: 'r3' as const, message: '', candidateIds: [], items: [] }; }, candidateEvidenceAdapter: { async toEvidenceWorkItems() { return []; } }, async runCandidateEvidence() { return { accepted: [], suggestions: [], failed: [] }; } };
    const report = await runWeeklyPreproductionProducerScan({ store: c.store, discoveryDependencies: deps });
    assert.equal(report.noData, 1, JSON.stringify(report));
    assert.equal((await readWeeklyPreproductionExecutionGate(c.store, c.task)).ready, false);
    await runWeeklyPreproductionProducerScan({ store: c.store, discoveryDependencies: deps });
    assert.equal(calls, 1, 'same original empty run must not recollect');
}
finally {
    if (oldToken === undefined)
        delete process.env.APIFY_TOKEN;
    else
        process.env.APIFY_TOKEN = oldToken;
} });
test('M1 calls formal operating producer and exact readback recovers lost snapshot acknowledgement without new snapshot', async (t) => { const c = await setup(t); delete c.pkg.operatingDecisionSnapshotRef; delete c.pkg.businessContentGoalRef; const pr = (await c.store.list<Record_>('social_weekly_operating_packages')).items[0]!; await c.store.update('social_weekly_operating_packages', pr.id, { payload: c.pkg }); const input = { store: c.store, tenantId: c.task.tenantId, programId: c.task.programId, packageId: c.task.packageId, packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'outline' as const, expectedConsumerInputHash: supplementConsumerHash(c.task) }; await bindWeeklyPreproductionAuthority(input); const create = c.store.create.bind(c.store); let lost = true; t.mock.method(c.store, 'create', async (...args: Parameters<typeof c.store.create>) => { const result = await create(...args); if (args[0] === 'social_operating_authority_snapshots' && lost) {
    lost = false;
    throw Error('lost acknowledgement');
} return result; }); const first = await runWeeklyPreproductionProducerScan({ store: c.store }); assert.equal(first.failed, 1, JSON.stringify(first)); assert.match(first.failures[0]!.code, /lost acknowledgement/, JSON.stringify(first)); const n = (await c.store.list('social_operating_authority_snapshots', { perPage: 500 })).totalItems; const restored = await runWeeklyPreproductionProducerScan({ store: c.store }); assert.equal(restored.succeeded, 1, JSON.stringify(restored)); assert.equal((await c.store.list('social_operating_authority_snapshots', { perPage: 500 })).totalItems, n); assert.equal((await readWeeklyPreproductionExecutionGate(c.store, c.task)).ready, true); });
test('M2 formal accepted supply produces director analysis and merged schedule before user confirmation', async (t) => { const c = await setup(t); const { preproductionPackage, seedPreproductionSupply } = await import('./weeklyPreproductionProducer.fixture.js'); const pkg = preproductionPackage(); pkg.socialContentPackage.publicationTasks[0]!.factRefs = c.authority.goal.publicFactRefs; await c.store.update('social_weekly_operating_packages', (await c.store.list<Record_>('social_weekly_operating_packages')).items[0]!.id, { payload: pkg }); c.task.schedule.stepKind = 'benchmark_collection'; c.task.status = 'blocked'; c.task.ownBlockingReasons = ['weekly_preproduction_authority_required', 'business_dispatch_required']; await c.store.update('social_weekly_execution_tasks', (await c.store.list<Record_>('social_weekly_execution_tasks')).items[0]!.id, {status:c.task.status,payload:c.task}); await seedPreproductionSupply(c.store); await c.store.create('social_discovery_scopes', { id: 'scope-positive', tenant_id: 'tenant-a', version: 1, status: 'active', payload: { approval: { status: 'approved', scopeVersion: 1, approvedBy: 'owner' }, market: 'US', language: 'en', keywordSet: { scope: { audienceRole: 'brand_buyer' }, graph: { sceneClusters: [] } }, keywords: [], discoveryBrief: { discoveryBriefId: 'brief', keywordSetId: 'keywords', keywordSetVersion: 1, productRef: 'product', market: 'US', audience: 'buyer', discoverySeedIds: [], trackedSceneIds: [], competitorAccounts: [], discoveryModes: ['momentum'], platforms: ['tiktok'], lookbackDays: 7, resultLimit: 1, budgetLimitCny: 0, productionGap: null, createdBy: 'director_agent', modePolicies: { momentum: { enabled: true, sourceRefs: ['query'], platforms: ['tiktok'], resultLimit: 1, refreshIntervalMinutes: 60, budgetLimitCny: 0 } } } } }); await bindWeeklyPreproductionAuthority({ store: c.store, tenantId: 'tenant-a', programId: 'program-a', packageId: 'package-a', packageVersion: 1, taskId: c.task.taskId, actorUserId: 'owner', kind: 'discovery', expectedConsumerInputHash: supplementConsumerHash(c.task), discovery: { scopeId: 'scope-positive', scopeVersion: 1, requestedModes: ['momentum'] } }); const old = process.env.APIFY_TOKEN; process.env.APIFY_TOKEN = 'controlled-test-port'; let calls = 0; try {
    const deps = { dataStore: c.store, async crawl() { calls++; return { platform: 'tiktok' as const, keyword: 'query', imported: 1, refreshed: 0, skipped: 0, skippedExisting: 0, returnedExisting: 0, requested: 1, total: 1, source: 'r3' as const, message: '', candidateIds: ['video-1'], items: [] }; }, candidateEvidenceAdapter: { async toEvidenceWorkItems() { return [{ tenantId: 'tenant-a', candidateId: 'video-1', discoveryPath: ['keyword'] as Array<'keyword'>, evidenceRefs: ['source'], g1: { runId: 'bound-run', queryRef: 'query', discoveryMode: 'momentum' as const, sourceUrl: 'https://www.tiktok.com/video-1' } }]; } }, async runCandidateEvidence() { const evidence = (await c.store.list<import('../socialDiscovery/qualityOrchestration.js').VersionedCandidateEvidence>('social_candidate_evidence')).items[0]!; return { accepted: [evidence], suggestions: [], failed: [] }; } };
    const {runSocialWeeklyExecutionScan}=await import('./socialWeeklyExecutionRuntime.js');
        const result=await runSocialWeeklyExecutionScan({dataStore:c.store,adapters:{},preproductionPorts:{discoveryDependencies:deps}});const report=result.preproduction;
    assert.equal(report.succeeded, 1, JSON.stringify({ report, jobs: (await c.store.list<Record_>(WEEKLY_PREPRODUCTION_JOBS)).items.map(r => r.payload) }));
    const planner = (await import('../socialPrograms/planningAuthority.js')).createWeeklyPlanningAuthority(c.store);
    const planning = await planner.get('tenant-a', 'program-a', 'package-a', 1);
    assert.equal(planning.status, 'awaiting_confirmation');
    assert.equal(planning.directorAnalyses.length, 1);
    assert.equal(planning.detailedSchedule?.items.length, 1);
    const task = (await c.store.list<Record_>('social_weekly_execution_tasks')).items[0]!.payload as typeof c.task;
    assert.deepEqual(task.ownBlockingReasons, ['business_dispatch_required']);
    assert.equal(task.status, 'blocked');
    assert.equal((await readWeeklyPreproductionExecutionGate(c.store, task)).ready, true);
    await runSocialWeeklyExecutionScan({dataStore:c.store,adapters:{},preproductionPorts:{discoveryDependencies:deps}});
    assert.equal(calls, 1);
}
finally {
    if (old === undefined)
        delete process.env.APIFY_TOKEN;
    else
        process.env.APIFY_TOKEN = old;
} });
test('late deadline change, successor package and incomplete durable scan never restore old consumer',async t=>{const c=await setup(t);const input={store:c.store,tenantId:'tenant-a',programId:'program-a',packageId:'package-a',packageVersion:1,taskId:c.task.taskId,actorUserId:'owner',kind:'outline' as const,expectedConsumerInputHash:supplementConsumerHash(c.task)};await bindWeeklyPreproductionAuthority(input);c.task.schedule.estimatedStartAt='2026-10-13T00:00:00Z';const tr=(await c.store.list<Record_>('social_weekly_execution_tasks')).items[0]!;await c.store.update('social_weekly_execution_tasks',tr.id,{payload:c.task});assert.equal((await runWeeklyPreproductionProducerScan({store:c.store})).failed,1);assert.equal((await readWeeklyPreproductionExecutionGate(c.store,c.task)).ready,false);c.task.packageVersion=2;await c.store.update('social_weekly_execution_tasks',tr.id,{payload:c.task});assert.equal((await runWeeklyPreproductionProducerScan({store:c.store})).failed,1);const list=c.store.list.bind(c.store);t.mock.method(c.store,'list',async<T>(collection:string,query:import('../storage/datastore.js').ListQuery={})=>{const r=await list<T>(collection,query);return collection===WEEKLY_PREPRODUCTION_JOBS?{...r,totalItems:r.totalItems+1}:r;});await assert.rejects(runWeeklyPreproductionProducerScan({store:c.store}),/scan_invalid|scan_incomplete/);});
