import assert from 'node:assert/strict';
import test from 'node:test';
import type {WeeklyExecutionTask,WeeklyOperatingPackage} from '../../shared/contracts/socialProgram.js';
import {prepareWeeklyHardQualityRepairFixture} from '../socialPrograms/weeklyContentQualityRecovery.fixture.js';
import {createWeeklyExecutionTaskService,WEEKLY_EXECUTION_TASKS} from '../socialPrograms/executionTasks.js';
import {createSocialWeeklyExecutionWorker} from './socialWeeklyExecutionWorker.js';
import {createSocialWeeklyProductionAdapter} from './socialWeeklyProductionAdapter.js';

test('actual repair child completes the original quality and conditional rework cards before explicit user approval',async t=>{
 t.mock.timers.enable({apis:['Date'],now:new Date('2026-10-02T05:00:00Z')});
 const f=await prepareWeeklyHardQualityRepairFixture();t.after(f.cleanup);
 Object.assign(f.pkg,{executionGraphVersion:2});
 f.pkg.workflowTasks.push({taskId:'actual-publishing-workflow',kind:'publishing',taskRef:{type:'weekly_workflow_task',id:'actual-publishing-workflow',version:1},dependsOnTaskIds:['content-workflow'],subjectRefs:[{type:'weekly_publication_task',id:'pub',version:1}],status:'planned',ownBlockingReasons:[],inheritedBlockingTaskIds:[],carriedFromTaskId:null});
 const now='2026-10-02T05:00:00Z';
 const pub=f.pkg.socialContentPackage.publicationTasks[0]!;pub.publishWindow=`${f.pkg.weekStart}T12:00:00+08:00`;
 f.pkg.socialContentPackage.authorization={mode:'bounded',accountIds:[pub.accountId],maxPublishItems:1,weekStart:f.pkg.weekStart,weekEnd:f.pkg.weekEnd,allowRealPublishing:true,authorizedBy:'owner',authorizedAt:`${f.pkg.weekStart}T00:00:00+08:00`,revokedBy:null,revokedAt:null};
 const {savePublicationReceptionBinding}=await import('../socialPrograms/publicationReceptionService.js');
 const reception=await savePublicationReceptionBinding(f.store,{tenantId:'t',programId:'p',packageId:'week1',packageVersion:1,publicationId:'pub',cta:pub.cta!,enterpriseFactHash:f.profile.factVersion!.contentHash,targets:[{id:'sales-inbox',required:true,ownerId:'owner',destination:{kind:'messaging',channel:'messenger',receptionMode:'human'},requiredDocumentUrls:[]}]},'owner');pub.receptionRequirement={required:true,bindingId:reception.bindingId};
 const sourceBrief=f.tables.starter_social_content_tasks![0]!.brief as Record<string,unknown>,authority=sourceBrief._weeklyAuthority as {weeklyPackage:WeeklyOperatingPackage;publicationTask:typeof pub};authority.publicationTask=structuredClone(pub);authority.weeklyPackage=structuredClone(f.pkg);
 const {sealAccountCredential}=await import('../lib/accountCredentials.js');const {refreshPlatformCapabilityEvidence}=await import('../publishing/platformCapabilities.js');
 f.tables.social_accounts=[{id:pub.accountId,tenantId:'t',platform:'tiktok',status:'connected',providerAccountId:'actual-open-id',scope:'video.publish',accessToken:sealAccountCredential('controlled-provider-token')},{id:'messenger-sales',tenantId:'t',platform:'facebook',status:'connected',providerAccountId:'actual-sales-page',messengerSubscribed:true,accessToken:sealAccountCredential('controlled-messenger-token')}];
 await refreshPlatformCapabilityEvidence({tenantId:'t',accountId:pub.accountId,platform:'tiktok',capability:'publishing.official',dataStore:f.store,providers:{async tiktok(){return {openId:'actual-open-id',publishGranted:true};},async youtube(){throw Error('not used');},async instagram(){throw Error('not used');},async facebook(){throw Error('not used');},async tiktokReceipt(){throw Error('not used');}}});
 const rework:WeeklyExecutionTask={...f.task,taskId:'weekly-rework-verification',subjectId:'pub:rework',status:'blocked',dependsOnTaskIds:[f.task.taskId],inheritedBlockingTaskIds:[f.task.taskId],ownBlockingReasons:[],resultRefs:[],attempt:0,idempotencyKey:'weekly-rework-verification',schedule:{...f.task.schedule,stepKind:'rework',responsibleActor:'content_agent',actualStartedAt:null,actualFinishedAt:null},lastError:null,createdAt:now,updatedAt:now};
 const approval:WeeklyExecutionTask={...f.task,taskId:'weekly-user-approval',subjectId:'pub:approval',status:'blocked',dependsOnTaskIds:[rework.taskId],inheritedBlockingTaskIds:[rework.taskId],ownBlockingReasons:[],resultRefs:[],attempt:0,idempotencyKey:'weekly-user-approval',budget:{category:'none',limitCny:null},schedule:{...f.task.schedule,stepKind:'user_approval',responsibleActor:'user',actualStartedAt:null,actualFinishedAt:null},lastError:null,createdAt:now,updatedAt:now};
 const publishing:WeeklyExecutionTask={...f.task,taskId:'weekly-publishing',workflowKind:'publishing',scope:'publication',subjectId:'pub:publishing',status:'blocked',dependsOnTaskIds:[approval.taskId],inheritedBlockingTaskIds:[approval.taskId],ownBlockingReasons:[],resultRefs:[],attempt:0,idempotencyKey:'weekly-publishing',budget:{category:'none',limitCny:0},schedule:{...f.task.schedule,stepKind:'publishing',responsibleActor:'publishing_agent',actualStartedAt:null,actualFinishedAt:null},lastError:null,createdAt:now,updatedAt:now};
 for(const task of [rework,approval,publishing])await f.store.create(WEEKLY_EXECUTION_TASKS,{tenant_id:'t',program_id:'p',package_id:'week1',package_version:1,task_id:task.taskId,workflow_kind:task.workflowKind,status:task.status,idempotency_key:task.idempotencyKey,next_attempt_at:'',payload:task,created_at:now,updated_at:now});
 await f.auditChildG4();await f.auditChildG5();
 const context=await f.service.context(f.childScope,'owner'),consumer=context.consumers.find(item=>item.executionTaskId===f.task.taskId);assert.ok(consumer?.resumeAvailable);
 await f.service.resume(f.childScope,'owner',{executionTaskId:f.task.taskId,requestId:'actual-card-chain-recovery-0001',expectedContextHash:consumer.contextHash});
 const worker=createSocialWeeklyExecutionWorker(f.store),adapter=createSocialWeeklyProductionAdapter(f.store,{repository:f.repository});
 const workerNow=new Date(Date.parse(f.current().nextAttemptAt!)+1000);
 const qualityClaim=await worker.claimNext({tenantId:'t',workerId:'quality-worker',now:workerNow});assert.equal(qualityClaim?.task.taskId,f.task.taskId);assert.ok(qualityClaim);
 const qualityResult=await adapter.execute(qualityClaim.task);assert.equal(qualityResult.status,'succeeded',JSON.stringify(qualityResult));if(qualityResult.status!=='succeeded')return;
 assert.deepEqual(qualityResult.resultRefs,[{type:'starter_social_content_artifact',id:f.result.artifactId,version:1}]);
 const quality=await worker.complete(qualityClaim,qualityResult.resultRefs,workerNow);assert.equal(quality.status,'succeeded');
 const reworkClaim=await worker.claimNext({tenantId:'t',workerId:'rework-verifier',now:workerNow});assert.equal(reworkClaim?.task.taskId,rework.taskId);assert.ok(reworkClaim);
 const reworkResult=await adapter.execute(reworkClaim.task);assert.equal(reworkResult.status,'succeeded',JSON.stringify(reworkResult));if(reworkResult.status!=='succeeded')return;
 assert.deepEqual(reworkResult.resultRefs,qualityResult.resultRefs);
 const verified=await worker.complete(reworkClaim,reworkResult.resultRefs,workerNow);assert.equal(verified.status,'succeeded');
 const beforeApproval=f.tables.social_weekly_execution_tasks!.find(row=>row.task_id===approval.taskId)!.payload as WeeklyExecutionTask;assert.equal(beforeApproval.status,'queued');
 const accepted=(await createWeeklyExecutionTaskService(f.store).approve('t','p','week1',approval.taskId,'owner')).find(task=>task.taskId===approval.taskId)!;
 assert.equal(accepted.status,'succeeded');const acceptedArtifact=accepted.resultRefs.find(ref=>ref.type==='starter_social_content_artifact');assert.deepEqual(acceptedArtifact,{type:'starter_social_content_artifact',id:f.result.artifactId,version:2});
 const {createSocialWeeklyG6ReviewService}=await import('../starter198/socialWeeklyG6ReviewService.js');const g6=createSocialWeeklyG6ReviewService(f.repository);const g6Scope={...f.childScope,programId:'p',packageId:'week1',packageVersion:1,publicationTaskId:'pub'};
 const g6Context=await g6.context(g6Scope,'owner');assert.deepEqual(g6Context.gaps,[]);assert.ok(g6Context.checks.every(check=>check.status==='passed'),JSON.stringify(g6Context.checks));
 const g6Read=await g6.check(g6Scope,'owner',{programId:'p',packageId:'week1',packageVersion:1,publicationTaskId:'pub',requestId:'actual-hard-repair-g6-0001',expectedContextHash:g6Context.contextHash});assert.equal(g6Read.item?.status,'passed');
 const {runWeeklyPublicationPackageScan}=await import('../publishing/weeklyPublicationWorker.js');const scan=await runWeeklyPublicationPackageScan({dataStore:f.store,tenantId:'t',taskId:'content'});assert.deepEqual(scan.errors,[]);assert.equal(scan.createdAssignments,1);assert.equal(scan.createdPackages,1);
 const assignment=f.tables.social_publication_assignments![0]!;assert.equal(assignment.production_result_id,g6Context.productionResultId);assert.equal((assignment.payload as {lineage:{productionResultRef:{id:string}}}).lineage.productionResultRef.id,g6Context.productionResultId);
 const again=await runWeeklyPublicationPackageScan({dataStore:f.store,tenantId:'t',taskId:'content'});assert.equal(again.createdAssignments,0);assert.equal(again.createdPackages,0);
 let posts=0,lookups=0;const provider={provider:'tiktok-content-posting-api',platform:'tiktok' as const,capability:'available' as const,async publish(){posts++;return {status:'unknown' as const,providerReceiptId:'actual-m1-unknown-receipt'};},async reconcile(){lookups++;return {status:'published' as const,providerReceiptId:'actual-m1-unknown-receipt',platformPostId:'actual-m1-post'};}};
 const {createSocialWeeklyPublicationAdapter}=await import('./socialWeeklyPublicationAdapter.js');const publicationAdapter=createSocialWeeklyPublicationAdapter(f.store,{publishingEnabled:()=>true,now:()=>workerNow,adapterFactory:async()=>provider});
 const publishClaim=await worker.claimNext({tenantId:'t',workerId:'publishing-worker',now:workerNow});assert.equal(publishClaim?.task.taskId,publishing.taskId);assert.ok(publishClaim);
 const pending=await publicationAdapter.execute(publishClaim.task);assert.equal(pending.status,'pending',JSON.stringify(pending));if(pending.status!=='pending')return;await worker.defer(publishClaim,{code:pending.code,message:pending.message,retryDelayMs:pending.retryDelayMs,now:workerNow});assert.equal(posts,1);assert.equal(lookups,0);
 const retryAt=new Date(workerNow.getTime()+(pending.retryDelayMs??30000)+1000),retryClaim=await worker.claimNext({tenantId:'t',workerId:'publishing-worker',now:retryAt});assert.equal(retryClaim?.task.taskId,publishing.taskId);assert.ok(retryClaim);
 const published=await publicationAdapter.execute(retryClaim.task);assert.equal(published.status,'succeeded',JSON.stringify(published));if(published.status!=='succeeded')return;await worker.complete(retryClaim,published.resultRefs,retryAt);assert.equal(posts,1);assert.equal(lookups,1);assert.equal(f.tables.social_publication_attempts!.length,1);
 assert.equal(f.supplierCalls(),1,'quality, conditional rework and approval must not start another supplier call');
 assert.equal(f.tables.content_execution_jobs!.length,1,'the independent repair job remains the only added production job');
});
