import {prepareWeeklyQualityAuditFixture} from './weeklyContentQualityAudit.fixture.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import type {WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';
import {g5FixtureScope,passedDirectorChecks} from '../starter198/socialDirectorG5ReviewService.fixture.js';
import {validateContentArtifact} from './socialWeeklyResultValidation.js';
import {readVerifiedWeeklyContentQualityAudit} from './weeklyContentQualityAudit.js';
import {SOCIAL_DIRECTOR_G5_REVIEWS} from '../starter198/socialDirectorG5ReviewService.js';
import {createWeeklyExecutionTaskService} from '../socialPrograms/executionTasks.js';
import {SocialProgramError} from '../socialPrograms/service.js';
import {buildSocialContentAuthorityLineage} from '../starter198/socialContentLineage.js';
import {productionFromApprovedWeeklyArtifact} from '../publishing/weeklyPublicationWorker.js';
import {createSocialWeeklyProductionAdapter} from './socialWeeklyProductionAdapter.js';
import {inventoryFixture} from '../socialPrograms/weeklyInventoryReuse.fixture.js';
import {createWeeklyInventoryReuseService} from '../socialPrograms/weeklyInventoryReuse.js';
import {createWeeklyOperatingPackageService} from '../socialPrograms/weeklyOperatingPackages.js';
import {createSocialOperatingRepository} from '../socialOperating/repository.js';
import type {OperatingAuthoritySnapshot} from '../../shared/contracts/socialOperatingDecision.js';
import {createSocialWeeklyPlanningAdapter,runSocialWeeklyExecutionScan} from './socialWeeklyExecutionRuntime.js';

test('default production persistence and actual G4/G5 plus separate weekly human approvals support immutable false-summary inventory assignment',async t=>{
 const f=await prepareWeeklyQualityAuditFixture();t.after(f.cleanup);
 const {task,ref,pkg,artifact,originalHash}=f;
 await assert.rejects(validateContentArtifact(f.store,task,ref));
 await f.g5.assign(g5FixtureScope,'owner',{reviewerUserId:'owner'});
 const context=await f.g5.context(g5FixtureScope,'owner');
 await f.g5.human(g5FixtureScope,'owner',{requestId:'weekly-quality-real-human-audit-0001',expectedContextHash:context.contextHash,checks:passedDirectorChecks(context)});
 const audit=await readVerifiedWeeklyContentQualityAudit(f.store,task,ref);
 assert.ok(audit.receiptId);assert.ok(audit.reviewId);
 await validateContentArtifact(f.store,task,ref);
 await validateContentArtifact(f.store,{...task,schedule:{...task.schedule,stepKind:'rework'}},ref);
 const adapter=createSocialWeeklyProductionAdapter(f.store,{start:async()=>{throw Error('must not start paid production');},create:async()=>{throw Error('must not create another content identity');}});
 const actualExecution=await adapter.execute(task);
 assert.equal(actualExecution.status,'succeeded',JSON.stringify(actualExecution));
 assert.equal(f.tables.starter_social_content_lineage?.length,1,'default persistence stores real output authority');
 assert.equal(artifact.status,'review_required');assert.equal(artifact.content_hash,originalHash);
 assert.equal(f.result.technicalReview.approved,false);assert.equal(f.result.creativeReview.approved,false);
 assert.equal(f.tables.social_publication_attempts?.length??0,0);
 const dependency:WeeklyExecutionTask={...task,taskId:'quality-verified',status:'succeeded',dependsOnTaskIds:[],inheritedBlockingTaskIds:[],ownBlockingReasons:[],resultRefs:[ref],inputSnapshot:{},schedule:{...task.schedule,responsibleActor:'content_agent'}};
 const approval={...dependency,taskId:'actual-final-user-approval',status:'blocked' as const,dependsOnTaskIds:[dependency.taskId],resultRefs:[],schedule:{...dependency.schedule,stepKind:'user_approval' as const,responsibleActor:'user' as const}};
 const row=(item:WeeklyExecutionTask)=>({id:item.taskId,tenant_id:item.tenantId,program_id:item.programId,package_id:item.packageId,package_version:item.packageVersion,task_id:item.taskId,payload:item});
 f.tables.social_weekly_execution_tasks=[row(dependency),row(approval)];
 f.tables.starter_social_content_tasks![0]!.weekly_plan_id='week1';
 dependency.status='blocked';
 await assert.rejects(createWeeklyExecutionTaskService(f.store).approve('t','p','week1',approval.taskId,'owner'),error=>error instanceof SocialProgramError&&error.code==='weekly_execution_upstream_incomplete');
 dependency.status='succeeded';
 await createWeeklyExecutionTaskService(f.store).approve('t','p','week1',approval.taskId,'owner');
 assert.equal(artifact.status,'approved');assert.equal(artifact.version,'2');
 const savedApproval=f.tables.social_weekly_execution_tasks!.find(r=>r.task_id===approval.taskId)!.payload as WeeklyExecutionTask;
 assert.equal(savedApproval.status,'succeeded');assert.ok(savedApproval.resultRefs.some(r=>r.type==='user_content_approval'));
 await validateContentArtifact(f.store,task,{...ref,version:2});
 const versioned=(type:string,id:string)=>({type,id,version:1});
 const lineage=buildSocialContentAuthorityLineage({version:'1',programRef:versioned('social_program','p'),packageRef:versioned('weekly_operating_package','week1'),weeklyTaskRef:versioned('weekly_workflow_task','content-workflow'),publicationTaskRef:versioned('weekly_publication_task','pub'),businessGoalRef:versioned('business_content_goal','goal'),enterpriseProfileRef:versioned('enterprise_profile','profile'),enterpriseFactRefs:[],referenceSelectionRef:versioned('reference_selection','selection'),candidateEvidenceRefs:[],inspirationHandoffs:[],directorBrief:f.handoff.directorBrief,productionResult:f.result});
 const approvedArtifact={id:artifact.id,tenant_id:String(artifact.tenant_id),task_id:String(artifact.task_id),artifact_id:String(artifact.artifact_id),version:String(artifact.version),status:String(artifact.status),content_hash:String(artifact.content_hash),resource_ref:String(artifact.resource_ref),content:artifact.content};
 const publishable=await productionFromApprovedWeeklyArtifact(f.store,approvedArtifact,lineage,pkg,{preserveProductionVersion:true});
 assert.equal(publishable.productionResultId,f.result.productionResultId);
 assert.ok(publishable.sourceRefs.some(r=>r.type==='social_director_g5_review'&&r.id===audit.reviewId));
 // Only copy the independent target week's operating authority; retain the actual
 // false-summary source media, G4/G5, default-persisted lineage and human decision.
 const targetFixture=await inventoryFixture();t.after(targetFixture.cleanup);
 for(const collection of ['social_programs','social_owned_accounts','social_operating_decisions','social_business_content_goals'])f.tables[collection]=structuredClone(targetFixture.tables[collection]!);
 const target=structuredClone(targetFixture.target);
 f.tables.social_weekly_operating_packages=f.tables.social_weekly_operating_packages!.filter(row=>row.package_id!=='week2');
 await f.store.create('social_weekly_operating_packages',{tenant_id:'t',program_id:'p',package_id:'week2',version:1,payload:target});
 const account=f.tables.social_owned_accounts![0]!;account.account_id='account';(account.payload as Record<string,unknown>).version=1;
 const snapshot:OperatingAuthoritySnapshot={snapshotId:'actual-false-inventory-snapshot',programId:'p',version:1,status:'ready',programRef:versioned('social_program','p'),enterprise:{ref:versioned('enterprise_operating_snapshot','enterprise'),products:['product'],markets:['US'],audiences:['buyers'],languages:['en'],publicFacts:[{ref:versioned('enterprise_fact','fact'),statement:f.profile.company.description}],prohibitedClaims:[],weeklyBudgetCny:10,salesOwnerId:'owner'},accountRefs:[versioned('owned_social_account','account')],conversionRouteRefs:[versioned('conversion_route','inquiry')],constraintsRef:versioned('social_operating_constraints','capacity-constraints'),capabilityStates:{'studio.production':'available','publishing.calendar':'available','customer.attribution':'available'},capabilitySourceRefs:{'studio.production':[],'publishing.calendar':[],'customer.attribution':[]},businessContentGoalRef:target.businessContentGoalRef!,capacityPlanRef:target.capacityPlanRef!,automationPolicyRef:target.automationPolicyRef!,referenceModeRef:versioned('reference_mode','mode'),decisionRefs:[versioned('decision_record','inventory-goal-decision')],impacts:[],invalidations:[],inputFingerprint:'actual-false-inventory-input',createdBy:'owner',createdAt:'2026-10-01T00:00:00Z'};
 await createSocialOperatingRepository(f.store).saveSnapshot('t',snapshot);target.operatingDecisionSnapshotRef=versioned('operating_authority_snapshot',snapshot.snapshotId);
 const inventory=createWeeklyInventoryReuseService(f.store),authority={tenantId:'t',programId:'p',packageId:'week2',packageVersion:1,actorUserId:'owner'};
 const candidates=await inventory.candidates(authority);assert.equal(candidates.items.length,1,JSON.stringify(candidates.gaps));
 const candidate=candidates.items[0]!;assert.ok(candidate.source.sourceRefs.some(r=>r.type==='social_director_g5_review'&&r.id===audit.reviewId));
 const binding=await inventory.confirm(authority,{artifactRef:candidate.source.artifactRef,expectedSourceHash:candidate.source.sourceHash,publicationTaskId:candidate.publicationTaskId,expectedTargetPublicationHash:candidate.targetPublicationHash,reason:'复用真实已审成片',rightsStatement:'本账号素材许可仍有效',timelinessStatement:'已核验本周企业事实及CTA'});
 const packages=createWeeklyOperatingPackageService(f.store);
 const next=await packages.revise('t','owner','p','week2',{expectedVersion:1,publicationTasks:target.socialContentPackage.publicationTasks.map(pub=>({...pub,inventoryReuseRef:binding.item.ref}))});
 await packages.activate('t','owner','p','week2',{expectedVersion:next.version,expectedProgramVersion:1});
 const scanned=await runSocialWeeklyExecutionScan({dataStore:f.store,adapters:{business_outline:createSocialWeeklyPlanningAdapter(f.store)},maxTasksPerTenant:1});
 assert.equal(scanned.succeeded,1,JSON.stringify(scanned));
 const targetApproval=f.tables.social_weekly_execution_tasks!.find(row=>row.package_id==='week2'&&row.package_version===next.version&&(row.payload as WeeklyExecutionTask).schedule.stepKind==='user_approval')!.payload as WeeklyExecutionTask;
 await createWeeklyExecutionTaskService(f.store).approve('t','p','week2',targetApproval.taskId,'owner');
 const targetPublishing=f.tables.social_weekly_execution_tasks!.find(row=>row.package_id==='week2'&&row.package_version===next.version&&(row.payload as WeeklyExecutionTask).schedule.stepKind==='publishing')!.payload as WeeklyExecutionTask;
 await inventory.prepareAssignment(targetPublishing);await inventory.prepareAssignment(targetPublishing);
 assert.equal(f.tables.social_publication_assignments?.length,1);assert.equal(f.tables.social_publication_assignments![0]!.production_result_id,f.result.productionResultId);
 assert.equal(f.tables.starter_social_content_tasks!.length,1);assert.equal(f.tables.starter_social_content_artifacts!.length,1);
 assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.social_publication_attempts?.length??0,0);
 assert.equal(f.result.technicalReview.approved,false);assert.equal(f.result.creativeReview.approved,false);
 await assert.rejects(validateContentArtifact(f.store,{...task,tenantId:'foreign'},{...ref,version:2}));
 const outcome=f.tables[SOCIAL_DIRECTOR_G5_REVIEWS]!.find(row=>row.kind==='outcome')!;
 const savedHash=outcome.content_hash;outcome.content_hash='0'.repeat(64);
 await assert.rejects(validateContentArtifact(f.store,task,{...ref,version:2}));
 await assert.rejects(inventory.prepareAssignment(targetPublishing));outcome.content_hash=savedHash;
 await validateContentArtifact(f.store,task,{...ref,version:2});
 f.profile.brand.tone='改变后的实际品牌调性';
 await assert.rejects(validateContentArtifact(f.store,task,{...ref,version:2}));
 await assert.rejects(inventory.prepareAssignment(targetPublishing));
});
