import test from 'node:test';
import assert from 'node:assert/strict';

test('actual owned product route exposes exact prerequisite before original scheduler can create a run',async t=>{
 const keys=['SEEDANCE_VIDEO_ENABLED','SEEDANCE_API_KEY','SEEDREAM_API_KEY'] as const;const old=Object.fromEntries(keys.map(key=>[key,process.env[key]]));t.after(()=>{for(const key of keys){if(old[key]===undefined)delete process.env[key];else process.env[key]=old[key];}});process.env.SEEDANCE_VIDEO_ENABLED='true';process.env.SEEDANCE_API_KEY='controlled-no-real-provider';process.env.SEEDREAM_API_KEY='controlled-no-real-provider';
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');const {assessWeeklyOwnedProductIdentity,bindWeeklyOwnedProductIdentity,resumeWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const {repository,f,pkg,task,created,actual}=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true});
 const scope={tenantId:task.tenantId,programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:task.publicationTaskId!,contentTaskId:String(created.task_id)};
 const result=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});
 assert.equal(result.required,true);assert.equal(result.status,'blocked');assert.deepEqual(result.gaps,['weekly_owned_product_identity_verification_required']);
 assert.ok(result.consumerTaskId);assert.ok(result.requirements.length);for(const requirement of result.requirements){assert.ok(requirement.sceneIds.length);assert.ok(requirement.productRef);assert.ok(requirement.imageHashes.every(hash=>/^[a-f0-9]{64}$/.test(hash)));}
 assert.equal(actual.lastError?.code,'weekly_owned_product_identity_verification_required');assert.ok(!created.run_id);assert.equal(f.tables.workflow_runs?.filter(row=>(row.starter_context as Record<string,unknown>|undefined)?.socialTaskId===scope.contentTaskId).length??0,0);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,{...scope,tenantId:'foreign'},{repository}),{code:'weekly_owned_product_identity_scope_invalid'});
 const row=f.tables.starter_social_content_tasks!.find(row=>row.task_id===scope.contentTaskId);assert.ok(row);const original=row.brief;row.brief={...(original as object),_weeklyOwnedProductIdentityDemand:{schemaVersion:'weekly-owned-product-identity.v1',...scope,version:Number(row.version),consumerTaskId:result.consumerTaskId,requirementHash:result.requirementHash,requirements:result.requirements,bindings:[],boundBy:'owner',boundAt:new Date().toISOString(),recordHash:'0'.repeat(64)}};
 const forged=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(forged.status,'blocked');assert.deepEqual(forged.gaps,['weekly_owned_product_identity_binding_changed']);row.brief=original;
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(item=>result.requirements[0]?.imageIds.includes(item.id));assert.ok(image);assert.ok(typeof image.url==='string');const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));
 const recordId='material0000001',sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`,sha=String(image.contentSha256);let currentBytes=bytes;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?structuredClone(raw):null,materialBytes:{fetch:async()=>new Response(currentBytes,{headers:{'content-type':'image/png','content-length':String(currentBytes.length)}})}};
 const service=createWeeklyMaterialRequestService(f.store,materialPorts),consumerId=result.consumerTaskId;assert.ok(consumerId);const requirement=result.requirements[0];assert.ok(requirement);assert.equal(result.requirements.length,1);
 const consumerRow=f.tables.social_weekly_execution_tasks!.find(row=>row.task_id===consumerId);assert.ok(consumerRow);(consumerRow.payload as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask).scope='content';
 const request=await service.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-09T08:00:00+08:00',verificationDueAt:'2026-10-09T09:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:consumerId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'实际核验产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const bindingInput={actorUserId:'owner',expectedTaskVersion:result.contentTaskVersion,expectedRequirementHash:result.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]};
 await bindWeeklyOwnedProductIdentity(f.store,scope,bindingInput,ports);assert.equal((await assessWeeklyOwnedProductIdentity(f.store,scope,ports)).status,'blocked');
 await service.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});
 await service.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:consumerId,accepted:true,factCheck:'指定产品外观对应真实企业产品',rightsCheck:'指定企业拥有素材并授权目标账号商业使用',visualCheck:'身份包装与该组镜头要求一致'}]});
 const beforeAttach=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.deepEqual(beforeAttach.gaps,['weekly_owned_product_identity_source_not_bound']);assert.equal(beforeAttach.materials[0]?.sourceBound,false);
 const bound=await bindWeeklyOwnedProductIdentity(f.store,scope,{...bindingInput,expectedTaskVersion:beforeAttach.contentTaskVersion},ports);assert.ok(bound.version>beforeAttach.contentTaskVersion,'attaching verified source advances task version while the frozen plan remains valid');const ready=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.equal(ready.status,'ready');assert.equal(ready.materials[0]?.sourceBound,true);
 currentBytes=Buffer.from('changed actual physical bytes');await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports));assert.ok(!row.run_id);assert.equal(f.tables.content_execution_jobs?.length??0,0);currentBytes=bytes;
 const {startSocialContentTask}=await import('../starter198/socialContentTasks.js');const {scheduleSocialContentWork}=await import('../starter198/socialContentScheduler.js');const {readWeeklyReferenceSources,weeklyReferenceResolver}=await import('./socialWeeklyReferenceSource.js');
 const plans=f.tables.social_weekly_agent_planning!.map(row=>row.payload as import('../../shared/contracts/socialProgram.js').WeeklyAgentPlanningState).filter(plan=>plan.status==='dispatched');assert.equal(plans.length,1);const analysis=plans[0]?.directorAnalyses[0];assert.ok(analysis);const authority=(row.brief as Record<string,unknown>)._weeklyAuthority;const references=await readWeeklyReferenceSources(f.store,'t',authority,analysis);
 const originalVersion=ready.contentTaskVersion;const started=await startSocialContentTask({repository,tenantId:'t',userId:'owner',taskId:scope.contentTaskId,expectedVersion:String(originalVersion),idempotencyKey:'owned-reviewed-original-scheduler-start',referenceResolver:weeklyReferenceResolver(references),orchestratorQueue:{enqueue:queue=>scheduleSocialContentWork({repository,queue,now:new Date(),materialEvidencePorts:ports})}});
 assert.ok(started.runId);const run=f.tables.workflow_runs!.find(run=>run.id===started.runId);assert.ok(run);const context=run.starter_context as Record<string,unknown>;const schedulerProof=context.weeklyMaterialPlan as import('../starter198/socialWeeklySchedulerMaterialPlan.js').WeeklySchedulerMaterialPlanProof;assert.ok(schedulerProof);assert.equal(Number(started.version),Number(schedulerProof.originalTaskVersion)+1);assert.equal(schedulerProof.scheduledTaskVersion,started.version);assert.ok(Number(schedulerProof.originalTaskVersion)>=originalVersion);assert.ok(context.weeklyReplicationAuthority);
 const {readWeeklyReplicationAuthority}=await import('../starter198/socialWeeklyReplicationAuthority.js');const actualTask=await repository.get('starter_social_content_tasks','t',row.id);assert.ok(actualTask);assert.ok(await readWeeklyReplicationAuthority(repository,actualTask));
 const running=await assessWeeklyOwnedProductIdentity(f.store,scope,ports);assert.equal(running.status,'ready');assert.equal(running.materials[0]?.sourceBound,true);assert.equal(f.tables.content_execution_jobs?.length??0,0,'formal scheduler proof does not claim producer or paid supplier execution');assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 await assert.rejects(bindWeeklyOwnedProductIdentity(f.store,scope,{...bindingInput,expectedTaskVersion:Number(started.version)},ports),{code:'weekly_owned_product_identity_binding_changed'});
 const {createSocialWeeklyExecutionWorker}=await import('./socialWeeklyExecutionWorker.js');const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js');
 const {createWeeklyExecutionTaskService}=await import('../socialPrograms/executionTasks.js');const executionService=createWeeklyExecutionTaskService(f.store);await executionService.block('t',pkg.programId,pkg.packageId,consumerId,'unrelated_required_input');const stillBlocked=await resumeWeeklyOwnedProductIdentity(f.store,scope,'owner',ports);assert.equal(stillBlocked.status,'blocked');assert.deepEqual(stillBlocked.ownBlockingReasons,['unrelated_required_input']);await executionService.unblock('t',pkg.programId,pkg.packageId,consumerId,'unrelated_required_input');
 const resumed=await resumeWeeklyOwnedProductIdentity(f.store,scope,'owner',ports);assert.equal(resumed.status,'queued');
 const worker=createSocialWeeklyExecutionWorker(f.store,{ownedProductIdentity:ports});const claim=await worker.claimNext({tenantId:'t',workerId:'actual-owned-prerequisite-worker',kinds:['content'],now:new Date()});assert.ok(claim);assert.equal(claim.task.taskId,consumerId);
 const adapted=await createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports}).execute(claim.task);assert.equal(adapted.status,'succeeded',JSON.stringify(adapted));if(adapted.status!=='succeeded')throw Error('real owned prerequisite must succeed');assert.equal(adapted.resultRefs[0]?.type,'starter_social_owned_product_identity_demand');
 const done=await worker.complete(claim,adapted.resultRefs);assert.equal(done.status,'succeeded');assert.ok(done.schedule.actualFinishedAt);assert.equal(done.resultRefs[0]?.type,'starter_social_owned_product_identity_demand');assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 const {validateWeeklyExecutionResults}=await import('./socialWeeklyResultValidation.js');const consumerTask=consumerRow.payload as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask;const manifest=(row.brief as Record<string,unknown>)._weeklyOwnedProductIdentityDemand as import('../../shared/contracts/weeklyOwnedProductIdentity.js').FrozenWeeklyOwnedProductIdentityDemand;const ownedRef={type:'starter_social_owned_product_identity_demand',id:scope.contentTaskId,version:manifest.version};
 await assert.rejects(validateWeeklyExecutionResults(f.store,{...consumerTask,accountId:'foreign'},[ownedRef]),{code:'weekly_owned_product_identity_consumer_invalid'});
 const status=run.status;for(const invalid of ['cancelled','failed','dead_letter']){run.status=invalid;await assert.rejects(validateWeeklyExecutionResults(f.store,consumerTask,[ownedRef]),{code:'weekly_owned_product_identity_original_run_invalid'});await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_run_invalid'});}run.status=status;const tenant=run.tenant_id;run.tenant_id='foreign';await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_run_invalid'});run.tenant_id=tenant;
 const recordedVersion=row.version;row.version=String(Number(recordedVersion)+1);await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_plan_missing'});row.version=recordedVersion;
 const boundSource=f.tables.starter_social_task_sources!.find(source=>source.task_id===scope.contentTaskId&&source.source_ref===sourceRef);assert.ok(boundSource);const sourceVersion=boundSource.source_version;boundSource.source_version='changed-original-material-version';await assert.rejects(assessWeeklyOwnedProductIdentity(f.store,scope,ports),{code:'weekly_owned_product_identity_original_plan_missing'});boundSource.source_version=sourceVersion;

});

test('new real factory keeps preparation before script and preserves post-storyboard material consumer without fabricated predecessor success',async t=>{
 const oldEnabled=process.env.SEEDANCE_VIDEO_ENABLED,oldKey=process.env.SEEDANCE_API_KEY,oldImage=process.env.SEEDREAM_API_KEY;
 t.after(()=>{for(const [key,value] of [['SEEDANCE_VIDEO_ENABLED',oldEnabled],['SEEDANCE_API_KEY',oldKey],['SEEDREAM_API_KEY',oldImage]]){if(value===undefined)delete process.env[key!];else process.env[key!]=value;}});
 process.env.SEEDANCE_VIDEO_ENABLED='true';process.env.SEEDANCE_API_KEY='controlled-no-provider';process.env.SEEDREAM_API_KEY='controlled-no-provider';
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');const {assessWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const {materializeWeeklyExecutionTasks,planWeeklyExecutionTasks}=await import('../socialPrograms/executionTasks.js');
 const {repository,f,pkg,created}=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true,targetCta:'Contact sales',metricTargets:['播放目标1000','点赞目标20','评论目标5','分享目标5']});
 // Discard only this isolated fixture's demonstration execution row. The
 // canonical content/source records remain unchanged; no production proof or
 // predecessor is manufactured to make the real graph executable.
 for(const row of [...(f.tables.social_weekly_execution_tasks??[])])await f.store.delete('social_weekly_execution_tasks',row.id);
 // This earlier production-source fixture intentionally lacks the full week
 // summary. Preserve a visible unresolved readiness blocker for graph-only
 // assessment; this is not a fabricated business approval.
 pkg.planningBlockers=['fixture_weekly_business_readiness_unverified'];
 pkg.executionGraphVersion=2;
 const storedPackage=f.tables.social_weekly_operating_packages.find(row=>row.package_id===pkg.packageId&&row.version===pkg.version);assert.ok(storedPackage);storedPackage.payload=structuredClone(pkg);
 const executionsForFixture=async()=>{const {createWeeklyExecutionTaskService}=await import('../socialPrograms/executionTasks.js');return createWeeklyExecutionTaskService(f.store).list('t',pkg.programId,pkg.packageId,pkg.version);};const {applyBusinessDispatchToExecutionTasks}=await import('../socialPrograms/executionTasks.js');await materializeWeeklyExecutionTasks(f.store,'t',pkg);assert.ok(pkg.agentPlanning?.dispatch);await applyBusinessDispatchToExecutionTasks(f.store,'t',pkg.programId,pkg.packageId,pkg.version,pkg.agentPlanning.dispatch);const tasks=await executionsForFixture(),planned=planWeeklyExecutionTasks('t',pkg,pkg.createdAt);assert.deepEqual(tasks.map(task=>task.taskId).sort(),planned.map(task=>task.taskId).sort());
 const material=tasks.find(task=>task.schedule.stepKind==='material_readiness'&&task.publicationTaskId===pkg.socialContentPackage.publicationTasks[0]?.publicationTaskId);assert.ok(material);
 const storyboard=tasks.find(task=>task.schedule.stepKind==='storyboard'&&task.publicationTaskId===material.publicationTaskId),assets=tasks.find(task=>task.schedule.stepKind==='asset_generation'&&task.publicationTaskId===material.publicationTaskId);assert.ok(storyboard);assert.ok(assets);assert.ok(material.dependsOnTaskIds.includes(storyboard.taskId));assert.deepEqual(assets.dependsOnTaskIds,[material.taskId]);assert.notEqual(storyboard.status,'succeeded');assert.notEqual(material.status,'succeeded');
 const preparation=tasks.find(task=>task.schedule.stepKind==='material_preparation'&&task.publicationTaskId===material.publicationTaskId),script=tasks.find(task=>task.schedule.stepKind==='script'&&task.publicationTaskId===material.publicationTaskId);assert.ok(preparation);assert.ok(script);assert.deepEqual(script.dependsOnTaskIds,[preparation.taskId]);assert.ok(!preparation.dependsOnTaskIds.includes(storyboard.taskId));
 const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js');
 const result=await createSocialWeeklyProductionAdapter(f.store,{repository}).execute(preparation);assert.equal(result.status,'blocked');if(result.status==='blocked')assert.equal(result.code,'weekly_owned_product_identity_verification_required');
 const scope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:material.publicationTaskId!,contentTaskId:String(created.task_id)};const actual=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(actual.consumerTaskId,material.taskId);assert.equal(actual.status,'blocked');assert.ok(actual.requirements.length);
 const {createWeeklyExecutionTaskService}=await import('../socialPrograms/executionTasks.js');const executions=createWeeklyExecutionTaskService(f.store);await executions.block('t',pkg.programId,pkg.packageId,preparation.taskId,'weekly_owned_product_identity_verification_required');
 const {recheckWeeklyMaterialPreparation}=await import('./weeklyMaterialPreparationRecovery.js');const recoveryScope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,taskId:preparation.taskId,actorUserId:'owner'};await assert.rejects(recheckWeeklyMaterialPreparation(f.store,recoveryScope,{repository}));
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {bindWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(i=>actual.requirements[0]?.imageIds.includes(i.id));assert.ok(image);assert.ok(image.url);const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));const recordId='material0000002',sha=String(image.contentSha256),sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};let physical=bytes;
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?raw:null,materialBytes:{fetch:async()=>new Response(physical,{headers:{'content-type':'image/png','content-length':String(physical.length)}})}};
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'真实产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const service=createWeeklyMaterialRequestService(f.store,materialPorts),requirement=actual.requirements[0];assert.ok(requirement);assert.equal(actual.requirements.length,1);
 const request=await service.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:'2026-10-09T08:00:00+08:00',verificationDueAt:'2026-10-09T09:00:00+08:00',timeZone:'Asia/Shanghai',consumers:[{taskId:material.taskId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 await service.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});await service.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:material.taskId,accepted:true,factCheck:'实物产品身份一致',rightsCheck:'企业授权此商业用途',visualCheck:'实物包装符合目标镜头要求'}]});
 await bindWeeklyOwnedProductIdentity(f.store,scope,{actorUserId:'owner',expectedTaskVersion:actual.contentTaskVersion,expectedRequirementHash:actual.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]},ports);
 const adapter=createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports});const prepared=await adapter.execute(preparation);assert.equal(prepared.status,'succeeded');if(prepared.status!=='succeeded')return;assert.equal(prepared.resultRefs[0]?.type,'starter_social_material_preparation');
 const {validateWeeklyExecutionResults}=await import('./socialWeeklyResultValidation.js');await validateWeeklyExecutionResults(f.store,preparation,prepared.resultRefs,new Date(),{ownedProductIdentity:ports});
 const contentRow=f.tables.starter_social_content_tasks.find(r=>r.task_id===scope.contentTaskId);assert.ok(contentRow);const originalBrief=structuredClone(contentRow.brief);let concurrentEdit=false;
 const concurrentPorts={...ports,materialPorts:{...materialPorts,getMaterial:async(tenant:string,id:string)=>{const value=await materialPorts.getMaterial(tenant,id);if(!concurrentEdit){concurrentEdit=true;contentRow.brief={...(contentRow.brief as Record<string,unknown>),_concurrentEvidenceTest:'actual edit persisted during material validation'};}return value;}}};
 await assert.rejects(recheckWeeklyMaterialPreparation(f.store,recoveryScope,concurrentPorts),{code:'weekly_material_preparation_evidence_changed'});contentRow.brief=originalBrief;assert.ok((await executions.list('t',pkg.programId,pkg.packageId,pkg.version)).find(t=>t.taskId===preparation.taskId)?.ownBlockingReasons.includes('weekly_owned_product_identity_verification_required'));
 const originalPayload=storedPackage.payload;storedPackage.payload=null;await assert.rejects(validateWeeklyExecutionResults(f.store,preparation,prepared.resultRefs,new Date(),{ownedProductIdentity:ports}),{code:'weekly_material_preparation_scope_invalid'});storedPackage.payload=originalPayload;
 const express=(await import('express')).default;const {createWeeklyOwnedProductIdentityRouter}=await import('../starter198/weeklyOwnedProductIdentityRouter.js');const {createWeeklyOwnedProductIdentityUI}=await import('../starter198/weeklyOwnedProductIdentityUI.js');const app=express();app.use(express.json());app.use((_req,res,next)=>{res.locals.tenantId='t';res.locals.userId='owner';next();});app.use('/tasks/:taskId/identity',createWeeklyOwnedProductIdentityRouter(createWeeklyOwnedProductIdentityUI(f.store,ports),async()=>({tenantId:'t',userId:'owner'})));const server=app.listen(0);t.after(()=>server.close());const address=server.address();assert.ok(address&&typeof address!=='string');const base=`http://127.0.0.1:${address.port}/tasks/${scope.contentTaskId}/identity`;
 const query=new URLSearchParams({programId:scope.programId,packageId:scope.packageId,packageVersion:String(scope.packageVersion),publicationTaskId:scope.publicationTaskId,expectedRunId:''});const readResponse=await fetch(`${base}?${query}`);assert.equal(readResponse.status,200);const packet=(await readResponse.json()).item;assert.equal(packet.assessment.preparationTaskId,preparation.taskId);assert.equal(packet.assessment.preparationTask.status,'blocked');assert.equal(packet.assessment.consumerTaskId,material.taskId);
 const body={programId:scope.programId,packageId:scope.packageId,packageVersion:scope.packageVersion,publicationTaskId:scope.publicationTaskId,expectedRunId:null,preparationTaskId:preparation.taskId};const postPreparation=(value:unknown)=>fetch(`${base}/recheck-preparation`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});assert.equal((await postPreparation({...body,preparationTaskId:material.taskId})).status,409);assert.equal((await postPreparation({...body,tenantId:'foreign'})).status,400);const resumeResponse=await postPreparation(body);assert.equal(resumeResponse.status,200);const recovered=(await resumeResponse.json()).item as import('../../shared/contracts/socialProgram.js').WeeklyExecutionTask;
assert.ok(!recovered.ownBlockingReasons.includes('weekly_owned_product_identity_verification_required'));assert.notEqual(recovered.status,'succeeded');assert.ok(recovered.inheritedBlockingTaskIds.length>0);assert.ok(recovered.dependsOnTaskIds.length);
 await assert.rejects(recheckWeeklyMaterialPreparation(f.store,{...recoveryScope,actorUserId:'foreign'},ports));
 physical=Buffer.from('changed bytes');await assert.rejects(validateWeeklyExecutionResults(f.store,preparation,prepared.resultRefs,new Date(),{ownedProductIdentity:ports}));physical=bytes;
 // Read the actual immutable planning output through the registered planning
 // adapter and result validator before clearing the fixture's explicit unknown
 // readiness marker. No predecessor status or result ref is manufactured.
 const {createSocialWeeklyPlanningAdapter,WEEKLY_PREPRODUCTION_STEPS}=await import('./socialWeeklyExecutionRuntime.js');const planningAdapter=createSocialWeeklyPlanningAdapter(f.store);const outline=tasks.find(t=>t.schedule.stepKind==='business_outline');assert.ok(outline);const outlineProof=await planningAdapter.execute(outline);assert.equal(outlineProof.status,'succeeded');if(outlineProof.status!=='succeeded')return;await validateWeeklyExecutionResults(f.store,outline,outlineProof.resultRefs);
 await executions.unblock('t',pkg.programId,pkg.packageId,outline.taskId,'fixture_weekly_business_readiness_unverified');
 const {createSocialWeeklyExecutionWorker}=await import('./socialWeeklyExecutionWorker.js');const worker=createSocialWeeklyExecutionWorker(f.store,{ownedProductIdentity:ports});const completedPlanning:string[]=[];let preparationCompleted=false;const due=new Date(Math.max(Date.now(),Date.parse(script.schedule.estimatedStartAt))+1);
 for(let attempt=0;attempt<8;attempt++){
  const claim=await worker.claimNext({tenantId:'t',workerId:'actual-factory-preparation-worker',now:due});assert.ok(claim,JSON.stringify({completedPlanning,tasks:(await executions.list('t',pkg.programId,pkg.packageId,pkg.version)).map(t=>({step:t.schedule.stepKind,status:t.status,own:t.ownBlockingReasons,inherited:t.inheritedBlockingTaskIds,start:t.schedule.estimatedStartAt}))}));
  if(claim.task.taskId===preparation.taskId){const output=await adapter.execute(claim.task);assert.equal(output.status,'succeeded');if(output.status!=='succeeded')break;const complete=await worker.complete(claim,output.resultRefs,due);assert.equal(complete.status,'succeeded');preparationCompleted=true;break;}
  assert.ok(WEEKLY_PREPRODUCTION_STEPS.includes(claim.task.schedule.stepKind),'only truthful frozen planning predecessors may be reconciled');const output=await planningAdapter.execute(claim.task);assert.equal(output.status,'succeeded');if(output.status!=='succeeded')break;const complete=await worker.complete(claim,output.resultRefs,due);assert.equal(complete.status,'succeeded');completedPlanning.push(claim.task.schedule.stepKind);
 }
 assert.equal(preparationCompleted,true);assert.ok(completedPlanning.includes('business_schedule'));const scriptClaim=await worker.claimNext({tenantId:'t',workerId:'actual-factory-preparation-worker',now:due});assert.equal(scriptClaim?.task.taskId,script.taskId);assert.deepEqual(scriptClaim?.task.dependsOnTaskIds,[preparation.taskId]);assert.equal(scriptClaim?.task.inheritedBlockingTaskIds.length,0);if(scriptClaim)await worker.defer(scriptClaim,{code:'controlled_stop_before_paid_script',message:'明确在脚本付费调用之前停止',blockingReason:'controlled_stop_before_paid_script',now:due});
 // These are actual factory consumers. The adapter has only read the preparation
 // evidence; it has not forged the unmet business/script/storyboard predecessors.
 assert.notEqual(material.status,'succeeded');assert.notEqual(script.status,'succeeded');assert.ok(!created.run_id);assert.equal(f.tables.content_execution_jobs?.length??0,0);assert.equal(f.tables.starter_usage_ledger?.length??0,0);
 // Execute the same claimed script through the real scheduler, then the real
 // durable producer only as far as its pre-supply pause (no vendor call).
 await executions.unblock('t',pkg.programId,pkg.packageId,script.taskId,'controlled_stop_before_paid_script');
 const originalScript=await worker.claimNext({tenantId:'t',workerId:'actual-phase-script-worker',now:due});assert.equal(originalScript?.task.taskId,script.taskId);assert.ok(originalScript);
 const {scheduleSocialContentWork}=await import('../starter198/socialContentScheduler.js');
 const phaseAdapter=createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports,orchestratorQueue:{enqueue:queue=>scheduleSocialContentWork({repository,queue,now:new Date(),materialEvidencePorts:ports,productionRunner:async()=>{}})}});
 const starting=await phaseAdapter.execute(originalScript.task);assert.equal(starting.status,'pending',JSON.stringify(starting));
 const current=await repository.get('starter_social_content_tasks','t',contentRow.id);assert.ok(current?.run_id);
 const {admitContentExecutionJob,DurableContentExecutionWorker,readContentExecutionJob}=await import('../contentExecution/durableQueue.js');
 const actualJob=await admitContentExecutionJob({dataStore:f.store,tenantId:'t',userId:'owner',taskId:scope.contentTaskId,runId:String(current.run_id),accountId:script.accountId,taskType:'social_content_weekly'});
 let suppliers=0,successes=0,failures=0;
 const {runSocialContentAutoProduction}=await import('../starter198/socialContentProductionExecution.js');
 const productionWorker=new DurableContentExecutionWorker({dataStore:f.store,execute:job=>runSocialContentAutoProduction({repository,tenantId:job.tenantId,userId:job.userId,taskId:job.taskId,runId:job.runId,materialEvidencePorts:ports,runtime:{synthesizeVoice:async()=>{suppliers++;throw Error('forbidden paid voice');},renderComposite:async()=>{suppliers++;throw Error('forbidden render');}}}),onSucceeded:async()=>{successes++;},onRetry:async(_job,error)=>{console.error(error instanceof Error?error.stack:error);const ctx=f.tables.workflow_runs!.find(row=>row.id===current.run_id)?.starter_context as Record<string,any>;console.error('handoff-refs',JSON.stringify({job:ctx?.weeklyReplicationAuthority?.job?.version,ref:ctx?.weeklyPreSupplyHandoff?.directorBrief?.replicationJobRef,account:ctx?.weeklyPreSupplyHandoff?.directorBrief?.accountPlaybookRef,proofAccount:ctx?.weeklyReplicationAuthority?.context?.accountPlaybookRef,plan:ctx?.weeklyPreSupplyHandoff?.executionPlan?.directorBriefVersion,brief:ctx?.weeklyPreSupplyHandoff?.directorBrief?.version,review:ctx?.weeklyPreSupplyHandoff?.directorReview?.directorBriefVersion}));},onBlocked:async(_job,error)=>{failures++;console.error(error instanceof Error?error.stack:error);},env:{CONTENT_EXECUTION_TENANT_CONCURRENCY:'1'}});
 await productionWorker.drain();for(let attempt=0;attempt<300&&productionWorker.isLocallyActive('t',scope.contentTaskId);attempt++)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(productionWorker.isLocallyActive('t',scope.contentTaskId),false,'actual durable worker must settle its pause');const paused=await readContentExecutionJob(f.store,'t',scope.contentTaskId,String(current.run_id));assert.equal(paused?.status,'paused',JSON.stringify(paused));assert.equal(paused?.id,actualJob.id);assert.equal(suppliers,0);assert.equal(successes,0);assert.equal(failures,0);const {readSocialTaskDetail}=await import('../starter198/socialContentRecords.js');const pausedDetail=await readSocialTaskDetail({repository,tenantId:'t',taskId:scope.contentTaskId});assert.equal(pausedDetail?.productionProgress?.waitingForScheduledAssets,true);assert.equal(pausedDetail?.productionProgress?.estimatedRemainingSeconds,null);assert.ok(pausedDetail);const {contentProgressNodes}=await import('../../src/lib/contentProductionExperience.js');const nodes=contentProgressNodes(pausedDetail);assert.equal(nodes.find(n=>n.id==='script')?.state,'complete');assert.equal(nodes.find(n=>n.id==='shots')?.state,'blocked');assert.equal(nodes.find(n=>n.id==='shots')?.label,'等待素材与资产排期');for(const id of ['edit','quality','acceptance'])assert.equal(nodes.find(n=>n.id===id)?.state,'pending');assert.ok(!nodes.some(n=>n.state==='active'));
 const {readWeeklyPreSupplyHandoff}=await import('../starter198/socialWeeklyPreSupplyHandoff.js');const handoff=await readWeeklyPreSupplyHandoff(repository,'t',scope.contentTaskId);assert.ok(handoff);assert.equal(handoff.assetAvailability,'planned_not_generated');
 const scriptOutput=await phaseAdapter.execute(originalScript.task);assert.equal(scriptOutput.status,'succeeded',JSON.stringify(scriptOutput));if(scriptOutput.status!=='succeeded')throw Error('locked original script not available');await worker.complete(originalScript,scriptOutput.resultRefs,due);
 const storyboardNow=new Date(Math.max(due.getTime(),Date.parse(storyboard.schedule.estimatedStartAt!)));const storyboardClaim=await worker.claimNext({tenantId:'t',workerId:'actual-phase-storyboard-worker',now:storyboardNow});assert.equal(storyboardClaim?.task.schedule.stepKind,'storyboard');assert.ok(storyboardClaim);const storyboardOutput=await phaseAdapter.execute(storyboardClaim.task);assert.equal(storyboardOutput.status,'succeeded',JSON.stringify(storyboardOutput));if(storyboardOutput.status!=='succeeded')throw Error('locked pre-supply storyboard not available');assert.equal(storyboardOutput.resultRefs[0]?.type,'starter_weekly_pre_supply_handoff');await worker.complete(storyboardClaim,storyboardOutput.resultRefs,storyboardNow);
 const materialNow=new Date(Math.max(storyboardNow.getTime(),Date.parse(material.schedule.estimatedStartAt!)));const materialClaim=await worker.claimNext({tenantId:'t',workerId:'actual-phase-material-worker',now:materialNow});assert.equal(materialClaim?.task.schedule.stepKind,'material_readiness',JSON.stringify((await executions.list('t',pkg.programId,pkg.packageId,pkg.version)).map(task=>({kind:task.schedule.stepKind,state:task.status,own:task.ownBlockingReasons,inherited:task.inheritedBlockingTaskIds,start:task.schedule.estimatedStartAt,next:task.nextAttemptAt}))));assert.ok(materialClaim);const materialOutput=await phaseAdapter.execute(materialClaim.task);assert.equal(materialOutput.status,'succeeded',JSON.stringify(materialOutput));if(materialOutput.status!=='succeeded')throw Error('fresh original material not available');await worker.complete(materialClaim,materialOutput.resultRefs,materialNow);
 const assetNow=new Date(Math.max(materialNow.getTime(),Date.parse(assets.schedule.estimatedStartAt!)));const assetClaim=await worker.claimNext({tenantId:'t',workerId:'actual-phase-assets-worker',now:assetNow});assert.equal(assetClaim?.task.schedule.stepKind,'asset_generation');assert.ok(assetClaim);
 // Resume uses the actual leased asset task and original settled job; never a new run or supplier submit.
 const {resumeWeeklyProductionAssetStage,assertWeeklyProductionAssetAuthorization}=await import('../starter198/socialWeeklyProductionStageResume.js');
 const resume=()=>resumeWeeklyProductionAssetStage({repository,assetTask:assetClaim.task,now:assetNow,validationPorts:{ownedProductIdentity:ports}});
 const jobRow=f.tables.content_execution_jobs!.find(row=>row.id===actualJob.id);assert.ok(jobRow);
 const originalJob=structuredClone(jobRow);
 assert.ok(assetClaim.task.lease);await assert.rejects(resumeWeeklyProductionAssetStage({repository,assetTask:{...assetClaim.task,lease:{...assetClaim.task.lease,token:'wrong-claim-token'}},now:assetNow,validationPorts:{ownedProductIdentity:ports}}),{code:'weekly_stage_asset_claim_invalid'});
 jobRow.worker_id='still-settling-original-worker';await assert.rejects(resume(),{code:'weekly_stage_original_worker_not_settled'});jobRow.worker_id=originalJob.worker_id;
 jobRow.provider_receipts=[{provider:'controlled-provider',requestId:'original-unknown',state:'unknown',providerTaskId:'original-provider-task',metadata:{},firstRecordedAt:assetNow.toISOString(),updatedAt:assetNow.toISOString()}];await assert.rejects(resume(),{code:'weekly_stage_provider_reconciliation_required'});jobRow.provider_receipts=originalJob.provider_receipts;
 jobRow.provider_receipts=[{provider:'controlled-provider',state:'unknown'}];await assert.rejects(resume(),{code:'weekly_stage_provider_receipt_integrity_required'});jobRow.provider_receipts=originalJob.provider_receipts;
 const originalStage=structuredClone((jobRow.checkpoint as Record<string,unknown>).weeklyStage);(jobRow.checkpoint as Record<string,unknown>).weeklyStage={...(originalStage as object),stage:'assets_authorized'};await assert.rejects(assertWeeklyProductionAssetAuthorization(repository,handoff,assetNow,{ownedProductIdentity:ports}),{code:'weekly_stage_authorization_missing'});(jobRow.checkpoint as Record<string,unknown>).weeklyStage=originalStage;
 t.mock.timers.enable({apis:['Date'],now:assetNow.getTime()});
 try{const resumedOutput=await phaseAdapter.execute(assetClaim.task);assert.equal(resumedOutput.status,'pending',JSON.stringify(resumedOutput));const {pauseWeeklyPreSupplyStage}=await import('../starter198/socialWeeklyPreSupplyHandoff.js');assert.equal(await pauseWeeklyPreSupplyStage(repository,handoff,{ownedProductIdentity:ports}),false,'actual producer boundary requires fresh authorization and materials');}finally{t.mock.timers.reset();}
 const resumed=await readContentExecutionJob(f.store,'t',scope.contentTaskId,String(current.run_id));assert.ok(resumed);assert.equal(resumed.id,actualJob.id);assert.equal(resumed.runId,current.run_id);assert.equal(resumed.status,'queued');assert.equal(resumed.providerReceipts.length,0);
 await assertWeeklyProductionAssetAuthorization(repository,handoff,assetNow,{ownedProductIdentity:ports});
 await assert.rejects(resume(),{code:'weekly_stage_checkpoint_invalid'});
 physical=Buffer.from('material drift after original asset authorization');await assert.rejects(assertWeeklyProductionAssetAuthorization(repository,handoff,assetNow,{ownedProductIdentity:ports}));physical=bytes;
 const savedJob=await f.store.getById<import('../storage/datastore.js').Record_>('content_execution_jobs',actualJob.id);assert.ok(savedJob);const checkpoint=savedJob.checkpoint as Record<string,unknown>,stage=checkpoint.weeklyStage as Record<string,unknown>,proof=stage.authorization as Record<string,unknown>;
 const originalHash=proof.assetInputHash;proof.assetInputHash='0'.repeat(64);await assert.rejects(assertWeeklyProductionAssetAuthorization(repository,handoff,assetNow,{ownedProductIdentity:ports}),{code:'weekly_stage_authorization_invalid'});proof.assetInputHash=originalHash;
 const activePayload=storedPackage.payload as import('../../shared/contracts/socialProgram.js').WeeklyOperatingPackage;activePayload.status='retired';await assert.rejects(assertWeeklyProductionAssetAuthorization(repository,handoff,assetNow,{ownedProductIdentity:ports}));activePayload.status='active';
 // The original authorized job can reconcile an existing unknown receipt.
 // The read-only adapter and actual provider gateway use its same durable IDs.
 const {runWithContentExecutionContext,recordCurrentContentProviderReceipt}=await import('../contentExecution/context.js');
 await runWithContentExecutionContext({dataStore:f.store,jobId:actualJob.id,action:()=>recordCurrentContentProviderReceipt({provider:'seedance',requestId:'original-stage-request',state:'unknown',providerTaskId:'actual-original-provider-task',metadata:{reservationId:'actual-original-reservation',reservedCny:2,model:'controlled-seedance'}})});
 const {controlContentExecutionJob}=await import('../contentExecution/durableQueue.js');await controlContentExecutionJob({dataStore:f.store,tenantId:'t',jobId:actualJob.id,action:'pause',now:assetNow});const reconciling=await controlContentExecutionJob({dataStore:f.store,tenantId:'t',jobId:actualJob.id,action:'resume',now:assetNow});assert.equal(reconciling.id,actualJob.id);assert.equal(reconciling.runId,current.run_id);assert.equal(reconciling.status,'reconciling');
 t.mock.timers.enable({apis:['Date'],now:assetNow.getTime()});try{const observed=await phaseAdapter.execute(assetClaim.task);assert.equal(observed.status,'pending');if(observed.status==='pending')assert.equal(observed.code,'provider_reconciliation');const {pauseWeeklyPreSupplyStage}=await import('../starter198/socialWeeklyPreSupplyHandoff.js');assert.equal(await pauseWeeklyPreSupplyStage(repository,handoff,{ownedProductIdentity:ports}),false);}finally{t.mock.timers.reset();}
 const {generateSeedanceConceptVideo}=await import('../lib/generativeVideoGateway.js');let providerPosts=0,providerGets=0;
 const recoveredOutput=await runWithContentExecutionContext({dataStore:f.store,jobId:actualJob.id,providerReceipts:reconciling.providerReceipts,action:()=>generateSeedanceConceptVideo({tenantId:'t',prompt:'original controlled request',durationSeconds:5,ratio:'9:16',idempotencyKey:'original-stage-request',timeoutMs:1000,apiKey:'controlled-never-external',model:'controlled-seedance',pollMs:1,reserveBudget:()=>{throw Error('no second reserve');},releaseBudget:()=>{throw Error('no release of original reservation');},transport:async(url,init)=>{if(init?.method==='POST'){providerPosts++;throw Error('no new provider submission');}providerGets++;if(String(url).endsWith('/actual-original-provider-task'))return Response.json({status:'succeeded',content:{video_url:'https://controlled.invalid/original.mp4'}});if(String(url)==='https://controlled.invalid/original.mp4')return new Response(Buffer.from('controlled original supplier result'));throw Error('unexpected controlled request');}})});
 assert.equal(recoveredOutput.providerTaskId,'actual-original-provider-task');assert.equal(providerPosts,0);assert.equal(providerGets,2);const actualRecovered=await readContentExecutionJob(f.store,'t',scope.contentTaskId,String(current.run_id));assert.equal(actualRecovered?.providerReceipts[0]?.state,'completed');assert.equal(actualRecovered?.id,actualJob.id);
 assert.equal(f.tables.content_execution_jobs!.length,1);assert.equal(suppliers,0);assert.equal(successes,0);assert.equal(failures,0);


});
