import test from 'node:test';
import assert from 'node:assert/strict';
import {prepareWeeklyNonPresenterPlanningFixture} from './weeklyNonPresenterProduction.fixture.js';
import {createWeeklyOperatingPackageService} from '../socialPrograms/weeklyOperatingPackages.js';
import {createSocialOperatingDecisionService} from '../socialOperating/service.js';
import {planCapacity} from '../socialOperating/capacityPlanner.js';
import {resolveAutomationPolicy} from '../socialOperating/automationPolicyResolver.js';
import {setContentExecutionLimit} from '../contentExecution/durableQueue.js';
import {materializeWeeklyExecutionTasks,listWeeklyExecutionTasks,applyBusinessDispatchToExecutionTasks} from '../socialPrograms/executionTasks.js';
import {createWeeklyPlanningAuthority} from '../socialPrograms/planningAuthority.js';
import {createWeeklyExecutionTaskService} from '../socialPrograms/executionTasks.js';
import {INITIAL_CAPACITY_SCHEDULE_REQUIRED} from '../socialPrograms/weeklyInitialScheduleGate.js';
import {createWeeklyInitialScheduleService} from '../socialPrograms/weeklyInitialSchedule.js';
import {scheduleHash,applyFrozenWeeklySchedule} from '../socialPrograms/weeklyScheduleSnapshots.js';
import {WEEKLY_EXECUTION_FREEZES} from '../socialPrograms/weeklyExecutionGate.js';
import type {Record_} from '../storage/datastore.js';

test('M1 controlled single external video uses actual initial capacity confirmation before production',async t=>{
 const {prepareWeeklyNonPresenterProductionFixture}=await import('./weeklyNonPresenterProduction.fixture.js');
 const setup=await prepareWeeklyNonPresenterProductionFixture(t,{ownedReferenceBytes:true,productInventory:true,primaryStructure:true,targetCta:'Contact sales',metricTargets:['播放目标1000','点赞目标20','评论目标5','分享目标5']}),{f}=setup;
 const clock='2026-10-10T01:00:00Z',decisions=createSocialOperatingDecisionService(f.store,()=>clock);
 const goalRef=setup.pkg.businessContentGoalRef!;
 const goal=await decisions.getGoal('t','p',goalRef.id,goalRef.version);
 const options={operator:{type:'user' as const,id:'owner'},decidedAt:clock};
 const capacity=planCapacity({goal,desiredOriginalContents:1,desiredAdaptations:0,costPerOriginalCny:1,costPerAdaptationCny:1,readyMaterialUnits:1,materialUnitsPerOriginal:1,productionItemsPerDay:1,daysUntilDeadline:7,accounts:[{ref:{type:'owned_social_account',id:'account',version:2},accountId:'account',status:'active',weeklyPublicationCapacity:1}],interactionItemsPerWeek:10,salesLeadsPerWeek:10,expectedInteractionsPerPublication:1,expectedLeadsPerPublication:1,capabilities:{'studio.production':'available','publishing.calendar':'available','customer.attribution':'available'}},options);
 assert.equal(capacity.plan.status,'ready');await decisions.saveOperatingDecision('t','p',capacity.decision);
 const policy=resolveAutomationPolicy({goal,mode:'managed',action:'draft',capability:{key:'studio.production',availability:'available'},factsVerified:true,withinBudget:true,rightsSufficient:true},options);
 assert.equal(policy.policy.status,'allowed');await decisions.saveOperatingDecision('t','p',policy.decision);
 const packages=createWeeklyOperatingPackageService(f.store);
 const source=await packages.create('t','owner','p',{weekStart:'2026-10-12',objective:goal.objective,perItemBudgetCny:1,successCriteria:['实际发布一条视频'],enterpriseProfileRef:{type:'enterprise_profile',id:'profile',version:1},businessContentGoalRef:goalRef,capacityPlanRef:{type:'capacity_plan',id:capacity.decision.decisionId,version:1},automationPolicyRef:{type:'automation_policy',id:policy.decision.decisionId,version:1},referenceSourcePolicy:setup.pkg.referenceSourcePolicy,publicationTasks:setup.pkg.socialContentPackage.publicationTasks.map(pub=>({...structuredClone(pub),publishWindow:'2026-10-15T10:00:00Z'}))});
 const planning=createWeeklyPlanningAuthority(f.store),initial=await planning.initialize('t',source);
 const director=await planning.runDirectorAnalysis({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:initial.version,actor:'director_agent'});
 const detailed=await planning.mergeDetailedSchedule({tenantId:'t',programId:'p',package:source,expectedPlanningVersion:director.version,actor:'business_agent'});
 const confirmed=await planning.confirm({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:detailed.version,userId:'owner'});
 const dispatched=await planning.dispatch({tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,expectedPlanningVersion:confirmed.version,actor:'business_agent'});
 assert(dispatched.dispatch);await applyBusinessDispatchToExecutionTasks(f.store,'t','p',source.packageId,source.version,dispatched.dispatch,clock);

 for(const [scope,scopeKey]of [['tenant','*'],['account','account'],['task_type','social_content_weekly']] as const)await setContentExecutionLimit({dataStore:f.store,tenantId:'t',scope,scopeKey,maxRunning:2,updatedBy:'owner',now:new Date(clock)});
 const authority={tenantId:'t',programId:'p',packageId:source.packageId,packageVersion:source.version,actorUserId:'owner'},service=createWeeklyInitialScheduleService(f.store,{now:()=>clock}),preview=await service.preview(authority),graph=preview.graph;
 const userCapacity={constraints:Object.fromEntries(graph.tasks.map(task=>[task.taskId,{resourceKey:'production',remainingMinutes:task.schedule.estimatedDurationMinutes,remainingCostCny:1,bufferMinutes:0,availableAt:clock}])),resources:{production:{concurrency:2,workingWindows:[{startAt:clock,finishAt:'2026-10-26T20:00:00Z'}]}},remainingBudgetCny:100,operationalDeadlines:Object.fromEntries(graph.tasks.filter(task=>['performance_monitoring','weekly_review','template_extraction','template_performance_validation'].includes(task.schedule.stepKind)).map(task=>[task.taskId,'2026-10-26T18:00:00Z']))};
 const proposal=await service.propose(authority,userCapacity);assert.equal(proposal.plan.publicationGap,0,JSON.stringify(proposal.plan.assignments));
 const result=await service.confirm(authority,{proposalId:proposal.proposalId,expectedVersion:source.version,inputEvidenceHash:proposal.inputEvidenceHash});
 assert.equal(result.activated,false);assert.equal(result.item.version,2);
 const pkg=result.item;
 const newInitial=await planning.initialize('t',pkg);const newAnalysis=await planning.runDirectorAnalysis({tenantId:'t',programId:'p',packageId:pkg.packageId,packageVersion:pkg.version,expectedPlanningVersion:newInitial.version,actor:'director_agent'});
 const newDetail=await planning.mergeDetailedSchedule({tenantId:'t',programId:'p',package:pkg,expectedPlanningVersion:newAnalysis.version,actor:'business_agent'});
 const newConfirmed=await planning.confirm({tenantId:'t',programId:'p',packageId:pkg.packageId,packageVersion:pkg.version,expectedPlanningVersion:newDetail.version,userId:'owner'});
 const newDispatch=await planning.dispatch({tenantId:'t',programId:'p',packageId:pkg.packageId,packageVersion:pkg.version,expectedPlanningVersion:newConfirmed.version,actor:'business_agent'});
 assert.ok(newDispatch.dispatch);await applyBusinessDispatchToExecutionTasks(f.store,'t','p',pkg.packageId,pkg.version,newDispatch.dispatch,clock);
 const activated=await packages.activate('t','owner','p',pkg.packageId,{expectedVersion:pkg.version,expectedProgramVersion:1,authorizePublishing:true});assert.equal(activated.status,'active');
 const repository=setup.repository,executions=createWeeklyExecutionTaskService(f.store);
 const tasks=await listWeeklyExecutionTasks(f.store,'t','p',pkg.packageId,pkg.version);
 const preparation=tasks.find(task=>task.schedule.stepKind==='material_preparation')!,script=tasks.find(task=>task.schedule.stepKind==='script')!,storyboard=tasks.find(task=>task.schedule.stepKind==='storyboard')!,material=tasks.find(task=>task.schedule.stepKind==='material_readiness')!,assets=tasks.find(task=>task.schedule.stepKind==='asset_generation')!;
 const due=new Date(Math.max(Date.now(),Date.parse(preparation.schedule.estimatedStartAt))+1);
 const {createSocialWeeklyExecutionWorker}=await import('./socialWeeklyExecutionWorker.js');const worker=createSocialWeeklyExecutionWorker(f.store);
 const {createSocialWeeklyPlanningAdapter,WEEKLY_PREPRODUCTION_STEPS}=await import('./socialWeeklyExecutionRuntime.js');const planningAdapter=createSocialWeeklyPlanningAdapter(f.store);let preparationClaim:NonNullable<Awaited<ReturnType<typeof worker.claimNext>>>|null=null;
 for(let attempt=0;attempt<8;attempt++){const claim=await worker.claimNext({tenantId:'t',workerId:'m1-real-factory-worker',now:due});assert.ok(claim);if(claim.task.taskId===preparation.taskId){preparationClaim=claim;break;}assert.ok(WEEKLY_PREPRODUCTION_STEPS.includes(claim.task.schedule.stepKind));const output=await planningAdapter.execute(claim.task);assert.equal(output.status,'succeeded',JSON.stringify(output));if(output.status!=='succeeded')throw Error('actual planning output missing');await worker.complete(claim,output.resultRefs,due);}
 assert.ok(preparationClaim);const {createSocialWeeklyProductionAdapter}=await import('./socialWeeklyProductionAdapter.js');const exposed=await createSocialWeeklyProductionAdapter(f.store,{repository}).execute(preparationClaim.task);assert.equal(exposed.status,'blocked');if(exposed.status==='blocked')assert.equal(exposed.code,'weekly_owned_product_identity_verification_required');
 const created=f.tables.starter_social_content_tasks.find(row=>row.create_idempotency_key===`weekly-production:${pkg.packageId}:${pkg.version}:${material.publicationTaskId}`);assert.ok(created);
 const {assessWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');
 const scope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,publicationTaskId:material.publicationTaskId!,contentTaskId:String(created.task_id)};const actual=await assessWeeklyOwnedProductIdentity(f.store,scope,{repository});assert.equal(actual.consumerTaskId,material.taskId);assert.equal(actual.status,'blocked');assert.ok(actual.requirements.length);
 await worker.defer(preparationClaim,{code:'weekly_owned_product_identity_verification_required',message:'需真实产品素材审核',blockingReason:'weekly_owned_product_identity_verification_required',now:due});
 const {recheckWeeklyMaterialPreparation}=await import('./weeklyMaterialPreparationRecovery.js');const recoveryScope={tenantId:'t',programId:pkg.programId,packageId:pkg.packageId,packageVersion:pkg.version,taskId:preparation.taskId,actorUserId:'owner'};await assert.rejects(recheckWeeklyMaterialPreparation(f.store,recoveryScope,{repository}));
 const {createWeeklyMaterialRequestService}=await import('../socialPrograms/weeklyMaterialRequests.js');const {bindWeeklyOwnedProductIdentity}=await import('./weeklyOwnedProductIdentityDemand.js');const {readFile}=await import('node:fs/promises');const path=await import('node:path');
 const inventory=await repository.materialLibrary!('t'),image=inventory.items.find(i=>actual.requirements[0]?.imageIds.includes(i.id));assert.ok(image);assert.ok(image.url);const bytes=await readFile(path.resolve('data',image.url.replace(/^\//,'')));const recordId='material0000002',sha=String(image.contentSha256),sourceRef=`socialmaterial:${Buffer.from(`pb-${recordId}`).toString('base64url')}`;
 const raw={id:recordId,tenantId:'t',scope:'own',type:'image',sha256:sha,sizeBytes:bytes.length,videoFile:'identity.png',sourceType:'licensed_upload'};let physical=bytes;
 const materialPorts={getMaterial:async(tenant:string,id:string)=>tenant==='t'&&id===recordId?raw:null,materialBytes:{fetch:async()=>new Response(physical,{headers:{'content-type':'image/png','content-length':String(physical.length)}})}};
 const ports={repository,materialPorts,getMaterial:async(id:string,tenant:string)=>materialPorts.getMaterial(tenant,id),sourceOptions:{resolve:async()=>({optionId:'actual-option',kind:'material' as const,sourceRef,sourceVersion:sha,label:'真实产品',type:'image' as const,thumbnailHref:null}),list:async()=>({items:[],totalItems:0,totalPages:0,page:1,perPage:20,status:'ready' as const})}};
 const materials=createWeeklyMaterialRequestService(f.store,materialPorts),requirement=actual.requirements[0];assert.ok(requirement);assert.equal(actual.requirements.length,1);
 const request=await materials.create({tenantId:'t',programId:pkg.programId,requirementKey:requirement.requirementId,requirements:requirement.description,assigneeUserId:'owner',reviewerUserId:'owner',dueAt:preparation.schedule.estimatedStartAt!,verificationDueAt:preparation.schedule.estimatedFinishAt!,timeZone:'Asia/Shanghai',consumers:[{taskId:material.taskId,packageId:pkg.packageId,packageVersion:pkg.version,requirement:`${requirement.requirementId}：${requirement.description}`}],actorUserId:'owner'});
 await materials.submit({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',materialRecordIds:[recordId],expectedSubmissionVersion:0});await materials.review({tenantId:'t',programId:pkg.programId,requestId:request.requestId,actorUserId:'owner',submissionVersion:1,consumerDecisions:[{taskId:material.taskId,accepted:true,factCheck:'实物产品身份一致',rightsCheck:'企业授权此商业用途',visualCheck:'实物包装符合目标镜头要求'}]});
 await bindWeeklyOwnedProductIdentity(f.store,scope,{actorUserId:'owner',expectedTaskVersion:actual.contentTaskVersion,expectedRequirementHash:actual.requirementHash,bindings:[{requirementId:requirement.requirementId,requestId:request.requestId}]},ports);
 const actualWorker=createSocialWeeklyExecutionWorker(f.store,{ownedProductIdentity:ports});await recheckWeeklyMaterialPreparation(f.store,recoveryScope,ports);
 const readyClaim=await actualWorker.claimNext({tenantId:'t',workerId:'m1-real-preparation-worker',now:due});assert.equal(readyClaim?.task.taskId,preparation.taskId);assert.ok(readyClaim);
 const phaseAdapter=createSocialWeeklyProductionAdapter(f.store,{repository,sourceOptions:ports.sourceOptions,ownedProductIdentity:ports});const preparationOutput=await phaseAdapter.execute(readyClaim.task);assert.equal(preparationOutput.status,'succeeded',JSON.stringify(preparationOutput));if(preparationOutput.status!=='succeeded')throw Error('actual material preparation missing');await actualWorker.complete(readyClaim,preparationOutput.resultRefs,due);
 console.log('M1_MATERIAL_READY',JSON.stringify({packageId:pkg.packageId,version:pkg.version,preparationTaskId:preparation.taskId,materialConsumerTaskId:material.taskId,contentTaskId:scope.contentTaskId,requestId:request.requestId,fileSha256:sha,runId:created.run_id??null}));
 console.log('M1_ACTIVE_GRAPH',JSON.stringify({packageId:activated.packageId,version:activated.version,tasks:(await listWeeklyExecutionTasks(f.store,'t','p',activated.packageId,activated.version)).map(task=>({taskId:task.taskId,step:task.schedule.stepKind,status:task.status,own:task.ownBlockingReasons}))}));
 console.log('M1_INITIAL_CAPACITY',JSON.stringify({packageId:result.item.packageId,version:result.item.version,snapshotId:result.snapshot.snapshotId,source:'controlled external analysis and explicit user capacity assumptions; no supplier paid'}));
});
