import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,WeeklyOperatingPackage,VersionedSocialRef} from '../../shared/contracts/socialProgram.js';
import {socialObject,socialJson,socialRequestHash} from '../starter198/socialContentValidation.js';
import {withExecutionPackageGate,executionPackageFrozen} from '../socialPrograms/weeklyExecutionGate.js';
import {socialAccessToken,youtubeCredentials} from '../lib/accountCredentials.js';
import {readWeeklyPublicationMetricEvidence,type WeeklyPublicationMetricRead} from './weeklyPublicationMetricEvidence.js';
import {readOfficialWeeklyPublicationMetrics,type MetricPublication,type MetricProviderSample} from './weeklyPublicationMetricProvider.js';
import type {SocialWeeklyExecutionAdapter} from './socialWeeklyExecutionAdapter.js';
import {createWeeklyExecutionTaskService} from '../socialPrograms/executionTasks.js';
import {SOCIAL_METRIC_KEYS} from '../socialMetrics/aggregation.js';
export const WEEKLY_METRIC_COLLECTION_JOBS='weekly_metric_collection_jobs';
type Attribution=WeeklyPublicationMetricRead&{publications:MetricPublication[]};
export interface MetricProducerPorts {now?:()=>Date;fetch?:typeof fetch;graphVersion?:string;readAttribution?:typeof readWeeklyPublicationMetricEvidence;readProvider?:(input:{publication:MetricPublication;account:Record_})=>Promise<MetricProviderSample>;}
interface Job {type:'weekly_metric_collection_job';jobId:string;tenantId:string;programId:string;packageId:string;packageVersion:number;taskId:string;accountId:string;taskHash:string;status:'collecting'|'collected'|'blocked'|'no_data';publicationHash:string|null;accountHash:string|null;publicationRefs:MetricPublication[];snapshotRefs:VersionedSocialRef[];createdAt:string;updatedAt:string;lastError:string|null;recordHash:string;}
const parsed=<T>(value:unknown)=>socialObject(socialJson(value)) as unknown as T;
const taskHash=(t:WeeklyExecutionTask)=>socialRequestHash({tenantId:t.tenantId,programId:t.programId,packageId:t.packageId,packageVersion:t.packageVersion,taskId:t.taskId,accountId:t.accountId,stepKind:t.schedule.stepKind,inputSnapshot:t.inputSnapshot});
const seal=(v:Job)=>({...v,recordHash:socialRequestHash({...v,recordHash:''})});
async function rows(store:DataStore,name:string,where:Record<string,string|number>) {const out:Record_[]=[];let total:number|undefined;for(let page=1;page<=10000;page++){const r=await store.list<Record_>(name,{where,page,perPage:100,sort:'id'});if(!Number.isSafeInteger(r.totalItems)||r.totalItems<0||total!==undefined&&r.totalItems!==total||r.items.some(x=>!x.id||out.some(y=>y.id===x.id)||Object.entries(where).some(([k,v])=>x[k]!==v)))throw Error('weekly_metric_producer_read_invalid');total=r.totalItems;out.push(...r.items);if(out.length===total)return out;if(!r.items.length||out.length>total)break;}throw Error('weekly_metric_producer_read_incomplete');}
function validateJob(row:Record_,task:WeeklyExecutionTask){const j=parsed<Job>(row.payload);if(j?.type!=='weekly_metric_collection_job'||j.jobId!==row.id||j.tenantId!==row.tenant_id||j.programId!==row.program_id||j.packageId!==row.package_id||j.packageVersion!==row.package_version||j.taskId!==row.task_id||j.accountId!==row.account_id||j.status!==row.status||!['collecting','collected','blocked','no_data'].includes(j.status)||row.record_hash!==j.recordHash||j.recordHash!==socialRequestHash({...j,recordHash:''})||j.tenantId!==task.tenantId||j.programId!==task.programId||j.packageId!==task.packageId||j.packageVersion!==task.packageVersion||j.taskId!==task.taskId||j.accountId!==task.accountId||j.taskHash!==taskHash(task))throw Error('weekly_metric_collection_job_corrupt');return j;}
async function live(store:DataStore,task:WeeklyExecutionTask){if(task.workflowKind!=='engagement'||task.schedule.stepKind!=='performance_monitoring'||!task.accountId)throw Error('weekly_metric_producer_task_invalid');const ts=await rows(store,'social_weekly_execution_tasks',{tenant_id:task.tenantId,program_id:task.programId,task_id:task.taskId});const t=parsed<WeeklyExecutionTask>(ts[0]?.payload);if(ts.length!==1||taskHash(t)!==taskHash(task)||['cancelled','dead_letter'].includes(t.status))throw Error('weekly_metric_producer_consumer_changed');const ps=await rows(store,'social_weekly_operating_packages',{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,version:task.packageVersion});const pkg=parsed<WeeklyOperatingPackage>(ps[0]?.payload);if(ps.length!==1||pkg.programId!==task.programId||pkg.packageId!==task.packageId||pkg.version!==task.packageVersion||!['active','draft'].includes(pkg.status)||await executionPackageFrozen(store,task))throw Error('weekly_metric_producer_package_changed');return pkg;}
async function account(store:DataStore,task:WeeklyExecutionTask,platform:string,now:Date){const a=await store.getById<Record_>(platform==='youtube'?'youtube_accounts':'social_accounts',String(task.accountId));if(!a||a.tenantId!==task.tenantId||a.id!==task.accountId||a.status!=='connected'||platform!=='youtube'&&a.platform!==platform||a.mock||a.simulated||a.synthetic)throw Error('weekly_metric_credentials_unavailable');const expires=String(a.tokenExpiresAt??a.expiresAt??'');if(expires&&(!Number.isFinite(Date.parse(expires))||Date.parse(expires)<=now.getTime()))throw Error('weekly_metric_credentials_expired');if(platform==='youtube')youtubeCredentials(a);else{socialAccessToken(a);const scopes=new Set(String(a.scope??'').split(/[\s,]+/));const required=platform==='facebook'?'read_insights':platform==='instagram'?(a.oauthProvider==='instagram_login'?'instagram_business_manage_insights':'instagram_manage_insights'):'video.list';if(!scopes.has(required))throw Error('weekly_metric_scope_missing');}const native=String(platform==='youtube'?a.channelId??'':a.providerAccountId??'');if(!native)throw Error('weekly_metric_native_account_missing');return{row:a,native,hash:socialRequestHash({tenantId:task.tenantId,accountId:a.id,platform,native,oauthProvider:a.oauthProvider??null,parentPageId:a.parentPageId??null})};}
export function createWeeklyPublicationMetricProducerAdapter(store:DataStore,ports:MetricProducerPorts={}):SocialWeeklyExecutionAdapter {return{async execute(task){const now=ports.now?.()??new Date();let job:Job|undefined;try{return await withExecutionPackageGate(store,task,async assert=>{
 const pkg=await live(store,task),jobId=socialRequestHash({type:'weekly_metric_collection_job',tenantId:task.tenantId,taskId:task.taskId}).slice(0,15),old=await rows(store,WEEKLY_METRIC_COLLECTION_JOBS,{tenant_id:task.tenantId,task_id:task.taskId});if(old.length>1)throw Error('weekly_metric_collection_job_ambiguous');job=old.length?validateJob(old[0]!,task):{type:'weekly_metric_collection_job',jobId,tenantId:task.tenantId,programId:task.programId,packageId:task.packageId,packageVersion:task.packageVersion,taskId:task.taskId,accountId:String(task.accountId),taskHash:taskHash(task),status:'collecting',publicationHash:null,accountHash:null,publicationRefs:[],snapshotRefs:[],createdAt:now.toISOString(),updatedAt:now.toISOString(),lastError:null,recordHash:''};
 const persist=async()=>{job!.updatedAt=now.toISOString();job=seal(job!);await assert();const data={id:job.jobId,tenant_id:job.tenantId,program_id:job.programId,package_id:job.packageId,package_version:job.packageVersion,task_id:job.taskId,account_id:job.accountId,status:job.status,payload:job,record_hash:job.recordHash};if(old.length||await store.getById(WEEKLY_METRIC_COLLECTION_JOBS,job.jobId)){if(!await store.update(WEEKLY_METRIC_COLLECTION_JOBS,job.jobId,data))throw Error('weekly_metric_collection_job_write_failed');}else if(!await store.create(WEEKLY_METRIC_COLLECTION_JOBS,data))throw Error('weekly_metric_collection_job_write_failed');};
 await persist();try{
 const allPubs=pkg.socialContentPackage.publicationTasks.filter(p=>p.accountId===task.accountId),pubs=allPubs.filter(p=>p.status!=='cancelled');const declaredPlatforms=[...new Set(allPubs.map(p=>p.platform))];let platform=declaredPlatforms.length===1?declaredPlatforms[0]!:'';if(!allPubs.length){const youtube=await store.getById<Record_>('youtube_accounts',String(task.accountId)),social=await store.getById<Record_>('social_accounts',String(task.accountId));const exact=[youtube&&youtube.tenantId===task.tenantId?{platform:'youtube'}:null,social&&social.tenantId===task.tenantId?{platform:String(social.platform??'')}:null].filter(value=>value!==null);if(exact.length===1)platform=exact[0]!.platform;}if(!['youtube','facebook','instagram','tiktok'].includes(platform)||pubs.some(p=>p.platform!==platform))throw Error('weekly_metric_producer_platform_invalid');const a=await account(store,task,platform,now);if(job.accountHash&&job.accountHash!==a.hash)throw Error('weekly_metric_producer_account_changed');job.accountHash=a.hash;
 if(job.snapshotRefs.length){const proof=await (ports.readAttribution??readWeeklyPublicationMetricEvidence)(store,task,pkg,now) as Attribution;if(socialRequestHash(proof.publications)!==job.publicationHash||job.snapshotRefs.some(ref=>!proof.sources.some(row=>row.id===ref.id)))throw Error('weekly_metric_collected_provenance_changed');for(const ref of job.snapshotRefs){const snapshot=await store.getById<Record_>('social_metric_snapshots',ref.id);const raw=parsed<Record<string,unknown>>(snapshot?.raw_metrics),bound=parsed<Record<string,unknown>>(raw?.weeklyProducer);if(!snapshot||bound?.jobId!==job.jobId||bound.taskHash!==job.taskHash||bound.publicationHash!==job.publicationHash||bound.accountHash!==a.hash||bound.recordHash!==socialRequestHash({...bound,recordHash:''})||bound.metricsHash!==socialRequestHash(snapshot.metrics)||bound.providerHash!==socialRequestHash(raw.provider))throw Error('weekly_metric_collected_provenance_changed');}job.status='collected';job.lastError=null;await persist();return{status:'succeeded',resultRefs:job.snapshotRefs};}
 if(!pubs.length){job.status='no_data';job.lastError='weekly_metrics_complete_empty_publication_set';await persist();return{status:'blocked',code:job.lastError,message:'完整空发布集合已记录 no_data；不作为指标完成证明。'};}
 const start=Date.parse(`${pkg.weekStart}T00:00:00Z`),end=Date.parse(`${pkg.weekEnd}T23:59:59.999Z`);const evidence=await (ports.readAttribution??readWeeklyPublicationMetricEvidence)(store,task,pkg,now) as Attribution;const publications=evidence.publications;if(!Array.isArray(publications)||publications.length!==pubs.length||pubs.some(pub=>publications.filter(p=>p.publicationTaskId===pub.publicationTaskId&&p.accountId===pub.accountId&&p.platform===pub.platform).length!==1))throw Error('weekly_metric_published_receipt_missing');const publicationHash=socialRequestHash(publications);if(job.publicationHash&&job.publicationHash!==publicationHash)throw Error('weekly_metric_publication_changed');job.publicationHash=publicationHash;job.publicationRefs=publications;await persist();
 const refs:VersionedSocialRef[]=[];
 for(const publication of publications){const date=now.toISOString().slice(0,10),existing=await rows(store,'social_metric_snapshots',{tenant_id:task.tenantId,platform:publication.platform,account_id:publication.accountId,content_id:publication.platformPostId});const candidates=existing.filter(row=>parsed<Record<string,unknown>>(parsed<Record<string,unknown>>(row.raw_metrics)?.weeklyProducer)?.jobId===job!.jobId);if(candidates.length>1)throw Error('weekly_metric_snapshot_ambiguous');if(candidates.length){const raw=parsed<Record<string,unknown>>(candidates[0]!.raw_metrics),binding=parsed<Record<string,unknown>>(raw?.weeklyProducer);if(!evidence.sources.some(source=>source.id===candidates[0]!.id)||binding?.jobId!==job.jobId||binding.taskHash!==job.taskHash||binding.publicationHash!==publicationHash||binding.accountHash!==a.hash||binding.recordHash!==socialRequestHash({...binding,recordHash:''})||socialRequestHash(candidates[0]!.metrics)!==binding.metricsHash||socialRequestHash(raw.provider)!==binding.providerHash)throw Error('weekly_metric_snapshot_identity_changed');refs.push({type:'social_metric_snapshot',id:candidates[0]!.id,version:1});continue;}
 if(!Number.isFinite(start)||!Number.isFinite(end)||now.getTime()<start||now.getTime()>end)throw Error('weekly_metric_capture_outside_week');if(existing.some(row=>row.snapshot_date===date))throw Error('weekly_metric_snapshot_identity_changed');const sample=await (ports.readProvider??(input=>readOfficialWeeklyPublicationMetrics({...input,fetch:ports.fetch,graphVersion:ports.graphVersion})))({publication,account:a.row});if(sample.platformPostId!==publication.platformPostId||sample.nativeAccountId!==a.native||!Object.keys(sample.metrics).length||Object.entries(sample.metrics).some(([key,value])=>!SOCIAL_METRIC_KEYS.includes(key as typeof SOCIAL_METRIC_KEYS[number])||typeof value!=='number'||!Number.isFinite(value)||value<0||sample.presence[key]!==true))throw Error('weekly_metric_sample_invalid');await live(store,task);const current=await account(store,task,platform,now);if(current.hash!==a.hash)throw Error('weekly_metric_producer_account_changed');const fresh=await (ports.readAttribution??readWeeklyPublicationMetricEvidence)(store,task,pkg,now) as Attribution;if(socialRequestHash(fresh.publications)!==publicationHash)throw Error('weekly_metric_publication_changed');const body={jobId:job.jobId,taskHash:job.taskHash,publicationHash,accountHash:a.hash,metricsHash:socialRequestHash(sample.metrics),providerHash:socialRequestHash(sample.raw),presence:sample.presence,publication,recordHash:''},binding={...body,recordHash:socialRequestHash(body)};const id=socialRequestHash({tenantId:task.tenantId,platform:publication.platform,accountId:publication.accountId,contentId:publication.platformPostId,date}).slice(0,15);await assert();if(!await store.create('social_metric_snapshots',{id,tenant_id:task.tenantId,platform:publication.platform,account_id:publication.accountId,content_id:publication.platformPostId,snapshot_date:date,captured_at:now.toISOString(),value_kind:'cumulative',metrics:sample.metrics,raw_metrics:{provider:sample.raw,weeklyProducer:binding}}))throw Error('weekly_metric_snapshot_write_failed');refs.push({type:'social_metric_snapshot',id,version:1});}
 job.snapshotRefs=refs;job.status='collected';job.lastError=null;await persist();return{status:'succeeded',resultRefs:refs};
 }catch(error){job.status='blocked';job.lastError=error instanceof Error?error.message:'weekly_metric_provider_unavailable';await persist();throw error;}
 });}catch(error){return{status:'blocked',code:error instanceof Error?error.message:'weekly_metric_collection_failed',message:'真实发布指标采集尚未就绪；保留原始缺项，未用零值替代。'};}}};}
export async function listWeeklyMetricCollectionJobs(input:{store:DataStore;tenantId:string;programId:string;packageId:string;packageVersion:number}) {const result:Job[]=[];for(const row of await rows(input.store,WEEKLY_METRIC_COLLECTION_JOBS,{tenant_id:input.tenantId,program_id:input.programId,package_id:input.packageId,package_version:input.packageVersion})){const ts=await rows(input.store,'social_weekly_execution_tasks',{tenant_id:input.tenantId,program_id:input.programId,task_id:String(row.task_id)});if(ts.length!==1)throw Error('weekly_metric_producer_consumer_changed');const task=parsed<WeeklyExecutionTask>(ts[0]!.payload);if(task.tenantId!==input.tenantId||task.programId!==input.programId||task.packageId!==input.packageId||task.packageVersion!==input.packageVersion)throw Error('weekly_metric_producer_consumer_changed');result.push(validateJob(row,task));}return result;}

/** Formal scan-start recovery only for the same blocked producer and gap. */
export async function runWeeklyMetricCollectionRecoveryScan(input:{store:DataStore;ports?:MetricProducerPorts;now?:Date;tenantIds?:string[]}){
 const report={recovered:0,failed:0};
 const jobs=await rows(input.store,WEEKLY_METRIC_COLLECTION_JOBS,{status:'blocked'});
 for(const row of jobs){if(input.tenantIds&&!input.tenantIds.includes(String(row.tenant_id)))continue;try{
 const ts=await rows(input.store,'social_weekly_execution_tasks',{tenant_id:String(row.tenant_id),program_id:String(row.program_id),task_id:String(row.task_id)});if(ts.length!==1)throw Error('weekly_metric_producer_consumer_changed');const task=parsed<WeeklyExecutionTask>(ts[0]!.payload),job=validateJob(row,task),gap=job.lastError;
 if(task.status!=='blocked'||task.lease||!gap||task.lastError?.code!==gap||!task.ownBlockingReasons.includes(gap))continue;
 await withExecutionPackageGate(input.store,task,async assert=>{await live(input.store,task);const result=await createWeeklyPublicationMetricProducerAdapter(input.store,{...input.ports,now:()=>input.now??input.ports?.now?.()??new Date()}).execute(task);if(result.status!=='succeeded')return;const current=(await rows(input.store,'social_weekly_execution_tasks',{tenant_id:task.tenantId,program_id:task.programId,task_id:task.taskId}));const fresh=parsed<WeeklyExecutionTask>(current[0]?.payload);if(current.length!==1||taskHash(fresh)!==taskHash(task)||fresh.status!=='blocked'||fresh.lease||fresh.lastError?.code!==gap||!fresh.ownBlockingReasons.includes(gap))throw Error('weekly_metric_producer_consumer_changed');await assert();const changed=await createWeeklyExecutionTaskService(input.store).unblock(task.tenantId,task.programId,task.packageId,task.taskId,gap);if(!changed.some(t=>t.taskId===task.taskId&&!t.ownBlockingReasons.includes(gap)))throw Error('weekly_metric_recovery_failed');report.recovered++;});
 }catch{report.failed++;}}
 return report;
}
