import test from 'node:test';import assert from 'node:assert/strict';
import {prepareFiveMotherProductionFixture} from './weeklyFiveMotherProduction.fixture.js';
import {admitContentExecutionJob,setContentExecutionLimit,listContentExecutionJobs,DurableContentExecutionWorker,controlContentExecutionJob,type ContentExecutionLimitScope} from '../contentExecution/durableQueue.js';
/** Real durable admission/claim, with a held execution port and no provider calls or success receipts. */
export async function assertFiveMotherDurableCapacity(setup:Awaited<ReturnType<typeof prepareFiveMotherProductionFixture>>,limited:ContentExecutionLimitScope){
 const store=setup.f.store,tasks=setup.tasks.filter(t=>t.schedule.stepKind==='video_generation');assert.equal(tasks.length,5);assert.equal(new Set(tasks.map(t=>t.inputSnapshot.motherContentId)).size,5);const now=new Date(setup.clock);
 for(const [scope,scopeKey]of [['tenant','*'],['account','account'],['task_type','social_content_weekly']] as const)await setContentExecutionLimit({dataStore:store,tenantId:'t',scope,scopeKey,maxRunning:scope===limited?1:5,updatedBy:'owner',now});
 const jobs=await Promise.all(tasks.map(task=>admitContentExecutionJob({dataStore:store,tenantId:task.tenantId,userId:'owner',taskId:task.taskId,runId:`capacity-admission:${task.taskId}`,accountId:task.accountId!,taskType:'social_content_weekly',now})));
 assert.equal(new Set(jobs.map(j=>j.id)).size,5);let release!:()=>void;const gate=new Promise<void>(resolve=>{release=resolve;}),started:string[]=[];let succeeded=0;
 const worker=new DurableContentExecutionWorker({dataStore:store,now:()=>now,env:{CONTENT_EXECUTION_WORKER_CONCURRENCY:'5',CONTENT_EXECUTION_TENANT_MAX_RUNNING:'5',CONTENT_EXECUTION_ACCOUNT_MAX_RUNNING:'5',CONTENT_EXECUTION_TASK_TYPE_MAX_RUNNING:'5'},async execute(job){started.push(job.taskId);await gate;throw Error('content_execution_stopped');},async onSucceeded(){succeeded++;}});
 try{await worker.drain();await worker.drain();assert.equal(started.length,1,`${limited} admission must leave four real mothers waiting`);const actual=await listContentExecutionJobs(store,'t');assert.equal(actual.filter(j=>j.status==='running').length,1);assert.equal(actual.filter(j=>j.status==='queued').length,4);assert.ok(actual.every(j=>j.providerReceipts.length===0&&!j.completedAt));assert.ok(started.every(id=>tasks.some(t=>t.taskId===id)));}finally{for(const job of jobs)await controlContentExecutionJob({dataStore:store,tenantId:'t',jobId:job.id,action:'pause'});release();for(let i=0;i<30&&tasks.some(t=>worker.isLocallyActive('t',t.taskId));i++)await new Promise<void>(resolve=>setImmediate(resolve));worker.stop();}
 assert.equal(succeeded,0);const final=await listContentExecutionJobs(store,'t');assert.ok(final.every(j=>j.status==='paused'&&!j.completedAt&&j.providerReceipts.length===0));assert.equal(setup.f.tables.social_publication_attempts?.length??0,0);
}
for(const scope of ['tenant','account','task_type'] as const)test(`five persisted mother tasks obey durable ${scope} limit under actual parallel worker admission`,async t=>{const setup=await prepareFiveMotherProductionFixture(t);await assertFiveMotherDurableCapacity(setup,scope);});
