import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import {setup,weekly} from './weeklyPublicationMetricProducer.fixture.js';
import {readStarterPublicationPackage} from '../publishing/starterPublicationPackage.js';
import {executeWeeklyPublication,type WeeklyPublishingProviderAdapter} from '../publishing/weeklyLineage.js';
import {encryptSecret} from '../lib/tenantPlatformApps.js';
import {WEEKLY_METRIC_COLLECTION_JOBS} from './weeklyPublicationMetricProducer.js';
import {createDefaultWeeklyExecutionAdapters} from './weeklyExecutionAdapters.js';
import {runSocialWeeklyExecutionScan} from './socialWeeklyExecutionRuntime.js';
import {createSocialWeeklyProducerEvidenceRouter} from '../routes/socialWeeklyProducerEvidence.js';
const now=new Date('2026-09-26T12:00:00Z');
async function fixture(t:Parameters<typeof setup>[0]){t.mock.timers.reset();t.mock.timers.enable({apis:['Date'],now:new Date('2026-09-24T12:00:00Z')});const f=await setup(t),task=f.tasks.find(t=>t.schedule.stepKind==='performance_monitoring')!;await f.dataStore.create('social_weekly_execution_tasks',{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion,task_id:task.taskId,payload:task,status:task.status});await f.dataStore.create('youtube_accounts',{id:'account-1',tenantId:'tenant-a',status:'connected',channelId:'channel-real',clientId:'local-client',clientSecret:encryptSecret('local-secret'),accessToken:encryptSecret('local-token'),tokenExpiresAt:'2099-01-01T00:00:00Z'});const provider:WeeklyPublishingProviderAdapter={provider:'youtube-data-api',platform:'youtube',capability:'available',publish:async()=>({status:'published',providerReceiptId:'receipt-real',platformPostId:'post-real'}),reconcile:async()=>{throw Error('unreachable');}};const publicationPackage=await readStarterPublicationPackage('tenant-a',f.assignment.packageId,f.dataStore);assert.ok(publicationPackage);assert.equal((await executeWeeklyPublication({assignment:f.assignment,publicationPackage,contentPackage:weekly.socialContentPackage,adapter:provider,existingPublishedCount:0,dataStore:f.dataStore,now:new Date('2026-09-24T12:00:00Z')})).status,'published');return{...f,task};}
const actualResponse=()=>new Response(JSON.stringify({items:[{id:'post-real',snippet:{channelId:'channel-real'},statistics:{viewCount:'0',likeCount:null}}]}),{status:200,headers:{'Content-Type':'application/json'}});

test('formal runtime produces metrics from real published receipt; blocked credential repair scan recovers original task and combined HTTP GET is read-only',async t=>{
 const f=await fixture(t);f.task.dependsOnTaskIds=[];f.task.status='queued';f.task.ownBlockingReasons=[];f.task.inheritedBlockingTaskIds=[];f.task.schedule.estimatedStartAt=now.toISOString();f.task.schedule.latestStartAt='2026-09-27T12:00:00Z';const row=f.dataStore.rows.get('social_weekly_execution_tasks')!.find(r=>r.task_id===f.task.taskId)!;row.status='queued';
 f.dataStore.rows.set('social_weekly_agent_planning',[{id:'planning',tenant_id:'tenant-a',program_id:f.task.programId,package_id:f.task.packageId,package_version:2,planning_version:4,payload:{planningId:'planning',version:4,programId:f.task.programId,packageId:f.task.packageId,packageVersion:2,status:'dispatched',skeleton:{slots:[{slotId:'slot',motherContentId:'mother',publicationTaskIds:['weekly-item-1'],accountIds:['account-1'],platforms:['youtube']}]},directorAnalyses:[],detailedSchedule:{ref:{id:'schedule',version:1},items:[]},userConfirmation:{confirmedBy:'owner'},dispatch:{packageVersion:2,detailedScheduleRef:{id:'schedule',version:1},scheduleItems:[]}}}]);
 const account=f.dataStore.rows.get('youtube_accounts')![0]!,token=account.accessToken;account.accessToken='';let calls=0;const ports={now:()=>now,fetch:async()=>{calls++;return actualResponse();}};const adapters=createDefaultWeeklyExecutionAdapters(f.dataStore,{metrics:ports});
 const first=await runSocialWeeklyExecutionScan({dataStore:f.dataStore,now,adapters,maxTasksPerTenant:1,metricRecoveryPorts:{ports}});assert.equal(first.blocked,1,JSON.stringify(first));assert.equal(calls,0);assert.equal(row.payload.status,'blocked');assert.equal(f.dataStore.rows.get(WEEKLY_METRIC_COLLECTION_JOBS)![0]!.payload.status,'blocked');
 account.accessToken=token;const later=new Date('2026-09-27T12:00:00Z');const latePorts={...ports,now:()=>later};const recovered=await runSocialWeeklyExecutionScan({dataStore:f.dataStore,now:later,adapters:createDefaultWeeklyExecutionAdapters(f.dataStore,{metrics:latePorts}),maxTasksPerTenant:1,metricRecoveryPorts:{ports:latePorts}});assert.equal(recovered.metricRecovery.recovered,1,JSON.stringify(recovered));assert.equal(recovered.succeeded,1,JSON.stringify(recovered));assert.equal(row.payload.taskId,f.task.taskId);assert.equal(row.payload.status,'succeeded');assert.equal(calls,1);assert.equal((await runSocialWeeklyExecutionScan({dataStore:f.dataStore,now:later,adapters,maxTasksPerTenant:1,metricRecoveryPorts:{ports:latePorts}})).claimed,0);assert.equal(calls,1);
 await f.dataStore.create('users',{id:'owner',tenantId:'tenant-a',role:'admin'});let tenant='tenant-a';const app=express();app.use((_req,res,next)=>{res.locals.tenantId=tenant;res.locals.userId='owner';next();});app.use('/:programId/:packageId',createSocialWeeklyProducerEvidenceRouter(f.dataStore));app.use((error:Error,_req:express.Request,res:express.Response,_next:express.NextFunction)=>res.status(409).json({error:error.message}));const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));t.after(()=>new Promise<void>(r=>server.close(()=>r())));const address=server.address();assert.ok(address&&typeof address==='object');const url=`http://127.0.0.1:${address.port}/${f.task.programId}/${f.task.packageId}?version=2`;
 const create=f.dataStore.create,update=f.dataStore.update,del=f.dataStore.delete;let writes=0;f.dataStore.create=async()=>{writes++;throw Error('GET_cannot_create');};f.dataStore.update=async()=>{writes++;throw Error('GET_cannot_update');};f.dataStore.delete=async()=>{writes++;throw Error('GET_cannot_delete');};try{const response=await fetch(url),body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.equal(body.items.metrics.length,1);assert.equal(body.items.metrics[0].taskId,f.task.taskId);assert.equal(body.items.metrics[0].status,'collected');assert.equal((await fetch(url.replace('version=2','version=1'))).status,409);tenant='foreign';assert.equal((await fetch(url)).status,403);assert.equal(writes,0);assert.equal(calls,1);}finally{f.dataStore.create=create;f.dataStore.update=update;f.dataStore.delete=del;}
});
