import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import type {DataStore,ListQuery,Record_} from '../storage/datastore.js';
import {socialRequestHash} from '../starter198/socialContentValidation.js';
import {issueWeeklyCreativeRepairAuthority,resolveWeeklyCreativeRepairAuthority} from './weeklyCreativeRepairAuthority.js';
import {WEEKLY_PRODUCTION_REPAIR_CASES} from '../socialPrograms/weeklyProductionRepairCases.js';
import {WEEKLY_CREATIVE_REPAIR_CONFIGURATIONS} from '../socialPrograms/weeklyCreativeRepairConfiguration.js';

function fixture(deadlineAt='2026-10-12T12:00:00.000Z'){
 const tables=new Map<string,Record_[]>();
 const store:DataStore={getById:async<T>(c:string,id:string)=>structuredClone(tables.get(c)?.find(r=>r.id===id)??null) as T|null,list:async<T>(c:string,q:ListQuery={})=>{const items=(tables.get(c)??[]).filter(r=>Object.entries(q.where??{}).every(([k,v])=>r[k]===v));return{items:structuredClone(items) as T[],totalItems:items.length,totalPages:1,page:1,perPage:q.perPage??30};},create:async<T>(c:string,v:Record<string,unknown>)=>{const rows=tables.get(c)??[],row={id:String(v.id??`${c}-${rows.length}`),...structuredClone(v)};tables.set(c,[...rows,row]);return structuredClone(row) as T;},update:async(c,id,v)=>{const row=tables.get(c)?.find(r=>r.id===id);if(!row)return false;Object.assign(row,structuredClone(v));return true;},delete:async()=>false};
 const pkg={programId:'program',packageId:'package',version:3},authority={weeklyPackage:pkg,programRef:{type:'social_program',id:'program',version:2},publicationTask:{publicationTaskId:'publication'},weeklyWorkflowTask:{taskRef:{type:'weekly_workflow_task',id:'workflow',version:3}}};
 const content={productionResult:{id:'original'}};const artifactHash=socialRequestHash({resourceRef:'socialfile:original',content});
 const body:any={schemaVersion:'weekly-production-repair-case.v1',caseId:'case',version:1,requestId:'request',requestHash:'request-hash',tenantId:'tenant',programId:'program',packageId:'package',packageVersion:3,publicationTaskId:'publication',accountId:'account',qualityTaskId:'quality',approvalTaskId:'approval',kind:'creative_revision',trigger:{type:'user_changes_requested',operationId:'decision',operationRequestHash:'decision-hash',artifactDecisionVersion:1,note:'调整开头',noteHash:socialRequestHash('调整开头')},parent:{taskId:'parent',runId:'parent-run',artifactRef:{type:'starter_social_content_artifact',id:'artifact',version:1},artifactHash,sceneCacheHash:'cache'},affectedSceneIds:[],ownerUserId:'owner',reviewerUserId:'reviewer',deadlineAt,affectedPublishWindow:'2026-10-13T12:00:00.000Z',estimatedDurationMinutes:60,maximumCostCny:10,configurationGaps:[],state:'ready',admission:null,execution:null,childArtifactRef:null,createdBy:'reviewer',createdAt:'2026-10-10T00:00:00.000Z',updatedAt:'2026-10-10T00:00:00.000Z'};const item={...body,recordHash:socialRequestHash(body)};
 const configBody:any={type:'weekly_creative_repair_configuration',version:1,tenantId:'tenant',caseId:'case',parentArtifactHash:artifactHash,decisionOperationId:'decision',feedbackHash:item.trigger.noteHash,revisionScope:'只调整前三秒',estimatedDurationMinutes:60,maximumCostCny:10,deadlineAt,ownerUserId:'owner',reviewerUserId:'reviewer',confirmedBy:'owner',confirmedAt:'2026-10-10T01:00:00.000Z'};const configuration={...configBody,recordHash:socialRequestHash(configBody)};
 tables.set(WEEKLY_PRODUCTION_REPAIR_CASES,[{id:'case-row',tenant_id:'tenant',case_id:'case',content_hash:socialRequestHash(item),payload:item}]);tables.set(WEEKLY_CREATIVE_REPAIR_CONFIGURATIONS,[{id:'config-row',tenant_id:'tenant',case_id:'case',content_hash:socialRequestHash(configuration),payload:configuration}]);tables.set('social_weekly_operating_packages',[{id:'package-row',tenant_id:'tenant',program_id:'program',package_id:'package',version:3,payload:{...pkg,status:'active',executionGraphVersion:3}}]);tables.set('starter_social_content_tasks',[{id:'parent-row',tenant_id:'tenant',task_id:'parent',run_id:'parent-run',weekly_plan_id:'package',create_idempotency_key:'weekly-production:package:3:publication',brief:{_weeklyAuthority:authority}}]);tables.set('starter_social_content_artifacts',[{id:'artifact-row',tenant_id:'tenant',task_id:'parent',artifact_id:'artifact',status:'changes_requested',last_operation_id:'decision',resource_ref:'socialfile:original',content,content_hash:artifactHash}]);tables.set('starter_social_content_operations',[{id:'operation-row',tenant_id:'tenant',operation_id:'decision',operation:'decide_social_content_artifact',target_id:'parent',request_hash:'decision-hash',status:'succeeded'}]);
 return{store,tables,item,configuration,authority};
}
async function child(f:ReturnType<typeof fixture>){const issued=await issueWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',caseId:'case',childTaskId:'child',expectedCaseHash:f.item.recordHash,expectedConfigurationHash:f.configuration.recordHash,now:new Date('2026-10-10T02:00:00.000Z')});return{...issued,task:{tenant_id:'tenant',task_id:'child',create_idempotency_key:issued.bindingKey,run_id:'',brief:{_weeklyAuthority:issued.authority,_weeklyCreativeRepairProof:issued.proof}}};}

test('server issues a separate child binding and resolves it only from durable repair evidence',async()=>{const f=fixture(),issued=await child(f),actual=await resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:issued.task,now:new Date('2026-10-10T02:01:00.000Z')});assert.equal(issued.bindingKey,'weekly-creative-repair:package:3:publication:case');assert.equal(actual?.repairCase.caseId,'case');assert.deepEqual(actual?.authority,f.authority);assert.equal((f.tables.get('starter_social_content_tasks')![0]!.brief as any)._weeklyAuthority.weeklyPackage.packageId,'package');});

test('forged proof and embedded authority cannot bypass durable case evidence',async()=>{const f=fixture(),issued=await child(f);const forged=structuredClone(issued.task) as any;forged.brief._weeklyAuthority.weeklyPackage.packageId='victim';await assert.rejects(()=>resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:forged,now:new Date('2026-10-10T02:01:00.000Z')}),{code:'weekly_creative_repair_authority_invalid'});const forgedHash=structuredClone(issued.task) as any;forgedHash.brief._weeklyCreativeRepairProof.caseRecordHash='client-value';await assert.rejects(()=>resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:forgedHash,now:new Date('2026-10-10T02:01:00.000Z')}),{code:'weekly_creative_repair_authority_invalid'});});

test('cross tenant use is rejected even with an otherwise valid proof',async()=>{const f=fixture(),issued=await child(f);await assert.rejects(()=>resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'other',task:issued.task,now:new Date('2026-10-10T02:01:00.000Z')}),{code:'weekly_creative_repair_authority_invalid'});});

test('expired proof cannot admit an unstarted child but remains readable for its already started run',async()=>{const f=fixture(),issued=await child(f);await assert.rejects(()=>resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:issued.task,now:new Date('2026-10-12T12:00:00.001Z')}),{code:'weekly_creative_repair_authority_invalid'});const started={...issued.task,run_id:'child-run'};assert.equal((await resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:started,now:new Date('2026-10-12T12:00:00.001Z')}))?.proof.childTaskId,'child');});

test('package cancellation invalidates child admission and runtime context',async()=>{const f=fixture(),issued=await child(f),id=createHash('sha256').update(['tenant','package','3'].join('\0')).digest('hex').slice(0,15);f.tables.set('social_weekly_cancellations',[{id,tenant_id:'tenant',program_id:'program',package_id:'package',package_version:3,status:'completed',effects:[]}]);await assert.rejects(()=>resolveWeeklyCreativeRepairAuthority({store:f.store,tenantId:'tenant',task:issued.task,now:new Date('2026-10-10T02:01:00.000Z')}),{code:'weekly_creative_repair_authority_invalid'});});
