import test,{beforeEach,afterEach} from 'node:test';import assert from 'node:assert/strict';
import {prepareWeeklyEnterpriseFactFixture} from './weeklyEnterpriseFactSupplement.fixture.js';
import {checkWeeklyEnterpriseFactSupplement,ENTERPRISE_FACT_GAP} from './weeklyEnterpriseFactSupplement.js';
import {materializeWeeklySupplementException,listWeeklySupplementExceptions,runWeeklySupplementExceptionScan} from './weeklySupplementExceptionMaterializer.js';
import type {WeeklyExecutionTask} from '../../shared/contracts/socialProgram.js';import type {Record_} from '../storage/datastore.js';
const fetchOriginal=globalThis.fetch;beforeEach(()=>{globalThis.fetch=async()=>{throw Error('operations-stage2-external-fetch-forbidden');};});afterEach(()=>{globalThis.fetch=fetchOriginal;});
test('canonical official operating statement IDs validate confirmed facts; no_data and confirmation drift never ready',async context=>{
 const f=await prepareWeeklyEnterpriseFactFixture(context),now=new Date(Date.now()+1000);const check=()=>checkWeeklyEnterpriseFactSupplement({store:f.store,task:f.task,now});assert.equal((await check()).ready,true,JSON.stringify(await check()));
 const packageRow=(await f.store.list<Record_>('social_weekly_operating_packages')).items[0]!;const noRefs=structuredClone(f.pkg);noRefs.socialContentPackage.publicationTasks[0]!.factRefs=[];await f.store.update('social_weekly_operating_packages',packageRow.id,{payload:noRefs});assert.equal((await check()).reason,'frozen_fact_references_missing');await f.store.update('social_weekly_operating_packages',packageRow.id,{payload:f.pkg});await f.store.update('users','owner',{active:false});assert.equal((await check()).reason,'confirmation_actor_unknown');await f.store.update('users','owner',{active:true});
 const profiles=await f.store.list<Record_>('tenant_profiles');const row=profiles.items[0]!;await f.store.delete('tenant_profiles',row.id);assert.equal((await check()).reason,'no_data');await f.confirm();assert.equal((await check()).ready,true,'actual enterprise confirmation service restores exact statements');
 const restored=(await f.store.list<Record_>('tenant_profiles')).items[0]!;const profile=structuredClone(restored.profile) as typeof f.profile;profile.products.highlights='Changed claim';await f.store.update('tenant_profiles',restored.id,{profile});assert.equal((await check()).reason,'confirmed_content_hash_changed');
});
test('two consumers create independent durable facts exceptions and repair only exact originals; new week stays pending',async context=>{
 const f=await prepareWeeklyEnterpriseFactFixture(context),now=new Date(Date.now()+1000),t=f.task;const second={...structuredClone(t),taskId:'consumer-two'};
 for(const task of [t,second]){task.status='blocked';task.ownBlockingReasons=[ENTERPRISE_FACT_GAP,'other_gap'];task.lastError={code:ENTERPRISE_FACT_GAP,message:'missing confirmed facts',retryable:false,occurredAt:now.toISOString()};await f.store.create('social_weekly_execution_tasks',{tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion,task_id:task.taskId,idempotency_key:task.taskId,status:task.status,payload:task});}
 const profile=(await f.store.list<Record_>('tenant_profiles')).items[0]!;await f.store.delete('tenant_profiles',profile.id);
 assert.equal((await runWeeklySupplementExceptionScan({store:f.store,now})).resolved,0);assert.equal((await runWeeklySupplementExceptionScan({store:f.store,now})).resolved,0);const scope={store:f.store,tenantId:t.tenantId,programId:t.programId,packageId:t.packageId,packageVersion:1};const pending=await listWeeklySupplementExceptions(scope);assert.equal(pending.length,2);assert.equal(new Set(pending.map(p=>p.exceptionId)).size,2);assert.ok(pending.every(p=>p.kind==='enterprise_facts'&&p.status==='assignment_pending'));
 const future={...structuredClone(t),taskId:'next-week-consumer',packageId:'next-week'};const nextPkg={...structuredClone(f.pkg),packageId:'next-week',weekStart:'2026-10-19',weekEnd:'2026-10-25'};await f.store.create('social_weekly_operating_packages',{tenant_id:t.tenantId,program_id:t.programId,package_id:future.packageId,version:1,status:'active',payload:nextPkg});await f.store.create('social_weekly_execution_tasks',{tenant_id:t.tenantId,program_id:t.programId,package_id:future.packageId,package_version:1,task_id:future.taskId,idempotency_key:future.taskId,status:future.status,payload:future});
 await f.confirm();assert.equal((await runWeeklySupplementExceptionScan({store:f.store,now:new Date(Date.now()+1000)})).resolved,2);const consumers=(await f.store.list<Record_>('social_weekly_execution_tasks')).items.map(r=>r.payload as WeeklyExecutionTask);assert.ok(consumers.filter(c=>c.taskId!=='next-week-consumer').every(c=>!c.ownBlockingReasons.includes(ENTERPRISE_FACT_GAP)&&c.ownBlockingReasons.includes('other_gap')));assert.ok(consumers.find(c=>c.taskId==='next-week-consumer')!.ownBlockingReasons.includes(ENTERPRISE_FACT_GAP));assert.equal((await checkWeeklyEnterpriseFactSupplement({store:f.store,task:future,now:new Date(Date.now()+1000)})).reason,'operating_snapshot_scope_changed');
});
test('formal worker consumes persisted fact gap and recovers original task after official confirmation',async context=>{
 const {runSocialWeeklyExecutionScan}=await import('./socialWeeklyExecutionRuntime.js');const f=await prepareWeeklyEnterpriseFactFixture(context),t=f.task;const profile=(await f.store.list<Record_>('tenant_profiles')).items[0]!;await f.store.delete('tenant_profiles',profile.id);
 const plan={planningId:'actual-plan',version:1,programId:t.programId,packageId:t.packageId,packageVersion:1,status:'dispatched',skeleton:{slots:[{slotId:'slot',motherContentId:'mother',publicationTaskIds:['pub'],accountIds:['account-a']}]},directorAnalyses:[],userConfirmation:{confirmedBy:'owner'},detailedSchedule:{ref:{id:'schedule',version:1},items:[]},dispatch:{packageId:t.packageId,packageVersion:1,detailedScheduleRef:{id:'schedule',version:1},scheduleItems:[]}};
 await f.store.create('social_weekly_agent_planning',{tenant_id:t.tenantId,program_id:t.programId,package_id:t.packageId,package_version:1,planning_version:1,payload:plan});await f.store.create('social_weekly_execution_tasks',{tenant_id:t.tenantId,program_id:t.programId,package_id:t.packageId,package_version:1,task_id:t.taskId,idempotency_key:t.taskId,status:t.status,payload:t});
 let executorCalls=0;const adapter={async execute(_task:WeeklyExecutionTask){executorCalls++;return {status:'pending' as const,code:'downstream_real_evidence_pending',message:'actual evidence still required'};}};
 const now=new Date('2026-10-12T00:00:00Z');assert.equal((await runSocialWeeklyExecutionScan({dataStore:f.store,adapters:{material_readiness:adapter},now,maxTasksPerTenant:1})).blocked,1);
 const scope={store:f.store,tenantId:t.tenantId,programId:t.programId,packageId:t.packageId,packageVersion:1};assert.equal((await listWeeklySupplementExceptions(scope))[0]?.kind,'enterprise_facts');
 await f.confirm();const recovered=await runSocialWeeklyExecutionScan({dataStore:f.store,adapters:{material_readiness:adapter},now,maxTasksPerTenant:1});assert.equal(recovered.supplementRecovery.resolved,1);assert.equal(recovered.pending,1);assert.equal(executorCalls,1,'formal runtime blocks before calling downstream adapter');assert.equal((await listWeeklySupplementExceptions(scope))[0]?.status,'resolved');assert.equal((await f.store.list('starter_usage_ledger')).totalItems,0);
});
