import {createHash} from 'node:crypto';
import type {DataStore,Record_} from '../storage/datastore.js';
import type {WeeklyExecutionTask,WeeklyProductionStepKind} from '../../shared/contracts/socialProgram.js';
import type {WeeklyCreativeRepairProof} from './weeklyCreativeRepairAuthority.js';
import {socialObject,socialJson,socialRequestHash,SocialContentWorkflowError} from '../starter198/socialContentValidation.js';
import {resolveWeeklyCreativeRepairAuthority} from './weeklyCreativeRepairAuthority.js';
import {withExecutionPackageGate} from '../socialPrograms/weeklyExecutionGate.js';

export const WEEKLY_CREATIVE_REPAIR_EXECUTION_STEPS=['material_preparation','script','storyboard','material_readiness','asset_generation'] as const;
export interface WeeklyCreativeRepairExecutionLineage {schemaVersion:'weekly-creative-repair-execution-lineage.v1';caseId:string;caseRequestHash:string;configurationHash:string;authorityHash:string;childTaskId:string;childBindingKey:string;originalPublicationTaskId:string;recordHash:string}
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
const fail=(code:string):never=>{throw new SocialContentWorkflowError(code,409);};
export function readWeeklyCreativeRepairExecutionLineage(task:WeeklyExecutionTask):WeeklyCreativeRepairExecutionLineage|null{const raw=socialObject(socialJson(task.inputSnapshot?.creativeRepairExecution));if(!raw)return null;const value=raw as unknown as WeeklyCreativeRepairExecutionLineage,{recordHash,...body}=value;if(value.schemaVersion!=='weekly-creative-repair-execution-lineage.v1'||recordHash!==socialRequestHash(body)||!value.caseId||!value.childTaskId)return fail('weekly_creative_repair_execution_lineage_invalid');return value;}

export async function ensureWeeklyCreativeRepairExecutionGraph(input:{store:DataStore;tenantId:string;childTaskId:string;proof:WeeklyCreativeRepairProof;configurationHash:string;authorityHash:string;now:Date}){
 const rows=await input.store.list<Record_>('starter_social_content_tasks',{where:{tenant_id:input.tenantId,task_id:input.childTaskId},perPage:2}),child=rows.items[0];if(rows.totalItems!==1||rows.items.length!==1||!child)return fail('weekly_creative_repair_execution_child_missing');
 const authority=await resolveWeeklyCreativeRepairAuthority({store:input.store,tenantId:input.tenantId,task:child,now:input.now});if(!authority||socialRequestHash(authority.proof)!==socialRequestHash(input.proof)||authority.configuration.recordHash!==input.configurationHash||authority.proof.originalAuthorityHash!==input.authorityHash)return fail('weekly_creative_repair_execution_authority_changed');
 const lineageBody={schemaVersion:'weekly-creative-repair-execution-lineage.v1' as const,caseId:input.proof.caseId,caseRequestHash:input.proof.caseRequestHash,configurationHash:input.configurationHash,authorityHash:input.authorityHash,childTaskId:input.childTaskId,childBindingKey:authority.bindingKey,originalPublicationTaskId:input.proof.publicationTaskId},lineage={...lineageBody,recordHash:socialRequestHash(lineageBody)};
 return withExecutionPackageGate(input.store,{tenantId:input.tenantId,programId:authority.repairCase.programId,packageId:input.proof.packageId,packageVersion:input.proof.packageVersion},async assert=>{
  const existing=await input.store.list<Record_>('social_weekly_execution_tasks',{where:{tenant_id:input.tenantId,package_id:input.proof.packageId,package_version:input.proof.packageVersion},perPage:500});if(existing.totalItems!==existing.items.length)return fail('weekly_creative_repair_execution_graph_incomplete');
  const matching=existing.items.filter(row=>socialObject(socialJson(socialObject(socialJson(row.payload))?.inputSnapshot))?.creativeRepairExecution&&readWeeklyCreativeRepairExecutionLineage(socialJson(row.payload) as WeeklyExecutionTask)?.caseId===input.proof.caseId);
  if(matching.length){if(matching.length!==WEEKLY_CREATIVE_REPAIR_EXECUTION_STEPS.length)return fail('weekly_creative_repair_execution_graph_changed');for(const row of matching){const task=socialJson(row.payload) as WeeklyExecutionTask,l=readWeeklyCreativeRepairExecutionLineage(task);if(!l||l.recordHash!==lineage.recordHash||row.task_id!==task.taskId)return fail('weekly_creative_repair_execution_graph_changed');}return matching.map(row=>socialJson(row.payload) as WeeklyExecutionTask);}
  const createdAt=input.now.toISOString(),syntheticPublication=`creative-repair:${input.proof.caseId}`;let previous:string|null=null;const tasks:WeeklyExecutionTask[]=[];
  for(const [index,step] of WEEKLY_CREATIVE_REPAIR_EXECUTION_STEPS.entries()){const taskId=`wet_cr_${hash([input.tenantId,input.proof.caseId,step]).slice(0,24)}`,start=new Date(input.now.getTime()+index*60_000).toISOString(),finish=new Date(input.now.getTime()+(index+1)*60_000).toISOString();const task={tenantId:input.tenantId,programId:authority.repairCase.programId,packageId:input.proof.packageId,packageVersion:input.proof.packageVersion,taskId,workflowKind:'content' as const,scope:'content' as const,subjectId:input.childTaskId,accountId:authority.repairCase.accountId,publicationTaskId:syntheticPublication,idempotencyKey:`weekly-creative-repair-execution:${input.proof.caseId}:${step}`,title:`创意返工 · ${step}`,description:'按冻结返工权限执行真实生产前置阶段',status:'queued' as const,dependsOnTaskIds:previous?[previous]:[],upstreamVersionRefs:[],budget:{category:'production' as const,limitCny:authority.configuration.maximumCostCny},ownBlockingReasons:[],inheritedBlockingTaskIds:[],resultRefs:[],attempt:0,maxAttempts:3,lease:null,nextAttemptAt:null,lastError:null,recoveredFromDeadLetterAt:null,cancelReason:null,inputSnapshot:{creativeRepairExecution:lineage},schedule:{stepKind:step as WeeklyProductionStepKind,responsibleActor:'content_agent' as const,estimatedDurationMinutes:1,estimatedStartAt:start,estimatedFinishAt:finish,actualStartedAt:null,actualFinishedAt:null},createdAt,updatedAt:createdAt};tasks.push(task);previous=taskId;}
  for(const task of tasks){await assert();const saved=await input.store.create('social_weekly_execution_tasks',{id:task.taskId,tenant_id:task.tenantId,program_id:task.programId,package_id:task.packageId,package_version:task.packageVersion,task_id:task.taskId,workflow_kind:task.workflowKind,status:task.status,idempotency_key:task.idempotencyKey,next_attempt_at:'',payload:task,created_at:createdAt,updated_at:createdAt});if(!saved)return fail('weekly_creative_repair_execution_graph_save_failed');}
  return tasks;
 });
}
